"""Grade 9 English: Literature MCQ, Grammar, Writing/Vocab."""

def _q(prompt, options, answer, explanation, hint, skill="general", difficulty="medium"):
    return {
        "prompt": prompt,
        "options": options,
        "answer": answer,
        "explanation": explanation,
        "hint": hint,
        "skill": skill,
        "difficulty": difficulty,
    }


PASSAGE_A = (
    "Riya paused at the old library door. Dust motes swam in a shaft of late light. "
    "She had promised herself she would return the borrowed journal, yet her fingers "
    "tightened on its worn cover. Inside were her grandmother’s recipes — and a letter "
    "never sent. “Some stories,” the librarian had once said, “wait for the right reader.” "
    "Riya breathed in the smell of paper and decided the right reader might be her."
)

PASSAGE_B = (
    "The mountain path narrowed until Arjun had to turn sideways. Wind tugged at his jacket. "
    "Below, the valley looked like a crumpled green map. He checked his water bottle — half full — "
    "and thought of his sister’s dare: reach the ridge before noon. A goat watched him with calm eyes, "
    "as if it owned the cliff. Arjun laughed, surprising himself, and took the next step."
)

PASSAGE_C = (
    "In the school courtyard, Mira watered a stubborn marigold. Classmates rushed past toward the "
    "football field, their cheers rising like bright balloons. Mira’s science fair board leaned "
    "against the wall, edges curling. She had measured plant growth for six weeks. Today the judges "
    "would come. The marigold, she noticed, had opened one new petal overnight — a small, quiet vote of confidence."
)


def lit_prompt(passage: str, question: str) -> str:
    return f'Read:\n\n"{passage}"\n\n{question}'


LIT_A = [
    _q(lit_prompt(PASSAGE_A, "Why does Riya pause at the library door?"),
       ["She is lost", "She feels conflicted about returning the journal", "She is angry at the librarian", "She forgot her keys"],
       "b", "Her fingers tighten on the cover even though she promised to return it — hesitation and conflict.",
       "Find the sentence that shows her body language and promise.", "inference", "easy"),
    _q(lit_prompt(PASSAGE_A, "The dust motes in the light mainly create a sense of…"),
       ["danger", "atmosphere / mood", "humour", "anger"],
       "b", "Sensory detail sets a quiet, reflective atmosphere rather than advancing plot alone.",
       "Ask what the sensory image is doing for mood.", "tone", "easy"),
    _q(lit_prompt(PASSAGE_A, "The librarian’s line “Some stories wait for the right reader” suggests…"),
       ["books expire quickly", "meaning depends on who is ready to receive it", "librarians dislike children", "Riya should throw the letter away"],
       "b", "The quote implies timing and readiness matter for a story’s impact.",
       "Interpret the figurative claim about stories and readers.", "theme", "medium"),
    _q(lit_prompt(PASSAGE_A, "What is inside the journal besides recipes?"),
       ["A map", "A never-sent letter", "Money", "A train ticket"],
       "b", "The passage explicitly mentions a letter never sent.",
       "Scan for the dash after “recipes”.", "detail", "easy"),
    _q(lit_prompt(PASSAGE_A, "Riya’s final decision shows she…"),
       ["rejects her grandmother", "chooses to engage with the story herself", "returns the journal immediately without thought", "leaves the library forever"],
       "b", "She decides she might be the right reader — engagement, not rejection.",
       "Look at the last sentence.", "inference", "medium"),
    _q(lit_prompt(PASSAGE_A, "The phrase “worn cover” implies the journal is…"),
       ["brand new", "well used / old", "waterproof", "empty"],
       "b", "“Worn” signals long use and age.",
       "What does “worn” usually mean for objects?", "vocab", "easy"),
    _q(lit_prompt(PASSAGE_A, "Which best states a theme of the passage?"),
       ["Cooking is difficult", "Personal history can wait until someone is ready to face it", "Libraries are dusty", "Promises never matter"],
       "b", "The delayed letter and “right reader” point to readiness with family stories.",
       "Theme = big idea supported by details, not a single object.", "theme", "medium"),
    _q(lit_prompt(PASSAGE_A, "The narrator’s tone toward Riya is mainly…"),
       ["mocking", "sympathetic / gentle", "furious", "indifferent"],
       "b", "Close attention to her hesitation and sensory world feels gentle, not mocking.",
       "Tone = author’s attitude; check word choice.", "tone", "medium"),
    _q(lit_prompt(PASSAGE_B, "Why does Arjun turn sideways on the path?"),
       ["He is dancing", "The path has become very narrow", "He sees a train", "He dropped his bottle"],
       "b", "The path “narrowed until Arjun had to turn sideways.”",
       "Locate the cause in the first sentence.", "detail", "easy"),
    _q(lit_prompt(PASSAGE_B, "“The valley looked like a crumpled green map” is an example of…"),
       ["simile", "metaphor", "alliteration", "hyperbole"],
       "a", "“Like” signals a simile comparing valley to a map.",
       "Like/as → simile; is/was without like → metaphor.", "figurative", "easy"),
    _q(lit_prompt(PASSAGE_B, "Arjun’s sister’s dare mainly adds…"),
       ["a goal and motivation", "a weather report", "a villain", "a recipe"],
       "a", "The noon deadline gives purpose to the climb.",
       "What does the dare make him try to do?", "structure", "medium"),
    _q(lit_prompt(PASSAGE_B, "The goat’s calm eyes, “as if it owned the cliff,” suggest…"),
       ["the goat is dangerous", "humorous confidence / quiet mastery of the place", "Arjun should go home", "the cliff is artificial"],
       "b", "The playful personification makes the goat seem serenely in charge.",
       "Read the “as if” clause for attitude.", "inference", "medium"),
    _q(lit_prompt(PASSAGE_B, "Arjun laughs “surprising himself,” which shows…"),
       ["he is usually solemn under pressure", "he always laughs on cliffs", "he fears goats", "he finished the climb"],
       "a", "Surprise at his own laugh implies it is unusual for him in that moment.",
       "What does “surprising himself” imply about habit?", "inference", "medium"),
    _q(lit_prompt(PASSAGE_B, "Which detail shows risk without stating “danger” directly?"),
       ["Half-full water bottle", "Narrow path and wind on a cliff", "Green map", "Noon dare alone"],
       "b", "Narrow cliff path and wind imply peril through setting.",
       "Setting can imply risk.", "craft", "medium"),
    _q(lit_prompt(PASSAGE_B, "The overall mood of the climb passage is…"),
       ["tense but determined", "purely comic", "hopeless", "sleepy"],
       "a", "Wind, narrow path, and dare create tension; the laugh and next step show resolve.",
       "Combine setting + character action for mood.", "tone", "medium"),
    _q(lit_prompt(PASSAGE_B, "Arjun’s next step at the end emphasises…"),
       ["giving up", "continuing despite difficulty", "returning the goat", "reading a map"],
       "b", "After laughing, he takes the next step — persistence.",
       "Endings often crystallise the character’s choice.", "inference", "easy"),
    _q(lit_prompt(PASSAGE_C, "Mira’s marigold is called “stubborn,” which suggests…",),
       ["it grows easily", "it has been hard to keep going", "it is artificial", "judges dislike flowers"],
       "b", "“Stubborn” personifies difficulty in the plant’s survival/growth.",
       "Personifying adjectives reveal struggle.", "vocab", "easy"),
    _q(lit_prompt(PASSAGE_C, "“Cheers rising like bright balloons” is…"),
       ["metaphor", "simile", "irony", "pun"],
       "b", "“Like” compares cheers to balloons — simile.",
       "Spot like/as.", "figurative", "easy"),
    _q(lit_prompt(PASSAGE_C, "Why do the curling edges of Mira’s board matter?"),
       ["They prove she cheated", "They hint at nervousness / imperfect preparation under pressure", "They show rain inside", "They are unrelated decoration"],
       "b", "Curling edges are a small imperfect detail that humanises her stress.",
       "Physical details can mirror emotion.", "inference", "medium"),
    _q(lit_prompt(PASSAGE_C, "The new petal is described as “a small, quiet vote of confidence.” This is mainly…"),
       ["literal election news", "figurative encouragement from the plant’s progress", "a judge’s scorecard", "a football chant"],
       "b", "The plant cannot vote; the image figuratively reassures Mira.",
       "Non-literal “vote” = figurative meaning.", "figurative", "medium"),
    _q(lit_prompt(PASSAGE_C, "Contrast between Mira and her classmates highlights…"),
       ["she prefers quiet, patient work to the noisy rush of the field", "she hates sports", "nobody likes science", "the courtyard is empty"],
       "a", "They rush to football; she tends a plant and a project — different energies.",
       "Contrast reveals character priorities.", "structure", "medium"),
    _q(lit_prompt(PASSAGE_C, "Six weeks of measuring plant growth shows Mira is…"),
       ["impatient", "persistent and methodical", "uninterested", "afraid of judges"],
       "b", "Long, careful measurement signals persistence.",
       "Time invested = trait clue.", "inference", "easy"),
    _q(lit_prompt(PASSAGE_C, "A reasonable theme is…"),
       ["Quiet dedication can be its own kind of courage", "Football is better than science", "Flowers never bloom", "Judges are always unfair"],
       "a", "Her steady care and the petal’s “vote” support quiet courage.",
       "Theme must fit the whole passage.", "theme", "medium"),
    _q(lit_prompt(PASSAGE_C, "The author’s purpose is mainly to…"),
       ["list science fair rules", "portray a character’s quiet resolve before judgment", "teach photosynthesis formulas", "advertise football"],
       "b", "Narrative focus is Mira’s feelings and resolve, not a rulebook.",
       "Purpose follows what the text spends energy on.", "purpose", "medium"),
]

# Fix typo in one prompt that has trailing comma inside lit_prompt call - actually looking at the code:
# _q(lit_prompt(PASSAGE_C, "Mira’s marigold is called “stubborn,” which suggests…"),
# that's fine - the trailing comma after suggests…" is inside the string... wait I have:
# lit_prompt(PASSAGE_C, "Mira’s marigold is called “stubborn,” which suggests…"),
# with an extra ) - let me check: `_q(lit_prompt(PASSAGE_C, "Mira’s marigold is called “stubborn,” which suggests…"),` 
# There's `…"),`  then next line options - but I wrote `…",),` with an errant comma before closing paren of lit_prompt!

LIT_A = [q for q in LIT_A]  # placeholder; fix below in loop

LIT_B = [
    _q(lit_prompt(PASSAGE_A, "Which sensory detail appears in the library scene?"),
       ["The smell of paper", "The taste of salt", "A siren", "Falling snow"],
       "a", "Riya “breathed in the smell of paper.”",
       "Scan for senses: sight, smell, touch.", "detail", "easy"),
    _q(lit_prompt(PASSAGE_A, "The journal mainly symbolises…"),
       ["forgotten family connection / unfinished communication", "a school textbook", "money problems", "a sports trophy"],
       "a", "Recipes plus an unsent letter point to family memory and unfinished words.",
       "Symbols carry meaning beyond the object.", "theme", "hard"),
    _q(lit_prompt(PASSAGE_A, "Riya’s tightened fingers are an example of…"),
       ["showing emotion through action (show, don’t tell)", "a simile", "direct definition of fear", "comic relief"],
       "a", "Body language shows conflict without naming it.",
       "Action revealing feeling = show, don’t tell.", "craft", "medium"),
    _q(lit_prompt(PASSAGE_A, "“Late light” most nearly suggests…"),
       ["early morning", "end of day / fading afternoon", "midnight", "neon signs"],
       "b", "Late light implies late day.",
       "Read the adjective “late.”", "vocab", "easy"),
    _q(lit_prompt(PASSAGE_A, "The passage is written in…"),
       ["first person (“I”)", "second person (“you”)", "third person limited around Riya", "only dialogue"],
       "c", "Narration follows Riya’s actions and thoughts from outside using “she.”",
       "Check pronouns.", "structure", "medium"),
    _q(lit_prompt(PASSAGE_A, "Which inference is best supported?"),
       ["Riya has never met her grandmother", "The letter may matter emotionally to Riya’s family story", "The librarian stole the journal", "The library is closing forever"],
       "b", "An unsent letter kept with recipes implies emotional weight.",
       "Stick to what the text supports.", "inference", "medium"),
    _q(lit_prompt(PASSAGE_B, "The crumpled green map image primarily helps the reader…"),
       ["see the valley’s textured distance from above", "learn cartography", "meet Arjun’s sister", "count goats"],
       "a", "The simile makes the view vivid from the height of the path.",
       "Ask what the image lets you picture.", "figurative", "medium"),
    _q(lit_prompt(PASSAGE_B, "Half-full water is a detail that…"),
       ["proves he will fail", "quietly marks limited resources on the climb", "means he just started", "is only about thirst advertising"],
       "b", "It notes constraint without melodrama.",
       "Small props can signal stakes.", "craft", "medium"),
    _q(lit_prompt(PASSAGE_B, "Arjun’s laugh functions as…"),
       ["a release of tension", "proof he quit", "anger at the goat", "the noon signal"],
       "a", "Laughing on a hard path suggests tension easing into courage.",
       "How does the laugh change the moment?", "inference", "medium"),
    _q(lit_prompt(PASSAGE_B, "The dare to reach the ridge before noon is an example of…"),
       ["external motivation / goal", "flashback", "metaphor for sleep", "alliteration"],
       "a", "A time-bound challenge from someone else drives action.",
       "Goals can be external (others) or internal.", "structure", "easy"),
    _q(lit_prompt(PASSAGE_B, "Which word best describes the goat’s role?"),
       ["antagonist villain", "brief comic witness", "narrator", "mapmaker"],
       "b", "The calm, “owning” goat adds a wry beat, not a true villain arc.",
       "How long and how seriously is the goat treated?", "structure", "medium"),
    _q(lit_prompt(PASSAGE_B, "“Wind tugged at his jacket” personifies the wind by…"),
       ["giving it a human-like action (tugging)", "measuring speed", "naming a storm", "using a simile with “like”"],
       "a", "Wind cannot literally tug as a person does; the verb personifies it.",
       "Personification = human action on non-human.", "figurative", "easy"),
    _q(lit_prompt(PASSAGE_C, "Mira’s project duration (six weeks) contrasts with…"),
       ["the classmates’ momentary rush to the field", "the judges’ absence", "the marigold’s colour only", "a football rulebook"],
       "a", "Long patience vs. quick rush sharpens character contrast.",
       "Find the opposing energy in the courtyard.", "structure", "medium"),
    _q(lit_prompt(PASSAGE_C, "The curling board edges mainly make Mira seem…"),
       ["perfectly polished", "human and a little vulnerable", "dishonest", "finished years ago"],
       "b", "Imperfection under pressure invites empathy.",
       "Imperfect props humanise characters.", "inference", "easy"),
    _q(lit_prompt(PASSAGE_C, "Calling cheers “bright balloons” appeals mainly to…"),
       ["sound transformed into a visual image", "taste", "touch of rubber only", "smell"],
       "a", "Sound (cheers) is pictured as bright rising balloons — synesthetic-ish imagery.",
       "Which sense does the image emphasise?", "figurative", "hard"),
    _q(lit_prompt(PASSAGE_C, "The marigold’s new petal overnight suggests…"),
       ["failure of the experiment", "incremental progress worth noticing", "judges cancelled", "Mira stopped watering"],
       "b", "One new petal is small growth — progress.",
       "Overnight change = small win.", "inference", "easy"),
    _q(lit_prompt(PASSAGE_C, "Mira’s attitude is best described as…"),
       ["quietly hopeful", "boastful", "furious", "indifferent"],
       "a", "Careful work plus reading the petal as confidence shows quiet hope.",
       "Match actions to attitude words.", "tone", "medium"),
    _q(lit_prompt(PASSAGE_C, "Which title best fits the Mira passage?"),
       ["The Loudest Cheer", "A Quiet Petal Before the Judges", "Football Rules", "How to Build a Board Overnight"],
       "b", "It centres the soft plant image and the coming judgment.",
       "Titles should reflect focus and tone.", "theme", "medium"),
    _q(lit_prompt(PASSAGE_A, "The word “motes” in “dust motes” most nearly means…"),
       ["large stones", "tiny particles", "books", "windows"],
       "b", "Dust motes are tiny floating particles.",
       "Use context: dust + swimming in light.", "vocab", "easy"),
    _q(lit_prompt(PASSAGE_B, "The phrase “crumpled green map” emphasises the valley’s…"),
       ["smooth flatness", "folded, uneven green expanse from above", "exact road names", "lack of colour"],
       "b", "Crumpled suggests uneven folds; green paints vegetation.",
       "Unpack each adjective in the image.", "figurative", "medium"),
    _q(lit_prompt(PASSAGE_C, "The science fair board “leaned against the wall” suggests Mira is…"),
       ["still waiting / not yet presenting", "already gone home", "playing football", "hiding the board forever"],
       "a", "It waits with her — not yet in front of judges.",
       "Props’ positions can show timing.", "inference", "easy"),
    _q(lit_prompt(PASSAGE_A, "Which claim is NOT supported by the text?"),
       ["Riya holds a journal with family material", "A librarian once spoke about stories and readers", "Riya’s grandmother emailed her that morning", "Riya notices the smell of paper"],
       "c", "No email is mentioned; the letter is unsent and in the journal.",
       "Eliminate what the passage never says.", "detail", "medium"),
    _q(lit_prompt(PASSAGE_B, "Arjun’s water bottle being half full is an example of…"),
       ["foreshadowing certain death", "a concrete detail that grounds the scene", "a metaphor for maps", "hyperbole"],
       "b", "It is a literal, grounding detail (not certain doom).",
       "Not every detail is heavy symbolism.", "craft", "medium"),
    _q(lit_prompt(PASSAGE_C, "The passage invites the reader to value…"),
       ["patience and careful observation", "only winning trophies", "ignoring plants", "rushing always"],
       "a", "Six weeks of data and noticing one petal celebrate patience.",
       "What does the author linger on with care?", "theme", "easy"),
]

# Fix the stubborn marigold question if broken
for i, q in enumerate(LIT_A):
    if "stubborn" in q["prompt"] and "suggests" in q["prompt"]:
        LIT_A[i] = _q(
            lit_prompt(PASSAGE_C, "Mira’s marigold is called “stubborn,” which suggests…"),
            ["it grows easily", "it has been hard to keep going", "it is artificial", "judges dislike flowers"],
            "b",
            "“Stubborn” personifies difficulty in the plant’s survival/growth.",
            "Personifying adjectives reveal struggle.",
            "vocab",
            "easy",
        )


GRAM_A = [
    _q("Choose the correct sentence.",
       ["She don’t like tea.", "She doesn’t like tea.", "She doesn’t likes tea.", "She not like tea."],
       "b", "Third-person singular needs doesn’t + base verb.",
       "Match subject and auxiliary.", "agreement", "easy"),
    _q("Fill in: By next June, we ____ here for ten years.",
       ["will live", "will have lived", "lived", "are living"],
       "b", "Future perfect marks duration completed by a future point.",
       "“By + future time” often needs future perfect.", "tense", "medium"),
    _q("Change to passive: “The chef cooked the meal.”",
       ["The meal cooked the chef.", "The meal was cooked by the chef.", "The meal is cooking the chef.", "The chef was cooked the meal."],
       "b", "Object becomes subject; past simple → was/were + past participle.",
       "Keep the tense; move the object forward.", "voice", "easy"),
    _q("Reported speech: He said, “I am tired.” → He said that he ____ tired.",
       ["is", "was", "will be", "were being"],
       "b", "Backshift present to past after a past reporting verb.",
       "Am/is → was in reported speech.", "reported", "easy"),
    _q("Choose the correct article: She is ____ honest person.",
       ["a", "an", "the", "no article"],
       "b", "Honest begins with a vowel sound → an.",
       "Use sound, not just spelling.", "articles", "easy"),
    _q("Identify the error: “Neither of the answers are correct.”",
       ["Neither", "of the answers", "are → should be is", "correct"],
       "c", "Neither is singular → is.",
       "Neither/either take singular verbs.", "agreement", "medium"),
    _q("Modal: You ____ wear a helmet on this site. (strong obligation)",
       ["might", "must", "could", "may"],
       "b", "Must expresses strong obligation.",
       "Match modal strength to meaning.", "modals", "easy"),
    _q("Choose the correct verb: The news ____ surprising.",
       ["are", "is", "were", "have"],
       "b", "News is singular in standard English → is.",
       "Some plural-looking nouns are singular.", "agreement", "medium"),
    _q("Fill in: If it rains, we ____ indoors.",
       ["stay", "stayed", "would stayed", "had stayed"],
       "a", "First conditional: If + present, will/can/other present forms; “stay” fits as a present/instructional result (or “will stay”). Among options, stay is correct.",
       "First conditional uses present in the if-clause.", "conditional", "medium"),
    _q("Pick the correctly punctuated sentence.",
       ["Lets go, its late.", "Let’s go; it’s late.", "Lets go; its’ late.", "Let’s go its late."],
       "b", "Let’s = let us; it’s = it is; semicolon joins related clauses.",
       "Check apostrophes in let’s/it’s.", "punctuation", "easy"),
    _q("Voice: “A song was sung by the choir” is…",
       ["active voice", "passive voice", "imperative", "interrogative"],
       "b", "Was sung + by-phrase marks passive.",
       "Look for be + past participle.", "voice", "easy"),
    _q("Choose: She has been working here ____ 2019.",
       ["for", "since", "from", "at"],
       "b", "Since + starting point; for + duration.",
       "2019 is a point in time → since.", "preposition", "easy"),
    _q("Reported: “Where do you live?” she asked me. → She asked me where I ____.",
       ["live", "lived", "do live", "am living yesterday"],
       "b", "Wh-question becomes statement order with backshift: lived.",
       "No question word order after asked.", "reported", "medium"),
    _q("Select the correct comparative: This puzzle is ____ than that one.",
       ["more easier", "easier", "easyer", "most easy"],
       "b", "Easier is the correct comparative; avoid double comparative.",
       "Don’t stack more + -er.", "degrees", "easy"),
    _q("Identify the clause type: “when the bell rang” in “We left when the bell rang.”",
       ["noun clause", "adjective clause", "adverb clause of time", "main clause"],
       "c", "It modifies left by telling when — adverbial time clause.",
       "Ask what question the clause answers.", "clauses", "medium"),
    _q("Fill: Neither Ravi nor his friends ____ ready.",
       ["is", "are", "was", "has"],
       "b", "With neither…nor, the verb agrees with the nearer subject (friends → are).",
       "Proximity rule for neither…nor.", "agreement", "hard"),
    _q("Choose correct: I look forward to ____ you.",
       ["meet", "meeting", "met", "meets"],
       "b", "Look forward to + gerund.",
       "Here “to” is a preposition, not infinitive marker.", "verb-pattern", "medium"),
    _q("Passive of “People speak English here.”",
       ["English is spoken here.", "English spoken here people.", "English was speak here.", "English are spoken here."],
       "a", "Present simple passive: is/are + past participle; English is singular mass → is spoken.",
       "Drop the generic people; keep tense.", "voice", "easy"),
    _q("Choose the right determiner: ____ of the milk was spilled.",
       ["Many", "Much", "Few", "Several"],
       "b", "Milk is uncountable → much.",
       "Uncountable nouns take much/little, not many/few.", "determiners", "easy"),
    _q("Error spot: “He suggested to go home.” Correct form uses…",
       ["suggested to go", "suggested going", "suggested go", "suggested gone"],
       "b", "Suggest + gerund (or that-clause), not to-infinitive.",
       "Remember verb patterns after suggest.", "verb-pattern", "medium"),
    _q("Choose: She ____ finished the novel before the exam started.",
       ["has", "had", "have", "having"],
       "b", "Past perfect for earlier past before another past.",
       "Two past times → earlier one uses had + past participle.", "tense", "medium"),
    _q("Which sentence uses a non-defining relative clause correctly?",
       ["My brother who lives in Pune is a doctor. (only one brother, commas needed)", "My brother, who lives in Pune, is a doctor.", "My brother, that lives in Pune, is a doctor.", "My brother which lives in Pune is a doctor."],
       "b", "Non-defining clauses take commas; that is not used in non-defining clauses; who for people.",
       "Commas mark extra information.", "relative", "hard"),
    _q("Fill: It’s time we ____ home.",
       ["go", "went", "gone", "going"],
       "b", "It’s time + past tense form (unreal present).",
       "Idiomatic: It’s time we went…", "tense", "hard"),
    _q("Choose correct preposition: She is good ____ mathematics.",
       ["in", "at", "on", "by"],
       "b", "Good at + subject/skill.",
       "Collocation: good at.", "preposition", "easy"),
]

GRAM_B = [
    _q("Choose: The team ____ winning after half-time.",
       ["was", "were", "are", "be"],
       "a", "Team as a single unit often takes singular was (especially in Indian exam English).",
       "Collective noun as one unit → singular.", "agreement", "medium"),
    _q("Active form of “The window was broken by the storm.”",
       ["The storm broke the window.", "The storm was broken the window.", "The window broke the storm.", "The storm broken window."],
       "a", "Restore the agent as subject; past simple active: broke.",
       "Undo passive: agent + past verb + object.", "voice", "easy"),
    _q("Reported: She said, “I will call tomorrow.” → She said she ____ call the next day.",
       ["will", "would", "shall", "can"],
       "b", "Will → would; tomorrow → the next day.",
       "Backshift modals in reported speech.", "reported", "easy"),
    _q("Fill: He has lived here ____ five years.",
       ["since", "for", "from", "during"],
       "a", "Wait — five years is duration → for. Fix.",
       "Duration → for; starting point → since.", "preposition", "easy"),
    _q("Choose the correct question tag: You’re ready, ____?",
       ["are you", "aren’t you", "isn’t you", "don’t you"],
       "b", "Positive statement → negative tag: aren’t you.",
       "Opposite polarity in tags.", "tags", "easy"),
    _q("Identify tense: “She had been waiting for an hour when the bus arrived.”",
       ["past perfect continuous", "present perfect", "simple past", "future perfect"],
       "a", "Had been + -ing marks past perfect continuous.",
       "Had been + verb-ing.", "tense", "medium"),
    _q("Choose: Hardly had we entered ____ it started raining.",
       ["when", "than", "then", "that"],
       "a", "Hardly…when is the correlative pair.",
       "Hardly/scarcely → when; no sooner → than.", "connectors", "hard"),
    _q("Correct the adjective order: “a leather black new bag” →",
       ["a new black leather bag", "a black new leather bag", "a leather new black bag", "a new leather black bag"],
       "a", "Typical order: opinion/age → colour → material.",
       "Age/colour/material sequence.", "adjectives", "hard"),
    _q("Fill: Prefer tea ____ coffee.",
       ["than", "to", "from", "over than"],
       "b", "Prefer A to B.",
       "Prefer collocates with to.", "preposition", "easy"),
    _q("Which is a complex sentence?",
       ["I came and I saw.", "I came.", "I came when you called.", "Come here."],
       "c", "One independent + one dependent clause (when…).",
       "Complex = subordinating conjunction joining clauses.", "sentences", "medium"),
    _q("Choose: Each of the players ____ a medal.",
       ["receive", "receives", "have received yesterday only as plural", "are receiving always"],
       "b", "Each is singular → receives.",
       "Each/every → singular verb.", "agreement", "easy"),
    _q("Passive: “They are repairing the road.”",
       ["The road is being repaired.", "The road is repaired them.", "The road was being repair.", "The road repairs."],
       "a", "Present continuous passive: is/are being + past participle.",
       "Continuous passive needs being.", "voice", "medium"),
    _q("Choose synonym of the underlined idea: He was reluctant to speak. He was…",
       ["eager", "unwilling", "loud", "certain"],
       "b", "Reluctant means unwilling/hesitant.",
       "Reluctant ≈ not willing.", "vocab", "easy"),
    _q("Fill: She insisted ____ paying the bill.",
       ["to", "on", "for", "at"],
       "b", "Insist on + gerund/noun.",
       "Insist on…", "preposition", "medium"),
    _q("Reported command: “Close the door,” he said to me. → He told me ____ the door.",
       ["close", "to close", "closing", "closed"],
       "b", "Told + object + to-infinitive.",
       "Commands become to-infinitives.", "reported", "easy"),
    _q("Choose correct: Between you and ____, this is secret.",
       ["I", "me", "myself", "mine"],
       "b", "Object of preposition between → me.",
       "After prepositions use object pronouns.", "pronouns", "medium"),
    _q("Which sentence is in the present perfect?",
       ["She wrote a letter.", "She has written a letter.", "She had written a letter.", "She writes a letter."],
       "b", "Has/have + past participle = present perfect.",
       "Spot has/have + V3.", "tense", "easy"),
    _q("Error: “One of my friend is a pilot.” Correction:",
       ["One of my friends is a pilot.", "One of my friend are a pilot.", "One of my friends are a pilot.", "One my friends is a pilot."],
       "a", "One of + plural noun + singular verb.",
       "One of → plural noun, singular verb.", "agreement", "medium"),
    _q("Fill: No sooner had she left ____ the phone rang.",
       ["when", "than", "then", "but"],
       "b", "No sooner…than.",
       "Correlative: no sooner / than.", "connectors", "medium"),
    _q("Choose: The man ____ house we bought is a doctor. (relative)",
       ["who", "whom", "whose", "which"],
       "c", "Whose shows possession (man’s house).",
       "Possession → whose.", "relative", "easy"),
    _q("Conditional: If I ____ you, I would apologise.",
       ["am", "was", "were", "will be"],
       "c", "Second conditional often uses were for all persons (subjunctive).",
       "If I were you…", "conditional", "medium"),
    _q("Choose correct spelling in context: Their house is over ____.",
       ["their", "there", "they’re", "thar"],
       "b", "There indicates place.",
       "There/their/they’re confusion.", "confusables", "easy"),
    _q("Identify the infinitive: “She hopes to win.”",
       ["hopes", "to win", "she", "win as bare only"],
       "b", "To win is the to-infinitive.",
       "To + base verb.", "verb-pattern", "easy"),
    _q("Choose: Seldom ____ such courage.",
       ["we have seen", "have we seen", "we saw have", "seen we have"],
       "b", "Negative adverb fronting triggers inversion: have we seen.",
       "Seldom/never at front → invert auxiliary.", "inversion", "hard"),
]

# Fix GRAM_B for/since question
for i, q in enumerate(GRAM_B):
    if "five years" in q["prompt"]:
        GRAM_B[i] = _q(
            "Fill: He has lived here ____ five years.",
            ["since", "for", "from", "during"],
            "b",
            "Five years is a duration, so use for. Since takes a starting point.",
            "Duration → for; starting point → since.",
            "preposition",
            "easy",
        )
        break

# Soften awkward option text in GRAM_B each of players
for i, q in enumerate(GRAM_B):
    if "Each of the players" in q["prompt"]:
        GRAM_B[i] = _q(
            "Choose: Each of the players ____ a medal.",
            ["receive", "receives", "have received", "are receiving"],
            "b",
            "Each is singular → receives.",
            "Each/every → singular verb.",
            "agreement",
            "easy",
        )
        break


WORDS_A = [
    _q("Choose the synonym of “brief”.",
       ["lengthy", "concise", "noisy", "ancient"],
       "b", "Brief means short/concise.",
       "Synonym = closest meaning.", "synonym", "easy"),
    _q("Antonym of “scarce” is…",
       ["rare", "abundant", "tiny", "hidden"],
       "b", "Scarce ↔ abundant/plentiful.",
       "Antonym = opposite.", "antonym", "easy"),
    _q("Choose the correct word: The ____ of the school spoke to parents.",
       ["principle", "principal", "premier", "principle’s"],
       "b", "Principal = head of school; principle = rule/belief.",
       "Principal vs principle.", "confusable", "easy"),
    _q("Idiom: “break the ice” means…",
       ["shatter glass", "start conversation in a friendly way", "cancel a match", "freeze water"],
       "b", "It means ease social tension / begin chatting.",
       "Idioms are not literal.", "idiom", "easy"),
    _q("One-word substitute: A person who loves books.",
       ["bibliophile", "philanthropist", "sceptic", "optimist"],
       "a", "Bibliophile = book lover.",
       "Biblio- relates to books.", "oneword", "medium"),
    _q("Choose: The storm will ____ our picnic plans.",
       ["effect", "affect", "affection", "effective"],
       "b", "Affect (verb) = influence; effect (noun) = result.",
       "Affect vs effect.", "confusable", "easy"),
    _q("Synonym of “diligent”…",
       ["lazy", "hardworking", "rude", "noisy"],
       "b", "Diligent means careful and hardworking.",
       "Closest meaning.", "synonym", "easy"),
    _q("Antonym of “optimistic”…",
       ["hopeful", "cheerful", "pessimistic", "eager"],
       "c", "Optimistic ↔ pessimistic.",
       "Opposite attitude about the future.", "antonym", "easy"),
    _q("Phrasal verb: “call off” means…",
       ["phone someone", "cancel", "shout loudly", "visit briefly"],
       "b", "Call off = cancel.",
       "Use context of events/matches.", "phrasal", "easy"),
    _q("Choose formal option for a notice heading style:",
       ["hey guys picnic!!!", "NOTICE", "yo read this", "sup"],
       "b", "School notices use a clear formal heading such as NOTICE.",
       "Match register to format.", "format", "easy"),
    _q("Word meaning “capable of being heard”…",
       ["edible", "audible", "visible", "legible"],
       "b", "Audible = can be heard.",
       "Audio → hear.", "oneword", "easy"),
    _q("Choose correctly: stationery vs stationary — “The bus was ____ in traffic.”",
       ["stationery", "stationary", "stationerly", "stationory"],
       "b", "Stationary = not moving; stationery = writing materials.",
       "Car/bus → stationary.", "confusable", "easy"),
    _q("Idiom: “once in a blue moon” means…",
       ["very often", "very rarely", "at night only", "during exams"],
       "b", "It means very rarely.",
       "Blue moon idiom = rarity.", "idiom", "easy"),
    _q("Synonym of “fragile”…",
       ["sturdy", "delicate", "heavy", "loud"],
       "b", "Fragile = easily broken; delicate.",
       "Closest meaning.", "synonym", "easy"),
    _q("Antonym of “expand”…",
       ["enlarge", "contract", "grow", "spread"],
       "b", "Expand ↔ contract/shrink.",
       "Opposite of grow larger.", "antonym", "easy"),
    _q("Choose the best word: A ____ speech bored the audience.",
       ["concise", "tedious", "vivid", "witty"],
       "b", "Tedious = long and boring.",
       "Bored → tedious.", "vocab", "medium"),
    _q("One-word: Government by the people…",
       ["monarchy", "democracy", "autocracy", "bureaucracy"],
       "b", "Democracy = rule by the people.",
       "Demos = people.", "oneword", "easy"),
    _q("Phrasal: “look into” means…",
       ["stare at a mirror only", "investigate", "ignore", "memorise"],
       "b", "Look into = investigate.",
       "Into suggests examining.", "phrasal", "easy"),
    _q("Choose for a formal email opening to an unknown reader:",
       ["Hey!", "Dear Sir or Madam,", "Yo,", "What’s up,"],
       "b", "Unknown recipient → Dear Sir or Madam.",
       "Formal register openings.", "format", "easy"),
    _q("Confusable: “accept” vs “except” — “All ____ Rohan were present.”",
       ["accept", "except", "expect", "access"],
       "b", "Except = leaving out; accept = receive/agree.",
       "Leaving someone out → except.", "confusable", "easy"),
    _q("Synonym of “courageous”…",
       ["timid", "brave", "silent", "clever"],
       "b", "Courageous ≈ brave.",
       "Closest meaning.", "synonym", "easy"),
    _q("Idiom: “spill the beans” means…",
       ["cook dinner", "reveal a secret", "plant seeds", "cry loudly"],
       "b", "Spill the beans = tell a secret.",
       "Non-literal meaning.", "idiom", "easy"),
    _q("Choose precise word: The ____ of the mountain was covered with snow.",
       ["peek", "peak", "pique", "peel"],
       "b", "Peak = top of a mountain.",
       "Peak/peek/pique trio.", "confusable", "medium"),
    _q("One-word: A person who travels to work daily…",
       ["tourist", "commuter", "pilgrim", "nomad"],
       "b", "Commuter travels regularly to work.",
       "Daily work travel = commute.", "oneword", "medium"),
]

WORDS_B = [
    _q("Antonym of “ancient”…",
       ["old", "modern", "historic", "aged"],
       "b", "Ancient ↔ modern/new.",
       "Opposite in time.", "antonym", "easy"),
    _q("Synonym of “precise”…",
       ["vague", "exact", "rough", "random"],
       "b", "Precise = exact/accurate.",
       "Closest meaning.", "synonym", "easy"),
    _q("Idiom: “hit the nail on the head” means…",
       ["do carpentry", "describe something exactly right", "fail a test", "sleep early"],
       "b", "It means be exactly correct.",
       "Non-literal success of accuracy.", "idiom", "medium"),
    _q("Confusable: “complement” vs “compliment” — “Her scarf was a perfect ____ to the dress.”",
       ["compliment", "complement", "compliance", "complex"],
       "b", "Complement = completes/goes well with; compliment = praise.",
       "Goes-with → complement.", "confusable", "medium"),
    _q("Phrasal: “put off” means…",
       ["wear clothes", "postpone", "extinguish", "publish"],
       "b", "Put off = postpone/delay.",
       "Off can suggest pushing away in time.", "phrasal", "easy"),
    _q("One-word: Incapable of being read…",
       ["illegible", "illegal", "illogical", "eligible"],
       "a", "Illegible = unreadable handwriting/text.",
       "Legible = readable; il- negates.", "oneword", "medium"),
    _q("Choose formal closing when the reader’s name is unknown:",
       ["Yours sincerely", "Yours faithfully", "See ya", "Love"],
       "b", "Unknown name → Yours faithfully (with Dear Sir/Madam).",
       "Faithfully vs sincerely rule.", "format", "medium"),
    _q("Synonym of “reluctant”…",
       ["eager", "unwilling", "joyful", "swift"],
       "b", "Reluctant = unwilling/hesitant.",
       "Closest meaning.", "synonym", "easy"),
    _q("Antonym of “generous”…",
       ["kind", "stingy", "helpful", "noble"],
       "b", "Generous ↔ stingy/miserly.",
       "Opposite with money/help.", "antonym", "easy"),
    _q("Choose: The doctor prescribed a ____ for the infection.",
       ["council", "counsel", "course? Wait", "capsule only"],
       "a", "Need a better item — rewrite.",
       "Fix.", "confusable", "easy"),
    _q("Idiom: “cost an arm and a leg” means…",
       ["be very expensive", "require surgery", "be free", "be light"],
       "a", "It means very costly.",
       "Body-part idioms for price.", "idiom", "easy"),
    _q("Word for “a period of ten years”…",
       ["decade", "century", "millennium", "fortnight"],
       "a", "Decade = 10 years.",
       "Century = 100; millennium = 1000.", "oneword", "easy"),
    _q("Phrasal: “give up” means…",
       ["donate upward", "quit / stop trying", "raise a hand", "start again"],
       "b", "Give up = quit.",
       "Common phrasal for quitting.", "phrasal", "easy"),
    _q("Confusable: “advice” vs “advise” — “Please ____ me on this choice.”",
       ["advice", "advise", "advicing", "advisory as verb"],
       "b", "Advise = verb; advice = noun.",
       "Verb form needed after Please.", "confusable", "easy"),
    _q("Choose the most precise word: The witness gave a ____ account of the event.",
       ["blurry", "vivid", "mute", "lazy"],
       "b", "Vivid = clear and detailed.",
       "Account quality → vivid.", "vocab", "medium"),
    _q("Antonym of “scarce” already practised; antonym of “victory”…",
       ["triumph", "defeat", "medal", "cheer"],
       "b", "Victory ↔ defeat.",
       "Opposite result.", "antonym", "easy"),
    _q("One-word: A signature style of a writer…",
       ["autograph only", "diction / idiom? Better: idiolect is advanced — use “style”? Rewrite", "pen name", "biography"],
       "c", "Rewrite this item properly.",
       "Fix.", "oneword", "medium"),
    _q("Formal notice body should usually include…",
       ["only emojis", "purpose, date/time/place, and who to contact", "a poem only", "slang greetings"],
       "b", "Notices need clear purpose and logistics.",
       "What must a reader act on?", "format", "easy"),
    _q("Synonym of “abandon”…",
       ["keep", "desert / leave", "build", "polish"],
       "b", "Abandon = leave behind.",
       "Closest meaning.", "synonym", "easy"),
    _q("Idiom: “on cloud nine” means…",
       ["very happy", "lost in fog", "asleep", "angry"],
       "a", "On cloud nine = extremely happy.",
       "Mood idiom.", "idiom", "easy"),
    _q("Choose: Their ideas ____ each other well.",
       ["compliment", "complement", "comply", "complicate always"],
       "b", "Complement = go well together.",
       "Ideas fitting → complement.", "confusable", "medium"),
    _q("Phrasal: “turn down” can mean…",
       ["increase volume only", "reject an offer", "stand up", "wake up"],
       "b", "Turn down = reject (also lower volume, but reject fits options).",
       "Context of offers/jobs.", "phrasal", "medium"),
    _q("One-word: Happening every year…",
       ["annual", "manual", "casual", "neutral"],
       "a", "Annual = yearly.",
       "Annus = year.", "oneword", "easy"),
    _q("Best subject line for a school email requesting leave:",
       ["sup", "Request for leave — [dates] — [name]", "!!!!!!", "see attached meme"],
       "b", "Clear, formal, informative subject lines help readers.",
       "Subject lines should state purpose.", "format", "easy"),
]

# Fix broken WORDS_B items
for i, q in enumerate(WORDS_B):
    if "doctor prescribed" in q["prompt"]:
        WORDS_B[i] = _q(
            "Confusable: “council” vs “counsel” — “She sought legal ____.”",
            ["council", "counsel", "cancel", "console"],
            "b",
            "Counsel = advice; council = a group of people.",
            "Advice → counsel.",
            "confusable",
            "medium",
        )
    if "signature style of a writer" in q["prompt"]:
        WORDS_B[i] = _q(
            "One-word: A fictitious name used by a writer…",
            ["biography", "autograph", "pseudonym", "manuscript"],
            "c",
            "Pseudonym = pen name / fictitious name.",
            "Pseudo- means false/fake name.",
            "oneword",
            "medium",
        )
    if q["options"] and "desert / leave" in q["options"]:
        WORDS_B[i] = _q(
            "Synonym of “abandon”…",
            ["keep", "leave", "build", "polish"],
            "b",
            "Abandon means leave behind / give up.",
            "Closest meaning.",
            "synonym",
            "easy",
        )
    if "complicate always" in q.get("options", []):
        WORDS_B[i] = _q(
            "Choose: Their ideas ____ each other well.",
            ["compliment", "complement", "comply", "complicate"],
            "b",
            "Complement means go well together.",
            "Ideas fitting → complement.",
            "confusable",
            "medium",
        )


CHAPTERS = [
    {
        "file": "g9-english-literature.ts",
        "export": "g9EnglishLiterature",
        "prefix": "g9-eng-ch01",
        "doc": "english-ch01-literature.md",
        "meta": {
            "id": "literature-mcq",
            "title": "Literature MCQ",
            "emoji": "📖",
            "blurb": "Theme, tone, inference & craft",
            "topic": "comprehension",
            "paperTopics": ["comprehension", "vocabulary"],
        },
        "lesson": {
            "emoji": "📖",
            "title": "Read like a critic",
            "body": [
                "Plot is the surface; theme, tone and craft sit underneath.",
                "Every answer should point back to a line in the passage.",
            ],
            "speak": "Today we practise literature multiple choice with evidence.",
            "visual": "sentence",
            "cards": [
                ("Theme", "Big idea built from evidence", "💡"),
                ("Tone", "Writer’s attitude in word choice", "🎚️"),
                ("Inference", "Logical reading between the lines", "🔎"),
                ("Figurative language", "Simile, metaphor, personification", "✨"),
            ],
            "demo": {
                "title": "Evidence first",
                "speak": "Read the question, scan for a matching line, then choose.",
                "steps": ["Read the question stem", "Underline a key phrase in the passage", "Eliminate options the text does not support", "Pick the best-supported answer"],
                "punchline": "Evidence beats guesswork.",
            },
            "try": {
                "prompt": "“Her smile was a lighthouse.” This is a…",
                "options": [("a", "simile"), ("b", "metaphor"), ("c", "alliteration"), ("d", "irony")],
                "answerId": "b",
                "why": "Was (without like/as) signals metaphor.",
            },
            "wrap_title": "Evidence reader!",
            "bullets": ["Quote the line in your head", "Tone lives in diction", "Theme ≠ one detail"],
        },
        "lesson_notes": [
            "Theme vs topic; tone vs mood.",
            "Inference with textual support.",
            "Figurative language identification.",
            "Author’s purpose and structural contrast.",
        ],
        "A": LIT_A,
        "B": LIT_B,
        "bp": "eng",
    },
    {
        "file": "g9-english-grammar.ts",
        "export": "g9EnglishGrammar",
        "prefix": "g9-eng-ch02",
        "doc": "english-ch02-grammar.md",
        "meta": {
            "id": "grammar-workshop",
            "title": "Grammar Workshop",
            "emoji": "✏️",
            "blurb": "Tense, voice, agreement & editing",
            "topic": "grammar",
            "paperTopics": ["grammar", "comprehension"],
        },
        "lesson": {
            "emoji": "✏️",
            "title": "Grammar workshop",
            "body": [
                "Tense, voice and agreement keep sentences trustworthy.",
                "Name the rule, then choose the form.",
            ],
            "speak": "We tighten grammar: tense, voice, agreement and reported speech.",
            "visual": "sentence",
            "cards": [
                ("Tense", "Time relationships — perfect forms included", "⏳"),
                ("Voice", "Active doer vs passive focus", "🔄"),
                ("Agreement", "Subject and verb must match", "🤝"),
                ("Reported speech", "Backshift and pronoun changes", "🗣️"),
            ],
            "demo": {
                "title": "Backshift",
                "speak": "He said he was tired — am becomes was.",
                "steps": ['Direct: “I am tired.”', "Reporting verb in past", "Am → was", "He said that he was tired."],
                "punchline": "Past reporting usually steps the tense back.",
            },
            "try": {
                "prompt": "Neither of the answers ____ correct.",
                "options": [("a", "are"), ("b", "is"), ("c", "were being"), ("d", "have")],
                "answerId": "b",
                "why": "Neither is singular → is.",
            },
            "wrap_title": "Grammar engineer!",
            "bullets": ["Name the rule", "Watch nearest subject with nor/or", "Passive keeps the tense"],
        },
        "lesson_notes": [
            "Subject–verb agreement including each/neither.",
            "Tense and conditionals.",
            "Active/passive transforms.",
            "Reported speech and common editing errors.",
        ],
        "A": GRAM_A,
        "B": GRAM_B,
        "bp": "eng",
    },
    {
        "file": "g9-english-words.ts",
        "export": "g9EnglishWords",
        "prefix": "g9-eng-ch03",
        "doc": "english-ch03-words.md",
        "meta": {
            "id": "writing-vocab",
            "title": "Writing & Vocabulary",
            "emoji": "✉️",
            "blurb": "Confusables, idioms, formats",
            "topic": "vocabulary",
            "paperTopics": ["vocabulary", "idioms-lite", "comprehension"],
        },
        "lesson": {
            "emoji": "✉️",
            "title": "Precision & format",
            "body": [
                "The right word and the right form make writing work.",
                "Register changes with the reader.",
            ],
            "speak": "Vocabulary precision and school writing formats.",
            "visual": "word-cards",
            "cards": [
                ("Confusables", "principal/principle · affect/effect", "👯"),
                ("Idioms", "Meaning from use, not word-by-word", "🧩"),
                ("One-word substitutes", "Compress a phrase into one term", "🎯"),
                ("Formats", "Notice and email: purpose + details + sign-off", "📋"),
            ],
            "demo": {
                "title": "Register fix",
                "speak": "Replace hey fix the bus with a polite specific request.",
                "steps": ["Identify the reader (principal)", "State the fact clearly", "Use polite formal phrasing", "Close correctly"],
                "punchline": "Same message, fitting voice.",
            },
            "try": {
                "prompt": "The match was ____ due to rain.",
                "options": [("a", "called off"), ("b", "called up"), ("c", "called on"), ("d", "called in")],
                "answerId": "a",
                "why": "Call off means cancel.",
            },
            "wrap_title": "Precision pro!",
            "bullets": ["Who is the reader?", "Confusables differ by one letter", "Formats have expected parts"],
        },
        "lesson_notes": [
            "Synonyms/antonyms at Grade 9 breadth.",
            "Confusables and phrasal verbs.",
            "Idioms and one-word substitutes.",
            "Notice/email register and structure.",
        ],
        "A": WORDS_A,
        "B": WORDS_B,
        "bp": "eng",
    },
]
