"""Grade 9 Maths question banks: Number Systems, Polynomials, Coordinate Geometry."""

def _q(prompt, options, answer, explanation, hint, skill="general", difficulty="medium"):
    return {
        "prompt": prompt,
        "options": options,
        "answer": answer,
        "explanation": explanation,
        "hint": hint,
        "skill": skill,
        "difficulty": difficulty,
    }


# ---------------------------------------------------------------------------
# Chapter 1: Number Systems (48)
# ---------------------------------------------------------------------------
NUMBERS_A = [
    _q("Which of the following is an irrational number?",
       ["√9", "0.25", "√2", "7/3"], "c",
       "√2 cannot be written as p/q in lowest terms; √9 = 3 and 0.25 = 1/4 are rational.",
       "Ask whether the number can be written as p/q with integers.", "irrational", "easy"),
    _q("Every rational number can also be called a…",
       ["natural number", "integer", "real number", "whole number only"], "c",
       "Rationals sit inside the reals. Not every rational is a natural number or integer.",
       "Recall the nested number sets: N ⊂ W ⊂ Z ⊂ Q ⊂ R.", "sets", "easy"),
    _q("The decimal expansion of 1/8 is…",
       ["0.125 (terminating)", "0.121212… (non-terminating repeating)", "0.1121121112… (non-repeating)", "√2"], "a",
       "1 ÷ 8 = 0.125 exactly, so the expansion terminates.",
       "Divide and see if the remainder becomes zero.", "decimals", "easy"),
    _q("A number whose decimal is non-terminating and non-repeating must be…",
       ["rational", "irrational", "an integer", "a whole number"], "b",
       "Non-terminating non-repeating decimals define irrational numbers.",
       "Link decimal type to rational vs irrational.", "decimals", "easy"),
    _q("Between 2 and 3 there are…",
       ["no rational numbers", "exactly one rational", "exactly two rationals", "infinitely many rationals"], "d",
       "Between any two distinct reals there are infinitely many rationals (and irrationals).",
       "Density of rationals on the number line.", "density", "easy"),
    _q("√(16/25) simplifies to…",
       ["4/5", "16/25", "4/25", "8/5"], "a",
       "√(16/25) = √16 / √25 = 4/5.",
       "Take square roots of numerator and denominator separately.", "roots", "easy"),
    _q("Which statement is true?",
       ["Every integer is irrational", "Every real number is rational", "Every natural number is a whole number", "0 is not a real number"], "c",
       "Natural numbers are 1,2,3,… and wholes add 0, so every natural is whole.",
       "Check each claim against the definitions of N, W, Z, Q, R.", "sets", "easy"),
    _q("The rationalising factor of √3 is…",
       ["√3", "3", "1/3", "√2"], "a",
       "√3 × √3 = 3, a rational number, so √3 rationalises √3.",
       "Multiply so the product becomes rational.", "rationalise", "easy"),
    _q("0.¯6 (0.666…) equals…",
       ["6/9", "2/3", "both A and B (since 6/9 = 2/3)", "6/10"], "c",
       "0.¯6 = 6/9 = 2/3, so both equivalent fraction forms are correct.",
       "Convert a repeating single digit using 9 in the denominator.", "decimals", "medium"),
    _q("Which is a terminating decimal?",
       ["1/3", "1/6", "1/7", "1/5"], "d",
       "1/5 = 0.2. A fraction in lowest terms terminates iff the denominator’s primes are only 2 and/or 5.",
       "Check prime factors of the denominator after simplifying.", "decimals", "medium"),
    _q("√8 simplified in simplest radical form is…",
       ["2√2", "4√2", "√4 · √2 = 2√2 only if written 2√2", "8"], "a",
       "√8 = √(4·2) = 2√2.",
       "Factor out the largest perfect square under the root.", "roots", "medium"),
    _q("If x = √5 + √3 and y = √5 − √3, then xy equals…",
       ["2", "8", "√15", "√5 − √3"], "a",
       "xy = (√5)² − (√3)² = 5 − 3 = 2.",
       "Use the difference of squares identity.", "surds", "medium"),
    _q("On the number line, √2 lies between…",
       ["0 and 1", "1 and 2", "2 and 3", "3 and 4"], "b",
       "1² = 1 and 2² = 4, so √2 ≈ 1.414 lies between 1 and 2.",
       "Compare with perfect squares nearby.", "locate", "easy"),
    _q("Which law is correct for positive real a and integers m, n?",
       ["a^m * a^n = a^(m+n)", "a^m * a^n = a^(m*n)", "a^m * a^n = a^(m-n)", "(a^m)^n = a^(m+n)"], "a",
       "When multiplying same bases, add exponents: a^m * a^n = a^(m+n).",
       "Recall the product rule for exponents.", "exponents", "easy"),
    _q("(√7 − √5)(√7 + √5) equals…",
       ["2", "12", "√35", "−2"], "a",
       "Difference of squares: 7 − 5 = 2.",
       "Expand as (a−b)(a+b) = a² − b².", "surds", "easy"),
    _q("Which number is rational?",
       ["π", "√7", "0.101001000100001… (pattern of growing zeros)", "0.¯27"], "d",
       "0.¯27 = 27/99 is a repeating decimal, hence rational. The others are irrational.",
       "Repeating decimals are rational; non-repeating non-terminating are not.", "decimals", "medium"),
    _q("Rationalising the denominator of 1/√5 gives…",
       ["√5 / 5", "5/√5", "√5", "1/5"], "a",
       "Multiply numerator and denominator by √5: √5 / 5.",
       "Multiply top and bottom by √5.", "rationalise", "easy"),
    _q("If 2ˣ = 32, then x equals…",
       ["4", "5", "6", "16"], "b",
       "32 = 2⁵, so x = 5.",
       "Write 32 as a power of 2.", "exponents", "easy"),
    _q("The product of a non-zero rational and an irrational number is…",
       ["always rational", "always irrational", "always an integer", "sometimes zero"], "b",
       "For non-zero rational r and irrational α, rα is irrational (else α would be rational).",
       "If the product were rational, you could solve for the irrational as a ratio.", "irrational", "medium"),
    _q("√(0.09) equals…",
       ["0.3", "0.03", "0.9", "3"], "a",
       "0.09 = 9/100, and √(9/100) = 3/10 = 0.3.",
       "Rewrite as a fraction under a square root.", "roots", "easy"),
    _q("Which expression equals (3²)³?",
       ["3⁵", "3⁶", "9³", "both B and C"], "d",
       "(3²)³ = 3⁶ and 9³ = (3²)³ = 3⁶, so both B and C.",
       "Use (aᵐ)ⁿ = aᵐⁿ and rewrite 9 as 3².", "exponents", "medium"),
    _q("An example of a number that is real but not rational is…",
       ["−4", "22/7", "√11", "0"], "c",
       "√11 is irrational (hence real but not rational). −4, 22/7 and 0 are rational.",
       "Pick the non-perfect-square root.", "sets", "easy"),
    _q("Simplify: √50 − √18 + √8",
       ["4√2", "3√2", "2√2", "5√2"], "a",
       "√50=5√2, √18=3√2, √8=2√2 → 5√2 − 3√2 + 2√2 = 4√2.",
       "Simplify each radical, then combine like terms.", "surds", "hard"),
    _q("If a = 2 + √3, then 1/a equals…",
       ["2 − √3", "√3 − 2", "2 + √3", "1/(2−√3) only, not simplified"], "a",
       "Rationalise: 1/(2+√3) · (2−√3)/(2−√3) = 2−√3, since (2)²−(√3)²=1.",
       "Multiply by the conjugate 2 − √3.", "rationalise", "hard"),
]

NUMBERS_B = [
    _q("Which of these is NOT a real number in the usual school number system?",
       ["√(−4) interpreted as a real square root", "√4", "−√9", "0.¯3"], "a",
       "The square root of a negative is not real; √4=2 and −√9=−3 are real.",
       "Square roots of negatives leave the reals.", "sets", "easy"),
    _q("The decimal 0.125125125… (repeating “125”) is…",
       ["irrational", "rational", "an integer", "not a real number"], "b",
       "A repeating block means a rational number (equal to 125/999).",
       "Repeating expansions are rational.", "decimals", "easy"),
    _q("√(49/64) equals…",
       ["7/8", "49/64", "7/64", "√7 / 8"], "a",
       "√49/√64 = 7/8.",
       "Split the root across numerator and denominator.", "roots", "easy"),
    _q("Which set is densest in the sense that between any two members there is another of the same set?",
       ["Natural numbers", "Integers", "Even integers", "Rational numbers"], "d",
       "Rationals (and reals) are dense; integers have gaps of size 1.",
       "Think about gaps on the number line.", "density", "medium"),
    _q("Rationalise 3/(√7 − √5).",
       ["(3/2)(√7 + √5)", "(3/2)(√7 − √5)", "3(√7 + √5)", "√7 + √5"], "a",
       "Multiply by √7+√5: numerator 3(√7+√5), denominator 7−5=2.",
       "Multiply by the conjugate of the denominator.", "rationalise", "hard"),
    _q("If 5ˣ⁺¹ = 125, then x equals…",
       ["1", "2", "3", "4"], "b",
       "125 = 5³, so x+1 = 3 and x = 2.",
       "Write both sides with base 5.", "exponents", "easy"),
    _q("√12 + √27 equals…",
       ["5√3", "√39", "3√3", "√3"], "a",
       "√12=2√3 and √27=3√3, so the sum is 5√3.",
       "Simplify each surd to a multiple of √3.", "surds", "medium"),
    _q("Which fraction has a terminating decimal expansion?",
       ["13/80", "7/12", "11/14", "5/6"], "a",
       "80 = 2⁴·5, so after simplifying, only primes 2 and 5 remain → terminating.",
       "Prime-factor the denominator.", "decimals", "medium"),
    _q("π − 22/7 is…",
       ["rational", "irrational", "zero", "an integer"], "b",
       "π is irrational and 22/7 is rational; their difference is irrational (and not zero).",
       "Irrational ± nonzero rational stays irrational.", "irrational", "medium"),
    _q("(√2)⁶ equals…",
       ["4", "8", "16", "2√2"], "b",
       "(√2)⁶ = (2^{1/2})⁶ = 2³ = 8.",
       "Convert √2 to a power of 2, then multiply exponents.", "exponents", "medium"),
    _q("The number 0.101001000100001… (one more zero between 1s each time) is…",
       ["rational", "irrational", "terminating", "repeating"], "b",
       "The gaps grow without a repeating block, so the decimal is non-repeating → irrational.",
       "No fixed repeating block means irrational.", "decimals", "hard"),
    _q("If x = √3 − 1, then x + 1/x equals…",
       ["√3", "2", "0", "√3 − 1"], "b",
       "1/x = 1/(√3−1) = (√3+1)/2 after rationalising? Wait: (√3−1)(√3+1)=2, so 1/x=(√3+1)/2. Then x+1/x = (√3−1) + (√3+1)/2. Recheck: actually 1/(√3−1)·(√3+1)/(√3+1)=(√3+1)/2. Sum: (2(√3−1) + (√3+1))/2 = (2√3−2+√3+1)/2=(3√3−1)/2. Hmm that contradicts option B.",
       "Rationalise 1/x using the conjugate.", "rationalise", "hard"),
    _q("Which is correct?",
       ["√(a+b) = √a + √b for all positive a,b", "√(a·b) = √a · √b for non-negative a,b", "√(a−b) = √a − √b always", "(√a)² = −a"], "b",
       "The product rule √(ab)=√a√b holds for non-negative a,b; sums do not split that way.",
       "Only the product (and quotient) rules hold in general for square roots.", "roots", "medium"),
    _q("Locate which integer pair traps √10.",
       ["2 and 3", "3 and 4", "4 and 5", "1 and 2"], "b",
       "3²=9 and 4²=16, so √10 ≈ 3.16 lies between 3 and 4.",
       "Compare with nearby perfect squares.", "locate", "easy"),
    _q("2⁻³ equals…",
       ["−8", "−1/8", "1/8", "8"], "c",
       "2⁻³ = 1/2³ = 1/8.",
       "Negative exponent means reciprocal of the positive power.", "exponents", "easy"),
    _q("The additive inverse of √5 − 2 is…",
       ["√5 + 2", "2 − √5", "−√5 − 2", "1/(√5 − 2)"], "b",
       "Adding 2 − √5 cancels: (√5 − 2) + (2 − √5) = 0.",
       "Flip the sign of the whole expression.", "sets", "medium"),
    _q("Simplify (√18 / √8).",
       ["3/2", "√(9/4) = 3/2", "both A and B", "√2"], "c",
       "√18/√8 = √(18/8) = √(9/4) = 3/2.",
       "Combine under one root or simplify each surd first.", "surds", "medium"),
    _q("Which number is an integer but not a whole number?",
       ["0", "5", "−3", "12"], "c",
       "Whole numbers are 0,1,2,…; −3 is an integer but not whole.",
       "Wholes start at 0; integers include negatives.", "sets", "easy"),
    _q("If √(x − 1) = 3, then x equals…",
       ["8", "10", "9", "4"], "b",
       "Square both sides: x − 1 = 9 → x = 10.",
       "Square both sides carefully.", "roots", "easy"),
    _q("(5√2)² equals…",
       ["10", "50", "25√2", "5√4"], "b",
       "(5√2)² = 25 · 2 = 50.",
       "Square the coefficient and the radicand.", "surds", "easy"),
    _q("A number of the form p/q with p, q integers and q ≠ 0 is called…",
       ["irrational", "rational", "transcendental only", "natural only"], "b",
       "That is the definition of a rational number.",
       "Recall the definition of Q.", "sets", "easy"),
    _q("Which equals 8^{2/3}?",
       ["4", "2", "16", "64"], "a",
       "8^{2/3} = (8^{1/3})² = 2² = 4.",
       "Cube root of 8 is 2, then square.", "exponents", "medium"),
    _q("√(72) in simplest form is…",
       ["6√2", "8√2", "36√2", "12√3"], "a",
       "√72 = √(36·2) = 6√2.",
       "Pull out the largest square factor.", "roots", "medium"),
    _q("If a > 0, then √a · √a equals…",
       ["a", "√a", "a²", "2√a"], "a",
       "√a · √a = a for a ≥ 0.",
       "Product of a square root with itself recovers the radicand.", "roots", "easy"),
]

# Fix the problematic question in NUMBERS_B that has a wrong answer explanation
# Replace index of "If x = √3 − 1, then x + 1/x equals…"
for i, q in enumerate(NUMBERS_B):
    if q["prompt"].startswith("If x = √3 − 1"):
        NUMBERS_B[i] = _q(
            "If x = 2 + √3, then x · (2 − √3) equals…",
            ["1", "7", "4 − 2√3", "√3"],
            "a",
            "(2+√3)(2−√3) = 4 − 3 = 1.",
            "Use the difference of squares on conjugates.",
            "surds",
            "medium",
        )
        break


# ---------------------------------------------------------------------------
# Chapter 2: Polynomials (48)
# ---------------------------------------------------------------------------
POLY_A = [
    _q("The degree of the polynomial 5x³ − 2x + 7 is…",
       ["5", "3", "2", "7"], "b",
       "The highest power of x with a non-zero coefficient is 3.",
       "Degree = highest power with non-zero coefficient.", "degree", "easy"),
    _q("A linear polynomial has degree…",
       ["0", "1", "2", "3"], "b",
       "By definition, linear polynomials are degree 1.",
       "Match the name to the degree.", "degree", "easy"),
    _q("The zero of the polynomial p(x) = 2x − 6 is…",
       ["6", "3", "−3", "2"], "b",
       "2x − 6 = 0 → x = 3.",
       "Solve p(x) = 0.", "zeros", "easy"),
    _q("Which is a quadratic polynomial?",
       ["x³ + 1", "5x − 2", "x² − 4x + 3", "7"], "c",
       "Degree 2 makes it quadratic.",
       "Look for degree exactly 2.", "degree", "easy"),
    _q("If p(x) = x² − 5x + 6, then p(2) equals…",
       ["0", "2", "6", "−4"], "a",
       "4 − 10 + 6 = 0, so x = 2 is a zero.",
       "Substitute x = 2 carefully.", "evaluate", "easy"),
    _q("By the remainder theorem, the remainder when p(x) is divided by (x − a) is…",
       ["p(0)", "p(a)", "p(−a)", "a"], "b",
       "Remainder theorem: remainder is p(a).",
       "Recall remainder theorem wording.", "remainder", "easy"),
    _q("If (x − 1) is a factor of p(x), then…",
       ["p(0) = 1", "p(1) = 0", "p(−1) = 0", "p(1) = 1"], "b",
       "Factor theorem: (x − a) is a factor iff p(a) = 0. Here a = 1.",
       "Factor theorem links factors to zeros.", "factor", "easy"),
    _q("The constant polynomial 9 has degree…",
       ["9", "1", "0", "undefined"], "c",
       "Non-zero constants are degree 0. (The zero polynomial’s degree is left undefined.)",
       "Constants other than zero have degree 0.", "degree", "medium"),
    _q("Factorise: x² − 9",
       ["(x − 3)(x + 3)", "(x − 9)(x + 1)", "(x − 3)²", "x(x − 9)"], "a",
       "Difference of squares: x² − 3² = (x − 3)(x + 3).",
       "Use a² − b² = (a − b)(a + b).", "factorise", "easy"),
    _q("The number of zeros of a non-zero polynomial of degree n is at most…",
       ["n − 1", "n", "n + 1", "2n"], "b",
       "A degree-n polynomial has at most n zeros (unless identically zero).",
       "Fundamental bound: degree limits zeros.", "zeros", "medium"),
    _q("Expand (x + 2)(x + 5).",
       ["x² + 7x + 10", "x² + 10x + 7", "x² + 3x + 10", "x² + 7x + 7"], "a",
       "x² + 5x + 2x + 10 = x² + 7x + 10.",
       "FOIL or distribute carefully.", "expand", "easy"),
    _q("If p(x) = x³ − 1, then p(1) equals…",
       ["0", "1", "−1", "2"], "a",
       "1 − 1 = 0, so (x − 1) is a factor of x³ − 1.",
       "Substitute x = 1.", "evaluate", "easy"),
    _q("Which identity is correct?",
       ["(a + b)² = a² + b²", "(a + b)² = a² + 2ab + b²", "(a − b)² = a² − b²", "(a + b)(a − b) = a² + b²"], "b",
       "(a + b)² expands to a² + 2ab + b².",
       "Recall the standard square identity.", "identity", "easy"),
    _q("The coefficient of x in 3x³ − 4x² + 5x − 6 is…",
       ["3", "−4", "5", "−6"], "c",
       "The term 5x has coefficient 5.",
       "Find the term with power exactly 1.", "coeff", "easy"),
    _q("Divide x² + 5x + 6 by (x + 2). The quotient is…",
       ["x + 3", "x + 2", "x + 5", "x − 3"], "a",
       "(x + 2)(x + 3) = x² + 5x + 6.",
       "Factor or use synthetic/long division.", "divide", "medium"),
    _q("A cubic polynomial has degree…",
       ["2", "3", "4", "1"], "b",
       "Cubic means degree 3.",
       "Match the name to the degree.", "degree", "easy"),
    _q("If α and β are zeros of x² − 5x + 6, then α + β equals…",
       ["6", "5", "−5", "1"], "b",
       "For x² − (sum)x + product, sum of zeros = 5.",
       "Sum of zeros = −(coefficient of x)/leading coefficient.", "zeros", "medium"),
    _q("p(x) = 2x² − 3x + 1. Then p(1) equals…",
       ["0", "1", "2", "−1"], "a",
       "2 − 3 + 1 = 0.",
       "Substitute x = 1.", "evaluate", "easy"),
    _q("Which is a monomial?",
       ["x + 1", "3x²y", "x² − y²", "2x + 3y + 1"], "b",
       "A monomial is a single term; 3x²y is one term.",
       "Count the number of terms.", "classify", "easy"),
    _q("Factorise: x² + 5x + 6",
       ["(x + 2)(x + 3)", "(x + 1)(x + 6)", "(x − 2)(x − 3)", "(x + 5)(x + 1)"], "a",
       "Need two numbers that multiply to 6 and add to 5: 2 and 3.",
       "Find factor pairs of the constant that sum to the middle coefficient.", "factorise", "easy"),
    _q("The remainder when x³ + 3x + 1 is divided by (x − 1) is…",
       ["5", "1", "3", "0"], "a",
       "p(1) = 1 + 3 + 1 = 5.",
       "Use the remainder theorem: evaluate at x = 1.", "remainder", "medium"),
    _q("(x + y)² − (x − y)² equals…",
       ["4xy", "2xy", "x² − y²", "0"], "a",
       "Expand: (x²+2xy+y²) − (x²−2xy+y²) = 4xy.",
       "Expand both squares and subtract.", "identity", "medium"),
    _q("If (x − 2) is a factor of x² − kx + 8 and k is a constant, then k equals…",
       ["2", "4", "6", "8"], "c",
       "p(2)=0 → 4 − 2k + 8 = 0 → 12 = 2k → k = 6.",
       "Apply factor theorem: p(2) = 0.", "factor", "hard"),
    _q("The zeros of x² − 4 are…",
       ["2 only", "−2 only", "2 and −2", "4 and −4"], "c",
       "x² − 4 = (x − 2)(x + 2) = 0 → x = ±2.",
       "Factor as a difference of squares.", "zeros", "easy"),
]

POLY_B = [
    _q("Which polynomial is of degree 4?",
       ["x³ + x⁴ − 1", "4x + 1", "x² + 4", "4"], "a",
       "The x⁴ term makes the degree 4.",
       "Find the highest power present.", "degree", "easy"),
    _q("A quadratic polynomial can have at most how many zeros?",
       ["1", "2", "3", "4"], "b",
       "Degree 2 ⇒ at most 2 zeros.",
       "Zeros ≤ degree.", "zeros", "easy"),
    _q("p(x) = x² − 3x − 4. A zero of p is…",
       ["4", "−1", "both A and B", "3"], "c",
       "(x − 4)(x + 1) = x² − 3x − 4, so zeros are 4 and −1.",
       "Factor or try integer candidates.", "zeros", "medium"),
    _q("The value of (a + b + c)² − (a² + b² + c²) equals…",
       ["2(ab + bc + ca)", "ab + bc + ca", "2abc", "0"], "a",
       "Expand (a+b+c)² = a²+b²+c² + 2(ab+bc+ca).",
       "Expand the square identity for three terms.", "identity", "medium"),
    _q("If p(x) = x³ − 6x² + 11x − 6 and p(1)=0, which is a factor?",
       ["x + 1", "x − 1", "x − 6", "x + 6"], "b",
       "p(1)=0 ⇒ (x − 1) is a factor by the factor theorem.",
       "Factor theorem: zero → factor.", "factor", "easy"),
    _q("Expand (2x − 3)².",
       ["4x² − 12x + 9", "4x² − 9", "4x² + 12x + 9", "4x² − 6x + 9"], "a",
       "(2x)² − 2·2x·3 + 3² = 4x² − 12x + 9.",
       "Use (a − b)² = a² − 2ab + b².", "expand", "easy"),
    _q("The coefficient of x² in (x + 1)(x + 2)(x + 3) is…",
       ["6", "11", "5", "9"], "a",
       "First (x+1)(x+2)=x²+3x+2; times (x+3): x³+3x² + 3x²+9x + 2x+6 = x³+6x²+11x+6. Coefficient of x² is 6.",
       "Expand step by step and collect x² terms.", "coeff", "hard"),
    _q("Remainder when 2x³ − 3x² + x − 1 is divided by (x − 2) is…",
       ["5", "9", "1", "0"], "b",
       "p(2)=2·8 − 3·4 + 2 − 1 = 16 − 12 + 2 − 1 = 5… wait: 16-12=4, +2=6, -1=5. Fix answer to 5.",
       "Evaluate p(2) by the remainder theorem.", "remainder", "medium"),
    _q("Which is a binomial?",
       ["5x", "x² + 3x", "x² + 3x + 2", "0"], "b",
       "A binomial has exactly two terms.",
       "Count terms.", "classify", "easy"),
    _q("Factorise: 4x² − 12x + 9",
       ["(2x − 3)²", "(2x + 3)²", "(4x − 3)(x − 3)", "(2x − 9)(2x − 1)"], "a",
       "It is a perfect square: (2x − 3)².",
       "Check if it matches (a − b)².", "factorise", "medium"),
    _q("If α, β are zeros of x² − 7x + 10, then αβ equals…",
       ["7", "10", "−10", "−7"], "b",
       "Product of zeros = constant/leading = 10.",
       "Product = c/a for ax² + bx + c.", "zeros", "medium"),
    _q("(x + 4)(x − 4) equals…",
       ["x² − 16", "x² + 16", "x² − 8x + 16", "x² + 8x − 16"], "a",
       "Difference of squares: x² − 16.",
       "Use (a+b)(a−b)=a²−b².", "identity", "easy"),
    _q("p(x)=x²+1. How many real zeros does it have?",
       ["0", "1", "2", "infinitely many"], "a",
       "x² + 1 = 0 ⇒ x² = −1, no real solution.",
       "Ask if the graph crosses the x-axis.", "zeros", "medium"),
    _q("The zero of ax + b (a ≠ 0) is…",
       ["b/a", "−b/a", "a/b", "−a/b"], "b",
       "ax + b = 0 ⇒ x = −b/a.",
       "Solve the linear equation.", "zeros", "easy"),
    _q("Which is NOT a polynomial in x?",
       ["x² + √2 x + 1", "x + 1/x", "√3 x³ − 4", "5"], "b",
       "1/x = x⁻¹ is not a non-negative integer power, so not a polynomial.",
       "Polynomials only allow whole-number powers ≥ 0.", "classify", "medium"),
    _q("If p(x)=x³−3x+2 and (x−1) is a factor, the other factor quadratic starts with…",
       ["x²", "x³", "3x", "constant only"], "a",
       "Dividing a cubic by a linear factor leaves a quadratic (leading x²).",
       "Degree drops by 1 on exact division by a linear factor.", "divide", "medium"),
    _q("Expand (x − 1)(x² + x + 1).",
       ["x³ − 1", "x³ + 1", "x³ − x² + x − 1", "x³ + x² + x − 1"], "a",
       "This is the standard factorisation of x³ − 1.",
       "Distribute or recognise x³ − 1.", "expand", "medium"),
    _q("The graph of y = x² − 1 crosses the x-axis at…",
       ["(0, −1) only", "(1, 0) and (−1, 0)", "(1, 0) only", "nowhere"], "b",
       "Zeros are x = ±1, so intercepts (1,0) and (−1,0).",
       "Set y = 0 and solve.", "zeros", "easy"),
    _q("For p(x)=2x²+5x−3, p(−3) equals…",
       ["0", "6", "−6", "18"], "a",
       "2·9 + 5·(−3) − 3 = 18 − 15 − 3 = 0.",
       "Substitute carefully with the negative sign.", "evaluate", "medium"),
    _q("(3x + 2)(x − 1) equals…",
       ["3x² − x − 2", "3x² + 2x − 2", "3x² − 3x − 2", "3x² − x + 2"], "a",
       "3x·x + 3x·(−1) + 2·x + 2·(−1) = 3x² − 3x + 2x − 2 = 3x² − x − 2.",
       "Distribute each term.", "expand", "easy"),
    _q("If the remainder is 0 when p(x) is divided by (x + 3), then…",
       ["p(3)=0", "p(−3)=0", "p(0)=−3", "p(3)=−3"], "b",
       "x + 3 = x − (−3), so evaluate at −3.",
       "Write divisor as (x − a) to read a.", "remainder", "medium"),
    _q("Factorise: x² − 2x − 15",
       ["(x − 5)(x + 3)", "(x − 3)(x + 5)", "(x − 15)(x + 1)", "(x + 5)(x + 3)"], "a",
       "Numbers that multiply to −15 and add to −2: −5 and 3.",
       "Find the factor pair of −15 that sums to −2.", "factorise", "medium"),
    _q("The leading coefficient of −7x⁵ + 3x² − 1 is…",
       ["−7", "3", "−1", "5"], "a",
       "Leading coefficient belongs to the highest-degree term: −7.",
       "Look at the term of highest degree.", "coeff", "easy"),
    _q("Which identity helps expand (x + 2)³?",
       ["(a+b)³ = a³ + 3a²b + 3ab² + b³", "(a+b)² = a² + b²", "a³ − b³ = (a−b)³", "(a+b)(a−b)=a²−b² only"], "a",
       "The cube identity expands (a+b)³ fully.",
       "Recall the binomial cube expansion.", "identity", "easy"),
]

# Fix remainder answer inconsistency in POLY_B
for i, q in enumerate(POLY_B):
    if q["prompt"].startswith("Remainder when 2x³"):
        POLY_B[i] = _q(
            "Remainder when 2x³ − 3x² + x − 1 is divided by (x − 2) is…",
            ["5", "9", "1", "0"],
            "a",
            "p(2) = 2·8 − 3·4 + 2 − 1 = 16 − 12 + 2 − 1 = 5.",
            "Evaluate p(2) by the remainder theorem.",
            "remainder",
            "medium",
        )
        break


# ---------------------------------------------------------------------------
# Chapter 3: Coordinate Geometry intro (48)
# ---------------------------------------------------------------------------
COORD_A = [
    _q("The point where the x-axis and y-axis meet is called the…",
       ["quadrant", "origin", "abscissa", "ordinate"], "b",
       "Their intersection is the origin (0, 0).",
       "Name the intersection of the axes.", "basics", "easy"),
    _q("In the ordered pair (3, −2), the abscissa is…",
       ["−2", "3", "0", "5"], "b",
       "Abscissa means the x-coordinate, which is 3.",
       "Abscissa = x; ordinate = y.", "basics", "easy"),
    _q("The point (−4, 5) lies in which quadrant?",
       ["I", "II", "III", "IV"], "b",
       "x negative, y positive → quadrant II.",
       "Sign of x and y decides the quadrant.", "quadrants", "easy"),
    _q("A point on the x-axis has…",
       ["x = 0", "y = 0", "x = y", "x = −y"], "b",
       "On the x-axis the y-coordinate is 0.",
       "Which coordinate vanishes on the x-axis?", "axes", "easy"),
    _q("The distance of point (0, 6) from the origin is…",
       ["0", "6", "36", "√6"], "b",
       "It lies on the y-axis 6 units from (0,0).",
       "Use the distance formula or axis distance.", "distance", "easy"),
    _q("Which point lies in quadrant III?",
       ["(2, 3)", "(−2, 3)", "(−2, −3)", "(2, −3)"], "c",
       "Both coordinates negative → quadrant III.",
       "III is (−, −).", "quadrants", "easy"),
    _q("The ordinate of (−7, 0) is…",
       ["−7", "0", "7", "undefined"], "b",
       "Ordinate is the y-coordinate: 0.",
       "Ordinate means y.", "basics", "easy"),
    _q("Points (2, 0), (−3, 0) and (5, 0) are…",
       ["on the y-axis", "on the x-axis", "in quadrant I", "at the origin"], "b",
       "Each has y = 0, so all lie on the x-axis.",
       "y = 0 means on the x-axis.", "axes", "easy"),
    _q("The mirror image of (3, 4) in the x-axis is…",
       ["(−3, 4)", "(3, −4)", "(−3, −4)", "(4, 3)"], "b",
       "Reflection in the x-axis flips the sign of y.",
       "x-axis reflection: (x, y) → (x, −y).", "reflect", "medium"),
    _q("If a point has equal abscissa and ordinate and lies in quadrant I, an example is…",
       ["(2, 2)", "(−2, −2)", "(2, −2)", "(−2, 2)"], "a",
       "Equal positive coordinates sit in quadrant I.",
       "Need x = y > 0.", "quadrants", "easy"),
    _q("Distance between (0, 0) and (3, 4) is…",
       ["5", "7", "12", "25"], "a",
       "√(3² + 4²) = √(9+16) = 5.",
       "Use √(x² + y²) from the origin.", "distance", "easy"),
    _q("Which point is 3 units to the left of the origin on the x-axis?",
       ["(3, 0)", "(0, 3)", "(−3, 0)", "(0, −3)"], "c",
       "Left on the x-axis means negative x: (−3, 0).",
       "Left → negative x; on axis → y = 0.", "axes", "easy"),
    _q("The signs of coordinates in quadrant IV are…",
       ["(+, +)", "(−, +)", "(−, −)", "(+, −)"], "d",
       "Quadrant IV: x positive, y negative.",
       "Clockwise from I: IV is bottom-right.", "quadrants", "easy"),
    _q("If P(x, y) lies on the y-axis, then…",
       ["y = 0", "x = 0", "x = y", "x + y = 0"], "b",
       "On the y-axis, x = 0.",
       "Which coordinate is zero on the y-axis?", "axes", "easy"),
    _q("The point (0, −5) is…",
       ["in quadrant III", "in quadrant IV", "on the negative y-axis", "on the positive x-axis"], "c",
       "x = 0 and y < 0 means on the negative y-axis (not inside a quadrant).",
       "Axis points are not in any quadrant.", "axes", "medium"),
    _q("Distance between A(1, 2) and B(4, 6) is…",
       ["5", "7", "25", "√13"], "a",
       "√((4−1)² + (6−2)²) = √(9+16) = 5.",
       "Use the distance formula: root of delta-x squared plus delta-y squared.", "distance", "medium"),
    _q("Reflecting (5, −2) in the y-axis gives…",
       ["(−5, −2)", "(5, 2)", "(−5, 2)", "(2, −5)"], "a",
       "y-axis reflection flips the sign of x.",
       "(x, y) → (−x, y) across the y-axis.", "reflect", "medium"),
    _q("Which ordered pair represents the origin?",
       ["(1, 1)", "(0, 0)", "(0, 1)", "(1, 0)"], "b",
       "The origin is (0, 0).",
       "Both coordinates zero.", "basics", "easy"),
    _q("A point with abscissa −3 and ordinate 7 is written…",
       ["(7, −3)", "(−3, 7)", "(−3, −7)", "(3, 7)"], "b",
       "Ordered pairs are (abscissa, ordinate) = (−3, 7).",
       "Write (x, y) in that order.", "basics", "easy"),
    _q("How many quadrants does the Cartesian plane have?",
       ["2", "3", "4", "5"], "c",
       "The two axes divide the plane into four quadrants.",
       "Count the regions made by the axes.", "quadrants", "easy"),
    _q("The point equidistant from (2, 0) and (−2, 0) that lies on the y-axis could be…",
       ["(0, 0)", "(2, 2)", "(0, 3) also works among options? Wait", "(1, 0)"], "a",
       "Any (0, y) is equidistant from (2,0) and (−2,0); (0,0) is on the list.",
       "Perpendicular bisector of (−2,0)(2,0) is the y-axis.", "distance", "hard"),
    _q("If both coordinates of a point are zero, the point…",
       ["lies in quadrant I", "is the origin", "lies on x-axis only, not y-axis", "does not exist"], "b",
       "(0,0) is the origin, belonging to both axes.",
       "Only the origin has both coordinates zero.", "basics", "easy"),
    _q("Which point is closer to the origin: A(3, 4) or B(0, 6)?",
       ["A", "B", "equally far", "cannot tell"], "a",
       "OA = 5 and OB = 6, so A is closer.",
       "Compare √(x²+y²) for each.", "distance", "medium"),
    _q("The vertical line through (−2, 5) has equation…",
       ["y = −2", "x = −2", "y = 5", "x = 5"], "b",
       "A vertical line has constant x-coordinate: x = −2.",
       "Vertical → fixed x.", "axes", "medium"),
]

# Fix the awkward option in COORD_A q about equidistant
for i, q in enumerate(COORD_A):
    if "equidistant from (2, 0)" in q["prompt"]:
        COORD_A[i] = _q(
            "Which point on the y-axis is equidistant from (2, 0) and (−2, 0)?",
            ["(0, 0)", "(2, 2)", "(1, 0)", "(2, 0)"],
            "a",
            "Any point (0, y) is equidistant from (2,0) and (−2,0); among the options, (0,0) works.",
            "The perpendicular bisector of (−2,0) and (2,0) is the y-axis.",
            "distance",
            "hard",
        )
        break

COORD_B = [
    _q("The Cartesian plane is also called the…",
       ["number line only", "coordinate plane", "quadrant line", "ray plane"], "b",
       "It is the coordinate (or Cartesian) plane.",
       "Another name for the xy-plane.", "basics", "easy"),
    _q("Point (0, 8) lies…",
       ["in quadrant I", "on the positive y-axis", "on the positive x-axis", "in quadrant II"], "b",
       "x = 0, y > 0 → positive y-axis.",
       "Axis points are not inside quadrants.", "axes", "easy"),
    _q("In quadrant II, x is ____ and y is ____.",
       ["positive, positive", "negative, positive", "negative, negative", "positive, negative"], "b",
       "Quadrant II: x < 0, y > 0.",
       "II is upper-left.", "quadrants", "easy"),
    _q("The distance of (−5, 0) from the origin is…",
       ["5", "−5", "0", "25"], "a",
       "Distance is absolute: 5 units along the x-axis.",
       "Distance is never negative.", "distance", "easy"),
    _q("Mirror image of (−1, 6) across the origin is…",
       ["(1, −6)", "(−1, −6)", "(1, 6)", "(6, −1)"], "a",
       "Point reflection through origin: (x, y) → (−x, −y).",
       "Negate both coordinates.", "reflect", "medium"),
    _q("Which point does NOT lie on the line x = 4?",
       ["(4, 0)", "(4, −2)", "(4, 7)", "(0, 4)"], "d",
       "(0, 4) has x = 0, not 4.",
       "Check the x-coordinate of each option.", "axes", "easy"),
    _q("Abscissa of a point is positive and ordinate negative. It lies in…",
       ["I", "II", "III", "IV"], "d",
       "(+, −) is quadrant IV.",
       "Match signs to quadrants.", "quadrants", "easy"),
    _q("Distance between (2, −1) and (2, 4) is…",
       ["5", "3", "√5", "0"], "a",
       "Same x-coordinate: |4 − (−1)| = 5.",
       "Vertical segment length is |y₂ − y₁|.", "distance", "easy"),
    _q("The point (7, 7) lies…",
       ["on the x-axis", "on the y-axis", "on the line y = x in quadrant I", "at the origin"], "c",
       "Equal positive coordinates → on y = x in quadrant I.",
       "Compare x and y.", "quadrants", "medium"),
    _q("If P(a, b) is reflected in both axes (x then y), the final image is…",
       ["(a, b)", "(−a, −b)", "(−a, b)", "(a, −b)"], "b",
       "x-axis: (a,−b); then y-axis: (−a,−b). Same as central inversion.",
       "Track each reflection’s effect on signs.", "reflect", "hard"),
    _q("Coordinates of a point 4 units above the x-axis and 3 units left of the y-axis are…",
       ["(4, −3)", "(−3, 4)", "(3, 4)", "(−4, 3)"], "b",
       "Left of y-axis → x = −3; above x-axis → y = 4.",
       "Translate the words into signs and distances.", "basics", "medium"),
    _q("Which is true for every point on the x-axis?",
       ["abscissa is zero", "ordinate is zero", "both coordinates equal", "both coordinates positive"], "b",
       "y = 0 for every point on the x-axis.",
       "Ordinate means y.", "axes", "easy"),
    _q("The area of the triangle formed by (0,0), (4,0) and (0,3) is…",
       ["12", "6", "7", "24"], "b",
       "Right triangle with legs 4 and 3: area = (1/2)·4·3 = 6.",
       "Base on x-axis, height on y-axis.", "distance", "medium"),
    _q("Point (−3, −3) lies in…",
       ["I", "II", "III", "IV"], "c",
       "Both negative → quadrant III.",
       "Sign check.", "quadrants", "easy"),
    _q("The horizontal line through (5, −2) has equation…",
       ["x = 5", "y = −2", "x = −2", "y = 5"], "b",
       "Horizontal lines have constant y.",
       "Horizontal → fixed y.", "axes", "medium"),
    _q("Distance between (−1, −1) and (2, 3) is…",
       ["5", "√18", "7", "25"], "a",
       "√[(2−(−1))² + (3−(−1))²] = √(9+16) = 5.",
       "Apply the distance formula.", "distance", "medium"),
    _q("Which point is the reflection of (0, 4) in the x-axis?",
       ["(0, −4)", "(4, 0)", "(−4, 0)", "(0, 4)"], "a",
       "Flip y: (0, −4).",
       "x-axis reflection changes y’s sign.", "reflect", "easy"),
    _q("If a point lies in quadrant I, then…",
       ["x > 0 and y > 0", "x < 0 and y > 0", "x > 0 and y < 0", "x < 0 and y < 0"], "a",
       "Quadrant I is the (+, +) region.",
       "I is upper-right.", "quadrants", "easy"),
    _q("The points (1, 2) and (1, −5)…",
       ["have the same ordinate", "lie on a vertical line", "lie on the x-axis", "are the same point"], "b",
       "Same x-coordinate ⇒ vertical line x = 1.",
       "Equal x means vertical alignment.", "axes", "medium"),
    _q("Coordinates (−6, 0) describe a point…",
       ["6 units left of origin on the x-axis", "6 units up on the y-axis", "in quadrant II", "in quadrant III"], "a",
       "y = 0 and x = −6 → on the negative x-axis.",
       "Read the signs and zeros.", "axes", "easy"),
    _q("√[(5−1)² + (2−2)²] is the distance between…",
       ["(5, 2) and (1, 2)", "(5, 1) and (2, 2)", "(1, 5) and (2, 2)", "(5, 2) and (2, 1)"], "a",
       "The expression matches Δx=4, Δy=0 between (5,2) and (1,2).",
       "Match the differences to the coordinates.", "distance", "medium"),
    _q("A point with zero abscissa and positive ordinate lies…",
       ["on the positive x-axis", "on the positive y-axis", "in quadrant I", "in quadrant II"], "b",
       "x = 0, y > 0 → positive y-axis.",
       "Zero abscissa means on the y-axis.", "axes", "easy"),
    _q("Which pair of points are symmetric about the y-axis?",
       ["(2, 3) and (−2, 3)", "(2, 3) and (2, −3)", "(2, 3) and (−2, −3)", "(2, 3) and (3, 2)"], "a",
       "y-axis symmetry flips x only: (2,3) ↔ (−2,3).",
       "Same y, opposite x.", "reflect", "medium"),
    _q("The origin is…",
       ["in quadrant I only", "the intersection of the axes", "not a point of the plane", "only on the x-axis, not the y-axis"], "b",
       "Origin is where both axes meet and belongs to both.",
       "Definition of the origin.", "basics", "easy"),
]

CHAPTERS = [
    {
        "file": "g9-maths-number-systems.ts",
        "export": "g9MathsNumberSystems",
        "prefix": "g9-maths-numbers",
        "doc": "maths-ch01-number-systems.md",
        "meta": {
            "id": "number-systems",
            "title": "Number Systems",
            "emoji": "🔢",
            "blurb": "Reals, rationals, surds & exponents",
            "topic": "fractions",
            "paperTopics": ["fractions", "linear-lite"],
        },
        "lesson": {
            "emoji": "🔢",
            "title": "Number systems",
            "body": [
                "From naturals to reals — and the irrationals that fill the gaps.",
                "Decimals, surds and exponent laws help you move fluently.",
            ],
            "speak": "Today we map the number systems and learn to work with surds and exponents.",
            "visual": "number-line",
            "cards": [
                ("Rationals", "p/q form; terminating or repeating decimals", "➗"),
                ("Irrationals", "Non-repeating, non-terminating decimals", "∞"),
                ("Surds", "Simplify and rationalise denominators", "√"),
                ("Exponents", "Same base: add, subtract, multiply powers", "⚡"),
            ],
            "demo": {
                "title": "Rationalise 1/√2",
                "speak": "Multiply top and bottom by root 2 to get root 2 over 2.",
                "steps": ["Start with 1/√2", "Multiply by √2/√2", "Get √2 / 2"],
                "punchline": "The denominator becomes rational.",
            },
            "try": {
                "prompt": "Which is irrational?",
                "options": [("a", "√9"), ("b", "√7"), ("c", "0.25"), ("d", "4/5")],
                "answerId": "b",
                "why": "√7 is not a perfect square, so it is irrational.",
            },
            "wrap_title": "Number line navigator!",
            "bullets": ["Q vs irrational", "Simplify surds", "Watch exponent laws"],
        },
        "lesson_notes": [
            "Nested sets N ⊂ W ⊂ Z ⊂ Q ⊂ R; irrationals fill gaps in Q.",
            "Terminating/repeating decimals ↔ rationals; non-repeating ↔ irrationals.",
            "Simplify radicals; rationalise denominators with conjugates.",
            "Exponent laws for positive bases and integer/rational exponents.",
        ],
        "A": NUMBERS_A,
        "B": NUMBERS_B,
        "hints_default_skill": True,
    },
    {
        "file": "g9-maths-polynomials.ts",
        "export": "g9MathsPolynomials",
        "prefix": "g9-maths-poly",
        "doc": "maths-ch02-polynomials.md",
        "meta": {
            "id": "polynomials",
            "title": "Polynomials",
            "emoji": "𝑥",
            "blurb": "Degree, zeros, factor & remainder",
            "topic": "linear-lite",
            "paperTopics": ["linear-lite", "fractions"],
        },
        "lesson": {
            "emoji": "𝑥",
            "title": "Polynomials",
            "body": [
                "Polynomials are built from powers of x with constant coefficients.",
                "Zeros, factors and remainders are three views of the same idea.",
            ],
            "speak": "Polynomials, zeros, and the factor and remainder theorems.",
            "visual": "balance",
            "cards": [
                ("Degree", "Highest power with a non-zero coefficient", "📶"),
                ("Zero", "Input that makes p(x) = 0", "🎯"),
                ("Remainder theorem", "Divide by (x−a) → remainder p(a)", "➗"),
                ("Factor theorem", "(x−a) is a factor iff p(a)=0", "🧩"),
            ],
            "demo": {
                "title": "Factor x² − 5x + 6",
                "speak": "Find numbers that multiply to 6 and add to 5: 2 and 3.",
                "steps": ["Need factors of 6 that add to 5", "2 and 3 work", "(x−2)(x−3)=x²−5x+6", "Zeros at 2 and 3"],
                "punchline": "Factors reveal the zeros.",
            },
            "try": {
                "prompt": "Degree of 4x³ − x + 1?",
                "options": [("a", "4"), ("b", "3"), ("c", "1"), ("d", "0")],
                "answerId": "b",
                "why": "Highest power is 3.",
            },
            "wrap_title": "Polynomial pro!",
            "bullets": ["Degree first", "p(a)=0 ↔ factor", "Expand and factor both ways"],
        },
        "lesson_notes": [
            "Degree, coefficients, monomials/binomials/trinomials.",
            "Evaluate polynomials; find zeros of linear and quadratic cases.",
            "Remainder and factor theorems.",
            "Standard identities and factorisation patterns.",
        ],
        "A": POLY_A,
        "B": POLY_B,
    },
    {
        "file": "g9-maths-coordinate.ts",
        "export": "g9MathsCoordinate",
        "prefix": "g9-maths-coord",
        "doc": "maths-ch03-coordinate-geometry.md",
        "meta": {
            "id": "coordinate-geometry",
            "title": "Coordinate Geometry",
            "emoji": "📍",
            "blurb": "Axes, quadrants & distance intro",
            "topic": "linear-lite",
            "paperTopics": ["linear-lite", "fractions"],
        },
        "lesson": {
            "emoji": "📍",
            "title": "Coordinate geometry",
            "body": [
                "Every point gets an address: (x, y).",
                "Axes, quadrants and distance unlock the plane.",
            ],
            "speak": "Plot points with coordinates and measure distances.",
            "visual": "number-line",
            "cards": [
                ("Origin", "(0, 0) — where axes meet", "⭕"),
                ("Quadrants", "I (+,+), II (−,+), III (−,−), IV (+,−)", "🧭"),
                ("Axes", "x-axis: y=0 · y-axis: x=0", "➕"),
                ("Distance", "√[(x₂−x₁)² + (y₂−y₁)²]", "📏"),
            ],
            "demo": {
                "title": "Plot (−3, 2)",
                "speak": "Move 3 left, then 2 up — that is quadrant II.",
                "steps": ["Start at origin", "x = −3 → left 3", "y = 2 → up 2", "Land in quadrant II"],
                "punchline": "Signs tell the quadrant before you plot.",
            },
            "try": {
                "prompt": "Where is (−2, −5)?",
                "options": [("a", "I"), ("b", "II"), ("c", "III"), ("d", "IV")],
                "answerId": "c",
                "why": "Both negative → quadrant III.",
            },
            "wrap_title": "Plane pilot!",
            "bullets": ["(x, y) order matters", "Axes are not quadrants", "Distance formula from Pythagoras"],
        },
        "lesson_notes": [
            "Cartesian plane, origin, abscissa and ordinate.",
            "Four quadrants and points on the axes.",
            "Reflections in axes and origin.",
            "Distance formula as Pythagoras on a grid.",
        ],
        "A": COORD_A,
        "B": COORD_B,
    },
]
