"""Grade 9 Science: Matter, Cell/Tissues, Motion."""

def _q(prompt, options, answer, explanation, hint, skill="general", difficulty="medium"):
    return {
        "prompt": prompt,
        "options": options,
        "answer": answer,
        "explanation": explanation,
        "hint": hint,
        "skill": skill,
        "difficulty": difficulty,
    }


MATTER_A = [
    _q("Matter is anything that has…",
       ["only colour", "mass and occupies space", "only smell", "only taste"],
       "b", "Matter has mass and occupies space.",
       "Recall the school definition of matter.", "basics", "easy"),
    _q("In which state are particles most loosely packed and free to move far apart?",
       ["solid", "liquid", "gas", "all equal"],
       "c", "Gas particles are farthest apart and move freely.",
       "Compare packing in solid/liquid/gas.", "states", "easy"),
    _q("The change of a liquid into vapour at any temperature below boiling point is…",
       ["melting", "evaporation", "sublimation", "condensation"],
       "b", "Evaporation occurs at the surface below boiling point.",
       "Surface process below boiling point.", "change", "easy"),
    _q("Dry ice (solid CO₂) changing directly to gas is…",
       ["melting", "freezing", "sublimation", "evaporation"],
       "c", "Solid → gas directly is sublimation.",
       "Skip the liquid state.", "change", "easy"),
    _q("Which has a definite shape and definite volume?",
       ["gas", "liquid", "solid", "plasma only in stars"],
       "c", "Solids keep shape and volume.",
       "Definite shape is the solid clue.", "states", "easy"),
    _q("Boiling occurs…",
       ["only at the surface", "throughout the bulk of the liquid at a fixed temperature (for given pressure)", "only in solids", "without heat"],
       "b", "Boiling is bulk vaporisation at the boiling point for a given pressure.",
       "Contrast boiling with evaporation.", "change", "medium"),
    _q("Latent heat of vaporisation is the heat…",
       ["to raise temperature of vapour by 1°C", "to convert unit mass of liquid to vapour at constant temperature", "to melt any solid", "stored only in solids"],
       "b", "It is heat to change liquid → vapour without temperature change (per unit mass).",
       "Latent = hidden during phase change.", "latent", "medium"),
    _q("Cooling caused by evaporation happens because…",
       ["particles gain heat from surroundings? Wait — high-energy particles leave, lowering average KE", "particles stop moving", "mass increases", "volume becomes zero"],
       "a", "Faster particles escape; remaining liquid has lower average kinetic energy → cooler.",
       "Who leaves during evaporation?", "evaporation", "hard"),
    _q("Which factor increases the rate of evaporation?",
       ["decreasing surface area", "increasing humidity", "increasing wind speed", "decreasing temperature"],
       "c", "Wind removes vapour, speeding further evaporation.",
       "Think clothes drying on a windy day.", "evaporation", "medium"),
    _q("Liquids have…",
       ["definite shape and volume", "definite volume but no definite shape", "neither shape nor volume", "definite shape only"],
       "b", "Liquids take container shape but keep volume.",
       "Pour water into different vessels.", "states", "easy"),
    _q("The SI unit of temperature commonly converted from Celsius in science is…",
       ["fahrenheit only", "kelvin", "calorie", "pascal"],
       "b", "SI unit of thermodynamic temperature is kelvin.",
       "SI temperature unit.", "units", "easy"),
    _q("0°C equals how many kelvin?",
       ["0 K", "100 K", "273 K", "373 K"],
       "c", "T(K) = t(°C) + 273 (approx. 273.15).",
       "Add 273 to Celsius.", "units", "easy"),
    _q("Interparticle forces are strongest in…",
       ["gases", "liquids", "solids", "vacuums"],
       "c", "Solids have the strongest forces and least particle motion freedom.",
       "Strong forces ↔ fixed shape.", "particle", "easy"),
    _q("Condensation is the change from…",
       ["liquid to solid", "gas to liquid", "solid to gas", "liquid to gas"],
       "b", "Gas → liquid is condensation.",
       "Steam on a cold lid.", "change", "easy"),
    _q("Which is NOT a characteristic of particles of matter?",
       ["they have spaces between them", "they are continuously moving", "they attract each other", "they are always at absolute rest in liquids"],
       "d", "Particles move in all states; they are not at absolute rest in liquids.",
       "Kinetic idea of matter.", "particle", "medium"),
    _q("Humidity high means evaporation is…",
       ["faster", "slower", "unchanged always", "impossible"],
       "b", "Air already holds much vapour, so net evaporation slows.",
       "Saturated air accepts less vapour.", "evaporation", "medium"),
    _q("Melting point of ice at standard pressure is…",
       ["100°C", "0°C", "−273°C", "37°C"],
       "b", "Ice melts at 0°C at standard atmospheric pressure.",
       "Common benchmark temperature.", "change", "easy"),
    _q("A gas can be liquefied by…",
       ["increasing temperature only", "applying pressure and/or lowering temperature", "removing all mass", "painting it blue"],
       "b", "Cooling and compressing favour liquefaction.",
       "Think LPG storage.", "states", "medium"),
    _q("Which process cools a clay pot of water?",
       ["water freezing solid instantly", "evaporation through porous walls", "condensation inside only", "sublimation of clay"],
       "b", "Porous pots allow evaporation that cools the remaining water.",
       "Link evaporation and cooling.", "evaporation", "medium"),
    _q("Plasma (mentioned in advanced contexts) is…",
       ["a solid crystal always", "an ionised gas-like state of matter", "only liquid metal", "identical to ice"],
       "b", "Plasma consists of ionised particles; often called a fourth state.",
       "Ionised state beyond ordinary gas.", "states", "hard"),
    _q("Diffusion is fastest in…",
       ["solids", "liquids", "gases", "all equal always"],
       "c", "Particles move fastest and are least packed in gases.",
       "Smell of perfume spreading.", "particle", "easy"),
    _q("During melting of ice at 0°C, temperature of the mixture…",
       ["rises steadily", "falls steadily", "stays constant until melting finishes", "becomes 100°C at once"],
       "c", "Heat goes into latent heat; temperature plateaus during the phase change.",
       "Latent heat keeps temperature steady.", "latent", "medium"),
    _q("Which has the highest fluidity?",
       ["iron rod", "honey at room temperature", "oxygen gas", "ice cube"],
       "c", "Gases flow most freely; solids do not flow as fluids in ordinary sense.",
       "Fluids = liquids and gases; gases are most fluid.", "states", "medium"),
    _q("The boiling point of water at standard atmospheric pressure is…",
       ["0°C", "50°C", "100°C", "273°C"],
       "c", "Water boils at 100°C at 1 atm.",
       "Standard boiling point of water.", "change", "easy"),
]

# Fix awkward option in cooling/evaporation question
for i, q in enumerate(MATTER_A):
    if q["prompt"].startswith("Cooling caused by evaporation"):
        MATTER_A[i] = _q(
            "Cooling caused by evaporation happens because…",
            [
                "higher-energy particles leave, lowering average kinetic energy of the rest",
                "particles stop moving completely",
                "mass of liquid increases",
                "volume becomes exactly zero",
            ],
            "a",
            "Faster particles escape; remaining liquid has lower average kinetic energy → cooler.",
            "Which particles leave during evaporation?",
            "evaporation",
            "hard",
        )
        break

MATTER_B = [
    _q("Particles of matter are…",
       ["visible easily always as separate dots to the eye", "extremely small", "never in motion", "without spaces between them"],
       "b", "Particles are too small to see individually; they move and have spaces.",
       "Particle nature basics.", "particle", "easy"),
    _q("Naphthalene balls disappear over time mainly by…",
       ["melting to liquid first always", "sublimation", "condensation", "freezing"],
       "b", "Naphthalene sublimes: solid → vapour.",
       "Common sublimation example.", "change", "easy"),
    _q("Which state can be compressed the most easily?",
       ["solid", "liquid", "gas", "all identical"],
       "c", "Large spaces between gas particles allow easy compression.",
       "Compressibility ranking.", "states", "easy"),
    _q("Steam at 100°C causes more severe burns than water at 100°C mainly because steam…",
       ["has lower temperature", "carries latent heat of vaporisation released on condensation", "is denser than water", "has no energy"],
       "b", "Condensing steam releases latent heat in addition to cooling.",
       "Latent heat of vaporisation.", "latent", "hard"),
    _q("The process of a gas changing into a solid without becoming liquid is…",
       ["deposition (sometimes taught with sublimation reverse)", "melting", "boiling", "evaporation"],
       "a", "Gas → solid directly is deposition (reverse of sublimation).",
       "Direct gas-to-solid change.", "change", "hard"),
    _q("Increasing surface area of a liquid…",
       ["decreases evaporation rate", "increases evaporation rate", "stops all motion", "changes boiling point to 0 always"],
       "b", "More surface → more molecules can escape per time.",
       "Spread water in a plate vs a cup.", "evaporation", "easy"),
    _q("A liquid’s boiling point depends on…",
       ["colour only", "external pressure", "only the container’s brand", "magnetism only"],
       "b", "Lower pressure → lower boiling point (e.g., on mountains).",
       "Pressure and boiling.", "change", "medium"),
    _q("Which statement is true?",
       ["Gases have definite shape", "Solids are highly compressible", "Liquids flow and take container shape", "Particles in solids never vibrate"],
       "c", "Liquids flow; solids vibrate about fixed positions; gases lack definite shape.",
       "Eliminate false state claims.", "states", "easy"),
    _q("Sponge is compressible though solid because…",
       ["it has no particles", "it has tiny holes filled with air", "it is a liquid", "it is a gas"],
       "b", "Air pockets compress; the material itself is solid.",
       "Structure vs state.", "states", "medium"),
    _q("When we smell perfume from across a room, the process is mainly…",
       ["sedimentation", "diffusion", "sublimation of glass", "centrifugation"],
       "b", "Perfume vapour mixes through air by diffusion.",
       "Mixing of particles.", "particle", "easy"),
    _q("Kelvin scale starts at…",
       ["0°C", "absolute zero (−273°C approx.)", "100°C", "32°F only"],
       "b", "0 K is absolute zero ≈ −273°C.",
       "Bottom of the kelvin scale.", "units", "medium"),
    _q("Which change is physical?",
       ["burning paper", "rusting iron", "melting wax", "digesting food"],
       "c", "Melting wax changes state, not chemical identity.",
       "Physical vs chemical change.", "change", "medium"),
    _q("Evaporation causes cooling; this helps…",
       ["sweating cool the body", "ice form faster always in deserts", "boiling without heat", "solids expand forever"],
       "a", "Sweat evaporates, taking heat from skin.",
       "Everyday application.", "evaporation", "easy"),
    _q("The force of attraction between particles is weakest in…",
       ["solids", "liquids", "gases", "ice only"],
       "c", "Gas particles interact least strongly.",
       "Weak forces ↔ free motion.", "particle", "easy"),
    _q("At the melting point, solid and liquid…",
       ["cannot coexist", "can coexist in equilibrium", "must both be gases", "have zero mass"],
       "b", "During melting, both phases can be present at the melting temperature.",
       "Phase equilibrium at melting point.", "latent", "medium"),
    _q("Which factor does NOT increase evaporation rate?",
       ["higher temperature", "more wind", "larger surface area", "higher humidity"],
       "d", "Higher humidity slows evaporation.",
       "Pick the opposite factor.", "evaporation", "medium"),
    _q("Ice floats on water because…",
       ["ice is denser", "ice is less dense than liquid water", "ice has no mass", "water has no particles"],
       "b", "Open structure of ice makes it less dense than water.",
       "Density comparison.", "states", "medium"),
    _q("The temperature at which a liquid starts boiling (at given pressure) is its…",
       ["melting point", "boiling point", "freezing point only if gas", "flash point always same as melting"],
       "b", "Boiling point is that characteristic temperature for the liquid at that pressure.",
       "Name the property.", "change", "easy"),
    _q("Intermixing of particles of two different types of matter on their own is…",
       ["diffusion", "sedimentation", "filtration", "distillation always"],
       "a", "Diffusion is spontaneous mixing of particles.",
       "Definition of diffusion.", "particle", "easy"),
    _q("To convert 25°C to kelvin…",
       ["subtract 273", "add 273", "multiply by 273", "divide by 273"],
       "b", "K ≈ °C + 273 → 298 K.",
       "Add 273.", "units", "easy"),
    _q("Which best explains why liquids can be poured?",
       ["particles are fixed in place rigidly", "particles can move past one another while staying close", "particles are infinitely far apart", "there are no forces at all"],
       "b", "Liquid particles move/slide while cohesive enough to keep volume.",
       "Particle picture of fluidity.", "states", "medium"),
    _q("Camphor disappears from a dish mainly due to…",
       ["filtration", "sublimation", "sedimentation", "condensation into the dish"],
       "b", "Camphor sublimes into vapour.",
       "Classic sublimation substance.", "change", "easy"),
    _q("Heat required to change 1 kg of solid to liquid at melting point is called…",
       ["latent heat of fusion", "latent heat of vaporisation", "specific heat only", "solar constant"],
       "a", "Latent heat of fusion is for solid ↔ liquid.",
       "Fusion ↔ melting.", "latent", "medium"),
    _q("Matter around us exists mainly in…",
       ["one state only", "three common states: solid, liquid, gas", "only plasma", "only vapour"],
       "b", "School science focuses on solid, liquid and gas.",
       "Common states of matter.", "basics", "easy"),
]


CELL_A = [
    _q("The basic structural and functional unit of life is the…",
       ["tissue", "organ", "cell", "organism"],
       "c", "Cell theory: cell is the basic unit of life.",
       "Smallest living unit.", "basics", "easy"),
    _q("Who coined the term “cell” after observing cork?",
       ["Darwin", "Robert Hooke", "Newton", "Mendel"],
       "b", "Robert Hooke observed cork cells.",
       "History of the word cell.", "history", "easy"),
    _q("The control centre of the cell that contains genetic material is the…",
       ["mitochondrion", "nucleus", "ribosome", "vacuole"],
       "b", "Nucleus houses DNA and controls activities.",
       "Which organelle holds chromosomes?", "organelle", "easy"),
    _q("Powerhouse of the cell refers to…",
       ["nucleus", "mitochondria", "golgi apparatus", "cell wall"],
       "b", "Mitochondria release energy (cellular respiration).",
       "Energy organelle nickname.", "organelle", "easy"),
    _q("Which is present in plant cells but not in typical animal cells?",
       ["mitochondria", "cell membrane", "cell wall", "ribosomes"],
       "c", "Rigid cell wall of cellulose is plant-typical.",
       "Plant vs animal checklist.", "compare", "easy"),
    _q("Chloroplasts are associated with…",
       ["protein digestion", "photosynthesis", "nerve signals", "bone growth"],
       "b", "Chloroplasts trap light to make food.",
       "Green plastids.", "organelle", "easy"),
    _q("A group of similar cells performing a specific function forms a…",
       ["organelle", "tissue", "organ system only", "population"],
       "b", "Tissue = group of similar cells with a common function.",
       "Cells → tissues → organs.", "organisation", "easy"),
    _q("The selectively permeable boundary of an animal cell is the…",
       ["cell wall", "plasma membrane", "nuclear envelope only", "cytoplasm"],
       "b", "Plasma/cell membrane controls entry and exit.",
       "Selective barrier name.", "organelle", "easy"),
    _q("Prokaryotic cells lack a…",
       ["cell membrane", "true membrane-bound nucleus", "DNA of any kind", "ribosomes always"],
       "b", "Prokaryotes lack a true nucleus; DNA is not in a nuclear envelope.",
       "Pro- means before a true nucleus.", "classify", "medium"),
    _q("Which tissue provides support in plants and may be living or dead depending on type?",
       ["meristematic only always dead", "sclerenchyma (support; dead at maturity)", "blood", "nerve"],
       "b", "Sclerenchyma is a supporting tissue, typically dead at maturity.",
       "Plant support tissues.", "tissue", "hard"),
    _q("Meristematic tissue in plants is responsible for…",
       ["photosynthesis only", "growth by cell division", "transport of only water forever without division", "storing only fat in animals"],
       "b", "Meristems actively divide to allow growth.",
       "Growing tips of roots/shoots.", "tissue", "medium"),
    _q("Epithelial tissue in animals mainly…",
       ["contracts to move bones", "covers body surfaces and lines cavities", "carries oxygen as haemoglobin tissue name", "stores only starch"],
       "b", "Epithelium covers and lines surfaces.",
       "Covering tissue.", "tissue", "medium"),
    _q("Large central vacuoles are typical of…",
       ["animal cells", "plant cells", "viruses", "all bacteria without exception in exams always"],
       "b", "Mature plant cells often have a large central vacuole.",
       "Plant cell hallmarks.", "compare", "easy"),
    _q("Ribosomes help in…",
       ["lipid storage only", "protein synthesis", "photosynthesis", "digestion of food in stomach tissue"],
       "b", "Ribosomes assemble proteins.",
       "Protein factory.", "organelle", "easy"),
    _q("Xylem mainly transports…",
       ["food from leaves", "water and minerals from roots", "oxygen in blood", "hormones only in animals"],
       "b", "Xylem conducts water and minerals upward.",
       "Plant vascular tissue roles.", "tissue", "medium"),
    _q("Phloem transports…",
       ["water only upward always", "food (sugars) to plant parts", "only carbon dioxide", "only sunlight"],
       "b", "Phloem moves prepared food.",
       "Food-conducting tissue.", "tissue", "medium"),
    _q("Which organelle packages and dispatches proteins?",
       ["lysosome", "golgi apparatus", "chloroplast", "cell wall"],
       "b", "Golgi modifies and packages materials.",
       "Shipping centre of the cell.", "organelle", "medium"),
    _q("Lysosomes are rich in…",
       ["chlorophyll", "digestive enzymes", "cellulose only", "starch grains only"],
       "b", "Lysosomes contain hydrolytic enzymes (suicide bags).",
       "Digestive organelle.", "organelle", "medium"),
    _q("Connective tissue examples include…",
       ["skin epithelium only", "blood, bone and cartilage", "xylem", "meristem"],
       "b", "Blood, bone and cartilage are connective tissues.",
       "Diverse connective examples.", "tissue", "medium"),
    _q("Muscle tissue is specialised for…",
       ["impulse only", "contraction and movement", "photosynthesis", "covering surfaces only"],
       "b", "Muscles contract to produce movement.",
       "Function of muscle.", "tissue", "easy"),
    _q("Nervous tissue is specialised to…",
       ["store fat", "transmit impulses", "transport water in stems", "make glucose in leaves"],
       "b", "Neurons transmit electrical/chemical signals.",
       "Signal tissue.", "tissue", "easy"),
    _q("Which is unicellular?",
       ["mango tree", "human", "Amoeba", "rose plant"],
       "c", "Amoeba is a single-celled organism.",
       "One cell vs many.", "basics", "easy"),
    _q("Cell wall of plants is mainly made of…",
       ["chitin only as in all plants", "cellulose", "peptidoglycan only", "keratin"],
       "b", "Plant cell walls are chiefly cellulose.",
       "Plant wall chemistry.", "compare", "easy"),
    _q("Chromosomes are found in the…",
       ["vacuole", "nucleus", "cell wall", "mitochondrial nickname only never nucleus"],
       "b", "Chromosomes reside in the nucleus (as chromatin/chromosomes).",
       "Where DNA is packaged in eukaryotes.", "organelle", "easy"),
]

# Fix sclerenchyma awkward options
for i, q in enumerate(CELL_A):
    if "support in plants" in q["prompt"]:
        CELL_A[i] = _q(
            "Which plant tissue provides rigid support and is usually dead at maturity?",
            ["meristematic tissue", "sclerenchyma", "blood", "nerve tissue"],
            "b",
            "Sclerenchyma is a supporting tissue, typically dead at maturity.",
            "Plant support tissues include sclerenchyma.",
            "tissue",
            "hard",
        )
        break

CELL_B = [
    _q("Who proposed that all cells arise from pre-existing cells?",
       ["Hooke alone", "Virchow", "Einstein", "Lavoisier"],
       "b", "Virchow: Omnis cellula e cellula.",
       "Cell theory contributor.", "history", "medium"),
    _q("Cytoplasm is…",
       ["the rigid outer wall", "the jelly-like substance between membrane and nucleus", "only DNA", "only air"],
       "b", "Cytoplasm fills the cell between membrane and nucleus.",
       "Interior medium of the cell.", "organelle", "easy"),
    _q("Which cells lack chloroplasts?",
       ["leaf mesophyll cells", "typical animal cells", "green algal cells with chloroplasts", "plant guard cells"],
       "b", "Animal cells do not have chloroplasts.",
       "Who photosynthesises?", "compare", "easy"),
    _q("Permanent tissues in plants are formed from…",
       ["blood", "meristematic tissues that have lost the ability to divide", "only animal epithelium", "viruses"],
       "b", "Differentiation of meristems yields permanent tissues.",
       "Meristem → permanent.", "tissue", "medium"),
    _q("Parenchyma typically…",
       ["is dead with thick lignin always", "is living and soft, often storing food", "transmits nerve impulses", "contracts like biceps"],
       "b", "Parenchyma is living ground tissue, often storage.",
       "Soft plant packing tissue.", "tissue", "medium"),
    _q("Collenchyma provides…",
       ["flexibility and support to growing plant parts", "impulse conduction", "oxygen transport in blood", "only flower colour"],
       "a", "Collenchyma supports young stems/petioles with flexibility.",
       "Living support tissue.", "tissue", "medium"),
    _q("The nucleus is separated from cytoplasm by the…",
       ["cell wall", "nuclear membrane", "xylem", "cuticle only"],
       "b", "Nuclear envelope/membrane bounds the nucleus.",
       "Boundary of nucleus.", "organelle", "easy"),
    _q("Mitochondria are more numerous in cells that…",
       ["need little energy", "require a lot of energy", "are dead xylem vessels only", "have no membrane"],
       "b", "Active cells need more mitochondria for ATP.",
       "Link energy demand to organelle number.", "organelle", "medium"),
    _q("Which is an example of a connective tissue that is fluid?",
       ["bone", "blood", "cartilage only", "tendon only"],
       "b", "Blood is a fluid connective tissue.",
       "Fluid connective tissue.", "tissue", "medium"),
    _q("Striated muscles are also called…",
       ["smooth muscles", "skeletal muscles (voluntary, striped)", "cardiac only without stripes", "xylem fibres"],
       "b", "Skeletal muscles appear striped (striated) and are voluntary.",
       "Striations ↔ skeletal.", "tissue", "medium"),
    _q("Smooth muscles are found in…",
       ["biceps mainly", "walls of internal organs (involuntary)", "heart only as skeletal", "leaf veins"],
       "b", "Visceral/smooth muscle is involuntary in organ walls.",
       "Involuntary non-striated muscle location.", "tissue", "medium"),
    _q("The heart is made of…",
       ["epithelial tissue only", "cardiac muscle tissue", "only parenchyma", "only sclerenchyma"],
       "b", "Cardiac muscle is specialised heart muscle.",
       "Heart muscle type.", "tissue", "easy"),
    _q("Plastids that store starch are…",
       ["chloroplasts", "leucoplasts (amyloplasts)", "chromoplasts that always photosynthesise", "lysosomes"],
       "b", "Leucoplasts/amyloplasts store starch.",
       "Colourless storage plastids.", "organelle", "hard"),
    _q("Chromoplasts mainly…",
       ["store water", "provide colours to flowers/fruits", "make ATP only", "form cell walls"],
       "b", "Chromoplasts hold pigments for colour.",
       "Chromo- = colour.", "organelle", "medium"),
    _q("Which feature is absent in prokaryotes?",
       ["ribosomes", "membrane-bound organelles like mitochondria", "plasma membrane", "DNA"],
       "b", "Prokaryotes lack membrane-bound organelles.",
       "Prokaryote vs eukaryote.", "classify", "medium"),
    _q("The outermost layer in plant cells is usually the…",
       ["plasma membrane inside the wall", "cell wall", "nuclear membrane outside everything", "cytoplasm shell"],
       "b", "Cell wall is outside the plasma membrane in plants.",
       "Order: wall outside membrane.", "compare", "easy"),
    _q("Tissue that covers the body and protects underlying parts is…",
       ["epithelial tissue", "xylem", "phloem", "meristem only deep inside"],
       "a", "Epithelium covers and protects.",
       "Covering animal tissue.", "tissue", "easy"),
    _q("Cartilage is a type of…",
       ["epithelial tissue", "connective tissue", "nervous tissue", "meristem"],
       "b", "Cartilage is connective tissue.",
       "Supportive connective tissue.", "tissue", "easy"),
    _q("Who observed living cells (e.g., protozoa) with better microscopes after Hooke?",
       ["Leeuwenhoek", "Dalton", "Bohr", "Faraday"],
       "a", "Antonie van Leeuwenhoek observed living microbes/cells.",
       "Early microscopy history.", "history", "medium"),
    _q("Cell theory states that…",
       ["all living beings are made of cells / cell products", "rocks are made of cells", "energy cannot be created", "atoms are indivisible"],
       "a", "Cell theory concerns organisation of living things.",
       "Core claim of cell theory.", "basics", "easy"),
    _q("Vacuoles in animal cells are generally…",
       ["larger than in plants", "smaller (when present) than the plant central vacuole", "made of cellulose wall", "absent in all cells forever"],
       "b", "Animal vacuoles are smaller/more temporary than plant central vacuoles.",
       "Compare vacuole size.", "compare", "medium"),
    _q("Phloem fibres are…",
       ["always living sieve tubes", "supportive components associated with phloem", "blood cells", "nerve endings"],
       "b", "Phloem includes fibres that help support.",
       "Vascular tissue components.", "tissue", "hard"),
    _q("A multicellular organism…",
       ["has only one cell", "is made of many cells", "cannot have tissues", "never grows"],
       "b", "Multi- = many cells.",
       "Prefix multi-.", "basics", "easy"),
    _q("The organelle involved in photosynthesis contains the pigment…",
       ["haemoglobin", "chlorophyll", "melanin only", "keratin"],
       "b", "Chlorophyll in chloroplasts captures light.",
       "Green photosynthetic pigment.", "organelle", "easy"),
]


MOTION_A = [
    _q("Distance is…",
       ["a vector", "a scalar (path length)", "always equal to displacement", "measured only in kg"],
       "b", "Distance is scalar path length; displacement is vector.",
       "Scalar vs vector for path length.", "basics", "easy"),
    _q("Displacement can be zero when distance is not zero if the body…",
       ["never moves", "returns to its starting point", "moves in a straight line one way only", "has infinite speed"],
       "b", "A round trip can have zero net displacement.",
       "Start and end at same point.", "basics", "easy"),
    _q("Speed equals…",
       ["distance / time", "displacement / time only as a name for speed", "force / mass", "mass × acceleration"],
       "a", "Average speed = total distance / total time.",
       "Speed formula.", "speed", "easy"),
    _q("Velocity is…",
       ["speed with direction (vector)", "only a scalar", "same as acceleration always", "measured in kg"],
       "b", "Wait — answer should be a. Fix.",
       "Velocity = speed + direction.", "velocity", "easy"),
    _q("SI unit of acceleration is…",
       ["m/s", "m/s²", "m²/s", "N"],
       "b", "Acceleration is rate of change of velocity → m/s².",
       "Unit of Δv/Δt.", "units", "easy"),
    _q("A body moving with constant velocity has acceleration…",
       ["maximum", "zero", "infinite", "equal to velocity"],
       "b", "Constant velocity ⇒ zero acceleration.",
       "Acceleration needs changing velocity.", "accel", "easy"),
    _q("If a car goes 100 m east then 100 m west, displacement is…",
       ["200 m east", "0", "100 m west", "100 m east"],
       "b", "Net change in position is zero.",
       "Vector sum of opposite equal displacements.", "basics", "easy"),
    _q("Average velocity equals…",
       ["total distance / time", "displacement / total time", "speed × time", "acceleration × time only always"],
       "b", "Average velocity uses displacement over time.",
       "Velocity cares about net displacement.", "velocity", "medium"),
    _q("The slope of a distance–time graph gives…",
       ["acceleration", "speed", "force", "mass"],
       "b", "Slope of s–t (distance–time) indicates speed.",
       "Rise/run on distance–time.", "graphs", "medium"),
    _q("The slope of a velocity–time graph gives…",
       ["distance", "acceleration", "mass", "force"],
       "b", "a = Δv/Δt = slope on v–t graph.",
       "Slope meaning on v–t.", "graphs", "medium"),
    _q("Area under a velocity–time graph gives…",
       ["acceleration", "displacement (for the interval)", "force", "power"],
       "b", "∫v dt corresponds to displacement.",
       "Area under v–t.", "graphs", "medium"),
    _q("Which is a vector quantity?",
       ["speed", "distance", "displacement", "time"],
       "c", "Displacement has magnitude and direction.",
       "Vectors need direction.", "basics", "easy"),
    _q("Uniform circular motion has…",
       ["constant velocity", "constant speed but changing velocity (direction)", "zero speed", "no acceleration"],
       "b", "Direction changes continuously ⇒ velocity changes ⇒ centripetal acceleration.",
       "Speed vs velocity on a circle.", "accel", "medium"),
    _q("Equation for velocity under constant acceleration: v = …",
       ["u + at", "u − a/t", "ut + a", "a/u + t"],
       "a", "First equation of motion: v = u + at.",
       "Recall v = u + at.", "equations", "easy"),
    _q("s = ut + ½at² assumes…",
       ["variable acceleration randomly", "constant acceleration (and straight-line motion as used in class)", "zero mass", "circular path only"],
       "b", "Standard equations assume constant acceleration.",
       "When do the three equations apply?", "equations", "medium"),
    _q("A body starts from rest. Its initial velocity u is…",
       ["maximum", "0", "equal to g always", "infinite"],
       "b", "From rest means u = 0.",
       "Rest → zero initial velocity.", "equations", "easy"),
    _q("If acceleration is negative (deceleration), speed generally…",
       ["increases", "decreases (when velocity and accel oppose)", "stays meaningless", "becomes mass"],
       "b", "Deceleration reduces speed when opposing velocity.",
       "Opposite direction of a and v.", "accel", "medium"),
    _q("Distance travelled in nth second under constant a relates to…",
       ["only mass", "u + a(n − ½)", "u/a only", "t² only without u"],
       "b", "s_n = u + a(n − 1/2) for constant a (standard formula).",
       "Nth-second formula.", "equations", "hard"),
    _q("Which graph is a straight line through origin for uniform speed?",
       ["distance–time", "velocity–time always curved", "acceleration–time always rising", "force–time only"],
       "a", "Constant speed ⇒ linear distance–time through proportional rise.",
       "Uniform speed on s–t.", "graphs", "medium"),
    _q("Displacement’s SI unit is…",
       ["second", "metre", "m/s", "kg"],
       "b", "Displacement is a length → metre.",
       "SI length unit.", "units", "easy"),
    _q("A particle moves 3 m east and 4 m north. Net displacement magnitude is…",
       ["7 m", "5 m", "1 m", "12 m"],
       "b", "Perpendicular paths: √(3²+4²)=5 m.",
       "Pythagoras for perpendicular displacements.", "basics", "medium"),
    _q("Instantaneous speed is…",
       ["average over a day only", "speed at a particular instant", "always zero", "acceleration"],
       "b", "Instantaneous = at an instant (limit of average).",
       "Meaning of instantaneous.", "speed", "easy"),
    _q("If v–t graph is a horizontal line, acceleration is…",
       ["positive constant", "zero", "increasing", "undefined always"],
       "b", "Horizontal v means constant velocity → a = 0.",
       "Flat v–t ⇒ no acceleration.", "graphs", "easy"),
    _q("Free fall near Earth (ignoring air) has acceleration approximately…",
       ["0", "9.8 m/s² downward", "9.8 m/s upward always", "98 m/s²"],
       "b", "g ≈ 9.8 m/s² downward.",
       "Acceleration due to gravity.", "accel", "easy"),
]

for i, q in enumerate(MOTION_A):
    if q["prompt"].startswith("Velocity is"):
        MOTION_A[i] = _q(
            "Velocity is…",
            ["speed with direction (a vector)", "only a scalar like distance", "the same as acceleration", "measured in kilograms"],
            "a",
            "Velocity is a vector: speed with direction.",
            "Does velocity include direction?",
            "velocity",
            "easy",
        )
        break

MOTION_B = [
    _q("Which quantity can be negative in one-dimensional motion?",
       ["distance", "speed", "displacement", "time interval"],
       "c", "Displacement can be negative depending on chosen positive direction.",
       "Which can carry a sign?", "basics", "medium"),
    _q("A bus travels 60 km in 2 hours. Average speed is…",
       ["30 km/h", "120 km/h", "60 km/h", "15 km/h"],
       "a", "60/2 = 30 km/h.",
       "Distance over time.", "speed", "easy"),
    _q("If displacement is 40 m and time is 8 s, average velocity magnitude is…",
       ["5 m/s", "32 m/s", "48 m/s", "0.2 m/s"],
       "a", "40/8 = 5 m/s.",
       "Displacement/time.", "velocity", "easy"),
    _q("Acceleration is zero when…",
       ["velocity changes", "velocity is constant", "speed is zero only always", "the body is at rest or in uniform velocity — both have a=0"],
       "b", "Constant velocity (including rest) means zero acceleration. Option B is the clean choice.",
       "No change in velocity → a = 0.", "accel", "easy"),
    _q("v² = u² + 2as is used when…",
       ["time is unknown but a is constant", "acceleration varies wildly", "mass is required", "only circular motion"],
       "a", "Third equation eliminates t for constant a.",
       "Which variable is missing?", "equations", "medium"),
    _q("On a distance–time graph, a horizontal line means the body is…",
       ["speeding up", "at rest", "moving with increasing speed", "accelerating uniformly"],
       "b", "Distance not changing → at rest.",
       "Flat s–t.", "graphs", "easy"),
    _q("If a v–t graph is a straight line sloping upward, acceleration is…",
       ["zero", "constant and positive", "infinite", "negative always"],
       "b", "Constant positive slope → constant positive a.",
       "Straight sloping v–t.", "graphs", "medium"),
    _q("Scalar quantities have…",
       ["magnitude only", "magnitude and direction", "only direction", "neither"],
       "a", "Scalars: magnitude only.",
       "Scalar definition.", "basics", "easy"),
    _q("A car accelerates from 10 m/s to 20 m/s in 5 s. Acceleration is…",
       ["2 m/s²", "6 m/s²", "50 m/s²", "0.5 m/s²"],
       "a", "a = (20−10)/5 = 2 m/s².",
       "Δv/Δt.", "accel", "easy"),
    _q("Distance is never…",
       ["positive", "zero", "negative", "greater than displacement magnitude in a detour"],
       "c", "Distance cannot be negative.",
       "Path length ≥ 0.", "basics", "easy"),
    _q("For a freely falling object from rest, after time t, speed is about…",
       ["gt", "g/t", "g + t", "t/g"],
       "a", "v = u + gt with u = 0 → v = gt.",
       "Use v = u + at with u=0.", "equations", "medium"),
    _q("Uniform motion means…",
       ["equal distances in equal intervals of time (constant speed on a straight path as taught)", "ever-changing speed", "rest only", "circular with changing speed"],
       "a", "Equal distances in equal times characterises uniform motion.",
       "Definition of uniform motion.", "speed", "easy"),
    _q("Non-uniform motion means…",
       ["constant speed always", "changing speed (unequal distances in equal times)", "zero displacement always", "motion without path"],
       "b", "Speed changes in non-uniform motion.",
       "Opposite of uniform.", "speed", "easy"),
    _q("If u = 0, a = 2 m/s², t = 3 s, then s =…",
       ["9 m", "6 m", "18 m", "3 m"],
       "a", "s = 0·t + ½·2·9 = 9 m.",
       "s = ut + ½at².", "equations", "medium"),
    _q("A body moving east with speed 5 m/s has velocity…",
       ["5 m/s", "5 m/s east", "5 m east", "25 m/s²"],
       "b", "Velocity needs the direction stated.",
       "Include direction for velocity.", "velocity", "easy"),
    _q("Retardation means…",
       ["positive acceleration in direction of velocity", "acceleration opposite to velocity (deceleration)", "zero velocity only", "constant speed forever"],
       "b", "Retardation/deceleration opposes velocity.",
       "Slowing down.", "accel", "medium"),
    _q("The odometer of a car measures…",
       ["instantaneous velocity vector", "distance travelled", "acceleration", "displacement only"],
       "b", "Odometer records path distance.",
       "Dashboard instrument roles.", "basics", "easy"),
    _q("A speedometer shows…",
       ["average speed for the whole trip only", "instantaneous speed", "displacement", "force"],
       "b", "Speedometer indicates current speed.",
       "Instantaneous reading.", "speed", "easy"),
    _q("If distance–time graph is a curve bending upward, speed is…",
       ["constant", "increasing", "zero", "negative"],
       "b", "Increasing slope means increasing speed.",
       "Steeper s–t → faster.", "graphs", "hard"),
    _q("Displacement magnitude is always ____ distance.",
       ["greater than", "less than or equal to", "unrelated to", "exactly twice"],
       "b", "Shortest path ≤ actual path length.",
       "Straight shortcut vs path.", "basics", "medium"),
    _q("For constant speed on a straight line, acceleration is…",
       ["g", "0", "v/t always non-zero", "infinite"],
       "b", "No velocity change → a = 0.",
       "Constant velocity case.", "accel", "easy"),
    _q("Which equation does not require time explicitly?",
       ["v = u + at", "s = ut + ½at²", "v² = u² + 2as", "all require t"],
       "c", "v² = u² + 2as has no t.",
       "Scan for missing t.", "equations", "medium"),
    _q("A ball thrown upward returns to the hand. Net displacement is…",
       ["maximum height", "zero", "twice the height", "equal to distance"],
       "b", "Back to start → displacement zero; distance is twice height.",
       "Round trip displacement.", "basics", "medium"),
    _q("SI unit of speed is…",
       ["m/s", "m/s²", "N", "kg/m"],
       "a", "Speed = distance/time → m/s.",
       "SI speed unit.", "units", "easy"),
]

# Clean MOTION_B awkward acceleration option
for i, q in enumerate(MOTION_B):
    if q["prompt"].startswith("Acceleration is zero when"):
        MOTION_B[i] = _q(
            "Acceleration is zero when…",
            ["velocity changes", "velocity is constant", "force is infinite", "distance is maximum"],
            "b",
            "Constant velocity (including rest) means zero acceleration.",
            "No change in velocity → a = 0.",
            "accel",
            "easy",
        )
        break


CHAPTERS = [
    {
        "file": "g9-science-matter.ts",
        "export": "g9ScienceMatter",
        "prefix": "g9-sci-matter",
        "doc": "science-ch01-matter.md",
        "meta": {
            "id": "matter-surroundings",
            "title": "Matter in Our Surroundings",
            "emoji": "☁️",
            "blurb": "States, particles & changes of state",
            "topic": "materials",
            "paperTopics": ["materials", "forces-energy"],
        },
        "lesson": {
            "emoji": "☁️",
            "title": "Matter around us",
            "body": [
                "Everything that has mass and occupies space is matter.",
                "Particles, states and latent heat explain everyday changes.",
            ],
            "speak": "States of matter, particle model, and changes like evaporation.",
            "visual": "atom-lite",
            "cards": [
                ("Particles", "Tiny, moving, with spaces and forces", "•"),
                ("States", "Solid, liquid, gas — packing differs", "🧊"),
                ("Evaporation", "Surface vaporisation that cools", "💨"),
                ("Latent heat", "Heat for phase change without temperature rise", "🔥"),
            ],
            "demo": {
                "title": "Why sweat cools you",
                "speak": "Faster particles leave as vapour, so the remaining sweat is cooler.",
                "steps": ["Skin is wet with sweat", "Energetic particles evaporate", "Average energy of remaining liquid drops", "You feel cooler"],
                "punchline": "Evaporation is a cooling process.",
            },
            "try": {
                "prompt": "Solid to gas directly is called…",
                "options": [("a", "melting"), ("b", "sublimation"), ("c", "condensation"), ("d", "boiling")],
                "answerId": "b",
                "why": "Sublimation skips the liquid state.",
            },
            "wrap_title": "Matter mapper!",
            "bullets": ["States differ by packing", "Boiling ≠ evaporation", "Latent heat hides in phase change"],
        },
        "lesson_notes": [
            "Particle nature of matter.",
            "Solid/liquid/gas properties.",
            "Melting, boiling, evaporation, sublimation, condensation.",
            "Latent heat and factors affecting evaporation.",
        ],
        "A": MATTER_A,
        "B": MATTER_B,
        "bp": "sci",
    },
    {
        "file": "g9-science-cell.ts",
        "export": "g9ScienceCell",
        "prefix": "g9-sci-cell",
        "doc": "science-ch02-cell-tissues.md",
        "meta": {
            "id": "cell-tissues",
            "title": "Cell & Tissues",
            "emoji": "🔬",
            "blurb": "Organelles & tissue types intro",
            "topic": "cells-basics",
            "paperTopics": ["cells-basics", "living-things"],
        },
        "lesson": {
            "emoji": "🔬",
            "title": "Cells and tissues",
            "body": [
                "Cells build tissues; organelles divide the labour.",
                "Plant and animal cells share much — and differ in walls and chloroplasts.",
            ],
            "speak": "Cell organelles and an introduction to tissues.",
            "visual": "plant",
            "cards": [
                ("Nucleus", "Control centre with genetic material", "🧬"),
                ("Mitochondria", "Energy release", "⚡"),
                ("Plant extras", "Cell wall, chloroplasts, large vacuole", "🌿"),
                ("Tissues", "Similar cells with a shared job", "🧱"),
            ],
            "demo": {
                "title": "Plant vs animal cell",
                "speak": "Both have membrane, cytoplasm and nucleus; plants add wall and chloroplasts.",
                "steps": ["Start with shared parts", "Add cell wall outside membrane", "Add chloroplasts for photosynthesis", "Note large central vacuole"],
                "punchline": "Same toolkit, different extras.",
            },
            "try": {
                "prompt": "Which organelle is for photosynthesis?",
                "options": [("a", "mitochondrion"), ("b", "chloroplast"), ("c", "ribosome"), ("d", "lysosome")],
                "answerId": "b",
                "why": "Chloroplasts contain chlorophyll for photosynthesis.",
            },
            "wrap_title": "Cell explorer!",
            "bullets": ["Cell → tissue → organ", "Match organelle to job", "Meristems grow; permanent tissues specialise"],
        },
        "lesson_notes": [
            "Cell theory and microscopy history highlights.",
            "Organelles and plant vs animal differences.",
            "Plant tissues: meristematic and permanent (including vascular).",
            "Animal tissues: epithelial, connective, muscular, nervous.",
        ],
        "A": CELL_A,
        "B": CELL_B,
        "bp": "sci",
    },
    {
        "file": "g9-science-motion.ts",
        "export": "g9ScienceMotion",
        "prefix": "g9-sci-motion",
        "doc": "science-ch03-motion.md",
        "meta": {
            "id": "motion",
            "title": "Motion",
            "emoji": "🏃",
            "blurb": "Distance, speed, velocity & graphs",
            "topic": "forces-energy",
            "paperTopics": ["forces-energy", "materials"],
        },
        "lesson": {
            "emoji": "🏃",
            "title": "Describing motion",
            "body": [
                "Distance and displacement are not the same.",
                "Graphs and equations organise constant-acceleration stories.",
            ],
            "speak": "Distance, displacement, speed, velocity, acceleration and graphs.",
            "visual": "number-line",
            "cards": [
                ("Distance vs displacement", "Path length vs net change (vector)", "↔️"),
                ("Speed vs velocity", "Scalar vs vector rates", "🚦"),
                ("Acceleration", "Rate of change of velocity", "📈"),
                ("Graphs", "Slope and area tell the story", "📉"),
            ],
            "demo": {
                "title": "Round trip",
                "speak": "Walk 50 metres and back: distance 100 metres, displacement zero.",
                "steps": ["Go 50 m east", "Return 50 m west", "Distance adds to 100 m", "Displacement cancels to 0"],
                "punchline": "Scalars and vectors disagree on round trips.",
            },
            "try": {
                "prompt": "SI unit of acceleration?",
                "options": [("a", "m/s"), ("b", "m/s²"), ("c", "m"), ("d", "s")],
                "answerId": "b",
                "why": "Acceleration is change in velocity per time → m/s².",
            },
            "wrap_title": "Motion ready!",
            "bullets": ["Vectors need direction", "Slope of v–t is acceleration", "s = ut + ½at² for constant a"],
        },
        "lesson_notes": [
            "Distance, displacement, scalars and vectors.",
            "Speed, velocity, acceleration.",
            "Distance–time and velocity–time graphs.",
            "Equations of motion for constant acceleration.",
        ],
        "A": MOTION_A,
        "B": MOTION_B,
        "bp": "sci",
    },
]
