import type { HintOverlay } from "./types";

/** Grade 1 English item-specific hints (overlay) */
export const G1_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g1-eng-letters-a-q01": ["Say the alphabet.", "B then C."],
  "g1-eng-letters-a-q02": ["Listen to the first sound.", "M-oon."],
  "g1-eng-letters-a-q03": ["Blend the sounds.", "Cat."],
  "g1-eng-letters-a-q04": ["Letters are A\u2013Z.", "A."],
  "g1-eng-letters-a-q05": ["Count each letter.", "Three."],
  "g1-eng-letters-a-q06": ["Look at the last letter.", "\u2026g."],
  "g1-eng-letters-a-q07": ["Big letter form.", "A."],
  "g1-eng-letters-a-q08": ["Think of pets.", "Cat."],
  "g1-eng-letters-a-q09": ["Same ending sound.", "-at."],
  "g1-eng-letters-a-q10": ["Look at the start.", "I."],
  "g1-eng-letters-a-q11": ["Pick a word you know.", "Book."],
  "g1-eng-letters-a-q12": ["Say ball slowly.", "B."],
  "g1-eng-letters-a-q13": ["Count them.", "Five."],
  "g1-eng-letters-a-q14": ["Lower case.", "t."],
  "g1-eng-letters-a-q15": ["Colours you know.", "Red."],
  "g1-eng-letters-a-q16": ["Blend the parts.", "Blue."],
  "g1-eng-letters-b-q01": ["Alphabet order.", "C."],
  "g1-eng-letters-b-q02": ["First sound /s/.", "Sun."],
  "g1-eng-letters-b-q03": ["Blend.", "Pen."],
  "g1-eng-letters-b-q04": ["Count.", "Three."],
  "g1-eng-letters-b-q05": ["Last letter.", "t."],
  "g1-eng-letters-b-q06": ["Big letter.", "B."],
  "g1-eng-letters-b-q07": ["Farm animal.", "Cow."],
  "g1-eng-letters-b-q08": ["Same -un sound.", "Fun."],
  "g1-eng-letters-b-q09": ["Start of the word.", "A."],
  "g1-eng-letters-b-q10": ["Odd one out.", "7."],
  "g1-eng-letters-b-q11": ["First sound.", "T."],
  "g1-eng-letters-b-q12": ["Count.", "Three."],
  "g1-eng-letters-b-q13": ["Food from trees.", "Mango."],
  "g1-eng-letters-b-q14": ["Lower case.", "g."],
  "g1-eng-letters-b-q15": ["Blend.", "Ship."],
  "g1-eng-letters-b-q16": ["Count letters.", "On."],
  "g1-eng-reading-a-q01": ["Day sky light.", "Sun."],
  "g1-eng-reading-a-q02": ["Find the place words.", "On the mat."],
  "g1-eng-reading-a-q03": ["Think who has wings.", "Bird."],
  "g1-eng-reading-a-q04": ["Find the food word.", "Mango."],
  "g1-eng-reading-a-q05": ["Night sky.", "Moon."],
  "g1-eng-reading-a-q06": ["Colour word.", "Red."],
  "g1-eng-reading-a-q07": ["Think of a pond.", "Fish."],
  "g1-eng-reading-a-q08": ["Keeps us dry.", "Rain."],
  "g1-eng-reading-a-q09": ["Find the verb.", "Runs."],
  "g1-eng-reading-a-q10": ["What goes in a glass.", "Water."],
  "g1-eng-reading-a-q11": ["Subject of the sentence.", "Hen."],
  "g1-eng-reading-a-q12": ["Bedroom thing.", "Bed."],
  "g1-eng-reading-a-q13": ["Think of morning.", "School."],
  "g1-eng-reading-a-q14": ["Home for birds.", "Nests."],
  "g1-eng-reading-a-q15": ["School tool.", "Pencil."],
  "g1-eng-reading-a-q16": ["Weather word.", "Hot."],
  "g1-eng-reading-b-q01": ["Plant with trunk.", "Tree."],
  "g1-eng-reading-b-q02": ["Find place words.", "Door."],
  "g1-eng-reading-b-q03": ["Pet sound.", "Dog."],
  "g1-eng-reading-b-q04": ["Look in the sentence.", "Bus."],
  "g1-eng-reading-b-q05": ["Day begins.", "Sun."],
  "g1-eng-reading-b-q06": ["Colour word.", "Blue."],
  "g1-eng-reading-b-q07": ["Farm animal.", "Cow."],
  "g1-eng-reading-b-q08": ["Morning and night.", "Teeth."],
  "g1-eng-reading-b-q09": ["Verb in the sentence.", "Hops."],
  "g1-eng-reading-b-q10": ["Table tool.", "Spoon."],
  "g1-eng-reading-b-q11": ["Who does the action?", "Frog."],
  "g1-eng-reading-b-q12": ["Furniture.", "Chair."],
  "g1-eng-reading-b-q13": ["Wet weather.", "Rain."],
  "g1-eng-reading-b-q14": ["Home for fish.", "Water."],
  "g1-eng-reading-b-q15": ["Pages and words.", "Book."],
  "g1-eng-reading-b-q16": ["Feeling word.", "Cold."],
  "g1-eng-grammar-a-q01": ["Look at the first letter.", "Capital I."],
  "g1-eng-grammar-a-q02": ["A vs an.", "An apple."],
  "g1-eng-grammar-a-q03": ["Plural subject.", "Are."],
  "g1-eng-grammar-a-q04": ["One girl.", "Is."],
  "g1-eng-grammar-a-q05": ["I am\u2026", "Am."],
  "g1-eng-grammar-a-q06": ["Person/place/thing.", "School."],
  "g1-eng-grammar-a-q07": ["What can you do?", "Jump."],
  "g1-eng-grammar-a-q08": ["Special names.", "Monday."],
  "g1-eng-grammar-a-q09": ["Singular.", "Is."],
  "g1-eng-grammar-a-q10": ["A vs an.", "An."],
  "g1-eng-grammar-a-q11": ["More than one.", "Are."],
  "g1-eng-grammar-a-q12": ["Not a question.", "Full stop."],
  "g1-eng-grammar-a-q13": ["Look for ?", "Are you ready?"],
  "g1-eng-grammar-a-q14": ["My name is\u2026", "Is."],
  "g1-eng-grammar-a-q15": ["A ball.", "A."],
  "g1-eng-grammar-a-q16": ["Not a twin \u2014 an opposite.", "Small."],
  "g1-eng-grammar-b-q01": ["Sentence start.", "We\u2026"],
  "g1-eng-grammar-b-q02": ["An egg.", "An."],
  "g1-eng-grammar-b-q03": ["Singular.", "Is."],
  "g1-eng-grammar-b-q04": ["You are\u2026", "Are."],
  "g1-eng-grammar-b-q05": ["I + am.", "Am."],
  "g1-eng-grammar-b-q06": ["Noun.", "Teacher."],
  "g1-eng-grammar-b-q07": ["Verb.", "Sing."],
  "g1-eng-grammar-b-q08": ["Special name.", "Delhi."],
  "g1-eng-grammar-b-q09": ["More than one dog.", "Are."],
  "g1-eng-grammar-b-q10": ["An orange.", "An."],
  "g1-eng-grammar-b-q11": ["One boy.", "Is."],
  "g1-eng-grammar-b-q12": ["Ends with .", "It is time\u2026"],
  "g1-eng-grammar-b-q13": ["Ends with ?", "Question."],
  "g1-eng-grammar-b-q14": ["Her bag is\u2026", "Is."],
  "g1-eng-grammar-b-q15": ["A dog.", "A."],
  "g1-eng-grammar-b-q16": ["Not a twin.", "Sad."],
};
