import type { HintOverlay } from "./types";

/** Grade 1 Maths item-specific hints (overlay) */
export const G1_MATHS_HINTS: Record<string, HintOverlay> = {
  "g1-maths-numbers-a-q01": ["Count one step forward from 5.", "5, then 6."],
  "g1-maths-numbers-a-q02": ["Look at one hand.", "Count the fingers."],
  "g1-maths-numbers-a-q03": ["Think which pile is larger.", "8 comes later when you count."],
  "g1-maths-numbers-a-q04": ["Point and count each star.", "One, two, three."],
  "g1-maths-numbers-a-q05": ["Count back one from 10.", "10, then back to 9."],
  "g1-maths-numbers-a-q06": ["Say the number out loud.", "Seven sounds like 7."],
  "g1-maths-numbers-a-q07": ["Count the fruit in each choice.", "Stop at four."],
  "g1-maths-numbers-a-q08": ["See how the numbers grow.", "Add 2 to 6."],
  "g1-maths-numbers-a-q09": ["Find the least.", "2 comes first when you count."],
  "g1-maths-numbers-a-q10": ["Put the balls together.", "One and one make two."],
  "g1-maths-numbers-a-q11": ["Look at each place.", "Tens digit 1, ones digit 4."],
  "g1-maths-numbers-a-q12": ["Count forward.", "1, 2, 3, 4."],
  "g1-maths-numbers-a-q13": ["Last means the end.", "He stops at ten."],
  "g1-maths-numbers-a-q14": ["Compare the two numbers.", "9 is farther on the number line."],
  "g1-maths-numbers-a-q15": ["Empty plate has zero.", "Not one, not many \u2014 none."],
  "g1-maths-numbers-a-q16": ["Take one away from six.", "Five birds stay."],
  "g1-maths-numbers-b-q01": ["Count forward from 9.", "9, then 10."],
  "g1-maths-numbers-b-q02": ["Picture a cycle.", "Two wheels."],
  "g1-maths-numbers-b-q03": ["Find the lesser number.", "1 comes first."],
  "g1-maths-numbers-b-q04": ["Count each dot.", "Five dots."],
  "g1-maths-numbers-b-q05": ["Say it aloud.", "Ten."],
  "g1-maths-numbers-b-q06": ["Count one more.", "7 + 1 = 8."],
  "g1-maths-numbers-b-q07": ["Even numbers pair up.", "4 makes two pairs."],
  "g1-maths-numbers-b-q08": ["Add the new pencils.", "Three and two make five."],
  "g1-maths-numbers-b-q09": ["Count 4, 5, 6.", "The middle one is 5."],
  "g1-maths-numbers-b-q10": ["Count back.", "1, then 2."],
  "g1-maths-numbers-b-q11": ["Count the cats.", "Stop at two."],
  "g1-maths-numbers-b-q12": ["Look at the tens place.", "The left digit is 1."],
  "g1-maths-numbers-b-q13": ["Compare all four.", "8 wins."],
  "g1-maths-numbers-b-q14": ["Last number said is the count.", "Four."],
  "g1-maths-numbers-b-q15": ["Zero adds nothing.", "Still five."],
  "g1-maths-numbers-b-q16": ["Sort them first.", "2 then 4 then 9."],
  "g1-maths-add-a-q01": ["Count on from 2: 3, 4, 5.", "Two and three make five."],
  "g1-maths-add-a-q02": ["One more finger.", "Two."],
  "g1-maths-add-a-q03": ["Count on two from 4.", "Six."],
  "g1-maths-add-a-q04": ["Zero means add nothing.", "Still five."],
  "g1-maths-add-a-q05": ["Double three.", "Six."],
  "g1-maths-add-a-q06": ["One more than six.", "Seven."],
  "g1-maths-add-a-q07": ["Add the sweets.", "Six sweets."],
  "g1-maths-add-a-q08": ["Starting from nothing, add eight.", "Eight."],
  "g1-maths-add-a-q09": ["Count on two from 7.", "Nine."],
  "g1-maths-add-a-q10": ["Double four.", "Eight."],
  "g1-maths-add-a-q11": ["Add the rupees.", "\u20b97."],
  "g1-maths-add-a-q12": ["One and six.", "Seven."],
  "g1-maths-add-a-q13": ["Count on three from 5.", "Eight."],
  "g1-maths-add-a-q14": ["Add step by step.", "Six."],
  "g1-maths-add-a-q15": ["One more than nine.", "Ten."],
  "g1-maths-add-a-q16": ["Try each sum.", "Two and three."],
  "g1-maths-add-b-q01": ["Count on from 3.", "Seven."],
  "g1-maths-add-b-q02": ["Double five.", "Ten."],
  "g1-maths-add-b-q03": ["Count on five from 2.", "Seven."],
  "g1-maths-add-b-q04": ["Zero changes nothing.", "Eight."],
  "g1-maths-add-b-q05": ["One and eight.", "Nine."],
  "g1-maths-add-b-q06": ["Count on three from 6.", "Nine."],
  "g1-maths-add-b-q07": ["Add the crayons.", "Seven."],
  "g1-maths-add-b-q08": ["Count on three from 7.", "Ten."],
  "g1-maths-add-b-q09": ["Two and seven.", "Nine."],
  "g1-maths-add-b-q10": ["One more than four.", "Five."],
  "g1-maths-add-b-q11": ["Double three rupees.", "\u20b96."],
  "g1-maths-add-b-q12": ["One more than eight.", "Nine."],
  "g1-maths-add-b-q13": ["Count on from 3.", "Eight."],
  "g1-maths-add-b-q14": ["Add in order.", "Six."],
  "g1-maths-add-b-q15": ["Count on four from 6.", "Ten."],
  "g1-maths-add-b-q16": ["Check each pair.", "Double four."],
  "g1-maths-shapes-a-q01": ["Think of a round shape.", "No corners \u2014 circle."],
  "g1-maths-shapes-a-q02": ["Tri means three.", "Three sides."],
  "g1-maths-shapes-a-q03": ["Count the sides.", "All four match."],
  "g1-maths-shapes-a-q04": ["Corners are pointy.", "Circle has none."],
  "g1-maths-shapes-a-q05": ["Look at the book shape.", "Four sides, not all equal."],
  "g1-maths-shapes-a-q06": ["Each corner where sides meet.", "Four corners."],
  "g1-maths-shapes-a-q07": ["Pointy tip, three sides.", "Triangle."],
  "g1-maths-shapes-a-q08": ["Tall and flat.", "Rectangle."],
  "g1-maths-shapes-a-q09": ["Match corners to sides.", "Three."],
  "g1-maths-shapes-a-q10": ["Look at a wall clock.", "Circle."],
  "g1-maths-shapes-a-q11": ["Count carefully.", "Four sides."],
  "g1-maths-shapes-a-q12": ["Round things roll.", "Circle."],
  "g1-maths-shapes-a-q13": ["Picture the cut.", "Two triangles."],
  "g1-maths-shapes-a-q14": ["Not a circle.", "Square."],
  "g1-maths-shapes-a-q15": ["Pick the odd one.", "Apple."],
  "g1-maths-shapes-a-q16": ["Think of a window.", "Rectangle."],
  "g1-maths-shapes-b-q01": ["Sides are straight edges.", "None."],
  "g1-maths-shapes-b-q02": ["Pointy road signs.", "Triangle."],
  "g1-maths-shapes-b-q03": ["Equal sides help.", "Square."],
  "g1-maths-shapes-b-q04": ["Round bread.", "Circle."],
  "g1-maths-shapes-b-q05": ["Think of a book.", "Equal pairs."],
  "g1-maths-shapes-b-q06": ["One at each tip.", "Three."],
  "g1-maths-shapes-b-q07": ["Four equal sides.", "Square."],
  "g1-maths-shapes-b-q08": ["Look at \u20b91 coin.", "Circle."],
  "g1-maths-shapes-b-q09": ["Compare 4 and 3.", "Square."],
  "g1-maths-shapes-b-q10": ["Pointy end.", "Triangle."],
  "g1-maths-shapes-b-q11": ["Smooth all around.", "No."],
  "g1-maths-shapes-b-q12": ["Longer one way.", "Rectangle."],
  "g1-maths-shapes-b-q13": ["Three sides.", "Triangle."],
  "g1-maths-shapes-b-q14": ["Say the names.", "Square."],
  "g1-maths-shapes-b-q15": ["Wear on the wrist.", "Circle."],
  "g1-maths-shapes-b-q16": ["Every side matches.", "Four."],
};
