import type { HintOverlay } from "./types";

/** Grade 1 Science item-specific hints (overlay) */
export const G1_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g1-sci-plants-a-q01": ["Hidden in the ground.", "Root."],
  "g1-sci-plants-a-q02": ["Look at a tree.", "Green."],
  "g1-sci-plants-a-q03": ["Baby plant inside.", "New plant."],
  "g1-sci-plants-a-q04": ["Green kitchen.", "Leaf."],
  "g1-sci-plants-a-q05": ["Like we drink.", "Water."],
  "g1-sci-plants-a-q06": ["Attract bees.", "Pretty."],
  "g1-sci-plants-a-q07": ["Light helps make food.", "Sunlight."],
  "g1-sci-plants-a-q08": ["Fruit tree.", "Tree."],
  "g1-sci-plants-a-q09": ["Like anchors.", "Hold."],
  "g1-sci-plants-a-q10": ["Living green thing.", "Rose."],
  "g1-sci-plants-a-q11": ["Cut an apple.", "Seeds."],
  "g1-sci-plants-a-q12": ["Like a stick.", "Stem."],
  "g1-sci-plants-a-q13": ["Desert plant.", "Dry."],
  "g1-sci-plants-a-q14": ["Tree trunks.", "Trees."],
  "g1-sci-plants-a-q15": ["Odd one out.", "Wheel."],
  "g1-sci-plants-a-q16": ["They grow.", "Living."],
  "g1-sci-plants-b-q01": ["Under ground.", "Root."],
  "g1-sci-plants-b-q02": ["Plant kitchen.", "Food."],
  "g1-sci-plants-b-q03": ["Young plant.", "Seedling."],
  "g1-sci-plants-b-q04": ["Life cycle.", "Plant."],
  "g1-sci-plants-b-q05": ["Water and light.", "Care."],
  "g1-sci-plants-b-q06": ["Look and touch.", "Flat green."],
  "g1-sci-plants-b-q07": ["Sweet flower juice.", "Nectar."],
  "g1-sci-plants-b-q08": ["Palm tree.", "Tall."],
  "g1-sci-plants-b-q09": ["Home for roots.", "Grow."],
  "g1-sci-plants-b-q10": ["Pretty plant part.", "Lotus."],
  "g1-sci-plants-b-q11": ["Season change.", "Fall."],
  "g1-sci-plants-b-q12": ["Sunlight work.", "Food."],
  "g1-sci-plants-b-q13": ["Living plant.", "Water."],
  "g1-sci-plants-b-q14": ["Beginning.", "Seed."],
  "g1-sci-plants-b-q15": ["Sharp parts.", "Prick."],
  "g1-sci-plants-b-q16": ["Good for us.", "Air."],
  "g1-sci-animals-a-q01": ["Pet sound.", "Cat."],
  "g1-sci-animals-a-q02": ["Pond or sea.", "Water."],
  "g1-sci-animals-a-q03": ["Farm animal.", "Milk."],
  "g1-sci-animals-a-q04": ["Has wings.", "Sparrow."],
  "g1-sci-animals-a-q05": ["At home.", "Pets."],
  "g1-sci-animals-a-q06": ["Jungle king.", "Wild."],
  "g1-sci-animals-a-q07": ["Long back legs.", "Rabbit."],
  "g1-sci-animals-a-q08": ["To fly.", "Wings."],
  "g1-sci-animals-a-q09": ["Farm.", "Eggs."],
  "g1-sci-animals-a-q10": ["Not a sea animal.", "Dog."],
  "g1-sci-animals-a-q11": ["From flowers.", "Honey."],
  "g1-sci-animals-a-q12": ["Nose and hand.", "Trunk."],
  "g1-sci-animals-a-q13": ["Small insect.", "Ant."],
  "g1-sci-animals-a-q14": ["Warm clothes.", "Wool."],
  "g1-sci-animals-a-q15": ["Pond animal.", "Both."],
  "g1-sci-animals-a-q16": ["Odd one out.", "Table."],
  "g1-sci-animals-b-q01": ["Pond bird.", "Duck."],
  "g1-sci-animals-b-q02": ["Climbing.", "Trees."],
  "g1-sci-animals-b-q03": ["Strong legs.", "Run."],
  "g1-sci-animals-b-q04": ["Protects its body.", "Tortoise."],
  "g1-sci-animals-b-q05": ["Plant eaters.", "Grass."],
  "g1-sci-animals-b-q06": ["Orange and black.", "Stripes."],
  "g1-sci-animals-b-q07": ["In water.", "Fish."],
  "g1-sci-animals-b-q08": ["Be kind.", "Care."],
  "g1-sci-animals-b-q09": ["Farm animal.", "Milk."],
  "g1-sci-animals-b-q10": ["Baby rides inside.", "Kangaroo."],
  "g1-sci-animals-b-q11": ["They slither.", "No legs."],
  "g1-sci-animals-b-q12": ["Colourful feathers.", "Bird."],
  "g1-sci-animals-b-q13": ["Farm work.", "Ox."],
  "g1-sci-animals-b-q14": ["Pet habit.", "Milk."],
  "g1-sci-animals-b-q15": ["Not as house pets.", "Wild."],
  "g1-sci-animals-b-q16": ["Small with wings.", "Butterfly."],
  "g1-sci-body-a-q01": ["Sense of sight.", "Eyes."],
  "g1-sci-body-a-q02": ["Sense of hearing.", "Ears."],
  "g1-sci-body-a-q03": ["Sense of smell.", "Nose."],
  "g1-sci-body-a-q04": ["Sense of taste.", "Tongue."],
  "g1-sci-body-a-q05": ["Count.", "Two."],
  "g1-sci-body-a-q06": ["Legs and feet.", "Feet."],
  "g1-sci-body-a-q07": ["Keep clean.", "Teeth."],
  "g1-sci-body-a-q08": ["Air in and out.", "Nose."],
  "g1-sci-body-a-q09": ["Stay healthy.", "Before."],
  "g1-sci-body-a-q10": ["Beats all day.", "Chest."],
  "g1-sci-body-a-q11": ["Count.", "Two."],
  "g1-sci-body-a-q12": ["Sense of touch.", "Feel."],
  "g1-sci-body-a-q13": ["Play and move.", "Strong."],
  "g1-sci-body-a-q14": ["Night time.", "Sleep."],
  "g1-sci-body-a-q15": ["Count them.", "Hands."],
  "g1-sci-body-a-q16": ["Mouth.", "Teeth."],
  "g1-sci-body-b-q01": ["Put palms together.", "Hands."],
  "g1-sci-body-b-q02": ["Sight safety.", "Eyes."],
  "g1-sci-body-b-q03": ["Hearing.", "Ears."],
  "g1-sci-body-b-q04": ["Tongue feels them.", "Taste."],
  "g1-sci-body-b-q05": ["Walk on two.", "Two."],
  "g1-sci-body-b-q06": ["Be kind to others.", "Sneeze."],
  "g1-sci-body-b-q07": ["Skeleton.", "Stand."],
  "g1-sci-body-b-q08": ["Healthy habit.", "Water."],
  "g1-sci-body-b-q09": ["Keep them clean.", "Fingers."],
  "g1-sci-body-b-q10": ["Happy face.", "Mouth."],
  "g1-sci-body-b-q11": ["Sound.", "Music."],
  "g1-sci-body-b-q12": ["Health check.", "Healthy."],
  "g1-sci-body-b-q13": ["Strong legs.", "Legs."],
  "g1-sci-body-b-q14": ["Bath and wash.", "Clean."],
  "g1-sci-body-b-q15": ["Inside the head.", "Brain."],
  "g1-sci-body-b-q16": ["Helps us see.", "Eye."],
};
