import type { HintOverlay } from "./types";

/** Grade 10 Science item-specific hints (overlay) */
export const G10_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g10-sci-chem-a-q01": ["Endo = heat in; exo = heat out."],
  "g10-sci-chem-a-q02": ["Rusting is slow oxidation in moist air."],
  "g10-sci-chem-a-q03": ["Compare reactivity: Zn above Cu in the series."],
  "g10-sci-chem-a-q04": ["Count atoms on both sides."],
  "g10-sci-chem-a-q05": ["Quicklime is CaO; adding water slakes it."],
  "g10-sci-chem-a-q06": ["Decomposition: one reactant \u2192 multiple products."],
  "g10-sci-chem-a-q07": ["OIL RIG: Oxidation Is Loss (of electrons)."],
  "g10-sci-chem-a-q08": ["Air and light speed up rancidity."],
  "g10-sci-chem-a-q09": ["Electrons lost by one species are gained by another."],
  "g10-sci-chem-a-q10": ["Physical changes don't make new substances."],
  "g10-sci-chem-a-q11": ["Aluminium reduces iron oxide, releasing intense heat."],
  "g10-sci-chem-a-q12": ["H\u207a from acid and OH\u207b from base form water."],
  "g10-sci-chem-a-q13": ["Reactivity: Na \u226b Cu > Au."],
  "g10-sci-chem-a-q14": ["Look for a cloudy solid forming in solution."],
  "g10-sci-chem-a-q15": ["Magnesium oxidises to magnesium oxide."],
  "g10-sci-chem-a-q16": ["Cathode = reduction = hydrogen in water electrolysis."],
  "g10-sci-chem-a-q17": ["Keep fats cool, dark, and sealed."],
  "g10-sci-chem-a-q18": ["Reducing agent donates electrons / removes oxygen."],
  "g10-sci-chem-a-q19": ["Nitrate decomposition often releases brown NO\u2082."],
  "g10-sci-chem-a-q20": ["Combination: many reactants \u2192 one product."],
  "g10-sci-chem-a-q21": ["Walls harden as carbonate forms."],
  "g10-sci-chem-a-q22": ["Zn is more reactive and oxidises first."],
  "g10-sci-chem-a-q23": ["Metal \u2192 ion is oxidation."],
  "g10-sci-chem-a-q24": ["Balance Fe, then O, then H."],
  "g10-sci-chem-b-q01": ["Exo = heat exits the system."],
  "g10-sci-chem-b-q02": ["Ask: was a new substance formed?"],
  "g10-sci-chem-b-q03": ["Swap ions; barium sulphate is insoluble."],
  "g10-sci-chem-b-q04": ["Think Statue of Liberty green layer."],
  "g10-sci-chem-b-q05": ["Metals above H\u2082 liberate hydrogen from dilute acids."],
  "g10-sci-chem-b-q06": ["Plants store light energy in chemical bonds."],
  "g10-sci-chem-b-q07": ["Limewater test for carbon dioxide."],
  "g10-sci-chem-b-q08": ["Collect and ignite carefully \u2014 pop confirms H\u2082."],
  "g10-sci-chem-b-q09": ["Glowing splint test for oxygen."],
  "g10-sci-chem-b-q10": ["Acid + base \u2192 salt + water."],
  "g10-sci-chem-b-q11": ["Count each element after balancing."],
  "g10-sci-chem-b-q12": ["Anode oxidises; cathode reduces Cu\u00b2\u207a."],
  "g10-sci-chem-b-q13": ["Colour change from new compounds = chemical."],
  "g10-sci-chem-b-q14": ["Oxidising agent gets reduced."],
  "g10-sci-chem-b-q15": ["Tin is less reactive in this use context."],
  "g10-sci-chem-b-q16": ["Living cells release heat/energy from food."],
  "g10-sci-chem-b-q17": ["Track oxygen transfer."],
  "g10-sci-chem-b-q18": ["Hydrogen gives the pop test."],
  "g10-sci-chem-b-q19": ["Carbonates + acid \u2192 carbon dioxide."],
  "g10-sci-chem-b-q20": ["Loss of oxygen = reduction of the oxide."],
  "g10-sci-chem-b-q21": ["Think acid\u2013base neutralisation."],
  "g10-sci-chem-b-q22": ["Photo = driven by light."],
  "g10-sci-chem-b-q23": ["Balance Al and Fe together."],
  "g10-sci-chem-b-q24": ["Less oxygen \u2192 slower spoilage."],
  "g10-sci-life-a-q01": ["Nutrition = how organisms get energy materials."],
  "g10-sci-life-a-q02": ["Auto = self-feeding."],
  "g10-sci-life-a-q03": ["Green plastids do photosynthesis."],
  "g10-sci-life-a-q04": ["Guard cells open and close stomata."],
  "g10-sci-life-a-q05": ["Proteases digest proteins."],
  "g10-sci-life-a-q06": ["Bile emulsifies fats."],
  "g10-sci-life-a-q07": ["Iron-containing pigment binds O\u2082."],
  "g10-sci-life-a-q08": ["Aerobic = with oxygen."],
  "g10-sci-life-a-q09": ["Yeast makes alcohol; muscles make lactate."],
  "g10-sci-life-a-q10": ["Xylem = water highway."],
  "g10-sci-life-a-q11": ["Phloem = food highway."],
  "g10-sci-life-a-q12": ["Each kidney has about a million nephrons."],
  "g10-sci-life-a-q13": ["Left ventricle \u2192 aorta \u2192 body."],
  "g10-sci-life-a-q14": ["Pulmonary artery is the exception: artery with deoxygenated blood."],
  "g10-sci-life-a-q15": ["More area \u2192 faster absorption."],
  "g10-sci-life-a-q16": ["Evaporation from leaves drives pull."],
  "g10-sci-life-a-q17": ["Liver makes urea; kidneys excrete it."],
  "g10-sci-life-a-q18": ["Clotting prevents blood loss."],
  "g10-sci-life-a-q19": ["Mitochondria = aerobic ATP factories."],
  "g10-sci-life-a-q20": ["Hetero = other-feeding."],
  "g10-sci-life-a-q21": ["Amylium = starch."],
  "g10-sci-life-a-q22": ["Think two loops: heart\u2192lungs\u2192heart\u2192body\u2192heart."],
  "g10-sci-life-a-q23": ["Kidney-bean shaped cells around the pore."],
  "g10-sci-life-a-q24": ["Dialysis cleans blood externally."],
  "g10-sci-life-b-q01": ["Carbon dioxide and water in; sugar and oxygen out."],
  "g10-sci-life-b-q02": ["Water, not CO\u2082, is the usual O\u2082 source."],
  "g10-sci-life-b-q03": ["Squeezing waves along the digestive tract."],
  "g10-sci-life-b-q04": ["Emulsify = break into droplets."],
  "g10-sci-life-b-q05": ["Thin + moist + huge area = fast diffusion."],
  "g10-sci-life-b-q06": ["Lymph nodes filter lymph."],
  "g10-sci-life-b-q07": ["Cuff + gauge for BP."],
  "g10-sci-life-b-q08": ["Cohesion\u2013tension with transpiration."],
  "g10-sci-life-b-q09": ["Liver detoxifies ammonia to urea."],
  "g10-sci-life-b-q10": ["Exchange happens at capillary beds."],
  "g10-sci-life-b-q11": ["Stomach acid is a chemical defence too."],
  "g10-sci-life-b-q12": ["Same atoms as photosynthesis reversed."],
  "g10-sci-life-b-q13": ["Especially important in leg veins."],
  "g10-sci-life-b-q14": ["First step of urine formation."],
  "g10-sci-life-b-q15": ["Unicellular holozoic nutrition."],
  "g10-sci-life-b-q16": ["Respiration charges ATP batteries."],
  "g10-sci-life-b-q17": ["Less transpiration in dry habitats."],
  "g10-sci-life-b-q18": ["ABO antibodies live in plasma."],
  "g10-sci-life-b-q19": ["Dual gland: gut enzymes and blood sugar control."],
  "g10-sci-life-b-q20": ["Match ventilation to demand."],
  "g10-sci-life-b-q21": ["Decomposers recycle nutrients."],
  "g10-sci-life-b-q22": ["Ureter from kidney; urethra exits body."],
  "g10-sci-life-b-q23": ["What you see is what isn't strongly absorbed."],
  "g10-sci-life-b-q24": ["Thicker muscle \u2192 higher pressure."],
  "g10-sci-light-a-q01": ["Measure both angles from the normal."],
  "g10-sci-light-a-q02": ["Head-on to the normal means bounce straight back."],
  "g10-sci-light-a-q03": ["Stand in front of a bathroom mirror."],
  "g10-sci-light-a-q04": ["Centre of curvature is twice the focal length away."],
  "g10-sci-light-a-q05": ["Concave = converging for real objects beyond F."],
  "g10-sci-light-a-q06": ["Negative m often means inverted image."],
  "g10-sci-light-a-q07": ["C-bound rays reverse on themselves."],
  "g10-sci-light-a-q08": ["Air \u2192 glass bends toward the normal (usually)."],
  "g10-sci-light-a-q09": ["Larger n \u2192 slower light in that medium."],
  "g10-sci-light-a-q10": ["Product n sin\u03b8 is conserved across the interface."],
  "g10-sci-light-a-q11": ["Convex lenses converge."],
  "g10-sci-light-a-q12": ["Concave lenses diverge."],
  "g10-sci-light-a-q13": ["Converging lenses have positive power."],
  "g10-sci-light-a-q14": ["Optical fibres use TIR."],
  "g10-sci-light-a-q15": ["Beyond it \u2192 TIR."],
  "g10-sci-light-a-q16": ["Spectrum from raindrops."],
  "g10-sci-light-a-q17": ["Sit close to a concave mirror."],
  "g10-sci-light-a-q18": ["Objects look smaller but more area is visible."],
  "g10-sci-light-a-q19": ["Mind the sign convention."],
  "g10-sci-light-a-q20": ["P in dioptres."],
  "g10-sci-light-a-q21": ["Virtual images cannot be screened."],
  "g10-sci-light-a-q22": ["Wave at a mirror with one hand."],
  "g10-sci-light-a-q23": ["Use mirror formula 1/v+1/u=1/f."],
  "g10-sci-light-a-q24": ["Violet bends more than red in glass."],
  "g10-sci-light-b-q01": ["Draw a perpendicular at the hit point."],
  "g10-sci-light-b-q02": ["Plane mirror: |v|=|u|, erect."],
  "g10-sci-light-b-q03": ["Parallel in \u2192 through F out."],
  "g10-sci-light-b-q04": ["Symmetric conjugate positions at C."],
  "g10-sci-light-b-q05": ["Ratio of absolute indices."],
  "g10-sci-light-b-q06": ["Lateral shift increases with thickness."],
  "g10-sci-light-b-q07": ["Planets twinkle less (extended disks)."],
  "g10-sci-light-b-q08": ["i greater than critical angle inside the core."],
  "g10-sci-light-b-q09": ["Same-size real image at 2F."],
  "g10-sci-light-b-q10": ["Myopia \u2192 diverging lens."],
  "g10-sci-light-b-q11": ["Hypermetropia \u2192 converging lens."],
  "g10-sci-light-b-q12": ["Power uses dioptre; focal length uses metre."],
  "g10-sci-light-b-q13": ["Denser optically \u2192 slower."],
  "g10-sci-light-b-q14": ["Frequency stays; wavelength changes with medium."],
  "g10-sci-light-b-q15": ["Upside-down on the screen."],
  "g10-sci-light-b-q16": ["Vertex of the mirror."],
  "g10-sci-light-b-q17": ["Divide c by n."],
  "g10-sci-light-b-q18": ["Cylinder lenses fix uneven cornea focus."],
  "g10-sci-light-b-q19": ["Think of the mirror's opening size."],
  "g10-sci-light-b-q20": ["Be consistent with one convention."],
  "g10-sci-light-b-q21": ["Apparent depth / bent stick effect."],
  "g10-sci-light-b-q22": ["Net dioptres sum."],
  "g10-sci-light-b-q23": ["Refraction needs two media."],
  "g10-sci-light-b-q24": ["Convert cm to m before taking reciprocal."],
};

