import type { HintOverlay } from "./types";

/** Grade 10 Maths item-specific hints (overlay) */
export const G10_MATHS_HINTS: Record<string, HintOverlay> = {
  "g10-maths-linear-a-q01": ["Two-variable linear \u21d2 line."],
  "g10-maths-linear-a-q02": ["Compare a1/a2, b1/b2, c1/c2."],
  "g10-maths-linear-a-q03": ["a1/a2=b1/b2\u2260c1/c2 \u21d2 inconsistent."],
  "g10-maths-linear-a-q04": ["Add/subtract to eliminate a variable."],
  "g10-maths-linear-a-q05": ["Unique \u21d4 ratios of a and b differ."],
  "g10-maths-linear-a-q06": ["Replace x, then solve the one-variable equation."],
  "g10-maths-linear-a-q07": ["Make one coefficient match, then subtract."],
  "g10-maths-linear-a-q08": ["Constant x \u21d2 vertical line."],
  "g10-maths-linear-a-q09": ["y=0 is the horizontal axis."],
  "g10-maths-linear-a-q10": ["Intercepts: set other variable to 0."],
  "g10-maths-linear-a-q11": ["Check if one equation is a scalar multiple of the other."],
  "g10-maths-linear-a-q12": ["Substitute x=2y into the second equation."],
  "g10-maths-linear-a-q13": ["Inconsistent \u21d4 parallel and distinct."],
  "g10-maths-linear-a-q14": ["Non-zero coefficient determinant \u21d2 unique intersection."],
  "g10-maths-linear-a-q15": ["Eliminate pencils, then solve for the pen cost."],
  "g10-maths-linear-a-q16": ["Compare slopes from slope-intercept form."],
  "g10-maths-linear-a-q17": ["Three geometric cases: intersect, parallel, coincide."],
  "g10-maths-linear-a-q18": ["A verified common point is a solution of the system."],
  "g10-maths-linear-a-q19": ["All three ratios equal \u21d2 infinite solutions."],
  "g10-maths-linear-a-q20": ["Origin on the line \u21d4 constant term vanishes."],
  "g10-maths-linear-a-q21": ["Clear denominators with LCM of 2 and 3."],
  "g10-maths-linear-a-q22": ["Eliminate y, solve for x."],
  "g10-maths-linear-a-q23": ["Translate words to two linear equations."],
  "g10-maths-linear-a-q24": ["Each equation alone is a line parallel to an axis."],
  "g10-maths-linear-b-q01": ["For coincident lines all three coefficient ratios match."],
  "g10-maths-linear-b-q02": ["Same slope ratio but different c ratio."],
  "g10-maths-linear-b-q03": ["Clear decimals, then eliminate."],
  "g10-maths-linear-b-q04": ["Right triangle with legs on the axes."],
  "g10-maths-linear-b-q05": ["Adding equations adds the constants too."],
  "g10-maths-linear-b-q06": ["Translate each story into a linear equation in n and d."],
  "g10-maths-linear-b-q07": ["First kilometre at 15, rest at 8."],
  "g10-maths-linear-b-q08": ["Product of slopes = \u22121."],
  "g10-maths-linear-b-q09": ["Same line twice \u21d2 dependent system."],
  "g10-maths-linear-b-q10": ["Elimination by adding."],
  "g10-maths-linear-b-q11": ["Test each pair in both equations."],
  "g10-maths-linear-b-q12": ["For no solution: a-ratio = b-ratio \u2260 c-ratio."],
  "g10-maths-linear-b-q13": ["Find intercepts by zeroing each variable."],
  "g10-maths-linear-b-q14": ["Read coordinates where the lines cross."],
  "g10-maths-linear-b-q15": ["Subtract to eliminate y."],
  "g10-maths-linear-b-q16": ["Homogeneous with non-zero determinant \u21d2 only (0,0)."],
  "g10-maths-linear-b-q17": ["Set two equations from the two time frames."],
  "g10-maths-linear-b-q18": ["Set all three coefficient ratios equal."],
  "g10-maths-linear-b-q19": ["Distance |c1\u2212c2|/\u221a(a\u00b2+b\u00b2) for same a,b."],
  "g10-maths-linear-b-q20": ["Acid balance: percent \u00d7 volume."],
  "g10-maths-linear-b-q21": ["Same a,b ratios, different c."],
  "g10-maths-linear-b-q22": ["Infinite solutions when all three ratios are equal."],
  "g10-maths-linear-b-q23": ["Equal coefficient ratios including c \u21d2 dependent."],
  "g10-maths-linear-b-q24": ["Substitute y from one equation into the other."],
  "g10-maths-poly-a-q01": ["Degree = highest power with non-zero coefficient."],
  "g10-maths-poly-a-q02": ["Find x that makes p(x)=0; try factor pairs of 6."],
  "g10-maths-poly-a-q03": ["Factor theorem: (x\u2212a) factor \u21d2 p(a)=0."],
  "g10-maths-poly-a-q04": ["Remainder on dividing by x\u2212a is p(a)."],
  "g10-maths-poly-a-q05": ["Use x\u00b2 \u2212 (sum)x + (product)."],
  "g10-maths-poly-a-q06": ["For ax\u00b2+bx+c, sum = \u2212b/a."],
  "g10-maths-poly-a-q07": ["For ax\u00b2+bx+c, product = c/a."],
  "g10-maths-poly-a-q08": ["Degree bounds the number of roots."],
  "g10-maths-poly-a-q09": ["Constant non-zero \u2192 degree 0."],
  "g10-maths-poly-a-q10": ["Factor the quadratic to find zeros."],
  "g10-maths-poly-a-q11": ["Degree 2 \u2192 parabolic graph."],
  "g10-maths-poly-a-q12": ["Substitute the known zero into p(x)."],
  "g10-maths-poly-a-q13": ["Same idea as integer division: remainder smaller than divisor."],
  "g10-maths-poly-a-q14": ["Degree 1 \u2192 exactly one root."],
  "g10-maths-poly-a-q15": ["Solve ax+b=0."],
  "g10-maths-poly-a-q16": ["Rewrite as (sum)/(product)."],
  "g10-maths-poly-a-q17": ["Polynomials need non-negative integer powers only."],
  "g10-maths-poly-a-q18": ["Use factor theorem with x=\u22121."],
  "g10-maths-poly-a-q19": ["Sum = \u2212b/a."],
  "g10-maths-poly-a-q20": ["Product = c/a."],
  "g10-maths-poly-a-q21": ["Discriminant zero means repeated root."],
  "g10-maths-poly-a-q22": ["Difference of cubes: a\u00b3\u2212b\u00b3=(a\u2212b)(a\u00b2+ab+b\u00b2)."],
  "g10-maths-poly-a-q23": ["Read the coefficient of the x\u00b9 term."],
  "g10-maths-poly-a-q24": ["Use (sum)\u00b2 \u2212 2(product)."],
  "g10-maths-poly-b-q01": ["Build from (x \u2212 each zero)."],
  "g10-maths-poly-b-q02": ["Remainder theorem: evaluate at 2."],
  "g10-maths-poly-b-q03": ["Monic quadratic from sum and product."],
  "g10-maths-poly-b-q04": ["x-intercepts are the zeros."],
  "g10-maths-poly-b-q05": ["x\u00b2 = \u22121 has no real solution."],
  "g10-maths-poly-b-q06": ["Rearrange division algorithm: g = (p \u2212 r)/q."],
  "g10-maths-poly-b-q07": ["Reciprocal zeros \u21d2 product = 1."],
  "g10-maths-poly-b-q08": ["Sum \u22123 means the middle sign is plus 3x."],
  "g10-maths-poly-b-q09": ["Apply factor theorem: evaluate at x=\u22121."],
  "g10-maths-poly-b-q10": ["deg(pq)=deg p + deg q."],
  "g10-maths-poly-b-q11": ["Use (sum)\u00b2 \u2212 4(product)."],
  "g10-maths-poly-b-q12": ["Degree n \u21d2 at most n zeros."],
  "g10-maths-poly-b-q13": ["Constant term = product of constant parts."],
  "g10-maths-poly-b-q14": ["Substitute x=1 into the polynomial."],
  "g10-maths-poly-b-q15": ["Test p(1)=0."],
  "g10-maths-poly-b-q16": ["Factor out the common (x\u22121)."],
  "g10-maths-poly-b-q17": ["Factor as product \u00d7 sum."],
  "g10-maths-poly-b-q18": ["Look at the highest power's coefficient."],
  "g10-maths-poly-b-q19": ["Include factors x and (x\u22125)."],
  "g10-maths-poly-b-q20": ["Remainder theorem with a=\u22121."],
  "g10-maths-poly-b-q21": ["Swap sum/product roles carefully: new polynomial c x\u00b2 + b x + a (reversed coeffs)."],
  "g10-maths-poly-b-q22": ["deg(p/q)=deg p \u2212 deg q when q divides p."],
  "g10-maths-poly-b-q23": ["Set discriminant to zero."],
  "g10-maths-poly-b-q24": ["Divide out (x\u22121) after confirming p(1)=0."],
  "g10-maths-real-a-q01": ["Apply Euclid: remainder is non-negative and strictly less than the divisor."],
  "g10-maths-real-a-q02": ["Keep dividing the previous divisor by the remainder until remainder 0."],
  "g10-maths-real-a-q03": ["Use HCF \u00d7 LCM = a \u00d7 b."],
  "g10-maths-real-a-q04": ["A rational has a terminating decimal iff denominator (in lowest terms) is of form 2\u1d505\u207f."],
  "g10-maths-real-a-q05": ["Perfect-square roots are rational; non-perfect-square roots are irrational."],
  "g10-maths-real-a-q06": ["Use \u221a(ab) = \u221aa \u00d7 \u221ab for non-negative a, b."],
  "g10-maths-real-a-q07": ["Add coefficients of like radical terms."],
  "g10-maths-real-a-q08": ["Multiply numerator and denominator by the surd in the denominator."],
  "g10-maths-real-a-q09": ["Integers \u2282 rationals; irrationals like \u221a2 and \u03c0 are not rational."],
  "g10-maths-real-a-q10": ["Factor completely into primes."],
  "g10-maths-real-a-q11": ["LCM uses the highest power of each prime."],
  "g10-maths-real-a-q12": ["Use Euclid's algorithm step by step."],
  "g10-maths-real-a-q13": ["Combine under one square root, then simplify."],
  "g10-maths-real-a-q14": ["Pick a non-perfect square whose root sits between the bounds."],
  "g10-maths-real-a-q15": ["For a 3-digit repeat, multiply by 10\u00b3 and subtract."],
  "g10-maths-real-a-q16": ["A non-zero rational times an irrational stays irrational."],
  "g10-maths-real-a-q17": ["Factor out the largest perfect square."],
  "g10-maths-real-a-q18": ["Perfect square \u2192 integer root; otherwise irrational."],
  "g10-maths-real-a-q19": ["Take highest power of each prime across all three."],
  "g10-maths-real-a-q20": ["Check the denominator's primes after simplifying."],
  "g10-maths-real-a-q21": ["Multiply under one radical when both are non-negative."],
  "g10-maths-real-a-q22": ["Co-prime \u21d4 HCF is 1."],
  "g10-maths-real-a-q23": ["\u221a8 = \u221a(4\u00d72) = 2\u221a2."],
  "g10-maths-real-a-q24": ["Remember: product of numbers = HCF \u00d7 LCM."],
  "g10-maths-real-b-q01": ["Remainders: 102, then 51, then 0."],
  "g10-maths-real-b-q02": ["Least common multiple of the three."],
  "g10-maths-real-b-q03": ["Simplify the fraction inside before taking the root."],
  "g10-maths-real-b-q04": ["A repeating decimal can always be written as p/q."],
  "g10-maths-real-b-q05": ["Work backwards from Euclid steps to write HCF as 65x+117y."],
  "g10-maths-real-b-q06": ["One repeating digit \u2192 multiply by 10 and subtract."],
  "g10-maths-real-b-q07": ["Simplify each radical before subtracting."],
  "g10-maths-real-b-q08": ["Adding enough to reach the next multiple of the divisor clears the remainder."],
  "g10-maths-real-b-q09": ["Primes greater than 1 aren't perfect squares."],
  "g10-maths-real-b-q10": ["Use (a\u2212b)(a+b) = a\u00b2 \u2212 b\u00b2."],
  "g10-maths-real-b-q11": ["Count min(powers of 2, powers of 5) in the factorisation."],
  "g10-maths-real-b-q12": ["Multiply by the conjugate of the denominator."],
  "g10-maths-real-b-q13": ["Rational + irrational = irrational."],
  "g10-maths-real-b-q14": ["Use a\u00d7b = HCF\u00d7LCM and solve for b."],
  "g10-maths-real-b-q15": ["Write as a fraction under the root."],
  "g10-maths-real-b-q16": ["Make all exponents in prime factors multiples of 3."],
  "g10-maths-real-b-q17": ["Denominator's primes must be only 2 and/or 5."],
  "g10-maths-real-b-q18": ["Rationalise or compute 5\u00d71.41/2."],
  "g10-maths-real-b-q19": ["Square and square root cancel for non-negative values."],
  "g10-maths-real-b-q20": ["Numbers = HCF \u00d7 ratio parts; LCM = HCF \u00d7 product of ratio parts (if co-prime parts)."],
  "g10-maths-real-b-q21": ["Add inside first; roots don't distribute over addition."],
  "g10-maths-real-b-q22": ["Think unique prime factorisation."],
  "g10-maths-real-b-q23": ["Convert the root ratio to a square ratio, then use sum."],
  "g10-maths-real-b-q24": ["Multiply by the conjugate of the denominator."],
};

