import type { HintOverlay } from "./types";

/** Grade 2 English item-specific hints (overlay) */
export const G2_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g2-eng-reading-a-q01": ["Find the time words.", "Every morning."],
  "g2-eng-reading-a-q02": ["Find the place.", "Under the table."],
  "g2-eng-reading-a-q03": ["Kind action word.", "Shared."],
  "g2-eng-reading-a-q04": ["Think of wet weather.", "Stay dry."],
  "g2-eng-reading-a-q05": ["Time clue.", "Bedtime."],
  "g2-eng-reading-a-q06": ["So shows the reason.", "Bus was late."],
  "g2-eng-reading-a-q07": ["Pick the kind act.", "Helped."],
  "g2-eng-reading-a-q08": ["Teamwork.", "Work together."],
  "g2-eng-reading-a-q09": ["Seed \u2192 water \u2192 shoots.", "Grew plants."],
  "g2-eng-reading-a-q10": ["Warning words.", "Do not touch."],
  "g2-eng-reading-a-q11": ["Feeling word.", "Proud."],
  "g2-eng-reading-a-q12": ["Quiet reading place.", "Books."],
  "g2-eng-reading-a-q13": ["Order words.", "Wash hands."],
  "g2-eng-reading-a-q14": ["Subject of the sentence.", "Moon."],
  "g2-eng-reading-a-q15": ["Match main idea.", "Kitten home."],
  "g2-eng-reading-a-q16": ["Reason given.", "Save water."],
  "g2-eng-reading-b-q01": ["Find the animal.", "Sparrows."],
  "g2-eng-reading-b-q02": ["Find where.", "Behind sofa."],
  "g2-eng-reading-b-q03": ["Polite action.", "Thanked."],
  "g2-eng-reading-b-q04": ["Wet weather tool.", "Rain."],
  "g2-eng-reading-b-q05": ["When word.", "After breakfast."],
  "g2-eng-reading-b-q06": ["So links reason.", "Rain."],
  "g2-eng-reading-b-q07": ["Kind act.", "Shared."],
  "g2-eng-reading-b-q08": ["Action in sentence.", "Fly."],
  "g2-eng-reading-b-q09": ["Common topic.", "Sorted waste."],
  "g2-eng-reading-b-q10": ["Before you cross.", "Look."],
  "g2-eng-reading-b-q11": ["On stage.", "Brave."],
  "g2-eng-reading-b-q12": ["Mail place.", "Letters."],
  "g2-eng-reading-b-q13": ["Order words.", "Leave."],
  "g2-eng-reading-b-q14": ["Time/place clue.", "Night."],
  "g2-eng-reading-b-q15": ["Main idea.", "Puppy help."],
  "g2-eng-reading-b-q16": ["Why clause.", "Save power."],
  "g2-eng-grammar-a-q01": ["One person.", "Goes."],
  "g2-eng-grammar-a-q02": ["Plural.", "Are."],
  "g2-eng-grammar-a-q03": ["Yesterday word.", "Walked."],
  "g2-eng-grammar-a-q04": ["Naming word.", "Noun."],
  "g2-eng-grammar-a-q05": ["Adjective.", "Happy."],
  "g2-eng-grammar-a-q06": ["I + have.", "Have."],
  "g2-eng-grammar-a-q07": ["Proper noun.", "Mumbai."],
  "g2-eng-grammar-a-q08": ["Time clue.", "Went."],
  "g2-eng-grammar-a-q09": ["Which or what kind.", "Noun."],
  "g2-eng-grammar-a-q10": ["Present continuous.", "Is singing."],
  "g2-eng-grammar-a-q11": ["Replace the name.", "She."],
  "g2-eng-grammar-a-q12": ["An apple.", "An."],
  "g2-eng-grammar-a-q13": ["Question word.", "Where."],
  "g2-eng-grammar-a-q14": ["All the time vs not ever.", "Never."],
  "g2-eng-grammar-a-q15": ["Adverb ending.", "Softly."],
  "g2-eng-grammar-a-q16": ["Asking.", "?"],
  "g2-eng-grammar-b-q01": ["One boy.", "Eats."],
  "g2-eng-grammar-b-q02": ["Plural we.", "Are."],
  "g2-eng-grammar-b-q03": ["Already happened.", "Jumped."],
  "g2-eng-grammar-b-q04": ["Doing word.", "Action."],
  "g2-eng-grammar-b-q05": ["Adjective.", "Bright."],
  "g2-eng-grammar-b-q06": ["She + has.", "Has."],
  "g2-eng-grammar-b-q07": ["Proper noun.", "Monday."],
  "g2-eng-grammar-b-q08": ["Time clue.", "Played."],
  "g2-eng-grammar-b-q09": ["Plural people.", "They."],
  "g2-eng-grammar-b-q10": ["Singular + continuous.", "Is."],
  "g2-eng-grammar-b-q11": ["A vs an.", "An."],
  "g2-eng-grammar-b-q12": ["Question word.", "How."],
  "g2-eng-grammar-b-q13": ["Time opposite.", "Late."],
  "g2-eng-grammar-b-q14": ["Full of care.", "Careful."],
  "g2-eng-grammar-b-q15": ["Excitement.", "!"],
  "g2-eng-grammar-b-q16": ["A cat, the sun.", "Nouns."],
  "g2-eng-words-a-q01": ["Feeling twin.", "Glad."],
  "g2-eng-words-a-q02": ["Temperature opposite.", "Cold."],
  "g2-eng-words-a-q03": ["Young dog.", "Puppy."],
  "g2-eng-words-a-q04": ["Common phrase.", "Bee."],
  "g2-eng-words-a-q05": ["Size word.", "Huge."],
  "g2-eng-words-a-q06": ["Same ending sound.", "Night."],
  "g2-eng-words-a-q07": ["Join the parts.", "Sunflower."],
  "g2-eng-words-a-q08": ["Not happy.", "Not."],
  "g2-eng-words-a-q09": ["Meaning twin.", "Start."],
  "g2-eng-words-a-q10": ["Nothing inside.", "Empty."],
  "g2-eng-words-a-q11": ["Word meaning.", "Library."],
  "g2-eng-words-a-q12": ["Noun.", "Doctor."],
  "g2-eng-words-a-q13": ["Kind word.", "Please."],
  "g2-eng-words-a-q14": ["Special plural.", "Children."],
  "g2-eng-words-a-q15": ["Job word.", "Teacher."],
  "g2-eng-words-a-q16": ["Same sound, different meaning.", "Pear."],
  "g2-eng-words-b-q01": ["Speed twin.", "Quick."],
  "g2-eng-words-b-q02": ["Shut.", "Closed."],
  "g2-eng-words-b-q03": ["Young cat.", "Kitten."],
  "g2-eng-words-b-q04": ["Common phrase.", "Feather."],
  "g2-eng-words-b-q05": ["Size word.", "Tiny."],
  "g2-eng-words-b-q06": ["-ake sound.", "Lake."],
  "g2-eng-words-b-q07": ["Join parts.", "Rainbow."],
  "g2-eng-words-b-q08": ["Do again.", "Again."],
  "g2-eng-words-b-q09": ["Meaning twin.", "Finish."],
  "g2-eng-words-b-q10": ["Distance.", "Far."],
  "g2-eng-words-b-q11": ["Word meaning.", "Market."],
  "g2-eng-words-b-q12": ["Noun.", "School."],
  "g2-eng-words-b-q13": ["Good manners.", "Thank you."],
  "g2-eng-words-b-q14": ["Special plural.", "Mice."],
  "g2-eng-words-b-q15": ["Job word.", "Driver."],
  "g2-eng-words-b-q16": ["Same sound.", "See."],
};
