import type { HintOverlay } from "./types";

/** Grade 2 Maths item-specific hints (overlay) */
export const G2_MATHS_HINTS: Record<string, HintOverlay> = {
  "g2-maths-place-a-q01": ["Tens on the left in two-digit numbers.", "4 tens."],
  "g2-maths-place-a-q02": ["Ones on the right.", "7 ones."],
  "g2-maths-place-a-q03": ["3 bundles of ten.", "3 tens."],
  "g2-maths-place-a-q04": ["Trade ten ones.", "1 ten."],
  "g2-maths-place-a-q05": ["Write tens then ones.", "25."],
  "g2-maths-place-a-q06": ["Tens value + ones value.", "30 + 8."],
  "g2-maths-place-a-q07": ["Compare tens first.", "92."],
  "g2-maths-place-a-q08": ["Left digit.", "Tens."],
  "g2-maths-place-a-q09": ["Split the digits.", "4 tens, 5 ones."],
  "g2-maths-place-a-q10": ["After 9 comes 10.", "10."],
  "g2-maths-place-a-q11": ["9 tens and 9 ones.", "99."],
  "g2-maths-place-a-q12": ["Tens then ones.", "27."],
  "g2-maths-place-a-q13": ["Packs are tens.", "34."],
  "g2-maths-place-a-q14": ["5 \u00d7 10.", "50."],
  "g2-maths-place-a-q15": ["Right digit is 0.", "Zero ones."],
  "g2-maths-place-a-q16": ["Sort first.", "25."],
  "g2-maths-place-b-q01": ["Left digit.", "6 tens."],
  "g2-maths-place-b-q02": ["Right digit.", "3 ones."],
  "g2-maths-place-b-q03": ["7 bundles of ten.", "7."],
  "g2-maths-place-b-q04": ["Write 4 then 0.", "40."],
  "g2-maths-place-b-q05": ["Place values.", "50 + 6."],
  "g2-maths-place-b-q06": ["Compare tens.", "48."],
  "g2-maths-place-b-q07": ["Right digit.", "Ones."],
  "g2-maths-place-b-q08": ["Write tens then ones.", "92."],
  "g2-maths-place-b-q09": ["10 \u00d7 10 = 100.", "10 tens."],
  "g2-maths-place-b-q10": ["Notes are tens.", "\u20b923."],
  "g2-maths-place-b-q11": ["Bundle rule.", "10 ones."],
  "g2-maths-place-b-q12": ["Ones left.", "5."],
  "g2-maths-place-b-q13": ["Tens place matters most.", "82."],
  "g2-maths-place-b-q14": ["Compare tens.", "28."],
  "g2-maths-place-b-q15": ["Right digit.", "4 ones."],
  "g2-maths-place-b-q16": ["Add two tens.", "35."],
  "g2-maths-addsub-a-q01": ["Count on five from 12.", "17."],
  "g2-maths-addsub-a-q02": ["Take away four.", "16."],
  "g2-maths-addsub-a-q03": ["Add one ten.", "25."],
  "g2-maths-addsub-a-q04": ["Take away eight.", "10."],
  "g2-maths-addsub-a-q05": ["Count on from 9.", "15."],
  "g2-maths-addsub-a-q06": ["Take away five.", "9."],
  "g2-maths-addsub-a-q07": ["Subtract gifts.", "17."],
  "g2-maths-addsub-a-q08": ["Make 10 then add.", "15."],
  "g2-maths-addsub-a-q09": ["Take one ten.", "20."],
  "g2-maths-addsub-a-q10": ["Double eleven.", "22."],
  "g2-maths-addsub-a-q11": ["Add the prices.", "\u20b913."],
  "g2-maths-addsub-a-q12": ["Take away five.", "20."],
  "g2-maths-addsub-a-q13": ["Count on four.", "20."],
  "g2-maths-addsub-a-q14": ["Take away nine.", "10."],
  "g2-maths-addsub-a-q15": ["Count on from 13.", "19."],
  "g2-maths-addsub-a-q16": ["Count back three.", "7."],
  "g2-maths-addsub-b-q01": ["Count on five.", "19."],
  "g2-maths-addsub-b-q02": ["Take away two.", "20."],
  "g2-maths-addsub-b-q03": ["Make 10 from 8 + 2, then +7.", "17."],
  "g2-maths-addsub-b-q04": ["Take away seven.", "10."],
  "g2-maths-addsub-b-q05": ["Count on four.", "25."],
  "g2-maths-addsub-b-q06": ["Take away six.", "9."],
  "g2-maths-addsub-b-q07": ["Subtract spend.", "\u20b920."],
  "g2-maths-addsub-b-q08": ["Count on from 6.", "13."],
  "g2-maths-addsub-b-q09": ["Take two tens.", "20."],
  "g2-maths-addsub-b-q10": ["Double twelve.", "24."],
  "g2-maths-addsub-b-q11": ["Add prices.", "\u20b925."],
  "g2-maths-addsub-b-q12": ["Take away eight.", "20."],
  "g2-maths-addsub-b-q13": ["Double nine.", "18."],
  "g2-maths-addsub-b-q14": ["Take away six.", "10."],
  "g2-maths-addsub-b-q15": ["Count on five.", "28."],
  "g2-maths-addsub-b-q16": ["Add three.", "15."],
  "g2-maths-timemoney-a-q01": ["Clock face.", "60."],
  "g2-maths-timemoney-a-q02": ["Hour hand shorter.", "3."],
  "g2-maths-timemoney-a-q03": ["Add the rupees.", "\u20b915."],
  "g2-maths-timemoney-a-q04": ["Sun to Sat.", "7."],
  "g2-maths-timemoney-a-q05": ["Think of the day cycle.", "Night, then morning."],
  "g2-maths-timemoney-a-q06": ["Add coins.", "\u20b93."],
  "g2-maths-timemoney-a-q07": ["Half hour = 30 minutes.", "2:30."],
  "g2-maths-timemoney-a-q08": ["Compare amounts.", "\u20b920."],
  "g2-maths-timemoney-a-q09": ["Day and night.", "24."],
  "g2-maths-timemoney-a-q10": ["Subtract price.", "\u20b910."],
  "g2-maths-timemoney-a-q11": ["Shorter = hour.", "Hour hand."],
  "g2-maths-timemoney-a-q12": ["5 + 5.", "\u20b910."],
  "g2-maths-timemoney-a-q13": ["Daytime.", "Morning."],
  "g2-maths-timemoney-a-q14": ["Bigger value.", "\u20b95."],
  "g2-maths-timemoney-a-q15": ["Quarter of 60 is 15.", "4:15."],
  "g2-maths-timemoney-a-q16": ["Subtract.", "\u20b93."],
  "g2-maths-timemoney-b-q01": ["Same as minutes in an hour.", "60."],
  "g2-maths-timemoney-b-q02": ["Bottom of clock.", "6."],
  "g2-maths-timemoney-b-q03": ["Take away five rupees.", "\u20b915."],
  "g2-maths-timemoney-b-q04": ["Seven days.", "Week."],
  "g2-maths-timemoney-b-q05": ["Day order.", "After."],
  "g2-maths-timemoney-b-q06": ["Three twos.", "\u20b96."],
  "g2-maths-timemoney-b-q07": ["30 minutes past.", "5:30."],
  "g2-maths-timemoney-b-q08": ["Compare.", "\u20b99."],
  "g2-maths-timemoney-b-q09": ["Middle of day.", "Noon."],
  "g2-maths-timemoney-b-q10": ["Compare money to price.", "Yes."],
  "g2-maths-timemoney-b-q11": ["Longer = minutes.", "Minute hand."],
  "g2-maths-timemoney-b-q12": ["Two tens.", "\u20b920."],
  "g2-maths-timemoney-b-q13": ["Day cycle.", "Evening."],
  "g2-maths-timemoney-b-q14": ["Same value.", "5."],
  "g2-maths-timemoney-b-q15": ["To means before.", "2:45."],
  "g2-maths-timemoney-b-q16": ["Subtract.", "\u20b910."],
};
