import type { HintOverlay } from "./types";

/** Grade 2 Science item-specific hints (overlay) */
export const G2_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g2-sci-plants-a-q01": ["Baby plant wakes up.", "Water and warmth."],
  "g2-sci-plants-a-q02": ["Green kitchen.", "Sunlight."],
  "g2-sci-plants-a-q03": ["Hidden part.", "Under."],
  "g2-sci-plants-a-q04": ["Life cycle.", "Flower."],
  "g2-sci-plants-a-q05": ["Under soil food.", "Carrot."],
  "g2-sci-plants-a-q06": ["Like a pipe.", "Water."],
  "g2-sci-plants-a-q07": ["Fresh air.", "Oxygen."],
  "g2-sci-plants-a-q08": ["Weak stem.", "Support."],
  "g2-sci-plants-a-q09": ["Grain food.", "Wheat."],
  "g2-sci-plants-a-q10": ["Sleeping seed.", "Dormant."],
  "g2-sci-plants-a-q11": ["Leaf colour.", "Green."],
  "g2-sci-plants-a-q12": ["Travel.", "Wind and animals."],
  "g2-sci-plants-a-q13": ["Eyes grow shoots.", "Stem."],
  "g2-sci-plants-a-q14": ["Lives in water.", "Aquatic."],
  "g2-sci-plants-a-q15": ["Be kind.", "Care."],
  "g2-sci-plants-a-q16": ["Food making.", "Leaf."],
  "g2-sci-plants-b-q01": ["Just sprouted.", "Young."],
  "g2-sci-plants-b-q02": ["Bees visit.", "Colour and smell."],
  "g2-sci-plants-b-q03": ["Support.", "Stem."],
  "g2-sci-plants-b-q04": ["Cut and see.", "Inside."],
  "g2-sci-plants-b-q05": ["Green leafy.", "Spinach."],
  "g2-sci-plants-b-q06": ["Grow needs.", "Sunlight."],
  "g2-sci-plants-b-q07": ["Dry place plant.", "Stem."],
  "g2-sci-plants-b-q08": ["Odd one out.", "Games."],
  "g2-sci-plants-b-q09": ["Useful trees.", "Shade and air."],
  "g2-sci-plants-b-q10": ["Sprouting.", "Grow."],
  "g2-sci-plants-b-q11": ["Plant pipes.", "Stem."],
  "g2-sci-plants-b-q12": ["Aquatic.", "Lotus."],
  "g2-sci-plants-b-q13": ["Crops.", "Food."],
  "g2-sci-plants-b-q14": ["Soil food.", "Compost."],
  "g2-sci-plants-b-q15": ["Hold support.", "Climb."],
  "g2-sci-plants-b-q16": ["Needs light.", "Weak."],
  "g2-sci-animals-a-q01": ["Cow, goat, deer.", "Herbivore."],
  "g2-sci-animals-a-q02": ["Lion, tiger.", "Carnivore."],
  "g2-sci-animals-a-q03": ["Flight.", "Wings."],
  "g2-sci-animals-a-q04": ["In water.", "Gills."],
  "g2-sci-animals-a-q05": ["Plant eater.", "Herbivore."],
  "g2-sci-animals-a-q06": ["Long sleep.", "Bear."],
  "g2-sci-animals-a-q07": ["Count insect legs.", "Six."],
  "g2-sci-animals-a-q08": ["Pond life.", "Tadpole."],
  "g2-sci-animals-a-q09": ["Living needs.", "Air and shelter."],
  "g2-sci-animals-a-q10": ["Mixed diet.", "Omnivore."],
  "g2-sci-animals-a-q11": ["Desert animal.", "Hump."],
  "g2-sci-animals-a-q12": ["Warm fibre.", "Sheep."],
  "g2-sci-animals-a-q13": ["Owl, bat.", "Night."],
  "g2-sci-animals-a-q14": ["Home.", "Birds."],
  "g2-sci-animals-a-q15": ["Keep safe.", "Protect."],
  "g2-sci-animals-a-q16": ["Skeleton inside.", "Dog."],
  "g2-sci-animals-b-q01": ["Plant diet.", "Herbivore."],
  "g2-sci-animals-b-q02": ["Hunter.", "Carnivore."],
  "g2-sci-animals-b-q03": ["Water bird.", "Webbed."],
  "g2-sci-animals-b-q04": ["Not true fish.", "Mammal."],
  "g2-sci-animals-b-q05": ["From nectar.", "Bees."],
  "g2-sci-animals-b-q06": ["Birds fly far.", "Travel."],
  "g2-sci-animals-b-q07": ["Count carefully.", "Eight."],
  "g2-sci-animals-b-q08": ["Life cycle.", "Butterfly."],
  "g2-sci-animals-b-q09": ["Be kind.", "Care."],
  "g2-sci-animals-b-q10": ["Hole home.", "Rabbit."],
  "g2-sci-animals-b-q11": ["Useful nose.", "Trunk."],
  "g2-sci-animals-b-q12": ["Thread.", "Silkworm."],
  "g2-sci-animals-b-q13": ["Opposite of nocturnal.", "Day."],
  "g2-sci-animals-b-q14": ["Bee home.", "Bees."],
  "g2-sci-animals-b-q15": ["Be safe and kind.", "Do not hurt."],
  "g2-sci-animals-b-q16": ["Bird.", "Hen."],
  "g2-sci-airwater-a-q01": ["Life need.", "Air."],
  "g2-sci-airwater-a-q02": ["Feel it on your face.", "Wind."],
  "g2-sci-airwater-a-q03": ["Three forms.", "Vapour."],
  "g2-sci-airwater-a-q04": ["Frozen.", "Solid."],
  "g2-sci-airwater-a-q05": ["Health.", "Clean."],
  "g2-sci-airwater-a-q06": ["Water cycle.", "Clouds."],
  "g2-sci-airwater-a-q07": ["Heat change.", "Steam."],
  "g2-sci-airwater-a-q08": ["We feel it as wind.", "Cannot see."],
  "g2-sci-airwater-a-q09": ["Close the tap.", "Do not waste."],
  "g2-sci-airwater-a-q10": ["Soft moving air.", "Gentle."],
  "g2-sci-airwater-a-q11": ["Gills help.", "Oxygen."],
  "g2-sci-airwater-a-q12": ["Sun helps.", "Evaporates."],
  "g2-sci-airwater-a-q13": ["Daily use.", "Drink and clean."],
  "g2-sci-airwater-a-q14": ["Hard to breathe.", "Polluted."],
  "g2-sci-airwater-a-q15": ["Sky water.", "Droplets."],
  "g2-sci-airwater-a-q16": ["Hygiene.", "Clean."],
  "g2-sci-airwater-b-q01": ["Useful air.", "Dry and kites."],
  "g2-sci-airwater-b-q02": ["From boiling.", "Gas."],
  "g2-sci-airwater-b-q03": ["Safe water.", "Rivers and taps."],
  "g2-sci-airwater-b-q04": ["Heat softens ice.", "Water."],
  "g2-sci-airwater-b-q05": ["Strong wind.", "Dangerous."],
  "g2-sci-airwater-b-q06": ["Living need.", "Air."],
  "g2-sci-airwater-b-q07": ["Good habit.", "Saves."],
  "g2-sci-airwater-b-q08": ["Misty air.", "Air."],
  "g2-sci-airwater-b-q09": ["Drink clean water.", "Ill."],
  "g2-sci-airwater-b-q10": ["Even if unseen.", "Space."],
  "g2-sci-airwater-b-q11": ["Sun lifts water.", "Evaporation."],
  "g2-sci-airwater-b-q12": ["Keep water clean.", "Rivers."],
  "g2-sci-airwater-b-q13": ["Feel the breeze.", "Air."],
  "g2-sci-airwater-b-q14": ["Cold weather.", "Solid."],
  "g2-sci-airwater-b-q15": ["Lungs.", "Breathing."],
  "g2-sci-airwater-b-q16": ["Kills germs.", "Safer."],
};
