import type { HintOverlay } from "./types";

/** Grade 3 English item-specific hints (overlay) — Synonyms chapter */
export const G3_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g3-eng-synonyms-a-q01": ["Think of a good feeling after good news.", "Angry is not a twin of happy."],
  "g3-eng-synonyms-a-q02": ["Picture an elephant — big or large both fit.", "Small means the opposite size."],
  "g3-eng-synonyms-a-q03": ["Quick means not taking long.", "Try each option in the sentence."],
  "g3-eng-synonyms-a-q04": ["Begin means to get going.", "End and finish are not twins of begin."],
  "g3-eng-synonyms-a-q05": ["Brave people face hard things without running away.", "Scared is not a synonym of brave."],
  "g3-eng-synonyms-a-q06": ["Small things take little space.", "Huge is the opposite size."],
  "g3-eng-synonyms-a-q07": ["Quiet places have little sound.", "Noisy means lots of sound."],
  "g3-eng-synonyms-a-q08": ["Smart can mean good at thinking.", "Sleepy is not about thinking well."],
  "g3-eng-synonyms-a-q09": ["Think of something wrapped for a birthday.", "A problem is not a gift."],
  "g3-eng-synonyms-a-q10": ["End means something is over.", "Start is the opposite of end."],
  "g3-eng-synonyms-a-q11": ["Tasty food makes you smile while eating.", "Bitter is a different kind of taste."],
  "g3-eng-synonyms-a-q12": ["Sad is not a cheerful feeling.", "Joyful is closer to happy, not sad."],
  "g3-eng-synonyms-a-q13": ["In maths, hard means not easy.", "Soft is about touch, not about a sum."],
  "g3-eng-synonyms-a-q14": ["Kind people help and share.", "Rude is not a twin of kind."],
  "g3-eng-synonyms-a-q15": ["Scared means feeling fear.", "Brave is closer to the opposite."],
  "g3-eng-synonyms-a-q16": ["Pretty describes something lovely to see.", "Ugly is the opposite idea."],
  "g3-eng-synonyms-a-q17": ["Dirty clothes need washing.", "Clean is the opposite of dirty."],
  "g3-eng-synonyms-a-q18": ["Easy tasks do not take much struggle.", "Tough is closer to hard."],
  "g3-eng-synonyms-a-q19": ["Help means make someone's job lighter.", "Ignore means you do not help."],
  "g3-eng-synonyms-a-q20": ["Shout is a loud voice.", "Whisper is soft, not loud."],
  "g3-eng-synonyms-a-q21": ["Jump means leave the ground for a moment.", "Crawl stays close to the ground."],
  "g3-eng-synonyms-a-q22": ["Cold makes you want a sweater.", "Hot is the opposite feeling."],
  "g3-eng-synonyms-a-q23": ["Polite people say please and thank you.", "Rude is not a synonym of polite."],
  "g3-eng-synonyms-a-q24": ["Near means a short distance.", "Far is the opposite of near."],
  "g3-eng-synonyms-b-q01": ["Angry is a strong upset feeling.", "Calm is closer to the opposite."],
  "g3-eng-synonyms-b-q02": ["Heavy things are hard to lift.", "Light is the opposite of heavy."],
  "g3-eng-synonyms-b-q03": ["Laugh is a happy sound.", "Cry is not a twin of laugh."],
  "g3-eng-synonyms-b-q04": ["Neat rooms have things in place.", "Messy is the opposite of neat."],
  "g3-eng-synonyms-b-q05": ["Strong can mean full of power.", "Weak is the opposite of strong."],
  "g3-eng-synonyms-b-q06": ["Talk uses your voice and words.", "Run is a different action."],
  "g3-eng-synonyms-b-q07": ["Rich can mean having much money.", "Poor is the opposite idea."],
  "g3-eng-synonyms-b-q08": ["Bright things give light or look clear.", "Dark is closer to the opposite."],
  "g3-eng-synonyms-b-q09": ["Correct answers match the truth.", "Wrong is the opposite of correct."],
  "g3-eng-synonyms-b-q10": ["Buy means you pay and take something home.", "Sell means you give it away for money."],
  "g3-eng-synonyms-b-q11": ["Old things have been around a long time.", "New is the opposite of old."],
  "g3-eng-synonyms-b-q12": ["Tired means you need rest.", "Energetic is the opposite feeling."],
  "g3-eng-synonyms-b-q13": ["Empty means nothing is inside.", "Full is the opposite of empty."],
  "g3-eng-synonyms-b-q14": ["Cry often comes with tears.", "Laugh is not a twin of cry."],
  "g3-eng-synonyms-b-q15": ["Careful people think before they act.", "Careless is the opposite of careful."],
  "g3-eng-synonyms-b-q16": ["A friend is someone you like to be with.", "Enemy is the opposite idea."],
  "g3-eng-synonyms-b-q17": ["Hot things have heat.", "Icy is the opposite kind of feeling."],
  "g3-eng-synonyms-b-q18": ["Slowly means not fast.", "Quickly is the opposite of slowly."],
  "g3-eng-synonyms-b-q19": ["Look uses your eyes.", "Ignore means you turn away."],
  "g3-eng-synonyms-b-q20": ["Funny things make you laugh.", "Boring is not a twin of funny."],
  "g3-eng-synonyms-b-q21": ["Wet things have water on them.", "Dry is the opposite of wet."],
  "g3-eng-synonyms-b-q22": ["Huge means very big.", "Tiny is the opposite size."],
  "g3-eng-synonyms-b-q23": ["Thin means not wide or thick.", "Thick is closer to the opposite."],
  "g3-eng-synonyms-b-q24": ["Proud is a good feeling after doing well.", "Ashamed is closer to the opposite."],
};
