import type { HintOverlay } from "./types";

/** Grade 3 English item-specific hints (overlay) — Synonyms + Antonyms + Grammar */
export const G3_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g3-eng-synonyms-a-q01": ["Think of a good feeling after good news.", "Angry is not a twin of happy."],
  "g3-eng-synonyms-a-q02": ["Picture an elephant — big or large both fit.", "Small means the opposite size."],
  "g3-eng-synonyms-a-q03": ["Quick means not taking long.", "Try each option in the sentence."],
  "g3-eng-synonyms-a-q04": ["Begin means to get going.", "End and finish are not twins of begin."],
  "g3-eng-synonyms-a-q05": ["Brave people face hard things without running away.", "Scared is not a synonym of brave."],
  "g3-eng-synonyms-a-q06": ["Small things take little space.", "Huge is the opposite size."],
  "g3-eng-synonyms-a-q07": ["Quiet places have little sound.", "Noisy means lots of sound."],
  "g3-eng-synonyms-a-q08": ["Smart can mean good at thinking.", "Sleepy is not about thinking well."],
  "g3-eng-synonyms-a-q09": ["Think of something wrapped for a birthday.", "A problem is not a gift."],
  "g3-eng-synonyms-a-q10": ["End means something is over.", "Start is the opposite of end."],
  "g3-eng-synonyms-a-q11": ["Tasty food makes you smile while eating.", "Bitter is a different kind of taste."],
  "g3-eng-synonyms-a-q12": ["Sad is not a cheerful feeling.", "Joyful is closer to happy, not sad."],
  "g3-eng-synonyms-a-q13": ["In maths, hard means not easy.", "Soft is about touch, not about a sum."],
  "g3-eng-synonyms-a-q14": ["Kind people help and share.", "Rude is not a twin of kind."],
  "g3-eng-synonyms-a-q15": ["Scared means feeling fear.", "Brave is closer to the opposite."],
  "g3-eng-synonyms-a-q16": ["Pretty describes something lovely to see.", "Ugly is the opposite idea."],
  "g3-eng-synonyms-a-q17": ["Dirty clothes need washing.", "Clean is the opposite of dirty."],
  "g3-eng-synonyms-a-q18": ["Easy tasks do not take much struggle.", "Tough is closer to hard."],
  "g3-eng-synonyms-a-q19": ["Help means make someone's job lighter.", "Ignore means you do not help."],
  "g3-eng-synonyms-a-q20": ["Shout is a loud voice.", "Whisper is soft, not loud."],
  "g3-eng-synonyms-a-q21": ["Jump means leave the ground for a moment.", "Crawl stays close to the ground."],
  "g3-eng-synonyms-a-q22": ["Cold makes you want a sweater.", "Hot is the opposite feeling."],
  "g3-eng-synonyms-a-q23": ["Polite people say please and thank you.", "Rude is not a synonym of polite."],
  "g3-eng-synonyms-a-q24": ["Near means a short distance.", "Far is the opposite of near."],
  "g3-eng-synonyms-b-q01": ["Angry is a strong upset feeling.", "Calm is closer to the opposite."],
  "g3-eng-synonyms-b-q02": ["Heavy things are hard to lift.", "Light is the opposite of heavy."],
  "g3-eng-synonyms-b-q03": ["Laugh is a happy sound.", "Cry is not a twin of laugh."],
  "g3-eng-synonyms-b-q04": ["Neat rooms have things in place.", "Messy is the opposite of neat."],
  "g3-eng-synonyms-b-q05": ["Strong can mean full of power.", "Weak is the opposite of strong."],
  "g3-eng-synonyms-b-q06": ["Talk uses your voice and words.", "Run is a different action."],
  "g3-eng-synonyms-b-q07": ["Rich can mean having much money.", "Poor is the opposite idea."],
  "g3-eng-synonyms-b-q08": ["Bright things give light or look clear.", "Dark is closer to the opposite."],
  "g3-eng-synonyms-b-q09": ["Correct answers match the truth.", "Wrong is the opposite of correct."],
  "g3-eng-synonyms-b-q10": ["Buy means you pay and take something home.", "Sell means you give it away for money."],
  "g3-eng-synonyms-b-q11": ["Old things have been around a long time.", "New is the opposite of old."],
  "g3-eng-synonyms-b-q12": ["Tired means you need rest.", "Energetic is the opposite feeling."],
  "g3-eng-synonyms-b-q13": ["Empty means nothing is inside.", "Full is the opposite of empty."],
  "g3-eng-synonyms-b-q14": ["Cry often comes with tears.", "Laugh is not a twin of cry."],
  "g3-eng-synonyms-b-q15": ["Careful people think before they act.", "Careless is the opposite of careful."],
  "g3-eng-synonyms-b-q16": ["A friend is someone you like to be with.", "Enemy is the opposite idea."],
  "g3-eng-synonyms-b-q17": ["Hot things have heat.", "Icy is the opposite kind of feeling."],
  "g3-eng-synonyms-b-q18": ["Slowly means not fast.", "Quickly is the opposite of slowly."],
  "g3-eng-synonyms-b-q19": ["Look uses your eyes.", "Ignore means you turn away."],
  "g3-eng-synonyms-b-q20": ["Funny things make you laugh.", "Boring is not a twin of funny."],
  "g3-eng-synonyms-b-q21": ["Wet things have water on them.", "Dry is the opposite of wet."],
  "g3-eng-synonyms-b-q22": ["Huge means very big.", "Tiny is the opposite size."],
  "g3-eng-synonyms-b-q23": ["Thin means not wide or thick.", "Thick is closer to the opposite."],
  "g3-eng-synonyms-b-q24": ["Proud is a good feeling after doing well.", "Ashamed is closer to the opposite."],
  "g3-eng-antonyms-a-q01": ["Happy is a cheerful feeling.", "Glad and joyful are twins of happy, not opposites."],
  "g3-eng-antonyms-a-q02": ["Think of an ant next to an elephant.", "Large is a twin of big, not an opposite."],
  "g3-eng-antonyms-a-q03": ["Hot makes you want a fan.", "Warm is closer to hot than to cold."],
  "g3-eng-antonyms-a-q04": ["Up points toward the sky.", "Above is not the opposite of up."],
  "g3-eng-antonyms-a-q05": ["Full means filled up.", "Packed is closer to full, not empty."],
  "g3-eng-antonyms-a-q06": ["Early means before the usual time.", "Soon is not the opposite of early."],
  "g3-eng-antonyms-a-q07": ["Strong people can lift heavy things.", "Powerful is a twin of strong, not an opposite."],
  "g3-eng-antonyms-a-q08": ["An open door lets you walk through.", "Think of a door you cannot walk through."],
  "g3-eng-antonyms-a-q09": ["Day is when the sun is out.", "Morning is still part of the day."],
  "g3-eng-antonyms-a-q10": ["Clean clothes look washed.", "Neat is closer to clean, not dirty."],
  "g3-eng-antonyms-a-q11": ["Fast means taking little time.", "Quick is a twin of fast, not an opposite."],
  "g3-eng-antonyms-a-q12": ["Tall people reach high shelves.", "High is not the opposite of tall."],
  "g3-eng-antonyms-a-q13": ["Kind people help and share.", "Caring is a twin of kind, not an opposite."],
  "g3-eng-antonyms-a-q14": ["A pillow feels soft.", "Fluffy is not the opposite of soft."],
  "g3-eng-antonyms-a-q15": ["Light bags are easy to carry.", "Empty is about how full something is, not always about weight."],
  "g3-eng-antonyms-a-q16": ["Near means a short walk away.", "Close is a twin of near, not an opposite."],
  "g3-eng-antonyms-a-q17": ["Begin means to get going.", "Start means nearly the same as begin."],
  "g3-eng-antonyms-a-q18": ["Wet things have water on them.", "Damp means a little wet, not dry."],
  "g3-eng-antonyms-a-q19": ["Noisy places have lots of sound.", "Loud is a twin of noisy, not an opposite."],
  "g3-eng-antonyms-a-q20": ["Rich can mean having much money.", "Wealthy is a twin of rich, not an opposite."],
  "g3-eng-antonyms-a-q21": ["Correct answers match the truth.", "Right is a twin of correct, not an opposite."],
  "g3-eng-antonyms-a-q22": ["Brave people face hard things.", "Courageous means nearly the same as brave."],
  "g3-eng-antonyms-a-q23": ["Buy means you pay and take something home.", "Think of what the shopkeeper does."],
  "g3-eng-antonyms-a-q24": ["A thick book has many pages.", "Wide is not the clear opposite of thick."],
  "g3-eng-antonyms-b-q01": ["Old things have been around a long time.", "Ancient means very old, not new."],
  "g3-eng-antonyms-b-q02": ["Before means earlier than something.", "Earlier is not the opposite of before."],
  "g3-eng-antonyms-b-q03": ["Above means higher than something.", "Over is closer to above, not below."],
  "g3-eng-antonyms-b-q04": ["Inside means in the box.", "Within is a twin of inside, not an opposite."],
  "g3-eng-antonyms-b-q05": ["Win means you come first or beat the other side.", "Cheer is not the opposite of win."],
  "g3-eng-antonyms-b-q06": ["Love means you like something a lot.", "Like is not the opposite of love."],
  "g3-eng-antonyms-b-q07": ["A sharp pencil writes a thin line.", "Pointed is closer to sharp, not blunt."],
  "g3-eng-antonyms-b-q08": ["Sweet foods like ladoos taste sugary.", "Sugary is a twin of sweet, not an opposite."],
  "g3-eng-antonyms-b-q09": ["In class, hard means not easy to solve.", "Difficult means nearly the same as hard."],
  "g3-eng-antonyms-b-q10": ["Give means you hand something to someone.", "Offer is closer to give, not take."],
  "g3-eng-antonyms-b-q11": ["Push moves something away from you.", "Shove is a strong push, not a pull."],
  "g3-eng-antonyms-b-q12": ["Remember means keep something in your mind.", "Recall means nearly the same as remember."],
  "g3-eng-antonyms-b-q13": ["Arrive means you get to a place.", "Reach is closer to arrive, not leave."],
  "g3-eng-antonyms-b-q14": ["Polite people say please and thank you.", "Courteous is a twin of polite, not an opposite."],
  "g3-eng-antonyms-b-q15": ["A wide road has lots of space across.", "Broad is a twin of wide, not an opposite."],
  "g3-eng-antonyms-b-q16": ["A friend is someone you like to be with.", "Buddy means nearly the same as friend."],
  "g3-eng-antonyms-b-q17": ["Laugh is a happy sound.", "Giggle is a light laugh, not an opposite."],
  "g3-eng-antonyms-b-q18": ["Bright places have lots of light.", "Shiny is closer to bright, not dark."],
  "g3-eng-antonyms-b-q19": ["First means at the beginning.", "Next means the one after, not the opposite of first."],
  "g3-eng-antonyms-b-q20": ["High means far up from the ground.", "Up is not the opposite of high."],
  "g3-eng-antonyms-b-q21": ["Young means not many years old.", "Small is about size, not age."],
  "g3-eng-antonyms-b-q22": ["Huge means very big.", "Enormous is a twin of huge, not an opposite."],
  "g3-eng-antonyms-b-q23": ["A deep well goes far down.", "Wide is about how broad something is, not how deep."],
  "g3-eng-antonyms-b-q24": ["Proud is a good feeling after doing well.", "Pleased is closer to proud, not ashamed."],
  "g3-eng-grammar-a-q01": ["A noun names a person, place, or thing.", "Run tells an action, not a name."],
  "g3-eng-grammar-a-q02": ["Find the word that names a thing.", "Packed tells what Riya did."],
  "g3-eng-grammar-a-q03": ["Proper nouns are special names of people or places.", "City and river are common nouns."],
  "g3-eng-grammar-a-q04": ["Some plurals do not just add -s.", "Never say childrens."],
  "g3-eng-grammar-a-q05": ["A verb tells what someone does.", "Table names a thing, not an action."],
  "g3-eng-grammar-a-q06": ["Choose the action word that fits the blank.", "Sky names a place, not an action."],
  "g3-eng-grammar-a-q07": ["Kabir = he (one person).", "With he/she/it in the present, many verbs add -es or -s."],
  "g3-eng-grammar-a-q08": ["They means more than one.", "Use are with we/you/they."],
  "g3-eng-grammar-a-q09": ["An adjective tells more about a noun.", "Cat names an animal; fluffy describes it."],
  "g3-eng-grammar-a-q10": ["Find the word that describes the tree.", "Tree names the thing; tall tells what kind."],
  "g3-eng-grammar-a-q11": ["Pick a word that describes the mango.", "Eat is an action, not a describing word."],
  "g3-eng-grammar-a-q12": ["Look for a word that describes a noun.", "Loud tells what kind of drum."],
  "g3-eng-grammar-a-q13": ["Listen for the first sound of the next word.", "Apple begins with a vowel sound, so use an."],
  "g3-eng-grammar-a-q14": ["Book begins with a consonant sound.", "Use a before consonant sounds; an before vowel sounds."],
  "g3-eng-grammar-a-q15": ["Check the first sound of ice.", "Ice starts with i \u2014 a vowel sound."],
  "g3-eng-grammar-a-q16": ["The often means that one we both know.", "A/an mean any one; the means a known one."],
  "g3-eng-grammar-a-q17": ["Yesterday = past time.", "Go and goes are present forms."],
  "g3-eng-grammar-a-q18": ["Every day = present habit.", "Rose is past; rising needs a helping verb."],
  "g3-eng-grammar-a-q19": ["Past tense means the action already happened.", "Look for the -ed form or a past word like played."],
  "g3-eng-grammar-a-q20": ["Right now = happening at this moment.", "Is + verb-ing shows an action in progress."],
  "g3-eng-grammar-a-q21": ["Questions need a capital and a ?", "Where should start with a capital W."],
  "g3-eng-grammar-a-q22": ["Does the sentence show strong feeling?", "What a\u2026 often ends with !"],
  "g3-eng-grammar-a-q23": ["People's names need capitals.", "Kabir is a name."],
  "g3-eng-grammar-a-q24": ["Sentences start with a capital and usually end with a full stop.", "Ravi is a name, so it needs a capital."],
  "g3-eng-grammar-b-q01": ["A noun names a person, place, or thing.", "Sing is an action word."],
  "g3-eng-grammar-b-q02": ["Common nouns are general names, not special names.", "Asha is a special name (proper noun)."],
  "g3-eng-grammar-b-q03": ["Proper nouns are special names.", "Teacher and school are common nouns."],
  "g3-eng-grammar-b-q04": ["Words ending in x, s, sh, or ch often add -es.", "Box + es = boxes."],
  "g3-eng-grammar-b-q05": ["A verb tells what someone does.", "Desk is a noun."],
  "g3-eng-grammar-b-q06": ["Choose the action that fits.", "Song names a thing, not an action."],
  "g3-eng-grammar-b-q07": ["She = one person.", "With he/she/it, use goes not go."],
  "g3-eng-grammar-b-q08": ["Remember: I am, you are, he/she is.", "Never say I is or I are."],
  "g3-eng-grammar-b-q09": ["An adjective describes a noun.", "Noisy tells what kind of sound or place."],
  "g3-eng-grammar-b-q10": ["Find the describing word.", "Sweet tells what the ladoo tastes like."],
  "g3-eng-grammar-b-q11": ["Pick a word that describes the puppy.", "Ran is a verb; quickly tells how."],
  "g3-eng-grammar-b-q12": ["The adjective tells what kind of drink.", "Drink is the noun."],
  "g3-eng-grammar-b-q13": ["Listen to the first sound of umbrella.", "Umbrella starts with a vowel sound \u2192 an."],
  "g3-eng-grammar-b-q14": ["Dog begins with d \u2014 a consonant.", "Use a before consonant sounds."],
  "g3-eng-grammar-b-q15": ["Orange starts with o \u2014 a vowel sound.", "Use an before vowel sounds."],
  "g3-eng-grammar-b-q16": ["The is used for something unique or already known.", "We say the sun and the moon."],
  "g3-eng-grammar-b-q17": ["Last week = past time.", "Watch/watches are present forms."],
  "g3-eng-grammar-b-q18": ["Every morning = present habit.", "Made is past."],
  "g3-eng-grammar-b-q19": ["Present tense is happening now or as a habit.", "Baked already happened."],
  "g3-eng-grammar-b-q20": ["Look! points to something happening now.", "Is + verb-ing = action in progress."],
  "g3-eng-grammar-b-q21": ["Questions start with a capital and end with ?", "How needs a capital H."],
  "g3-eng-grammar-b-q22": ["Strong commands or feelings often use !", "Stop shows urgency."],
  "g3-eng-grammar-b-q23": ["The word I and place names need capitals.", "Mumbai is a proper noun."],
  "g3-eng-grammar-b-q24": ["This asks something \u2014 use a question mark.", "Start with a capital letter."],
};
