import type { HintOverlay } from "./types";

/** Grade 3 English item-specific hints (overlay) — Synonyms + Antonyms */
export const G3_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g3-eng-synonyms-a-q01": ["Think of a good feeling after good news.", "Angry is not a twin of happy."],
  "g3-eng-synonyms-a-q02": ["Picture an elephant — big or large both fit.", "Small means the opposite size."],
  "g3-eng-synonyms-a-q03": ["Quick means not taking long.", "Try each option in the sentence."],
  "g3-eng-synonyms-a-q04": ["Begin means to get going.", "End and finish are not twins of begin."],
  "g3-eng-synonyms-a-q05": ["Brave people face hard things without running away.", "Scared is not a synonym of brave."],
  "g3-eng-synonyms-a-q06": ["Small things take little space.", "Huge is the opposite size."],
  "g3-eng-synonyms-a-q07": ["Quiet places have little sound.", "Noisy means lots of sound."],
  "g3-eng-synonyms-a-q08": ["Smart can mean good at thinking.", "Sleepy is not about thinking well."],
  "g3-eng-synonyms-a-q09": ["Think of something wrapped for a birthday.", "A problem is not a gift."],
  "g3-eng-synonyms-a-q10": ["End means something is over.", "Start is the opposite of end."],
  "g3-eng-synonyms-a-q11": ["Tasty food makes you smile while eating.", "Bitter is a different kind of taste."],
  "g3-eng-synonyms-a-q12": ["Sad is not a cheerful feeling.", "Joyful is closer to happy, not sad."],
  "g3-eng-synonyms-a-q13": ["In maths, hard means not easy.", "Soft is about touch, not about a sum."],
  "g3-eng-synonyms-a-q14": ["Kind people help and share.", "Rude is not a twin of kind."],
  "g3-eng-synonyms-a-q15": ["Scared means feeling fear.", "Brave is closer to the opposite."],
  "g3-eng-synonyms-a-q16": ["Pretty describes something lovely to see.", "Ugly is the opposite idea."],
  "g3-eng-synonyms-a-q17": ["Dirty clothes need washing.", "Clean is the opposite of dirty."],
  "g3-eng-synonyms-a-q18": ["Easy tasks do not take much struggle.", "Tough is closer to hard."],
  "g3-eng-synonyms-a-q19": ["Help means make someone's job lighter.", "Ignore means you do not help."],
  "g3-eng-synonyms-a-q20": ["Shout is a loud voice.", "Whisper is soft, not loud."],
  "g3-eng-synonyms-a-q21": ["Jump means leave the ground for a moment.", "Crawl stays close to the ground."],
  "g3-eng-synonyms-a-q22": ["Cold makes you want a sweater.", "Hot is the opposite feeling."],
  "g3-eng-synonyms-a-q23": ["Polite people say please and thank you.", "Rude is not a synonym of polite."],
  "g3-eng-synonyms-a-q24": ["Near means a short distance.", "Far is the opposite of near."],
  "g3-eng-synonyms-b-q01": ["Angry is a strong upset feeling.", "Calm is closer to the opposite."],
  "g3-eng-synonyms-b-q02": ["Heavy things are hard to lift.", "Light is the opposite of heavy."],
  "g3-eng-synonyms-b-q03": ["Laugh is a happy sound.", "Cry is not a twin of laugh."],
  "g3-eng-synonyms-b-q04": ["Neat rooms have things in place.", "Messy is the opposite of neat."],
  "g3-eng-synonyms-b-q05": ["Strong can mean full of power.", "Weak is the opposite of strong."],
  "g3-eng-synonyms-b-q06": ["Talk uses your voice and words.", "Run is a different action."],
  "g3-eng-synonyms-b-q07": ["Rich can mean having much money.", "Poor is the opposite idea."],
  "g3-eng-synonyms-b-q08": ["Bright things give light or look clear.", "Dark is closer to the opposite."],
  "g3-eng-synonyms-b-q09": ["Correct answers match the truth.", "Wrong is the opposite of correct."],
  "g3-eng-synonyms-b-q10": ["Buy means you pay and take something home.", "Sell means you give it away for money."],
  "g3-eng-synonyms-b-q11": ["Old things have been around a long time.", "New is the opposite of old."],
  "g3-eng-synonyms-b-q12": ["Tired means you need rest.", "Energetic is the opposite feeling."],
  "g3-eng-synonyms-b-q13": ["Empty means nothing is inside.", "Full is the opposite of empty."],
  "g3-eng-synonyms-b-q14": ["Cry often comes with tears.", "Laugh is not a twin of cry."],
  "g3-eng-synonyms-b-q15": ["Careful people think before they act.", "Careless is the opposite of careful."],
  "g3-eng-synonyms-b-q16": ["A friend is someone you like to be with.", "Enemy is the opposite idea."],
  "g3-eng-synonyms-b-q17": ["Hot things have heat.", "Icy is the opposite kind of feeling."],
  "g3-eng-synonyms-b-q18": ["Slowly means not fast.", "Quickly is the opposite of slowly."],
  "g3-eng-synonyms-b-q19": ["Look uses your eyes.", "Ignore means you turn away."],
  "g3-eng-synonyms-b-q20": ["Funny things make you laugh.", "Boring is not a twin of funny."],
  "g3-eng-synonyms-b-q21": ["Wet things have water on them.", "Dry is the opposite of wet."],
  "g3-eng-synonyms-b-q22": ["Huge means very big.", "Tiny is the opposite size."],
  "g3-eng-synonyms-b-q23": ["Thin means not wide or thick.", "Thick is closer to the opposite."],
  "g3-eng-synonyms-b-q24": ["Proud is a good feeling after doing well.", "Ashamed is closer to the opposite."],
  "g3-eng-antonyms-a-q01": ["Happy is a cheerful feeling.", "Glad and joyful are twins of happy, not opposites."],
  "g3-eng-antonyms-a-q02": ["Think of an ant next to an elephant.", "Large is a twin of big, not an opposite."],
  "g3-eng-antonyms-a-q03": ["Hot makes you want a fan.", "Warm is closer to hot than to cold."],
  "g3-eng-antonyms-a-q04": ["Up points toward the sky.", "Above is not the opposite of up."],
  "g3-eng-antonyms-a-q05": ["Full means filled up.", "Packed is closer to full, not empty."],
  "g3-eng-antonyms-a-q06": ["Early means before the usual time.", "Soon is not the opposite of early."],
  "g3-eng-antonyms-a-q07": ["Strong people can lift heavy things.", "Powerful is a twin of strong, not an opposite."],
  "g3-eng-antonyms-a-q08": ["An open door lets you walk through.", "Think of a door you cannot walk through."],
  "g3-eng-antonyms-a-q09": ["Day is when the sun is out.", "Morning is still part of the day."],
  "g3-eng-antonyms-a-q10": ["Clean clothes look washed.", "Neat is closer to clean, not dirty."],
  "g3-eng-antonyms-a-q11": ["Fast means taking little time.", "Quick is a twin of fast, not an opposite."],
  "g3-eng-antonyms-a-q12": ["Tall people reach high shelves.", "High is not the opposite of tall."],
  "g3-eng-antonyms-a-q13": ["Kind people help and share.", "Caring is a twin of kind, not an opposite."],
  "g3-eng-antonyms-a-q14": ["A pillow feels soft.", "Fluffy is not the opposite of soft."],
  "g3-eng-antonyms-a-q15": ["Light bags are easy to carry.", "Empty is about how full something is, not always about weight."],
  "g3-eng-antonyms-a-q16": ["Near means a short walk away.", "Close is a twin of near, not an opposite."],
  "g3-eng-antonyms-a-q17": ["Begin means to get going.", "Start means nearly the same as begin."],
  "g3-eng-antonyms-a-q18": ["Wet things have water on them.", "Damp means a little wet, not dry."],
  "g3-eng-antonyms-a-q19": ["Noisy places have lots of sound.", "Loud is a twin of noisy, not an opposite."],
  "g3-eng-antonyms-a-q20": ["Rich can mean having much money.", "Wealthy is a twin of rich, not an opposite."],
  "g3-eng-antonyms-a-q21": ["Correct answers match the truth.", "Right is a twin of correct, not an opposite."],
  "g3-eng-antonyms-a-q22": ["Brave people face hard things.", "Courageous means nearly the same as brave."],
  "g3-eng-antonyms-a-q23": ["Buy means you pay and take something home.", "Think of what the shopkeeper does."],
  "g3-eng-antonyms-a-q24": ["A thick book has many pages.", "Wide is not the clear opposite of thick."],
  "g3-eng-antonyms-b-q01": ["Old things have been around a long time.", "Ancient means very old, not new."],
  "g3-eng-antonyms-b-q02": ["Before means earlier than something.", "Earlier is not the opposite of before."],
  "g3-eng-antonyms-b-q03": ["Above means higher than something.", "Over is closer to above, not below."],
  "g3-eng-antonyms-b-q04": ["Inside means in the box.", "Within is a twin of inside, not an opposite."],
  "g3-eng-antonyms-b-q05": ["Win means you come first or beat the other side.", "Cheer is not the opposite of win."],
  "g3-eng-antonyms-b-q06": ["Love means you like something a lot.", "Like is not the opposite of love."],
  "g3-eng-antonyms-b-q07": ["A sharp pencil writes a thin line.", "Pointed is closer to sharp, not blunt."],
  "g3-eng-antonyms-b-q08": ["Sweet foods like ladoos taste sugary.", "Sugary is a twin of sweet, not an opposite."],
  "g3-eng-antonyms-b-q09": ["In class, hard means not easy to solve.", "Difficult means nearly the same as hard."],
  "g3-eng-antonyms-b-q10": ["Give means you hand something to someone.", "Offer is closer to give, not take."],
  "g3-eng-antonyms-b-q11": ["Push moves something away from you.", "Shove is a strong push, not a pull."],
  "g3-eng-antonyms-b-q12": ["Remember means keep something in your mind.", "Recall means nearly the same as remember."],
  "g3-eng-antonyms-b-q13": ["Arrive means you get to a place.", "Reach is closer to arrive, not leave."],
  "g3-eng-antonyms-b-q14": ["Polite people say please and thank you.", "Courteous is a twin of polite, not an opposite."],
  "g3-eng-antonyms-b-q15": ["A wide road has lots of space across.", "Broad is a twin of wide, not an opposite."],
  "g3-eng-antonyms-b-q16": ["A friend is someone you like to be with.", "Buddy means nearly the same as friend."],
  "g3-eng-antonyms-b-q17": ["Laugh is a happy sound.", "Giggle is a light laugh, not an opposite."],
  "g3-eng-antonyms-b-q18": ["Bright places have lots of light.", "Shiny is closer to bright, not dark."],
  "g3-eng-antonyms-b-q19": ["First means at the beginning.", "Next means the one after, not the opposite of first."],
  "g3-eng-antonyms-b-q20": ["High means far up from the ground.", "Up is not the opposite of high."],
  "g3-eng-antonyms-b-q21": ["Young means not many years old.", "Small is about size, not age."],
  "g3-eng-antonyms-b-q22": ["Huge means very big.", "Enormous is a twin of huge, not an opposite."],
  "g3-eng-antonyms-b-q23": ["A deep well goes far down.", "Wide is about how broad something is, not how deep."],
  "g3-eng-antonyms-b-q24": ["Proud is a good feeling after doing well.", "Pleased is closer to proud, not ashamed."],
};
