import type { HintOverlay } from "./types";

/** Grade 3 Maths item-specific hints (overlay; survives content re-ingest) */
export const G3_MATHS_HINTS: Record<string, HintOverlay> = {
  "g3-maths-numbers-a-q01": ["Read hundreds, tens and ones from the figure, then join them."],
  "g3-maths-numbers-a-q02": ["Read hundreds, tens and ones from the figure, then join them."],
  "g3-maths-numbers-a-q03": ["Match the number name to hundreds, tens and ones — put 0 in empty places."],
  "g3-maths-numbers-a-q04": ["Just after / successor means one more."],
  "g3-maths-numbers-a-q05": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-a-q06": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-a-q07": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-a-q08": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-a-q09": ["Just before / predecessor means one less."],
  "g3-maths-numbers-a-q10": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q11": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-a-q12": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-a-q13": ["Find the jump size on the line, then count jumps to the point."],
  "g3-maths-numbers-a-q14": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-a-q15": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-a-q16": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q17": ["Ten tens make one hundred — scale that up to reach 200."],
  "g3-maths-numbers-a-q18": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-a-q19": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q20": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q21": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q22": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q23": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-a-q24": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-b-q01": ["Find the jump size on the line, then count jumps to the point."],
  "g3-maths-numbers-b-q02": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q03": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q04": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q05": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q06": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-b-q07": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q08": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-b-q09": ["Just before / predecessor means one less."],
  "g3-maths-numbers-b-q10": ["Read hundreds, tens and ones from the figure, then join them."],
  "g3-maths-numbers-b-q11": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-b-q12": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q13": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q14": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-b-q15": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-b-q16": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q17": ["Ten hundreds make one thousand."],
  "g3-maths-numbers-b-q18": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q19": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q20": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q21": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q22": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q23": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q24": ["Find what is added or taken each time, then do that again."],
  "g3-maths-addsub-a-q01": ["Add ones, then tens, then hundreds — line the places up."],
  "g3-maths-addsub-a-q02": ["When ones add to 10 or more, write the ones digit and carry 1 ten."],
  "g3-maths-addsub-a-q03": ["Carry carefully from ones to tens, then from tens to hundreds."],
  "g3-maths-addsub-a-q04": ["Subtract ones, then tens, then hundreds when no borrowing is needed."],
  "g3-maths-addsub-a-q05": ["If ones are too small, borrow 1 ten (that makes 10 ones)."],
  "g3-maths-addsub-a-q06": ["When you see zeros, borrow step by step from the next place that has a digit."],
  "g3-maths-addsub-a-q07": ["Join the two amounts — this is an addition story."],
  "g3-maths-addsub-a-q08": ["Together means add the two scores."],
  "g3-maths-addsub-a-q09": ["To find the missing addend, subtract the known number from the total."],
  "g3-maths-addsub-a-q10": ["The missing number is the difference between 720 and 385."],
  "g3-maths-addsub-a-q11": ["To check a subtraction, add the answer to the number you subtracted."],
  "g3-maths-addsub-a-q12": ["Round each number to the nearest hundred, then add."],
  "g3-maths-addsub-a-q13": ["Add two numbers first, then add the third."],
  "g3-maths-addsub-a-q14": ["Re-add the ones carefully — he may have forgotten the carry."],
  "g3-maths-addsub-a-q15": ["Gives out means take away — subtract."],
  "g3-maths-addsub-a-q16": ["Ones make 11, so carry 1 ten into the tens place."],
  "g3-maths-addsub-a-q17": ["Borrow from the hundreds when tens and ones need help."],
  "g3-maths-addsub-a-q18": ["If a + b = c, then c − a = b."],
  "g3-maths-addsub-a-q19": ["Work out each sum, then compare the totals."],
  "g3-maths-addsub-a-q20": ["Change = money given − price. Subtract carefully."],
  "g3-maths-addsub-a-q21": ["Adding 100 only changes the hundreds place."],
  "g3-maths-addsub-a-q22": ["Double of a number means that number plus itself."],
  "g3-maths-addsub-a-q23": ["Left means subtract the amount used from the total."],
  "g3-maths-addsub-a-q24": ["Add the stamps she gets, then subtract the ones she gives away."],
  "g3-maths-addsub-b-q01": ["Add ones, then tens, then hundreds — line the places up."],
  "g3-maths-addsub-b-q02": ["When ones add to 10 or more, write the ones digit and carry 1 ten."],
  "g3-maths-addsub-b-q03": ["Carry carefully from ones to tens, then from tens to hundreds."],
  "g3-maths-addsub-b-q04": ["Subtract ones, then tens, then hundreds when no borrowing is needed."],
  "g3-maths-addsub-b-q05": ["If ones are too small, borrow 1 ten (that makes 10 ones)."],
  "g3-maths-addsub-b-q06": ["When you see zeros, borrow step by step from the next place that has a digit."],
  "g3-maths-addsub-b-q07": ["Join the two amounts — this is an addition story."],
  "g3-maths-addsub-b-q08": ["Total score means add both teams' points."],
  "g3-maths-addsub-b-q09": ["To find the missing addend, subtract the known number from the total."],
  "g3-maths-addsub-b-q10": ["The missing number is the difference between 605 and 278."],
  "g3-maths-addsub-b-q11": ["To check a subtraction, add the answer to the number you subtracted."],
  "g3-maths-addsub-b-q12": ["Round each number to the nearest hundred, then add."],
  "g3-maths-addsub-b-q13": ["Add two numbers first, then add the third."],
  "g3-maths-addsub-b-q14": ["Re-add the ones carefully — she may have forgotten the carry."],
  "g3-maths-addsub-b-q15": ["Take away means subtract."],
  "g3-maths-addsub-b-q16": ["Ones make 15, so carry 1 ten into the tens place."],
  "g3-maths-addsub-b-q17": ["Borrow from the hundreds when tens and ones need help."],
  "g3-maths-addsub-b-q18": ["If a + b = c, then c − a = b."],
  "g3-maths-addsub-b-q19": ["Work out each sum, then compare the totals."],
  "g3-maths-addsub-b-q20": ["Change = money given − price. Subtract carefully."],
  "g3-maths-addsub-b-q21": ["Adding 200 only changes the hundreds place."],
  "g3-maths-addsub-b-q22": ["Double of a number means that number plus itself."],
  "g3-maths-addsub-b-q23": ["Left means subtract the amount sold from the total."],
  "g3-maths-addsub-b-q24": ["Add the marbles he wins, then subtract the ones he gives away."],
  "g3-maths-multiply-a-q01": ["Think of 6 groups of 4, or skip-count by 4 six times."],
  "g3-maths-multiply-a-q02": ["Count how many times 5 is added — that is the other factor."],
  "g3-maths-multiply-a-q03": ["Array → multiply rows by how many in each row."],
  "g3-maths-multiply-a-q04": ["Order can swap when multiplying — the product stays the same."],
  "g3-maths-multiply-a-q05": ["Any number times 1 stays the same."],
  "g3-maths-multiply-a-q06": ["Any number times 0 is 0."],
  "g3-maths-multiply-a-q07": ["Equal groups → multiply the number of boxes by idlis in each."],
  "g3-maths-multiply-a-q08": ["Same price each notebook → multiply ₹8 by 5."],
  "g3-maths-multiply-a-q09": ["Which number in the 7 times table makes 56?"],
  "g3-maths-multiply-a-q10": ["Five equal jumps of 5 means 5 × 5."],
  "g3-maths-multiply-a-q11": ["Rows × plants in a row: 4 × 9."],
  "g3-maths-multiply-a-q12": ["Work out each product, then compare."],
  "g3-maths-multiply-a-q13": ["Use an 8 times fact, or 8 × 5 then add one more 8."],
  "g3-maths-multiply-a-q14": ["Re-check 4 × 7 — he may have used 4 × 6 by mistake."],
  "g3-maths-multiply-a-q15": ["Equal bags → multiply bags by mangoes in each bag."],
  "g3-maths-multiply-a-q16": ["Double means two groups — multiply by 2."],
  "g3-maths-multiply-a-q17": ["Three friends each buy the same amount — multiply."],
  "g3-maths-multiply-a-q18": ["If a × b = c, then b × a = c too."],
  "g3-maths-multiply-a-q19": ["Round 19 to 20, then multiply by 3."],
  "g3-maths-multiply-a-q20": ["Same ticket price → multiply ₹12 by 3."],
  "g3-maths-multiply-a-q21": ["× 10 puts a zero after the other number."],
  "g3-maths-multiply-a-q22": ["Which number times 4 makes 36?"],
  "g3-maths-multiply-a-q23": ["Same price each ladoo → multiply ₹5 by 8."],
  "g3-maths-multiply-a-q24": ["Multiply packs first, then subtract the crayons she gives away."],
  "g3-maths-multiply-b-q01": ["Think of 7 groups of 3, or skip-count by 3 seven times."],
  "g3-maths-multiply-b-q02": ["Count how many times 4 is added — that is the other factor."],
  "g3-maths-multiply-b-q03": ["Array → multiply rows by stamps in each row."],
  "g3-maths-multiply-b-q04": ["Order can swap when multiplying — the product stays the same."],
  "g3-maths-multiply-b-q05": ["Any number times 1 stays the same."],
  "g3-maths-multiply-b-q06": ["Any number times 0 is 0."],
  "g3-maths-multiply-b-q07": ["Equal thalis → multiply thalis by puris on each."],
  "g3-maths-multiply-b-q08": ["Same price each pencil → multiply ₹9 by 6."],
  "g3-maths-multiply-b-q09": ["Which number in the 6 times table makes 48?"],
  "g3-maths-multiply-b-q10": ["Four equal jumps of 4 means 4 × 4."],
  "g3-maths-multiply-b-q11": ["Rows × desks in a row: 3 × 8."],
  "g3-maths-multiply-b-q12": ["Work out each product, then compare."],
  "g3-maths-multiply-b-q13": ["Use a 9 times fact, or 10 × 5 then subtract one 5."],
  "g3-maths-multiply-b-q14": ["Re-check 5 × 8 — she may have used 5 × 7 by mistake."],
  "g3-maths-multiply-b-q15": ["Equal packets → multiply packets by biscuits in each."],
  "g3-maths-multiply-b-q16": ["Double means two groups — multiply by 2."],
  "g3-maths-multiply-b-q17": ["Four children each plant the same amount — multiply."],
  "g3-maths-multiply-b-q18": ["If a × b = c, then b × a = c too."],
  "g3-maths-multiply-b-q19": ["Round 21 to 20, then multiply by 4."],
  "g3-maths-multiply-b-q20": ["Same ticket price → multiply ₹15 by 2."],
  "g3-maths-multiply-b-q21": ["× 10 puts a zero after the other number."],
  "g3-maths-multiply-b-q22": ["Which number times 7 makes 42?"],
  "g3-maths-multiply-b-q23": ["Same price each packet → multiply ₹4 by 9."],
  "g3-maths-multiply-b-q24": ["Multiply boxes first, then subtract the erasers he gives away."],
};
