import type { HintOverlay } from "./types";

/** Grade 3 Maths item-specific hints (overlay; survives content re-ingest) */
export const G3_MATHS_HINTS: Record<string, HintOverlay> = {
  "g3-maths-numbers-a-q01": ["Read hundreds, tens and ones from the figure, then join them."],
  "g3-maths-numbers-a-q02": ["Read hundreds, tens and ones from the figure, then join them."],
  "g3-maths-numbers-a-q03": ["Match the number name to hundreds, tens and ones — put 0 in empty places."],
  "g3-maths-numbers-a-q04": ["Just after / successor means one more."],
  "g3-maths-numbers-a-q05": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-a-q06": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-a-q07": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-a-q08": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-a-q09": ["Just before / predecessor means one less."],
  "g3-maths-numbers-a-q10": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q11": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-a-q12": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-a-q13": ["Find the jump size on the line, then count jumps to the point."],
  "g3-maths-numbers-a-q14": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-a-q15": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-a-q16": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q17": ["Ten tens make one hundred — scale that up to reach 200."],
  "g3-maths-numbers-a-q18": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-a-q19": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q20": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q21": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q22": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-a-q23": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-a-q24": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-b-q01": ["Find the jump size on the line, then count jumps to the point."],
  "g3-maths-numbers-b-q02": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q03": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q04": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q05": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q06": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-b-q07": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q08": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-b-q09": ["Just before / predecessor means one less."],
  "g3-maths-numbers-b-q10": ["Read hundreds, tens and ones from the figure, then join them."],
  "g3-maths-numbers-b-q11": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-b-q12": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q13": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q14": ["Compare from the left: hundreds, then tens, then ones."],
  "g3-maths-numbers-b-q15": ["Find what is added or taken each time, then do that again."],
  "g3-maths-numbers-b-q16": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q17": ["Ten hundreds make one thousand."],
  "g3-maths-numbers-b-q18": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q19": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q20": ["Look at the figure first; read every label before choosing."],
  "g3-maths-numbers-b-q21": ["Use place value to build, compare, or calculate as asked."],
  "g3-maths-numbers-b-q22": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q23": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g3-maths-numbers-b-q24": ["Find what is added or taken each time, then do that again."],
};

