import type { HintOverlay } from "./types";

/** Grade 3 Science item-specific hints (overlay; survives content re-ingest) */
export const G3_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g3-sci-animals-a-q01": ["Animals that eat only plants are herbivores."],
  "g3-sci-animals-a-q02": ["Animals that eat only plants are herbivores."],
  "g3-sci-animals-a-q03": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-a-q04": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q05": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q06": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-a-q07": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-a-q08": ["Animals that eat other animals are carnivores."],
  "g3-sci-animals-a-q09": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q10": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q11": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-a-q12": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-a-q13": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q14": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-a-q15": ["Animals that eat both plants and animals are omnivores."],
  "g3-sci-animals-a-q16": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q17": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q18": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-a-q19": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-a-q20": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-a-q21": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q22": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-a-q23": ["Animals that eat only plants are herbivores."],
  "g3-sci-animals-a-q24": ["Animals that eat both plants and animals are omnivores."],
  "g3-sci-animals-b-q01": ["Animals that eat only plants are herbivores."],
  "g3-sci-animals-b-q02": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-b-q03": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-b-q04": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q05": ["Animals that eat only plants are herbivores."],
  "g3-sci-animals-b-q06": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q07": ["Animals that eat both plants and animals are omnivores."],
  "g3-sci-animals-b-q08": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q09": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q10": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-b-q11": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q12": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q13": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-b-q14": ["Birds have feathers and beaks — use those clues."],
  "g3-sci-animals-b-q15": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-b-q16": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-b-q17": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q18": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q19": ["Think what the animal eats and where it lives."],
  "g3-sci-animals-b-q20": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q21": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-animals-b-q22": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-b-q23": ["Look at the animal or arrows in the figure; match food or home."],
  "g3-sci-animals-b-q24": ["Match the animal to its natural home: land, water, trees, or burrow."],
  "g3-sci-plants-a-q01": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-plants-a-q02": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-a-q03": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-plants-a-q04": ["Leaves make food for the plant using sunlight."],
  "g3-sci-plants-a-q05": ["Flowers help the plant make fruits and seeds."],
  "g3-sci-plants-a-q06": ["Fruits hold seeds that can grow into new plants."],
  "g3-sci-plants-a-q07": ["Leaves make food for the plant using sunlight."],
  "g3-sci-plants-a-q08": ["Leaves make food for the plant using sunlight."],
  "g3-sci-plants-a-q09": ["Fruits hold seeds that can grow into new plants."],
  "g3-sci-plants-a-q10": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-a-q11": ["Look at the labelled parts in the figure; match each part to its job."],
  "g3-sci-plants-a-q12": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-a-q13": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-plants-a-q14": ["Fruits hold seeds that can grow into new plants."],
  "g3-sci-plants-a-q15": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-a-q16": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-a-q17": ["Flowers help the plant make fruits and seeds."],
  "g3-sci-plants-a-q18": ["Look at the labelled parts in the figure; match each part to its job."],
  "g3-sci-plants-a-q19": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-a-q20": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-plants-a-q21": ["Leaves make food for the plant using sunlight."],
  "g3-sci-plants-a-q22": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-a-q23": ["Flowers help the plant make fruits and seeds."],
  "g3-sci-plants-a-q24": ["Look at the labelled parts in the figure; match each part to its job."],
  "g3-sci-plants-b-q01": ["The stem or trunk holds the plant up and carries water upward."],
  "g3-sci-plants-b-q02": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-plants-b-q03": ["Fruits hold seeds that can grow into new plants."],
  "g3-sci-plants-b-q04": ["Leaves make food for the plant using sunlight."],
  "g3-sci-plants-b-q05": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-b-q06": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-b-q07": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-b-q08": ["Fruits hold seeds that can grow into new plants."],
  "g3-sci-plants-b-q09": ["The stem or trunk holds the plant up and carries water upward."],
  "g3-sci-plants-b-q10": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-b-q11": ["Look at the labelled parts in the figure; match each part to its job."],
  "g3-sci-plants-b-q12": ["Look at the labelled parts in the figure; match each part to its job."],
  "g3-sci-plants-b-q13": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-plants-b-q14": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-b-q15": ["Look at the labelled parts in the figure; match each part to its job."],
  "g3-sci-plants-b-q16": ["Flowers help the plant make fruits and seeds."],
  "g3-sci-plants-b-q17": ["Look at the labelled parts in the figure; match each part to its job."],
  "g3-sci-plants-b-q18": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-b-q19": ["Recall each plant part's job: root, stem, leaf, flower, fruit, seed."],
  "g3-sci-plants-b-q20": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-plants-b-q21": ["Some stems store food underground — look for buds or eyes."],
  "g3-sci-plants-b-q22": ["Leaves make food for the plant using sunlight."],
  "g3-sci-plants-b-q23": ["The stem or trunk holds the plant up and carries water upward."],
  "g3-sci-plants-b-q24": ["Roots grow under the soil — they drink water and hold the plant."],
  "g3-sci-senses-a-q01": ["Eyes help us see — find the eye on the face."],
  "g3-sci-senses-a-q02": ["Ears help us hear sounds."],
  "g3-sci-senses-a-q03": ["The nose helps us smell."],
  "g3-sci-senses-a-q04": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-a-q05": ["Skin covers the body and helps us feel touch, heat and cold."],
  "g3-sci-senses-a-q06": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-a-q07": ["Skin covers the body and helps us feel touch, heat and cold."],
  "g3-sci-senses-a-q08": ["Ears help us hear sounds."],
  "g3-sci-senses-a-q09": ["The tongue helps us taste food."],
  "g3-sci-senses-a-q10": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-a-q11": ["Match each face label in the figure to the sense asked."],
  "g3-sci-senses-a-q12": ["Ears help us hear — find the ear on the face."],
  "g3-sci-senses-a-q13": ["Match each face label in the figure to the sense asked."],
  "g3-sci-senses-a-q14": ["Skin covers the body and helps us feel touch, heat and cold."],
  "g3-sci-senses-a-q15": ["Eyes help us see — find the eye on the face."],
  "g3-sci-senses-a-q16": ["The tongue helps us taste food."],
  "g3-sci-senses-a-q17": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-a-q18": ["The nose helps us smell."],
  "g3-sci-senses-a-q19": ["Match each face label in the figure to the sense asked."],
  "g3-sci-senses-a-q20": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-a-q21": ["Eyes help us see colours, shapes and movement."],
  "g3-sci-senses-a-q22": ["Eyes help us see colours, shapes and movement."],
  "g3-sci-senses-a-q23": ["Ears help us hear sounds."],
  "g3-sci-senses-a-q24": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q01": ["The tongue helps us taste food."],
  "g3-sci-senses-b-q02": ["Skin covers the body and helps us feel touch, heat and cold."],
  "g3-sci-senses-b-q03": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q04": ["The tongue helps us taste food."],
  "g3-sci-senses-b-q05": ["Ears help us hear — find the ear on the face."],
  "g3-sci-senses-b-q06": ["The nose helps us smell."],
  "g3-sci-senses-b-q07": ["The tongue helps us taste food."],
  "g3-sci-senses-b-q08": ["Eyes help us see colours, shapes and movement."],
  "g3-sci-senses-b-q09": ["Skin covers the body and helps us feel touch, heat and cold."],
  "g3-sci-senses-b-q10": ["The tongue helps us taste food."],
  "g3-sci-senses-b-q11": ["Match each face label in the figure to the sense asked."],
  "g3-sci-senses-b-q12": ["Eyes help us see — find the eye on the face."],
  "g3-sci-senses-b-q13": ["Ears help us hear — find the ear on the face."],
  "g3-sci-senses-b-q14": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q15": ["Match each face label in the figure to the sense asked."],
  "g3-sci-senses-b-q16": ["Skin covers the body and helps us feel touch, heat and cold."],
  "g3-sci-senses-b-q17": ["The tongue helps us taste food."],
  "g3-sci-senses-b-q18": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q19": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q20": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q21": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q22": ["Eyes help us see — find the eye on the face."],
  "g3-sci-senses-b-q23": ["Match each sense to its body part: eyes, ears, nose, tongue, skin."],
  "g3-sci-senses-b-q24": ["Match each face label in the figure to the sense asked."],
};

