import type { HintOverlay } from "./types";

/** Grade 4 English item-specific hints (overlay) */
export const G4_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g4-eng-ch01-a-q01": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q02": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q04": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q06": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q08": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q09": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q10": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q11": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q12": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q13": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q14": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q15": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q16": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q17": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q18": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q19": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q20": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q21": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q23": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q24": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q01": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q02": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q04": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q06": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q08": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q09": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q10": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q11": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q12": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q13": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q14": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q15": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q16": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q17": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q18": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q19": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q20": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q21": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q22": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q23": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q24": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch02-a-q01": ["A proper noun is a special name and starts with a capital letter."],
  "g4-eng-ch02-a-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q03": ["Use an before a vowel sound; use a before a consonant sound."],
  "g4-eng-ch02-a-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q05": ["An adjective describes a noun — which word tells more about a thing?"],
  "g4-eng-ch02-a-q06": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q07": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q08": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q09": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q10": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q11": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q12": ["A proper noun is a special name and starts with a capital letter."],
  "g4-eng-ch02-a-q13": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q14": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g4-eng-ch02-a-q15": ["Match the verb form to the time and the subject in the sentence."],
  "g4-eng-ch02-a-q16": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-a-q17": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-a-q18": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q19": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-a-q20": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-a-q21": ["Use an before a vowel sound; use a before a consonant sound."],
  "g4-eng-ch02-a-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q23": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q24": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q01": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch02-b-q02": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-b-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q05": ["Use an before a vowel sound; use a before a consonant sound."],
  "g4-eng-ch02-b-q06": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q07": ["Match the verb form to the time and the subject in the sentence."],
  "g4-eng-ch02-b-q08": ["A preposition shows relation (in, on, under, with…)."],
  "g4-eng-ch02-b-q09": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q10": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q11": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q12": ["A common noun is a general name for a person, place, or thing."],
  "g4-eng-ch02-b-q13": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q14": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q15": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q16": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q17": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q18": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-b-q19": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-b-q20": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-b-q21": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-b-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q23": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q24": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch03-a-q01": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-a-q02": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-a-q03": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q04": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-a-q05": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q06": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q07": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q08": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q09": ["Join the two smaller words to make one compound word."],
  "g4-eng-ch03-a-q10": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q11": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q12": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-a-q13": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q14": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q15": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q16": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q17": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q18": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q19": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q20": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q21": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q22": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q23": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q24": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q01": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-b-q02": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q03": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-b-q04": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q05": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q06": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q07": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q08": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q09": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-b-q10": ["Join the two smaller words to make one compound word."],
  "g4-eng-ch03-b-q11": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q12": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q13": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q14": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q15": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-b-q16": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q17": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q18": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q19": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q20": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-b-q21": ["Join the two smaller words to make one compound word."],
  "g4-eng-ch03-b-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q23": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q24": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch04-a-q01": ["Look for May I or Could I with please.", "A polite request asks, not orders."],
  "g4-eng-ch04-a-q02": ["Match the greeting to the time of day and the person.", "Ma'am shows respect for a grown-up."],
  "g4-eng-ch04-a-q03": ["Find the librarian's instruction.", "Return means bring the book back."],
  "g4-eng-ch04-a-q04": ["Polite asks often use Could I or May I.", "Cross out bossy orders."],
  "g4-eng-ch04-a-q05": ["Think about respectful ways children speak to elders.", "It is not always a family uncle."],
  "g4-eng-ch04-a-q06": ["Kind closings invite the person back.", "Cross out rude or cold lines."],
  "g4-eng-ch04-a-q07": ["Mother is in a meeting — she cannot talk now.", "Taking a message is helpful and polite."],
  "g4-eng-ch04-a-q08": ["Good phone manners start with a clear name.", "Cross out abrupt or rude openings."],
  "g4-eng-ch04-a-q09": ["Copy the caller's exact reason for calling.", "Ignore details that were never said."],
  "g4-eng-ch04-a-q10": ["Excuse me softens an interruption.", "He asks before sharpening his pencil."],
  "g4-eng-ch04-a-q11": ["Own the mistake gently.", "Cross out rude or careless replies."],
  "g4-eng-ch04-a-q12": ["Match greeting to morning/afternoon/evening.", "Use a respectful name for elders."],
  "g4-eng-ch04-a-q13": ["Accidents need a quick sorry.", "Ask if the other person is okay."],
  "g4-eng-ch04-a-q14": ["Polite requests ask; they do not grab.", "Please softens the ask."],
  "g4-eng-ch04-a-q15": ["Thank you pairs with You're welcome.", "Cross out cold or boastful replies."],
  "g4-eng-ch04-a-q16": ["Evening greeting matches after sunset.", "Uncle is respectful for an older guard."],
  "g4-eng-ch04-a-q17": ["Decline with thank you.", "Never insult the food or the giver."],
  "g4-eng-ch04-a-q18": ["Start with Excuse me for strangers.", "Add please to the question."],
  "g4-eng-ch04-a-q19": ["Tech glitches need a calm explanation.", "Check that the other person can hear you."],
  "g4-eng-ch04-a-q20": ["Celebrate others' wins.", "Cross out jealous or mean lines."],
  "g4-eng-ch04-a-q21": ["Sorry first, then a short reason.", "Offer a plan to do better."],
  "g4-eng-ch04-a-q22": ["Return the greeting you receive.", "Invite guests in kindly."],
  "g4-eng-ch04-a-q23": ["Remind gently and give a reason.", "Libraries need quiet voices."],
  "g4-eng-ch04-a-q24": ["Friends help each other when they can.", "Cross out selfish refusals."],
  "g4-eng-ch04-b-q01": ["Please marks a polite ask.", "Thank you is a reply, not the request."],
  "g4-eng-ch04-b-q02": ["Afternoon fits after lunch / after 12.", "Keep ma'am for teachers."],
  "g4-eng-ch04-b-q03": ["Ask permission for more food.", "Small / please keeps it polite."],
  "g4-eng-ch04-b-q04": ["Please and thank you matter on the bus too.", "State your stop clearly."],
  "g4-eng-ch04-b-q05": ["Accidents need calm, not blame.", "Offer to clean together."],
  "g4-eng-ch04-b-q06": ["Ask for a brief wait politely.", "Avoid snapping at the door."],
  "g4-eng-ch04-b-q07": ["End calls with thanks and a clear bye.", "Cross out rude hang-ups."],
  "g4-eng-ch04-b-q08": ["Excuse me works in crowds.", "Name why you need space (your floor)."],
  "g4-eng-ch04-b-q09": ["Thank you accepts praise kindly.", "Avoid boasting or putting yourself down harshly."],
  "g4-eng-ch04-b-q10": ["Ask the classmate who can reach it.", "Please keeps the ask soft."],
  "g4-eng-ch04-b-q11": ["Thank coaches for praise.", "Don't put teammates down."],
  "g4-eng-ch04-b-q12": ["Don't share private details loudly; say busy.", "Offer to take a message."],
  "g4-eng-ch04-b-q13": ["Stay calm in queues.", "State the fact politely."],
  "g4-eng-ch04-b-q14": ["Festival + welcome fits guests at night.", "Don't send guests away rudely."],
  "g4-eng-ch04-b-q15": ["Return + thank you completes borrowing.", "Never insult their things."],
  "g4-eng-ch04-b-q16": ["Give short clear steps.", "Helping visitors is good manners."],
  "g4-eng-ch04-b-q17": ["Praise effort, not only winning.", "Offer to practise together."],
  "g4-eng-ch04-b-q18": ["Start by noticing their point.", "Offer your idea with Could we…"],
  "g4-eng-ch04-b-q19": ["Sneezes get a quick Excuse me.", "Cover your mouth too (habit)."],
  "g4-eng-ch04-b-q20": ["Say yes clearly when you want to join.", "Don't set rude conditions."],
  "g4-eng-ch04-b-q21": ["Accept apologies graciously.", "Don't threaten back."],
  "g4-eng-ch04-b-q22": ["Office talk stays polite and clear.", "Name what you need."],
  "g4-eng-ch04-b-q23": ["Apologise briefly for the noise.", "Mute right away."],
  "g4-eng-ch04-b-q24": ["Elders' small asks deserve a warm yes when you can.", "Tulsi care is a kind favour."],
  "g4-eng-ch05-a-q01": ["Read the bold heading first.", "The body supports the heading."],
  "g4-eng-ch05-a-q02": ["Check the name at the bottom.", "Role/designation sits under the name."],
  "g4-eng-ch05-a-q03": ["Separate notice date from event date.", "Look for the fair day in the body."],
  "g4-eng-ch05-a-q04": ["Action points tell readers what to do.", "Cloth bag is listed in the body."],
  "g4-eng-ch05-a-q05": ["Think of the notice checklist.", "Facts help readers act."],
  "g4-eng-ch05-a-q06": ["Dear + first name often means informal.", "Yours lovingly fits friends/family."],
  "g4-eng-ch05-a-q07": ["Look at the top lines before Dear…", "Address + date come first."],
  "g4-eng-ch05-a-q08": ["Informal letters use warm closings.", "Yours faithfully is more formal."],
  "g4-eng-ch05-a-q09": ["Subject = purpose in brief.", "This one reminds about crayons for art."],
  "g4-eng-ch05-a-q10": ["Scan the body for bring/please bring.", "Two items are listed."],
  "g4-eng-ch05-a-q11": ["Check the signature block.", "Class Monitor is Kabir's role."],
  "g4-eng-ch05-a-q12": ["Read the For: field.", "Taken by is the writer, not the receiver."],
  "g4-eng-ch05-a-q13": ["Keep what / when / where.", "Confirm is part of the ask."],
  "g4-eng-ch05-a-q14": ["Time stamps help busy readers.", "7 October, 5:15 p.m. is when it arrived."],
  "g4-eng-ch05-a-q15": ["Use First / Then / Finally as clues.", "Packing comes before walking."],
  "g4-eng-ch05-a-q16": ["Start with the person doing the action.", "Who → wrote → what → to whom."],
  "g4-eng-ch05-a-q17": ["Notices = public facts.", "Diaries = personal feelings."],
  "g4-eng-ch05-a-q18": ["Teachers get Respected Ma'am / Sir.", "State leave days + reason."],
  "g4-eng-ch05-a-q19": ["Subject is a top field.", "Body comes after Dear…"],
  "g4-eng-ch05-a-q20": ["Headings stay short and clear.", "LOST + item names the topic."],
  "g4-eng-ch05-a-q21": ["Fill To + Subject before the body.", "Sign off at the end."],
  "g4-eng-ch05-a-q22": ["Formal letters need formal closings.", "Lovingly fits friends, not Principal."],
  "g4-eng-ch05-a-q23": ["Messages = facts only.", "Skip fantasy stories."],
  "g4-eng-ch05-a-q24": ["Top: address and date.", "End: closing + name."],
  "g4-eng-ch05-b-q01": ["Heading names the event.", "Playground is the place."],
  "g4-eng-ch05-b-q02": ["Find the weekdays in the body.", "Morning time is also listed."],
  "g4-eng-ch05-b-q03": ["Scan for Wear / bring lines.", "PT shoes are sports shoes."],
  "g4-eng-ch05-b-q04": ["Find the unwell / note sentence.", "Home note explains absence."],
  "g4-eng-ch05-b-q05": ["Bottom lines name the issuer.", "Sports Teacher matches the topic."],
  "g4-eng-ch05-b-q06": ["What first, then when/where.", "Don't skip the event name."],
  "g4-eng-ch05-b-q07": ["Find the main purpose in the body.", "Invite + news = friendly letter."],
  "g4-eng-ch05-b-q08": ["Use a complete calendar date.", "Avoid vague time words."],
  "g4-eng-ch05-b-q09": ["Tone = how it sounds to readers.", "Reminder + please/thank you = polite."],
  "g4-eng-ch05-b-q10": ["Subject needs purpose + key date.", "Avoid empty or emoji-only subjects."],
  "g4-eng-ch05-b-q11": ["Taken by = message writer.", "From = caller."],
  "g4-eng-ch05-b-q12": ["Who called + what they said.", "Extras can wait."],
  "g4-eng-ch05-b-q13": ["Start with The notice.", "Was pinned is the verb group."],
  "g4-eng-ch05-b-q14": ["Enter the place first.", "Thanking comes when leaving."],
  "g4-eng-ch05-b-q15": ["Body = main message.", "Greeting/closing are separate parts."],
  "g4-eng-ch05-b-q16": ["Receiver and subject before the story.", "Name at the end."],
  "g4-eng-ch05-b-q17": ["After 11:00 a.m. is a time rule.", "Welcome = they may attend then."],
  "g4-eng-ch05-b-q18": ["First pairs with Next / Finally.", "Prepare the desk before painting."],
  "g4-eng-ch05-b-q19": ["Include who + when + why.", "Ask/action (call back) helps."],
  "g4-eng-ch05-b-q20": ["Match format to purpose.", "Notices are public and brief."],
  "g4-eng-ch05-b-q21": ["Please often starts a polite instruction.", "Bring is the action."],
  "g4-eng-ch05-b-q22": ["Closing hugs the name at the end.", "Address stays at the top."],
  "g4-eng-ch05-b-q23": ["Header first, signature last.", "Details sit in the middle."],
  "g4-eng-ch05-b-q24": ["Emails end with thanks + name.", "Don't switch to notice format suddenly."],
};
