import type { HintOverlay } from "./types";

/** Grade 4 English item-specific hints (overlay) */
export const G4_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g4-eng-ch01-a-q01": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q02": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q04": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q06": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q08": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q09": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q10": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q11": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q12": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q13": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-a-q14": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q15": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q16": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-a-q17": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q18": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q19": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q20": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q21": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q23": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-a-q24": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q01": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q02": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q04": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q06": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q08": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q09": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch01-b-q10": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q11": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q12": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q13": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q14": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q15": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q16": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q17": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q18": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q19": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q20": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q21": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q22": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch01-b-q23": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch01-b-q24": ["Find evidence in the passage; avoid options the text does not support."],
  "g4-eng-ch02-a-q01": ["A proper noun is a special name and starts with a capital letter."],
  "g4-eng-ch02-a-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q03": ["Use an before a vowel sound; use a before a consonant sound."],
  "g4-eng-ch02-a-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q05": ["An adjective describes a noun — which word tells more about a thing?"],
  "g4-eng-ch02-a-q06": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q07": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q08": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q09": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q10": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q11": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q12": ["A proper noun is a special name and starts with a capital letter."],
  "g4-eng-ch02-a-q13": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q14": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g4-eng-ch02-a-q15": ["Match the verb form to the time and the subject in the sentence."],
  "g4-eng-ch02-a-q16": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-a-q17": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-a-q18": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q19": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-a-q20": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-a-q21": ["Use an before a vowel sound; use a before a consonant sound."],
  "g4-eng-ch02-a-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-a-q23": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-a-q24": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q01": ["Go back to the exact line in the passage that answers the question."],
  "g4-eng-ch02-b-q02": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-b-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q05": ["Use an before a vowel sound; use a before a consonant sound."],
  "g4-eng-ch02-b-q06": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q07": ["Match the verb form to the time and the subject in the sentence."],
  "g4-eng-ch02-b-q08": ["A preposition shows relation (in, on, under, with…)."],
  "g4-eng-ch02-b-q09": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q10": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q11": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q12": ["A common noun is a general name for a person, place, or thing."],
  "g4-eng-ch02-b-q13": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q14": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q15": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q16": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch02-b-q17": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q18": ["A verb shows an action or a state of being."],
  "g4-eng-ch02-b-q19": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-b-q20": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-b-q21": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g4-eng-ch02-b-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q23": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch02-b-q24": ["Name the grammar job or rule being tested in the sentence."],
  "g4-eng-ch03-a-q01": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-a-q02": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-a-q03": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q04": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-a-q05": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q06": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q07": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q08": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q09": ["Join the two smaller words to make one compound word."],
  "g4-eng-ch03-a-q10": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q11": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q12": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-a-q13": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q14": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q15": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q16": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q17": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q18": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q19": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q20": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q21": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-a-q22": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q23": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-a-q24": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q01": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-b-q02": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q03": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-b-q04": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q05": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q06": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q07": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q08": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q09": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-b-q10": ["Join the two smaller words to make one compound word."],
  "g4-eng-ch03-b-q11": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q12": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q13": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q14": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q15": ["Listen for the same ending sound in the words."],
  "g4-eng-ch03-b-q16": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q17": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q18": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q19": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q20": ["Pick the word with the opposite meaning."],
  "g4-eng-ch03-b-q21": ["Join the two smaller words to make one compound word."],
  "g4-eng-ch03-b-q22": ["Study the picture carefully; match it to the sentence or word asked."],
  "g4-eng-ch03-b-q23": ["Use word meaning, word parts, or context to decide."],
  "g4-eng-ch03-b-q24": ["Study the picture carefully; match it to the sentence or word asked."],
};

