import type { HintOverlay } from "./types";

/** Grade 4 Maths item-specific hints (overlay; survives content re-ingest) — itemId → [hint, optional hint2]. */
export const G4_MATHS_HINTS: Record<string, HintOverlay> = {
  "g4-maths-fractions-a-q01": ["Compare piece sizes in each shape — unequal pieces cannot make a true fraction."],
  "g4-maths-fractions-a-q02": ["The denominator is the bottom number: total equal parts in the whole."],
  "g4-maths-fractions-a-q03": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-a-q04": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-a-q05": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q06": ["Unit fractions have 1 as the numerator (one part of the whole)."],
  "g4-maths-fractions-a-q07": ["Count equal jumps from 0 to 1 on the line, then see how many jumps reach the point."],
  "g4-maths-fractions-a-q08": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-a-q09": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q10": ["Ask how many equal pieces of that size fit into one whole."],
  "g4-maths-fractions-a-q11": ["For unit fractions, a bigger denominator means a smaller piece."],
  "g4-maths-fractions-a-q12": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-a-q13": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q14": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q15": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-a-q16": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q17": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q18": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q19": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q20": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q21": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q22": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-a-q23": ["Ask how many equal pieces of that size fit into one whole."],
  "g4-maths-fractions-a-q24": ["Add only when denominators match; add the tops, keep the bottom."],
  "g4-maths-fractions-b-q01": ["Count equal jumps from 0 to 1 on the line, then see how many jumps reach the point."],
  "g4-maths-fractions-b-q02": ["The numerator is the top number: how many of those equal parts you count."],
  "g4-maths-fractions-b-q03": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q04": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q05": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q06": ["Unit fractions have 1 as the numerator (one part of the whole)."],
  "g4-maths-fractions-b-q07": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q08": ["Sharing equally means divide the total by the number of groups."],
  "g4-maths-fractions-b-q09": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q10": ["Ask how many equal pieces of that size fit into one whole."],
  "g4-maths-fractions-b-q11": ["For unit fractions, a bigger denominator means a smaller piece."],
  "g4-maths-fractions-b-q12": ["Scale top and bottom by the same factor to keep the fraction equal."],
  "g4-maths-fractions-b-q13": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q14": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q15": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q16": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-b-q17": ["Compare fractions with like bottoms, or use a common denominator / picture."],
  "g4-maths-fractions-b-q18": ["Sharing equally means divide the total by the number of groups."],
  "g4-maths-fractions-b-q19": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q20": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q21": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q22": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-b-q23": ["Find the fraction of the amount: divide by the denominator (then multiply if needed)."],
  "g4-maths-fractions-b-q24": ["Find the fraction of the amount: divide by the denominator (then multiply if needed)."],
  "g4-maths-large-a-q01": ["Find the named place label on the chart, then read the digit sitting under it."],
  "g4-maths-large-a-q02": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-a-q03": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-a-q04": ["Add every block's value; write 0 in places that have no block."],
  "g4-maths-large-a-q05": ["Compare the numbers on the bars from the left-most digit until they differ."],
  "g4-maths-large-a-q06": ["Add 1 to the number — watch for nines that roll over."],
  "g4-maths-large-a-q07": ["Face value is the digit alone — not multiplied by its place."],
  "g4-maths-large-a-q08": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-a-q09": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-a-q10": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q11": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q12": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q13": ["Align by place value and compare digits from the left."],
  "g4-maths-large-a-q14": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-a-q15": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-a-q16": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-a-q17": ["Empty = total − filled. Subtract carefully place by place."],
  "g4-maths-large-a-q18": ["Ten hundreds make one thousand — scale that up to reach 4,000."],
  "g4-maths-large-a-q19": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-a-q20": ["Subtract the smaller from the larger; line up ones under ones."],
  "g4-maths-large-a-q21": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q22": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-a-q23": ["Round each number first, then add or subtract the rounded values."],
  "g4-maths-large-a-q24": ["Spot the pattern of what is added each time; the added amount grows by ×10."],
  "g4-maths-large-b-q01": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-b-q02": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-b-q03": ["Find the named place label on the chart, then read the digit sitting under it."],
  "g4-maths-large-b-q04": ["Add every block's value; write 0 in places that have no block."],
  "g4-maths-large-b-q05": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-b-q06": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-b-q07": ["Face value is the digit alone — not multiplied by its place."],
  "g4-maths-large-b-q08": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-b-q09": ["See how much each term increases; keep adding that same step."],
  "g4-maths-large-b-q10": ["Add the two book counts; line ones under ones."],
  "g4-maths-large-b-q11": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-b-q12": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-b-q13": ["Align by place value and compare digits from the left."],
  "g4-maths-large-b-q14": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-b-q15": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-b-q16": ["Subtract the smaller from the larger; line up ones under ones."],
  "g4-maths-large-b-q17": ["Adding 1,000 bumps only the thousands place by 1."],
  "g4-maths-large-b-q18": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-b-q19": ["Add 1 to the number — watch for nines that roll over."],
  "g4-maths-large-b-q20": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-b-q21": ["Build digit by digit from the clues: ten thousands, thousands, hundreds, tens, ones."],
  "g4-maths-large-b-q22": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-b-q23": ["Compare the numbers on the bars from the left-most digit until they differ."],
  "g4-maths-large-b-q24": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-muldiv-a-q01": ["Multiply using place value or a known table fact; estimate to check."],
  "g4-maths-muldiv-a-q02": ["For each marked cell, multiply its row header by its column header."],
  "g4-maths-muldiv-a-q03": ["Count rows and how many in each row, then multiply — or count all dots."],
  "g4-maths-muldiv-a-q04": ["Remember the special rule for multiplying by zero."],
  "g4-maths-muldiv-a-q05": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-a-q06": ["Ask which times-table fact undoes this division."],
  "g4-maths-muldiv-a-q07": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-a-q08": ["Think of 3 groups of 12, or use a known table fact."],
  "g4-maths-muldiv-a-q09": ["Does swapping the two factors change the product?"],
  "g4-maths-muldiv-a-q10": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-a-q11": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-a-q12": ["Break 214 into hundreds, tens and ones; multiply each by 4, then add."],
  "g4-maths-muldiv-a-q13": ["Try 12 × 10, then add one more 12."],
  "g4-maths-muldiv-a-q14": ["Find the total first (often multiply), then subtract what was used."],
  "g4-maths-muldiv-a-q15": ["Ask: 6 times what number makes 54?"],
  "g4-maths-muldiv-a-q16": ["Multiply packs by pencils per pack, then add the loose ones."],
  "g4-maths-muldiv-a-q17": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-a-q18": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-a-q19": ["Missing dividend = divisor × quotient."],
  "g4-maths-muldiv-a-q20": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-a-q21": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-a-q22": ["Use a friendly break-up, like factoring through 25 × 4 = 100."],
  "g4-maths-muldiv-a-q23": ["Multiply using place value or a known table fact; estimate to check."],
  "g4-maths-muldiv-a-q24": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q01": ["a × b means b groups of a added together."],
  "g4-maths-muldiv-b-q02": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q03": ["Multiply using place value or a known table fact; estimate to check."],
  "g4-maths-muldiv-b-q04": ["Remember the special rule for multiplying by zero."],
  "g4-maths-muldiv-b-q05": ["What happens to a number when you divide it by one?"],
  "g4-maths-muldiv-b-q06": ["Ask which times-table fact undoes this division."],
  "g4-maths-muldiv-b-q07": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q08": ["Try 10 × 4, then add 1 × 4."],
  "g4-maths-muldiv-b-q09": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q10": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-b-q11": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-b-q12": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-b-q13": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q14": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-b-q15": ["Ask: what times 8 makes 96?"],
  "g4-maths-muldiv-b-q16": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-b-q17": ["Equal weekly amounts → multiply the weekly save by the number of weeks."],
  "g4-maths-muldiv-b-q18": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-b-q19": ["Missing dividend = divisor × quotient."],
  "g4-maths-muldiv-b-q20": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-b-q21": ["Find the total first (often multiply), then subtract what was used."],
  "g4-maths-muldiv-b-q22": ["Split as 15 × 10 plus 15 × 5, then add."],
  "g4-maths-muldiv-b-q23": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q24": ["Equal groups → multiply; sharing a total into groups → divide."],
};

