import type { HintOverlay } from "./types";

/** Grade 4 Maths item-specific hints (overlay; survives content re-ingest) — itemId → [hint, optional hint2]. */
export const G4_MATHS_HINTS: Record<string, HintOverlay> = {
  "g4-maths-fractions-a-q01": ["Compare piece sizes in each shape — unequal pieces cannot make a true fraction."],
  "g4-maths-fractions-a-q02": ["The denominator is the bottom number: total equal parts in the whole."],
  "g4-maths-fractions-a-q03": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-a-q04": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-a-q05": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q06": ["Unit fractions have 1 as the numerator (one part of the whole)."],
  "g4-maths-fractions-a-q07": ["Count equal jumps from 0 to 1 on the line, then see how many jumps reach the point."],
  "g4-maths-fractions-a-q08": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-a-q09": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q10": ["Ask how many equal pieces of that size fit into one whole."],
  "g4-maths-fractions-a-q11": ["For unit fractions, a bigger denominator means a smaller piece."],
  "g4-maths-fractions-a-q12": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-a-q13": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q14": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q15": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-a-q16": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q17": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q18": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-a-q19": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q20": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q21": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-a-q22": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-a-q23": ["Ask how many equal pieces of that size fit into one whole."],
  "g4-maths-fractions-a-q24": ["Add only when denominators match; add the tops, keep the bottom."],
  "g4-maths-fractions-b-q01": ["Count equal jumps from 0 to 1 on the line, then see how many jumps reach the point."],
  "g4-maths-fractions-b-q02": ["The numerator is the top number: how many of those equal parts you count."],
  "g4-maths-fractions-b-q03": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q04": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q05": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q06": ["Unit fractions have 1 as the numerator (one part of the whole)."],
  "g4-maths-fractions-b-q07": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q08": ["Sharing equally means divide the total by the number of groups."],
  "g4-maths-fractions-b-q09": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q10": ["Ask how many equal pieces of that size fit into one whole."],
  "g4-maths-fractions-b-q11": ["For unit fractions, a bigger denominator means a smaller piece."],
  "g4-maths-fractions-b-q12": ["Scale top and bottom by the same factor to keep the fraction equal."],
  "g4-maths-fractions-b-q13": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q14": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q15": ["Count the shaded parts in the figure first, then count all equal parts."],
  "g4-maths-fractions-b-q16": ["Name the whole, count equal parts, then write parts-used over parts-in-all."],
  "g4-maths-fractions-b-q17": ["Compare fractions with like bottoms, or use a common denominator / picture."],
  "g4-maths-fractions-b-q18": ["Sharing equally means divide the total by the number of groups."],
  "g4-maths-fractions-b-q19": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q20": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q21": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g4-maths-fractions-b-q22": ["Fraction left = whole minus the fraction taken (same denominator)."],
  "g4-maths-fractions-b-q23": ["Find the fraction of the amount: divide by the denominator (then multiply if needed)."],
  "g4-maths-fractions-b-q24": ["Find the fraction of the amount: divide by the denominator (then multiply if needed)."],
  "g4-maths-large-a-q01": ["Find the named place label on the chart, then read the digit sitting under it."],
  "g4-maths-large-a-q02": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-a-q03": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-a-q04": ["Add every block's value; write 0 in places that have no block."],
  "g4-maths-large-a-q05": ["Compare the numbers on the bars from the left-most digit until they differ."],
  "g4-maths-large-a-q06": ["Add 1 to the number — watch for nines that roll over."],
  "g4-maths-large-a-q07": ["Face value is the digit alone — not multiplied by its place."],
  "g4-maths-large-a-q08": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-a-q09": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-a-q10": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q11": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q12": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q13": ["Align by place value and compare digits from the left."],
  "g4-maths-large-a-q14": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-a-q15": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-a-q16": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-a-q17": ["Empty = total − filled. Subtract carefully place by place."],
  "g4-maths-large-a-q18": ["Ten hundreds make one thousand — scale that up to reach 4,000."],
  "g4-maths-large-a-q19": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-a-q20": ["Subtract the smaller from the larger; line up ones under ones."],
  "g4-maths-large-a-q21": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-a-q22": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-a-q23": ["Round each number first, then add or subtract the rounded values."],
  "g4-maths-large-a-q24": ["Spot the pattern of what is added each time; the added amount grows by ×10."],
  "g4-maths-large-b-q01": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-b-q02": ["Translate each word-group into digits and put zeros in empty places."],
  "g4-maths-large-b-q03": ["Find the named place label on the chart, then read the digit sitting under it."],
  "g4-maths-large-b-q04": ["Add every block's value; write 0 in places that have no block."],
  "g4-maths-large-b-q05": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-b-q06": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-b-q07": ["Face value is the digit alone — not multiplied by its place."],
  "g4-maths-large-b-q08": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-b-q09": ["See how much each term increases; keep adding that same step."],
  "g4-maths-large-b-q10": ["Add the two book counts; line ones under ones."],
  "g4-maths-large-b-q11": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-b-q12": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-b-q13": ["Align by place value and compare digits from the left."],
  "g4-maths-large-b-q14": ["Work out each equal jump size, then count jumps from the labelled start to the point."],
  "g4-maths-large-b-q15": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-b-q16": ["Subtract the smaller from the larger; line up ones under ones."],
  "g4-maths-large-b-q17": ["Adding 1,000 bumps only the thousands place by 1."],
  "g4-maths-large-b-q18": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-large-b-q19": ["Add 1 to the number — watch for nines that roll over."],
  "g4-maths-large-b-q20": ["Greatest: largest digits first. Smallest: smallest first, but do not start with 0."],
  "g4-maths-large-b-q21": ["Build digit by digit from the clues: ten thousands, thousands, hundreds, tens, ones."],
  "g4-maths-large-b-q22": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g4-maths-large-b-q23": ["Compare the numbers on the bars from the left-most digit until they differ."],
  "g4-maths-large-b-q24": ["Read every label in the figure, then build or compare the number place by place."],
  "g4-maths-muldiv-a-q01": ["Multiply using place value or a known table fact; estimate to check."],
  "g4-maths-muldiv-a-q02": ["For each marked cell, multiply its row header by its column header."],
  "g4-maths-muldiv-a-q03": ["Count rows and how many in each row, then multiply — or count all dots."],
  "g4-maths-muldiv-a-q04": ["Remember the special rule for multiplying by zero."],
  "g4-maths-muldiv-a-q05": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-a-q06": ["Ask which times-table fact undoes this division."],
  "g4-maths-muldiv-a-q07": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-a-q08": ["Think of 3 groups of 12, or use a known table fact."],
  "g4-maths-muldiv-a-q09": ["Does swapping the two factors change the product?"],
  "g4-maths-muldiv-a-q10": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-a-q11": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-a-q12": ["Break 214 into hundreds, tens and ones; multiply each by 4, then add."],
  "g4-maths-muldiv-a-q13": ["Try 12 × 10, then add one more 12."],
  "g4-maths-muldiv-a-q14": ["Find the total first (often multiply), then subtract what was used."],
  "g4-maths-muldiv-a-q15": ["Ask: 6 times what number makes 54?"],
  "g4-maths-muldiv-a-q16": ["Multiply packs by pencils per pack, then add the loose ones."],
  "g4-maths-muldiv-a-q17": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-a-q18": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-a-q19": ["Missing dividend = divisor × quotient."],
  "g4-maths-muldiv-a-q20": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-a-q21": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-a-q22": ["Use a friendly break-up, like factoring through 25 × 4 = 100."],
  "g4-maths-muldiv-a-q23": ["Multiply using place value or a known table fact; estimate to check."],
  "g4-maths-muldiv-a-q24": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q01": ["a × b means b groups of a added together."],
  "g4-maths-muldiv-b-q02": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q03": ["Multiply using place value or a known table fact; estimate to check."],
  "g4-maths-muldiv-b-q04": ["Remember the special rule for multiplying by zero."],
  "g4-maths-muldiv-b-q05": ["What happens to a number when you divide it by one?"],
  "g4-maths-muldiv-b-q06": ["Ask which times-table fact undoes this division."],
  "g4-maths-muldiv-b-q07": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q08": ["Try 10 × 4, then add 1 × 4."],
  "g4-maths-muldiv-b-q09": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q10": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-b-q11": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-b-q12": ["Decide: equal groups (×) or sharing/grouping (÷), then compute carefully."],
  "g4-maths-muldiv-b-q13": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q14": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-b-q15": ["Ask: what times 8 makes 96?"],
  "g4-maths-muldiv-b-q16": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-b-q17": ["Equal weekly amounts → multiply the weekly save by the number of weeks."],
  "g4-maths-muldiv-b-q18": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-muldiv-b-q19": ["Missing dividend = divisor × quotient."],
  "g4-maths-muldiv-b-q20": ["Division is equal sharing or equal grouping — pick which one the story asks."],
  "g4-maths-muldiv-b-q21": ["Find the total first (often multiply), then subtract what was used."],
  "g4-maths-muldiv-b-q22": ["Split as 15 × 10 plus 15 × 5, then add."],
  "g4-maths-muldiv-b-q23": ["Use the figure: count groups or items per group, then multiply or divide."],
  "g4-maths-muldiv-b-q24": ["Equal groups → multiply; sharing a total into groups → divide."],
  "g4-maths-measurement-a-q01": ["Match the object size to a sensible unit.", "Pencils are much shorter than a metre."],
  "g4-maths-measurement-a-q02": ["Remember the metric ladder for length.", "Centi means one-hundredth."],
  "g4-maths-measurement-a-q03": ["Milli is a tiny length unit.", "Count how many mm fit in 1 cm."],
  "g4-maths-measurement-a-q04": ["Convert metres to centimetres by multiplying by 100.", "25 \u00d7 100."],
  "g4-maths-measurement-a-q05": ["Litre and millilitre measure capacity.", "Milli means one-thousandth of a litre."],
  "g4-maths-measurement-a-q06": ["Mass is the amount of matter, not how fluffy it looks.", "Same kilogram means same mass."],
  "g4-maths-measurement-a-q07": ["Kilo means one thousand.", "Mass: kg \u2194 g."],
  "g4-maths-measurement-a-q08": ["Multiply kilograms by 1,000 to get grams.", "5 \u00d7 1,000."],
  "g4-maths-measurement-a-q09": ["Capacity is about liquid volume.", "Think of milk packets and bottles."],
  "g4-maths-measurement-a-q10": ["Change metres to cm first, then add the leftover cm.", "3 \u00d7 100 + 40."],
  "g4-maths-measurement-a-q11": ["Convert all options to the same unit.", "1 m = 100 cm = 1,000 mm."],
  "g4-maths-measurement-a-q12": ["Add the gram amounts.", "750 + 250."],
  "g4-maths-measurement-a-q13": ["Think of body-based traditional measures.", "Elbow to fingertip is a cubit/hath."],
  "g4-maths-measurement-a-q14": ["Convert litres to ml, then add.", "2 \u00d7 1,000 + 500."],
  "g4-maths-measurement-a-q15": ["Pick a unit that fits the journey size.", "Parks are usually many metres away."],
  "g4-maths-measurement-a-q16": ["Every 1,000 g make 1 kg.", "4,500 = 4 \u00d7 1,000 + 500."],
  "g4-maths-measurement-a-q17": ["Think of two pans and weights.", "Heaviness is mass."],
  "g4-maths-measurement-a-q18": ["Write every option in ml.", "1 l = 1,000 ml."],
  "g4-maths-measurement-a-q19": ["m \u2192 cm: multiply by 100.", "20 \u00d7 100."],
  "g4-maths-measurement-a-q20": ["Convert 1 litre to ml first.", "1,000 \u00f7 250."],
  "g4-maths-measurement-a-q21": ["Kilo means one thousand.", "Length: km \u2194 m."],
  "g4-maths-measurement-a-q22": ["Add kg and g separately, then regroup 1,000 g as 1 kg.", "300 + 700 = 1,000 g."],
  "g4-maths-measurement-a-q23": ["Match the tool to what you measure.", "Length needs a ruler or tape."],
  "g4-maths-measurement-a-q24": ["Convert litres to ml, then divide by 500.", "15,000 \u00f7 500."],
  "g4-maths-measurement-b-q01": ["Mass of small foods is often in grams.", "Not length or capacity."],
  "g4-maths-measurement-b-q02": ["Kilo means one thousand.", "km \u2194 m."],
  "g4-maths-measurement-b-q03": ["Multiply metres by 100, then add cm.", "800 + 5."],
  "g4-maths-measurement-b-q04": ["1 litre = 1,000 ml.", "750/1000 simplifies to 3/4."],
  "g4-maths-measurement-b-q05": ["Convert kg to grams to compare.", "1 kg = 1,000 g."],
  "g4-maths-measurement-b-q06": ["Add the distances, then convert km to m.", "4 \u00d7 1,000."],
  "g4-maths-measurement-b-q07": ["Jewellery mass has traditional names.", "Tola is linked to precious metals."],
  "g4-maths-measurement-b-q08": ["Group millilitres into thousands for litres.", "3 \u00d7 1,000 + 200."],
  "g4-maths-measurement-b-q09": ["Convert the metre part to cm.", "100 + 25."],
  "g4-maths-measurement-b-q10": ["Half a kilogram is half of 1,000 g.", "1,000 \u00f7 2."],
  "g4-maths-measurement-b-q11": ["Convert both to ml and compare.", "2 l = 2,000 ml; 8 \u00d7 200 = 1,600 ml."],
  "g4-maths-measurement-b-q12": ["Every 100 cm make 1 metre.", "120 = 100 + 20."],
  "g4-maths-measurement-b-q13": ["Convert litres to ml, then divide.", "5,000 \u00f7 250."],
  "g4-maths-measurement-b-q14": ["Mass is how heavy something is.", "kg and g are mass units."],
  "g4-maths-measurement-b-q15": ["Picture walking through a door.", "Metres fit human-sized heights."],
  "g4-maths-measurement-b-q16": ["Borrow 1 kg as 1,000 g if needed.", "4,000 g \u2212 250 g = 750 g leftover with 3 kg."],
  "g4-maths-measurement-b-q17": ["Multiply metres by 100.", "3 \u00d7 100."],
  "g4-maths-measurement-b-q18": ["Find how much was poured out, then subtract from 4 l.", "4,000 \u2212 1,200."],
  "g4-maths-measurement-b-q19": ["Use the standard conversion.", "1 m = 100 cm."],
  "g4-maths-measurement-b-q20": ["Convert kg to g, then divide by 500.", "10,000 \u00f7 500."],
  "g4-maths-measurement-b-q21": ["Multiply map cm by the scale value.", "7 \u00d7 1 km."],
  "g4-maths-measurement-b-q22": ["Picture a lunch-box water bottle.", "Hundreds of ml, not litres of tank size."],
  "g4-maths-measurement-b-q23": ["Add cm, regroup every 100 cm as 1 m.", "115 cm \u2192 1 m 15 cm."],
  "g4-maths-measurement-b-q24": ["Add, then convert 1,000 g into an extra kilogram.", "400 + 600 = 1,000 g."],
  "g4-maths-geometry-a-q01": ["Count the straight sides.", "Three sides \u2192 triangle."],
  "g4-maths-geometry-a-q02": ["A square is a special rectangle.", "Count the edges."],
  "g4-maths-geometry-a-q03": ["Think of a round steel plate or a chapati cutter.", "Equal distance from centre = circle."],
  "g4-maths-geometry-a-q04": ["Rectangles have four sides.", "Opposite sides match."],
  "g4-maths-geometry-a-q05": ["Closed means you return to the start with no opening.", "Squares enclose space."],
  "g4-maths-geometry-a-q06": ["Segment stops; ray has one end; line never stops.", "Both directions forever \u2192 line."],
  "g4-maths-geometry-a-q07": ["Picture sunlight starting at the sun.", "One start, endless path."],
  "g4-maths-geometry-a-q08": ["Look for two arms and a corner.", "Vertex + two arms."],
  "g4-maths-geometry-a-q09": ["Think of the corner of a notebook.", "Square corner = 90\u00b0."],
  "g4-maths-geometry-a-q10": ["Acute = sharp / smaller than a square corner.", "Compare with 90\u00b0."],
  "g4-maths-geometry-a-q11": ["Obtuse is 'open wider' than a right angle but not flat.", "Between 90\u00b0 and 180\u00b0."],
  "g4-maths-geometry-a-q12": ["All four sides of a square are equal.", "Divide perimeter by 4."],
  "g4-maths-geometry-a-q13": ["Walk along the fence of a park.", "Around the outside."],
  "g4-maths-geometry-a-q14": ["Add length and breadth, then double.", "2 \u00d7 (8 + 5)."],
  "g4-maths-geometry-a-q15": ["Right angles look like notebook corners.", "Four square corners \u2192 rectangle/square."],
  "g4-maths-geometry-a-q16": ["Think of railway tracks.", "Same gap, no meeting."],
  "g4-maths-geometry-a-q17": ["Skip the two adjacent vertices.", "5 \u2212 1 \u2212 2 = 2."],
  "g4-maths-geometry-a-q18": ["Equal sides \u2192 equilateral.", "All three match."],
  "g4-maths-geometry-a-q19": ["A dice is a cube.", "Square faces."],
  "g4-maths-geometry-a-q20": ["Segment means a cut piece.", "Two ends."],
  "g4-maths-geometry-a-q21": ["All three sides are 6 cm.", "Add three equal sides."],
  "g4-maths-geometry-a-q22": ["Match the corner to a square corner.", "Books have right-angled corners."],
  "g4-maths-geometry-a-q23": ["Hexa means six.", "Count the edges."],
  "g4-maths-geometry-a-q24": ["Meeting lines make corners.", "Corners are angles."],
  "g4-maths-geometry-b-q01": ["Penta means five.", "Count sides."],
  "g4-maths-geometry-b-q02": ["Straight sides vs smooth curve.", "Circles are round."],
  "g4-maths-geometry-b-q03": ["Length matches length; breadth matches breadth.", "Opposite sides equal."],
  "g4-maths-geometry-b-q04": ["A straight line makes a 180\u00b0 angle.", "Half of a full turn."],
  "g4-maths-geometry-b-q05": ["Acute < 90\u00b0.", "Compare each measure to 90\u00b0."],
  "g4-maths-geometry-b-q06": ["Four equal sides.", "Multiply one side by 4."],
  "g4-maths-geometry-b-q07": ["Double the sum of length and breadth.", "2 \u00d7 19."],
  "g4-maths-geometry-b-q08": ["Closed figures seal completely.", "U leaves a gap."],
  "g4-maths-geometry-b-q09": ["Vertex = corner point.", "Where arms join."],
  "g4-maths-geometry-b-q10": ["Each corner is 90\u00b0.", "Four corners."],
  "g4-maths-geometry-b-q11": ["Rhombus is like a pushed-over square.", "Sides equal."],
  "g4-maths-geometry-b-q12": ["Parallel lines never meet.", "Road edges stay apart."],
  "g4-maths-geometry-b-q13": ["Tri means three.", "Four sides would be a quadrilateral."],
  "g4-maths-geometry-b-q14": ["Joined side is not part of the outer boundary.", "2 \u00d7 (8 + 4) = 24."],
  "g4-maths-geometry-b-q15": ["Right angle = square corner.", "Exactly 90\u00b0."],
  "g4-maths-geometry-b-q16": ["Count faces of a dice.", "Cube numbers: 6, 12, 8."],
  "g4-maths-geometry-b-q17": ["Midpoint means halfway.", "Half of 7."],
  "g4-maths-geometry-b-q18": ["Quad means four.", "Four-sided closed shape."],
  "g4-maths-geometry-b-q19": ["Regular means all sides equal.", "Multiply side by 5."],
  "g4-maths-geometry-b-q20": ["At 3 the minute hand on 12 and hour on 3 make a square corner.", "90\u00b0 apart."],
  "g4-maths-geometry-b-q21": ["Intersect means cross.", "They share a point."],
  "g4-maths-geometry-b-q22": ["Perimeter \u00f7 4 for a square.", "48 \u00f7 4."],
  "g4-maths-geometry-b-q23": ["Obtuse sits between right and straight.", "Check 90\u00b0 < angle < 180\u00b0."],
  "g4-maths-geometry-b-q24": ["Straight sides, closed path.", "Triangle, square, pentagon are polygons."],
  "g4-maths-data-a-q01": ["Tally marks group by fives.", "Four lines + cross = 5."],
  "g4-maths-data-a-q02": ["Count the strokes.", "No diagonal yet \u2192 still under 5."],
  "g4-maths-data-a-q03": ["Read the key: what one picture is worth.", "3 \u00d7 2."],
  "g4-maths-data-a-q04": ["Compare bar heights.", "Higher bar \u2192 bigger count."],
  "g4-maths-data-a-q05": ["Find the largest number in the table.", "Compare 12, 8 and 5."],
  "g4-maths-data-a-q06": ["Add the two counts.", "8 + 5."],
  "g4-maths-data-a-q07": ["Multiply number of pictures by the key value.", "4 \u00d7 5."],
  "g4-maths-data-a-q08": ["Titles describe the data topic.", "Match graph to wording."],
  "g4-maths-data-a-q09": ["Make groups of 5, then leftovers.", "5 + 2."],
  "g4-maths-data-a-q10": ["Find the smallest number.", "Compare 6, 4, 6, 2."],
  "g4-maths-data-a-q11": ["Add the two equal amounts.", "6 + 6."],
  "g4-maths-data-a-q12": ["Halves scale the key.", "Half picture \u2192 half the value."],
  "g4-maths-data-a-q13": ["Think of survey answers and counts.", "Organised facts/numbers."],
  "g4-maths-data-a-q14": ["Categories + counts \u2192 graph.", "Bars or pictures work well."],
  "g4-maths-data-a-q15": ["Each gate is 5; count leftovers.", "5 + 5 + 2."],
  "g4-maths-data-a-q16": ["Look for the zero entry.", "0 means none."],
  "g4-maths-data-a-q17": ["Add all daily amounts.", "3 + 5 + 2."],
  "g4-maths-data-a-q18": ["Full pictures first, then the half.", "3 \u00d7 10 + 5."],
  "g4-maths-data-a-q19": ["Names vs numbers.", "Fruit names are categories."],
  "g4-maths-data-a-q20": ["Height encodes the number.", "Same height \u2192 same value."],
  "g4-maths-data-a-q21": ["Subtract known groups from the total.", "20 \u2212 15."],
  "g4-maths-data-a-q22": ["Rows and columns \u2192 table.", "Like a marksheet grid."],
  "g4-maths-data-a-q23": ["Use the key multiplier.", "3 \u00d7 4."],
  "g4-maths-data-a-q24": ["Quick counting while watching.", "Groups of five speed totals."],
  "g4-maths-data-b-q01": ["Each completed gate is 5.", "3 \u00d7 5."],
  "g4-maths-data-b-q02": ["Divide the total by the key value.", "12 \u00f7 3."],
  "g4-maths-data-b-q03": ["Find the maximum, then see who matches it.", "Both show 10."],
  "g4-maths-data-b-q04": ["Subtract the smaller from the larger.", "10 \u2212 4."],
  "g4-maths-data-b-q05": ["Picture + key = pictograph.", "Icons represent counts."],
  "g4-maths-data-b-q06": ["Scan for the greatest number.", "Compare 8, 6, 9, 7."],
  "g4-maths-data-b-q07": ["Add the two scores.", "8 + 7."],
  "g4-maths-data-b-q08": ["Look at the gap between marks.", "0 to 2 to 4."],
  "g4-maths-data-b-q09": ["10 + 1.", "Two fives and a single."],
  "g4-maths-data-b-q10": ["Add the cat and fish counts.", "5 + 3."],
  "g4-maths-data-b-q11": ["Add every category.", "8 + 5 + 3 + 4."],
  "g4-maths-data-b-q12": ["Halve the key value.", "10 \u00f7 2."],
  "g4-maths-data-b-q13": ["Graphs answer questions about the data shown.", "Look for most/least votes."],
  "g4-maths-data-b-q14": ["Data handling = organise and display.", "Make tallies/tables/graphs."],
  "g4-maths-data-b-q15": ["Multiply icons by key.", "5 \u00d7 2."],
  "g4-maths-data-b-q16": ["Tables map items to numbers.", "One row per category often."],
  "g4-maths-data-b-q17": ["Add the two matching counts.", "9 + 9."],
  "g4-maths-data-b-q18": ["Data handling organises information.", "Tallies and graphs help; ignoring does not."],
  "g4-maths-data-b-q19": ["Keys tell the value of one picture.", "Missing key \u2192 unknown scale."],
  "g4-maths-data-b-q20": ["Convert tallies to numbers, then add.", "10 + 5."],
  "g4-maths-data-b-q21": ["Title must match the categories.", "Travel modes fit."],
  "g4-maths-data-b-q22": ["Difference = larger \u2212 smaller.", "14 \u2212 9."],
  "g4-maths-data-b-q23": ["Frequency pairs category with count.", "Names + numbers."],
  "g4-maths-data-b-q24": ["Graph and table should tell the same story.", "Match heights to numbers."],
};
