import type { HintOverlay } from "./types";

/** Grade 4 Science item-specific hints (overlay; survives content re-ingest) — itemId → [hint, optional hint2]. */
export const G4_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g4-sci-food-a-q01": ["Which nutrient fuels running and playing? Think of rice, roti and potato."],
  "g4-sci-food-a-q02": ["Body-building foods are protein-rich — which card fits that job?"],
  "g4-sci-food-a-q03": ["Sour citrus fruits and amla point to one vitamin letter — which?"],
  "g4-sci-food-a-q04": ["Think of the part of plant food that helps digestion move along like a broom."],
  "g4-sci-food-a-q05": ["Sunshine on skin helps make the vitamin that strengthens bones."],
  "g4-sci-food-a-q06": ["Think of the mineral in milk and curd that builds bones and teeth."],
  "g4-sci-food-a-q07": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-a-q08": ["Which foods are oily or buttery and store lots of energy?"],
  "g4-sci-food-a-q09": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-a-q10": ["Water helps transport nutrients and keep every cell working."],
  "g4-sci-food-a-q11": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-a-q12": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-a-q13": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-a-q14": ["A balanced plate mixes energy, body-building, and protective foods."],
  "g4-sci-food-a-q15": ["Constipation often eases with more fibre and water in meals."],
  "g4-sci-food-a-q16": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-a-q17": ["Which everyday seasoning is enriched to help the thyroid?"],
  "g4-sci-food-a-q18": ["After sweating in the sun, replace lost fluid with a simple healthy drink."],
  "g4-sci-food-a-q19": ["Iodine is a starch test — recall which colour starch turns with iodine."],
  "g4-sci-food-a-q20": ["Extra stored fat is not healthy — moderation matters even for energy foods."],
  "g4-sci-food-a-q21": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-a-q22": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-a-q23": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-a-q24": ["Treats are fine sometimes; everyday food should still be nourishing."],
  "g4-sci-food-b-q01": ["Body-building foods are protein-rich — which option fits that job?"],
  "g4-sci-food-b-q02": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-b-q03": ["Iron-rich foods (leafy greens, jaggery, dates) help blood carry oxygen."],
  "g4-sci-food-b-q04": ["Think of the part of plant food that helps digestion move along like a broom."],
  "g4-sci-food-b-q05": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-b-q06": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-b-q07": ["What do we call a meal plan with every nutrient in sensible amounts?"],
  "g4-sci-food-b-q08": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q09": ["Sunshine on skin helps make the vitamin that strengthens bones."],
  "g4-sci-food-b-q10": ["Fats store energy — ghee, butter, oils, and nuts are fatty foods."],
  "g4-sci-food-b-q11": ["A balanced plate mixes energy, body-building, and protective foods."],
  "g4-sci-food-b-q12": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-b-q13": ["Iron-rich foods (leafy greens, jaggery, dates) help blood carry oxygen."],
  "g4-sci-food-b-q14": ["Body-building foods are protein-rich: dal, milk, eggs, beans, fish."],
  "g4-sci-food-b-q15": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q16": ["Pickles last because something stops germs — which kitchen staples do that?"],
  "g4-sci-food-b-q17": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-b-q18": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q19": ["Recall which vitamin matches the food or symptom in the question."],
  "g4-sci-food-b-q20": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q21": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-b-q22": ["Water helps transport nutrients and keep every cell working."],
  "g4-sci-food-b-q23": ["Roughage (fibre) in veggies and whole grains helps food move through."],
  "g4-sci-food-b-q24": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-matter-a-q01": ["Solids keep their own shape and volume."],
  "g4-sci-matter-a-q02": ["Liquids flow and take the shape of their container."],
  "g4-sci-matter-a-q03": ["Gases spread out and fill all the space in a container."],
  "g4-sci-matter-a-q04": ["What word means anything that takes up space and has weight?"],
  "g4-sci-matter-a-q05": ["Warmth changes ice from solid to liquid — what is that change called, and what forms?"],
  "g4-sci-matter-a-q06": ["Things that keep their own shape are which state of matter?"],
  "g4-sci-matter-a-q07": ["A liquid has no fixed shape — it follows the container you pour it into."],
  "g4-sci-matter-a-q08": ["What invisible gas from your lungs fills a balloon?"],
  "g4-sci-matter-a-q09": ["Cooling a liquid until it becomes solid is which change?"],
  "g4-sci-matter-a-q10": ["Solids keep their own shape and volume."],
  "g4-sci-matter-a-q11": ["Cooling a liquid until it becomes solid is which change?"],
  "g4-sci-matter-a-q12": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q13": ["Solids and liquids have fixed volume; gases do not."],
  "g4-sci-matter-a-q14": ["Melting is solid ice becoming liquid water when it warms."],
  "g4-sci-matter-a-q15": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q16": ["Which option does not flow and keeps tiny crystal shapes?"],
  "g4-sci-matter-a-q17": ["Strong heating that makes water bubble into steam has a special name."],
  "g4-sci-matter-a-q18": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q19": ["Heat turns solid ice cream into a runny liquid — name that change."],
  "g4-sci-matter-a-q20": ["Even if you cannot see it, moving air gives clues — what do you feel or see?"],
  "g4-sci-matter-a-q21": ["Soluble substances disappear into the liquid and make a solution."],
  "g4-sci-matter-a-q22": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q23": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q24": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q01": ["Liquids flow and take the shape of their container."],
  "g4-sci-matter-b-q02": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q03": ["What invisible gas is pumped inside a football?"],
  "g4-sci-matter-b-q04": ["Matter appears in three familiar forms — list them."],
  "g4-sci-matter-b-q05": ["Heat and wind help liquid water turn into invisible vapour."],
  "g4-sci-matter-b-q06": ["Solids keep their own shape and volume."],
  "g4-sci-matter-b-q07": ["Without a container, what does a liquid do on a flat floor?"],
  "g4-sci-matter-b-q08": ["Which option can pour or drip, even if slowly?"],
  "g4-sci-matter-b-q09": ["Warmth turns solid ice into liquid water — what is that change called?"],
  "g4-sci-matter-b-q10": ["Which substance spreads everywhere unless sealed in a closed container?"],
  "g4-sci-matter-b-q11": ["Solids and liquids have fixed volume; gases do not."],
  "g4-sci-matter-b-q12": ["When vapour cools, it turns back into tiny liquid drops."],
  "g4-sci-matter-b-q13": ["Melting is solid ice becoming liquid water when it warms."],
  "g4-sci-matter-b-q14": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q15": ["Melting is solid ice becoming liquid water when it warms."],
  "g4-sci-matter-b-q16": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q17": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q18": ["Three options flow; one keeps a fixed shape — find the odd one."],
  "g4-sci-matter-b-q19": ["Cooling vapour high up forms tiny drops — what do we call that collection?"],
  "g4-sci-matter-b-q20": ["Pumping presses more gas into the same space — how does that change the tyre?"],
  "g4-sci-matter-b-q21": ["Recall: which state has fixed volume but not fixed shape?"],
  "g4-sci-matter-b-q22": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q23": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q24": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-water-a-q01": ["Which everyday liquid covers most of Earth and fills rivers and taps?"],
  "g4-sci-water-a-q02": ["Natural sources include rain, rivers, lakes, ponds, and wells."],
  "g4-sci-water-a-q03": ["Clouds are tiny water drops; when heavy enough they fall as that change."],
  "g4-sci-water-a-q04": ["Rain seeps down into soil and rock — that store is drawn up by wells."],
  "g4-sci-water-a-q05": ["Sea water has something dissolved in it that changes its taste."],
  "g4-sci-water-a-q06": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-a-q07": ["Why do fields and farms need so much water?"],
  "g4-sci-water-a-q08": ["What heat source turns pond water into vapour on a hot day?"],
  "g4-sci-water-a-q09": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-a-q10": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-a-q11": ["Liquid becoming vapour has a special name — which change is that?"],
  "g4-sci-water-a-q12": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-a-q13": ["Rain seeps down into soil and rock — that store is drawn up by wells."],
  "g4-sci-water-a-q14": ["Ice becoming water is melting — a change of state with heat."],
  "g4-sci-water-a-q15": ["Which home method uses heat to kill germs in drinking water?"],
  "g4-sci-water-a-q16": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-a-q17": ["Rinse water is not for drinking — what garden job can it still do?"],
  "g4-sci-water-a-q18": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-a-q19": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-a-q20": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-a-q21": ["Where is the huge salty store of Earth's water?"],
  "g4-sci-water-a-q22": ["Evaporation is faster with heat, wind, and more open surface."],
  "g4-sci-water-a-q23": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-a-q24": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-b-q01": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q02": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q03": ["Which food is prepared by boiling in water?"],
  "g4-sci-water-b-q04": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q05": ["Which creature lives in water and breathes with gills?"],
  "g4-sci-water-b-q06": ["Ice becoming water is melting — a change of state with heat."],
  "g4-sci-water-b-q07": ["Ice becoming water is which change of state?"],
  "g4-sci-water-b-q08": ["Ice becoming water is melting — a change of state with heat."],
  "g4-sci-water-b-q09": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q10": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-b-q11": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-b-q12": ["Rain seeps down into soil and rock — that store is drawn up by wells."],
  "g4-sci-water-b-q13": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q14": ["Besides drinking, factories need water — for what kinds of jobs?"],
  "g4-sci-water-b-q15": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-b-q16": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-b-q17": ["Cooling vapour high in the sky forms what?"],
  "g4-sci-water-b-q18": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-b-q19": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-b-q20": ["Which source is not salty like the sea?"],
  "g4-sci-water-b-q21": ["About what fraction of Earth's surface is water?"],
  "g4-sci-water-b-q22": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q23": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-b-q24": ["Old stepwells and ponds collected rain — how did that help in dry months?"],
  "g4-sci-plants-a-q01": ["Think which part drinks from the soil and anchors the plant."],
  "g4-sci-plants-a-q02": ["Which green part cooks the plant's food in sunlight?"],
  "g4-sci-plants-a-q03": ["The long science word for \"making food with light\" starts with photo-."],
  "g4-sci-plants-a-q04": ["Plants use a gas we breathe out when they make food \u2014 which one?"],
  "g4-sci-plants-a-q05": ["What useful gas comes out of leaves when they make food?"],
  "g4-sci-plants-a-q06": ["Which green pigment traps sunlight in a leaf?"],
  "g4-sci-plants-a-q07": ["Think of the stem as a tall pipe that also holds the plant upright."],
  "g4-sci-plants-a-q08": ["Carrots grow underground and drink from soil \u2014 which part is that?"],
  "g4-sci-plants-a-q09": ["Palak is green and soft \u2014 which plant part matches that?"],
  "g4-sci-plants-a-q10": ["Cut open a mango or apple \u2014 what small parts grow into new plants?"],
  "g4-sci-plants-a-q11": ["What word means a seed starts sprouting into a baby plant?"],
  "g4-sci-plants-a-q12": ["Think of wetting moong on cotton in a warm room \u2014 what three conditions help?"],
  "g4-sci-plants-a-q13": ["What grows down first to drink water for the baby plant?"],
  "g4-sci-plants-a-q14": ["Think of shade, medicines and oxygen \u2014 why keep useful plants nearby?"],
  "g4-sci-plants-a-q15": ["Which fluffy plant fibre is spun into thread for shirts and kurtas?"],
  "g4-sci-plants-a-q16": ["Which option grows on a plant and lands on our thali?"],
  "g4-sci-plants-a-q17": ["Roots do not have eyes \u2014 what underground part can sprout from eyes?"],
  "g4-sci-plants-a-q18": ["What comes after a flower so the plant can make the next generation?"],
  "g4-sci-plants-a-q19": ["Which tall plant has a thick woody trunk?"],
  "g4-sci-plants-a-q20": ["Tiny leaf pores for gas exchange have a science name starting with sto-."],
  "g4-sci-plants-a-q21": ["What missing condition keeps dry seeds asleep?"],
  "g4-sci-plants-a-q22": ["Which upright part works like a pipe between roots and leaves?"],
  "g4-sci-plants-a-q23": ["Hard wood for chairs and doors comes from which plant part?"],
  "g4-sci-plants-a-q24": ["What dual job do green plants do for food and for the air we breathe?"],
  "g4-sci-plants-b-q01": ["Which option sounds like a flower's job, not a root's?"],
  "g4-sci-plants-b-q02": ["Where is the plant's green kitchen?"],
  "g4-sci-plants-b-q03": ["Why must the leaf's kitchen have light?"],
  "g4-sci-plants-b-q04": ["Which plant has a bunch of thin roots instead of one fat tap root?"],
  "g4-sci-plants-b-q05": ["What do we call the sweet part that grows from a flower and holds a seed?"],
  "g4-sci-plants-b-q06": ["Which place is too cold for a seed to wake up?"],
  "g4-sci-plants-b-q07": ["Which baby part grows up toward light \u2014 plumule or radicle?"],
  "g4-sci-plants-b-q08": ["Shade, oxygen and bird homes \u2014 which answer matches why we plant trees?"],
  "g4-sci-plants-b-q09": ["Strong brown shopping bags often come from which stem fibre?"],
  "g4-sci-plants-b-q10": ["Which kitchen-garden plant is often used in kadha or home remedies?"],
  "g4-sci-plants-b-q11": ["Which part is the water highway from root to leaf?"],
  "g4-sci-plants-b-q12": ["Which thali item starts as a grain from a cereal plant?"],
  "g4-sci-plants-b-q13": ["Where is storing water in a thick stem most useful?"],
  "g4-sci-plants-b-q14": ["What yellow powder do bees move between flowers?"],
  "g4-sci-plants-b-q15": ["Where does a sprouting seed get food before its leaves work?"],
  "g4-sci-plants-b-q16": ["Notebooks start as pulp from which living source?"],
  "g4-sci-plants-b-q17": ["Which colourful, sweet-smelling part invites bees?"],
  "g4-sci-plants-b-q18": ["Carrot shape underground \u2014 one main root or many equal threads?"],
  "g4-sci-plants-b-q19": ["How do trees help people and the planet?"],
  "g4-sci-plants-b-q20": ["Which answer names real plant fibres used for cloth or bags?"],
  "g4-sci-plants-b-q21": ["What does a leaf lose when you remove sunlight?"],
  "g4-sci-plants-b-q22": ["What gas from our breath can plants use to make food?"],
  "g4-sci-plants-b-q23": ["What kitchen product comes from mustard seeds or coconuts?"],
  "g4-sci-plants-b-q24": ["Start with a seed \u2014 what is the growing order toward new seeds?"],
  "g4-sci-animals-a-q01": ["What word means the natural home where an animal lives and finds food?"],
  "g4-sci-animals-a-q02": ["Which animal breathes with gills and swims with fins?"],
  "g4-sci-animals-a-q03": ["Plant-only eaters have which -vore name?"],
  "g4-sci-animals-a-q04": ["Meat-eating hunters are called what?"],
  "g4-sci-animals-a-q05": ["Which group eats both plants and animal food?"],
  "g4-sci-animals-a-q06": ["What desert trick does a camel's hump help with?"],
  "g4-sci-animals-a-q07": ["Why do Arctic animals need thick fur and fat?"],
  "g4-sci-animals-a-q08": ["What group name fits animals that use both water and land?"],
  "g4-sci-animals-a-q09": ["Start with the egg \u2014 what comes before the adult butterfly?"],
  "g4-sci-animals-a-q10": ["What adult animal does a tadpole become?"],
  "g4-sci-animals-a-q11": ["Which place is sandy, hot and short on rain?"],
  "g4-sci-animals-a-q12": ["How does a forest help a plant-eating deer?"],
  "g4-sci-animals-a-q13": ["What organ lets a fish take oxygen from water?"],
  "g4-sci-animals-a-q14": ["What do wings mainly help a bird do?"],
  "g4-sci-animals-a-q15": ["Which hunters snap up insects with a long sticky tongue?"],
  "g4-sci-animals-a-q16": ["What does the rabbit eat in grass \u2192 rabbit \u2192 fox?"],
  "g4-sci-animals-a-q17": ["Which forest animal climbs and uses a long balancing tail?"],
  "g4-sci-animals-a-q18": ["How do hens usually begin their young \u2014 eggs or seeds?"],
  "g4-sci-animals-a-q19": ["Why are a duck's toes joined by skin?"],
  "g4-sci-animals-a-q20": ["Which bird hunts when it is dark?"],
  "g4-sci-animals-a-q21": ["How do tough scales help a crocodile?"],
  "g4-sci-animals-a-q22": ["Which animal is common around village ponds in India?"],
  "g4-sci-animals-a-q23": ["What word means a helpful body feature or habit for survival?"],
  "g4-sci-animals-a-q24": ["What danger does a cool burrow help a desert animal avoid?"],
  "g4-sci-animals-b-q01": ["Where do you find dense trees and lots of rain?"],
  "g4-sci-animals-b-q02": ["What do lions eat \u2014 plants only or other animals?"],
  "g4-sci-animals-b-q03": ["Which listed animal eats plants, not meat?"],
  "g4-sci-animals-b-q04": ["What hunting job do sharp claws and a hooked beak support?"],
  "g4-sci-animals-b-q05": ["How do penguins move best in icy oceans?"],
  "g4-sci-animals-b-q06": ["What stage name is the hungry caterpillar?"],
  "g4-sci-animals-b-q07": ["What new body parts appear as a tadpole becomes a frog?"],
  "g4-sci-animals-b-q08": ["What eats what \u2014 start with the plant?"],
  "g4-sci-animals-b-q09": ["Why are many bird bones light and hollow?"],
  "g4-sci-animals-b-q10": ["Which flying mammal \"sees\" with echoes at night?"],
  "g4-sci-animals-b-q11": ["Why are many fish pointed at the front and smooth?"],
  "g4-sci-animals-b-q12": ["What word means awake and active in daylight?"],
  "g4-sci-animals-b-q13": ["What colour fur blends into snow?"],
  "g4-sci-animals-b-q14": ["What job do flat teeth do for a cow?"],
  "g4-sci-animals-b-q15": ["What does a life-cycle diagram teach about an animal?"],
  "g4-sci-animals-b-q16": ["Which small mammal digs and lives in tunnels underground?"],
  "g4-sci-animals-b-q17": ["Complete the analogy: fish gills match which human breathing organs?"],
  "g4-sci-animals-b-q18": ["What family job does a nest help birds do?"],
  "g4-sci-animals-b-q19": ["How does changing colour help a chameleon survive?"],
  "g4-sci-animals-b-q20": ["Count the legs \u2014 which group usually has six?"],
  "g4-sci-animals-b-q21": ["Why do some birds fly very far when seasons change?"],
  "g4-sci-animals-b-q22": ["Which place is a water home for animals?"],
  "g4-sci-animals-b-q23": ["What does a seal's thick fat do in icy water?"],
  "g4-sci-animals-b-q24": ["Looking at a mixed thali \u2014 why are humans called omnivores?"],
  "g4-sci-body-a-q01": ["Count: eyes, ears, nose, tongue, skin \u2014 how many?"],
  "g4-sci-body-a-q02": ["Which organs are for seeing?"],
  "g4-sci-body-a-q03": ["Which organs catch sound?"],
  "g4-sci-body-a-q04": ["Which sense is the nose for?"],
  "g4-sci-body-a-q05": ["Which sense lets you know if lemonade is sour?"],
  "g4-sci-body-a-q06": ["What covers your body and feels heat or a soft cloth?"],
  "g4-sci-body-a-q07": ["What do we call the whole bony frame of the body?"],
  "g4-sci-body-a-q08": ["Which bony box sits around your brain?"],
  "g4-sci-body-a-q09": ["What important organs sit safely inside the ribcage?"],
  "g4-sci-body-a-q10": ["What soft body parts pull so your arm can bend?"],
  "g4-sci-body-a-q11": ["Besides movement joints, what three jobs do bones do?"],
  "g4-sci-body-a-q12": ["What do we call the place where two bones meet so you can bend?"],
  "g4-sci-body-a-q13": ["Which daily choice builds stronger muscles and bones?"],
  "g4-sci-body-a-q14": ["What do soap and water remove before meals?"],
  "g4-sci-body-a-q15": ["Why do dentists ask you to brush morning and night?"],
  "g4-sci-body-a-q16": ["What does a good night's sleep do for a growing child?"],
  "g4-sci-body-a-q17": ["Why do teachers remind you not to slouch?"],
  "g4-sci-body-a-q18": ["Which mineral-rich foods help bones \u2014 think milk and curd."],
  "g4-sci-body-a-q19": ["What first step keeps germs out of a small wound?"],
  "g4-sci-body-a-q20": ["Why is ear safety important for the hearing sense?"],
  "g4-sci-body-a-q21": ["Which sense organs suffer when you read in a dark corner?"],
  "g4-sci-body-a-q22": ["Why is a water bottle a healthy school habit?"],
  "g4-sci-body-a-q23": ["Which option mixes exercise and rest in a sensible way?"],
  "g4-sci-body-a-q24": ["Which organ is the control centre that reads sense messages?"],
  "g4-sci-body-b-q01": ["Which option pairs the organ with its real sense?"],
  "g4-sci-body-b-q02": ["Which sense turns off when you shut your eyes?"],
  "g4-sci-body-b-q03": ["Why does food taste dull when you cannot smell well?"],
  "g4-sci-body-b-q04": ["Which body part uses many small bones for gripping a pencil?"],
  "g4-sci-body-b-q05": ["Do muscles pull when they shorten, or push like a stick?"],
  "g4-sci-body-b-q06": ["What double job does your spine do for support and nerves?"],
  "g4-sci-body-b-q07": ["Which choice protects sight instead of harming it?"],
  "g4-sci-body-b-q08": ["How does covering a sneeze protect people nearby?"],
  "g4-sci-body-b-q09": ["After kho-kho in the sun, what should you sip most days?"],
  "g4-sci-body-b-q10": ["What three lifestyle pieces build a strong frame?"],
  "g4-sci-body-b-q11": ["How does feeling pain or heat keep you safer?"],
  "g4-sci-body-b-q12": ["Which choice protects the hearing sense?"],
  "g4-sci-body-b-q13": ["Compare an elbow to a door hinge \u2014 how does it move?"],
  "g4-sci-body-b-q14": ["Which schedule covers mind, body and rest?"],
  "g4-sci-body-b-q15": ["What protection do vaccines give with a health worker's care?"],
  "g4-sci-body-b-q16": ["After you sweat a lot, what two simple habits help?"],
  "g4-sci-body-b-q17": ["Why do teachers check for clean nails before a meal?"],
  "g4-sci-body-b-q18": ["How do the skeleton and muscles team up?"],
  "g4-sci-body-b-q19": ["Which sense often notices smoke before you see flames?"],
  "g4-sci-body-b-q20": ["What do we call everyday cleanliness of body and clothes?"],
  "g4-sci-body-b-q21": ["Which pair belongs with the five senses?"],
  "g4-sci-body-b-q22": ["What three things cooperate when you bend a knee?"],
  "g4-sci-body-b-q23": ["Think of a balanced thali \u2014 what mix belongs most days?"],
  "g4-sci-body-b-q24": ["Why do eye-care tips include looking away from screens?"],
};


