import type { HintOverlay } from "./types";

/** Grade 4 Science item-specific hints (overlay; survives content re-ingest) — itemId → [hint, optional hint2]. */
export const G4_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g4-sci-food-a-q01": ["Which nutrient fuels running and playing? Think of rice, roti and potato."],
  "g4-sci-food-a-q02": ["Body-building foods are protein-rich — which card fits that job?"],
  "g4-sci-food-a-q03": ["Sour citrus fruits and amla point to one vitamin letter — which?"],
  "g4-sci-food-a-q04": ["Think of the part of plant food that helps digestion move along like a broom."],
  "g4-sci-food-a-q05": ["Sunshine on skin helps make the vitamin that strengthens bones."],
  "g4-sci-food-a-q06": ["Think of the mineral in milk and curd that builds bones and teeth."],
  "g4-sci-food-a-q07": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-a-q08": ["Which foods are oily or buttery and store lots of energy?"],
  "g4-sci-food-a-q09": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-a-q10": ["Water helps transport nutrients and keep every cell working."],
  "g4-sci-food-a-q11": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-a-q12": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-a-q13": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-a-q14": ["A balanced plate mixes energy, body-building, and protective foods."],
  "g4-sci-food-a-q15": ["Constipation often eases with more fibre and water in meals."],
  "g4-sci-food-a-q16": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-a-q17": ["Which everyday seasoning is enriched to help the thyroid?"],
  "g4-sci-food-a-q18": ["After sweating in the sun, replace lost fluid with a simple healthy drink."],
  "g4-sci-food-a-q19": ["Iodine is a starch test — recall which colour starch turns with iodine."],
  "g4-sci-food-a-q20": ["Extra stored fat is not healthy — moderation matters even for energy foods."],
  "g4-sci-food-a-q21": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-a-q22": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-a-q23": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-a-q24": ["Treats are fine sometimes; everyday food should still be nourishing."],
  "g4-sci-food-b-q01": ["Body-building foods are protein-rich — which option fits that job?"],
  "g4-sci-food-b-q02": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-b-q03": ["Iron-rich foods (leafy greens, jaggery, dates) help blood carry oxygen."],
  "g4-sci-food-b-q04": ["Think of the part of plant food that helps digestion move along like a broom."],
  "g4-sci-food-b-q05": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-b-q06": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-b-q07": ["What do we call a meal plan with every nutrient in sensible amounts?"],
  "g4-sci-food-b-q08": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q09": ["Sunshine on skin helps make the vitamin that strengthens bones."],
  "g4-sci-food-b-q10": ["Fats store energy — ghee, butter, oils, and nuts are fatty foods."],
  "g4-sci-food-b-q11": ["A balanced plate mixes energy, body-building, and protective foods."],
  "g4-sci-food-b-q12": ["Protective foods are fruits and vegetables packed with vitamins and minerals."],
  "g4-sci-food-b-q13": ["Iron-rich foods (leafy greens, jaggery, dates) help blood carry oxygen."],
  "g4-sci-food-b-q14": ["Body-building foods are protein-rich: dal, milk, eggs, beans, fish."],
  "g4-sci-food-b-q15": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q16": ["Pickles last because something stops germs — which kitchen staples do that?"],
  "g4-sci-food-b-q17": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-food-b-q18": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q19": ["Recall which vitamin matches the food or symptom in the question."],
  "g4-sci-food-b-q20": ["Read each food label or card in the figure; match it to the nutrient job asked."],
  "g4-sci-food-b-q21": ["Ask which nutrient builds and repairs the body."],
  "g4-sci-food-b-q22": ["Water helps transport nutrients and keep every cell working."],
  "g4-sci-food-b-q23": ["Roughage (fibre) in veggies and whole grains helps food move through."],
  "g4-sci-food-b-q24": ["Ask which nutrient mainly fuels the body."],
  "g4-sci-matter-a-q01": ["Solids keep their own shape and volume."],
  "g4-sci-matter-a-q02": ["Liquids flow and take the shape of their container."],
  "g4-sci-matter-a-q03": ["Gases spread out and fill all the space in a container."],
  "g4-sci-matter-a-q04": ["What word means anything that takes up space and has weight?"],
  "g4-sci-matter-a-q05": ["Warmth changes ice from solid to liquid — what is that change called, and what forms?"],
  "g4-sci-matter-a-q06": ["Things that keep their own shape are which state of matter?"],
  "g4-sci-matter-a-q07": ["A liquid has no fixed shape — it follows the container you pour it into."],
  "g4-sci-matter-a-q08": ["What invisible gas from your lungs fills a balloon?"],
  "g4-sci-matter-a-q09": ["Cooling a liquid until it becomes solid is which change?"],
  "g4-sci-matter-a-q10": ["Solids keep their own shape and volume."],
  "g4-sci-matter-a-q11": ["Cooling a liquid until it becomes solid is which change?"],
  "g4-sci-matter-a-q12": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q13": ["Solids and liquids have fixed volume; gases do not."],
  "g4-sci-matter-a-q14": ["Melting is solid ice becoming liquid water when it warms."],
  "g4-sci-matter-a-q15": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q16": ["Which option does not flow and keeps tiny crystal shapes?"],
  "g4-sci-matter-a-q17": ["Strong heating that makes water bubble into steam has a special name."],
  "g4-sci-matter-a-q18": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q19": ["Heat turns solid ice cream into a runny liquid — name that change."],
  "g4-sci-matter-a-q20": ["Even if you cannot see it, moving air gives clues — what do you feel or see?"],
  "g4-sci-matter-a-q21": ["Soluble substances disappear into the liquid and make a solution."],
  "g4-sci-matter-a-q22": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q23": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-a-q24": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q01": ["Liquids flow and take the shape of their container."],
  "g4-sci-matter-b-q02": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q03": ["What invisible gas is pumped inside a football?"],
  "g4-sci-matter-b-q04": ["Matter appears in three familiar forms — list them."],
  "g4-sci-matter-b-q05": ["Heat and wind help liquid water turn into invisible vapour."],
  "g4-sci-matter-b-q06": ["Solids keep their own shape and volume."],
  "g4-sci-matter-b-q07": ["Without a container, what does a liquid do on a flat floor?"],
  "g4-sci-matter-b-q08": ["Which option can pour or drip, even if slowly?"],
  "g4-sci-matter-b-q09": ["Warmth turns solid ice into liquid water — what is that change called?"],
  "g4-sci-matter-b-q10": ["Which substance spreads everywhere unless sealed in a closed container?"],
  "g4-sci-matter-b-q11": ["Solids and liquids have fixed volume; gases do not."],
  "g4-sci-matter-b-q12": ["When vapour cools, it turns back into tiny liquid drops."],
  "g4-sci-matter-b-q13": ["Melting is solid ice becoming liquid water when it warms."],
  "g4-sci-matter-b-q14": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q15": ["Melting is solid ice becoming liquid water when it warms."],
  "g4-sci-matter-b-q16": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q17": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q18": ["Three options flow; one keeps a fixed shape — find the odd one."],
  "g4-sci-matter-b-q19": ["Cooling vapour high up forms tiny drops — what do we call that collection?"],
  "g4-sci-matter-b-q20": ["Pumping presses more gas into the same space — how does that change the tyre?"],
  "g4-sci-matter-b-q21": ["Recall: which state has fixed volume but not fixed shape?"],
  "g4-sci-matter-b-q22": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q23": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-matter-b-q24": ["Use the figure: decide if what you see keeps shape, flows, or fills all space."],
  "g4-sci-water-a-q01": ["Which everyday liquid covers most of Earth and fills rivers and taps?"],
  "g4-sci-water-a-q02": ["Natural sources include rain, rivers, lakes, ponds, and wells."],
  "g4-sci-water-a-q03": ["Clouds are tiny water drops; when heavy enough they fall as that change."],
  "g4-sci-water-a-q04": ["Rain seeps down into soil and rock — that store is drawn up by wells."],
  "g4-sci-water-a-q05": ["Sea water has something dissolved in it that changes its taste."],
  "g4-sci-water-a-q06": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-a-q07": ["Why do fields and farms need so much water?"],
  "g4-sci-water-a-q08": ["What heat source turns pond water into vapour on a hot day?"],
  "g4-sci-water-a-q09": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-a-q10": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-a-q11": ["Liquid becoming vapour has a special name — which change is that?"],
  "g4-sci-water-a-q12": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-a-q13": ["Rain seeps down into soil and rock — that store is drawn up by wells."],
  "g4-sci-water-a-q14": ["Ice becoming water is melting — a change of state with heat."],
  "g4-sci-water-a-q15": ["Which home method uses heat to kill germs in drinking water?"],
  "g4-sci-water-a-q16": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-a-q17": ["Rinse water is not for drinking — what garden job can it still do?"],
  "g4-sci-water-a-q18": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-a-q19": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-a-q20": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-a-q21": ["Where is the huge salty store of Earth's water?"],
  "g4-sci-water-a-q22": ["Evaporation is faster with heat, wind, and more open surface."],
  "g4-sci-water-a-q23": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-a-q24": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-b-q01": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q02": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q03": ["Which food is prepared by boiling in water?"],
  "g4-sci-water-b-q04": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q05": ["Which creature lives in water and breathes with gills?"],
  "g4-sci-water-b-q06": ["Ice becoming water is melting — a change of state with heat."],
  "g4-sci-water-b-q07": ["Ice becoming water is which change of state?"],
  "g4-sci-water-b-q08": ["Ice becoming water is melting — a change of state with heat."],
  "g4-sci-water-b-q09": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q10": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-b-q11": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-b-q12": ["Rain seeps down into soil and rock — that store is drawn up by wells."],
  "g4-sci-water-b-q13": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q14": ["Besides drinking, factories need water — for what kinds of jobs?"],
  "g4-sci-water-b-q15": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-b-q16": ["Boiling, filtering, and keeping sources clean make water safer to drink."],
  "g4-sci-water-b-q17": ["Cooling vapour high in the sky forms what?"],
  "g4-sci-water-b-q18": ["Clouds are tiny water drops; when heavy enough they fall as rain."],
  "g4-sci-water-b-q19": ["Choose the habit that uses less water or reuses it."],
  "g4-sci-water-b-q20": ["Which source is not salty like the sea?"],
  "g4-sci-water-b-q21": ["About what fraction of Earth's surface is water?"],
  "g4-sci-water-b-q22": ["Follow the arrows or stages in the figure through the water's journey."],
  "g4-sci-water-b-q23": ["Trace evaporate → condense into clouds → precipitate as rain."],
  "g4-sci-water-b-q24": ["Old stepwells and ponds collected rain — how did that help in dry months?"],
};

