import type { HintOverlay } from "./types";

/** Grade 5 English item-specific hints (overlay) */
export const G5_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g5-eng-ch02-a-q01": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q04": ["A proper noun is a special name and starts with a capital letter."],
  "g5-eng-ch02-a-q05": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch02-a-q06": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q07": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-a-q08": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-a-q09": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q10": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-a-q11": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-a-q12": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-a-q13": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-a-q14": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-a-q15": ["An adjective describes a noun — which word tells more about a thing?"],
  "g5-eng-ch02-a-q16": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-a-q17": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-a-q18": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-a-q19": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q20": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-a-q21": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q22": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q23": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q24": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q01": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-b-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q03": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q04": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q05": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch02-b-q06": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch02-b-q07": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q08": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q09": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q10": ["A common noun is a general name for a person, place, or thing."],
  "g5-eng-ch02-b-q11": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q12": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q13": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-b-q14": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-b-q15": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-b-q16": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-b-q17": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-b-q18": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-b-q19": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-b-q20": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-b-q21": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q22": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q23": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q24": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch03-a-q01": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch03-a-q02": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q03": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q04": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-a-q05": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch03-a-q06": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q07": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q08": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q09": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q10": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q11": ["Pick the word closest in meaning; test it in the sentence."],
  "g5-eng-ch03-a-q12": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-a-q13": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-a-q14": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q15": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q16": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q17": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q18": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q19": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q20": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch03-a-q21": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q22": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q23": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q24": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q01": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q02": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q03": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q04": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q05": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q06": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q07": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q08": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q09": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q10": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q11": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q12": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q13": ["Pick the word closest in meaning; test it in the sentence."],
  "g5-eng-ch03-b-q14": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-b-q15": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q16": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q17": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q18": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q19": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q20": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q21": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q22": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q23": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q24": ["Use word meaning, word parts, or context to decide."],
};

