import type { HintOverlay } from "./types";

/** Grade 5 English item-specific hints (overlay) */
export const G5_ENGLISH_HINTS: Record<string, HintOverlay> = {
  // Ch1 Detective Eyes — Set A
  "g5-eng-ch01-a-q01": ["Ask what the whole passage is about, not just one detail."],
  "g5-eng-ch01-a-q02": ["Go back to the exact line that says where the prints disappeared."],
  "g5-eng-ch01-a-q03": ["Link the white rice flour on the rangoli to the kitten’s dusty paws."],
  "g5-eng-ch01-a-q04": ["A frown shows something feels wrong or confusing — what had she just noticed?"],
  "g5-eng-ch01-a-q05": ["Judge Kavya from what she does: she laughs, then adds a kitten to her design."],
  "g5-eng-ch01-a-q06": ["Check the first sentence for what Rohan was getting ready for."],
  "g5-eng-ch01-a-q07": ["Watch for NOT — which option is why he thought it would stay dry?"],
  "g5-eng-ch01-a-q08": ["The phrase describes the sky; what covers the sky like a thick blanket?"],
  "g5-eng-ch01-a-q09": ["Pick the lesson that fits the whole story: nature clues + listening to Dadi."],
  "g5-eng-ch01-a-q10": ["Use order words: First / Next / Then / Finally — what came first?"],
  "g5-eng-ch01-a-q11": ["Scan for the words “borrowing card” and read who designed it."],
  "g5-eng-ch01-a-q12": ["Empty shelves mean books are out with readers — that is the compliment."],
  "g5-eng-ch01-a-q13": ["A notice has several dates; find the last day to give your name."],
  "g5-eng-ch01-a-q14": ["Find what the club will provide — those are items you need not bring."],
  "g5-eng-ch01-a-q15": ["An adverb tells how an action happens; many end in -ly."],
  "g5-eng-ch01-a-q16": ["Drop “Priya and” and try the sentence: would you say I or me?"],
  "g5-eng-ch01-a-q17": ["Silent h in honest → an; we always say the truth."],
  "g5-eng-ch01-a-q18": ["“Look!” means it is happening now — use am/is/are + -ing."],
  "g5-eng-ch01-a-q19": ["Choose the preposition that shows position below something."],
  "g5-eng-ch01-a-q20": ["He wanted one thing, rain did another — join opposite ideas with but."],
  "g5-eng-ch01-a-q21": ["The prefix un- means “not”; which form of happy is real English?"],
  "g5-eng-ch01-a-q22": ["The kindest reply offers help and does not blame."],
  "g5-eng-ch01-a-q23": ["Order as who + action + what + when."],
  "g5-eng-ch01-a-q24": ["Same spelling, different jobs: one is an action, one names a kind of tower."],
  // Ch1 Detective Eyes — Set B
  "g5-eng-ch01-b-q01": ["Find what Kavya left near the gate for the visiting kitten."],
  "g5-eng-ch01-b-q02": ["Retell the events in order; drawing the kitten is the final action."],
  "g5-eng-ch01-b-q03": ["She is joking — whose “art” were the star-shaped prints?"],
  "g5-eng-ch01-b-q04": ["“Visited” means came to see; try that meaning in the sentence."],
  "g5-eng-ch01-b-q05": ["A good title matches the main idea: Dadi’s warning came true."],
  "g5-eng-ch01-b-q06": ["Find the direction word in the sky description."],
  "g5-eng-ch01-b-q07": ["“Drummed” compares rain to a drum — what kind of sound is that?"],
  "g5-eng-ch01-b-q08": ["He stayed dry because of his umbrella; what does that say about the others?"],
  "g5-eng-ch01-b-q09": ["“He grinned” and decided to listen more — what feeling does that show?"],
  "g5-eng-ch01-b-q10": ["Ask what the whole passage covers: dusty cupboard → steps → busy library."],
  "g5-eng-ch01-b-q11": ["Count the named piles: stories, science, and poems."],
  "g5-eng-ch01-b-q12": ["“Once” means at an earlier time — the books had been ignored before."],
  "g5-eng-ch01-b-q13": ["Labels came Next; Then came the next step — what was it?"],
  "g5-eng-ch01-b-q14": ["A notice’s purpose is usually in its first lines — who is invited to do what?"],
  "g5-eng-ch01-b-q15": ["The writer’s name and role usually appear at the end of a notice."],
  "g5-eng-ch01-b-q16": ["Check who the notice invites; Class 3 is not in that list."],
  "g5-eng-ch01-b-q17": ["Adjectives describe nouns — which words tell more about sparrow and nest?"],
  "g5-eng-ch01-b-q18": ["“Yesterday” signals the past — use the simple past verb."],
  "g5-eng-ch01-b-q19": ["Use in for months; on for days/dates; at for clock times."],
  "g5-eng-ch01-b-q20": ["Here or means “if you don’t” — what happens if you skip the advice?"],
  "g5-eng-ch01-b-q21": ["The suffix -ness turns an adjective into a noun (kind → …)."],
  "g5-eng-ch01-b-q22": ["Ancient means very old; pick the opposite of long-ago, not a synonym."],
  "g5-eng-ch01-b-q23": ["“May I” asks permission; “please” adds politeness."],
  "g5-eng-ch01-b-q24": ["Capitalise the question, put ? inside the quotation marks, then asked Meena."],
  // Ch2 Grammar
  "g5-eng-ch02-a-q01": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q04": ["A proper noun is a special name and starts with a capital letter."],
  "g5-eng-ch02-a-q05": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch02-a-q06": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q07": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-a-q08": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-a-q09": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q10": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-a-q11": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-a-q12": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-a-q13": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-a-q14": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-a-q15": ["An adjective describes a noun — which word tells more about a thing?"],
  "g5-eng-ch02-a-q16": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-a-q17": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-a-q18": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-a-q19": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q20": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-a-q21": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-a-q22": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q23": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-a-q24": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q01": ["A noun names a person, place, thing, or idea."],
  "g5-eng-ch02-b-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q03": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q04": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q05": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch02-b-q06": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch02-b-q07": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q08": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q09": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q10": ["A common noun is a general name for a person, place, or thing."],
  "g5-eng-ch02-b-q11": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q12": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q13": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-b-q14": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g5-eng-ch02-b-q15": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-b-q16": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-b-q17": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-b-q18": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-b-q19": ["Read the whole sentence; choose the word that fits grammar and meaning."],
  "g5-eng-ch02-b-q20": ["A verb shows an action or a state of being."],
  "g5-eng-ch02-b-q21": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q22": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch02-b-q23": ["Name the grammar job or rule being tested in the sentence."],
  "g5-eng-ch02-b-q24": ["Match the verb form to the time and the subject in the sentence."],
  // Ch3 Words
  "g5-eng-ch03-a-q01": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch03-a-q02": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q03": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q04": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-a-q05": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g5-eng-ch03-a-q06": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q07": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q08": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q09": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q10": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q11": ["Pick the word closest in meaning; test it in the sentence."],
  "g5-eng-ch03-a-q12": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-a-q13": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-a-q14": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q15": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q16": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q17": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q18": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q19": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q20": ["Match the verb form to the time and the subject in the sentence."],
  "g5-eng-ch03-a-q21": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q22": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q23": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-a-q24": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q01": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q02": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q03": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q04": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q05": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q06": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q07": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q08": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q09": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q10": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q11": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q12": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q13": ["Pick the word closest in meaning; test it in the sentence."],
  "g5-eng-ch03-b-q14": ["Pick the word with the opposite meaning."],
  "g5-eng-ch03-b-q15": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q16": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q17": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q18": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q19": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q20": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q21": ["Check four things: apostrophe for belonging, comma before the speech, inverted commas around only the spoken words, full stop inside them."],
  "g5-eng-ch03-b-q22": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q23": ["Use word meaning, word parts, or context to decide."],
  "g5-eng-ch03-b-q24": ["Use word meaning, word parts, or context to decide."],
  // Ch4 Talk It Out — Spoken English
  "g5-eng-ch04-a-q01": ["Find Meera's first spoken line — how does she open?"],
  "g5-eng-ch04-a-q02": ["Look for a line that offers a choice with Would you like…?"],
  "g5-eng-ch04-a-q03": ["Could you…? softens a request for information."],
  "g5-eng-ch04-a-q04": ["Meera is helping a new student learn class habits."],
  "g5-eng-ch04-a-q05": ["Scan for thanks and how Arjun says he feels."],
  "g5-eng-ch04-a-q06": ["How does Kabir prove it is him on the line?"],
  "g5-eng-ch04-a-q07": ["Why mention dinner when starting a call?"],
  "g5-eng-ch04-a-q08": ["Pick the line that asks for the homework details."],
  "g5-eng-ch04-a-q09": ["What extra help does Kabir offer beyond listing questions?"],
  "g5-eng-ch04-a-q10": ["Find the goodbye and kind wishes at the end."],
  "g5-eng-ch04-a-q11": ["What does the visitor say she came to collect?"],
  "g5-eng-ch04-a-q12": ["List the steps: past the playground, then…"],
  "g5-eng-ch04-a-q13": ["Would you like…? offers help without forcing it."],
  "g5-eng-ch04-a-q14": ["Which line repeats the route to check understanding?"],
  "g5-eng-ch04-a-q15": ["The speaker names herself near the start."],
  "g5-eng-ch04-a-q16": ["Find the clock time and place for Classes 4 and 5."],
  "g5-eng-ch04-a-q17": ["Look for the Do not… instruction."],
  "g5-eng-ch04-a-q18": ["A good apology owns the mistake and offers help."],
  "g5-eng-ch04-a-q19": ["Could I… please? asks permission; it does not demand."],
  "g5-eng-ch04-a-q20": ["Explain briefly and offer to take a message."],
  "g5-eng-ch04-a-q21": ["A clear invite names the event, day and time."],
  "g5-eng-ch04-a-q22": ["Excuse me plus a calm request keeps respect."],
  "g5-eng-ch04-a-q23": ["Use Good morning and a proper title for a teacher."],
  "g5-eng-ch04-a-q24": ["Thank the host and say a friendly goodbye."],
  "g5-eng-ch04-b-q01": ["Find Arjun's thanks right after the welcome."],
  "g5-eng-ch04-b-q02": ["He is new — why accept a tour of bags and lunch boxes?"],
  "g5-eng-ch04-b-q03": ["May I…? asks permission before helping."],
  "g5-eng-ch04-b-q04": ["What does Ms. Kapoor like students to do before speaking?"],
  "g5-eng-ch04-b-q05": ["Why did Riya miss Maths, and what does she need?"],
  "g5-eng-ch04-b-q06": ["Shall I…? gently offers to do something useful."],
  "g5-eng-ch04-b-q07": ["Kabir lists what to bring with the homework."],
  "g5-eng-ch04-b-q08": ["Feel better soon is a kindness about her fever."],
  "g5-eng-ch04-b-q09": ["Which door and landmark mark the office?"],
  "g5-eng-ch04-b-q10": ["How may I help you? is a service greeting."],
  "g5-eng-ch04-b-q11": ["Thoughtful praises kindness — check her reply."],
  "g5-eng-ch04-b-q12": ["The guard says who to ask if she gets confused."],
  "g5-eng-ch04-b-q13": ["Name the event Ananya announces for tomorrow."],
  "g5-eng-ch04-b-q14": ["What should students do after practice ends?"],
  "g5-eng-ch04-b-q15": ["Why end a public announcement with thanks and a wish?"],
  "g5-eng-ch04-b-q16": ["Apologise, give a short reason, then greet the birthday child."],
  "g5-eng-ch04-b-q17": ["Excuse me, ma'am — could you please…? fits class."],
  "g5-eng-ch04-b-q18": ["Wait your turn, then speak softly with Excuse me."],
  "g5-eng-ch04-b-q19": ["Decline with a reason and still thank them for inviting you."],
  "g5-eng-ch04-b-q20": ["Apologise, say wrong number, and end politely."],
  "g5-eng-ch04-b-q21": ["A simple thank-you is warm without bragging."],
  "g5-eng-ch04-b-q22": ["Acknowledge their idea, then share yours calmly."],
  "g5-eng-ch04-b-q23": ["Greet the postman and offer help at the door."],
  "g5-eng-ch04-b-q24": ["Thank the teacher before you leave the meeting."],
  // Ch5 Write It Right — Writing & Formats
  "g5-eng-ch05-a-q01": ["Read the notice heading — what event is named?"],
  "g5-eng-ch05-a-q02": ["Notices end with name and role — who signed?"],
  "g5-eng-ch05-a-q03": ["Find the last day to give names to the monitor."],
  "g5-eng-ch05-a-q04": ["What must you bring if you want to exchange books?"],
  "g5-eng-ch05-a-q05": ["Watch for NOT — which detail never appears?"],
  "g5-eng-ch05-a-q06": ["Informal letters start with the sender's address."],
  "g5-eng-ch05-a-q07": ["Who is named after Dear…?"],
  "g5-eng-ch05-a-q08": ["Find the word favourite in Dev's museum news."],
  "g5-eng-ch05-a-q09": ["Friends close with Your friend, not Yours faithfully."],
  "g5-eng-ch05-a-q10": ["Why ask about picnic and Fancy Dress in a friendly letter?"],
  "g5-eng-ch05-a-q11": ["Messages end with the writer's name."],
  "g5-eng-ch05-a-q12": ["Compare the old PTM time with the new one."],
  "g5-eng-ch05-a-q13": ["What did Ms. D'Souza ask Amma to bring?"],
  "g5-eng-ch05-a-q14": ["Messages exist to pass key facts quickly."],
  "g5-eng-ch05-a-q15": ["Diary entries often open with day and date."],
  "g5-eng-ch05-a-q16": ["What happened in the afternoon paragraph?"],
  "g5-eng-ch05-a-q17": ["Find tired and proud in the same sentence."],
  "g5-eng-ch05-a-q18": ["Ask who a diary is really written for."],
  "g5-eng-ch05-a-q19": ["List the usual notice parts: heading, date, facts, name/role."],
  "g5-eng-ch05-a-q20": ["Where does the writer's address sit in a friendly letter?"],
  "g5-eng-ch05-a-q21": ["Many readers at school → which format?"],
  "g5-eng-ch05-a-q22": ["One reader at home who missed a call → which format?"],
  "g5-eng-ch05-a-q23": ["Friendly news sounds chatty, not like a notice."],
  "g5-eng-ch05-a-q24": ["Unknown formal reader → Yours faithfully."],
  "g5-eng-ch05-b-q01": ["Find the place named for Library Week events."],
  "g5-eng-ch05-b-q02": ["Which two classes does the notice inform?"],
  "g5-eng-ch05-b-q03": ["Scan the list of Library Week activities."],
  "g5-eng-ch05-b-q04": ["Why put an issue date at the top of a notice?"],
  "g5-eng-ch05-b-q05": ["Read the date line under Dev's address."],
  "g5-eng-ch05-b-q06": ["Which two questions does Dev ask Anvi?"],
  "g5-eng-ch05-b-q07": ["Regards to Uncle and Aunty sit near the end."],
  "g5-eng-ch05-b-q08": ["Dear Anvi plus personal news = informal letter."],
  "g5-eng-ch05-b-q09": ["Who is named after Dear in the message?"],
  "g5-eng-ch05-b-q10": ["Messages often show date and clock time at the top."],
  "g5-eng-ch05-b-q11": ["Where did Kabir go, and when will he return?"],
  "g5-eng-ch05-b-q12": ["Which fact does not help Amma act on the call?"],
  "g5-eng-ch05-b-q13": ["Who brought lemonade during the clean-up?"],
  "g5-eng-ch05-b-q14": ["Read Zara's plan for tomorrow near the end."],
  "g5-eng-ch05-b-q15": ["Dear Diary addresses the journal itself."],
  "g5-eng-ch05-b-q16": ["Date/time, greeting, facts, name — message checklist."],
  "g5-eng-ch05-b-q17": ["Address → date → Dear… → body → closing → name."],
  "g5-eng-ch05-b-q18": ["Personal feelings about a day suit a diary."],
  "g5-eng-ch05-b-q19": ["News for a friend in another city suits an informal letter."],
  "g5-eng-ch05-b-q20": ["Whole-school facts belong on a notice board."],
  "g5-eng-ch05-b-q21": ["Formal letters open with Respected Sir/Madam."],
  "g5-eng-ch05-b-q22": ["Group instructions sound like a notice, not a diary."],
  "g5-eng-ch05-b-q23": ["Bossy commands with !!! are too rude for the Principal."],
  "g5-eng-ch05-b-q24": ["Name and designation appear together at the end."],
};
