import type { HintOverlay } from "./types";

/** Grade 5 Maths item-specific hints (overlay) */
export const G5_MATHS_HINTS: Record<string, HintOverlay> = {
  "g5-maths-angles-a-q01": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q02": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q03": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-a-q04": ["Vertex = corner point; arms = the two rays."],
  "g5-maths-angles-a-q05": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-a-q06": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q07": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q08": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q09": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-a-q10": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q11": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q12": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q13": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q14": ["A right angle is a square corner — like a book corner."],
  "g5-maths-angles-a-q15": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q16": ["Vertex = corner point; arms = the two rays."],
  "g5-maths-angles-a-q17": ["A right angle is a square corner — like a book corner."],
  "g5-maths-angles-a-q18": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q19": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-a-q20": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q21": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q22": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q23": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-a-q24": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q01": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q02": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q03": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-b-q04": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q05": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q06": ["Acute angles are sharper than a right angle (less than 90°)."],
  "g5-maths-angles-b-q07": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q08": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q09": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q10": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-b-q11": ["A right angle is a square corner — like a book corner."],
  "g5-maths-angles-b-q12": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q13": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q14": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q15": ["Vertex = corner point; arms = the two rays."],
  "g5-maths-angles-b-q16": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q17": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q18": ["Vertex = corner point; arms = the two rays."],
  "g5-maths-angles-b-q19": ["Obtuse angles are wider than a right angle but less than 180°."],
  "g5-maths-angles-b-q20": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q21": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-angles-b-q22": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-b-q23": ["A straight angle is a flat half-turn — 180°."],
  "g5-maths-angles-b-q24": ["Classify by size: acute < right < obtuse < straight."],
  "g5-maths-frac-a-q01": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-a-q02": ["Denominator is the bottom number — total equal parts."],
  "g5-maths-frac-a-q03": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-a-q04": ["A unit fraction has 1 as the numerator."],
  "g5-maths-frac-a-q05": ["Count the shaded parts in the figure first, then all equal parts."],
  "g5-maths-frac-a-q06": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-a-q07": ["For unit fractions, a bigger bottom means a smaller piece."],
  "g5-maths-frac-a-q08": ["Multiply or divide top and bottom by the same number."],
  "g5-maths-frac-a-q09": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g5-maths-frac-a-q10": ["Improper: top ≥ bottom. Mixed: whole + proper fraction."],
  "g5-maths-frac-a-q11": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-a-q12": ["For unit fractions, a bigger bottom means a smaller piece."],
  "g5-maths-frac-a-q13": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g5-maths-frac-a-q14": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-a-q15": ["Improper: top ≥ bottom. Mixed: whole + proper fraction."],
  "g5-maths-frac-a-q16": ["Count equal jumps from 0 to 1, then see where the point sits."],
  "g5-maths-frac-a-q17": ["For unit fractions, a bigger bottom means a smaller piece."],
  "g5-maths-frac-a-q18": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-a-q19": ["Parts you care about over total equal parts."],
  "g5-maths-frac-a-q20": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g5-maths-frac-a-q21": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-a-q22": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g5-maths-frac-a-q23": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-a-q24": ["Count equal jumps from 0 to 1, then see where the point sits."],
  "g5-maths-frac-b-q01": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-b-q02": ["Numerator is the top number — parts you count."],
  "g5-maths-frac-b-q03": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-b-q04": ["A unit fraction has 1 as the numerator."],
  "g5-maths-frac-b-q05": ["Count the shaded parts in the figure first, then all equal parts."],
  "g5-maths-frac-b-q06": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-b-q07": ["For unit fractions, a bigger bottom means a smaller piece."],
  "g5-maths-frac-b-q08": ["Multiply or divide top and bottom by the same number."],
  "g5-maths-frac-b-q09": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g5-maths-frac-b-q10": ["Improper: top ≥ bottom. Mixed: whole + proper fraction."],
  "g5-maths-frac-b-q11": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-b-q12": ["For unit fractions, a bigger bottom means a smaller piece."],
  "g5-maths-frac-b-q13": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g5-maths-frac-b-q14": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-b-q15": ["Improper: top ≥ bottom. Mixed: whole + proper fraction."],
  "g5-maths-frac-b-q16": ["Count equal jumps from 0 to 1, then see where the point sits."],
  "g5-maths-frac-b-q17": ["For unit fractions, a bigger bottom means a smaller piece."],
  "g5-maths-frac-b-q18": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-b-q19": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-b-q20": ["Add only when bottoms match; add tops, keep bottom."],
  "g5-maths-frac-b-q21": ["Name the whole, count equal parts, write parts-over-total."],
  "g5-maths-frac-b-q22": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-b-q23": ["Fraction left = whole minus the fraction taken."],
  "g5-maths-frac-b-q24": ["Divide the whole by the bottom number, then multiply by the top if needed."],
  "g5-maths-large-a-q01": ["Match the number name to hundreds, tens and ones — put 0 in empty places."],
  "g5-maths-large-a-q02": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g5-maths-large-a-q03": ["Find the named place, then read or compute the digit's worth."],
  "g5-maths-large-a-q04": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-a-q05": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-a-q06": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-a-q07": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-a-q08": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-a-q09": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-a-q10": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-a-q11": ["Find the named place, then read or compute the digit's worth."],
  "g5-maths-large-a-q12": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-a-q13": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-a-q14": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-a-q15": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-a-q16": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g5-maths-large-a-q17": ["Use place value to build, compare, or calculate as asked."],
  "g5-maths-large-a-q18": ["Use place value to build, compare, or calculate as asked."],
  "g5-maths-large-a-q19": ["Just after / successor means one more."],
  "g5-maths-large-a-q20": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-a-q21": ["Use place value to build, compare, or calculate as asked."],
  "g5-maths-large-a-q22": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-a-q23": ["Use place value to build, compare, or calculate as asked."],
  "g5-maths-large-a-q24": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-b-q01": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-b-q02": ["Use place value to build, compare, or calculate as asked."],
  "g5-maths-large-b-q03": ["Find the named place, then read or compute the digit's worth."],
  "g5-maths-large-b-q04": ["Write each digit times its place, joined with +."],
  "g5-maths-large-b-q05": ["Find the jump size on the line, then count jumps to the point."],
  "g5-maths-large-b-q06": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-b-q07": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-b-q08": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-b-q09": ["Find what is added or taken each time, then do that again."],
  "g5-maths-large-b-q10": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-b-q11": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-b-q12": ["Compare digits from the left-most place until they differ."],
  "g5-maths-large-b-q13": ["Match the number name to hundreds, tens and ones — put 0 in empty places."],
  "g5-maths-large-b-q14": ["Check the digit one place to the right: 0–4 stay, 5–9 round up."],
  "g5-maths-large-b-q15": ["Use place value to build, compare, or calculate as asked."],
  "g5-maths-large-b-q16": ["Even numbers end in 0, 2, 4, 6 or 8; odd end in 1, 3, 5, 7 or 9."],
  "g5-maths-large-b-q17": ["Use place value to build, compare, or calculate as asked."],
  "g5-maths-large-b-q18": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-b-q19": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-b-q20": ["Greatest: largest digits first. Smallest: smallest first, but not starting with 0."],
  "g5-maths-large-b-q21": ["Find the named place, then read or compute the digit's worth."],
  "g5-maths-large-b-q22": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-b-q23": ["Look at the figure first; read every label before choosing."],
  "g5-maths-large-b-q24": ["Find what is added or taken each time, then do that again."],
};

