import type { HintOverlay } from "./types";

/** Grade 5 Science item-specific hints (overlay) */
export const G5_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g5-sci-body-a-q01": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q02": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q03": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q04": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q05": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q06": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q07": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q08": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q09": ["The brain controls the body; nerves carry messages."],
  "g5-sci-body-a-q10": ["The brain controls the body; nerves carry messages."],
  "g5-sci-body-a-q11": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q12": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q13": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q14": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q15": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-a-q16": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q17": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q18": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-a-q19": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q20": ["The brain controls the body; nerves carry messages."],
  "g5-sci-body-a-q21": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q22": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-a-q23": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q24": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q01": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q02": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q03": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q04": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q05": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q06": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q07": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q08": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q09": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q10": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q11": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q12": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q13": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q14": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q15": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q16": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q17": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q18": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q19": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q20": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q21": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q22": ["Lungs exchange gases: oxygen in, carbon dioxide out."],
  "g5-sci-body-b-q23": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q24": ["Bones support and protect; joints let bones move."],
  "g5-sci-plants-a-q01": ["Look at the opened seed in the figure; match each letter to coat, food store, or baby plant."],
  "g5-sci-plants-a-q02": ["Roots take in water and minerals and anchor the plant."],
  "g5-sci-plants-a-q03": ["Plumule is the baby shoot — it grows upward into stem and leaves."],
  "g5-sci-plants-a-q04": ["Cotyledons are the seed's food stores for the baby plant."],
  "g5-sci-plants-a-q05": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q06": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q07": ["The radicle is the baby root — usually first to emerge."],
  "g5-sci-plants-a-q08": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q09": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q10": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q11": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q12": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-a-q13": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q14": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q15": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q16": ["Cotyledons are the seed's food stores for the baby plant."],
  "g5-sci-plants-a-q17": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q18": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q19": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q20": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q21": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q22": ["A fruit grows from the flower's ovary and holds seeds."],
  "g5-sci-plants-a-q23": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q24": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q01": ["Look at the opened seed in the figure; match each letter to coat, food store, or baby plant."],
  "g5-sci-plants-b-q02": ["Look at the opened seed in the figure; match each letter to coat, food store, or baby plant."],
  "g5-sci-plants-b-q03": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q04": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q05": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q06": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q07": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q08": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q09": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q10": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q11": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q12": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q13": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q14": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q15": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q16": ["Cotyledons are the seed's food stores for the baby plant."],
  "g5-sci-plants-b-q17": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q18": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q19": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q20": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q21": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q22": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q23": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q24": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-space-a-q01": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-a-q02": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q03": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q04": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-a-q05": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q06": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q07": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q08": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q09": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q10": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q11": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-a-q12": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-a-q13": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q14": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q15": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q16": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q17": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q18": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-a-q19": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q20": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q21": ["Earth's year is one orbit of the Sun; tilt helps make seasons."],
  "g5-sci-space-a-q22": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q23": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q24": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-b-q01": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-b-q02": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q03": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q04": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q05": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-b-q06": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-b-q07": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q08": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q09": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-b-q10": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q11": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-b-q12": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q13": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q14": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q15": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q16": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q17": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-b-q18": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-b-q19": ["Stars make their own light; planets reflect sunlight."],
  "g5-sci-space-b-q20": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q21": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q22": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-b-q23": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q24": ["Phases depend on how much of the Moon's lit side we see from Earth."],
};

