import type { HintOverlay } from "./types";

/** Grade 5 Science item-specific hints (overlay) */
export const G5_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g5-sci-body-a-q01": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q02": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q03": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q04": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q05": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q06": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q07": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q08": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q09": ["The brain controls the body; nerves carry messages."],
  "g5-sci-body-a-q10": ["The brain controls the body; nerves carry messages."],
  "g5-sci-body-a-q11": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q12": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q13": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q14": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q15": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-a-q16": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q17": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q18": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-a-q19": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q20": ["The brain controls the body; nerves carry messages."],
  "g5-sci-body-a-q21": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-a-q22": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-a-q23": ["Muscles pull on bones to create movement."],
  "g5-sci-body-a-q24": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q01": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q02": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q03": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q04": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q05": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q06": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q07": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q08": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q09": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q10": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q11": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q12": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q13": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q14": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q15": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q16": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q17": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q18": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q19": ["Match the organ or system to its main job."],
  "g5-sci-body-b-q20": ["Look at the labelled organ or system in the figure."],
  "g5-sci-body-b-q21": ["Bones support and protect; joints let bones move."],
  "g5-sci-body-b-q22": ["Lungs exchange gases: oxygen in, carbon dioxide out."],
  "g5-sci-body-b-q23": ["Muscles pull on bones to create movement."],
  "g5-sci-body-b-q24": ["Bones support and protect; joints let bones move."],
  "g5-sci-plants-a-q01": ["Look at the opened seed in the figure; match each letter to coat, food store, or baby plant."],
  "g5-sci-plants-a-q02": ["Roots take in water and minerals and anchor the plant."],
  "g5-sci-plants-a-q03": ["Plumule is the baby shoot — it grows upward into stem and leaves."],
  "g5-sci-plants-a-q04": ["Cotyledons are the seed's food stores for the baby plant."],
  "g5-sci-plants-a-q05": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q06": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q07": ["The radicle is the baby root — usually first to emerge."],
  "g5-sci-plants-a-q08": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q09": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q10": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q11": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q12": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-a-q13": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q14": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q15": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q16": ["Cotyledons are the seed's food stores for the baby plant."],
  "g5-sci-plants-a-q17": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-a-q18": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q19": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q20": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q21": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q22": ["A fruit grows from the flower's ovary and holds seeds."],
  "g5-sci-plants-a-q23": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-a-q24": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q01": ["Look at the opened seed in the figure; match each letter to coat, food store, or baby plant."],
  "g5-sci-plants-b-q02": ["Look at the opened seed in the figure; match each letter to coat, food store, or baby plant."],
  "g5-sci-plants-b-q03": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q04": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q05": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q06": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q07": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q08": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q09": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q10": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q11": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q12": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q13": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q14": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q15": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q16": ["Cotyledons are the seed's food stores for the baby plant."],
  "g5-sci-plants-b-q17": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q18": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q19": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q20": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q21": ["A seed holds a baby plant plus stored food, wrapped in a coat."],
  "g5-sci-plants-b-q22": ["Most seeds need water, air, and a suitable temperature to germinate."],
  "g5-sci-plants-b-q23": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-plants-b-q24": ["Ask how the fruit or seed travels: wind, water, animals, or explosion."],
  "g5-sci-space-a-q01": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-a-q02": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q03": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q04": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-a-q05": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q06": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q07": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q08": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q09": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q10": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q11": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-a-q12": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-a-q13": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q14": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q15": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q16": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q17": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q18": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-a-q19": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q20": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-a-q21": ["Earth's year is one orbit of the Sun; tilt helps make seasons."],
  "g5-sci-space-a-q22": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-a-q23": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-a-q24": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-b-q01": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-b-q02": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q03": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q04": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q05": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-b-q06": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-b-q07": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q08": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q09": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-b-q10": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q11": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-b-q12": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q13": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q14": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q15": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q16": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q17": ["Earth spinning on its axis causes day and night."],
  "g5-sci-space-b-q18": ["Link the clue to Sun, Earth, Moon, or planets."],
  "g5-sci-space-b-q19": ["Stars make their own light; planets reflect sunlight."],
  "g5-sci-space-b-q20": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q21": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-space-b-q22": ["Use the Sun–Earth–Moon figure; match positions to the event asked."],
  "g5-sci-space-b-q23": ["Use solar-system order or the planet property in the clue."],
  "g5-sci-space-b-q24": ["Phases depend on how much of the Moon's lit side we see from Earth."],
  "g5-sci-matter-a-q01": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-a-q02": ["Metals usually conduct heat and electricity; wood, plastic and rubber usually do not."],
  "g5-sci-matter-a-q03": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-a-q04": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-a-q05": ["A mixture keeps each part's properties; dissolving sugar in water is still a mixture."],
  "g5-sci-matter-a-q06": ["A mixture keeps each part's properties; dissolving sugar in water is still a mixture."],
  "g5-sci-matter-a-q07": ["Metals usually conduct heat and electricity; wood, plastic and rubber usually do not."],
  "g5-sci-matter-a-q08": ["Compare density with water: denser objects sink; less dense ones float."],
  "g5-sci-matter-a-q09": ["Choose the material whose property fits the job."],
  "g5-sci-matter-a-q10": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-a-q11": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-a-q12": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-a-q13": ["Melting, freezing, evaporation and condensation are changes of state."],
  "g5-sci-matter-a-q14": ["Melting, freezing, evaporation and condensation are changes of state."],
  "g5-sci-matter-a-q15": ["Ask whether you can get the starting material back easily (reversible) or not."],
  "g5-sci-matter-a-q16": ["Choose the material whose property fits the job."],
  "g5-sci-matter-a-q17": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-a-q18": ["Metals usually conduct heat and electricity; wood, plastic and rubber usually do not."],
  "g5-sci-matter-a-q19": ["A mixture keeps each part's properties; dissolving sugar in water is still a mixture."],
  "g5-sci-matter-a-q20": ["Choose the material whose property fits the job."],
  "g5-sci-matter-a-q21": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-a-q22": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-a-q23": ["Melting, freezing, evaporation and condensation are changes of state."],
  "g5-sci-matter-a-q24": ["Metals usually conduct heat and electricity; wood, plastic and rubber usually do not."],
  "g5-sci-matter-b-q01": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-b-q02": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-b-q03": ["Metals usually conduct heat and electricity; wood, plastic and rubber usually do not."],
  "g5-sci-matter-b-q04": ["Compare density with water: denser objects sink; less dense ones float."],
  "g5-sci-matter-b-q05": ["Ask whether you can get the starting material back easily (reversible) or not."],
  "g5-sci-matter-b-q06": ["Metals usually conduct heat and electricity; wood, plastic and rubber usually do not."],
  "g5-sci-matter-b-q07": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-b-q08": ["Melting, freezing, evaporation and condensation are changes of state."],
  "g5-sci-matter-b-q09": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-b-q10": ["Choose the material whose property fits the job."],
  "g5-sci-matter-b-q11": ["Ask whether you can get the starting material back easily (reversible) or not."],
  "g5-sci-matter-b-q12": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-b-q13": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-b-q14": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-b-q15": ["Compare density with water: denser objects sink; less dense ones float."],
  "g5-sci-matter-b-q16": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-b-q17": ["Choose the material whose property fits the job."],
  "g5-sci-matter-b-q18": ["Melting, freezing, evaporation and condensation are changes of state."],
  "g5-sci-matter-b-q19": ["Metals usually conduct heat and electricity; wood, plastic and rubber usually do not."],
  "g5-sci-matter-b-q20": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-matter-b-q21": ["Match the material to the property asked (hard, flexible, transparent, soluble)."],
  "g5-sci-matter-b-q22": ["A mixture keeps each part's properties; dissolving sugar in water is still a mixture."],
  "g5-sci-matter-b-q23": ["Choose the material whose property fits the job."],
  "g5-sci-matter-b-q24": ["Name the separation method: sieving, filtration, sedimentation, evaporation, or magnet."],
  "g5-sci-force-a-q01": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-a-q02": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-a-q03": ["Gravity pulls objects toward Earth; magnets can pull some metals without touching."],
  "g5-sci-force-a-q04": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-a-q05": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-a-q06": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-a-q07": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-a-q08": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-a-q09": ["A fixed pulley mainly changes the direction of your pull (pull down to lift up)."],
  "g5-sci-force-a-q10": ["An inclined plane (ramp) lets you use a smaller force over a longer distance."],
  "g5-sci-force-a-q11": ["Gravity pulls objects toward Earth; magnets can pull some metals without touching."],
  "g5-sci-force-a-q12": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-a-q13": ["Simple machines help us use force more easily: lever, pulley, ramp, wheel, screw, wedge."],
  "g5-sci-force-a-q14": ["Simple machines help us use force more easily: lever, pulley, ramp, wheel, screw, wedge."],
  "g5-sci-force-a-q15": ["A wheel and axle reduce friction so loads roll instead of scrape."],
  "g5-sci-force-a-q16": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-a-q17": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-a-q18": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-a-q19": ["An inclined plane (ramp) lets you use a smaller force over a longer distance."],
  "g5-sci-force-a-q20": ["A wheel and axle reduce friction so loads roll instead of scrape."],
  "g5-sci-force-a-q21": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-a-q22": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-a-q23": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-a-q24": ["Simple machines help us use force more easily: lever, pulley, ramp, wheel, screw, wedge."],
  "g5-sci-force-b-q01": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-b-q02": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-b-q03": ["Gravity pulls objects toward Earth; magnets can pull some metals without touching."],
  "g5-sci-force-b-q04": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-b-q05": ["A fixed pulley mainly changes the direction of your pull (pull down to lift up)."],
  "g5-sci-force-b-q06": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-b-q07": ["Simple machines help us use force more easily: lever, pulley, ramp, wheel, screw, wedge."],
  "g5-sci-force-b-q08": ["An inclined plane (ramp) lets you use a smaller force over a longer distance."],
  "g5-sci-force-b-q09": ["A wheel and axle reduce friction so loads roll instead of scrape."],
  "g5-sci-force-b-q10": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-b-q11": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-b-q12": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-b-q13": ["A wheel and axle reduce friction so loads roll instead of scrape."],
  "g5-sci-force-b-q14": ["An inclined plane (ramp) lets you use a smaller force over a longer distance."],
  "g5-sci-force-b-q15": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-b-q16": ["Simple machines help us use force more easily: lever, pulley, ramp, wheel, screw, wedge."],
  "g5-sci-force-b-q17": ["A force is a push or a pull; it can start, stop, speed up, slow, turn, or reshape."],
  "g5-sci-force-b-q18": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-b-q19": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-force-b-q20": ["Simple machines help us use force more easily: lever, pulley, ramp, wheel, screw, wedge."],
  "g5-sci-force-b-q21": ["Gravity pulls objects toward Earth; magnets can pull some metals without touching."],
  "g5-sci-force-b-q22": ["A fixed pulley mainly changes the direction of your pull (pull down to lift up)."],
  "g5-sci-force-b-q23": ["A lever has a fulcrum, load and effort \u2014 think see-saw, crowbar, scissors."],
  "g5-sci-force-b-q24": ["Friction opposes sliding; rough surfaces mean more friction; useful for grip, not for free sliding."],
  "g5-sci-env-a-q01": ["Natural resources come from nature: air, water, soil, forests, minerals, fuels."],
  "g5-sci-env-a-q02": ["Renewable resources can be replaced in a human lifetime; non-renewable take millions of years."],
  "g5-sci-env-a-q03": ["Forests give oxygen, homes for wildlife, soil hold, and rain help \u2014 cutting too many harms us."],
  "g5-sci-env-a-q04": ["Conserve by using wisely: reduce, reuse, recycle; save water and electricity; plant trees."],
  "g5-sci-env-a-q05": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-a-q06": ["Soil, water and air support life; protect them from waste and overuse."],
  "g5-sci-env-a-q07": ["Renewable resources can be replaced in a human lifetime; non-renewable take millions of years."],
  "g5-sci-env-a-q08": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-a-q09": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-a-q10": ["Forests give oxygen, homes for wildlife, soil hold, and rain help \u2014 cutting too many harms us."],
  "g5-sci-env-a-q11": ["Sun, wind and flowing water are cleaner renewables; coal and petroleum are fossil fuels."],
  "g5-sci-env-a-q12": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-a-q13": ["Renewable resources can be replaced in a human lifetime; non-renewable take millions of years."],
  "g5-sci-env-a-q14": ["Forests give oxygen, homes for wildlife, soil hold, and rain help \u2014 cutting too many harms us."],
  "g5-sci-env-a-q15": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-a-q16": ["Soil, water and air support life; protect them from waste and overuse."],
  "g5-sci-env-a-q17": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-a-q18": ["Sun, wind and flowing water are cleaner renewables; coal and petroleum are fossil fuels."],
  "g5-sci-env-a-q19": ["Forests give oxygen, homes for wildlife, soil hold, and rain help \u2014 cutting too many harms us."],
  "g5-sci-env-a-q20": ["Conserve by using wisely: reduce, reuse, recycle; save water and electricity; plant trees."],
  "g5-sci-env-a-q21": ["Sun, wind and flowing water are cleaner renewables; coal and petroleum are fossil fuels."],
  "g5-sci-env-a-q22": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-a-q23": ["Soil, water and air support life; protect them from waste and overuse."],
  "g5-sci-env-a-q24": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-b-q01": ["Natural resources come from nature: air, water, soil, forests, minerals, fuels."],
  "g5-sci-env-b-q02": ["Sun, wind and flowing water are cleaner renewables; coal and petroleum are fossil fuels."],
  "g5-sci-env-b-q03": ["Conserve by using wisely: reduce, reuse, recycle; save water and electricity; plant trees."],
  "g5-sci-env-b-q04": ["Renewable resources can be replaced in a human lifetime; non-renewable take millions of years."],
  "g5-sci-env-b-q05": ["Conserve by using wisely: reduce, reuse, recycle; save water and electricity; plant trees."],
  "g5-sci-env-b-q06": ["Forests give oxygen, homes for wildlife, soil hold, and rain help \u2014 cutting too many harms us."],
  "g5-sci-env-b-q07": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-b-q08": ["Renewable resources can be replaced in a human lifetime; non-renewable take millions of years."],
  "g5-sci-env-b-q09": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-b-q10": ["Renewable resources can be replaced in a human lifetime; non-renewable take millions of years."],
  "g5-sci-env-b-q11": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-b-q12": ["Soil, water and air support life; protect them from waste and overuse."],
  "g5-sci-env-b-q13": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-b-q14": ["Conserve by using wisely: reduce, reuse, recycle; save water and electricity; plant trees."],
  "g5-sci-env-b-q15": ["Natural resources come from nature: air, water, soil, forests, minerals, fuels."],
  "g5-sci-env-b-q16": ["Forests give oxygen, homes for wildlife, soil hold, and rain help \u2014 cutting too many harms us."],
  "g5-sci-env-b-q17": ["Sun, wind and flowing water are cleaner renewables; coal and petroleum are fossil fuels."],
  "g5-sci-env-b-q18": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-b-q19": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-b-q20": ["Forests give oxygen, homes for wildlife, soil hold, and rain help \u2014 cutting too many harms us."],
  "g5-sci-env-b-q21": ["Sun, wind and flowing water are cleaner renewables; coal and petroleum are fossil fuels."],
  "g5-sci-env-b-q22": ["Pollution is harmful waste in air, water, soil or as noise \u2014 link source to type."],
  "g5-sci-env-b-q23": ["Reduce = use less; reuse = use again; recycle = remake into new products."],
  "g5-sci-env-b-q24": ["Conserve by using wisely: reduce, reuse, recycle; save water and electricity; plant trees."],
};
