import type { HintOverlay } from "./types";

/** Grade 6 English item-specific hints (overlay) */
export const G6_ENGLISH_HINTS: Record<string, HintOverlay> = {
  // Reading Comprehension
  "g6-eng-comp-a-q01": ["Find the place named in the opening sentence."],
  "g6-eng-comp-a-q02": ["Match Kabir to the type of reading mentioned."],
  "g6-eng-comp-a-q03": ["Look for the librarian’s name."],
  "g6-eng-comp-a-q04": ["Find the sentence about Meera’s book."],
  "g6-eng-comp-a-q05": ["Locate the mangrove sentence."],
  "g6-eng-comp-a-q06": ["Find the promise at the end."],
  "g6-eng-comp-a-q07": ["Name the vendor in the passage."],
  "g6-eng-comp-a-q08": ["Find the description of how he works."],
  "g6-eng-comp-a-q09": ["Read Amma’s order carefully."],
  "g6-eng-comp-a-q10": ["Find the farm mention."],
  "g6-eng-comp-a-q11": ["Look for the rupee amount."],
  "g6-eng-comp-a-q12": ["Check the closing sentence."],
  "g6-eng-comp-a-q13": ["Find the meeting time."],
  "g6-eng-comp-a-q14": ["Match Ananya to her claim."],
  "g6-eng-comp-a-q15": ["Find Rohan’s point about plastic."],
  "g6-eng-comp-a-q16": ["Locate the teacher’s request."],
  "g6-eng-comp-a-q17": ["Find Ananya’s suggestion."],
  "g6-eng-comp-a-q18": ["Read the ending carefully."],
  "g6-eng-comp-a-q19": ["Find the monsoon detail."],
  "g6-eng-comp-a-q20": ["Locate the indoor practice sentence."],
  "g6-eng-comp-a-q21": ["Find Tuesday’s event."],
  "g6-eng-comp-a-q22": ["Look for Priya’s action after practice stopped."],
  "g6-eng-comp-a-q23": ["Find Priya’s message about patience."],
  "g6-eng-comp-a-q24": ["Read the final sentence."],
  "g6-eng-comp-b-q01": ["Check how Meera is introduced."],
  "g6-eng-comp-b-q02": ["Find who wrote the new books."],
  "g6-eng-comp-b-q03": ["Infer from what Mrs Rao does."],
  "g6-eng-comp-b-q04": ["Link mangroves to the main idea."],
  "g6-eng-comp-b-q05": ["What do people usually do at a library here?"],
  "g6-eng-comp-b-q06": ["Eliminate details that appear; find the outsider."],
  "g6-eng-comp-b-q07": ["Find the frequency."],
  "g6-eng-comp-b-q08": ["List the items in her order."],
  "g6-eng-comp-b-q09": ["Infer from his manner."],
  "g6-eng-comp-b-q10": ["Find the currency mark."],
  "g6-eng-comp-b-q11": ["Who receives Amma’s comment?"],
  "g6-eng-comp-b-q12": ["Focus on the final moral."],
  "g6-eng-comp-b-q13": ["Match speaker to idea."],
  "g6-eng-comp-b-q14": ["Find Rohan’s suggestion."],
  "g6-eng-comp-b-q15": ["Read his introduction."],
  "g6-eng-comp-b-q16": ["Find the reaction word."],
  "g6-eng-comp-b-q17": ["What theme links both stalls?"],
  "g6-eng-comp-b-q18": ["Check the teacher’s decision."],
  "g6-eng-comp-b-q19": ["Link weather to venue."],
  "g6-eng-comp-b-q20": ["Find the Tuesday cause."],
  "g6-eng-comp-b-q21": ["Who says it?"],
  "g6-eng-comp-b-q22": ["Read Wednesday’s action."],
  "g6-eng-comp-b-q23": ["Infer from her actions and words."],
  "g6-eng-comp-b-q24": ["Choose the title that covers the whole story."],
  // Grammar
  "g6-eng-gram-a-q01": ["Match singular subject to singular verb."],
  "g6-eng-gram-a-q02": ["Plural subject needs a plural verb."],
  "g6-eng-gram-a-q03": ["Which word names a person, place or thing?"],
  "g6-eng-gram-a-q04": ["Find the describing word."],
  "g6-eng-gram-a-q05": ["Use an before vowel sounds."],
  "g6-eng-gram-a-q06": ["Unique ranges usually need the."],
  "g6-eng-gram-a-q07": ["Irregular past of write."],
  "g6-eng-gram-a-q08": ["Would you say I are partners or me are partners?"],
  "g6-eng-gram-a-q09": ["Look for will + verb."],
  "g6-eng-gram-a-q10": ["Neither/either take singular verbs in school grammar."],
  "g6-eng-gram-a-q11": ["How did he speak?"],
  "g6-eng-gram-a-q12": ["Surface → on."],
  "g6-eng-gram-a-q13": ["Need a full subject + verb thought."],
  "g6-eng-gram-a-q14": ["Two items → comparative form."],
  "g6-eng-gram-a-q15": ["Superlative for the extreme."],
  "g6-eng-gram-a-q16": ["Backshift the tense after said."],
  "g6-eng-gram-a-q17": ["Which linker shows cause?"],
  "g6-eng-gram-a-q18": ["Who did the action?"],
  "g6-eng-gram-a-q19": ["Paired food as one unit."],
  "g6-eng-gram-a-q20": ["Word for a group acting as one."],
  "g6-eng-gram-a-q21": ["News takes a singular verb."],
  "g6-eng-gram-a-q22": ["Which word bursts with feeling?"],
  "g6-eng-gram-a-q23": ["Time word yesterday → past tense."],
  "g6-eng-gram-a-q24": ["Possessive pronouns: mine, yours, his, hers, ours, theirs."],
  "g6-eng-gram-b-q01": ["Plural subject → plural verb."],
  "g6-eng-gram-b-q02": ["Agree with the noun closest to the verb."],
  "g6-eng-gram-b-q03": ["Which word shows the action?"],
  "g6-eng-gram-b-q04": ["Listen for the vowel sound, not just the letter."],
  "g6-eng-gram-b-q05": ["Third form after has/have."],
  "g6-eng-gram-b-q06": ["Object pronoun after let."],
  "g6-eng-gram-b-q07": ["Look for be + -ing."],
  "g6-eng-gram-b-q08": ["Two people → between."],
  "g6-eng-gram-b-q09": ["Which word links choices?"],
  "g6-eng-gram-b-q10": ["Two-item comparison."],
  "g6-eng-gram-b-q11": ["Irregular plural + verb agreement."],
  "g6-eng-gram-b-q12": ["Questions ask; they often end with ?"],
  "g6-eng-gram-b-q13": ["Has/have + past participle."],
  "g6-eng-gram-b-q14": ["What was borrowed?"],
  "g6-eng-gram-b-q15": ["Uncountable nouns take much, not many."],
  "g6-eng-gram-b-q16": ["Imperatives tell someone to do something."],
  "g6-eng-gram-b-q17": ["People → who."],
  "g6-eng-gram-b-q18": ["Be + past participle for passive."],
  "g6-eng-gram-b-q19": ["Collective noun as a unit → singular."],
  "g6-eng-gram-b-q20": ["Which word names an idea you cannot touch?"],
  "g6-eng-gram-b-q21": ["If + present → will + base verb."],
  "g6-eng-gram-b-q22": ["Contrast linker."],
  "g6-eng-gram-b-q23": ["Subject–verb–object with adjective before noun."],
  "g6-eng-gram-b-q24": ["Exclamation mark + capital."],
  // Vocabulary
  "g6-eng-vocab-a-q01": ["Which word is closest in meaning to ancient?"],
  "g6-eng-vocab-a-q02": ["Opposite of brave."],
  "g6-eng-vocab-a-q03": ["Near meaning of assist."],
  "g6-eng-vocab-a-q04": ["Opposite of not-enough."],
  "g6-eng-vocab-a-q05": ["Use the storm context."],
  "g6-eng-vocab-a-q06": ["Seller word."],
  "g6-eng-vocab-a-q07": ["What does un- usually do?"],
  "g6-eng-vocab-a-q08": ["-ful ≈ full of."],
  "g6-eng-vocab-a-q09": ["Brief look word."],
  "g6-eng-vocab-a-q10": ["Opposite of giving freely."],
  "g6-eng-vocab-a-q11": ["See-through meaning."],
  "g6-eng-vocab-a-q12": ["Same sound, different spelling."],
  "g6-eng-vocab-a-q13": ["Start word."],
  "g6-eng-vocab-a-q14": ["Opposite of get bigger."],
  "g6-eng-vocab-a-q15": ["Context of traders."],
  "g6-eng-vocab-a-q16": ["Which word does not mean happy?"],
  "g6-eng-vocab-a-q17": ["Long-lasting materials."],
  "g6-eng-vocab-a-q18": ["Coming vs going."],
  "g6-eng-vocab-a-q19": ["Near meaning of cautious."],
  "g6-eng-vocab-a-q20": ["Figurative meaning, not literal ice."],
  "g6-eng-vocab-a-q21": ["Story lesson word."],
  "g6-eng-vocab-a-q22": ["Opposite of man-made."],
  "g6-eng-vocab-a-q23": ["Pleasant smell word."],
  "g6-eng-vocab-a-q24": ["Context of kitchen rubbish."],
  "g6-eng-vocab-b-q01": ["Near meaning of rapid."],
  "g6-eng-vocab-b-q02": ["Opposite of noisy."],
  "g6-eng-vocab-b-q03": ["Near meaning of tiny."],
  "g6-eng-vocab-b-q04": ["Opposite of winning."],
  "g6-eng-vocab-b-q05": ["Food context."],
  "g6-eng-vocab-b-q06": ["Protect synonym."],
  "g6-eng-vocab-b-q07": ["Again prefix."],
  "g6-eng-vocab-b-q08": ["-less ≈ without."],
  "g6-eng-vocab-b-q09": ["Buy word."],
  "g6-eng-vocab-b-q10": ["Opposite of include."],
  "g6-eng-vocab-b-q11": ["Farming context."],
  "g6-eng-vocab-b-q12": ["Same sound pair."],
  "g6-eng-vocab-b-q13": ["Near meaning of vanish."],
  "g6-eng-vocab-b-q14": ["Opposite of polite."],
  "g6-eng-vocab-b-q15": ["Yearly word."],
  "g6-eng-vocab-b-q16": ["Which is not big?"],
  "g6-eng-vocab-b-q17": ["Bendable meaning."],
  "g6-eng-vocab-b-q18": ["Opposite of lasting only a short time."],
  "g6-eng-vocab-b-q19": ["Near meaning of difficult."],
  "g6-eng-vocab-b-q20": ["Figurative ease."],
  "g6-eng-vocab-b-q21": ["Natural collocation for lights."],
  "g6-eng-vocab-b-q22": ["Opposite of public."],
  "g6-eng-vocab-b-q23": ["Near meaning of weary."],
  "g6-eng-vocab-b-q24": ["End-of-day light."],
};
