import type { HintOverlay } from "./types";

/** Grade 6 Maths item-specific hints (overlay) */
export const G6_MATHS_HINTS: Record<string, HintOverlay> = {
  // Integers
  "g6-maths-int-a-q01": ["Integers are …, −2, −1, 0, 1, 2, … — no fractions or decimals."],
  "g6-maths-int-a-q02": ["On a number line, left means smaller."],
  "g6-maths-int-a-q03": ["Additive inverse of a is the number that sums with a to 0."],
  "g6-maths-int-a-q04": ["Absolute value drops the sign — distance from zero."],
  "g6-maths-int-a-q05": ["Same signs: add the sizes and keep that sign."],
  "g6-maths-int-a-q06": ["Adding a negative is the same as subtracting."],
  "g6-maths-int-a-q07": ["Minus a negative becomes plus."],
  "g6-maths-int-a-q08": ["Different signs when multiplying → negative product."],
  "g6-maths-int-a-q09": ["Same signs when multiplying → positive product."],
  "g6-maths-int-a-q10": ["Different signs when dividing → negative quotient."],
  "g6-maths-int-a-q11": ["Natural ⊂ whole ⊂ integers — which way do the sets nest?"],
  "g6-maths-int-a-q12": ["Start at −2, then add the rise."],
  "g6-maths-int-a-q13": ["Negative floor plus upward moves."],
  "g6-maths-int-a-q14": ["Smallest (most left on the number line) comes first."],
  "g6-maths-int-a-q15": ["Add the three negatives."],
  "g6-maths-int-a-q16": ["For negatives, the one closer to zero is greater."],
  "g6-maths-int-a-q17": ["Subtracting a negative is adding."],
  "g6-maths-int-a-q18": ["Start with 200, subtract 350 — keep the sign for an overdrawn balance."],
  "g6-maths-int-a-q19": ["Compute inside first, then take absolute value."],
  "g6-maths-int-a-q20": ["Odd power of a negative stays negative."],
  "g6-maths-int-a-q21": ["Successor = add 1."],
  "g6-maths-int-a-q22": ["Predecessor = subtract 1."],
  "g6-maths-int-a-q23": ["Same signs when dividing → positive."],
  "g6-maths-int-a-q24": ["Which option really lands on −10?"],
  "g6-maths-int-b-q01": ["Scan for any non-whole number."],
  "g6-maths-int-b-q02": ["Distance is the absolute difference."],
  "g6-maths-int-b-q03": ["Two minuses cancel."],
  "g6-maths-int-b-q04": ["Different signs: subtract sizes, keep the sign of the larger."],
  "g6-maths-int-b-q05": ["Subtracting a larger number from a smaller gives a negative."],
  "g6-maths-int-b-q06": ["Subtracting a positive is adding a negative."],
  "g6-maths-int-b-q07": ["Count negatives: two negatives → overall positive."],
  "g6-maths-int-b-q08": ["Different signs → negative quotient."],
  "g6-maths-int-b-q09": ["Substitute, then add."],
  "g6-maths-int-b-q10": ["Minus a negative becomes plus."],
  "g6-maths-int-b-q11": ["Rising means add a positive to a negative depth."],
  "g6-maths-int-b-q12": ["Most negative = smallest."],
  "g6-maths-int-b-q13": ["Even count of negatives → positive."],
  "g6-maths-int-b-q14": ["What times −4 gives −36?"],
  "g6-maths-int-b-q15": ["Take absolute values first, then subtract."],
  "g6-maths-int-b-q16": ["Look for a number plus its additive inverse."],
  "g6-maths-int-b-q17": ["Add step by step left to right."],
  "g6-maths-int-b-q18": ["Combine the signed amounts with ₹."],
  "g6-maths-int-b-q19": ["Two −15s cancel the +30."],
  "g6-maths-int-b-q20": ["Same sum after swapping order."],
  "g6-maths-int-b-q21": ["A zero factor forces the product to zero."],
  "g6-maths-int-b-q22": ["What sits between −2 and 0 on the number line?"],
  "g6-maths-int-b-q23": ["Same signs → positive quotient."],
  "g6-maths-int-b-q24": ["Which identity always holds?"],
  // Fractions & Decimals
  "g6-maths-frac-a-q01": ["Same bottoms — add the tops."],
  "g6-maths-frac-a-q02": ["Subtract tops, then simplify."],
  "g6-maths-frac-a-q03": ["Multiply or divide top and bottom by the same number."],
  "g6-maths-frac-a-q04": ["Divide by 5, then multiply by 2."],
  "g6-maths-frac-a-q05": ["One digit after the decimal → denominator 10."],
  "g6-maths-frac-a-q06": ["Divide numerator by denominator."],
  "g6-maths-frac-a-q07": ["Line up decimal places and compare digit by digit."],
  "g6-maths-frac-a-q08": ["Align the decimal points, then add."],
  "g6-maths-frac-a-q09": ["Align decimals and subtract."],
  "g6-maths-frac-a-q10": ["Multiply as wholes, then count decimal places."],
  "g6-maths-frac-a-q11": ["Denominator 100 → two digits after the decimal."],
  "g6-maths-frac-a-q12": ["Common denominator, then add."],
  "g6-maths-frac-a-q13": ["Divide 7 by 20."],
  "g6-maths-frac-a-q14": ["Divide by the greatest common factor."],
  "g6-maths-frac-a-q15": ["2 × 4 = 8 and 0.5 × 4 = 2 → 10."],
  "g6-maths-frac-a-q16": ["Add the kilometres carefully."],
  "g6-maths-frac-a-q17": ["Proper means top < bottom."],
  "g6-maths-frac-a-q18": ["Whole × bottom + top, over the same bottom."],
  "g6-maths-frac-a-q19": ["Find one-eighth, then take three."],
  "g6-maths-frac-a-q20": ["Compare tenths, then hundredths."],
  "g6-maths-frac-a-q21": ["Subtract from 1.00."],
  "g6-maths-frac-a-q22": ["Convert the decimal to a fraction and simplify."],
  "g6-maths-frac-a-q23": ["Match forms, then add."],
  "g6-maths-frac-a-q24": ["Convert, then subtract."],
  "g6-maths-frac-b-q01": ["Common denominator of 3 and 6."],
  "g6-maths-frac-b-q02": ["Match denominators, then subtract."],
  "g6-maths-frac-b-q03": ["Cross-multiply or simplify both."],
  "g6-maths-frac-b-q04": ["Quarter of 2.4, then triple it."],
  "g6-maths-frac-b-q05": ["Two decimal places → /100, then simplify."],
  "g6-maths-frac-b-q06": ["Divide; remainder over the denominator."],
  "g6-maths-frac-b-q07": ["Align decimal points."],
  "g6-maths-frac-b-q08": ["Write 6 as 6.00, then subtract."],
  "g6-maths-frac-b-q09": ["Multiply both by 10 to clear the decimal, then divide."],
  "g6-maths-frac-b-q10": ["Add rupees and paise carefully."],
  "g6-maths-frac-b-q11": ["Compare place by place after the decimal."],
  "g6-maths-frac-b-q12": ["One decimal place → /10, then simplify."],
  "g6-maths-frac-b-q13": ["Multiply tops, multiply bottoms, simplify."],
  "g6-maths-frac-b-q14": ["Fraction of the whole capacity."],
  "g6-maths-frac-b-q15": ["Look at the next digit to decide rounding."],
  "g6-maths-frac-b-q16": ["Convert 2/5 to a decimal first."],
  "g6-maths-frac-b-q17": ["Divide 3 by 8."],
  "g6-maths-frac-b-q18": ["Divide as usual; keep the decimal place."],
  "g6-maths-frac-b-q19": ["Remaining parts over total parts."],
  "g6-maths-frac-b-q20": ["Match forms, then subtract."],
  "g6-maths-frac-b-q21": ["Three decimal places → /1000, then simplify."],
  "g6-maths-frac-b-q22": ["Convert and compare."],
  "g6-maths-frac-b-q23": ["Divide total length by piece length."],
  "g6-maths-frac-b-q24": ["One-sixth of 18, then five of those."],
  // Basic Geometry
  "g6-maths-geo-a-q01": ["Ray = start point + endless direction."],
  "g6-maths-geo-a-q02": ["Segment = finite piece with two ends."],
  "g6-maths-geo-a-q03": ["Square corner = right angle = 90°."],
  "g6-maths-geo-a-q04": ["Compare with 90°."],
  "g6-maths-geo-a-q05": ["Bigger than right, smaller than straight."],
  "g6-maths-geo-a-q06": ["Flat line angle = 180°."],
  "g6-maths-geo-a-q07": ["Tri- means three."],
  "g6-maths-geo-a-q08": ["Triangle angle sum is a half-turn."],
  "g6-maths-geo-a-q09": ["Count the sides of a four-sided polygon."],
  "g6-maths-geo-a-q10": ["Equal sides + right angles → square."],
  "g6-maths-geo-a-q11": ["Like railway tracks."],
  "g6-maths-geo-a-q12": ["⊥ means 90°."],
  "g6-maths-geo-a-q13": ["Half a diameter is a radius."],
  "g6-maths-geo-a-q14": ["Diameter is twice the radius."],
  "g6-maths-geo-a-q15": ["Which tool has a degree scale?"],
  "g6-maths-geo-a-q16": ["Straight sides + closed = polygon."],
  "g6-maths-geo-a-q17": ["Use triangle sum 180°."],
  "g6-maths-geo-a-q18": ["Every angle must be less than 90°."],
  "g6-maths-geo-a-q19": ["Add length and breadth, then double."],
  "g6-maths-geo-a-q20": ["Square area = side squared."],
  "g6-maths-geo-a-q21": ["Inside means distance from centre < radius."],
  "g6-maths-geo-a-q22": ["Complement → 90°; supplement → 180°."],
  "g6-maths-geo-a-q23": ["Supplement → straight angle."],
  "g6-maths-geo-a-q24": ["Centre-cutting chord = diameter."],
  "g6-maths-geo-b-q01": ["Line vs ray vs segment."],
  "g6-maths-geo-b-q02": ["Flat half-turn."],
  "g6-maths-geo-b-q03": ["Bigger than a straight angle."],
  "g6-maths-geo-b-q04": ["Join opposite corners — how many ways?"],
  "g6-maths-geo-b-q05": ["Equal sides name."],
  "g6-maths-geo-b-q06": ["Look for the 90° corner."],
  "g6-maths-geo-b-q07": ["Regular hexagon: six equal sides."],
  "g6-maths-geo-b-q08": ["Length times breadth."],
  "g6-maths-geo-b-q09": ["Half the diameter."],
  "g6-maths-geo-b-q10": ["Can never-meeting lines also meet at 90°?"],
  "g6-maths-geo-b-q11": ["Subtract the two known angles from 180°."],
  "g6-maths-geo-b-q12": ["Four equal sides share the perimeter."],
  "g6-maths-geo-b-q13": ["Point + pencil arm."],
  "g6-maths-geo-b-q14": ["Count the corners of a die."],
  "g6-maths-geo-b-q15": ["12 edges, 8 vertices, 6 faces."],
  "g6-maths-geo-b-q16": ["Iso- = equal (sides)."],
  "g6-maths-geo-b-q17": ["Opposite angles at an X."],
  "g6-maths-geo-b-q18": ["Greek number prefixes."],
  "g6-maths-geo-b-q19": ["Inside vs boundary."],
  "g6-maths-geo-b-q20": ["Complementary sum to 90°."],
  "g6-maths-geo-b-q21": ["Supplementary sum to 180°."],
  "g6-maths-geo-b-q22": ["No equal sides."],
  "g6-maths-geo-b-q23": ["Through the centre = longest."],
  "g6-maths-geo-b-q24": ["Polygons need straight sides only."],
};
