import type { HintOverlay } from "./types";

/** Grade 6 Science item-specific hints (overlay) */
export const G6_SCIENCE_HINTS: Record<string, HintOverlay> = {
  // Food & Nutrition
  "g6-sci-food-a-q01": ["Energy nutrient group."],
  "g6-sci-food-a-q02": ["Body-building nutrient."],
  "g6-sci-food-a-q03": ["Fibre foods."],
  "g6-sci-food-a-q04": ["Link vitamin C to its deficiency disease."],
  "g6-sci-food-a-q05": ["Iodine → thyroid."],
  "g6-sci-food-a-q06": ["Eyes and vitamin A."],
  "g6-sci-food-a-q07": ["Sunshine vitamin."],
  "g6-sci-food-a-q08": ["All groups, right amounts."],
  "g6-sci-food-a-q09": ["Protein-rich foods."],
  "g6-sci-food-a-q10": ["Risk of excess fat."],
  "g6-sci-food-a-q11": ["Iron → blood."],
  "g6-sci-food-a-q12": ["Look for mixed nutrient groups."],
  "g6-sci-food-a-q13": ["Jobs of water."],
  "g6-sci-food-a-q14": ["Night vision vitamin."],
  "g6-sci-food-a-q15": ["Bone-softening deficiency."],
  "g6-sci-food-a-q16": ["Protective = vitamins/minerals rich."],
  "g6-sci-food-a-q17": ["Energy in vs energy out."],
  "g6-sci-food-a-q18": ["Vitamin C foods."],
  "g6-sci-food-a-q19": ["Nutrients in milk."],
  "g6-sci-food-a-q20": ["Job of fibre."],
  "g6-sci-food-a-q21": ["Safe food habit."],
  "g6-sci-food-a-q22": ["B1 deficiency disease."],
  "g6-sci-food-a-q23": ["Anaemia and iron."],
  "g6-sci-food-a-q24": ["Why add iodine to salt?"],
  "g6-sci-food-b-q01": ["Plant storage form."],
  "g6-sci-food-b-q02": ["Veg protein."],
  "g6-sci-food-b-q03": ["D and bones."],
  "g6-sci-food-b-q04": ["Which item is not food chemistry?"],
  "g6-sci-food-b-q05": ["Fat foods."],
  "g6-sci-food-b-q06": ["Scurvy signs."],
  "g6-sci-food-b-q07": ["Why variety matters."],
  "g6-sci-food-b-q08": ["Greens’ gifts."],
  "g6-sci-food-b-q09": ["Daily drink choice."],
  "g6-sci-food-b-q10": ["Calcium’s job."],
  "g6-sci-food-b-q11": ["Energy examples."],
  "g6-sci-food-b-q12": ["What’s wrong with excess junk food?"],
  "g6-sci-food-b-q13": ["Heat-sensitive vitamin."],
  "g6-sci-food-b-q14": ["Egg nutrient."],
  "g6-sci-food-b-q15": ["Outdoor light and vitamins."],
  "g6-sci-food-b-q16": ["Balance about fats."],
  "g6-sci-food-b-q17": ["Where is the thyroid?"],
  "g6-sci-food-b-q18": ["Pair energy + protein."],
  "g6-sci-food-b-q19": ["What ORS restores."],
  "g6-sci-food-b-q20": ["Disease from missing nutrient."],
  "g6-sci-food-b-q21": ["Why millets help."],
  "g6-sci-food-b-q22": ["Low protein effect."],
  "g6-sci-food-b-q23": ["Food safety habit."],
  "g6-sci-food-b-q24": ["Picture a complete plate."],
  // Fibre to Fabric
  "g6-sci-fibre-a-q01": ["Plant source of cotton."],
  "g6-sci-fibre-a-q02": ["Animal fibre for woollens."],
  "g6-sci-fibre-a-q03": ["Who makes silk?"],
  "g6-sci-fibre-a-q04": ["Jute plant part."],
  "g6-sci-fibre-a-q05": ["Natural vs synthetic."],
  "g6-sci-fibre-a-q06": ["Factory-made fibre."],
  "g6-sci-fibre-a-q07": ["Fibre → yarn step."],
  "g6-sci-fibre-a-q08": ["Weaving tool."],
  "g6-sci-fibre-a-q09": ["Loops vs interlacing."],
  "g6-sci-fibre-a-q10": ["Cotton growing conditions."],
  "g6-sci-fibre-a-q11": ["Cotton seed removal name."],
  "g6-sci-fibre-a-q12": ["Wool harvest step."],
  "g6-sci-fibre-a-q13": ["Silk farming word."],
  "g6-sci-fibre-a-q14": ["Define yarn."],
  "g6-sci-fibre-a-q15": ["Summer fabric choice."],
  "g6-sci-fibre-a-q16": ["Jute products."],
  "g6-sci-fibre-a-q17": ["Two big fibre families."],
  "g6-sci-fibre-a-q18": ["Silk filament step."],
  "g6-sci-fibre-a-q19": ["Gandhian spinning wheel use."],
  "g6-sci-fibre-a-q20": ["Animal vs plant fibre."],
  "g6-sci-fibre-a-q21": ["Yarn → fabric methods."],
  "g6-sci-fibre-a-q22": ["Coconut fibre."],
  "g6-sci-fibre-a-q23": ["Why cotton feels cooler."],
  "g6-sci-fibre-a-q24": ["Origin of synthetics."],
  "g6-sci-fibre-b-q01": ["Order the three stages."],
  "g6-sci-fibre-b-q02": ["Cotton after ginning."],
  "g6-sci-fibre-b-q03": ["Known qualities of silk."],
  "g6-sci-fibre-b-q04": ["Synthetic drying property."],
  "g6-sci-fibre-b-q05": ["Animal fibre sources beyond sheep."],
  "g6-sci-fibre-b-q06": ["Jute processing soak."],
  "g6-sci-fibre-b-q07": ["Warm fabric."],
  "g6-sci-fibre-b-q08": ["What handloom means."],
  "g6-sci-fibre-b-q09": ["Plant source."],
  "g6-sci-fibre-b-q10": ["Burn test clue for cotton."],
  "g6-sci-fibre-b-q11": ["Burn test clue for wool."],
  "g6-sci-fibre-b-q12": ["Biodegradable angle."],
  "g6-sci-fibre-b-q13": ["Why twist yarn?"],
  "g6-sci-fibre-b-q14": ["Silk career word."],
  "g6-sci-fibre-b-q15": ["Medical cotton property."],
  "g6-sci-fibre-b-q16": ["First wool step."],
  "g6-sci-fibre-b-q17": ["What blend means."],
  "g6-sci-fibre-b-q18": ["Hand spinning tools."],
  "g6-sci-fibre-b-q19": ["Why edges fray."],
  "g6-sci-fibre-b-q20": ["Knitting property."],
  "g6-sci-fibre-b-q21": ["Cultural/history note at class level."],
  "g6-sci-fibre-b-q22": ["Spot the synthetic."],
  "g6-sci-fibre-b-q23": ["Care difference reason."],
  "g6-sci-fibre-b-q24": ["Smallest unit."],
  // Sorting Materials
  "g6-sci-sep-a-q01": ["When handpicking works."],
  "g6-sci-sep-a-q02": ["Grain harvest separation."],
  "g6-sci-sep-a-q03": ["Wind separation."],
  "g6-sci-sep-a-q04": ["Sieve property."],
  "g6-sci-sep-a-q05": ["Settling down."],
  "g6-sci-sep-a-q06": ["Pour after settling."],
  "g6-sci-sep-a-q07": ["Filter job."],
  "g6-sci-sep-a-q08": ["Sun/heat on solutions."],
  "g6-sci-sep-a-q09": ["Salt pans method."],
  "g6-sci-sep-a-q10": ["Magnetic property use."],
  "g6-sci-sep-a-q11": ["Need undissolved solid for filtration."],
  "g6-sci-sep-a-q12": ["Spin separation for milk."],
  "g6-sci-sep-a-q13": ["Weight difference."],
  "g6-sci-sep-a-q14": ["Muddy water cleanup."],
  "g6-sci-sep-a-q15": ["Kitchen filtration."],
  "g6-sci-sep-a-q16": ["Method for mixed liquids."],
  "g6-sci-sep-a-q17": ["Immiscible layers."],
  "g6-sci-sep-a-q18": ["Pure vs mixture."],
  "g6-sci-sep-a-q19": ["Air composition type."],
  "g6-sci-sep-a-q20": ["Kitchen sieving."],
  "g6-sci-sep-a-q21": ["Magnetic junk separation."],
  "g6-sci-sep-a-q22": ["Opposite of evaporation."],
  "g6-sci-sep-a-q23": ["Purpose of separation."],
  "g6-sci-sep-a-q24": ["Spot the mixture."],
  "g6-sci-sep-b-q01": ["Name the clear top liquid."],
  "g6-sci-sep-b-q02": ["Residue vs filtrate."],
  "g6-sci-sep-b-q03": ["Heat-driven method."],
  "g6-sci-sep-b-q04": ["Farm method for husk."],
  "g6-sci-sep-b-q05": ["When magnets fail."],
  "g6-sci-sep-b-q06": ["Alum/loading idea."],
  "g6-sci-sep-b-q07": ["Spot the insoluble."],
  "g6-sci-sep-b-q08": ["Define saturated."],
  "g6-sci-sep-b-q09": ["Dairy separation."],
  "g6-sci-sep-b-q10": ["Best tool first."],
  "g6-sci-sep-b-q11": ["Recovering dissolved salt."],
  "g6-sci-sep-b-q12": ["Define filtrate."],
  "g6-sci-sep-b-q13": ["Density idea."],
  "g6-sci-sep-b-q14": ["Lab filtration gear."],
  "g6-sci-sep-b-q15": ["Ink travel method name."],
  "g6-sci-sep-b-q16": ["See distinct parts."],
  "g6-sci-sep-b-q17": ["Uniform mixture."],
  "g6-sci-sep-b-q18": ["Kitchen handpicking."],
  "g6-sci-sep-b-q19": ["Key property."],
  "g6-sci-sep-b-q20": ["Sun drying science."],
  "g6-sci-sep-b-q21": ["Mixtures vs compounds methods."],
  "g6-sci-sep-b-q22": ["Clarify muddy water steps."],
  "g6-sci-sep-b-q23": ["Size-based solids."],
  "g6-sci-sep-b-q24": ["What stays in the pan?"],
};
