import type { HintOverlay } from "./types";

/** Grade 7 English item-specific hints (overlay) */
export const G7_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g7-eng-reading-a-q01": ["Look for where the action happens."],
  "g7-eng-reading-a-q02": ["Connect the quote to the idea of patience."],
  "g7-eng-reading-a-q03": ["Choose the detail closest to her attitude."],
  "g7-eng-reading-a-q04": ["Use context around planting."],
  "g7-eng-reading-a-q05": ["Read the sequence of events."],
  "g7-eng-reading-a-q06": ["Identify the issue the volunteers address."],
  "g7-eng-reading-a-q07": ["Look for the practical solution."],
  "g7-eng-reading-a-q08": ["Find the outcome sentence."],
  "g7-eng-reading-a-q09": ["Use astronomy context."],
  "g7-eng-reading-a-q10": ["Tone = attitude toward the topic."],
  "g7-eng-reading-a-q11": ["Match reason to group."],
  "g7-eng-reading-a-q12": ["Locate the children’s reason."],
  "g7-eng-reading-a-q13": ["Look at how she responds."],
  "g7-eng-reading-a-q14": ["Figurative language compares ideas."],
  "g7-eng-reading-a-q15": ["Compare the captain’s sayings."],
  "g7-eng-reading-a-q16": ["Inference must be grounded in the text."],
  "g7-eng-reading-a-q17": ["Find the actors in the solution."],
  "g7-eng-reading-a-q18": ["Focus on her steady actions."],
  "g7-eng-reading-a-q19": ["Ask what the detail contributes."],
  "g7-eng-reading-a-q20": ["Trace cause to effect in the passage."],
  "g7-eng-reading-a-q21": ["Locate the bridge relative to the ferry."],
  "g7-eng-reading-a-q22": ["Scan for the planting detail."],
  "g7-eng-reading-a-q23": ["Interpret the figurative ending."],
  "g7-eng-reading-a-q24": ["Theme should cover the whole passage."],
  "g7-eng-reading-b-q01": ["Mood = overall feeling."],
  "g7-eng-reading-b-q02": ["Track his actions and words."],
  "g7-eng-reading-b-q03": ["Find the cause in the same sentence."],
  "g7-eng-reading-b-q04": ["Link waste to direction of light."],
  "g7-eng-reading-b-q05": ["Find the wildlife effect."],
  "g7-eng-reading-b-q06": ["Look for the hopeful mechanism."],
  "g7-eng-reading-b-q07": ["Contrast with the ferry image."],
  "g7-eng-reading-b-q08": ["Time cue in the first sentence."],
  "g7-eng-reading-b-q09": ["Find a caring action."],
  "g7-eng-reading-b-q10": ["Opening sentence."],
  "g7-eng-reading-b-q11": ["Who can act on the advice?"],
  "g7-eng-reading-b-q12": ["Opinion vs fact."],
  "g7-eng-reading-b-q13": ["Read the closing sentence."],
  "g7-eng-reading-b-q14": ["Contrast old and new."],
  "g7-eng-reading-b-q15": ["Ask what the object is doing in the scene."],
  "g7-eng-reading-b-q16": ["Title should match the main idea."],
  "g7-eng-reading-b-q17": ["Locate the storytelling detail."],
  "g7-eng-reading-b-q18": ["Order the events."],
  "g7-eng-reading-b-q19": ["Find the time cue for results."],
  "g7-eng-reading-b-q20": ["Purpose = why the text exists."],
  "g7-eng-reading-b-q21": ["Figurative “pockets” = small areas."],
  "g7-eng-reading-b-q22": ["Who acts, and how?"],
  "g7-eng-reading-b-q23": ["Identify the main pair."],
  "g7-eng-reading-b-q24": ["Summary = main points only."],
  "g7-eng-grammar-a-q01": ["Match subject and verb."],
  "g7-eng-grammar-a-q02": ["Nouns name people, places, things, ideas."],
  "g7-eng-grammar-a-q03": ["Adjectives describe nouns."],
  "g7-eng-grammar-a-q04": ["Subject vs object pronoun."],
  "g7-eng-grammar-a-q05": ["Adverbs often end in -ly and modify verbs."],
  "g7-eng-grammar-a-q06": ["Use an before vowel sounds."],
  "g7-eng-grammar-a-q07": ["Time words cue tense."],
  "g7-eng-grammar-a-q08": ["Prepositions show relation (place/time)."],
  "g7-eng-grammar-a-q09": ["Check quote + question mark placement."],
  "g7-eng-grammar-a-q10": ["Cause–effect linker."],
  "g7-eng-grammar-a-q11": ["Neither/either take singular verbs."],
  "g7-eng-grammar-a-q12": ["Ask “wrote what?”"],
  "g7-eng-grammar-a-q13": ["One-syllable adjectives often take -er."],
  "g7-eng-grammar-a-q14": ["Complex = main + subordinate clause."],
  "g7-eng-grammar-a-q15": ["Possessive apostrophe."],
  "g7-eng-grammar-a-q16": ["Some nouns look plural but take singular verbs."],
  "g7-eng-grammar-a-q17": ["Interjections show emotion."],
  "g7-eng-grammar-a-q18": ["Each/every → singular verb."],
  "g7-eng-grammar-a-q19": ["Passive: be + past participle."],
  "g7-eng-grammar-a-q20": ["Who for people subjects."],
  "g7-eng-grammar-a-q21": ["Real future condition."],
  "g7-eng-grammar-a-q22": ["Find who/what does the verb."],
  "g7-eng-grammar-a-q23": ["f/fe often becomes ves."],
  "g7-eng-grammar-a-q24": ["Size before colour."],
  "g7-eng-grammar-b-q01": ["Agreement with the nearer subject."],
  "g7-eng-grammar-b-q02": ["Clauses answering when/why/how modify verbs."],
  "g7-eng-grammar-b-q03": ["Coordinating and in lists."],
  "g7-eng-grammar-b-q04": ["Gerund = -ing form as noun."],
  "g7-eng-grammar-b-q05": ["Imperative = request/command."],
  "g7-eng-grammar-b-q06": ["Collective noun as one unit."],
  "g7-eng-grammar-b-q07": ["Modals signal strength of need."],
  "g7-eng-grammar-b-q08": ["Object form after to/for."],
  "g7-eng-grammar-b-q09": ["Backshift tenses in reported speech."],
  "g7-eng-grammar-b-q10": ["Correlative conjunctions travel in pairs."],
  "g7-eng-grammar-b-q11": ["After a preposition use object pronouns."],
  "g7-eng-grammar-b-q12": ["Finite verbs show tense."],
  "g7-eng-grammar-b-q13": ["Use the with ranges and unique groups."],
  "g7-eng-grammar-b-q14": ["Tag mirrors auxiliary and polarity."],
  "g7-eng-grammar-b-q15": ["Compound = two mains linked."],
  "g7-eng-grammar-b-q16": ["One of + plural noun still takes singular verb."],
  "g7-eng-grammar-b-q17": ["Appositive renames a noun."],
  "g7-eng-grammar-b-q18": ["Some verbs/prepositions take -ing."],
  "g7-eng-grammar-b-q19": ["Avoid stacking negatives."],
  "g7-eng-grammar-b-q20": ["The + superlative."],
  "g7-eng-grammar-b-q21": ["Fixed preposition patterns."],
  "g7-eng-grammar-b-q22": ["Transitive verbs take objects."],
  "g7-eng-grammar-b-q23": ["Hardly pairs with when."],
  "g7-eng-grammar-b-q24": ["Agree with the head of the subject phrase."],
  "g7-eng-words-a-q01": ["Synonym ≈ similar meaning."],
  "g7-eng-words-a-q02": ["Antonym = opposite."],
  "g7-eng-words-a-q03": ["Think of seeing briefly."],
  "g7-eng-words-a-q04": ["Homophones sound the same."],
  "g7-eng-words-a-q05": ["Idioms are not literal."],
  "g7-eng-words-a-q06": ["Near meaning."],
  "g7-eng-words-a-q07": ["Opposite action."],
  "g7-eng-words-a-q08": ["Use sports fairness context."],
  "g7-eng-words-a-q09": ["Common negative prefix."],
  "g7-eng-words-a-q10": ["Suffix changes meaning."],
  "g7-eng-words-a-q11": ["Near synonym."],
  "g7-eng-words-a-q12": ["Character opposite."],
  "g7-eng-words-a-q13": ["Science-tinged vocab."],
  "g7-eng-words-a-q14": ["Common spelling trap."],
  "g7-eng-words-a-q15": ["Non-literal frequency."],
  "g7-eng-words-a-q16": ["Near meaning."],
  "g7-eng-words-a-q17": ["Time opposite."],
  "g7-eng-words-a-q18": ["Attitude word."],
  "g7-eng-words-a-q19": ["Greek root bio = life."],
  "g7-eng-words-a-q20": ["Fit the sentence."],
  "g7-eng-words-a-q21": ["Same sound, different spelling/meaning."],
  "g7-eng-words-a-q22": ["Near meaning."],
  "g7-eng-words-a-q23": ["Opposite."],
  "g7-eng-words-a-q24": ["Bene- often signals good."],
  "g7-eng-words-b-q01": ["Near meaning."],
  "g7-eng-words-b-q02": ["Outcome opposite."],
  "g7-eng-words-b-q03": ["Character vocab."],
  "g7-eng-words-b-q04": ["Non-literal accuracy."],
  "g7-eng-words-b-q05": ["Find the mismatch."],
  "g7-eng-words-b-q06": ["Prefix meaning."],
  "g7-eng-words-b-q07": ["Context of shortage."],
  "g7-eng-words-b-q08": ["Opposite of not see-through."],
  "g7-eng-words-b-q09": ["Common verb+noun pairs."],
  "g7-eng-words-b-q10": ["Near meaning."],
  "g7-eng-words-b-q11": ["Clarity vocab."],
  "g7-eng-words-b-q12": ["Motion opposite."],
  "g7-eng-words-b-q13": ["Greek therm = heat."],
  "g7-eng-words-b-q14": ["Expense idiom."],
  "g7-eng-words-b-q15": ["Near meaning."],
  "g7-eng-words-b-q16": ["Spelling + usage."],
  "g7-eng-words-b-q17": ["Genre opposite."],
  "g7-eng-words-b-q18": ["Attitude word."],
  "g7-eng-words-b-q19": ["Same pronunciation."],
  "g7-eng-words-b-q20": ["Near meaning."],
  "g7-eng-words-b-q21": ["Suffix -less."],
  "g7-eng-words-b-q22": ["Manners opposite."],
  "g7-eng-words-b-q23": ["Importance vocab."],
  "g7-eng-words-b-q24": ["Choose the noun form."],
};
