import type { HintOverlay } from "./types";

/** Grade 7 Maths item-specific hints (overlay) */
export const G7_MATHS_HINTS: Record<string, HintOverlay> = {
  "g7-maths-integers-a-q01": ["Integers are whole numbers and their negatives, including 0."],
  "g7-maths-integers-a-q02": ["Additive inverse means the number that sums with it to zero."],
  "g7-maths-integers-a-q03": ["On a number line, left means smaller."],
  "g7-maths-integers-a-q04": ["Same signs: add and keep the common sign."],
  "g7-maths-integers-a-q05": ["Adding a negative undoes some of the positive."],
  "g7-maths-integers-a-q06": ["Minus a negative becomes plus."],
  "g7-maths-integers-a-q07": ["Opposite signs multiply to a negative."],
  "g7-maths-integers-a-q08": ["Same signs (both negative) multiply to a positive."],
  "g7-maths-integers-a-q09": ["Division follows the same sign rules as multiplication."],
  "g7-maths-integers-a-q10": ["Same signs divide to a positive."],
  "g7-maths-integers-a-q11": ["Absolute value drops the sign."],
  "g7-maths-integers-a-q12": ["More negative means smaller."],
  "g7-maths-integers-a-q13": ["Down is negative; up is positive."],
  "g7-maths-integers-a-q14": ["Change = new value minus old value."],
  "g7-maths-integers-a-q15": ["Two negatives cancel."],
  "g7-maths-integers-a-q16": ["Subtracting a negative adds."],
  "g7-maths-integers-a-q17": ["Count negative factors: even count → positive."],
  "g7-maths-integers-a-q18": ["Odd powers of a negative stay negative."],
  "g7-maths-integers-a-q19": ["Successor is one more on the number line."],
  "g7-maths-integers-a-q20": ["Predecessor is one less."],
  "g7-maths-integers-a-q21": ["Opposites cancel to zero."],
  "g7-maths-integers-a-q22": ["Among negatives, larger absolute value is smaller."],
  "g7-maths-integers-a-q23": ["Debt is negative; deposits add."],
  "g7-maths-integers-a-q24": ["Work left to right with addition and subtraction."],
  "g7-maths-integers-b-q01": ["Closure means the result stays in the set."],
  "g7-maths-integers-b-q02": ["Commutative = order can swap."],
  "g7-maths-integers-b-q03": ["Identity leaves the number unchanged."],
  "g7-maths-integers-b-q04": ["Odd number of negative factors → negative product."],
  "g7-maths-integers-b-q05": ["What times −5 gives −20?"],
  "g7-maths-integers-b-q06": ["Distribute the minus across the bracket."],
  "g7-maths-integers-b-q07": ["Rising adds a positive change to a negative depth."],
  "g7-maths-integers-b-q08": ["Take absolute values first, then subtract."],
  "g7-maths-integers-b-q09": ["Identity for multiplication is 1."],
  "g7-maths-integers-b-q10": ["Change minus-negative to plus, then finish."],
  "g7-maths-integers-b-q11": ["Negative × positive = negative."],
  "g7-maths-integers-b-q12": ["Ascending means smallest to largest."],
  "g7-maths-integers-b-q13": ["Even count of negatives → positive."],
  "g7-maths-integers-b-q14": ["Combine negatives first, then add the positive."],
  "g7-maths-integers-b-q15": ["Subtract means add the opposite of b."],
  "g7-maths-integers-b-q16": ["Never divide by zero."],
  "g7-maths-integers-b-q17": ["Gain positive, loss negative."],
  "g7-maths-integers-b-q18": ["Multiply and divide left to right."],
  "g7-maths-integers-b-q19": ["Difference depends on which is larger."],
  "g7-maths-integers-b-q20": ["Distributive links × and +."],
  "g7-maths-integers-b-q21": ["Absolute value first, then apply the outer sign."],
  "g7-maths-integers-b-q22": ["List them carefully; exclude the endpoints."],
  "g7-maths-integers-b-q23": ["Multiplication before addition."],
  "g7-maths-integers-b-q24": ["Additive inverses sum to zero."],
  "g7-maths-equations-a-q01": ["Undo addition with subtraction on both sides."],
  "g7-maths-equations-a-q02": ["Undo subtraction by adding."],
  "g7-maths-equations-a-q03": ["Undo multiplication by dividing."],
  "g7-maths-equations-a-q04": ["Undo division by multiplying."],
  "g7-maths-equations-a-q05": ["Subtract 3 first, then divide by 2."],
  "g7-maths-equations-a-q06": ["Add 4, then divide by 5."],
  "g7-maths-equations-a-q07": ["Substitute each option if unsure."],
  "g7-maths-equations-a-q08": ["“Increased by” → +."],
  "g7-maths-equations-a-q09": ["Thrice → multiply by 3."],
  "g7-maths-equations-a-q10": ["Negating both sides flips the sign."],
  "g7-maths-equations-a-q11": ["Divide by 4, then add 1."],
  "g7-maths-equations-a-q12": ["Subtract 2, then multiply by 3."],
  "g7-maths-equations-a-q13": ["Write the equation, then isolate x."],
  "g7-maths-equations-a-q14": ["Move x or rearrange to isolate it."],
  "g7-maths-equations-a-q15": ["Plug x = 0 into each equation."],
  "g7-maths-equations-a-q16": ["Divide both sides by 6."],
  "g7-maths-equations-a-q17": ["Add 5, then multiply by 2."],
  "g7-maths-equations-a-q18": ["Add 12 to both sides."],
  "g7-maths-equations-a-q19": ["Combine like terms first."],
  "g7-maths-equations-a-q20": ["Simplify the left side first."],
  "g7-maths-equations-a-q21": ["Substitute the known value of x."],
  "g7-maths-equations-a-q22": ["If both sides match for every x, it is an identity."],
  "g7-maths-equations-a-q23": ["If you get a false statement, there is no solution."],
  "g7-maths-equations-a-q24": ["Spending subtracts from the total."],
  "g7-maths-equations-b-q01": ["Collect variable terms on one side, numbers on the other."],
  "g7-maths-equations-b-q02": ["Expand brackets, then collect like terms."],
  "g7-maths-equations-b-q03": ["Consecutive integers differ by 1."],
  "g7-maths-equations-b-q04": ["Clear denominators with a common multiple."],
  "g7-maths-equations-b-q05": ["Translate words carefully into an equation."],
  "g7-maths-equations-b-q06": ["Divide both sides by −2."],
  "g7-maths-equations-b-q07": ["Find x first, then evaluate the new expression."],
  "g7-maths-equations-b-q08": ["Subtract 8, then divide by −3."],
  "g7-maths-equations-b-q09": ["Perimeter of square = 4 × side."],
  "g7-maths-equations-b-q10": ["Multiply both sides by 3 first."],
  "g7-maths-equations-b-q11": ["Let Priya = p; Ravi = p + 5."],
  "g7-maths-equations-b-q12": ["Add x to both sides, then divide."],
  "g7-maths-equations-b-q13": ["Keep the balance equal."],
  "g7-maths-equations-b-q14": ["Dividing by one-half doubles the number."],
  "g7-maths-equations-b-q15": ["Let smaller = x; larger = x + 3."],
  "g7-maths-equations-b-q16": ["Subtract 7, then divide by 4."],
  "g7-maths-equations-b-q17": ["Translate phrase by phrase."],
  "g7-maths-equations-b-q18": ["Combine like terms first."],
  "g7-maths-equations-b-q19": ["Substitute and compare both sides."],
  "g7-maths-equations-b-q20": ["Divide by 3, then subtract 1."],
  "g7-maths-equations-b-q21": ["Translate “more than” carefully."],
  "g7-maths-equations-b-q22": ["Subtract x from both sides."],
  "g7-maths-equations-b-q23": ["Distribute the minus, then isolate x."],
  "g7-maths-equations-b-q24": ["Linear → degree one."],
  "g7-maths-angles-a-q01": ["Compare with 90°."],
  "g7-maths-angles-a-q02": ["Right angle = quarter turn."],
  "g7-maths-angles-a-q03": ["Obtuse is greater than a right angle but less than straight."],
  "g7-maths-angles-a-q04": ["Straight angle = half turn."],
  "g7-maths-angles-a-q05": ["Complement → right angle total."],
  "g7-maths-angles-a-q06": ["Supplement → straight angle total."],
  "g7-maths-angles-a-q07": ["Complement = 90° minus the angle."],
  "g7-maths-angles-a-q08": ["Supplement = 180° minus the angle."],
  "g7-maths-angles-a-q09": ["Vertical angles match."],
  "g7-maths-angles-a-q10": ["Linear pair → 180°."],
  "g7-maths-angles-a-q11": ["Opposite equals opposite."],
  "g7-maths-angles-a-q12": ["Linear pair sums to 180°."],
  "g7-maths-angles-a-q13": ["Full circle around a point."],
  "g7-maths-angles-a-q14": ["Triangle angles add to 180°."],
  "g7-maths-angles-a-q15": ["All three angles equal."],
  "g7-maths-angles-a-q16": ["Use the angle sum."],
  "g7-maths-angles-a-q17": ["Exterior = sum of the other two interiors."],
  "g7-maths-angles-a-q18": ["Same position at each intersection → equal."],
  "g7-maths-angles-a-q19": ["Z-shape angles match."],
  "g7-maths-angles-a-q20": ["Same-side interior → 180°."],
  "g7-maths-angles-a-q21": ["Co-interior angles are supplementary."],
  "g7-maths-angles-a-q22": ["Reflex is the larger turn."],
  "g7-maths-angles-a-q23": ["Parts of 90° in ratio 2:3."],
  "g7-maths-angles-a-q24": ["Complementary means sum 90°."],
  "g7-maths-angles-b-q01": ["Set vertically opposite angles equal."],
  "g7-maths-angles-b-q02": ["Let the angle be x; complement is x − 20."],
  "g7-maths-angles-b-q03": ["Equal supplements → each 90°."],
  "g7-maths-angles-b-q04": ["Exterior = sum of remote interiors."],
  "g7-maths-angles-b-q05": ["Matching positions are equal."],
  "g7-maths-angles-b-q06": ["Z-angles are equal."],
  "g7-maths-angles-b-q07": ["Parts of 180°."],
  "g7-maths-angles-b-q08": ["Angle sum would exceed or leave nothing."],
  "g7-maths-angles-b-q09": ["Linear pair → straight line."],
  "g7-maths-angles-b-q10": ["Angles around a point sum to 360°."],
  "g7-maths-angles-b-q11": ["Equal base angles share the remaining sum."],
  "g7-maths-angles-b-q12": ["Focus on the intersecting-lines fact."],
  "g7-maths-angles-b-q13": ["Corresponding angles equal when parallel."],
  "g7-maths-angles-b-q14": ["Bisector means cut into equal halves."],
  "g7-maths-angles-b-q15": ["Half of 90°."],
  "g7-maths-angles-b-q16": ["Co-interior angles sum to 180°."],
  "g7-maths-angles-b-q17": ["Named by its largest angle type."],
  "g7-maths-angles-b-q18": ["180 − 90 leaves 90° to share."],
  "g7-maths-angles-b-q19": ["Equal corresponding → parallel."],
  "g7-maths-angles-b-q20": ["Greater than 180° → reflex."],
  "g7-maths-angles-b-q21": ["Adjacent angles on intersecting lines form a linear pair."],
  "g7-maths-angles-b-q22": ["One full turn around the shape."],
  "g7-maths-angles-b-q23": ["Exterior equals sum of remote interiors."],
  "g7-maths-angles-b-q24": ["Complementary → combined right angle."],
};
