import type { HintOverlay } from "./types";

/** Grade 7 Science item-specific hints (overlay) */
export const G7_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g7-sci-nutrition-a-q01": ["Auto = self; troph = food."],
  "g7-sci-nutrition-a-q02": ["Photo = light."],
  "g7-sci-nutrition-a-q03": ["Raw materials of photosynthesis."],
  "g7-sci-nutrition-a-q04": ["By-product of photosynthesis."],
  "g7-sci-nutrition-a-q05": ["Green pigment name."],
  "g7-sci-nutrition-a-q06": ["Organelle for food-making."],
  "g7-sci-nutrition-a-q07": ["Hetero = other."],
  "g7-sci-nutrition-a-q08": ["Sapro = rotten/dead."],
  "g7-sci-nutrition-a-q09": ["Parasite lives on a host."],
  "g7-sci-nutrition-a-q10": ["Why eat insects?"],
  "g7-sci-nutrition-a-q11": ["Tiny pores on leaves."],
  "g7-sci-nutrition-a-q12": ["Diet type."],
  "g7-sci-nutrition-a-q13": ["Both plant and animal foods."],
  "g7-sci-nutrition-a-q14": ["Steps of animal nutrition."],
  "g7-sci-nutrition-a-q15": ["Where proteins meet acid/enzymes."],
  "g7-sci-nutrition-a-q16": ["Bile and fats."],
  "g7-sci-nutrition-a-q17": ["Structure–function in intestine."],
  "g7-sci-nutrition-a-q18": ["Nutrient roles."],
  "g7-sci-nutrition-a-q19": ["Mineral deficiency diseases."],
  "g7-sci-nutrition-a-q20": ["Vitamin–disease pairs."],
  "g7-sci-nutrition-a-q21": ["Base of the chain."],
  "g7-sci-nutrition-a-q22": ["Cud-chewing."],
  "g7-sci-nutrition-a-q23": ["How Amoeba feeds."],
  "g7-sci-nutrition-a-q24": ["Symbiosis = living together for mutual benefit."],
  "g7-sci-nutrition-b-q01": ["List photosynthesis inputs."],
  "g7-sci-nutrition-b-q02": ["Organelle name."],
  "g7-sci-nutrition-b-q03": ["Contrast with autotrophs."],
  "g7-sci-nutrition-b-q04": ["Nutrient gap in poor soils."],
  "g7-sci-nutrition-b-q05": ["Energy conversion."],
  "g7-sci-nutrition-b-q06": ["Classic starch test."],
  "g7-sci-nutrition-b-q07": ["Host–parasite relation."],
  "g7-sci-nutrition-b-q08": ["First enzyme action on starch."],
  "g7-sci-nutrition-b-q09": ["Absorption structures."],
  "g7-sci-nutrition-b-q10": ["End products of protein digestion."],
  "g7-sci-nutrition-b-q11": ["Lipid digestion products."],
  "g7-sci-nutrition-b-q12": ["Balanced diet components."],
  "g7-sci-nutrition-b-q13": ["Vitamin–disease link."],
  "g7-sci-nutrition-b-q14": ["Bone-related deficiency."],
  "g7-sci-nutrition-b-q15": ["Role of decomposers."],
  "g7-sci-nutrition-b-q16": ["Ingestion → digestion → absorption."],
  "g7-sci-nutrition-b-q17": ["Products vs reactants."],
  "g7-sci-nutrition-b-q18": ["Why plants look green."],
  "g7-sci-nutrition-b-q19": ["Chain vs web."],
  "g7-sci-nutrition-b-q20": ["Mouth enzyme substrate."],
  "g7-sci-nutrition-b-q21": ["Plant transport tissues."],
  "g7-sci-nutrition-b-q22": ["Xylem vs phloem."],
  "g7-sci-nutrition-b-q23": ["Fungi nutrition."],
  "g7-sci-nutrition-b-q24": ["Producer definition."],
  "g7-sci-heat-a-q01": ["Heat vs temperature basics."],
  "g7-sci-heat-a-q02": ["Definition of temperature."],
  "g7-sci-heat-a-q03": ["Units of temperature."],
  "g7-sci-heat-a-q04": ["Fixed points."],
  "g7-sci-heat-a-q05": ["Boiling point."],
  "g7-sci-heat-a-q06": ["Thermometer types."],
  "g7-sci-heat-a-q07": ["Modes of heat transfer."],
  "g7-sci-heat-a-q08": ["Fluids = liquids/gases."],
  "g7-sci-heat-a-q09": ["No medium needed."],
  "g7-sci-heat-a-q10": ["Conductors vs insulators."],
  "g7-sci-heat-a-q11": ["Why wooden handles."],
  "g7-sci-heat-a-q12": ["Land vs sea breeze."],
  "g7-sci-heat-a-q13": ["Day pattern."],
  "g7-sci-heat-a-q14": ["Surface colour and heat."],
  "g7-sci-heat-a-q15": ["Why silvered flasks."],
  "g7-sci-heat-a-q16": ["Thermos design."],
  "g7-sci-heat-a-q17": ["Latent heat idea."],
  "g7-sci-heat-a-q18": ["Why sweat cools."],
  "g7-sci-heat-a-q19": ["Expansion comparison."],
  "g7-sci-heat-a-q20": ["Real-life expansion."],
  "g7-sci-heat-a-q21": ["Thermometer feature."],
  "g7-sci-heat-a-q22": ["Direction of heat flow."],
  "g7-sci-heat-a-q23": ["Clothing and heat."],
  "g7-sci-heat-a-q24": ["Compare thermometer ranges."],
  "g7-sci-heat-b-q01": ["Compare materials."],
  "g7-sci-heat-b-q02": ["Everyday convection."],
  "g7-sci-heat-b-q03": ["Sensing fire heat."],
  "g7-sci-heat-b-q04": ["Insulating clothing."],
  "g7-sci-heat-b-q05": ["Breeze = fluid movement."],
  "g7-sci-heat-b-q06": ["Thermometer technology."],
  "g7-sci-heat-b-q07": ["Differential expansion."],
  "g7-sci-heat-b-q08": ["Boiling vs evaporation."],
  "g7-sci-heat-b-q09": ["Evaporation conditions."],
  "g7-sci-heat-b-q10": ["Factors affecting evaporation."],
  "g7-sci-heat-b-q11": ["How liquid thermometers work."],
  "g7-sci-heat-b-q12": ["Range limitation."],
  "g7-sci-heat-b-q13": ["Purpose of insulation."],
  "g7-sci-heat-b-q14": ["Sun to Earth."],
  "g7-sci-heat-b-q15": ["°C vs K intervals."],
  "g7-sci-heat-b-q16": ["Conversion."],
  "g7-sci-heat-b-q17": ["Colour and heating."],
  "g7-sci-heat-b-q18": ["Mass and temperature change."],
  "g7-sci-heat-b-q19": ["Cookware materials."],
  "g7-sci-heat-b-q20": ["Thermometer anatomy."],
  "g7-sci-heat-b-q21": ["Distinguish the terms."],
  "g7-sci-heat-b-q22": ["Density and rising fluid."],
  "g7-sci-heat-b-q23": ["Lab heat practice."],
  "g7-sci-heat-b-q24": ["Insulating materials."],
  "g7-sci-acids-a-q01": ["Property of acids."],
  "g7-sci-acids-a-q02": ["Property of bases."],
  "g7-sci-acids-a-q03": ["Litmus test."],
  "g7-sci-acids-a-q04": ["Litmus in alkali."],
  "g7-sci-acids-a-q05": ["Neutral behaviour."],
  "g7-sci-acids-a-q06": ["pH scale middle."],
  "g7-sci-acids-a-q07": ["pH of acids."],
  "g7-sci-acids-a-q08": ["pH of bases."],
  "g7-sci-acids-a-q09": ["Natural indicators."],
  "g7-sci-acids-a-q10": ["China rose colours."],
  "g7-sci-acids-a-q11": ["Common acid formulas."],
  "g7-sci-acids-a-q12": ["Acid formulas."],
  "g7-sci-acids-a-q13": ["Common bases."],
  "g7-sci-acids-a-q14": ["Neutralisation products."],
  "g7-sci-acids-a-q15": ["Everyday neutralisation."],
  "g7-sci-acids-a-q16": ["Acid–metal reaction."],
  "g7-sci-acids-a-q17": ["Limewater test."],
  "g7-sci-acids-a-q18": ["Household chemicals."],
  "g7-sci-acids-a-q19": ["Lime chemistry."],
  "g7-sci-acids-a-q20": ["Everyday salt."],
  "g7-sci-acids-a-q21": ["Acid properties."],
  "g7-sci-acids-a-q22": ["Alkali definition."],
  "g7-sci-acids-a-q23": ["Indicator colours."],
  "g7-sci-acids-a-q24": ["Phenolphthalein in alkali."],
  "g7-sci-acids-b-q01": ["Dental chemistry."],
  "g7-sci-acids-b-q02": ["Effluent treatment idea."],
  "g7-sci-acids-b-q03": ["Common base."],
  "g7-sci-acids-b-q04": ["Smell-based indicators."],
  "g7-sci-acids-b-q05": ["Neutralisation example."],
  "g7-sci-acids-b-q06": ["Methyl orange colours."],
  "g7-sci-acids-b-q07": ["Indicator in base."],
  "g7-sci-acids-b-q08": ["Acids in food."],
  "g7-sci-acids-b-q09": ["Household base."],
  "g7-sci-acids-b-q10": ["Carbonate test with acid."],
  "g7-sci-acids-b-q11": ["Water on pH scale."],
  "g7-sci-acids-b-q12": ["Read the pH scale."],
  "g7-sci-acids-b-q13": ["High pH."],
  "g7-sci-acids-b-q14": ["Ionic view of neutralisation."],
  "g7-sci-acids-b-q15": ["Useful salts."],
  "g7-sci-acids-b-q16": ["Important compounds."],
  "g7-sci-acids-b-q17": ["Spot the false property."],
  "g7-sci-acids-b-q18": ["Spot the false property."],
  "g7-sci-acids-b-q19": ["Why use universal indicator."],
  "g7-sci-acids-b-q20": ["Lab safety rule."],
  "g7-sci-acids-b-q21": ["Agriculture chemistry."],
  "g7-sci-acids-b-q22": ["Acidic ions."],
  "g7-sci-acids-b-q23": ["Basic ions."],
  "g7-sci-acids-b-q24": ["Classify the compounds."],
};
