import type { HintOverlay } from "./types";

/** Grade 8 English item-specific hints (overlay) */
export const G8_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g8-eng-ch01-a-q01": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-a-q02": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q04": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q06": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q08": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q09": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q10": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q11": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-a-q12": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q13": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q14": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q15": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q16": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q17": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q18": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q19": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q20": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q21": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q22": ["Listen for the same ending sound in the words."],
  "g8-eng-ch01-a-q23": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-a-q24": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q01": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q02": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q04": ["An adjective describes a noun — which word tells more about a thing?"],
  "g8-eng-ch01-b-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q06": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-b-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q08": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q09": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q10": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q11": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q12": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q13": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q14": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q15": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q16": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q17": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q18": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q19": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q20": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q21": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q22": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q23": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q24": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch02-a-q01": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q05": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q06": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q07": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q08": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q09": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q10": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q11": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q12": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q13": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q14": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q15": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g8-eng-ch02-a-q16": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q17": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q18": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q19": ["An adjective describes a noun — which word tells more about a thing?"],
  "g8-eng-ch02-a-q20": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q21": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q22": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q23": ["Pick the word closest in meaning; test it in the sentence."],
  "g8-eng-ch02-a-q24": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q01": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q05": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q06": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q07": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q08": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q09": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q10": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-b-q11": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-b-q12": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-b-q13": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch02-b-q14": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q15": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q16": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q17": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q18": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q19": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q20": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q21": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q22": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q23": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q24": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch03-a-q01": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q02": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q03": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q04": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q05": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q06": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q07": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q08": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q09": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q10": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q11": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-a-q12": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q13": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q14": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q15": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q16": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q17": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q18": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q19": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q20": ["An adjective describes a noun — which word tells more about a thing?"],
  "g8-eng-ch03-a-q21": ["An adjective describes a noun."],
  "g8-eng-ch03-a-q22": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q23": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q24": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q01": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q02": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q03": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q04": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q05": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q06": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q07": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q08": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q09": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-b-q10": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q11": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q12": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q13": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q14": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q15": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q16": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q17": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q18": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-b-q19": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q20": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-b-q21": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q22": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q23": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch03-b-q24": ["A verb shows an action or a state of being."],
  "g8-eng-ch04-a-q01": ["Find where Rohan names his debate side."],
  "g8-eng-ch04-a-q02": ["What job do Firstly / Secondly / Finally do for a listener?"],
  "g8-eng-ch04-a-q03": ["'On the other hand' usually introduces what kind of idea?"],
  "g8-eng-ch04-a-q04": ["Which line uses a softener like 'Would you mind if\u2026?'"],
  "g8-eng-ch04-a-q05": ["What does Rohan say judges notice about rebuttals?"],
  "g8-eng-ch04-a-q06": ["Compare corridor chat language with debate-hall language."],
  "g8-eng-ch04-a-q07": ["Treat 'get cracking' as an idiom \u2014 what does it urge people to do?"],
  "g8-eng-ch04-a-q08": ["Does 'Point taken' accept or reject advice?"],
  "g8-eng-ch04-a-q09": ["The motion is usually stated near the start of an opening speech."],
  "g8-eng-ch04-a-q10": ["Look for the words 'proposition' or 'opposition' in the speech."],
  "g8-eng-ch04-a-q11": ["'To sum up' appears when a speaker is wrapping up."],
  "g8-eng-ch04-a-q12": ["Find where the speaker names a critic's claim and answers it."],
  "g8-eng-ch04-a-q13": ["Link the one-hour idea to the concentration reason in the speech."],
  "g8-eng-ch04-a-q14": ["Does this speaker ask the house to support or oppose the motion?"],
  "g8-eng-ch04-a-q15": ["Which line challenges the proposition's case before adding new evidence?"],
  "g8-eng-ch04-a-q16": ["'Moreover' adds another reason \u2014 same side or opposite side?"],
  "g8-eng-ch04-a-q17": ["After rejecting a blanket cap, what alternative does the speaker offer?"],
  "g8-eng-ch04-a-q18": ["Is 'May I have your attention, please?' polite public speech or a rebuke?"],
  "g8-eng-ch04-a-q19": ["Who does the announcement invite by class?"],
  "g8-eng-ch04-a-q20": ["Find the deadline for giving names \u2014 not the workshop day."],
  "g8-eng-ch04-a-q21": ["Pick the reply that acknowledges a concern and still disagrees with reasons."],
  "g8-eng-ch04-a-q22": ["What do debate rules say about speaking while someone else holds the floor?"],
  "g8-eng-ch04-a-q23": ["Which opening uses formal address and a clear stance?"],
  "g8-eng-ch04-a-q24": ["Which marker signals contrast rather than sequence, example, or closing?"],
  "g8-eng-ch04-b-q01": ["Opposition argues against the motion \u2014 what will Anya stress?"],
  "g8-eng-ch04-b-q02": ["What exact question does Anya ask about Rohan's case?"],
  "g8-eng-ch04-b-q03": ["'May I suggest\u2026' softens advice into what kind of speech act?"],
  "g8-eng-ch04-b-q04": ["Register means matching tone \u2014 formal hall or casual chat?"],
  "g8-eng-ch04-b-q05": ["Which sequencing word opens the first reason?"],
  "g8-eng-ch04-b-q06": ["Besides study, which needs does the speaker list as not luxuries?"],
  "g8-eng-ch04-b-q07": ["What does 'I urge you to vote\u2026' ask the house to do?"],
  "g8-eng-ch04-b-q08": ["Compare P1's stance on the cap with P2's stance."],
  "g8-eng-ch04-b-q09": ["Which home-study contrast does the speaker use?"],
  "g8-eng-ch04-b-q10": ["'Instead' introduces an alternative \u2014 what is it?"],
  "g8-eng-ch04-b-q11": ["What two items must students bring?"],
  "g8-eng-ch04-b-q12": ["Name the room given in the announcement."],
  "g8-eng-ch04-b-q13": ["Look for question \u2192 answer \u2192 response, not overlapping speech."],
  "g8-eng-ch04-b-q14": ["Which reply names a concrete fix after hearing the feedback?"],
  "g8-eng-ch04-b-q15": ["In debate vocabulary, what is a 'motion'?"],
  "g8-eng-ch04-b-q16": ["Match Firstly to order and However to contrast."],
  "g8-eng-ch04-b-q17": ["Which line is packed with slang better suited to friends?"],
  "g8-eng-ch04-b-q18": ["Rohan lists three harms \u2014 what is the third?"],
  "g8-eng-ch04-b-q19": ["Which two subject areas does P2 name for extra practice?"],
  "g8-eng-ch04-b-q20": ["Choose the request that uses 'Could you please\u2026'"],
  "g8-eng-ch04-b-q21": ["What does the speaker claim about shorter, well-designed tasks?"],
  "g8-eng-ch04-b-q22": ["Which softener acknowledges the other person before disagreeing?"],
  "g8-eng-ch04-b-q23": ["A strong point needs more than insults \u2014 what else?"],
  "g8-eng-ch04-b-q24": ["What job does 'Thank you' do at the end of an announcement?"],
  "g8-eng-ch05-a-q01": ["Check the name and designation at the bottom of the notice."],
  "g8-eng-ch05-a-q02": ["Separate issue date, event date, and name-submission deadline."],
  "g8-eng-ch05-a-q03": ["Which detail answers when and where so a student can attend?"],
  "g8-eng-ch05-a-q04": ["Ask which lines give actionable rules \u2014 can any of A\u2013C be dropped?"],
  "g8-eng-ch05-a-q05": ["A good subject names purpose and topic before you open the mail."],
  "g8-eng-ch05-a-q06": ["Named salutation \u2192 which closing? Unnamed \u2192 which closing?"],
  "g8-eng-ch05-a-q07": ["Read the first paragraph for the exact favour requested."],
  "g8-eng-ch05-a-q08": ["Is the tone rude, jokey, angry, or polite and specific?"],
  "g8-eng-ch05-a-q09": ["In formal letters, sender's address comes before the date."],
  "g8-eng-ch05-a-q10": ["The salutation is Sir/Madam \u2014 which closing pairs with that?"],
  "g8-eng-ch05-a-q11": ["Use the subject line and body to name the writer's aim."],
  "g8-eng-ch05-a-q12": ["Where does the subject sit relative to the salutation?"],
  "g8-eng-ch05-a-q13": ["Heading names the piece; byline names the writer."],
  "g8-eng-ch05-a-q14": ["'By Meera Joseph\u2026' identifies the author \u2014 what is that called?"],
  "g8-eng-ch05-a-q15": ["What happened to the cricket pitch behind the canteen?"],
  "g8-eng-ch05-a-q16": ["Find the Student Council's proposed temporary fix."],
  "g8-eng-ch05-a-q17": ["Which closing sentence states an opinion, not just a fact?"],
  "g8-eng-ch05-a-q18": ["School boards use which short public format for event facts?"],
  "g8-eng-ch05-a-q19": ["Magazine opinion pieces use heading, byline and developed paragraphs."],
  "g8-eng-ch05-a-q20": ["Read the receiver's address block \u2014 who is it for?"],
  "g8-eng-ch05-a-q21": ["'Hey' and 'See ya' clash with which letter register?"],
  "g8-eng-ch05-a-q22": ["Which subject line gives the reader no purpose at all?"],
  "g8-eng-ch05-a-q23": ["Where does the word NOTICE usually sit in the layout?"],
  "g8-eng-ch05-a-q24": ["Dear Sir/Madam pairs with which complimentary close?"],
  "g8-eng-ch05-b-q01": ["Find the venue named in the notice."],
  "g8-eng-ch05-b-q02": ["How many participants may each House send?"],
  "g8-eng-ch05-b-q03": ["What prepared piece length must students bring?"],
  "g8-eng-ch05-b-q04": ["'Hereby informed' is typical of which tone?"],
  "g8-eng-ch05-b-q05": ["Check the To-field and the salutation together."],
  "g8-eng-ch05-b-q06": ["Find the promised return date \u2014 not the fair date."],
  "g8-eng-ch05-b-q07": ["Which sentence explains why the books are still needed?"],
  "g8-eng-ch05-b-q08": ["Copy the subject line's topic carefully."],
  "g8-eng-ch05-b-q09": ["What two actions does Aarav want from the paper/authorities path?"],
  "g8-eng-ch05-b-q10": ["Which detail is a specific recent incident, not vague anger?"],
  "g8-eng-ch05-b-q11": ["Recall standard formal-letter order from address to signature."],
  "g8-eng-ch05-b-q12": ["Where was the scrap of ground that held cricket?"],
  "g8-eng-ch05-b-q13": ["Link lost play space to crowded corridors."],
  "g8-eng-ch05-b-q14": ["Notices push brief facts; articles develop viewpoint \u2014 which is P2?"],
  "g8-eng-ch05-b-q15": ["Is the last line a close like 'Yours sincerely' or a concluding opinion?"],
  "g8-eng-ch05-b-q16": ["Public attention + official action \u2192 which formats help?"],
  "g8-eng-ch05-b-q17": ["Is E1 mainly entertaining, announcing, editorialising, or requesting?"],
  "g8-eng-ch05-b-q18": ["Pick the measured formal opening for a complaint letter."],
  "g8-eng-ch05-b-q19": ["Notices need a date and issuer details \u2014 what is missing otherwise?"],
  "g8-eng-ch05-b-q20": ["Named reader Ms. Iyer \u2192 faithfully or sincerely?"],
  "g8-eng-ch05-b-q21": ["Which genre commonly places 'By \u2026' under the title?"],
  "g8-eng-ch05-b-q22": ["Compare N1's job (inform/instruct) with P2's job (reflect/persuade)."],
  "g8-eng-ch05-b-q23": ["Complimentary close comes before the name \u2014 in which order?"],
  "g8-eng-ch05-b-q24": ["Dear Sir + Yours faithfully belong to which genre, not articles?"],
};
