import type { HintOverlay } from "./types";

/** Grade 8 English item-specific hints (overlay) */
export const G8_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g8-eng-ch01-a-q01": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-a-q02": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q04": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q06": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q08": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q09": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q10": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q11": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-a-q12": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q13": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q14": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q15": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q16": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q17": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q18": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-a-q19": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q20": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q21": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-a-q22": ["Listen for the same ending sound in the words."],
  "g8-eng-ch01-a-q23": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-a-q24": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q01": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q02": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q03": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q04": ["An adjective describes a noun — which word tells more about a thing?"],
  "g8-eng-ch01-b-q05": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q06": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch01-b-q07": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q08": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q09": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q10": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q11": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q12": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q13": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q14": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q15": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q16": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q17": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q18": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q19": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q20": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q21": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q22": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch01-b-q23": ["Reread the lines; use rhyme, repetition, or feeling as clues."],
  "g8-eng-ch01-b-q24": ["Find evidence in the passage; avoid options the text does not support."],
  "g8-eng-ch02-a-q01": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q05": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q06": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q07": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q08": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q09": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q10": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q11": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q12": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-a-q13": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q14": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q15": ["A pronoun stands in for a noun (he, she, it, they…)."],
  "g8-eng-ch02-a-q16": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-a-q17": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q18": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q19": ["An adjective describes a noun — which word tells more about a thing?"],
  "g8-eng-ch02-a-q20": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q21": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q22": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-a-q23": ["Pick the word closest in meaning; test it in the sentence."],
  "g8-eng-ch02-a-q24": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q01": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q02": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q03": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q04": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q05": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q06": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q07": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q08": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q09": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q10": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-b-q11": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-b-q12": ["A verb shows an action or a state of being."],
  "g8-eng-ch02-b-q13": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch02-b-q14": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q15": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q16": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q17": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q18": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q19": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q20": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q21": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch02-b-q22": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q23": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch02-b-q24": ["Name the grammar job or rule being tested in the sentence."],
  "g8-eng-ch03-a-q01": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q02": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q03": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q04": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q05": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q06": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q07": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q08": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q09": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q10": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q11": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-a-q12": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q13": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q14": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-a-q15": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q16": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q17": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q18": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q19": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q20": ["An adjective describes a noun — which word tells more about a thing?"],
  "g8-eng-ch03-a-q21": ["An adjective describes a noun."],
  "g8-eng-ch03-a-q22": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q23": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-a-q24": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q01": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q02": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q03": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q04": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q05": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q06": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q07": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q08": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q09": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-b-q10": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q11": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q12": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q13": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q14": ["A noun names a person, place, thing, or idea."],
  "g8-eng-ch03-b-q15": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q16": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q17": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q18": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-b-q19": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q20": ["Match the verb form to the time and the subject in the sentence."],
  "g8-eng-ch03-b-q21": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q22": ["Use word meaning, word parts, or context to decide."],
  "g8-eng-ch03-b-q23": ["Go back to the exact line in the passage that answers the question."],
  "g8-eng-ch03-b-q24": ["A verb shows an action or a state of being."],
};

