import type { HintOverlay } from "./types";

/** Grade 8 Maths item-specific hints (overlay) */
export const G8_MATHS_HINTS: Record<string, HintOverlay> = {
  "g8-maths-compare-a-q01": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q02": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q03": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-a-q04": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q05": ["Set up the comparison carefully; keep units consistent."],
  "g8-maths-compare-a-q06": ["Discount comes off the marked price."],
  "g8-maths-compare-a-q07": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q08": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q09": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q10": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q11": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q12": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q13": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q14": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q15": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q16": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-a-q17": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q18": ["Simple interest uses P × R × T / 100."],
  "g8-maths-compare-a-q19": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q20": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q21": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q22": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q23": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q24": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q01": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q02": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q03": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-b-q04": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q05": ["Set up the comparison carefully; keep units consistent."],
  "g8-maths-compare-b-q06": ["Discount comes off the marked price."],
  "g8-maths-compare-b-q07": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q08": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q09": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q10": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q11": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q12": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q13": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q14": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q15": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q16": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-b-q17": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q18": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q19": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q20": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q21": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q22": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q23": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q24": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-linear-a-q01": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q02": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q03": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q04": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q05": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q06": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q07": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q08": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q09": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q10": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q11": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q12": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q13": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q14": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q15": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q16": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q17": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q18": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q19": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q20": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q21": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q22": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q23": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q24": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q01": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q02": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q03": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q04": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q05": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q06": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q07": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q08": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q09": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q10": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q11": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q12": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q13": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q14": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q15": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q16": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q17": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q18": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q19": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q20": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q21": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q22": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q23": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q24": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-rational-a-q01": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q02": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q03": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-a-q04": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-a-q05": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q06": ["Same signs add; different signs subtract and keep the larger's sign."],
  "g8-maths-rational-a-q07": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q08": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q09": ["Positives right of 0, negatives left; equal jumps."],
  "g8-maths-rational-a-q10": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q11": ["On the number line, numbers to the right are greater."],
  "g8-maths-rational-a-q12": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q13": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q14": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q15": ["Subtracting is adding the opposite."],
  "g8-maths-rational-a-q16": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q17": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q18": ["Same signs add; different signs subtract and keep the larger's sign."],
  "g8-maths-rational-a-q19": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q20": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q21": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q22": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q23": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q24": ["Same signs → positive; different signs → negative."],
  "g8-maths-rational-b-q01": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q02": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q03": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-b-q04": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q05": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q06": ["Same signs → positive; different signs → negative."],
  "g8-maths-rational-b-q07": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-b-q08": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q09": ["Positives right of 0, negatives left; equal jumps."],
  "g8-maths-rational-b-q10": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q11": ["On the number line, numbers to the right are greater."],
  "g8-maths-rational-b-q12": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q13": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q14": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q15": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q16": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q17": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q18": ["Subtracting is adding the opposite."],
  "g8-maths-rational-b-q19": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q20": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q21": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q22": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q23": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q24": ["Same signs add; different signs subtract and keep the larger's sign."],
  "g8-maths-algebra-a-q01": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-a-q02": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-a-q03": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-a-q04": ["Combine like terms only; flip all signs when subtracting a bracket."],
  "g8-maths-algebra-a-q05": ["Combine like terms only; flip all signs when subtracting a bracket."],
  "g8-maths-algebra-a-q06": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-a-q07": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-a-q08": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-a-q09": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q10": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q11": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q12": ["Substitute the value, then simplify carefully."],
  "g8-maths-algebra-a-q13": ["Divide coefficients, then subtract exponents of matching variables."],
  "g8-maths-algebra-a-q14": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-a-q15": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-a-q16": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q17": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q18": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q19": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q20": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q21": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q22": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q23": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-a-q24": ["Combine like terms only; flip all signs when subtracting a bracket."],
  "g8-maths-algebra-b-q01": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-b-q02": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-b-q03": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-b-q04": ["Combine like terms only; flip all signs when subtracting a bracket."],
  "g8-maths-algebra-b-q05": ["Combine like terms only; flip all signs when subtracting a bracket."],
  "g8-maths-algebra-b-q06": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-b-q07": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-b-q08": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-b-q09": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q10": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q11": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q12": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q13": ["Divide coefficients, then subtract exponents of matching variables."],
  "g8-maths-algebra-b-q14": ["Distribute to every term, then combine like terms."],
  "g8-maths-algebra-b-q15": ["Count terms separated by + or \u2212; coefficients sit in front of variables."],
  "g8-maths-algebra-b-q16": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q17": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q18": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q19": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q20": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q21": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q22": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q23": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-algebra-b-q24": ["Use (a\u00b1b)\u00b2 or a\u00b2\u2212b\u00b2; expand or factor with the matching pattern."],
  "g8-maths-mensuration-a-q01": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q02": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q03": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q04": ["Use C = 2\u03c0r and A = \u03c0r\u00b2; diameter is twice the radius."],
  "g8-maths-mensuration-a-q05": ["Use C = 2\u03c0r and A = \u03c0r\u00b2; diameter is twice the radius."],
  "g8-maths-mensuration-a-q06": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-a-q07": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-a-q08": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-a-q09": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-a-q10": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q11": ["Use C = 2\u03c0r and A = \u03c0r\u00b2; diameter is twice the radius."],
  "g8-maths-mensuration-a-q12": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q13": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-a-q14": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-a-q15": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-a-q16": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-a-q17": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q18": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-a-q19": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q20": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-a-q21": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-a-q22": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-a-q23": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-a-q24": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-b-q01": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-b-q02": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-b-q03": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-b-q04": ["Use C = 2\u03c0r and A = \u03c0r\u00b2; diameter is twice the radius."],
  "g8-maths-mensuration-b-q05": ["Use C = 2\u03c0r and A = \u03c0r\u00b2; diameter is twice the radius."],
  "g8-maths-mensuration-b-q06": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-b-q07": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-b-q08": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-b-q09": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-b-q10": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-b-q11": ["Use C = 2\u03c0r and A = \u03c0r\u00b2; diameter is twice the radius."],
  "g8-maths-mensuration-b-q12": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-b-q13": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-b-q14": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-b-q15": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-b-q16": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-b-q17": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-b-q18": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-b-q19": ["Use C = 2\u03c0r and A = \u03c0r\u00b2; diameter is twice the radius."],
  "g8-maths-mensuration-b-q20": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-b-q21": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-mensuration-b-q22": ["Pick the right area formula; keep length units the same."],
  "g8-maths-mensuration-b-q23": ["Cube a\u00b3, cuboid lbh, cylinder \u03c0r\u00b2h \u2014 answer in cubic units."],
  "g8-maths-mensuration-b-q24": ["LSA covers sides; TSA adds the bases. List faces before multiplying."],
  "g8-maths-exponents-a-q01": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-a-q02": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q03": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q04": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q05": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-a-q06": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-a-q07": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-a-q08": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-a-q09": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q10": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-a-q11": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q12": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q13": ["Evaluate or rewrite with the same base before comparing."],
  "g8-maths-exponents-a-q14": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q15": ["One digit before the decimal, times a power of 10."],
  "g8-maths-exponents-a-q16": ["One digit before the decimal, times a power of 10."],
  "g8-maths-exponents-a-q17": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-a-q18": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-a-q19": ["Rewrite both sides with the same base, then equate exponents."],
  "g8-maths-exponents-a-q20": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q21": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-a-q22": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-a-q23": ["a^(m/n) means the n-th root first, then raise to m."],
  "g8-maths-exponents-a-q24": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q01": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-b-q02": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q03": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q04": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q05": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-b-q06": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-b-q07": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-b-q08": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-b-q09": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q10": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-b-q11": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q12": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q13": ["Evaluate or rewrite with the same base before comparing."],
  "g8-maths-exponents-b-q14": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q15": ["One digit before the decimal, times a power of 10."],
  "g8-maths-exponents-b-q16": ["One digit before the decimal, times a power of 10."],
  "g8-maths-exponents-b-q17": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-b-q18": ["a\u207b\u207f = 1/a\u207f; flip the fraction and make the exponent positive."],
  "g8-maths-exponents-b-q19": ["Rewrite both sides with the same base, then equate exponents."],
  "g8-maths-exponents-b-q20": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q21": ["Exponent means repeated multiplication of the base."],
  "g8-maths-exponents-b-q22": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
  "g8-maths-exponents-b-q23": ["a^(m/n) means the n-th root first, then raise to m."],
  "g8-maths-exponents-b-q24": ["Same base: add for \u00d7, subtract for \u00f7, multiply for a power of a power."],
};
