import type { HintOverlay } from "./types";

/** Grade 8 Maths item-specific hints (overlay) */
export const G8_MATHS_HINTS: Record<string, HintOverlay> = {
  "g8-maths-compare-a-q01": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q02": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q03": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-a-q04": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q05": ["Set up the comparison carefully; keep units consistent."],
  "g8-maths-compare-a-q06": ["Discount comes off the marked price."],
  "g8-maths-compare-a-q07": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q08": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q09": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q10": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q11": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q12": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q13": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q14": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q15": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q16": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-a-q17": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q18": ["Simple interest uses P × R × T / 100."],
  "g8-maths-compare-a-q19": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q20": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q21": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q22": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q23": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-a-q24": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q01": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q02": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q03": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-b-q04": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q05": ["Set up the comparison carefully; keep units consistent."],
  "g8-maths-compare-b-q06": ["Discount comes off the marked price."],
  "g8-maths-compare-b-q07": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q08": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q09": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q10": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q11": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q12": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q13": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q14": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q15": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q16": ["Keep units the same; simplify both parts by the same factor."],
  "g8-maths-compare-b-q17": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q18": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q19": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q20": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q21": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q22": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q23": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-compare-b-q24": ["Percent means out of 100; convert via fraction or decimal."],
  "g8-maths-linear-a-q01": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q02": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q03": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q04": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q05": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q06": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q07": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q08": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q09": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q10": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q11": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q12": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q13": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q14": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q15": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q16": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q17": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q18": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q19": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-a-q20": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q21": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q22": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q23": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-a-q24": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q01": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q02": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q03": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q04": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q05": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q06": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q07": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q08": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q09": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q10": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q11": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q12": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q13": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q14": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q15": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q16": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q17": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q18": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q19": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-linear-b-q20": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q21": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q22": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q23": ["Write an equation from the story, then isolate the variable."],
  "g8-maths-linear-b-q24": ["Do the same to both sides until the unknown stands alone."],
  "g8-maths-rational-a-q01": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q02": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q03": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-a-q04": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-a-q05": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q06": ["Same signs add; different signs subtract and keep the larger's sign."],
  "g8-maths-rational-a-q07": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q08": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q09": ["Positives right of 0, negatives left; equal jumps."],
  "g8-maths-rational-a-q10": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q11": ["On the number line, numbers to the right are greater."],
  "g8-maths-rational-a-q12": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q13": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q14": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q15": ["Subtracting is adding the opposite."],
  "g8-maths-rational-a-q16": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q17": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q18": ["Same signs add; different signs subtract and keep the larger's sign."],
  "g8-maths-rational-a-q19": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q20": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q21": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q22": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q23": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-a-q24": ["Same signs → positive; different signs → negative."],
  "g8-maths-rational-b-q01": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q02": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q03": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-b-q04": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q05": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q06": ["Same signs → positive; different signs → negative."],
  "g8-maths-rational-b-q07": ["Opposite means the same distance on the other side of 0."],
  "g8-maths-rational-b-q08": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q09": ["Positives right of 0, negatives left; equal jumps."],
  "g8-maths-rational-b-q10": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q11": ["On the number line, numbers to the right are greater."],
  "g8-maths-rational-b-q12": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q13": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q14": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q15": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q16": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q17": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q18": ["Subtracting is adding the opposite."],
  "g8-maths-rational-b-q19": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q20": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q21": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q22": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q23": ["Watch the signs; use a number line to check."],
  "g8-maths-rational-b-q24": ["Same signs add; different signs subtract and keep the larger's sign."],
};

