import type { HintOverlay } from "./types";

/** Grade 8 Science item-specific hints (overlay) */
export const G8_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g8-sci-cells-a-q01": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q02": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q03": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q04": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q05": ["The cell membrane controls what enters and leaves."],
  "g8-sci-cells-a-q06": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-a-q07": ["Compare wall, chloroplasts, and vacuole size in plant vs animal cells."],
  "g8-sci-cells-a-q08": ["A rigid cell wall is typical of plant cells, outside the membrane."],
  "g8-sci-cells-a-q09": ["Chloroplasts trap sunlight to make food in plant cells."],
  "g8-sci-cells-a-q10": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-a-q11": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-a-q12": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q13": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q14": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q15": ["A rigid cell wall is typical of plant cells, outside the membrane."],
  "g8-sci-cells-a-q16": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q17": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q18": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q19": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q20": ["The cell membrane controls what enters and leaves."],
  "g8-sci-cells-a-q21": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-a-q22": ["Chloroplasts trap sunlight to make food in plant cells."],
  "g8-sci-cells-a-q23": ["Mitochondria release energy from food — the powerhouses."],
  "g8-sci-cells-a-q24": ["Compare wall, chloroplasts, and vacuole size in plant vs animal cells."],
  "g8-sci-cells-b-q01": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q02": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q03": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q04": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q05": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q06": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q07": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q08": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q09": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q10": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q11": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q12": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q13": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q14": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q15": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q16": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q17": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q18": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q19": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q20": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q21": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q22": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q23": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q24": ["Compare wall, chloroplasts, and vacuole size in plant vs animal cells."],
  "g8-sci-force-a-q01": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q02": ["Recall the SI unit named in the lesson for force."],
  "g8-sci-force-a-q03": ["Contact forces need touch; non-contact forces act at a distance."],
  "g8-sci-force-a-q04": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q05": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q06": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q07": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q08": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q09": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q10": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q11": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q12": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q13": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q14": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q15": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q16": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q17": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q18": ["Contact forces need touch; non-contact forces act at a distance."],
  "g8-sci-force-a-q19": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q20": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q21": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q22": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q23": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q24": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q01": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q02": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q03": ["Contact forces need touch; non-contact forces act at a distance."],
  "g8-sci-force-b-q04": ["Recall the SI unit named in the lesson for force."],
  "g8-sci-force-b-q05": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q06": ["Recall the SI unit named in the lesson for force."],
  "g8-sci-force-b-q07": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q08": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q09": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q10": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q11": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q12": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q13": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q14": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q15": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q16": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q17": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q18": ["Magnetic force can attract or repel without touching."],
  "g8-sci-force-b-q19": ["Magnetic force can attract or repel without touching."],
  "g8-sci-force-b-q20": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q21": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q22": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q23": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q24": ["Identify which force is acting and in which direction."],
  "g8-sci-metals-a-q01": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q02": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q03": ["Most metals are good conductors of heat and electricity."],
  "g8-sci-metals-a-q04": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q05": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q06": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q07": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q08": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-a-q09": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q10": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-a-q11": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q12": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-a-q13": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q14": ["Metals often show metallic lustre when freshly cut."],
  "g8-sci-metals-a-q15": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q16": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q17": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-a-q18": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q19": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q20": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-a-q21": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-a-q22": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q23": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q24": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q01": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q02": ["Metals often show metallic lustre when freshly cut."],
  "g8-sci-metals-b-q03": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q04": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q05": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q06": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q07": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q08": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q09": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q10": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q11": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q12": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q13": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q14": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q15": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q16": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q17": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q18": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q19": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q20": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q21": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q22": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q23": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q24": ["Match the property (shine, conduction, malleability) to the substance."],
};

