import type { HintOverlay } from "./types";

/** Grade 8 Science item-specific hints (overlay) */
export const G8_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g8-sci-cells-a-q01": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q02": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q03": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q04": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q05": ["The cell membrane controls what enters and leaves."],
  "g8-sci-cells-a-q06": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-a-q07": ["Compare wall, chloroplasts, and vacuole size in plant vs animal cells."],
  "g8-sci-cells-a-q08": ["A rigid cell wall is typical of plant cells, outside the membrane."],
  "g8-sci-cells-a-q09": ["Chloroplasts trap sunlight to make food in plant cells."],
  "g8-sci-cells-a-q10": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-a-q11": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-a-q12": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q13": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q14": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q15": ["A rigid cell wall is typical of plant cells, outside the membrane."],
  "g8-sci-cells-a-q16": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q17": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q18": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q19": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-a-q20": ["The cell membrane controls what enters and leaves."],
  "g8-sci-cells-a-q21": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-a-q22": ["Chloroplasts trap sunlight to make food in plant cells."],
  "g8-sci-cells-a-q23": ["Mitochondria release energy from food — the powerhouses."],
  "g8-sci-cells-a-q24": ["Compare wall, chloroplasts, and vacuole size in plant vs animal cells."],
  "g8-sci-cells-b-q01": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q02": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q03": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q04": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q05": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q06": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q07": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q08": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q09": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q10": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q11": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q12": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q13": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q14": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q15": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q16": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q17": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q18": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q19": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q20": ["Recall the organelle or cell type the question names."],
  "g8-sci-cells-b-q21": ["Cells → tissues → organs → organ systems."],
  "g8-sci-cells-b-q22": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q23": ["The nucleus controls the cell and holds genetic material."],
  "g8-sci-cells-b-q24": ["Compare wall, chloroplasts, and vacuole size in plant vs animal cells."],
  "g8-sci-force-a-q01": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q02": ["Recall the SI unit named in the lesson for force."],
  "g8-sci-force-a-q03": ["Contact forces need touch; non-contact forces act at a distance."],
  "g8-sci-force-a-q04": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q05": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q06": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q07": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q08": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q09": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q10": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q11": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q12": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q13": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q14": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q15": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q16": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q17": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q18": ["Contact forces need touch; non-contact forces act at a distance."],
  "g8-sci-force-a-q19": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q20": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q21": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q22": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-a-q23": ["Identify which force is acting and in which direction."],
  "g8-sci-force-a-q24": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q01": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q02": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q03": ["Contact forces need touch; non-contact forces act at a distance."],
  "g8-sci-force-b-q04": ["Recall the SI unit named in the lesson for force."],
  "g8-sci-force-b-q05": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q06": ["Recall the SI unit named in the lesson for force."],
  "g8-sci-force-b-q07": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q08": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q09": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q10": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q11": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q12": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q13": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q14": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q15": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q16": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q17": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q18": ["Magnetic force can attract or repel without touching."],
  "g8-sci-force-b-q19": ["Magnetic force can attract or repel without touching."],
  "g8-sci-force-b-q20": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q21": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q22": ["Pressure = force ÷ area; sharper contact → higher pressure."],
  "g8-sci-force-b-q23": ["Identify which force is acting and in which direction."],
  "g8-sci-force-b-q24": ["Identify which force is acting and in which direction."],
  "g8-sci-metals-a-q01": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q02": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q03": ["Most metals are good conductors of heat and electricity."],
  "g8-sci-metals-a-q04": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q05": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q06": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q07": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q08": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-a-q09": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q10": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-a-q11": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q12": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-a-q13": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q14": ["Metals often show metallic lustre when freshly cut."],
  "g8-sci-metals-a-q15": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q16": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q17": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-a-q18": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q19": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q20": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-a-q21": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-a-q22": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q23": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-a-q24": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q01": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q02": ["Metals often show metallic lustre when freshly cut."],
  "g8-sci-metals-b-q03": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q04": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q05": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q06": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q07": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q08": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q09": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q10": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q11": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q12": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q13": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q14": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q15": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q16": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q17": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q18": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q19": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q20": ["Non-metals are often dull, brittle, and poor conductors."],
  "g8-sci-metals-b-q21": ["Recall which metal reacts with moist air to form rust."],
  "g8-sci-metals-b-q22": ["Use the metal's reactivity with air, water, or acids."],
  "g8-sci-metals-b-q23": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-metals-b-q24": ["Match the property (shine, conduction, malleability) to the substance."],
  "g8-sci-combustion-a-q01": ["Ask whether the substance can burn in air."],
  "g8-sci-combustion-a-q02": ["Ignition temperature is the lowest temperature for catching fire."],
  "g8-sci-combustion-a-q03": ["Rapid = quick burn; spontaneous = starts on its own; explosion = sudden bang."],
  "g8-sci-combustion-a-q04": ["Fire needs fuel, oxygen, and heat \u2014 remove any one."],
  "g8-sci-combustion-a-q05": ["Outer blue flame zone is hottest; middle yellow gives light; inner is coolest."],
  "g8-sci-combustion-a-q06": ["Calorific value is heat from 1 kg of fuel burnt completely (kJ/kg)."],
  "g8-sci-combustion-a-q07": ["CO2 and dry powder cut off air; never use water on oil or electrical fires."],
  "g8-sci-combustion-a-q08": ["Incomplete burning can make poisonous carbon monoxide."],
  "g8-sci-combustion-a-q09": ["LPG and CNG are cleaner common fuels than raw coal or wet wood."],
  "g8-sci-combustion-a-q10": ["Sulphur dioxide and nitrogen oxides link to acid rain; CO2 to warming."],
  "g8-sci-combustion-a-q11": ["Ask whether the substance can burn in air."],
  "g8-sci-combustion-a-q12": ["Ignition temperature is the lowest temperature for catching fire."],
  "g8-sci-combustion-a-q13": ["Rapid = quick burn; spontaneous = starts on its own; explosion = sudden bang."],
  "g8-sci-combustion-a-q14": ["Fire needs fuel, oxygen, and heat \u2014 remove any one."],
  "g8-sci-combustion-a-q15": ["Outer blue flame zone is hottest; middle yellow gives light; inner is coolest."],
  "g8-sci-combustion-a-q16": ["Calorific value is heat from 1 kg of fuel burnt completely (kJ/kg)."],
  "g8-sci-combustion-a-q17": ["CO2 and dry powder cut off air; never use water on oil or electrical fires."],
  "g8-sci-combustion-a-q18": ["Incomplete burning can make poisonous carbon monoxide."],
  "g8-sci-combustion-a-q19": ["LPG and CNG are cleaner common fuels than raw coal or wet wood."],
  "g8-sci-combustion-a-q20": ["Sulphur dioxide and nitrogen oxides link to acid rain; CO2 to warming."],
  "g8-sci-combustion-a-q21": ["Ask whether the substance can burn in air."],
  "g8-sci-combustion-a-q22": ["Ignition temperature is the lowest temperature for catching fire."],
  "g8-sci-combustion-a-q23": ["Rapid = quick burn; spontaneous = starts on its own; explosion = sudden bang."],
  "g8-sci-combustion-a-q24": ["Fire needs fuel, oxygen, and heat \u2014 remove any one."],
  "g8-sci-combustion-b-q01": ["Outer blue flame zone is hottest; middle yellow gives light; inner is coolest."],
  "g8-sci-combustion-b-q02": ["Calorific value is heat from 1 kg of fuel burnt completely (kJ/kg)."],
  "g8-sci-combustion-b-q03": ["CO2 and dry powder cut off air; never use water on oil or electrical fires."],
  "g8-sci-combustion-b-q04": ["Incomplete burning can make poisonous carbon monoxide."],
  "g8-sci-combustion-b-q05": ["LPG and CNG are cleaner common fuels than raw coal or wet wood."],
  "g8-sci-combustion-b-q06": ["Sulphur dioxide and nitrogen oxides link to acid rain; CO2 to warming."],
  "g8-sci-combustion-b-q07": ["Ask whether the substance can burn in air."],
  "g8-sci-combustion-b-q08": ["Ignition temperature is the lowest temperature for catching fire."],
  "g8-sci-combustion-b-q09": ["Rapid = quick burn; spontaneous = starts on its own; explosion = sudden bang."],
  "g8-sci-combustion-b-q10": ["Fire needs fuel, oxygen, and heat \u2014 remove any one."],
  "g8-sci-combustion-b-q11": ["Outer blue flame zone is hottest; middle yellow gives light; inner is coolest."],
  "g8-sci-combustion-b-q12": ["Calorific value is heat from 1 kg of fuel burnt completely (kJ/kg)."],
  "g8-sci-combustion-b-q13": ["CO2 and dry powder cut off air; never use water on oil or electrical fires."],
  "g8-sci-combustion-b-q14": ["Incomplete burning can make poisonous carbon monoxide."],
  "g8-sci-combustion-b-q15": ["LPG and CNG are cleaner common fuels than raw coal or wet wood."],
  "g8-sci-combustion-b-q16": ["Sulphur dioxide and nitrogen oxides link to acid rain; CO2 to warming."],
  "g8-sci-combustion-b-q17": ["Ask whether the substance can burn in air."],
  "g8-sci-combustion-b-q18": ["Ignition temperature is the lowest temperature for catching fire."],
  "g8-sci-combustion-b-q19": ["Rapid = quick burn; spontaneous = starts on its own; explosion = sudden bang."],
  "g8-sci-combustion-b-q20": ["Fire needs fuel, oxygen, and heat \u2014 remove any one."],
  "g8-sci-combustion-b-q21": ["Outer blue flame zone is hottest; middle yellow gives light; inner is coolest."],
  "g8-sci-combustion-b-q22": ["Calorific value is heat from 1 kg of fuel burnt completely (kJ/kg)."],
  "g8-sci-combustion-b-q23": ["CO2 and dry powder cut off air; never use water on oil or electrical fires."],
  "g8-sci-combustion-b-q24": ["Incomplete burning can make poisonous carbon monoxide."],
  "g8-sci-sound-a-q01": ["Sound starts with vibration \u2014 to-and-fro motion."],
  "g8-sci-sound-a-q02": ["Sound needs a material medium; it cannot travel in vacuum."],
  "g8-sci-sound-a-q03": ["Amplitude \u2194 loudness; frequency \u2194 pitch (unit hertz)."],
  "g8-sci-sound-a-q04": ["Human hearing is roughly 20 Hz to 20,000 Hz."],
  "g8-sci-sound-a-q05": ["Below 20 Hz is infrasound; above 20 kHz is ultrasound."],
  "g8-sci-sound-a-q06": ["Pinna collects sound; eardrum vibrates first among the membranes."],
  "g8-sci-sound-a-q07": ["An echo is reflected sound heard after a delay."],
  "g8-sci-sound-a-q08": ["Noise is unwanted sound; protect hearing and reduce loud sources."],
  "g8-sci-sound-a-q09": ["SONAR and medical scans use ultrasound echoes."],
  "g8-sci-sound-a-q10": ["Sound is usually fastest in solids, then liquids, then gases."],
  "g8-sci-sound-a-q11": ["Sound starts with vibration \u2014 to-and-fro motion."],
  "g8-sci-sound-a-q12": ["Sound needs a material medium; it cannot travel in vacuum."],
  "g8-sci-sound-a-q13": ["Amplitude \u2194 loudness; frequency \u2194 pitch (unit hertz)."],
  "g8-sci-sound-a-q14": ["Human hearing is roughly 20 Hz to 20,000 Hz."],
  "g8-sci-sound-a-q15": ["Below 20 Hz is infrasound; above 20 kHz is ultrasound."],
  "g8-sci-sound-a-q16": ["Pinna collects sound; eardrum vibrates first among the membranes."],
  "g8-sci-sound-a-q17": ["An echo is reflected sound heard after a delay."],
  "g8-sci-sound-a-q18": ["Noise is unwanted sound; protect hearing and reduce loud sources."],
  "g8-sci-sound-a-q19": ["SONAR and medical scans use ultrasound echoes."],
  "g8-sci-sound-a-q20": ["Sound is usually fastest in solids, then liquids, then gases."],
  "g8-sci-sound-a-q21": ["Sound starts with vibration \u2014 to-and-fro motion."],
  "g8-sci-sound-a-q22": ["Sound needs a material medium; it cannot travel in vacuum."],
  "g8-sci-sound-a-q23": ["Amplitude \u2194 loudness; frequency \u2194 pitch (unit hertz)."],
  "g8-sci-sound-a-q24": ["Human hearing is roughly 20 Hz to 20,000 Hz."],
  "g8-sci-sound-b-q01": ["Below 20 Hz is infrasound; above 20 kHz is ultrasound."],
  "g8-sci-sound-b-q02": ["Pinna collects sound; eardrum vibrates first among the membranes."],
  "g8-sci-sound-b-q03": ["An echo is reflected sound heard after a delay."],
  "g8-sci-sound-b-q04": ["Noise is unwanted sound; protect hearing and reduce loud sources."],
  "g8-sci-sound-b-q05": ["SONAR and medical scans use ultrasound echoes."],
  "g8-sci-sound-b-q06": ["Sound is usually fastest in solids, then liquids, then gases."],
  "g8-sci-sound-b-q07": ["Sound starts with vibration \u2014 to-and-fro motion."],
  "g8-sci-sound-b-q08": ["Sound needs a material medium; it cannot travel in vacuum."],
  "g8-sci-sound-b-q09": ["Amplitude \u2194 loudness; frequency \u2194 pitch (unit hertz)."],
  "g8-sci-sound-b-q10": ["Human hearing is roughly 20 Hz to 20,000 Hz."],
  "g8-sci-sound-b-q11": ["Below 20 Hz is infrasound; above 20 kHz is ultrasound."],
  "g8-sci-sound-b-q12": ["Pinna collects sound; eardrum vibrates first among the membranes."],
  "g8-sci-sound-b-q13": ["An echo is reflected sound heard after a delay."],
  "g8-sci-sound-b-q14": ["Noise is unwanted sound; protect hearing and reduce loud sources."],
  "g8-sci-sound-b-q15": ["SONAR and medical scans use ultrasound echoes."],
  "g8-sci-sound-b-q16": ["Sound is usually fastest in solids, then liquids, then gases."],
  "g8-sci-sound-b-q17": ["Sound starts with vibration \u2014 to-and-fro motion."],
  "g8-sci-sound-b-q18": ["Sound needs a material medium; it cannot travel in vacuum."],
  "g8-sci-sound-b-q19": ["Amplitude \u2194 loudness; frequency \u2194 pitch (unit hertz)."],
  "g8-sci-sound-b-q20": ["Human hearing is roughly 20 Hz to 20,000 Hz."],
  "g8-sci-sound-b-q21": ["Below 20 Hz is infrasound; above 20 kHz is ultrasound."],
  "g8-sci-sound-b-q22": ["Pinna collects sound; eardrum vibrates first among the membranes."],
  "g8-sci-sound-b-q23": ["An echo is reflected sound heard after a delay."],
  "g8-sci-sound-b-q24": ["Noise is unwanted sound; protect hearing and reduce loud sources."],
  "g8-sci-chemfx-a-q01": ["Good conducting liquids have mobile ions (electrolytes)."],
  "g8-sci-chemfx-a-q02": ["Distilled water is a poor conductor; salt or acid improves conduction."],
  "g8-sci-chemfx-a-q03": ["Oils and many organic liquids are poor conductors."],
  "g8-sci-chemfx-a-q04": ["Cathode is negative; anode is positive in these cells."],
  "g8-sci-chemfx-a-q05": ["Metal ions deposit on the cathode during electroplating."],
  "g8-sci-chemfx-a-q06": ["Electroplating coats an object for shine or corrosion resistance."],
  "g8-sci-chemfx-a-q07": ["LEDs and compass deflection can detect weak currents."],
  "g8-sci-chemfx-a-q08": ["Gas bubbles or metal deposits show chemical effects of current."],
  "g8-sci-chemfx-a-q09": ["The object to plate is the cathode in a suitable metal-salt bath."],
  "g8-sci-chemfx-a-q10": ["Use low-voltage battery testers \u2014 never mains in a beaker."],
  "g8-sci-chemfx-a-q11": ["Good conducting liquids have mobile ions (electrolytes)."],
  "g8-sci-chemfx-a-q12": ["Distilled water is a poor conductor; salt or acid improves conduction."],
  "g8-sci-chemfx-a-q13": ["Oils and many organic liquids are poor conductors."],
  "g8-sci-chemfx-a-q14": ["Cathode is negative; anode is positive in these cells."],
  "g8-sci-chemfx-a-q15": ["Metal ions deposit on the cathode during electroplating."],
  "g8-sci-chemfx-a-q16": ["Electroplating coats an object for shine or corrosion resistance."],
  "g8-sci-chemfx-a-q17": ["LEDs and compass deflection can detect weak currents."],
  "g8-sci-chemfx-a-q18": ["Gas bubbles or metal deposits show chemical effects of current."],
  "g8-sci-chemfx-a-q19": ["The object to plate is the cathode in a suitable metal-salt bath."],
  "g8-sci-chemfx-a-q20": ["Use low-voltage battery testers \u2014 never mains in a beaker."],
  "g8-sci-chemfx-a-q21": ["Good conducting liquids have mobile ions (electrolytes)."],
  "g8-sci-chemfx-a-q22": ["Distilled water is a poor conductor; salt or acid improves conduction."],
  "g8-sci-chemfx-a-q23": ["Oils and many organic liquids are poor conductors."],
  "g8-sci-chemfx-a-q24": ["Cathode is negative; anode is positive in these cells."],
  "g8-sci-chemfx-b-q01": ["Metal ions deposit on the cathode during electroplating."],
  "g8-sci-chemfx-b-q02": ["Electroplating coats an object for shine or corrosion resistance."],
  "g8-sci-chemfx-b-q03": ["LEDs and compass deflection can detect weak currents."],
  "g8-sci-chemfx-b-q04": ["Gas bubbles or metal deposits show chemical effects of current."],
  "g8-sci-chemfx-b-q05": ["The object to plate is the cathode in a suitable metal-salt bath."],
  "g8-sci-chemfx-b-q06": ["Use low-voltage battery testers \u2014 never mains in a beaker."],
  "g8-sci-chemfx-b-q07": ["Good conducting liquids have mobile ions (electrolytes)."],
  "g8-sci-chemfx-b-q08": ["Distilled water is a poor conductor; salt or acid improves conduction."],
  "g8-sci-chemfx-b-q09": ["Oils and many organic liquids are poor conductors."],
  "g8-sci-chemfx-b-q10": ["Cathode is negative; anode is positive in these cells."],
  "g8-sci-chemfx-b-q11": ["Metal ions deposit on the cathode during electroplating."],
  "g8-sci-chemfx-b-q12": ["Electroplating coats an object for shine or corrosion resistance."],
  "g8-sci-chemfx-b-q13": ["LEDs and compass deflection can detect weak currents."],
  "g8-sci-chemfx-b-q14": ["Gas bubbles or metal deposits show chemical effects of current."],
  "g8-sci-chemfx-b-q15": ["The object to plate is the cathode in a suitable metal-salt bath."],
  "g8-sci-chemfx-b-q16": ["Use low-voltage battery testers \u2014 never mains in a beaker."],
  "g8-sci-chemfx-b-q17": ["Good conducting liquids have mobile ions (electrolytes)."],
  "g8-sci-chemfx-b-q18": ["Distilled water is a poor conductor; salt or acid improves conduction."],
  "g8-sci-chemfx-b-q19": ["Oils and many organic liquids are poor conductors."],
  "g8-sci-chemfx-b-q20": ["Cathode is negative; anode is positive in these cells."],
  "g8-sci-chemfx-b-q21": ["Metal ions deposit on the cathode during electroplating."],
  "g8-sci-chemfx-b-q22": ["Electroplating coats an object for shine or corrosion resistance."],
  "g8-sci-chemfx-b-q23": ["LEDs and compass deflection can detect weak currents."],
  "g8-sci-chemfx-b-q24": ["Gas bubbles or metal deposits show chemical effects of current."],
};
