import type { HintOverlay } from "./types";

/** Grade 9 item-specific hints (overlay) */
export const G9_ENGLISH_HINTS: Record<string, HintOverlay> = {
  "g9-eng-ch01-a-q01": ["Find the sentence that shows her body language and promise."],
  "g9-eng-ch01-a-q02": ["Ask what the sensory image is doing for mood."],
  "g9-eng-ch01-a-q03": ["Interpret the figurative claim about stories and readers."],
  "g9-eng-ch01-a-q04": ["Scan for the dash after “recipes”."],
  "g9-eng-ch01-a-q05": ["Look at the last sentence."],
  "g9-eng-ch01-a-q06": ["What does “worn” usually mean for objects?"],
  "g9-eng-ch01-a-q07": ["Theme = big idea supported by details, not a single object."],
  "g9-eng-ch01-a-q08": ["Tone = author’s attitude; check word choice."],
  "g9-eng-ch01-a-q09": ["Locate the cause in the first sentence."],
  "g9-eng-ch01-a-q10": ["Like/as → simile; is/was without like → metaphor."],
  "g9-eng-ch01-a-q11": ["What does the dare make him try to do?"],
  "g9-eng-ch01-a-q12": ["Read the “as if” clause for attitude."],
  "g9-eng-ch01-a-q13": ["What does “surprising himself” imply about habit?"],
  "g9-eng-ch01-a-q14": ["Setting can imply risk."],
  "g9-eng-ch01-a-q15": ["Combine setting + character action for mood."],
  "g9-eng-ch01-a-q16": ["Endings often crystallise the character’s choice."],
  "g9-eng-ch01-a-q17": ["Personifying adjectives reveal struggle."],
  "g9-eng-ch01-a-q18": ["Spot like/as."],
  "g9-eng-ch01-a-q19": ["Physical details can mirror emotion."],
  "g9-eng-ch01-a-q20": ["Non-literal “vote” = figurative meaning."],
  "g9-eng-ch01-a-q21": ["Contrast reveals character priorities."],
  "g9-eng-ch01-a-q22": ["Time invested = trait clue."],
  "g9-eng-ch01-a-q23": ["Theme must fit the whole passage."],
  "g9-eng-ch01-a-q24": ["Purpose follows what the text spends energy on."],
  "g9-eng-ch01-b-q01": ["Scan for senses: sight, smell, touch."],
  "g9-eng-ch01-b-q02": ["Symbols carry meaning beyond the object."],
  "g9-eng-ch01-b-q03": ["Action revealing feeling = show, don’t tell."],
  "g9-eng-ch01-b-q04": ["Read the adjective “late.”"],
  "g9-eng-ch01-b-q05": ["Check pronouns."],
  "g9-eng-ch01-b-q06": ["Stick to what the text supports."],
  "g9-eng-ch01-b-q07": ["Ask what the image lets you picture."],
  "g9-eng-ch01-b-q08": ["Small props can signal stakes."],
  "g9-eng-ch01-b-q09": ["How does the laugh change the moment?"],
  "g9-eng-ch01-b-q10": ["Goals can be external (others) or internal."],
  "g9-eng-ch01-b-q11": ["How long and how seriously is the goat treated?"],
  "g9-eng-ch01-b-q12": ["Personification = human action on non-human."],
  "g9-eng-ch01-b-q13": ["Find the opposing energy in the courtyard."],
  "g9-eng-ch01-b-q14": ["Imperfect props humanise characters."],
  "g9-eng-ch01-b-q15": ["Which sense does the image emphasise?"],
  "g9-eng-ch01-b-q16": ["Overnight change = small win."],
  "g9-eng-ch01-b-q17": ["Match actions to attitude words."],
  "g9-eng-ch01-b-q18": ["Titles should reflect focus and tone."],
  "g9-eng-ch01-b-q19": ["Use context: dust + swimming in light."],
  "g9-eng-ch01-b-q20": ["Unpack each adjective in the image."],
  "g9-eng-ch01-b-q21": ["Props’ positions can show timing."],
  "g9-eng-ch01-b-q22": ["Eliminate what the passage never says."],
  "g9-eng-ch01-b-q23": ["Not every detail is heavy symbolism."],
  "g9-eng-ch01-b-q24": ["What does the author linger on with care?"],
  "g9-eng-ch02-a-q01": ["Match subject and auxiliary."],
  "g9-eng-ch02-a-q02": ["“By + future time” often needs future perfect."],
  "g9-eng-ch02-a-q03": ["Keep the tense; move the object forward."],
  "g9-eng-ch02-a-q04": ["Am/is → was in reported speech."],
  "g9-eng-ch02-a-q05": ["Use sound, not just spelling."],
  "g9-eng-ch02-a-q06": ["Neither/either take singular verbs."],
  "g9-eng-ch02-a-q07": ["Match modal strength to meaning."],
  "g9-eng-ch02-a-q08": ["Some plural-looking nouns are singular."],
  "g9-eng-ch02-a-q09": ["First conditional uses present in the if-clause."],
  "g9-eng-ch02-a-q10": ["Check apostrophes in let’s/it’s."],
  "g9-eng-ch02-a-q11": ["Look for be + past participle."],
  "g9-eng-ch02-a-q12": ["2019 is a point in time → since."],
  "g9-eng-ch02-a-q13": ["No question word order after asked."],
  "g9-eng-ch02-a-q14": ["Don’t stack more + -er."],
  "g9-eng-ch02-a-q15": ["Ask what question the clause answers."],
  "g9-eng-ch02-a-q16": ["Proximity rule for neither…nor."],
  "g9-eng-ch02-a-q17": ["Here “to” is a preposition, not infinitive marker."],
  "g9-eng-ch02-a-q18": ["Drop the generic people; keep tense."],
  "g9-eng-ch02-a-q19": ["Uncountable nouns take much/little, not many/few."],
  "g9-eng-ch02-a-q20": ["Remember verb patterns after suggest."],
  "g9-eng-ch02-a-q21": ["Two past times → earlier one uses had + past participle."],
  "g9-eng-ch02-a-q22": ["Commas mark extra information."],
  "g9-eng-ch02-a-q23": ["Idiomatic: It’s time we went…"],
  "g9-eng-ch02-a-q24": ["Collocation: good at."],
  "g9-eng-ch02-b-q01": ["Collective noun as one unit → singular."],
  "g9-eng-ch02-b-q02": ["Undo passive: agent + past verb + object."],
  "g9-eng-ch02-b-q03": ["Backshift modals in reported speech."],
  "g9-eng-ch02-b-q04": ["Duration → for; starting point → since."],
  "g9-eng-ch02-b-q05": ["Opposite polarity in tags."],
  "g9-eng-ch02-b-q06": ["Had been + verb-ing."],
  "g9-eng-ch02-b-q07": ["Hardly/scarcely → when; no sooner → than."],
  "g9-eng-ch02-b-q08": ["Age/colour/material sequence."],
  "g9-eng-ch02-b-q09": ["Prefer collocates with to."],
  "g9-eng-ch02-b-q10": ["Complex = subordinating conjunction joining clauses."],
  "g9-eng-ch02-b-q11": ["Each/every → singular verb."],
  "g9-eng-ch02-b-q12": ["Continuous passive needs being."],
  "g9-eng-ch02-b-q13": ["Reluctant ≈ not willing."],
  "g9-eng-ch02-b-q14": ["Insist on…"],
  "g9-eng-ch02-b-q15": ["Commands become to-infinitives."],
  "g9-eng-ch02-b-q16": ["After prepositions use object pronouns."],
  "g9-eng-ch02-b-q17": ["Spot has/have + V3."],
  "g9-eng-ch02-b-q18": ["One of → plural noun, singular verb."],
  "g9-eng-ch02-b-q19": ["Correlative: no sooner / than."],
  "g9-eng-ch02-b-q20": ["Possession → whose."],
  "g9-eng-ch02-b-q21": ["If I were you…"],
  "g9-eng-ch02-b-q22": ["There/their/they’re confusion."],
  "g9-eng-ch02-b-q23": ["To + base verb."],
  "g9-eng-ch02-b-q24": ["Seldom/never at front → invert auxiliary."],
  "g9-eng-ch03-a-q01": ["Synonym = closest meaning."],
  "g9-eng-ch03-a-q02": ["Antonym = opposite."],
  "g9-eng-ch03-a-q03": ["Principal vs principle."],
  "g9-eng-ch03-a-q04": ["Idioms are not literal."],
  "g9-eng-ch03-a-q05": ["Biblio- relates to books."],
  "g9-eng-ch03-a-q06": ["Affect vs effect."],
  "g9-eng-ch03-a-q07": ["Closest meaning."],
  "g9-eng-ch03-a-q08": ["Opposite attitude about the future."],
  "g9-eng-ch03-a-q09": ["Use context of events/matches."],
  "g9-eng-ch03-a-q10": ["Match register to format."],
  "g9-eng-ch03-a-q11": ["Audio → hear."],
  "g9-eng-ch03-a-q12": ["Car/bus → stationary."],
  "g9-eng-ch03-a-q13": ["Blue moon idiom = rarity."],
  "g9-eng-ch03-a-q14": ["Closest meaning."],
  "g9-eng-ch03-a-q15": ["Opposite of grow larger."],
  "g9-eng-ch03-a-q16": ["Bored → tedious."],
  "g9-eng-ch03-a-q17": ["Demos = people."],
  "g9-eng-ch03-a-q18": ["Into suggests examining."],
  "g9-eng-ch03-a-q19": ["Formal register openings."],
  "g9-eng-ch03-a-q20": ["Leaving someone out → except."],
  "g9-eng-ch03-a-q21": ["Closest meaning."],
  "g9-eng-ch03-a-q22": ["Non-literal meaning."],
  "g9-eng-ch03-a-q23": ["Peak/peek/pique trio."],
  "g9-eng-ch03-a-q24": ["Daily work travel = commute."],
  "g9-eng-ch03-b-q01": ["Opposite in time."],
  "g9-eng-ch03-b-q02": ["Closest meaning."],
  "g9-eng-ch03-b-q03": ["Non-literal success of accuracy."],
  "g9-eng-ch03-b-q04": ["Goes-with → complement."],
  "g9-eng-ch03-b-q05": ["Off can suggest pushing away in time."],
  "g9-eng-ch03-b-q06": ["Legible = readable; il- negates."],
  "g9-eng-ch03-b-q07": ["Faithfully vs sincerely rule."],
  "g9-eng-ch03-b-q08": ["Closest meaning."],
  "g9-eng-ch03-b-q09": ["Opposite with money/help."],
  "g9-eng-ch03-b-q10": ["Advice → counsel."],
  "g9-eng-ch03-b-q11": ["Body-part idioms for price."],
  "g9-eng-ch03-b-q12": ["Century = 100; millennium = 1000."],
  "g9-eng-ch03-b-q13": ["Common phrasal for quitting."],
  "g9-eng-ch03-b-q14": ["Verb form needed after Please."],
  "g9-eng-ch03-b-q15": ["Account quality → vivid."],
  "g9-eng-ch03-b-q16": ["Opposite result."],
  "g9-eng-ch03-b-q17": ["Pseudo- means false/fake name."],
  "g9-eng-ch03-b-q18": ["What must a reader act on?"],
  "g9-eng-ch03-b-q19": ["Closest meaning."],
  "g9-eng-ch03-b-q20": ["Mood idiom."],
  "g9-eng-ch03-b-q21": ["Ideas fitting → complement."],
  "g9-eng-ch03-b-q22": ["Context of offers/jobs."],
  "g9-eng-ch03-b-q23": ["Annus = year."],
  "g9-eng-ch03-b-q24": ["Subject lines should state purpose."],
};
