import type { HintOverlay } from "./types";

/** Grade 9 item-specific hints (overlay) */
export const G9_MATHS_HINTS: Record<string, HintOverlay> = {
  "g9-maths-numbers-a-q01": ["Ask whether the number can be written as p/q with integers."],
  "g9-maths-numbers-a-q02": ["Recall the nested number sets: N ⊂ W ⊂ Z ⊂ Q ⊂ R."],
  "g9-maths-numbers-a-q03": ["Divide and see if the remainder becomes zero."],
  "g9-maths-numbers-a-q04": ["Link decimal type to rational vs irrational."],
  "g9-maths-numbers-a-q05": ["Density of rationals on the number line."],
  "g9-maths-numbers-a-q06": ["Take square roots of numerator and denominator separately."],
  "g9-maths-numbers-a-q07": ["Check each claim against the definitions of N, W, Z, Q, R."],
  "g9-maths-numbers-a-q08": ["Multiply so the product becomes rational."],
  "g9-maths-numbers-a-q09": ["Convert a repeating single digit using 9 in the denominator."],
  "g9-maths-numbers-a-q10": ["Check prime factors of the denominator after simplifying."],
  "g9-maths-numbers-a-q11": ["Factor out the largest perfect square under the root."],
  "g9-maths-numbers-a-q12": ["Use the difference of squares identity."],
  "g9-maths-numbers-a-q13": ["Compare with perfect squares nearby."],
  "g9-maths-numbers-a-q14": ["Recall the product rule for exponents."],
  "g9-maths-numbers-a-q15": ["Expand as (a−b)(a+b) = a² − b²."],
  "g9-maths-numbers-a-q16": ["Repeating decimals are rational; non-repeating non-terminating are not."],
  "g9-maths-numbers-a-q17": ["Multiply top and bottom by √5."],
  "g9-maths-numbers-a-q18": ["Write 32 as a power of 2."],
  "g9-maths-numbers-a-q19": ["If the product were rational, you could solve for the irrational as a ratio."],
  "g9-maths-numbers-a-q20": ["Rewrite as a fraction under a square root."],
  "g9-maths-numbers-a-q21": ["Use (aᵐ)ⁿ = aᵐⁿ and rewrite 9 as 3²."],
  "g9-maths-numbers-a-q22": ["Pick the non-perfect-square root."],
  "g9-maths-numbers-a-q23": ["Simplify each radical, then combine like terms."],
  "g9-maths-numbers-a-q24": ["Multiply by the conjugate 2 − √3."],
  "g9-maths-numbers-b-q01": ["Square roots of negatives leave the reals."],
  "g9-maths-numbers-b-q02": ["Repeating expansions are rational."],
  "g9-maths-numbers-b-q03": ["Split the root across numerator and denominator."],
  "g9-maths-numbers-b-q04": ["Think about gaps on the number line."],
  "g9-maths-numbers-b-q05": ["Multiply by the conjugate of the denominator."],
  "g9-maths-numbers-b-q06": ["Write both sides with base 5."],
  "g9-maths-numbers-b-q07": ["Simplify each surd to a multiple of √3."],
  "g9-maths-numbers-b-q08": ["Prime-factor the denominator."],
  "g9-maths-numbers-b-q09": ["Irrational ± nonzero rational stays irrational."],
  "g9-maths-numbers-b-q10": ["Convert √2 to a power of 2, then multiply exponents."],
  "g9-maths-numbers-b-q11": ["No fixed repeating block means irrational."],
  "g9-maths-numbers-b-q12": ["Use the difference of squares on conjugates."],
  "g9-maths-numbers-b-q13": ["Only the product (and quotient) rules hold in general for square roots."],
  "g9-maths-numbers-b-q14": ["Compare with nearby perfect squares."],
  "g9-maths-numbers-b-q15": ["Negative exponent means reciprocal of the positive power."],
  "g9-maths-numbers-b-q16": ["Flip the sign of the whole expression."],
  "g9-maths-numbers-b-q17": ["Combine under one root or simplify each surd first."],
  "g9-maths-numbers-b-q18": ["Wholes start at 0; integers include negatives."],
  "g9-maths-numbers-b-q19": ["Square both sides carefully."],
  "g9-maths-numbers-b-q20": ["Square the coefficient and the radicand."],
  "g9-maths-numbers-b-q21": ["Recall the definition of Q."],
  "g9-maths-numbers-b-q22": ["Cube root of 8 is 2, then square."],
  "g9-maths-numbers-b-q23": ["Pull out the largest square factor."],
  "g9-maths-numbers-b-q24": ["Product of a square root with itself recovers the radicand."],
  "g9-maths-poly-a-q01": ["Degree = highest power with non-zero coefficient."],
  "g9-maths-poly-a-q02": ["Match the name to the degree."],
  "g9-maths-poly-a-q03": ["Solve p(x) = 0."],
  "g9-maths-poly-a-q04": ["Look for degree exactly 2."],
  "g9-maths-poly-a-q05": ["Substitute x = 2 carefully."],
  "g9-maths-poly-a-q06": ["Recall remainder theorem wording."],
  "g9-maths-poly-a-q07": ["Factor theorem links factors to zeros."],
  "g9-maths-poly-a-q08": ["Constants other than zero have degree 0."],
  "g9-maths-poly-a-q09": ["Use a² − b² = (a − b)(a + b)."],
  "g9-maths-poly-a-q10": ["Fundamental bound: degree limits zeros."],
  "g9-maths-poly-a-q11": ["FOIL or distribute carefully."],
  "g9-maths-poly-a-q12": ["Substitute x = 1."],
  "g9-maths-poly-a-q13": ["Recall the standard square identity."],
  "g9-maths-poly-a-q14": ["Find the term with power exactly 1."],
  "g9-maths-poly-a-q15": ["Factor or use synthetic/long division."],
  "g9-maths-poly-a-q16": ["Match the name to the degree."],
  "g9-maths-poly-a-q17": ["Sum of zeros = −(coefficient of x)/leading coefficient."],
  "g9-maths-poly-a-q18": ["Substitute x = 1."],
  "g9-maths-poly-a-q19": ["Count the number of terms."],
  "g9-maths-poly-a-q20": ["Find factor pairs of the constant that sum to the middle coefficient."],
  "g9-maths-poly-a-q21": ["Use the remainder theorem: evaluate at x = 1."],
  "g9-maths-poly-a-q22": ["Expand both squares and subtract."],
  "g9-maths-poly-a-q23": ["Apply factor theorem: p(2) = 0."],
  "g9-maths-poly-a-q24": ["Factor as a difference of squares."],
  "g9-maths-poly-b-q01": ["Find the highest power present."],
  "g9-maths-poly-b-q02": ["Zeros ≤ degree."],
  "g9-maths-poly-b-q03": ["Factor or try integer candidates."],
  "g9-maths-poly-b-q04": ["Expand the square identity for three terms."],
  "g9-maths-poly-b-q05": ["Factor theorem: zero → factor."],
  "g9-maths-poly-b-q06": ["Use (a − b)² = a² − 2ab + b²."],
  "g9-maths-poly-b-q07": ["Expand step by step and collect x² terms."],
  "g9-maths-poly-b-q08": ["Evaluate p(2) by the remainder theorem."],
  "g9-maths-poly-b-q09": ["Count terms."],
  "g9-maths-poly-b-q10": ["Check if it matches (a − b)²."],
  "g9-maths-poly-b-q11": ["Product = c/a for ax² + bx + c."],
  "g9-maths-poly-b-q12": ["Use (a+b)(a−b)=a²−b²."],
  "g9-maths-poly-b-q13": ["Ask if the graph crosses the x-axis."],
  "g9-maths-poly-b-q14": ["Solve the linear equation."],
  "g9-maths-poly-b-q15": ["Polynomials only allow whole-number powers ≥ 0."],
  "g9-maths-poly-b-q16": ["Degree drops by 1 on exact division by a linear factor."],
  "g9-maths-poly-b-q17": ["Distribute or recognise x³ − 1."],
  "g9-maths-poly-b-q18": ["Set y = 0 and solve."],
  "g9-maths-poly-b-q19": ["Substitute carefully with the negative sign."],
  "g9-maths-poly-b-q20": ["Distribute each term."],
  "g9-maths-poly-b-q21": ["Write divisor as (x − a) to read a."],
  "g9-maths-poly-b-q22": ["Find the factor pair of −15 that sums to −2."],
  "g9-maths-poly-b-q23": ["Look at the term of highest degree."],
  "g9-maths-poly-b-q24": ["Recall the binomial cube expansion."],
  "g9-maths-coord-a-q01": ["Name the intersection of the axes."],
  "g9-maths-coord-a-q02": ["Abscissa = x; ordinate = y."],
  "g9-maths-coord-a-q03": ["Sign of x and y decides the quadrant."],
  "g9-maths-coord-a-q04": ["Which coordinate vanishes on the x-axis?"],
  "g9-maths-coord-a-q05": ["Use the distance formula or axis distance."],
  "g9-maths-coord-a-q06": ["III is (−, −)."],
  "g9-maths-coord-a-q07": ["Ordinate means y."],
  "g9-maths-coord-a-q08": ["y = 0 means on the x-axis."],
  "g9-maths-coord-a-q09": ["x-axis reflection: (x, y) → (x, −y)."],
  "g9-maths-coord-a-q10": ["Need x = y > 0."],
  "g9-maths-coord-a-q11": ["Use √(x² + y²) from the origin."],
  "g9-maths-coord-a-q12": ["Left → negative x; on axis → y = 0."],
  "g9-maths-coord-a-q13": ["Clockwise from I: IV is bottom-right."],
  "g9-maths-coord-a-q14": ["Which coordinate is zero on the y-axis?"],
  "g9-maths-coord-a-q15": ["Axis points are not in any quadrant."],
  "g9-maths-coord-a-q16": ["Use the distance formula: root of delta-x squared plus delta-y squared."],
  "g9-maths-coord-a-q17": ["(x, y) → (−x, y) across the y-axis."],
  "g9-maths-coord-a-q18": ["Both coordinates zero."],
  "g9-maths-coord-a-q19": ["Write (x, y) in that order."],
  "g9-maths-coord-a-q20": ["Count the regions made by the axes."],
  "g9-maths-coord-a-q21": ["The perpendicular bisector of (−2,0) and (2,0) is the y-axis."],
  "g9-maths-coord-a-q22": ["Only the origin has both coordinates zero."],
  "g9-maths-coord-a-q23": ["Compare √(x²+y²) for each."],
  "g9-maths-coord-a-q24": ["Vertical → fixed x."],
  "g9-maths-coord-b-q01": ["Another name for the xy-plane."],
  "g9-maths-coord-b-q02": ["Axis points are not inside quadrants."],
  "g9-maths-coord-b-q03": ["II is upper-left."],
  "g9-maths-coord-b-q04": ["Distance is never negative."],
  "g9-maths-coord-b-q05": ["Negate both coordinates."],
  "g9-maths-coord-b-q06": ["Check the x-coordinate of each option."],
  "g9-maths-coord-b-q07": ["Match signs to quadrants."],
  "g9-maths-coord-b-q08": ["Vertical segment length is |y₂ − y₁|."],
  "g9-maths-coord-b-q09": ["Compare x and y."],
  "g9-maths-coord-b-q10": ["Track each reflection’s effect on signs."],
  "g9-maths-coord-b-q11": ["Translate the words into signs and distances."],
  "g9-maths-coord-b-q12": ["Ordinate means y."],
  "g9-maths-coord-b-q13": ["Base on x-axis, height on y-axis."],
  "g9-maths-coord-b-q14": ["Sign check."],
  "g9-maths-coord-b-q15": ["Horizontal → fixed y."],
  "g9-maths-coord-b-q16": ["Apply the distance formula."],
  "g9-maths-coord-b-q17": ["x-axis reflection changes y’s sign."],
  "g9-maths-coord-b-q18": ["I is upper-right."],
  "g9-maths-coord-b-q19": ["Equal x means vertical alignment."],
  "g9-maths-coord-b-q20": ["Read the signs and zeros."],
  "g9-maths-coord-b-q21": ["Match the differences to the coordinates."],
  "g9-maths-coord-b-q22": ["Zero abscissa means on the y-axis."],
  "g9-maths-coord-b-q23": ["Same y, opposite x."],
  "g9-maths-coord-b-q24": ["Definition of the origin."],
};
