import type { HintOverlay } from "./types";

/** Grade 9 item-specific hints (overlay) */
export const G9_SCIENCE_HINTS: Record<string, HintOverlay> = {
  "g9-sci-matter-a-q01": ["Recall the school definition of matter."],
  "g9-sci-matter-a-q02": ["Compare packing in solid/liquid/gas."],
  "g9-sci-matter-a-q03": ["Surface process below boiling point."],
  "g9-sci-matter-a-q04": ["Skip the liquid state."],
  "g9-sci-matter-a-q05": ["Definite shape is the solid clue."],
  "g9-sci-matter-a-q06": ["Contrast boiling with evaporation."],
  "g9-sci-matter-a-q07": ["Latent = hidden during phase change."],
  "g9-sci-matter-a-q08": ["Which particles leave during evaporation?"],
  "g9-sci-matter-a-q09": ["Think clothes drying on a windy day."],
  "g9-sci-matter-a-q10": ["Pour water into different vessels."],
  "g9-sci-matter-a-q11": ["SI temperature unit."],
  "g9-sci-matter-a-q12": ["Add 273 to Celsius."],
  "g9-sci-matter-a-q13": ["Strong forces ↔ fixed shape."],
  "g9-sci-matter-a-q14": ["Steam on a cold lid."],
  "g9-sci-matter-a-q15": ["Kinetic idea of matter."],
  "g9-sci-matter-a-q16": ["Saturated air accepts less vapour."],
  "g9-sci-matter-a-q17": ["Common benchmark temperature."],
  "g9-sci-matter-a-q18": ["Think LPG storage."],
  "g9-sci-matter-a-q19": ["Link evaporation and cooling."],
  "g9-sci-matter-a-q20": ["Ionised state beyond ordinary gas."],
  "g9-sci-matter-a-q21": ["Smell of perfume spreading."],
  "g9-sci-matter-a-q22": ["Latent heat keeps temperature steady."],
  "g9-sci-matter-a-q23": ["Fluids = liquids and gases; gases are most fluid."],
  "g9-sci-matter-a-q24": ["Standard boiling point of water."],
  "g9-sci-matter-b-q01": ["Particle nature basics."],
  "g9-sci-matter-b-q02": ["Common sublimation example."],
  "g9-sci-matter-b-q03": ["Compressibility ranking."],
  "g9-sci-matter-b-q04": ["Latent heat of vaporisation."],
  "g9-sci-matter-b-q05": ["Direct gas-to-solid change."],
  "g9-sci-matter-b-q06": ["Spread water in a plate vs a cup."],
  "g9-sci-matter-b-q07": ["Pressure and boiling."],
  "g9-sci-matter-b-q08": ["Eliminate false state claims."],
  "g9-sci-matter-b-q09": ["Structure vs state."],
  "g9-sci-matter-b-q10": ["Mixing of particles."],
  "g9-sci-matter-b-q11": ["Bottom of the kelvin scale."],
  "g9-sci-matter-b-q12": ["Physical vs chemical change."],
  "g9-sci-matter-b-q13": ["Everyday application."],
  "g9-sci-matter-b-q14": ["Weak forces ↔ free motion."],
  "g9-sci-matter-b-q15": ["Phase equilibrium at melting point."],
  "g9-sci-matter-b-q16": ["Pick the opposite factor."],
  "g9-sci-matter-b-q17": ["Density comparison."],
  "g9-sci-matter-b-q18": ["Name the property."],
  "g9-sci-matter-b-q19": ["Definition of diffusion."],
  "g9-sci-matter-b-q20": ["Add 273."],
  "g9-sci-matter-b-q21": ["Particle picture of fluidity."],
  "g9-sci-matter-b-q22": ["Classic sublimation substance."],
  "g9-sci-matter-b-q23": ["Fusion ↔ melting."],
  "g9-sci-matter-b-q24": ["Common states of matter."],
  "g9-sci-cell-a-q01": ["Smallest living unit."],
  "g9-sci-cell-a-q02": ["History of the word cell."],
  "g9-sci-cell-a-q03": ["Which organelle holds chromosomes?"],
  "g9-sci-cell-a-q04": ["Energy organelle nickname."],
  "g9-sci-cell-a-q05": ["Plant vs animal checklist."],
  "g9-sci-cell-a-q06": ["Green plastids."],
  "g9-sci-cell-a-q07": ["Cells → tissues → organs."],
  "g9-sci-cell-a-q08": ["Selective barrier name."],
  "g9-sci-cell-a-q09": ["Pro- means before a true nucleus."],
  "g9-sci-cell-a-q10": ["Plant support tissues include sclerenchyma."],
  "g9-sci-cell-a-q11": ["Growing tips of roots/shoots."],
  "g9-sci-cell-a-q12": ["Covering tissue."],
  "g9-sci-cell-a-q13": ["Plant cell hallmarks."],
  "g9-sci-cell-a-q14": ["Protein factory."],
  "g9-sci-cell-a-q15": ["Plant vascular tissue roles."],
  "g9-sci-cell-a-q16": ["Food-conducting tissue."],
  "g9-sci-cell-a-q17": ["Shipping centre of the cell."],
  "g9-sci-cell-a-q18": ["Digestive organelle."],
  "g9-sci-cell-a-q19": ["Diverse connective examples."],
  "g9-sci-cell-a-q20": ["Function of muscle."],
  "g9-sci-cell-a-q21": ["Signal tissue."],
  "g9-sci-cell-a-q22": ["One cell vs many."],
  "g9-sci-cell-a-q23": ["Plant wall chemistry."],
  "g9-sci-cell-a-q24": ["Where DNA is packaged in eukaryotes."],
  "g9-sci-cell-b-q01": ["Cell theory contributor."],
  "g9-sci-cell-b-q02": ["Interior medium of the cell."],
  "g9-sci-cell-b-q03": ["Who photosynthesises?"],
  "g9-sci-cell-b-q04": ["Meristem → permanent."],
  "g9-sci-cell-b-q05": ["Soft plant packing tissue."],
  "g9-sci-cell-b-q06": ["Living support tissue."],
  "g9-sci-cell-b-q07": ["Boundary of nucleus."],
  "g9-sci-cell-b-q08": ["Link energy demand to organelle number."],
  "g9-sci-cell-b-q09": ["Fluid connective tissue."],
  "g9-sci-cell-b-q10": ["Striations ↔ skeletal."],
  "g9-sci-cell-b-q11": ["Involuntary non-striated muscle location."],
  "g9-sci-cell-b-q12": ["Heart muscle type."],
  "g9-sci-cell-b-q13": ["Colourless storage plastids."],
  "g9-sci-cell-b-q14": ["Chromo- = colour."],
  "g9-sci-cell-b-q15": ["Prokaryote vs eukaryote."],
  "g9-sci-cell-b-q16": ["Order: wall outside membrane."],
  "g9-sci-cell-b-q17": ["Covering animal tissue."],
  "g9-sci-cell-b-q18": ["Supportive connective tissue."],
  "g9-sci-cell-b-q19": ["Early microscopy history."],
  "g9-sci-cell-b-q20": ["Core claim of cell theory."],
  "g9-sci-cell-b-q21": ["Compare vacuole size."],
  "g9-sci-cell-b-q22": ["Vascular tissue components."],
  "g9-sci-cell-b-q23": ["Prefix multi-."],
  "g9-sci-cell-b-q24": ["Green photosynthetic pigment."],
  "g9-sci-motion-a-q01": ["Scalar vs vector for path length."],
  "g9-sci-motion-a-q02": ["Start and end at same point."],
  "g9-sci-motion-a-q03": ["Speed formula."],
  "g9-sci-motion-a-q04": ["Does velocity include direction?"],
  "g9-sci-motion-a-q05": ["Unit of Δv/Δt."],
  "g9-sci-motion-a-q06": ["Acceleration needs changing velocity."],
  "g9-sci-motion-a-q07": ["Vector sum of opposite equal displacements."],
  "g9-sci-motion-a-q08": ["Velocity cares about net displacement."],
  "g9-sci-motion-a-q09": ["Rise/run on distance–time."],
  "g9-sci-motion-a-q10": ["Slope meaning on v–t."],
  "g9-sci-motion-a-q11": ["Area under v–t."],
  "g9-sci-motion-a-q12": ["Vectors need direction."],
  "g9-sci-motion-a-q13": ["Speed vs velocity on a circle."],
  "g9-sci-motion-a-q14": ["Recall v = u + at."],
  "g9-sci-motion-a-q15": ["When do the three equations apply?"],
  "g9-sci-motion-a-q16": ["Rest → zero initial velocity."],
  "g9-sci-motion-a-q17": ["Opposite direction of a and v."],
  "g9-sci-motion-a-q18": ["Nth-second formula."],
  "g9-sci-motion-a-q19": ["Uniform speed on s–t."],
  "g9-sci-motion-a-q20": ["SI length unit."],
  "g9-sci-motion-a-q21": ["Pythagoras for perpendicular displacements."],
  "g9-sci-motion-a-q22": ["Meaning of instantaneous."],
  "g9-sci-motion-a-q23": ["Flat v–t ⇒ no acceleration."],
  "g9-sci-motion-a-q24": ["Acceleration due to gravity."],
  "g9-sci-motion-b-q01": ["Which can carry a sign?"],
  "g9-sci-motion-b-q02": ["Distance over time."],
  "g9-sci-motion-b-q03": ["Displacement/time."],
  "g9-sci-motion-b-q04": ["No change in velocity → a = 0."],
  "g9-sci-motion-b-q05": ["Which variable is missing?"],
  "g9-sci-motion-b-q06": ["Flat s–t."],
  "g9-sci-motion-b-q07": ["Straight sloping v–t."],
  "g9-sci-motion-b-q08": ["Scalar definition."],
  "g9-sci-motion-b-q09": ["Δv/Δt."],
  "g9-sci-motion-b-q10": ["Path length ≥ 0."],
  "g9-sci-motion-b-q11": ["Use v = u + at with u=0."],
  "g9-sci-motion-b-q12": ["Definition of uniform motion."],
  "g9-sci-motion-b-q13": ["Opposite of uniform."],
  "g9-sci-motion-b-q14": ["s = ut + ½at²."],
  "g9-sci-motion-b-q15": ["Include direction for velocity."],
  "g9-sci-motion-b-q16": ["Slowing down."],
  "g9-sci-motion-b-q17": ["Dashboard instrument roles."],
  "g9-sci-motion-b-q18": ["Instantaneous reading."],
  "g9-sci-motion-b-q19": ["Steeper s–t → faster."],
  "g9-sci-motion-b-q20": ["Straight shortcut vs path."],
  "g9-sci-motion-b-q21": ["Constant velocity case."],
  "g9-sci-motion-b-q22": ["Scan for missing t."],
  "g9-sci-motion-b-q23": ["Round trip displacement."],
  "g9-sci-motion-b-q24": ["SI speed unit."],
};
