import type { ChapterDef, PrepQuestion } from "../types";

/** Antonyms — authored Grade 3 English content (original). */

const SET_A: PrepQuestion[] = [
  {
    id: "g3-eng-antonyms-a-q01",
    prompt: "Which word means the OPPOSITE of \"happy\"?",
    options: [
      { id: "a", text: "sad" },
      { id: "b", text: "glad" },
      { id: "c", text: "joyful" },
      { id: "d", text: "merry" },
    ],
    answerId: "a",
    explanation: "\"Sad\" is the opposite feeling of \"happy.\" Glad, joyful and merry are closer to happy.",
    hints: ["Happy is a cheerful feeling.", "Glad and joyful are twins of happy, not opposites."],
  },
  {
    id: "g3-eng-antonyms-a-q02",
    prompt: "Which word means the OPPOSITE of \"big\"?",
    options: [
      { id: "a", text: "small" },
      { id: "b", text: "large" },
      { id: "c", text: "huge" },
      { id: "d", text: "giant" },
    ],
    answerId: "a",
    explanation: "\"Small\" is the opposite size of \"big.\" Large, huge and giant mean nearly the same as big.",
    hints: ["Think of an ant next to an elephant.", "Large is a twin of big, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q03",
    prompt: "The chai was too **hot**. Which word means the opposite of \"hot\"?",
    options: [
      { id: "a", text: "warm" },
      { id: "b", text: "boiling" },
      { id: "c", text: "spicy" },
      { id: "d", text: "cold" },
    ],
    answerId: "d",
    explanation: "\"Cold\" is the opposite of \"hot.\" Warm and boiling are still on the heated side.",
    hints: ["Hot makes you want a fan.", "Warm is closer to hot than to cold."],
  },
  {
    id: "g3-eng-antonyms-a-q04",
    prompt: "Which word means the OPPOSITE of \"up\"?",
    options: [
      { id: "a", text: "above" },
      { id: "b", text: "high" },
      { id: "c", text: "over" },
      { id: "d", text: "down" },
    ],
    answerId: "d",
    explanation: "\"Down\" is the opposite direction of \"up.\" Above, high and over are closer to up.",
    hints: ["Up points toward the sky.", "Above is not the opposite of up."],
  },
  {
    id: "g3-eng-antonyms-a-q05",
    prompt: "Riya's water bottle was **full**. Which word means the opposite of \"full\"?",
    options: [
      { id: "a", text: "packed" },
      { id: "b", text: "empty" },
      { id: "c", text: "heavy" },
      { id: "d", text: "crowded" },
    ],
    answerId: "b",
    explanation: "\"Empty\" means nothing inside — the opposite of \"full.\" Packed and crowded are fuller ideas.",
    hints: ["Full means filled up.", "Packed is closer to full, not empty."],
  },
  {
    id: "g3-eng-antonyms-a-q06",
    prompt: "Which word means the OPPOSITE of \"early\"?",
    options: [
      { id: "a", text: "late" },
      { id: "b", text: "soon" },
      { id: "c", text: "first" },
      { id: "d", text: "quick" },
    ],
    answerId: "a",
    explanation: "\"Late\" means after the right time — the opposite of \"early.\" Soon and first are not opposites.",
    hints: ["Early means before the usual time.", "Soon is not the opposite of early."],
  },
  {
    id: "g3-eng-antonyms-a-q07",
    prompt: "Kabir is **strong** and can carry the cricket bag. Which word means the opposite of \"strong\"?",
    options: [
      { id: "a", text: "tough" },
      { id: "b", text: "powerful" },
      { id: "c", text: "solid" },
      { id: "d", text: "weak" },
    ],
    answerId: "d",
    explanation: "\"Weak\" means not strong. Tough, powerful and solid are closer to strong.",
    hints: ["Strong people can lift heavy things.", "Powerful is a twin of strong, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q08",
    prompt: "Which word means the OPPOSITE of \"open\"?",
    options: [
      { id: "a", text: "closed" },
      { id: "b", text: "wide" },
      { id: "c", text: "clear" },
      { id: "d", text: "free" },
    ],
    answerId: "a",
    explanation: "\"Closed\" (or shut) is the opposite of \"open.\" Wide and clear are not opposites.",
    hints: ["An open door lets you walk through.", "Think of a door you cannot walk through."],
  },
  {
    id: "g3-eng-antonyms-a-q09",
    prompt: "We play in the park during the **day**. Which word means the opposite of \"day\"?",
    options: [
      { id: "a", text: "morning" },
      { id: "b", text: "noon" },
      { id: "c", text: "night" },
      { id: "d", text: "afternoon" },
    ],
    answerId: "c",
    explanation: "\"Night\" is when it is dark — the opposite of \"day.\" Morning, noon and afternoon are parts of the day.",
    hints: ["Day is when the sun is out.", "Morning is still part of the day."],
  },
  {
    id: "g3-eng-antonyms-a-q10",
    prompt: "Which word means the OPPOSITE of \"clean\"?",
    options: [
      { id: "a", text: "neat" },
      { id: "b", text: "fresh" },
      { id: "c", text: "shiny" },
      { id: "d", text: "dirty" },
    ],
    answerId: "d",
    explanation: "\"Dirty\" means not clean. Neat, fresh and shiny are closer to clean.",
    hints: ["Clean clothes look washed.", "Neat is closer to clean, not dirty."],
  },
  {
    id: "g3-eng-antonyms-a-q11",
    prompt: "The auto moved **fast** on the empty road. Which word means the opposite of \"fast\"?",
    options: [
      { id: "a", text: "quick" },
      { id: "b", text: "speedy" },
      { id: "c", text: "swift" },
      { id: "d", text: "slow" },
    ],
    answerId: "d",
    explanation: "\"Slow\" is the opposite of \"fast.\" Quick, speedy and swift mean nearly the same as fast.",
    hints: ["Fast means taking little time.", "Quick is a twin of fast, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q12",
    prompt: "Which word means the OPPOSITE of \"tall\"?",
    options: [
      { id: "a", text: "short" },
      { id: "b", text: "high" },
      { id: "c", text: "long" },
      { id: "d", text: "huge" },
    ],
    answerId: "a",
    explanation: "\"Short\" is the opposite of \"tall\" for height. High and long are not clear opposites here.",
    hints: ["Tall people reach high shelves.", "High is not the opposite of tall."],
  },
  {
    id: "g3-eng-antonyms-a-q13",
    prompt: "Amma was **kind** to the lost puppy. Which word means the opposite of \"kind\"?",
    options: [
      { id: "a", text: "caring" },
      { id: "b", text: "gentle" },
      { id: "c", text: "rude" },
      { id: "d", text: "helpful" },
    ],
    answerId: "c",
    explanation: "\"Rude\" means not kind or polite. Caring, gentle and helpful are closer to kind.",
    hints: ["Kind people help and share.", "Caring is a twin of kind, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q14",
    prompt: "Which word means the OPPOSITE of \"soft\" (to touch)?",
    options: [
      { id: "a", text: "fluffy" },
      { id: "b", text: "smooth" },
      { id: "c", text: "gentle" },
      { id: "d", text: "hard" },
    ],
    answerId: "d",
    explanation: "\"Hard\" is the opposite feel of \"soft.\" Fluffy and smooth are closer to soft.",
    hints: ["A pillow feels soft.", "Fluffy is not the opposite of soft."],
  },
  {
    id: "g3-eng-antonyms-a-q15",
    prompt: "Ananya's school bag felt **light**. Which word means the opposite of \"light\" (weight)?",
    options: [
      { id: "a", text: "heavy" },
      { id: "b", text: "easy" },
      { id: "c", text: "thin" },
      { id: "d", text: "empty" },
    ],
    answerId: "a",
    explanation: "Here \"light\" means not much weight, so \"heavy\" is the opposite. Easy and thin are different ideas.",
    hints: ["Light bags are easy to carry.", "Empty is about how full something is, not always about weight."],
  },
  {
    id: "g3-eng-antonyms-a-q16",
    prompt: "Which word means the OPPOSITE of \"near\"?",
    options: [
      { id: "a", text: "far" },
      { id: "b", text: "close" },
      { id: "c", text: "beside" },
      { id: "d", text: "next" },
    ],
    answerId: "a",
    explanation: "\"Far\" means a long distance away — the opposite of \"near.\" Close and beside are closer to near.",
    hints: ["Near means a short walk away.", "Close is a twin of near, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q17",
    prompt: "Please **begin** your worksheet. Which word means the opposite of \"begin\"?",
    options: [
      { id: "a", text: "start" },
      { id: "b", text: "end" },
      { id: "c", text: "open" },
      { id: "d", text: "try" },
    ],
    answerId: "b",
    explanation: "\"End\" means to finish — the opposite of \"begin.\" Start is a twin of begin.",
    hints: ["Begin means to get going.", "Start means nearly the same as begin."],
  },
  {
    id: "g3-eng-antonyms-a-q18",
    prompt: "Which word means the OPPOSITE of \"wet\"?",
    options: [
      { id: "a", text: "damp" },
      { id: "b", text: "soaked" },
      { id: "c", text: "dry" },
      { id: "d", text: "muddy" },
    ],
    answerId: "c",
    explanation: "\"Dry\" means without water — the opposite of \"wet.\" Damp and soaked are still wet ideas.",
    hints: ["Wet things have water on them.", "Damp means a little wet, not dry."],
  },
  {
    id: "g3-eng-antonyms-a-q19",
    prompt: "The market was very **noisy**. Which word means the opposite of \"noisy\"?",
    options: [
      { id: "a", text: "quiet" },
      { id: "b", text: "loud" },
      { id: "c", text: "busy" },
      { id: "d", text: "crowded" },
    ],
    answerId: "a",
    explanation: "\"Quiet\" means little sound — the opposite of \"noisy.\" Loud is closer to noisy.",
    hints: ["Noisy places have lots of sound.", "Loud is a twin of noisy, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q20",
    prompt: "Which word means the OPPOSITE of \"rich\"?",
    options: [
      { id: "a", text: "poor" },
      { id: "b", text: "wealthy" },
      { id: "c", text: "lucky" },
      { id: "d", text: "grand" },
    ],
    answerId: "a",
    explanation: "\"Poor\" means having little money — the opposite of \"rich.\" Wealthy means nearly the same as rich.",
    hints: ["Rich can mean having much money.", "Wealthy is a twin of rich, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q21",
    prompt: "Meera chose the **correct** sum. Which word means the opposite of \"correct\"?",
    options: [
      { id: "a", text: "right" },
      { id: "b", text: "true" },
      { id: "c", text: "wrong" },
      { id: "d", text: "exact" },
    ],
    answerId: "c",
    explanation: "\"Wrong\" means not correct. Right, true and exact are closer to correct.",
    hints: ["Correct answers match the truth.", "Right is a twin of correct, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-a-q22",
    prompt: "Which word means the OPPOSITE of \"brave\"?",
    options: [
      { id: "a", text: "courageous" },
      { id: "b", text: "bold" },
      { id: "c", text: "proud" },
      { id: "d", text: "scared" },
    ],
    answerId: "d",
    explanation: "\"Scared\" (afraid) is the opposite feeling of \"brave.\" Courageous and bold are closer to brave.",
    hints: ["Brave people face hard things.", "Courageous means nearly the same as brave."],
  },
  {
    id: "g3-eng-antonyms-a-q23",
    prompt: "Aarav bought a pencil for ₹5. Buying is the opposite of which action?",
    options: [
      { id: "a", text: "keep" },
      { id: "b", text: "find" },
      { id: "c", text: "sell" },
      { id: "d", text: "share" },
    ],
    answerId: "c",
    explanation: "\"Sell\" means give something for money — the opposite of \"buy.\" Keep, find and share are different actions.",
    hints: ["Buy means you pay and take something home.", "Think of what the shopkeeper does."],
  },
  {
    id: "g3-eng-antonyms-a-q24",
    prompt: "Which word means the OPPOSITE of \"thick\"?",
    options: [
      { id: "a", text: "wide" },
      { id: "b", text: "fat" },
      { id: "c", text: "thin" },
      { id: "d", text: "broad" },
    ],
    answerId: "c",
    explanation: "\"Thin\" is the opposite of \"thick.\" Wide, fat and broad are closer to thick ideas.",
    hints: ["A thick book has many pages.", "Wide is not the clear opposite of thick."],
  },
];

const SET_B: PrepQuestion[] = [
  {
    id: "g3-eng-antonyms-b-q01",
    prompt: "Which word means the OPPOSITE of \"old\" (for a school bag)?",
    options: [
      { id: "a", text: "ancient" },
      { id: "b", text: "new" },
      { id: "c", text: "used" },
      { id: "d", text: "worn" },
    ],
    answerId: "b",
    explanation: "\"New\" is the opposite of \"old.\" Ancient, used and worn are closer to old.",
    hints: ["Old things have been around a long time.", "Ancient means very old, not new."],
  },
  {
    id: "g3-eng-antonyms-b-q02",
    prompt: "Wash your hands **before** lunch. Which word means the opposite of \"before\"?",
    options: [
      { id: "a", text: "after" },
      { id: "b", text: "earlier" },
      { id: "c", text: "first" },
      { id: "d", text: "already" },
    ],
    answerId: "a",
    explanation: "\"After\" means later in time — the opposite of \"before.\" Earlier and first are closer to before.",
    hints: ["Before means earlier than something.", "Earlier is not the opposite of before."],
  },
  {
    id: "g3-eng-antonyms-b-q03",
    prompt: "Which word means the OPPOSITE of \"above\"?",
    options: [
      { id: "a", text: "over" },
      { id: "b", text: "up" },
      { id: "c", text: "below" },
      { id: "d", text: "high" },
    ],
    answerId: "c",
    explanation: "\"Below\" means under — the opposite of \"above.\" Over, up and high are closer to above.",
    hints: ["Above means higher than something.", "Over is closer to above, not below."],
  },
  {
    id: "g3-eng-antonyms-b-q04",
    prompt: "The cat sat **inside** the box. Which word means the opposite of \"inside\"?",
    options: [
      { id: "a", text: "within" },
      { id: "b", text: "outside" },
      { id: "c", text: "under" },
      { id: "d", text: "beside" },
    ],
    answerId: "b",
    explanation: "\"Outside\" means not in — the opposite of \"inside.\" Within means nearly the same as inside.",
    hints: ["Inside means in the box.", "Within is a twin of inside, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-b-q05",
    prompt: "Which word means the OPPOSITE of \"win\"?",
    options: [
      { id: "a", text: "score" },
      { id: "b", text: "cheer" },
      { id: "c", text: "play" },
      { id: "d", text: "lose" },
    ],
    answerId: "d",
    explanation: "\"Lose\" is the opposite of \"win\" in a game. Score, cheer and play are different actions.",
    hints: ["Win means you come first or beat the other side.", "Cheer is not the opposite of win."],
  },
  {
    id: "g3-eng-antonyms-b-q06",
    prompt: "Nisha **loves** mango pickle. Which word means the opposite of \"love\"?",
    options: [
      { id: "a", text: "like" },
      { id: "b", text: "enjoy" },
      { id: "c", text: "hate" },
      { id: "d", text: "prefer" },
    ],
    answerId: "c",
    explanation: "\"Hate\" is a strong opposite of \"love.\" Like, enjoy and prefer are softer positive words.",
    hints: ["Love means you like something a lot.", "Like is not the opposite of love."],
  },
  {
    id: "g3-eng-antonyms-b-q07",
    prompt: "Which word means the OPPOSITE of \"sharp\" (for a pencil tip)?",
    options: [
      { id: "a", text: "pointed" },
      { id: "b", text: "blunt" },
      { id: "c", text: "fine" },
      { id: "d", text: "keen" },
    ],
    answerId: "b",
    explanation: "\"Blunt\" means not sharp. Pointed, fine and keen are closer to sharp.",
    hints: ["A sharp pencil writes a thin line.", "Pointed is closer to sharp, not blunt."],
  },
  {
    id: "g3-eng-antonyms-b-q08",
    prompt: "The laddu tasted **sweet**. Which word means the opposite of \"sweet\"?",
    options: [
      { id: "a", text: "sugary" },
      { id: "b", text: "tasty" },
      { id: "c", text: "bitter" },
      { id: "d", text: "yummy" },
    ],
    answerId: "c",
    explanation: "\"Bitter\" is a taste opposite of \"sweet.\" Sugary, tasty and yummy are not opposites.",
    hints: ["Sweet foods like ladoos taste sugary.", "Sugary is a twin of sweet, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-b-q09",
    prompt: "Which word means the OPPOSITE of \"hard\" (for a maths sum)?",
    options: [
      { id: "a", text: "tough" },
      { id: "b", text: "tricky" },
      { id: "c", text: "difficult" },
      { id: "d", text: "easy" },
    ],
    answerId: "d",
    explanation: "Here \"hard\" means not easy, so \"easy\" is the opposite. Tough and difficult are twins of hard.",
    hints: ["In class, hard means not easy to solve.", "Difficult means nearly the same as hard."],
  },
  {
    id: "g3-eng-antonyms-b-q10",
    prompt: "Please **give** Diya the eraser. Which word means the opposite of \"give\"?",
    options: [
      { id: "a", text: "share" },
      { id: "b", text: "take" },
      { id: "c", text: "offer" },
      { id: "d", text: "pass" },
    ],
    answerId: "b",
    explanation: "\"Take\" means receive or grab — often the opposite action of \"give.\" Share and offer are closer to give.",
    hints: ["Give means you hand something to someone.", "Offer is closer to give, not take."],
  },
  {
    id: "g3-eng-antonyms-b-q11",
    prompt: "Which word means the OPPOSITE of \"push\"?",
    options: [
      { id: "a", text: "shove" },
      { id: "b", text: "press" },
      { id: "c", text: "pull" },
      { id: "d", text: "nudge" },
    ],
    answerId: "c",
    explanation: "\"Pull\" is the opposite action of \"push.\" Shove, press and nudge are closer to pushing.",
    hints: ["Push moves something away from you.", "Shove is a strong push, not a pull."],
  },
  {
    id: "g3-eng-antonyms-b-q12",
    prompt: "Rohan tried to **remember** his spelling list. Which word means the opposite of \"remember\"?",
    options: [
      { id: "a", text: "recall" },
      { id: "b", text: "forget" },
      { id: "c", text: "learn" },
      { id: "d", text: "study" },
    ],
    answerId: "b",
    explanation: "\"Forget\" means you cannot bring something to mind — the opposite of \"remember.\" Recall is a twin of remember.",
    hints: ["Remember means keep something in your mind.", "Recall means nearly the same as remember."],
  },
  {
    id: "g3-eng-antonyms-b-q13",
    prompt: "Which word means the OPPOSITE of \"arrive\"?",
    options: [
      { id: "a", text: "reach" },
      { id: "b", text: "come" },
      { id: "c", text: "enter" },
      { id: "d", text: "leave" },
    ],
    answerId: "d",
    explanation: "\"Leave\" (go away) is the opposite of \"arrive.\" Reach and come are closer to arrive.",
    hints: ["Arrive means you get to a place.", "Reach is closer to arrive, not leave."],
  },
  {
    id: "g3-eng-antonyms-b-q14",
    prompt: "The shopkeeper was **polite** for ₹10 change. Which word means the opposite of \"polite\"?",
    options: [
      { id: "a", text: "courteous" },
      { id: "b", text: "rude" },
      { id: "c", text: "kind" },
      { id: "d", text: "gentle" },
    ],
    answerId: "b",
    explanation: "\"Rude\" means not polite. Courteous, kind and gentle are closer to polite.",
    hints: ["Polite people say please and thank you.", "Courteous is a twin of polite, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-b-q15",
    prompt: "Which word means the OPPOSITE of \"wide\"?",
    options: [
      { id: "a", text: "broad" },
      { id: "b", text: "narrow" },
      { id: "c", text: "large" },
      { id: "d", text: "open" },
    ],
    answerId: "b",
    explanation: "\"Narrow\" means not wide. Broad and large are closer to wide.",
    hints: ["A wide road has lots of space across.", "Broad is a twin of wide, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-b-q16",
    prompt: "Amina shared her tiffin with a **friend**. Which word means the opposite of \"friend\"?",
    options: [
      { id: "a", text: "buddy" },
      { id: "b", text: "pal" },
      { id: "c", text: "enemy" },
      { id: "d", text: "mate" },
    ],
    answerId: "c",
    explanation: "An \"enemy\" is the opposite idea of a \"friend.\" Buddy, pal and mate are twins of friend.",
    hints: ["A friend is someone you like to be with.", "Buddy means nearly the same as friend."],
  },
  {
    id: "g3-eng-antonyms-b-q17",
    prompt: "Which word means the OPPOSITE of \"laugh\"?",
    options: [
      { id: "a", text: "giggle" },
      { id: "b", text: "smile" },
      { id: "c", text: "cheer" },
      { id: "d", text: "cry" },
    ],
    answerId: "d",
    explanation: "\"Cry\" is the opposite action of \"laugh.\" Giggle, smile and cheer are happier actions.",
    hints: ["Laugh is a happy sound.", "Giggle is a light laugh, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-b-q18",
    prompt: "The classroom was **bright** after Diwali cleaning. Which word means the opposite of \"bright\"?",
    options: [
      { id: "a", text: "shiny" },
      { id: "b", text: "dark" },
      { id: "c", text: "clear" },
      { id: "d", text: "glowing" },
    ],
    answerId: "b",
    explanation: "\"Dark\" means little light — the opposite of \"bright.\" Shiny, clear and glowing are closer to bright.",
    hints: ["Bright places have lots of light.", "Shiny is closer to bright, not dark."],
  },
  {
    id: "g3-eng-antonyms-b-q19",
    prompt: "Which word means the OPPOSITE of \"first\"?",
    options: [
      { id: "a", text: "next" },
      { id: "b", text: "early" },
      { id: "c", text: "top" },
      { id: "d", text: "last" },
    ],
    answerId: "d",
    explanation: "\"Last\" is the opposite of \"first\" in a line or list. Next and early are not clear opposites.",
    hints: ["First means at the beginning.", "Next means the one after, not the opposite of first."],
  },
  {
    id: "g3-eng-antonyms-b-q20",
    prompt: "The kite flew **high** over the gali. Which word means the opposite of \"high\"?",
    options: [
      { id: "a", text: "tall" },
      { id: "b", text: "up" },
      { id: "c", text: "low" },
      { id: "d", text: "above" },
    ],
    answerId: "c",
    explanation: "\"Low\" is the opposite of \"high.\" Tall, up and above are closer to high ideas.",
    hints: ["High means far up from the ground.", "Up is not the opposite of high."],
  },
  {
    id: "g3-eng-antonyms-b-q21",
    prompt: "Which word means the OPPOSITE of \"young\"?",
    options: [
      { id: "a", text: "small" },
      { id: "b", text: "old" },
      { id: "c", text: "new" },
      { id: "d", text: "tiny" },
    ],
    answerId: "b",
    explanation: "\"Old\" is the opposite of \"young\" for age. Small and tiny are about size, not age.",
    hints: ["Young means not many years old.", "Small is about size, not age."],
  },
  {
    id: "g3-eng-antonyms-b-q22",
    prompt: "During the monsoon, the lane had **huge** puddles. Which word means the opposite of \"huge\"?",
    options: [
      { id: "a", text: "enormous" },
      { id: "b", text: "giant" },
      { id: "c", text: "tiny" },
      { id: "d", text: "vast" },
    ],
    answerId: "c",
    explanation: "\"Tiny\" means very small — the opposite of \"huge.\" Enormous, giant and vast mean very big.",
    hints: ["Huge means very big.", "Enormous is a twin of huge, not an opposite."],
  },
  {
    id: "g3-eng-antonyms-b-q23",
    prompt: "Which word means the OPPOSITE of \"deep\" (for a well)?",
    options: [
      { id: "a", text: "long" },
      { id: "b", text: "tall" },
      { id: "c", text: "wide" },
      { id: "d", text: "shallow" },
    ],
    answerId: "d",
    explanation: "\"Shallow\" means not deep. Long, tall and wide measure other directions.",
    hints: ["A deep well goes far down.", "Wide is about how broad something is, not how deep."],
  },
  {
    id: "g3-eng-antonyms-b-q24",
    prompt: "Sana felt **proud** after a neat notebook. Which word means the opposite of \"proud\"?",
    options: [
      { id: "a", text: "pleased" },
      { id: "b", text: "glad" },
      { id: "c", text: "happy" },
      { id: "d", text: "ashamed" },
    ],
    answerId: "d",
    explanation: "\"Ashamed\" is a bad feeling about yourself — closer to the opposite of \"proud.\" Pleased and glad are positive.",
    hints: ["Proud is a good feeling after doing well.", "Pleased is closer to proud, not ashamed."],
  },
];

const lesson: ChapterDef["lesson"] = [
  {
    id: "h",
    type: "hook",
    emoji: "🔄",
    title: "Word opposites",
    body: [
      "Some words face each other — they mean the opposite thing.",
      "We call those opposites antonyms. Tap, try, then check!",
    ],
    cta: "Meet the opposites!",
    visual: "word-cards",
    speak: "Some words mean the opposite. We call them antonyms.",
  },
  {
    id: "r1",
    type: "reveal",
    title: "Tap the flip",
    lead: "Reveal the opposite for each word.",
    visual: "word-cards",
    speak: "Tap each word to reveal an antonym.",
    cards: [
      { label: "hot", reveal: "cold", emoji: "❄️" },
      { label: "big", reveal: "small", emoji: "🐜" },
      { label: "happy", reveal: "sad", emoji: "😢" },
      { label: "up", reveal: "down", emoji: "⬇️" },
    ],
  },
  {
    id: "d1",
    type: "demo",
    title: "Try it in a sentence",
    visual: "word-cards",
    speak: "The chai is hot. The chai is cold. Hot and cold are antonyms — they flip the meaning.",
    steps: [
      "The chai is hot.",
      "Swap hot for cold: The chai is cold.",
      "The meaning flips — not the same!",
      "So hot and cold are antonyms",
    ],
    punchline: "If swapping the word flips the meaning, you found an opposite!",
  },
  {
    id: "t1",
    type: "try",
    title: "Pick the opposite",
    prompt: "Antonym of “brave”?",
    options: [
      { id: "a", text: "courageous" },
      { id: "b", text: "scared" },
      { id: "c", text: "bold" },
      { id: "d", text: "strong" },
    ],
    answerId: "b",
    why: "Scared is the opposite of brave. Courageous and bold are closer to synonyms.",
    visual: "word-cards",
    speak: "Which word is an antonym of brave?",
  },
  {
    id: "c1",
    type: "check",
    title: "Quick check",
    visual: "word-cards",
    speak: "Which pair are antonyms?",
    question: {
      id: "g3-eng-antonyms-check",
      prompt: "Which pair are antonyms?",
      options: [
        { id: "a", text: "big — large" },
        { id: "b", text: "happy — glad" },
        { id: "c", text: "hot — cold" },
        { id: "d", text: "start — begin" },
      ],
      answerId: "c",
      explanation: "Hot and cold are opposites. The other pairs are synonyms (nearly the same meaning).",
      hints: ["Antonyms are meaning opposites.", "Big and large are twins, not opposites."],
    },
  },
  {
    id: "w",
    type: "wrap",
    emoji: "📚",
    title: "Opposite power!",
    bullets: [
      "Antonym = opposite meaning",
      "Try swapping the word — does the idea flip?",
      "Watch out for synonym traps in the options",
      "Set A and Set B — 24 questions each",
    ],
    cta: "Back to chapter",
    speak: "Antonym means opposite. You are ready for the practice sets.",
  },
];

export const g3EnglishAntonyms: ChapterDef = {
  id: "antonyms",
  title: "Antonyms",
  emoji: "🔄",
  blurb: "Opposite meanings",
  lesson,
  sets: [
    {
      id: "set-a",
      title: "Set A",
      questionCount: SET_A.length,
      topic: "antonyms",
      questions: SET_A,
    },
    {
      id: "set-b",
      title: "Set B",
      questionCount: SET_B.length,
      topic: "antonyms",
      questions: SET_B,
    },
  ],
  paperTopics: ["antonyms", "vocabulary"],
};

export const g3EnglishAntonymsQuestions: PrepQuestion[] = [...SET_A, ...SET_B];
