import type { ChapterDef, PrepQuestion } from "../types";

/** Add & Subtract - authored SOF-style content (original). */

const SET_A: PrepQuestion[] = [
  {
    id: "g3-maths-addsub-a-q01",
    prompt: "What is 234 + 152?",
    options: [
      { id: "a", text: "386" },
      { id: "b", text: "376" },
      { id: "c", text: "396" },
      { id: "d", text: "284" },
    ],
    answerId: "a",
    explanation: "Add ones: 4 + 2 = 6. Add tens: 3 + 5 = 8. Add hundreds: 2 + 1 = 3. So 234 + 152 = 386.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q02",
    prompt: "What is 47 + 38?",
    options: [
      { id: "a", text: "75" },
      { id: "b", text: "85" },
      { id: "c", text: "95" },
      { id: "d", text: "70" },
    ],
    answerId: "b",
    explanation: "Ones: 7 + 8 = 15 → write 5, carry 1 ten. Tens: 4 + 3 + 1 = 8. So 47 + 38 = 85.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q03",
    prompt: "What is 256 + 178?",
    options: [
      { id: "a", text: "424" },
      { id: "b", text: "434" },
      { id: "c", text: "324" },
      { id: "d", text: "444" },
    ],
    answerId: "b",
    explanation: "Ones: 6 + 8 = 14 → write 4, carry 1. Tens: 5 + 7 + 1 = 13 → write 3, carry 1. Hundreds: 2 + 1 + 1 = 4. So 434.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q04",
    prompt: "What is 586 − 243?",
    options: [
      { id: "a", text: "343" },
      { id: "b", text: "333" },
      { id: "c", text: "353" },
      { id: "d", text: "243" },
    ],
    answerId: "a",
    explanation: "Ones: 6 − 3 = 3. Tens: 8 − 4 = 4. Hundreds: 5 − 2 = 3. So 586 − 243 = 343.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q05",
    prompt: "What is 52 − 28?",
    options: [
      { id: "a", text: "34" },
      { id: "b", text: "24" },
      { id: "c", text: "30" },
      { id: "d", text: "14" },
    ],
    answerId: "b",
    explanation: "Ones: you cannot take 8 from 2, so borrow 1 ten. 12 − 8 = 4. Tens: 4 − 2 = 2. So 52 − 28 = 24.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q06",
    prompt: "What is 400 − 176?",
    options: [
      { id: "a", text: "234" },
      { id: "b", text: "224" },
      { id: "c", text: "324" },
      { id: "d", text: "276" },
    ],
    answerId: "b",
    explanation: "Borrow across the zeros: 400 − 176 = 224. Check: 224 + 176 = 400.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q07",
    prompt: "Aman has ₹85. He earns ₹47 more helping at the shop. How many rupees does he have now?",
    options: [
      { id: "a", text: "₹122" },
      { id: "b", text: "₹132" },
      { id: "c", text: "₹142" },
      { id: "d", text: "₹38" },
    ],
    answerId: "b",
    explanation: "85 + 47 = 132, so Aman has ₹132.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q08",
    prompt: "In a cricket match, Meera scores 124 runs and Kabir scores 98 runs. How many runs did they score together?",
    options: [
      { id: "a", text: "212" },
      { id: "b", text: "222" },
      { id: "c", text: "232" },
      { id: "d", text: "26" },
    ],
    answerId: "b",
    explanation: "124 + 98 = 222 runs in all.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q09",
    prompt: "345 + ___ = 500. What number fills the blank?",
    options: [
      { id: "a", text: "155" },
      { id: "b", text: "145" },
      { id: "c", text: "165" },
      { id: "d", text: "255" },
    ],
    answerId: "a",
    explanation: "500 − 345 = 155, so 345 + 155 = 500.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q10",
    prompt: "720 − ___ = 385. What number fills the blank?",
    options: [
      { id: "a", text: "335" },
      { id: "b", text: "345" },
      { id: "c", text: "325" },
      { id: "d", text: "435" },
    ],
    answerId: "a",
    explanation: "720 − 385 = 335, so the missing number is 335.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q11",
    prompt: "Riya subtracts 91 − 47 and gets 44. How can she check her answer?",
    options: [
      { id: "a", text: "44 − 47" },
      { id: "b", text: "44 + 47" },
      { id: "c", text: "91 + 47" },
      { id: "d", text: "91 − 44" },
    ],
    answerId: "b",
    explanation: "Addition undoes subtraction: 44 + 47 = 91, so her answer checks out.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q12",
    prompt: "Which is the best estimate for 198 + 203?",
    options: [
      { id: "a", text: "300" },
      { id: "b", text: "400" },
      { id: "c", text: "500" },
      { id: "d", text: "200" },
    ],
    answerId: "b",
    explanation: "198 is about 200 and 203 is about 200, so 200 + 200 = 400.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q13",
    prompt: "What is 125 + 230 + 145?",
    options: [
      { id: "a", text: "490" },
      { id: "b", text: "500" },
      { id: "c", text: "510" },
      { id: "d", text: "400" },
    ],
    answerId: "b",
    explanation: "125 + 230 = 355, then 355 + 145 = 500.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q14",
    prompt: "Arjun wrote 63 + 28 = 81. What is the correct sum?",
    options: [
      { id: "a", text: "81" },
      { id: "b", text: "91" },
      { id: "c", text: "85" },
      { id: "d", text: "101" },
    ],
    answerId: "b",
    explanation: "Ones: 3 + 8 = 11 → write 1, carry 1. Tens: 6 + 2 + 1 = 9. The correct sum is 91.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q15",
    prompt: "A school cupboard has 56 notebooks. The teacher gives out 29. How many notebooks are left?",
    options: [
      { id: "a", text: "27" },
      { id: "b", text: "37" },
      { id: "c", text: "85" },
      { id: "d", text: "25" },
    ],
    answerId: "a",
    explanation: "56 − 29 = 27 notebooks left.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q16",
    prompt: "What is 76 + 45?",
    options: [
      { id: "a", text: "111" },
      { id: "b", text: "121" },
      { id: "c", text: "131" },
      { id: "d", text: "101" },
    ],
    answerId: "b",
    explanation: "Ones: 6 + 5 = 11 → write 1, carry 1. Tens: 7 + 4 + 1 = 12. So 76 + 45 = 121.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q17",
    prompt: "What is 305 − 128?",
    options: [
      { id: "a", text: "187" },
      { id: "b", text: "177" },
      { id: "c", text: "227" },
      { id: "d", text: "183" },
    ],
    answerId: "b",
    explanation: "Borrow to subtract ones and tens: 305 − 128 = 177. Check: 177 + 128 = 305.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q18",
    prompt: "If 8 + 7 = 15, which of these is also true?",
    options: [
      { id: "a", text: "15 − 8 = 7" },
      { id: "b", text: "15 + 8 = 7" },
      { id: "c", text: "8 − 7 = 15" },
      { id: "d", text: "7 − 15 = 8" },
    ],
    answerId: "a",
    explanation: "Addition and subtraction are partners: 8 + 7 = 15 means 15 − 8 = 7 (and 15 − 7 = 8).",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q19",
    prompt: "Which sum is greater: 199 + 12 or 200 + 10?",
    options: [
      { id: "a", text: "199 + 12" },
      { id: "b", text: "200 + 10" },
      { id: "c", text: "Both are equal" },
      { id: "d", text: "We cannot tell" },
    ],
    answerId: "a",
    explanation: "199 + 12 = 211 and 200 + 10 = 210, so 199 + 12 is greater.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q20",
    prompt: "Sana pays with a ₹50 note for a pencil box that costs ₹28. How much change should she get?",
    options: [
      { id: "a", text: "₹18" },
      { id: "b", text: "₹22" },
      { id: "c", text: "₹32" },
      { id: "d", text: "₹78" },
    ],
    answerId: "b",
    explanation: "50 − 28 = 22, so Sana gets ₹22 change.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q21",
    prompt: "What is 248 + 100?",
    options: [
      { id: "a", text: "348" },
      { id: "b", text: "258" },
      { id: "c", text: "338" },
      { id: "d", text: "248" },
    ],
    answerId: "a",
    explanation: "Adding 100 increases the hundreds digit by 1: 248 + 100 = 348.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q22",
    prompt: "What is the double of 36?",
    options: [
      { id: "a", text: "62" },
      { id: "b", text: "72" },
      { id: "c", text: "66" },
      { id: "d", text: "70" },
    ],
    answerId: "b",
    explanation: "Double means add a number to itself: 36 + 36 = 72.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q23",
    prompt: "A water tank holds 210 litres. After using 85 litres, how much water is left?",
    options: [
      { id: "a", text: "125 litres" },
      { id: "b", text: "135 litres" },
      { id: "c", text: "295 litres" },
      { id: "d", text: "115 litres" },
    ],
    answerId: "a",
    explanation: "210 − 85 = 125 litres left.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-a-q24",
    prompt: "Tara collects 148 stamps, then gets 76 more, then gives 50 to a friend. How many stamps does she have now?",
    options: [
      { id: "a", text: "174" },
      { id: "b", text: "164" },
      { id: "c", text: "184" },
      { id: "d", text: "224" },
    ],
    answerId: "a",
    explanation: "148 + 76 = 224, then 224 − 50 = 174 stamps.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
];

const SET_B: PrepQuestion[] = [
  {
    id: "g3-maths-addsub-b-q01",
    prompt: "What is 315 + 264?",
    options: [
      { id: "a", text: "579" },
      { id: "b", text: "569" },
      { id: "c", text: "589" },
      { id: "d", text: "415" },
    ],
    answerId: "a",
    explanation: "Ones: 5 + 4 = 9. Tens: 1 + 6 = 7. Hundreds: 3 + 2 = 5. So 315 + 264 = 579.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q02",
    prompt: "What is 59 + 37?",
    options: [
      { id: "a", text: "86" },
      { id: "b", text: "96" },
      { id: "c", text: "106" },
      { id: "d", text: "90" },
    ],
    answerId: "b",
    explanation: "Ones: 9 + 7 = 16 → write 6, carry 1. Tens: 5 + 3 + 1 = 9. So 59 + 37 = 96.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q03",
    prompt: "What is 387 + 246?",
    options: [
      { id: "a", text: "623" },
      { id: "b", text: "633" },
      { id: "c", text: "643" },
      { id: "d", text: "533" },
    ],
    answerId: "b",
    explanation: "Ones: 7 + 6 = 13 → write 3, carry 1. Tens: 8 + 4 + 1 = 13 → write 3, carry 1. Hundreds: 3 + 2 + 1 = 6. So 633.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q04",
    prompt: "What is 749 − 325?",
    options: [
      { id: "a", text: "424" },
      { id: "b", text: "414" },
      { id: "c", text: "434" },
      { id: "d", text: "324" },
    ],
    answerId: "a",
    explanation: "Ones: 9 − 5 = 4. Tens: 4 − 2 = 2. Hundreds: 7 − 3 = 4. So 749 − 325 = 424.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q05",
    prompt: "What is 81 − 46?",
    options: [
      { id: "a", text: "45" },
      { id: "b", text: "35" },
      { id: "c", text: "25" },
      { id: "d", text: "55" },
    ],
    answerId: "b",
    explanation: "Ones: borrow 1 ten → 11 − 6 = 5. Tens: 7 − 4 = 3. So 81 − 46 = 35.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q06",
    prompt: "What is 500 − 267?",
    options: [
      { id: "a", text: "243" },
      { id: "b", text: "233" },
      { id: "c", text: "333" },
      { id: "d", text: "267" },
    ],
    answerId: "b",
    explanation: "Borrow across the zeros: 500 − 267 = 233. Check: 233 + 267 = 500.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q07",
    prompt: "Neha saves ₹120. Her grandmother gives her ₹85 more. How much money does Neha have now?",
    options: [
      { id: "a", text: "₹195" },
      { id: "b", text: "₹205" },
      { id: "c", text: "₹215" },
      { id: "d", text: "₹35" },
    ],
    answerId: "b",
    explanation: "120 + 85 = 205, so Neha has ₹205.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q08",
    prompt: "Two teams score 156 and 189 points in a school sports day. What is their total score?",
    options: [
      { id: "a", text: "335" },
      { id: "b", text: "345" },
      { id: "c", text: "355" },
      { id: "d", text: "33" },
    ],
    answerId: "b",
    explanation: "156 + 189 = 345 points in all.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q09",
    prompt: "268 + ___ = 400. What number fills the blank?",
    options: [
      { id: "a", text: "132" },
      { id: "b", text: "142" },
      { id: "c", text: "122" },
      { id: "d", text: "168" },
    ],
    answerId: "a",
    explanation: "400 − 268 = 132, so 268 + 132 = 400.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q10",
    prompt: "605 − ___ = 278. What number fills the blank?",
    options: [
      { id: "a", text: "327" },
      { id: "b", text: "337" },
      { id: "c", text: "317" },
      { id: "d", text: "427" },
    ],
    answerId: "a",
    explanation: "605 − 278 = 327, so the missing number is 327.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q11",
    prompt: "Dev subtracts 83 − 39 and gets 44. Which sum checks his answer?",
    options: [
      { id: "a", text: "44 − 39" },
      { id: "b", text: "44 + 39" },
      { id: "c", text: "83 + 39" },
      { id: "d", text: "83 − 44" },
    ],
    answerId: "b",
    explanation: "44 + 39 = 83, so addition checks the subtraction.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q12",
    prompt: "Which is the best estimate for 297 + 304?",
    options: [
      { id: "a", text: "500" },
      { id: "b", text: "600" },
      { id: "c", text: "700" },
      { id: "d", text: "400" },
    ],
    answerId: "b",
    explanation: "297 is about 300 and 304 is about 300, so 300 + 300 = 600.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q13",
    prompt: "What is 214 + 186 + 100?",
    options: [
      { id: "a", text: "490" },
      { id: "b", text: "500" },
      { id: "c", text: "510" },
      { id: "d", text: "400" },
    ],
    answerId: "b",
    explanation: "214 + 186 = 400, then 400 + 100 = 500.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q14",
    prompt: "Leela wrote 74 + 19 = 83. What is the correct sum?",
    options: [
      { id: "a", text: "83" },
      { id: "b", text: "93" },
      { id: "c", text: "85" },
      { id: "d", text: "103" },
    ],
    answerId: "b",
    explanation: "Ones: 4 + 9 = 13 → write 3, carry 1. Tens: 7 + 1 + 1 = 9. The correct sum is 93.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q15",
    prompt: "A box has 92 pencils. Children take 47 pencils. How many pencils are left in the box?",
    options: [
      { id: "a", text: "45" },
      { id: "b", text: "55" },
      { id: "c", text: "139" },
      { id: "d", text: "35" },
    ],
    answerId: "a",
    explanation: "92 − 47 = 45 pencils left.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q16",
    prompt: "What is 89 + 56?",
    options: [
      { id: "a", text: "135" },
      { id: "b", text: "145" },
      { id: "c", text: "155" },
      { id: "d", text: "125" },
    ],
    answerId: "b",
    explanation: "Ones: 9 + 6 = 15 → write 5, carry 1. Tens: 8 + 5 + 1 = 14. So 89 + 56 = 145.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q17",
    prompt: "What is 412 − 159?",
    options: [
      { id: "a", text: "263" },
      { id: "b", text: "253" },
      { id: "c", text: "353" },
      { id: "d", text: "243" },
    ],
    answerId: "b",
    explanation: "Borrow as needed: 412 − 159 = 253. Check: 253 + 159 = 412.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q18",
    prompt: "If 9 + 6 = 15, which of these is also true?",
    options: [
      { id: "a", text: "15 − 9 = 6" },
      { id: "b", text: "15 + 9 = 6" },
      { id: "c", text: "9 − 6 = 15" },
      { id: "d", text: "6 − 15 = 9" },
    ],
    answerId: "a",
    explanation: "9 + 6 = 15 means 15 − 9 = 6 (and 15 − 6 = 9).",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q19",
    prompt: "Which sum is greater: 298 + 15 or 300 + 12?",
    options: [
      { id: "a", text: "298 + 15" },
      { id: "b", text: "300 + 12" },
      { id: "c", text: "Both are equal" },
      { id: "d", text: "We cannot tell" },
    ],
    answerId: "a",
    explanation: "298 + 15 = 313 and 300 + 12 = 312, so 298 + 15 is greater.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q20",
    prompt: "Kabir pays with a ₹100 note for a book that costs ₹64. How much change should he get?",
    options: [
      { id: "a", text: "₹36" },
      { id: "b", text: "₹46" },
      { id: "c", text: "₹26" },
      { id: "d", text: "₹164" },
    ],
    answerId: "a",
    explanation: "100 − 64 = 36, so Kabir gets ₹36 change.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q21",
    prompt: "What is 367 + 200?",
    options: [
      { id: "a", text: "567" },
      { id: "b", text: "387" },
      { id: "c", text: "557" },
      { id: "d", text: "367" },
    ],
    answerId: "a",
    explanation: "Adding 200 increases the hundreds digit by 2: 367 + 200 = 567.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q22",
    prompt: "What is the double of 45?",
    options: [
      { id: "a", text: "80" },
      { id: "b", text: "90" },
      { id: "c", text: "85" },
      { id: "d", text: "95" },
    ],
    answerId: "b",
    explanation: "Double means add a number to itself: 45 + 45 = 90.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q23",
    prompt: "A sack has 350 kg of rice. The shopkeeper sells 175 kg. How much rice is left?",
    options: [
      { id: "a", text: "175 kg" },
      { id: "b", text: "185 kg" },
      { id: "c", text: "525 kg" },
      { id: "d", text: "165 kg" },
    ],
    answerId: "a",
    explanation: "350 − 175 = 175 kg left.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-addsub-b-q24",
    prompt: "Rohan has 205 marbles. He wins 88 more, then gives 40 to his sister. How many marbles does he have now?",
    options: [
      { id: "a", text: "253" },
      { id: "b", text: "243" },
      { id: "c", text: "263" },
      { id: "d", text: "293" },
    ],
    answerId: "a",
    explanation: "205 + 88 = 293, then 293 − 40 = 253 marbles.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
];

const lesson: ChapterDef["lesson"] = [
  {
    id: "h",
    type: "hook",
    emoji: "➕",
    title: "Join & take away",
    body: [
      "Adding joins groups. Subtracting takes some away.",
      "We'll practise carrying, borrowing and clever checks.",
      "Lesson is optional — jump to a set anytime.",
    ],
    cta: "Let's go!",
    visual: "place-value",
    speak: "Adding joins groups. Subtracting takes some away. We'll practise carrying, borrowing and checks.",
  },
  {
    id: "r1",
    type: "reveal",
    title: "Place under place",
    lead: "Tap each card.",
    visual: "place-value",
    speak: "Line up ones under ones, tens under tens, hundreds under hundreds. Carry when ones make ten or more. Borrow a ten when ones are too small.",
    cards: [
      { label: "Line up", reveal: "Ones under ones · tens under tens · hundreds under hundreds", emoji: "📐" },
      { label: "Carry", reveal: "Ones ≥ 10 → write ones digit, carry 1 ten", emoji: "📦" },
      { label: "Borrow", reveal: "Ones too small → borrow 1 ten = 10 ones", emoji: "🔁" },
      { label: "Check", reveal: "Subtract? Add to check. Estimate first to spot wild answers", emoji: "✅" },
    ],
  },
  {
    id: "d1",
    type: "demo",
    title: "Add with a carry: 47 + 38",
    visual: "place-value",
    speak: "Ones: seven plus eight is fifteen. Write five, carry one ten. Tens: four plus three plus one is eight. Forty-seven plus thirty-eight is eighty-five.",
    steps: [
      "Ones: 7 + 8 = 15 → write 5, carry 1 ten",
      "Tens: 4 + 3 + 1 = 8",
      "Answer: 85",
    ],
    punchline: "Overflow ones become a carried ten.",
  },
  {
    id: "t1",
    type: "try",
    title: "Your turn",
    prompt: "What is 56 + 27?",
    options: [
      { id: "a", text: "73" },
      { id: "b", text: "83" },
      { id: "c", text: "93" },
      { id: "d", text: "70" },
    ],
    answerId: "b",
    why: "Ones: 6 + 7 = 13 → write 3, carry 1. Tens: 5 + 2 + 1 = 8 → 83.",
    visual: "place-value",
    speak: "What is fifty-six plus twenty-seven?",
  },
  {
    id: "d2",
    type: "demo",
    title: "Borrow & check: 52 − 28",
    visual: "number-line",
    speak: "Ones are too small, so borrow one ten. Twelve minus eight is four. Tens: four minus two is two. Check: twenty-four plus twenty-eight is fifty-two.",
    steps: [
      "Ones: borrow → 12 − 8 = 4",
      "Tens: 4 − 2 = 2 → answer 24",
      "Check: 24 + 28 = 52",
    ],
    punchline: "Borrow to subtract; add to check.",
  },
  {
    id: "c1",
    type: "check",
    title: "Quick check",
    visual: "number-line",
    speak: "Sana pays with a fifty-rupee note for a pencil box that costs twenty-eight rupees. How much change?",
    question: {
      id: "g3-addsub-check",
      prompt: "Sana pays with ₹50 for a pencil box that costs ₹28. How much change?",
      options: [
        { id: "a", text: "₹18" },
        { id: "b", text: "₹22" },
        { id: "c", text: "₹32" },
        { id: "d", text: "₹78" },
      ],
      answerId: "b",
      explanation: "50 − 28 = 22, so the change is ₹22.",
      hints: ["Change means subtract the price from the money given.", "50 minus 28."],
    },
  },
  {
    id: "w",
    type: "wrap",
    emoji: "⭐",
    title: "Add-sub star!",
    bullets: [
      "Line up places; carry and borrow carefully",
      "Check subtraction by adding",
      "Estimate to catch wild answers; use ₹ for money",
      "Set A and Set B ready — 24 MCQs each",
    ],
    cta: "Back to chapter",
    speak: "You can add, subtract, carry, borrow and check. Set A and Set B are ready.",
  },
];

export const g3MathsAddSubtract: ChapterDef = {
  id: "add-sub",
  title: "Add & Subtract",
  emoji: "➕",
  blurb: "Carry, borrow & check",
  lesson,
  sets: [
    {
      id: "set-a",
      title: "Set A",
      questionCount: SET_A.length,
      topic: "add-sub",
      questions: SET_A,
    },
    {
      id: "set-b",
      title: "Set B",
      questionCount: SET_B.length,
      topic: "add-sub",
      questions: SET_B,
    },
  ],
  paperTopics: ["add-sub", "place-value"],
};

export const g3MathsAddSubtractQuestions: PrepQuestion[] = [...SET_A, ...SET_B];

