import type { ChapterDef, PrepQuestion } from "../types";

/** Multiply Basics - authored olympiad-style content (original). */

const SET_A: PrepQuestion[] = [
  {
    id: "g3-maths-multiply-a-q01",
    prompt: "What is 6 × 4?",
    options: [
      { id: "a", text: "24" },
      { id: "b", text: "10" },
      { id: "c", text: "28" },
      { id: "d", text: "20" },
    ],
    answerId: "a",
    explanation: "6 groups of 4 make 24. Or skip-count: 4, 8, 12, 16, 20, 24.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q02",
    prompt: "Which multiplication matches 5 + 5 + 5 + 5?",
    options: [
      { id: "a", text: "5 × 3" },
      { id: "b", text: "5 × 4" },
      { id: "c", text: "4 × 4" },
      { id: "d", text: "5 + 4" },
    ],
    answerId: "b",
    explanation: "Five is added four times, so 5 × 4 = 20. Multiplication is a short way to write repeated addition.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q03",
    prompt: "A tray has 3 rows of 7 ladoos. How many ladoos are there in all?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "21" },
      { id: "c", text: "24" },
      { id: "d", text: "14" },
    ],
    answerId: "b",
    explanation: "An array of 3 rows with 7 in each row is 3 × 7 = 21 ladoos.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q04",
    prompt: "Which equals 8 × 3?",
    options: [
      { id: "a", text: "8 + 3" },
      { id: "b", text: "3 × 8" },
      { id: "c", text: "8 × 4" },
      { id: "d", text: "8 − 3" },
    ],
    answerId: "b",
    explanation: "Multiplication can swap order: 8 × 3 = 3 × 8 = 24.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q05",
    prompt: "What is 9 × 1?",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "9" },
      { id: "d", text: "10" },
    ],
    answerId: "c",
    explanation: "Any number times 1 stays the same: 9 × 1 = 9.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q06",
    prompt: "What is 7 × 0?",
    options: [
      { id: "a", text: "7" },
      { id: "b", text: "0" },
      { id: "c", text: "1" },
      { id: "d", text: "70" },
    ],
    answerId: "b",
    explanation: "Any number times 0 is 0. Seven groups of nothing is nothing.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q07",
    prompt: "Meera packs 4 tiffin boxes with 6 idlis in each. How many idlis does she pack?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "20" },
      { id: "c", text: "24" },
      { id: "d", text: "28" },
    ],
    answerId: "c",
    explanation: "4 groups of 6 idlis → 4 × 6 = 24 idlis.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q08",
    prompt: "A notebook costs ₹8. How much do 5 notebooks cost?",
    options: [
      { id: "a", text: "₹13" },
      { id: "b", text: "₹35" },
      { id: "c", text: "₹40" },
      { id: "d", text: "₹48" },
    ],
    answerId: "c",
    explanation: "5 × ₹8 = ₹40.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q09",
    prompt: "7 × ___ = 56. What number fills the blank?",
    options: [
      { id: "a", text: "6" },
      { id: "b", text: "7" },
      { id: "c", text: "8" },
      { id: "d", text: "9" },
    ],
    answerId: "c",
    explanation: "7 × 8 = 56, so the missing factor is 8.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q10",
    prompt: "Skip-count by 5 five times: 5, 10, 15, 20, 25. What multiplication is this?",
    options: [
      { id: "a", text: "5 × 4" },
      { id: "b", text: "5 × 5" },
      { id: "c", text: "5 + 5" },
      { id: "d", text: "10 × 5" },
    ],
    answerId: "b",
    explanation: "Five jumps of 5 land on 25, so 5 × 5 = 25.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q11",
    prompt: "A school garden has 4 rows of 9 marigold plants. How many plants are there?",
    options: [
      { id: "a", text: "13" },
      { id: "b", text: "32" },
      { id: "c", text: "36" },
      { id: "d", text: "45" },
    ],
    answerId: "c",
    explanation: "4 × 9 = 36 marigold plants.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q12",
    prompt: "Which product is greater: 6 × 7 or 5 × 9?",
    options: [
      { id: "a", text: "6 × 7" },
      { id: "b", text: "5 × 9" },
      { id: "c", text: "Both are equal" },
      { id: "d", text: "We cannot tell" },
    ],
    answerId: "b",
    explanation: "6 × 7 = 42 and 5 × 9 = 45, so 5 × 9 is greater.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q13",
    prompt: "What is 8 × 6?",
    options: [
      { id: "a", text: "42" },
      { id: "b", text: "48" },
      { id: "c", text: "54" },
      { id: "d", text: "14" },
    ],
    answerId: "b",
    explanation: "8 × 6 = 48. You can also think 8 × 5 = 40, then add one more 8 → 48.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q14",
    prompt: "Arjun wrote 4 × 7 = 24. What is the correct product?",
    options: [
      { id: "a", text: "24" },
      { id: "b", text: "28" },
      { id: "c", text: "32" },
      { id: "d", text: "11" },
    ],
    answerId: "b",
    explanation: "4 × 7 = 28. Arjun may have done 4 × 6 by mistake.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q15",
    prompt: "Kabir buys 6 bags of mangoes. Each bag has 5 mangoes. How many mangoes in all?",
    options: [
      { id: "a", text: "11" },
      { id: "b", text: "25" },
      { id: "c", text: "30" },
      { id: "d", text: "35" },
    ],
    answerId: "c",
    explanation: "6 × 5 = 30 mangoes.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q16",
    prompt: "What is the double of 9, written as a multiplication?",
    options: [
      { id: "a", text: "9 + 2" },
      { id: "b", text: "9 × 2" },
      { id: "c", text: "9 × 9" },
      { id: "d", text: "2 × 2" },
    ],
    answerId: "b",
    explanation: "Double means two groups of the number: 9 × 2 = 18.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q17",
    prompt: "Three friends each buy 4 pencils. How many pencils do they buy together?",
    options: [
      { id: "a", text: "7" },
      { id: "b", text: "12" },
      { id: "c", text: "14" },
      { id: "d", text: "16" },
    ],
    answerId: "b",
    explanation: "3 × 4 = 12 pencils in all.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q18",
    prompt: "If 6 × 5 = 30, which of these is also true?",
    options: [
      { id: "a", text: "5 × 6 = 30" },
      { id: "b", text: "6 + 5 = 30" },
      { id: "c", text: "30 × 6 = 5" },
      { id: "d", text: "6 − 5 = 30" },
    ],
    answerId: "a",
    explanation: "Order can swap in multiplication: 6 × 5 = 5 × 6 = 30.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q19",
    prompt: "Which is the best estimate for 19 × 3?",
    options: [
      { id: "a", text: "30" },
      { id: "b", text: "40" },
      { id: "c", text: "60" },
      { id: "d", text: "90" },
    ],
    answerId: "c",
    explanation: "19 is about 20, and 20 × 3 = 60. (Exact answer is 57, close to 60.)",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q20",
    prompt: "A bus ticket costs ₹12. How much do 3 tickets cost?",
    options: [
      { id: "a", text: "₹15" },
      { id: "b", text: "₹24" },
      { id: "c", text: "₹36" },
      { id: "d", text: "₹48" },
    ],
    answerId: "c",
    explanation: "3 × ₹12 = ₹36.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q21",
    prompt: "What is 10 × 7?",
    options: [
      { id: "a", text: "17" },
      { id: "b", text: "70" },
      { id: "c", text: "77" },
      { id: "d", text: "700" },
    ],
    answerId: "b",
    explanation: "Multiplying by 10 puts a zero after the number: 10 × 7 = 70.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q22",
    prompt: "___ × 4 = 36. What number fills the blank?",
    options: [
      { id: "a", text: "6" },
      { id: "b", text: "8" },
      { id: "c", text: "9" },
      { id: "d", text: "12" },
    ],
    answerId: "c",
    explanation: "9 × 4 = 36, so the missing factor is 9.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q23",
    prompt: "At a sweet shop, one ladoo costs ₹5. How much do 8 ladoos cost?",
    options: [
      { id: "a", text: "₹13" },
      { id: "b", text: "₹35" },
      { id: "c", text: "₹40" },
      { id: "d", text: "₹45" },
    ],
    answerId: "c",
    explanation: "8 × ₹5 = ₹40.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-a-q24",
    prompt: "Sana has 3 packs of crayons with 6 crayons in each pack. She gives 4 crayons to a friend. How many crayons does she have left?",
    options: [
      { id: "a", text: "14" },
      { id: "b", text: "18" },
      { id: "c", text: "22" },
      { id: "d", text: "10" },
    ],
    answerId: "a",
    explanation: "First 3 × 6 = 18 crayons, then 18 − 4 = 14 left.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
];

const SET_B: PrepQuestion[] = [
  {
    id: "g3-maths-multiply-b-q01",
    prompt: "What is 7 × 3?",
    options: [
      { id: "a", text: "21" },
      { id: "b", text: "10" },
      { id: "c", text: "24" },
      { id: "d", text: "28" },
    ],
    answerId: "a",
    explanation: "7 groups of 3 make 21. Or skip-count: 3, 6, 9, 12, 15, 18, 21.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q02",
    prompt: "Which multiplication matches 4 + 4 + 4 + 4 + 4 + 4?",
    options: [
      { id: "a", text: "4 × 5" },
      { id: "b", text: "4 × 6" },
      { id: "c", text: "6 × 6" },
      { id: "d", text: "4 + 6" },
    ],
    answerId: "b",
    explanation: "Four is added six times, so 4 × 6 = 24.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q03",
    prompt: "A stamp sheet has 5 rows of 4 stamps. How many stamps are there?",
    options: [
      { id: "a", text: "9" },
      { id: "b", text: "16" },
      { id: "c", text: "20" },
      { id: "d", text: "24" },
    ],
    answerId: "c",
    explanation: "5 × 4 = 20 stamps in the array.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q04",
    prompt: "Which equals 9 × 2?",
    options: [
      { id: "a", text: "9 + 2" },
      { id: "b", text: "2 × 9" },
      { id: "c", text: "9 × 3" },
      { id: "d", text: "9 − 2" },
    ],
    answerId: "b",
    explanation: "Multiplication can swap order: 9 × 2 = 2 × 9 = 18.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q05",
    prompt: "What is 8 × 1?",
    options: [
      { id: "a", text: "0" },
      { id: "b", text: "1" },
      { id: "c", text: "8" },
      { id: "d", text: "9" },
    ],
    answerId: "c",
    explanation: "Any number times 1 stays the same: 8 × 1 = 8.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q06",
    prompt: "What is 5 × 0?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "0" },
      { id: "c", text: "1" },
      { id: "d", text: "50" },
    ],
    answerId: "b",
    explanation: "Any number times 0 is 0.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q07",
    prompt: "Rohan fills 3 thalis with 8 puris on each. How many puris does he use?",
    options: [
      { id: "a", text: "11" },
      { id: "b", text: "21" },
      { id: "c", text: "24" },
      { id: "d", text: "32" },
    ],
    answerId: "c",
    explanation: "3 groups of 8 puris → 3 × 8 = 24 puris.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q08",
    prompt: "A pencil costs ₹9. How much do 6 pencils cost?",
    options: [
      { id: "a", text: "₹15" },
      { id: "b", text: "₹45" },
      { id: "c", text: "₹54" },
      { id: "d", text: "₹63" },
    ],
    answerId: "c",
    explanation: "6 × ₹9 = ₹54.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q09",
    prompt: "6 × ___ = 48. What number fills the blank?",
    options: [
      { id: "a", text: "6" },
      { id: "b", text: "7" },
      { id: "c", text: "8" },
      { id: "d", text: "9" },
    ],
    answerId: "c",
    explanation: "6 × 8 = 48, so the missing factor is 8.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q10",
    prompt: "Skip-count by 4 four times: 4, 8, 12, 16. What multiplication is this?",
    options: [
      { id: "a", text: "4 × 3" },
      { id: "b", text: "4 × 4" },
      { id: "c", text: "4 + 4" },
      { id: "d", text: "8 × 4" },
    ],
    answerId: "b",
    explanation: "Four jumps of 4 land on 16, so 4 × 4 = 16.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q11",
    prompt: "A classroom has 3 rows of 8 desks. How many desks are there?",
    options: [
      { id: "a", text: "11" },
      { id: "b", text: "16" },
      { id: "c", text: "24" },
      { id: "d", text: "32" },
    ],
    answerId: "c",
    explanation: "3 × 8 = 24 desks.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q12",
    prompt: "Which product is greater: 7 × 8 or 6 × 9?",
    options: [
      { id: "a", text: "7 × 8" },
      { id: "b", text: "6 × 9" },
      { id: "c", text: "Both are equal" },
      { id: "d", text: "We cannot tell" },
    ],
    answerId: "a",
    explanation: "7 × 8 = 56 and 6 × 9 = 54, so 7 × 8 is greater.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q13",
    prompt: "What is 9 × 5?",
    options: [
      { id: "a", text: "40" },
      { id: "b", text: "45" },
      { id: "c", text: "50" },
      { id: "d", text: "14" },
    ],
    answerId: "b",
    explanation: "9 × 5 = 45. You can also think 10 × 5 = 50, then subtract one 5 → 45.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q14",
    prompt: "Leela wrote 5 × 8 = 35. What is the correct product?",
    options: [
      { id: "a", text: "35" },
      { id: "b", text: "40" },
      { id: "c", text: "45" },
      { id: "d", text: "13" },
    ],
    answerId: "b",
    explanation: "5 × 8 = 40. Leela may have done 5 × 7 by mistake.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q15",
    prompt: "Ananya buys 7 packets of biscuits. Each packet has 4 biscuits. How many biscuits in all?",
    options: [
      { id: "a", text: "11" },
      { id: "b", text: "24" },
      { id: "c", text: "28" },
      { id: "d", text: "32" },
    ],
    answerId: "c",
    explanation: "7 × 4 = 28 biscuits.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q16",
    prompt: "What is the double of 8, written as a multiplication?",
    options: [
      { id: "a", text: "8 + 2" },
      { id: "b", text: "8 × 2" },
      { id: "c", text: "8 × 8" },
      { id: "d", text: "2 × 2" },
    ],
    answerId: "b",
    explanation: "Double means two groups of the number: 8 × 2 = 16.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q17",
    prompt: "Four children each plant 5 saplings on Van Mahotsav. How many saplings do they plant together?",
    options: [
      { id: "a", text: "9" },
      { id: "b", text: "15" },
      { id: "c", text: "20" },
      { id: "d", text: "25" },
    ],
    answerId: "c",
    explanation: "4 × 5 = 20 saplings in all.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q18",
    prompt: "If 7 × 4 = 28, which of these is also true?",
    options: [
      { id: "a", text: "4 × 7 = 28" },
      { id: "b", text: "7 + 4 = 28" },
      { id: "c", text: "28 × 7 = 4" },
      { id: "d", text: "7 − 4 = 28" },
    ],
    answerId: "a",
    explanation: "Order can swap in multiplication: 7 × 4 = 4 × 7 = 28.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q19",
    prompt: "Which is the best estimate for 21 × 4?",
    options: [
      { id: "a", text: "40" },
      { id: "b", text: "60" },
      { id: "c", text: "80" },
      { id: "d", text: "100" },
    ],
    answerId: "c",
    explanation: "21 is about 20, and 20 × 4 = 80. (Exact answer is 84, close to 80.)",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q20",
    prompt: "A movie ticket costs ₹15. How much do 2 tickets cost?",
    options: [
      { id: "a", text: "₹17" },
      { id: "b", text: "₹25" },
      { id: "c", text: "₹30" },
      { id: "d", text: "₹45" },
    ],
    answerId: "c",
    explanation: "2 × ₹15 = ₹30.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q21",
    prompt: "What is 10 × 8?",
    options: [
      { id: "a", text: "18" },
      { id: "b", text: "80" },
      { id: "c", text: "88" },
      { id: "d", text: "800" },
    ],
    answerId: "b",
    explanation: "Multiplying by 10 puts a zero after the number: 10 × 8 = 80.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q22",
    prompt: "___ × 7 = 42. What number fills the blank?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "6" },
      { id: "c", text: "7" },
      { id: "d", text: "8" },
    ],
    answerId: "b",
    explanation: "6 × 7 = 42, so the missing factor is 6.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q23",
    prompt: "At a kirana shop, one packet of chips costs ₹4. How much do 9 packets cost?",
    options: [
      { id: "a", text: "₹13" },
      { id: "b", text: "₹32" },
      { id: "c", text: "₹36" },
      { id: "d", text: "₹40" },
    ],
    answerId: "c",
    explanation: "9 × ₹4 = ₹36.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
  {
    id: "g3-maths-multiply-b-q24",
    prompt: "Dev has 5 boxes of erasers with 7 erasers in each box. He gives 6 erasers to his sister. How many erasers does he have left?",
    options: [
      { id: "a", text: "29" },
      { id: "b", text: "35" },
      { id: "c", text: "41" },
      { id: "d", text: "23" },
    ],
    answerId: "a",
    explanation: "First 5 × 7 = 35 erasers, then 35 − 6 = 29 left.",
    hints: ["Read carefully.", "Eliminate impossible options first."],
  },
];

const lesson: ChapterDef["lesson"] = [
  {
    id: "h",
    type: "hook",
    emoji: "✖️",
    title: "Equal groups",
    body: [
      "Multiplying is a fast way to join equal groups.",
      "We'll use arrays, times facts and rupee stories.",
      "Lesson is optional — jump to a set anytime.",
    ],
    cta: "Let's go!",
    visual: "place-value",
    speak: "Multiplying joins equal groups fast. We'll use arrays, times facts and rupee stories.",
  },
  {
    id: "r1",
    type: "reveal",
    title: "Multiply toolkit",
    lead: "Tap each card.",
    visual: "place-value",
    speak: "Repeated addition becomes multiply. Arrays are rows times columns. Order can swap. Times zero is zero. Times one stays the same.",
    cards: [
      { label: "Equal groups", reveal: "4 groups of 6 → 4 × 6", emoji: "📦" },
      { label: "Array", reveal: "Rows × columns = total", emoji: "🔲" },
      { label: "Swap order", reveal: "3 × 8 = 8 × 3 — same product", emoji: "🔄" },
      { label: "0 and 1", reveal: "× 0 → 0 · × 1 → same number", emoji: "✨" },
    ],
  },
  {
    id: "d1",
    type: "demo",
    title: "Array: 3 rows of 7",
    visual: "place-value",
    speak: "Three rows with seven ladoos in each row. Three times seven is twenty-one.",
    steps: [
      "Count one row: 7",
      "Three equal rows → 3 × 7",
      "Product: 21",
    ],
    punchline: "Rows × items in a row = total.",
  },
  {
    id: "t1",
    type: "try",
    title: "Your turn",
    prompt: "What is 5 × 6?",
    options: [
      { id: "a", text: "11" },
      { id: "b", text: "25" },
      { id: "c", text: "30" },
      { id: "d", text: "35" },
    ],
    answerId: "c",
    why: "5 groups of 6 make 30. Or 5 × 5 = 25, plus one more 5 → 30.",
    visual: "number-line",
    speak: "What is five times six?",
  },
  {
    id: "d2",
    type: "demo",
    title: "Money: 5 notebooks at ₹8",
    visual: "number-line",
    speak: "Each notebook is eight rupees. Five notebooks: five times eight is forty rupees.",
    steps: [
      "Same price each time → multiply",
      "5 × ₹8",
      "Total: ₹40",
    ],
    punchline: "Equal costs → multiply by how many you buy.",
  },
  {
    id: "c1",
    type: "check",
    title: "Quick check",
    visual: "number-line",
    speak: "A bus ticket costs twelve rupees. How much do three tickets cost?",
    question: {
      id: "g3-multiply-check",
      prompt: "A bus ticket costs ₹12. How much do 3 tickets cost?",
      options: [
        { id: "a", text: "₹15" },
        { id: "b", text: "₹24" },
        { id: "c", text: "₹36" },
        { id: "d", text: "₹48" },
      ],
      answerId: "c",
      explanation: "3 × ₹12 = ₹36.",
      hints: ["Same price for each ticket — multiply.", "3 times 12."],
    },
  },
  {
    id: "w",
    type: "wrap",
    emoji: "⭐",
    title: "Multiply star!",
    bullets: [
      "Equal groups and arrays → multiply",
      "Order can swap; ×0 is 0; ×1 stays same",
      "Use times facts; ₹ stories mean multiply the price",
      "Set A and Set B ready — 24 MCQs each",
    ],
    cta: "Back to chapter",
    speak: "You can multiply with groups, arrays and rupee stories. Set A and Set B are ready.",
  },
];

export const g3MathsMultiply: ChapterDef = {
  id: "multiply",
  title: "Multiply Basics",
  emoji: "✖️",
  blurb: "Arrays & times facts",
  lesson,
  sets: [
    {
      id: "set-a",
      title: "Set A",
      questionCount: SET_A.length,
      topic: "multiply-basics",
      questions: SET_A,
    },
    {
      id: "set-b",
      title: "Set B",
      questionCount: SET_B.length,
      topic: "multiply-basics",
      questions: SET_B,
    },
  ],
  paperTopics: ["multiply-basics", "add-sub"],
};

export const g3MathsMultiplyQuestions: PrepQuestion[] = [...SET_A, ...SET_B];
