import type { ChapterDef, PrepQuestion } from "../types";

/** Data Handling - authored SOF-style content (original). */

const SET_A: PrepQuestion[] = [
  {
    id: "g4-maths-data-a-q01",
    prompt: "In a tally chart, one complete tally gate (|||| with a slash) stands for…",
    options: [
      { id: "a", text: "4" },
      { id: "b", text: "5" },
      { id: "c", text: "10" },
      { id: "d", text: "1" },
    ],
    answerId: "b",
    explanation: "A tally gate of five strokes (four upright + one diagonal) means 5.",
    hints: ["Tally marks group by fives.", "Four lines + cross = 5."],
  },
  {
    id: "g4-maths-data-a-q02",
    prompt: "Tally |||| means…",
    options: [
      { id: "a", text: "3" },
      { id: "b", text: "4" },
      { id: "c", text: "5" },
      { id: "d", text: "6" },
    ],
    answerId: "b",
    explanation: "Four upright strokes without a cross mean 4.",
    hints: ["Count the strokes.", "No diagonal yet → still under 5."],
  },
  {
    id: "g4-maths-data-a-q03",
    prompt: "A pictograph uses pictures. If 1 ⚽ = 2 goals, then ⚽⚽⚽ means…",
    options: [
      { id: "a", text: "3 goals" },
      { id: "b", text: "5 goals" },
      { id: "c", text: "6 goals" },
      { id: "d", text: "2 goals" },
    ],
    answerId: "c",
    explanation: "Three footballs × 2 goals each = 6 goals.",
    hints: ["Read the key: what one picture is worth.", "3 × 2."],
  },
  {
    id: "g4-maths-data-a-q04",
    prompt: "In a bar graph, taller bars show…",
    options: [
      { id: "a", text: "Smaller numbers" },
      { id: "b", text: "Larger numbers" },
      { id: "c", text: "Only names" },
      { id: "d", text: "Colours only" },
    ],
    answerId: "b",
    explanation: "Bar height (or length) matches the value — taller means more.",
    hints: ["Compare bar heights.", "Higher bar → bigger count."],
  },
  {
    id: "g4-maths-data-a-q05",
    prompt: "A table shows Class 4A favourite fruits: Mango 12, Banana 8, Apple 5. Which fruit is most popular?",
    options: [
      { id: "a", text: "Banana" },
      { id: "b", text: "Apple" },
      { id: "c", text: "Mango" },
      { id: "d", text: "All equal" },
    ],
    answerId: "c",
    explanation: "12 is the greatest count, so mango is most popular.",
    hints: ["Find the largest number in the table.", "Compare 12, 8 and 5."],
  },
  {
    id: "g4-maths-data-a-q06",
    prompt: "How many children chose banana or apple (from 12, 8, 5)?",
    options: [
      { id: "a", text: "13" },
      { id: "b", text: "20" },
      { id: "c", text: "17" },
      { id: "d", text: "8" },
    ],
    answerId: "a",
    explanation: "8 + 5 = 13 children.",
    hints: ["Add the two counts.", "8 + 5."],
  },
  {
    id: "g4-maths-data-a-q07",
    prompt: "Pictograph key: 1 🌸 = 5 flowers. How many flowers do 🌸🌸🌸🌸 show?",
    options: [
      { id: "a", text: "4" },
      { id: "b", text: "9" },
      { id: "c", text: "20" },
      { id: "d", text: "25" },
    ],
    answerId: "c",
    explanation: "4 pictures × 5 = 20 flowers.",
    hints: ["Multiply number of pictures by the key value.", "4 × 5."],
  },
  {
    id: "g4-maths-data-a-q08",
    prompt: "Which is the best title for a bar graph of students' favourite sports?",
    options: [
      { id: "a", text: "My lunch box" },
      { id: "b", text: "Favourite sports of Class 4" },
      { id: "c", text: "Rainfall in Mumbai" },
      { id: "d", text: "Multiplication tables" },
    ],
    answerId: "b",
    explanation: "The title should match what the graph shows — favourite sports.",
    hints: ["Titles describe the data topic.", "Match graph to wording."],
  },
  {
    id: "g4-maths-data-a-q09",
    prompt: "Tally for 7 is…",
    options: [
      { id: "a", text: "||||" },
      { id: "b", text: "|||| |||" },
      { id: "c", text: "|||| ||" },
      { id: "d", text: "|||" },
    ],
    answerId: "c",
    explanation: "One gate of 5 plus 2 more strokes = 7.",
    hints: ["Make groups of 5, then leftovers.", "5 + 2."],
  },
  {
    id: "g4-maths-data-a-q10",
    prompt: "A bar graph of books read: Riya 6, Arjun 4, Meera 6, Kabir 2. Who read the fewest?",
    options: [
      { id: "a", text: "Riya" },
      { id: "b", text: "Arjun" },
      { id: "c", text: "Meera" },
      { id: "d", text: "Kabir" },
    ],
    answerId: "d",
    explanation: "Kabir's 2 is the smallest value.",
    hints: ["Find the smallest number.", "Compare 6, 4, 6, 2."],
  },
  {
    id: "g4-maths-data-a-q11",
    prompt: "How many books did Riya and Meera read together (6 and 6)?",
    options: [
      { id: "a", text: "6" },
      { id: "b", text: "10" },
      { id: "c", text: "12" },
      { id: "d", text: "8" },
    ],
    answerId: "c",
    explanation: "6 + 6 = 12 books.",
    hints: ["Add the two equal amounts.", "6 + 6."],
  },
  {
    id: "g4-maths-data-a-q12",
    prompt: "In a pictograph, half a picture usually means…",
    options: [
      { id: "a", text: "Twice the key value" },
      { id: "b", text: "Half the key value" },
      { id: "c", text: "Zero" },
      { id: "d", text: "The key value squared" },
    ],
    answerId: "b",
    explanation: "A half symbol stands for half of what one full picture is worth.",
    hints: ["Halves scale the key.", "Half picture → half the value."],
  },
  {
    id: "g4-maths-data-a-q13",
    prompt: "Data means…",
    options: [
      { id: "a", text: "Only drawings" },
      { id: "b", text: "Facts and numbers collected for a purpose" },
      { id: "c", text: "Only tallies" },
      { id: "d", text: "Only bar heights" },
    ],
    answerId: "b",
    explanation: "Data are facts or numbers we collect and organise.",
    hints: ["Think of survey answers and counts.", "Organised facts/numbers."],
  },
  {
    id: "g4-maths-data-a-q14",
    prompt: "Which tool is best to show how many students like each of four hobbies?",
    options: [
      { id: "a", text: "Only a clock" },
      { id: "b", text: "A bar graph or pictograph" },
      { id: "c", text: "A protractor alone" },
      { id: "d", text: "A weighing scale" },
    ],
    answerId: "b",
    explanation: "Bar graphs and pictographs compare counts across categories.",
    hints: ["Categories + counts → graph.", "Bars or pictures work well."],
  },
  {
    id: "g4-maths-data-a-q15",
    prompt: "A tally shows |||| |||| || for cricket fans. How many fans?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "12" },
      { id: "c", text: "7" },
      { id: "d", text: "15" },
    ],
    answerId: "b",
    explanation: "5 + 5 + 2 = 12.",
    hints: ["Each gate is 5; count leftovers.", "5 + 5 + 2."],
  },
  {
    id: "g4-maths-data-a-q16",
    prompt: "Table: Mon 3 cm rain, Tue 5 cm, Wed 0 cm, Thu 2 cm. Which day had no rain?",
    options: [
      { id: "a", text: "Monday" },
      { id: "b", text: "Tuesday" },
      { id: "c", text: "Wednesday" },
      { id: "d", text: "Thursday" },
    ],
    answerId: "c",
    explanation: "Wednesday shows 0 cm.",
    hints: ["Look for the zero entry.", "0 means none."],
  },
  {
    id: "g4-maths-data-a-q17",
    prompt: "Total rainfall Mon–Thu (3+5+0+2) is…",
    options: [
      { id: "a", text: "8 cm" },
      { id: "b", text: "10 cm" },
      { id: "c", text: "12 cm" },
      { id: "d", text: "5 cm" },
    ],
    answerId: "b",
    explanation: "3 + 5 + 0 + 2 = 10 cm.",
    hints: ["Add all daily amounts.", "3 + 5 + 2."],
  },
  {
    id: "g4-maths-data-a-q18",
    prompt: "If 1 ★ = 10 points in a pictograph, ★★★½ means…",
    options: [
      { id: "a", text: "30 points" },
      { id: "b", text: "35 points" },
      { id: "c", text: "25 points" },
      { id: "d", text: "15 points" },
    ],
    answerId: "b",
    explanation: "3 full stars = 30 and half a star = 5, total 35.",
    hints: ["Full pictures first, then the half.", "3 × 10 + 5."],
  },
  {
    id: "g4-maths-data-a-q19",
    prompt: "A bar graph axis that shows the names of fruits is usually the…",
    options: [
      { id: "a", text: "Scale of kilograms only" },
      { id: "b", text: "Category axis (labels)" },
      { id: "c", text: "Thermometer" },
      { id: "d", text: "Clock face" },
    ],
    answerId: "b",
    explanation: "Category labels (mango, apple…) sit on one axis; numbers on the other.",
    hints: ["Names vs numbers.", "Fruit names are categories."],
  },
  {
    id: "g4-maths-data-a-q20",
    prompt: "Which statement about a bar graph is true?",
    options: [
      { id: "a", text: "Bars must overlap" },
      { id: "b", text: "Bars of equal height show equal values" },
      { id: "c", text: "Taller always means smaller" },
      { id: "d", text: "Titles are never needed" },
    ],
    answerId: "b",
    explanation: "Equal bar heights mean equal values.",
    hints: ["Height encodes the number.", "Same height → same value."],
  },
  {
    id: "g4-maths-data-a-q21",
    prompt: "Survey of 20 children: 9 like idli, 6 like dosa, rest like poha. How many like poha?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "6" },
      { id: "c", text: "9" },
      { id: "d", text: "20" },
    ],
    answerId: "a",
    explanation: "20 − 9 − 6 = 5 like poha.",
    hints: ["Subtract known groups from the total.", "20 − 15."],
  },
  {
    id: "g4-maths-data-a-q22",
    prompt: "Organised data in rows and columns is called a…",
    options: [
      { id: "a", text: "Tally only" },
      { id: "b", text: "Table" },
      { id: "c", text: "Ray" },
      { id: "d", text: "Perimeter" },
    ],
    answerId: "b",
    explanation: "A table arranges data in rows and columns.",
    hints: ["Rows and columns → table.", "Like a marksheet grid."],
  },
  {
    id: "g4-maths-data-a-q23",
    prompt: "Pictograph: 🚗 = 4 cars. Row shows 🚗🚗🚗. Number of cars?",
    options: [
      { id: "a", text: "3" },
      { id: "b", text: "7" },
      { id: "c", text: "12" },
      { id: "d", text: "4" },
    ],
    answerId: "c",
    explanation: "3 × 4 = 12 cars.",
    hints: ["Use the key multiplier.", "3 × 4."],
  },
  {
    id: "g4-maths-data-a-q24",
    prompt: "Why do we use tally marks?",
    options: [
      { id: "a", text: "To measure angles" },
      { id: "b", text: "To count quickly while collecting data" },
      { id: "c", text: "To find perimeter" },
      { id: "d", text: "To convert kg to g" },
    ],
    answerId: "b",
    explanation: "Tallies help count on the fly as we survey or observe.",
    hints: ["Quick counting while watching.", "Groups of five speed totals."],
  },
];

const SET_B: PrepQuestion[] = [
  {
    id: "g4-maths-data-b-q01",
    prompt: "Tally |||| |||| |||| means…",
    options: [
      { id: "a", text: "12" },
      { id: "b", text: "14" },
      { id: "c", text: "15" },
      { id: "d", text: "10" },
    ],
    answerId: "c",
    explanation: "Three gates of 5 = 15.",
    hints: ["Each completed gate is 5.", "3 × 5."],
  },
  {
    id: "g4-maths-data-b-q02",
    prompt: "A pictograph key says 1 book-icon = 3 books. How many pictures for 12 books?",
    options: [
      { id: "a", text: "3" },
      { id: "b", text: "4" },
      { id: "c", text: "6" },
      { id: "d", text: "12" },
    ],
    answerId: "b",
    explanation: "12 ÷ 3 = 4 pictures.",
    hints: ["Divide the total by the key value.", "12 ÷ 3."],
  },
  {
    id: "g4-maths-data-b-q03",
    prompt: "Ice-cream likes: Vanilla 10, Chocolate 7, Butterscotch 10, Mango 4. Which flavours tie for most liked?",
    options: [
      { id: "a", text: "Chocolate and Mango" },
      { id: "b", text: "Vanilla and Butterscotch" },
      { id: "c", text: "Vanilla and Chocolate" },
      { id: "d", text: "Only Mango" },
    ],
    answerId: "b",
    explanation: "Vanilla and Butterscotch both have 10, the highest.",
    hints: ["Find the maximum, then see who matches it.", "Both show 10."],
  },
  {
    id: "g4-maths-data-b-q04",
    prompt: "How many more children like Vanilla than Mango (10 vs 4)?",
    options: [
      { id: "a", text: "4" },
      { id: "b", text: "6" },
      { id: "c", text: "10" },
      { id: "d", text: "14" },
    ],
    answerId: "b",
    explanation: "10 − 4 = 6 more.",
    hints: ["Subtract the smaller from the larger.", "10 − 4."],
  },
  {
    id: "g4-maths-data-b-q05",
    prompt: "Which display uses pictures to stand for numbers?",
    options: [
      { id: "a", text: "Only a number line" },
      { id: "b", text: "Pictograph" },
      { id: "c", text: "Only a protractor" },
      { id: "d", text: "Balance scale" },
    ],
    answerId: "b",
    explanation: "A pictograph uses pictures with a key.",
    hints: ["Picture + key = pictograph.", "Icons represent counts."],
  },
  {
    id: "g4-maths-data-b-q06",
    prompt: "Quiz scores: Asha 8, Bala 6, Chetan 9, Diya 7. Who scored highest?",
    options: [
      { id: "a", text: "Asha" },
      { id: "b", text: "Bala" },
      { id: "c", text: "Chetan" },
      { id: "d", text: "Diya" },
    ],
    answerId: "c",
    explanation: "9 is the highest score (Chetan).",
    hints: ["Scan for the greatest number.", "Compare 8, 6, 9, 7."],
  },
  {
    id: "g4-maths-data-b-q07",
    prompt: "Total of Asha and Diya's scores (8 and 7) is…",
    options: [
      { id: "a", text: "14" },
      { id: "b", text: "15" },
      { id: "c", text: "16" },
      { id: "d", text: "9" },
    ],
    answerId: "b",
    explanation: "8 + 7 = 15.",
    hints: ["Add the two scores.", "8 + 7."],
  },
  {
    id: "g4-maths-data-b-q08",
    prompt: "Bar graph scale reads 0, 2, 4, 6, 8… Each step is…",
    options: [
      { id: "a", text: "1 unit" },
      { id: "b", text: "2 units" },
      { id: "c", text: "4 units" },
      { id: "d", text: "8 units" },
    ],
    answerId: "b",
    explanation: "The numbers rise by 2 each mark.",
    hints: ["Look at the gap between marks.", "0 to 2 to 4."],
  },
  {
    id: "g4-maths-data-b-q09",
    prompt: "Tally for 11 is…",
    options: [
      { id: "a", text: "|||| |||| |" },
      { id: "b", text: "|||| |||| ||" },
      { id: "c", text: "|||| |||" },
      { id: "d", text: "||| ||||" },
    ],
    answerId: "a",
    explanation: "Two gates (10) plus one stroke = 11.",
    hints: ["10 + 1.", "Two fives and a single."],
  },
  {
    id: "g4-maths-data-b-q10",
    prompt: "Pets: Dog 8, Cat 5, Fish 3, None 4. How many children have a cat or a fish?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "8" },
      { id: "c", text: "9" },
      { id: "d", text: "4" },
    ],
    answerId: "b",
    explanation: "5 + 3 = 8 children.",
    hints: ["Add the cat and fish counts.", "5 + 3."],
  },
  {
    id: "g4-maths-data-b-q11",
    prompt: "How many children were surveyed in the pets table (8+5+3+4)?",
    options: [
      { id: "a", text: "16" },
      { id: "b", text: "18" },
      { id: "c", text: "20" },
      { id: "d", text: "12" },
    ],
    answerId: "c",
    explanation: "8 + 5 + 3 + 4 = 20.",
    hints: ["Add every category.", "8 + 5 + 3 + 4."],
  },
  {
    id: "g4-maths-data-b-q12",
    prompt: "A half symbol in a pictograph with key 1 icon = 10 means…",
    options: [
      { id: "a", text: "20" },
      { id: "b", text: "10" },
      { id: "c", text: "5" },
      { id: "d", text: "1" },
    ],
    answerId: "c",
    explanation: "Half of 10 is 5.",
    hints: ["Halve the key value.", "10 ÷ 2."],
  },
  {
    id: "g4-maths-data-b-q13",
    prompt: "Which question can a bar graph of favourite subjects answer?",
    options: [
      { id: "a", text: "Who is the tallest child?" },
      { id: "b", text: "Which subject has the most votes?" },
      { id: "c", text: "What is 7 × 8?" },
      { id: "d", text: "How heavy is a school bag?" },
    ],
    answerId: "b",
    explanation: "The graph compares vote counts by subject.",
    hints: ["Graphs answer questions about the data shown.", "Look for most/least votes."],
  },
  {
    id: "g4-maths-data-b-q14",
    prompt: "Raw tick marks collected in class should next be…",
    options: [
      { id: "a", text: "Thrown away" },
      { id: "b", text: "Organised into tallies, tables or graphs" },
      { id: "c", text: "Used only for perimeter" },
      { id: "d", text: "Converted to kilograms" },
    ],
    answerId: "b",
    explanation: "We organise raw counts into tallies, tables and graphs.",
    hints: ["Data handling = organise and display.", "Make tallies/tables/graphs."],
  },
  {
    id: "g4-maths-data-b-q15",
    prompt: "Pictograph: 1 sapling icon = 2 plants. Row has 5 icons. Plants planted?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "7" },
      { id: "c", text: "10" },
      { id: "d", text: "2" },
    ],
    answerId: "c",
    explanation: "5 × 2 = 10 plants.",
    hints: ["Multiply icons by key.", "5 × 2."],
  },
  {
    id: "g4-maths-data-b-q16",
    prompt: "In a table, rows often show…",
    options: [
      { id: "a", text: "Only colours" },
      { id: "b", text: "Different categories or items" },
      { id: "c", text: "Only angles" },
      { id: "d", text: "Only parallel lines" },
    ],
    answerId: "b",
    explanation: "Each row usually lists one category or item with its data.",
    hints: ["Tables map items to numbers.", "One row per category often."],
  },
  {
    id: "g4-maths-data-b-q17",
    prompt: "Bar lengths for houses in a colony: Type A 9, Type B 6, Type C 9, Type D 3. How many Type A and Type C houses together?",
    options: [
      { id: "a", text: "9" },
      { id: "b", text: "15" },
      { id: "c", text: "18" },
      { id: "d", text: "12" },
    ],
    answerId: "c",
    explanation: "9 + 9 = 18.",
    hints: ["Add the two matching counts.", "9 + 9."],
  },
  {
    id: "g4-maths-data-b-q18",
    prompt: "Which is NOT a way to handle data?",
    options: [
      { id: "a", text: "Tally marks" },
      { id: "b", text: "Pictograph" },
      { id: "c", text: "Bar graph" },
      { id: "d", text: "Ignoring all numbers collected" },
    ],
    answerId: "d",
    explanation: "Throwing data away is not data handling — we organise and display it.",
    hints: ["Data handling organises information.", "Tallies and graphs help; ignoring does not."],
  },
  {
    id: "g4-maths-data-b-q19",
    prompt: "If a pictograph has no key, the problem is…",
    options: [
      { id: "a", text: "Colours are wrong" },
      { id: "b", text: "You cannot know what each picture is worth" },
      { id: "c", text: "The title is too long" },
      { id: "d", text: "Bars are too thin" },
    ],
    answerId: "b",
    explanation: "Without a key, picture counts cannot be turned into real numbers.",
    hints: ["Keys tell the value of one picture.", "Missing key → unknown scale."],
  },
  {
    id: "g4-maths-data-b-q20",
    prompt: "Monday's tally of library visitors is |||| ||||. Tuesday adds ||||. Total for both days?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "13" },
      { id: "c", text: "15" },
      { id: "d", text: "8" },
    ],
    answerId: "c",
    explanation: "Monday 10 + Tuesday 5 = 15.",
    hints: ["Convert tallies to numbers, then add.", "10 + 5."],
  },
  {
    id: "g4-maths-data-b-q21",
    prompt: "A survey title 'Modes of travel to school' fits data about…",
    options: [
      { id: "a", text: "Favourite colours only" },
      { id: "b", text: "Bus, walk, cycle, car counts" },
      { id: "c", text: "Only mass in kilograms" },
      { id: "d", text: "Only triangle types" },
    ],
    answerId: "b",
    explanation: "The title matches how children travel to school.",
    hints: ["Title must match the categories.", "Travel modes fit."],
  },
  {
    id: "g4-maths-data-b-q22",
    prompt: "Compare two bars: Maths 14 votes, Art 9 votes. Maths has how many more?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "9" },
      { id: "c", text: "14" },
      { id: "d", text: "23" },
    ],
    answerId: "a",
    explanation: "14 − 9 = 5.",
    hints: ["Difference = larger − smaller.", "14 − 9."],
  },
  {
    id: "g4-maths-data-b-q23",
    prompt: "Which list is already arranged as a simple frequency table idea?",
    options: [
      { id: "a", text: "Red, blue, green as colours only with no counts" },
      { id: "b", text: "Hopscotch 6, Lagori 4, Kho-kho 8" },
      { id: "c", text: "A single random number 42" },
      { id: "d", text: "A rhyming poem" },
    ],
    answerId: "b",
    explanation: "Each game name is paired with how many times it was chosen.",
    hints: ["Frequency pairs category with count.", "Names + numbers."],
  },
  {
    id: "g4-maths-data-b-q24",
    prompt: "After making a bar graph, a useful check is…",
    options: [
      { id: "a", text: "Erase the title" },
      { id: "b", text: "See whether bar heights match the table numbers" },
      { id: "c", text: "Remove the scale" },
      { id: "d", text: "Mix unrelated categories" },
    ],
    answerId: "b",
    explanation: "Bars should agree with the table — a quick accuracy check.",
    hints: ["Graph and table should tell the same story.", "Match heights to numbers."],
  },
];

const lesson: ChapterDef["lesson"] = [
  {
    id: "h",
    type: "hook",
    emoji: "📊",
    title: "Counting what we see",
    body: [
      "Data handling means collecting numbers and showing them clearly.",
      "Tallies, tables, pictographs and bar graphs help us compare.",
      "Lesson is optional; jump to a set anytime.",
    ],
    cta: "Let's organise!",
    visual: "number-line",
    speak: "Data handling means collecting numbers and showing them clearly with tallies, tables, pictographs and bar graphs.",
  },
  {
    id: "r1",
    type: "reveal",
    title: "Four friendly tools",
    lead: "Tap each card.",
    visual: "number-line",
    speak: "Tally marks group by fives. Tables use rows and columns. Pictographs use pictures with a key. Bar graphs use bar heights.",
    cards: [
      { label: "Tally", reveal: "|||| with a slash = 5", emoji: "✍️" },
      { label: "Table", reveal: "Rows & columns of facts", emoji: "🗓️" },
      { label: "Pictograph", reveal: "Pictures + a key (1 icon = ?)", emoji: "🖼️" },
      { label: "Bar graph", reveal: "Bar height shows the number", emoji: "📊" },
    ],
  },
  {
    id: "d1",
    type: "demo",
    title: "From tallies to totals",
    visual: "number-line",
    speak: "Count complete gates of five, then add leftover strokes. Write the total in a table. Compare to see most and least.",
    steps: [
      "Gate of 5: four lines + one slash",
      "Add leftover strokes",
      "Put totals in a table",
      "Find most / least / difference",
    ],
    punchline: "Organise first, then compare.",
  },
  {
    id: "t1",
    type: "try",
    title: "Your turn",
    prompt: "If 1 sun icon = 2 sunny days, how many sunny days do 4 icons show?",
    options: [
      { id: "a", text: "4" },
      { id: "b", text: "6" },
      { id: "c", text: "8" },
      { id: "d", text: "2" },
    ],
    answerId: "c",
    why: "4 × 2 = 8 sunny days.",
    visual: "number-line",
    speak: "If one sun icon equals two sunny days, how many sunny days do four icons show?",
  },
  {
    id: "d2",
    type: "demo",
    title: "Read a bar graph",
    visual: "number-line",
    speak: "Read the title and the scale. Match each bar to its category. Taller means more. Use the scale marks carefully.",
    steps: [
      "Read title and labels",
      "Check the scale (0, 2, 4…)",
      "Compare bar heights",
      "Answer most, least, total, difference",
    ],
    punchline: "Title · scale · height · compare.",
  },
  {
    id: "c1",
    type: "check",
    title: "Quick check",
    visual: "number-line",
    speak: "A tally shows two gates and three extra strokes. How many is that?",
    question: {
      id: "g4-data-check",
      prompt: "A tally shows |||| |||| |||. How many does it show?",
      options: [
        { id: "a", text: "10" },
        { id: "b", text: "11" },
        { id: "c", text: "13" },
        { id: "d", text: "8" },
      ],
      answerId: "c",
      explanation: "5 + 5 + 3 = 13.",
      hints: ["Each gate counts as 5.", "Then add the three strokes."],
    },
  },
  {
    id: "w",
    type: "wrap",
    emoji: "⭐",
    title: "Data detective!",
    bullets: [
      "Tallies group by 5",
      "Tables organise; graphs compare",
      "Always read the pictograph key and bar scale",
      "Set A and Set B ready — 24 MCQs each",
    ],
    cta: "Back to chapter",
    speak: "You can read tallies, tables and graphs. Set A and Set B are ready.",
  },
];


export const g4MathsDataHandling: ChapterDef = {
  id: "g4-data-handling",
  title: "Data Handling",
  emoji: "📊",
  blurb: "Pictographs, bars, tallies & tables",
  lesson,
  sets: [
    {
      id: "set-a",
      title: "Set A",
      questionCount: SET_A.length,
      topic: "data-handling",
      questions: SET_A,
    },
    {
      id: "set-b",
      title: "Set B",
      questionCount: SET_B.length,
      topic: "data-handling",
      questions: SET_B,
    },
  ],
  paperTopics: ["data-handling", "add-sub"],
};

export const g4MathsDataHandlingQuestions: PrepQuestion[] = [...SET_A, ...SET_B];

