import type { ChapterDef, PrepQuestion } from "../types";

/** Geometry - authored SOF-style content (original). */

const SET_A: PrepQuestion[] = [
  {
    id: "g4-maths-geometry-a-q01",
    prompt: "A closed shape with 3 straight sides is a…",
    options: [
      { id: "a", text: "Quadrilateral" },
      { id: "b", text: "Triangle" },
      { id: "c", text: "Circle" },
      { id: "d", text: "Pentagon" },
    ],
    answerId: "b",
    explanation: "A triangle has exactly three straight sides.",
    hints: ["Count the straight sides.", "Three sides → triangle."],
  },
  {
    id: "g4-maths-geometry-a-q02",
    prompt: "How many sides does a square have?",
    options: [
      { id: "a", text: "3" },
      { id: "b", text: "4" },
      { id: "c", text: "5" },
      { id: "d", text: "6" },
    ],
    answerId: "b",
    explanation: "A square has 4 equal sides and 4 right angles.",
    hints: ["A square is a special rectangle.", "Count the edges."],
  },
  {
    id: "g4-maths-geometry-a-q03",
    prompt: "Which shape has all points at the same distance from the centre?",
    options: [
      { id: "a", text: "Square" },
      { id: "b", text: "Triangle" },
      { id: "c", text: "Circle" },
      { id: "d", text: "Rectangle" },
    ],
    answerId: "c",
    explanation: "In a circle, every point on the rim is the same distance from the centre.",
    hints: ["Think of a round steel plate or a chapati cutter.", "Equal distance from centre = circle."],
  },
  {
    id: "g4-maths-geometry-a-q04",
    prompt: "A rectangle has…",
    options: [
      { id: "a", text: "3 sides" },
      { id: "b", text: "4 equal sides only" },
      { id: "c", text: "4 sides with opposite sides equal" },
      { id: "d", text: "5 sides" },
    ],
    answerId: "c",
    explanation: "A rectangle has 4 sides; opposite sides are equal and all angles are right angles.",
    hints: ["Rectangles have four sides.", "Opposite sides match."],
  },
  {
    id: "g4-maths-geometry-a-q05",
    prompt: "Which of these is a closed shape?",
    options: [
      { id: "a", text: "A ray" },
      { id: "b", text: "A line segment" },
      { id: "c", text: "A square" },
      { id: "d", text: "An open curve like a C" },
    ],
    answerId: "c",
    explanation: "A square joins end to end with no gap, so it is closed.",
    hints: ["Closed means you return to the start with no opening.", "Squares enclose space."],
  },
  {
    id: "g4-maths-geometry-a-q06",
    prompt: "A line that goes on forever in both directions is a…",
    options: [
      { id: "a", text: "Ray" },
      { id: "b", text: "Line segment" },
      { id: "c", text: "Line" },
      { id: "d", text: "Angle" },
    ],
    answerId: "c",
    explanation: "A line has no end points; it extends both ways.",
    hints: ["Segment stops; ray has one end; line never stops.", "Both directions forever → line."],
  },
  {
    id: "g4-maths-geometry-a-q07",
    prompt: "A ray has…",
    options: [
      { id: "a", text: "Two end points" },
      { id: "b", text: "One end point and goes forever one way" },
      { id: "c", text: "No end points" },
      { id: "d", text: "Three end points" },
    ],
    answerId: "b",
    explanation: "A ray starts at a point and goes on forever in one direction.",
    hints: ["Picture sunlight starting at the sun.", "One start, endless path."],
  },
  {
    id: "g4-maths-geometry-a-q08",
    prompt: "An angle is formed by…",
    options: [
      { id: "a", text: "One straight line only" },
      { id: "b", text: "Two rays sharing a common end point" },
      { id: "c", text: "Three circles" },
      { id: "d", text: "Four parallel lines" },
    ],
    answerId: "b",
    explanation: "Two rays (arms) with a common end point (vertex) make an angle.",
    hints: ["Look for two arms and a corner.", "Vertex + two arms."],
  },
  {
    id: "g4-maths-geometry-a-q09",
    prompt: "A right angle measures…",
    options: [
      { id: "a", text: "45°" },
      { id: "b", text: "90°" },
      { id: "c", text: "180°" },
      { id: "d", text: "360°" },
    ],
    answerId: "b",
    explanation: "A right angle is exactly 90° — like a square corner.",
    hints: ["Think of the corner of a notebook.", "Square corner = 90°."],
  },
  {
    id: "g4-maths-geometry-a-q10",
    prompt: "Which angle is smaller than a right angle?",
    options: [
      { id: "a", text: "Obtuse angle" },
      { id: "b", text: "Straight angle" },
      { id: "c", text: "Acute angle" },
      { id: "d", text: "Complete angle" },
    ],
    answerId: "c",
    explanation: "An acute angle is less than 90°.",
    hints: ["Acute = sharp / smaller than a square corner.", "Compare with 90°."],
  },
  {
    id: "g4-maths-geometry-a-q11",
    prompt: "An obtuse angle is…",
    options: [
      { id: "a", text: "Less than 90°" },
      { id: "b", text: "Exactly 90°" },
      { id: "c", text: "Between 90° and 180°" },
      { id: "d", text: "Exactly 180°" },
    ],
    answerId: "c",
    explanation: "Obtuse angles are greater than 90° but less than 180°.",
    hints: ["Obtuse is 'open wider' than a right angle but not flat.", "Between 90° and 180°."],
  },
  {
    id: "g4-maths-geometry-a-q12",
    prompt: "A square has a perimeter of 20 cm. What is the length of one side?",
    options: [
      { id: "a", text: "4 cm" },
      { id: "b", text: "5 cm" },
      { id: "c", text: "10 cm" },
      { id: "d", text: "20 cm" },
    ],
    answerId: "b",
    explanation: "Perimeter = 4 × side, so side = 20 ÷ 4 = 5 cm.",
    hints: ["All four sides of a square are equal.", "Divide perimeter by 4."],
  },
  {
    id: "g4-maths-geometry-a-q13",
    prompt: "Perimeter means…",
    options: [
      { id: "a", text: "The space inside a shape" },
      { id: "b", text: "The distance around a shape" },
      { id: "c", text: "The number of diagonals" },
      { id: "d", text: "The centre point" },
    ],
    answerId: "b",
    explanation: "Perimeter is the total length of the boundary around a shape.",
    hints: ["Walk along the fence of a park.", "Around the outside."],
  },
  {
    id: "g4-maths-geometry-a-q14",
    prompt: "A rectangular garden is 8 m long and 5 m wide. What is its perimeter?",
    options: [
      { id: "a", text: "13 m" },
      { id: "b", text: "26 m" },
      { id: "c", text: "40 m" },
      { id: "d", text: "18 m" },
    ],
    answerId: "b",
    explanation: "Perimeter = 2 × (length + breadth) = 2 × (8 + 5) = 26 m.",
    hints: ["Add length and breadth, then double.", "2 × (8 + 5)."],
  },
  {
    id: "g4-maths-geometry-a-q15",
    prompt: "Which shape always has 4 right angles?",
    options: [
      { id: "a", text: "Any triangle" },
      { id: "b", text: "Any pentagon" },
      { id: "c", text: "A rectangle (including a square)" },
      { id: "d", text: "A circle" },
    ],
    answerId: "c",
    explanation: "Rectangles (and squares) have four right angles.",
    hints: ["Right angles look like notebook corners.", "Four square corners → rectangle/square."],
  },
  {
    id: "g4-maths-geometry-a-q16",
    prompt: "Parallel lines…",
    options: [
      { id: "a", text: "Meet at one point" },
      { id: "b", text: "Meet at two points" },
      { id: "c", text: "Never meet and stay the same distance apart" },
      { id: "d", text: "Form a triangle" },
    ],
    answerId: "c",
    explanation: "Parallel lines never meet and keep a constant distance.",
    hints: ["Think of railway tracks.", "Same gap, no meeting."],
  },
  {
    id: "g4-maths-geometry-a-q17",
    prompt: "How many diagonals can you draw from one vertex of a pentagon?",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "2" },
      { id: "c", text: "3" },
      { id: "d", text: "5" },
    ],
    answerId: "b",
    explanation: "From one vertex of a pentagon you can draw 2 diagonals (not to itself or its neighbours).",
    hints: ["Skip the two adjacent vertices.", "5 − 1 − 2 = 2."],
  },
  {
    id: "g4-maths-geometry-a-q18",
    prompt: "A triangle with all sides equal is…",
    options: [
      { id: "a", text: "Scalene" },
      { id: "b", text: "Isosceles only" },
      { id: "c", text: "Equilateral" },
      { id: "d", text: "Right-angled always" },
    ],
    answerId: "c",
    explanation: "An equilateral triangle has three equal sides.",
    hints: ["Equal sides → equilateral.", "All three match."],
  },
  {
    id: "g4-maths-geometry-a-q19",
    prompt: "Which is true for a cube's face?",
    options: [
      { id: "a", text: "Each face is a circle" },
      { id: "b", text: "Each face is a square" },
      { id: "c", text: "Each face is a triangle" },
      { id: "d", text: "It has no faces" },
    ],
    answerId: "b",
    explanation: "A cube has 6 square faces.",
    hints: ["A dice is a cube.", "Square faces."],
  },
  {
    id: "g4-maths-geometry-a-q20",
    prompt: "A line segment has…",
    options: [
      { id: "a", text: "No end points" },
      { id: "b", text: "Exactly one end point" },
      { id: "c", text: "Exactly two end points" },
      { id: "d", text: "Infinitely many end points" },
    ],
    answerId: "c",
    explanation: "A line segment is a piece of a line with two end points.",
    hints: ["Segment means a cut piece.", "Two ends."],
  },
  {
    id: "g4-maths-geometry-a-q21",
    prompt: "The perimeter of an equilateral triangle with side 6 cm is…",
    options: [
      { id: "a", text: "12 cm" },
      { id: "b", text: "18 cm" },
      { id: "c", text: "24 cm" },
      { id: "d", text: "6 cm" },
    ],
    answerId: "b",
    explanation: "3 × 6 = 18 cm.",
    hints: ["All three sides are 6 cm.", "Add three equal sides."],
  },
  {
    id: "g4-maths-geometry-a-q22",
    prompt: "Which corner is a right angle?",
    options: [
      { id: "a", text: "A sharp slice of pizza much thinner than a notebook corner" },
      { id: "b", text: "The corner of a book page" },
      { id: "c", text: "A nearly flat open door almost in a straight line" },
      { id: "d", text: "A full spin around" },
    ],
    answerId: "b",
    explanation: "A book or notebook corner is a right angle (90°).",
    hints: ["Match the corner to a square corner.", "Books have right-angled corners."],
  },
  {
    id: "g4-maths-geometry-a-q23",
    prompt: "A hexagon has how many sides?",
    options: [
      { id: "a", text: "5" },
      { id: "b", text: "6" },
      { id: "c", text: "7" },
      { id: "d", text: "8" },
    ],
    answerId: "b",
    explanation: "A hexagon has 6 sides.",
    hints: ["Hexa means six.", "Count the edges."],
  },
  {
    id: "g4-maths-geometry-a-q24",
    prompt: "Two lines that meet at a point form…",
    options: [
      { id: "a", text: "Parallel lines" },
      { id: "b", text: "An angle at the meeting point" },
      { id: "c", text: "A circle" },
      { id: "d", text: "A cube" },
    ],
    answerId: "b",
    explanation: "When two lines meet, they form angles at the intersection.",
    hints: ["Meeting lines make corners.", "Corners are angles."],
  },
];

const SET_B: PrepQuestion[] = [
  {
    id: "g4-maths-geometry-b-q01",
    prompt: "A closed shape with 5 straight sides is a…",
    options: [
      { id: "a", text: "Triangle" },
      { id: "b", text: "Quadrilateral" },
      { id: "c", text: "Pentagon" },
      { id: "d", text: "Hexagon" },
    ],
    answerId: "c",
    explanation: "A pentagon has five sides.",
    hints: ["Penta means five.", "Count sides."],
  },
  {
    id: "g4-maths-geometry-b-q02",
    prompt: "Which shape has no straight sides?",
    options: [
      { id: "a", text: "Square" },
      { id: "b", text: "Rectangle" },
      { id: "c", text: "Triangle" },
      { id: "d", text: "Circle" },
    ],
    answerId: "d",
    explanation: "A circle is a curved closed path with no straight sides.",
    hints: ["Straight sides vs smooth curve.", "Circles are round."],
  },
  {
    id: "g4-maths-geometry-b-q03",
    prompt: "Opposite sides of a rectangle are…",
    options: [
      { id: "a", text: "Always unequal" },
      { id: "b", text: "Equal" },
      { id: "c", text: "Curved" },
      { id: "d", text: "Diagonal" },
    ],
    answerId: "b",
    explanation: "In a rectangle, each pair of opposite sides is equal.",
    hints: ["Length matches length; breadth matches breadth.", "Opposite sides equal."],
  },
  {
    id: "g4-maths-geometry-b-q04",
    prompt: "A straight angle measures…",
    options: [
      { id: "a", text: "90°" },
      { id: "b", text: "45°" },
      { id: "c", text: "180°" },
      { id: "d", text: "360°" },
    ],
    answerId: "c",
    explanation: "A straight angle is a flat half-turn of 180°.",
    hints: ["A straight line makes a 180° angle.", "Half of a full turn."],
  },
  {
    id: "g4-maths-geometry-b-q05",
    prompt: "Which is an acute angle?",
    options: [
      { id: "a", text: "120°" },
      { id: "b", text: "90°" },
      { id: "c", text: "35°" },
      { id: "d", text: "180°" },
    ],
    answerId: "c",
    explanation: "35° is less than 90°, so it is acute.",
    hints: ["Acute < 90°.", "Compare each measure to 90°."],
  },
  {
    id: "g4-maths-geometry-b-q06",
    prompt: "Perimeter of a square of side 9 cm is…",
    options: [
      { id: "a", text: "18 cm" },
      { id: "b", text: "27 cm" },
      { id: "c", text: "36 cm" },
      { id: "d", text: "81 cm" },
    ],
    answerId: "c",
    explanation: "4 × 9 = 36 cm.",
    hints: ["Four equal sides.", "Multiply one side by 4."],
  },
  {
    id: "g4-maths-geometry-b-q07",
    prompt: "A rectangular playground is 12 m by 7 m. Perimeter?",
    options: [
      { id: "a", text: "19 m" },
      { id: "b", text: "38 m" },
      { id: "c", text: "84 m" },
      { id: "d", text: "26 m" },
    ],
    answerId: "b",
    explanation: "2 × (12 + 7) = 2 × 19 = 38 m.",
    hints: ["Double the sum of length and breadth.", "2 × 19."],
  },
  {
    id: "g4-maths-geometry-b-q08",
    prompt: "Which figure is open?",
    options: [
      { id: "a", text: "Circle" },
      { id: "b", text: "Square" },
      { id: "c", text: "Equilateral triangle" },
      { id: "d", text: "A U-shaped curve" },
    ],
    answerId: "d",
    explanation: "A U-shape has an opening, so it is not a closed figure.",
    hints: ["Closed figures seal completely.", "U leaves a gap."],
  },
  {
    id: "g4-maths-geometry-b-q09",
    prompt: "The vertex of an angle is…",
    options: [
      { id: "a", text: "One of the arms" },
      { id: "b", text: "The common end point of the arms" },
      { id: "c", text: "The longest side" },
      { id: "d", text: "A parallel line" },
    ],
    answerId: "b",
    explanation: "The vertex is where the two arms meet.",
    hints: ["Vertex = corner point.", "Where arms join."],
  },
  {
    id: "g4-maths-geometry-b-q10",
    prompt: "How many right angles does a square have?",
    options: [
      { id: "a", text: "1" },
      { id: "b", text: "2" },
      { id: "c", text: "3" },
      { id: "d", text: "4" },
    ],
    answerId: "d",
    explanation: "Every corner of a square is a right angle — four in all.",
    hints: ["Each corner is 90°.", "Four corners."],
  },
  {
    id: "g4-maths-geometry-b-q11",
    prompt: "A rhombus has…",
    options: [
      { id: "a", text: "4 equal sides" },
      { id: "b", text: "3 equal sides" },
      { id: "c", text: "No equal sides" },
      { id: "d", text: "5 equal sides" },
    ],
    answerId: "a",
    explanation: "All four sides of a rhombus are equal (angles need not all be right).",
    hints: ["Rhombus is like a pushed-over square.", "Sides equal."],
  },
  {
    id: "g4-maths-geometry-b-q12",
    prompt: "Which pair of lines is parallel?",
    options: [
      { id: "a", text: "Two sides of a triangle meeting at a vertex" },
      { id: "b", text: "Opposite long sides of a straight road divider" },
      { id: "c", text: "The hands of a clock at 3 o'clock" },
      { id: "d", text: "Two diameters of a circle that cross" },
    ],
    answerId: "b",
    explanation: "Opposite edges of a straight road divider stay the same distance apart.",
    hints: ["Parallel lines never meet.", "Road edges stay apart."],
  },
  {
    id: "g4-maths-geometry-b-q13",
    prompt: "A triangle cannot have…",
    options: [
      { id: "a", text: "3 sides" },
      { id: "b", text: "3 angles" },
      { id: "c", text: "4 sides" },
      { id: "d", text: "A closed boundary" },
    ],
    answerId: "c",
    explanation: "By definition a triangle has exactly 3 sides, not 4.",
    hints: ["Tri means three.", "Four sides would be a quadrilateral."],
  },
  {
    id: "g4-maths-geometry-b-q14",
    prompt: "Side of a square is 4 cm. Perimeter of two such squares joined along one full side (like a rectangle 8 cm by 4 cm) is…",
    options: [
      { id: "a", text: "16 cm" },
      { id: "b", text: "24 cm" },
      { id: "c", text: "32 cm" },
      { id: "d", text: "20 cm" },
    ],
    answerId: "b",
    explanation: "Outer path: 8 + 4 + 8 + 4 = 24 cm (the joined side is inside, not on the perimeter).",
    hints: ["Joined side is not part of the outer boundary.", "2 × (8 + 4) = 24."],
  },
  {
    id: "g4-maths-geometry-b-q15",
    prompt: "An angle of 90° is called…",
    options: [
      { id: "a", text: "Acute" },
      { id: "b", text: "Obtuse" },
      { id: "c", text: "Right" },
      { id: "d", text: "Reflex" },
    ],
    answerId: "c",
    explanation: "Exactly 90° is a right angle.",
    hints: ["Right angle = square corner.", "Exactly 90°."],
  },
  {
    id: "g4-maths-geometry-b-q16",
    prompt: "Which solid has 6 faces, 12 edges and 8 vertices?",
    options: [
      { id: "a", text: "Cylinder" },
      { id: "b", text: "Cone" },
      { id: "c", text: "Cube" },
      { id: "d", text: "Sphere" },
    ],
    answerId: "c",
    explanation: "A cube has 6 faces, 12 edges and 8 corners (vertices).",
    hints: ["Count faces of a dice.", "Cube numbers: 6, 12, 8."],
  },
  {
    id: "g4-maths-geometry-b-q17",
    prompt: "A line segment AB has length 7 cm. Point M is its midpoint. AM = ?",
    options: [
      { id: "a", text: "7 cm" },
      { id: "b", text: "3.5 cm" },
      { id: "c", text: "14 cm" },
      { id: "d", text: "0 cm" },
    ],
    answerId: "b",
    explanation: "The midpoint splits the segment into two equal parts of 3.5 cm each.",
    hints: ["Midpoint means halfway.", "Half of 7."],
  },
  {
    id: "g4-maths-geometry-b-q18",
    prompt: "Which shape is a quadrilateral?",
    options: [
      { id: "a", text: "Triangle" },
      { id: "b", text: "Pentagon" },
      { id: "c", text: "Rectangle" },
      { id: "d", text: "Circle" },
    ],
    answerId: "c",
    explanation: "A rectangle has four sides, so it is a quadrilateral.",
    hints: ["Quad means four.", "Four-sided closed shape."],
  },
  {
    id: "g4-maths-geometry-b-q19",
    prompt: "Perimeter of a regular pentagon with side 5 cm is…",
    options: [
      { id: "a", text: "20 cm" },
      { id: "b", text: "25 cm" },
      { id: "c", text: "30 cm" },
      { id: "d", text: "15 cm" },
    ],
    answerId: "b",
    explanation: "5 equal sides: 5 × 5 = 25 cm.",
    hints: ["Regular means all sides equal.", "Multiply side by 5."],
  },
  {
    id: "g4-maths-geometry-b-q20",
    prompt: "When the clock hands form a right angle, one example time is…",
    options: [
      { id: "a", text: "6:00" },
      { id: "b", text: "3:00" },
      { id: "c", text: "12:00" },
      { id: "d", text: "9:30 only" },
    ],
    answerId: "b",
    explanation: "At 3:00 the hands form a right angle (90°).",
    hints: ["At 3 the minute hand on 12 and hour on 3 make a square corner.", "90° apart."],
  },
  {
    id: "g4-maths-geometry-b-q21",
    prompt: "Intersecting lines…",
    options: [
      { id: "a", text: "Never meet" },
      { id: "b", text: "Meet at one or more points" },
      { id: "c", text: "Are always parallel" },
      { id: "d", text: "Must form a circle" },
    ],
    answerId: "b",
    explanation: "Intersecting lines cross and meet at a point.",
    hints: ["Intersect means cross.", "They share a point."],
  },
  {
    id: "g4-maths-geometry-b-q22",
    prompt: "A square park has perimeter 48 m. Length of one side?",
    options: [
      { id: "a", text: "8 m" },
      { id: "b", text: "10 m" },
      { id: "c", text: "12 m" },
      { id: "d", text: "16 m" },
    ],
    answerId: "c",
    explanation: "48 ÷ 4 = 12 m.",
    hints: ["Perimeter ÷ 4 for a square.", "48 ÷ 4."],
  },
  {
    id: "g4-maths-geometry-b-q23",
    prompt: "Which angle is obtuse?",
    options: [
      { id: "a", text: "20°" },
      { id: "b", text: "90°" },
      { id: "c", text: "135°" },
      { id: "d", text: "180°" },
    ],
    answerId: "c",
    explanation: "135° is between 90° and 180°, so it is obtuse.",
    hints: ["Obtuse sits between right and straight.", "Check 90° < angle < 180°."],
  },
  {
    id: "g4-maths-geometry-b-q24",
    prompt: "A closed shape made only of straight sides is a…",
    options: [
      { id: "a", text: "Circle" },
      { id: "b", text: "Oval" },
      { id: "c", text: "Polygon" },
      { id: "d", text: "Sphere" },
    ],
    answerId: "c",
    explanation: "Polygons are closed figures with straight sides only.",
    hints: ["Straight sides, closed path.", "Triangle, square, pentagon are polygons."],
  },
];

const lesson: ChapterDef["lesson"] = [
  {
    id: "h",
    type: "hook",
    emoji: "📐",
    title: "Shapes, lines & corners",
    body: [
      "Geometry is about shapes, lines and angles around us — tiles, windows, clocks.",
      "We'll meet 2D shapes, perimeter, and simple angle names.",
      "Lesson is optional; jump to a set anytime.",
    ],
    cta: "Explore!",
    visual: "number-line",
    speak: "Geometry is about shapes, lines and angles. We'll meet 2D shapes, perimeter, and simple angle names.",
  },
  {
    id: "r1",
    type: "reveal",
    title: "Name the pieces",
    lead: "Tap each card.",
    visual: "number-line",
    speak: "A line goes both ways forever. A ray has one start. A segment has two ends. An angle has two arms and a vertex.",
    cards: [
      { label: "Line", reveal: "No end points — forever both ways", emoji: "➖" },
      { label: "Ray", reveal: "One end point — forever one way", emoji: "➡️" },
      { label: "Segment", reveal: "Two end points — a finite piece", emoji: "📏" },
      { label: "Angle", reveal: "Two arms + vertex (corner)", emoji: "📐" },
    ],
  },
  {
    id: "d1",
    type: "demo",
    title: "Angle families",
    visual: "number-line",
    speak: "Acute is less than ninety degrees. Right is exactly ninety. Obtuse is between ninety and one hundred eighty. Straight is one hundred eighty.",
    steps: [
      "Acute < 90°",
      "Right = 90° (notebook corner)",
      "Obtuse: 90° to 180°",
      "Straight = 180°",
    ],
    punchline: "Compare every angle with a square corner.",
  },
  {
    id: "t1",
    type: "try",
    title: "Your turn",
    prompt: "A square has side 6 cm. What is its perimeter?",
    options: [
      { id: "a", text: "12 cm" },
      { id: "b", text: "18 cm" },
      { id: "c", text: "24 cm" },
      { id: "d", text: "36 cm" },
    ],
    answerId: "c",
    why: "4 × 6 = 24 cm.",
    visual: "number-line",
    speak: "A square has side six centimetres. What is its perimeter?",
  },
  {
    id: "d2",
    type: "demo",
    title: "Perimeter walk",
    visual: "number-line",
    speak: "Perimeter is the distance around. For a rectangle, add length and breadth, then double. For a square, multiply one side by four.",
    steps: [
      "Perimeter = walk around the boundary",
      "Rectangle: 2 × (l + b)",
      "Square: 4 × side",
      "Equilateral triangle: 3 × side",
    ],
    punchline: "Add every outer side once.",
  },
  {
    id: "c1",
    type: "check",
    title: "Quick check",
    visual: "number-line",
    speak: "A rectangular courtyard is ten metres by four metres. What is the perimeter?",
    question: {
      id: "g4-geo-check",
      prompt: "A rectangular courtyard is 10 m by 4 m. What is its perimeter?",
      options: [
        { id: "a", text: "14 m" },
        { id: "b", text: "28 m" },
        { id: "c", text: "40 m" },
        { id: "d", text: "24 m" },
      ],
      answerId: "b",
      explanation: "2 × (10 + 4) = 28 m.",
      hints: ["Add length and breadth first.", "Then multiply by 2."],
    },
  },
  {
    id: "w",
    type: "wrap",
    emoji: "⭐",
    title: "Shape explorer!",
    bullets: [
      "Know lines, rays, segments and angles",
      "Acute, right, obtuse, straight",
      "Perimeter = distance around",
      "Set A and Set B ready — 24 MCQs each",
    ],
    cta: "Back to chapter",
    speak: "You can name shapes and find perimeters. Set A and Set B are ready.",
  },
];


export const g4MathsGeometry: ChapterDef = {
  id: "g4-geometry",
  title: "Geometry",
  emoji: "📐",
  blurb: "2D shapes, perimeter, lines & angles",
  lesson,
  sets: [
    {
      id: "set-a",
      title: "Set A",
      questionCount: SET_A.length,
      topic: "geometry",
      questions: SET_A,
    },
    {
      id: "set-b",
      title: "Set B",
      questionCount: SET_B.length,
      topic: "geometry",
      questions: SET_B,
    },
  ],
  paperTopics: ["geometry", "measurement"],
};

export const g4MathsGeometryQuestions: PrepQuestion[] = [...SET_A, ...SET_B];

