import type { ChapterDef, PrepQuestion } from "../types";

/** Measurement - authored SOF-style content (original). */

const SET_A: PrepQuestion[] = [
  {
    id: "g4-maths-measurement-a-q01",
    prompt: "Which unit is best for measuring the length of a pencil?",
    options: [
      { id: "a", text: "Kilometre" },
      { id: "b", text: "Metre" },
      { id: "c", text: "Centimetre" },
      { id: "d", text: "Kilogram" },
    ],
    answerId: "c",
    explanation: "A pencil is short, so centimetres (cm) are the right unit.",
    hints: ["Match the object size to a sensible unit.", "Pencils are much shorter than a metre."],
  },
  {
    id: "g4-maths-measurement-a-q02",
    prompt: "How many centimetres make 1 metre?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "100" },
      { id: "c", text: "1000" },
      { id: "d", text: "50" },
    ],
    answerId: "b",
    explanation: "1 metre = 100 centimetres.",
    hints: ["Remember the metric ladder for length.", "Centi means one-hundredth."],
  },
  {
    id: "g4-maths-measurement-a-q03",
    prompt: "How many millimetres make 1 centimetre?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "100" },
      { id: "c", text: "1000" },
      { id: "d", text: "5" },
    ],
    answerId: "a",
    explanation: "1 centimetre = 10 millimetres.",
    hints: ["Milli is a tiny length unit.", "Count how many mm fit in 1 cm."],
  },
  {
    id: "g4-maths-measurement-a-q04",
    prompt: "A school corridor is 25 m long. How many centimetres is that?",
    options: [
      { id: "a", text: "250 cm" },
      { id: "b", text: "2,500 cm" },
      { id: "c", text: "2500 m" },
      { id: "d", text: "25 cm" },
    ],
    answerId: "b",
    explanation: "25 × 100 = 2,500 cm.",
    hints: ["Convert metres to centimetres by multiplying by 100.", "25 × 100."],
  },
  {
    id: "g4-maths-measurement-a-q05",
    prompt: "Riya's water bottle holds 1 litre. How many millilitres is that?",
    options: [
      { id: "a", text: "10 ml" },
      { id: "b", text: "100 ml" },
      { id: "c", text: "1,000 ml" },
      { id: "d", text: "100 l" },
    ],
    answerId: "c",
    explanation: "1 litre = 1,000 millilitres.",
    hints: ["Litre and millilitre measure capacity.", "Milli means one-thousandth of a litre."],
  },
  {
    id: "g4-maths-measurement-a-q06",
    prompt: "Which is heavier: 1 kg of cotton or 1 kg of iron?",
    options: [
      { id: "a", text: "Cotton" },
      { id: "b", text: "Iron" },
      { id: "c", text: "They have the same mass" },
      { id: "d", text: "Cannot tell" },
    ],
    answerId: "c",
    explanation: "Both have a mass of 1 kg, so they are equally heavy.",
    hints: ["Mass is the amount of matter, not how fluffy it looks.", "Same kilogram means same mass."],
  },
  {
    id: "g4-maths-measurement-a-q07",
    prompt: "How many grams make 1 kilogram?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "100" },
      { id: "c", text: "1,000" },
      { id: "d", text: "10000" },
    ],
    answerId: "c",
    explanation: "1 kilogram = 1,000 grams.",
    hints: ["Kilo means one thousand.", "Mass: kg ↔ g."],
  },
  {
    id: "g4-maths-measurement-a-q08",
    prompt: "A sack of rice weighs 5 kg. How many grams is that?",
    options: [
      { id: "a", text: "50 g" },
      { id: "b", text: "500 g" },
      { id: "c", text: "5,000 g" },
      { id: "d", text: "50,000 g" },
    ],
    answerId: "c",
    explanation: "5 × 1,000 = 5,000 g.",
    hints: ["Multiply kilograms by 1,000 to get grams.", "5 × 1,000."],
  },
  {
    id: "g4-maths-measurement-a-q09",
    prompt: "Which unit measures capacity (how much a container holds)?",
    options: [
      { id: "a", text: "Metre" },
      { id: "b", text: "Gram" },
      { id: "c", text: "Litre" },
      { id: "d", text: "Second" },
    ],
    answerId: "c",
    explanation: "Litres (and millilitres) measure capacity.",
    hints: ["Capacity is about liquid volume.", "Think of milk packets and bottles."],
  },
  {
    id: "g4-maths-measurement-a-q10",
    prompt: "A ribbon is 3 m 40 cm long. What is its length in centimetres?",
    options: [
      { id: "a", text: "340 cm" },
      { id: "b", text: "304 cm" },
      { id: "c", text: "3,400 cm" },
      { id: "d", text: "43 cm" },
    ],
    answerId: "a",
    explanation: "3 m = 300 cm, plus 40 cm = 340 cm.",
    hints: ["Change metres to cm first, then add the leftover cm.", "3 × 100 + 40."],
  },
  {
    id: "g4-maths-measurement-a-q11",
    prompt: "Which is the longest length?",
    options: [
      { id: "a", text: "90 cm" },
      { id: "b", text: "1 m" },
      { id: "c", text: "80 cm" },
      { id: "d", text: "950 mm" },
    ],
    answerId: "b",
    explanation: "1 m = 100 cm, which is longer than 90 cm, 80 cm or 950 mm (95 cm).",
    hints: ["Convert all options to the same unit.", "1 m = 100 cm = 1,000 mm."],
  },
  {
    id: "g4-maths-measurement-a-q12",
    prompt: "Ammi buys 750 g of sugar and 250 g of tea. What is the total mass in grams?",
    options: [
      { id: "a", text: "900 g" },
      { id: "b", text: "1,000 g" },
      { id: "c", text: "500 g" },
      { id: "d", text: "1,250 g" },
    ],
    answerId: "b",
    explanation: "750 + 250 = 1,000 g (which is also 1 kg).",
    hints: ["Add the gram amounts.", "750 + 250."],
  },
  {
    id: "g4-maths-measurement-a-q13",
    prompt: "Which Indian traditional length unit is about the distance from elbow to fingertip?",
    options: [
      { id: "a", text: "Ser" },
      { id: "b", text: "Hath (cubit)" },
      { id: "c", text: "Maund" },
      { id: "d", text: "Tola" },
    ],
    answerId: "b",
    explanation: "A hath (cubit) is roughly elbow to fingertip — used in older Indian measuring.",
    hints: ["Think of body-based traditional measures.", "Elbow to fingertip is a cubit/hath."],
  },
  {
    id: "g4-maths-measurement-a-q14",
    prompt: "A jug has 2 l 500 ml of lemonade. How many millilitres is that in all?",
    options: [
      { id: "a", text: "2,500 ml" },
      { id: "b", text: "250 ml" },
      { id: "c", text: "7,500 ml" },
      { id: "d", text: "2,050 ml" },
    ],
    answerId: "a",
    explanation: "2 l = 2,000 ml, plus 500 ml = 2,500 ml.",
    hints: ["Convert litres to ml, then add.", "2 × 1,000 + 500."],
  },
  {
    id: "g4-maths-measurement-a-q15",
    prompt: "The distance from home to the park is best measured in…",
    options: [
      { id: "a", text: "Millimetres" },
      { id: "b", text: "Centimetres" },
      { id: "c", text: "Kilometres" },
      { id: "d", text: "Millilitres" },
    ],
    answerId: "c",
    explanation: "Road distances are measured in kilometres (or metres for shorter walks).",
    hints: ["Pick a unit that fits the journey size.", "Parks are usually many metres away."],
  },
  {
    id: "g4-maths-measurement-a-q16",
    prompt: "Convert 4,500 g to kilograms and grams.",
    options: [
      { id: "a", text: "4 kg 500 g" },
      { id: "b", text: "45 kg 0 g" },
      { id: "c", text: "4 kg 50 g" },
      { id: "d", text: "450 kg 0 g" },
    ],
    answerId: "a",
    explanation: "4,500 ÷ 1,000 = 4 kg with 500 g left.",
    hints: ["Every 1,000 g make 1 kg.", "4,500 = 4 × 1,000 + 500."],
  },
  {
    id: "g4-maths-measurement-a-q17",
    prompt: "A shopkeeper uses a balance scale. What does it compare?",
    options: [
      { id: "a", text: "Lengths" },
      { id: "b", text: "Masses" },
      { id: "c", text: "Times" },
      { id: "d", text: "Temperatures" },
    ],
    answerId: "b",
    explanation: "A balance compares masses (how heavy things are).",
    hints: ["Think of two pans and weights.", "Heaviness is mass."],
  },
  {
    id: "g4-maths-measurement-a-q18",
    prompt: "Which is the smallest capacity?",
    options: [
      { id: "a", text: "1 l" },
      { id: "b", text: "500 ml" },
      { id: "c", text: "2 l" },
      { id: "d", text: "1,500 ml" },
    ],
    answerId: "b",
    explanation: "500 ml is half a litre; the others are 1 l or more.",
    hints: ["Write every option in ml.", "1 l = 1,000 ml."],
  },
  {
    id: "g4-maths-measurement-a-q19",
    prompt: "A cricket pitch is about 20 m long. About how many centimetres is that?",
    options: [
      { id: "a", text: "20 cm" },
      { id: "b", text: "200 cm" },
      { id: "c", text: "2,000 cm" },
      { id: "d", text: "20,000 cm" },
    ],
    answerId: "c",
    explanation: "20 × 100 = 2,000 cm.",
    hints: ["m → cm: multiply by 100.", "20 × 100."],
  },
  {
    id: "g4-maths-measurement-a-q20",
    prompt: "Meera drinks 250 ml of milk each morning. How many days will 1 litre last?",
    options: [
      { id: "a", text: "2" },
      { id: "b", text: "4" },
      { id: "c", text: "5" },
      { id: "d", text: "8" },
    ],
    answerId: "b",
    explanation: "1,000 ml ÷ 250 ml = 4 days.",
    hints: ["Convert 1 litre to ml first.", "1,000 ÷ 250."],
  },
  {
    id: "g4-maths-measurement-a-q21",
    prompt: "Which statement is true?",
    options: [
      { id: "a", text: "1 km = 100 m" },
      { id: "b", text: "1 km = 1,000 m" },
      { id: "c", text: "1 km = 10 m" },
      { id: "d", text: "1 km = 1,000 cm" },
    ],
    answerId: "b",
    explanation: "1 kilometre = 1,000 metres.",
    hints: ["Kilo means one thousand.", "Length: km ↔ m."],
  },
  {
    id: "g4-maths-measurement-a-q22",
    prompt: "A parcel of books weighs 2 kg 300 g. Another weighs 1 kg 700 g. Total mass?",
    options: [
      { id: "a", text: "3 kg 1,000 g" },
      { id: "b", text: "4 kg" },
      { id: "c", text: "3 kg 900 g" },
      { id: "d", text: "4 kg 100 g" },
    ],
    answerId: "b",
    explanation: "2 kg 300 g + 1 kg 700 g = 3 kg 1,000 g = 4 kg.",
    hints: ["Add kg and g separately, then regroup 1,000 g as 1 kg.", "300 + 700 = 1,000 g."],
  },
  {
    id: "g4-maths-measurement-a-q23",
    prompt: "Which tool measures length most accurately for a notebook side?",
    options: [
      { id: "a", text: "Kitchen scale" },
      { id: "b", text: "Measuring tape or ruler" },
      { id: "c", text: "Clock" },
      { id: "d", text: "Thermometer" },
    ],
    answerId: "b",
    explanation: "A ruler or measuring tape measures length.",
    hints: ["Match the tool to what you measure.", "Length needs a ruler or tape."],
  },
  {
    id: "g4-maths-measurement-a-q24",
    prompt: "A tank holds 15 litres of water. How many 500 ml bottles can be filled from it?",
    options: [
      { id: "a", text: "15" },
      { id: "b", text: "20" },
      { id: "c", text: "30" },
      { id: "d", text: "50" },
    ],
    answerId: "c",
    explanation: "15 l = 15,000 ml; 15,000 ÷ 500 = 30 bottles.",
    hints: ["Convert litres to ml, then divide by 500.", "15,000 ÷ 500."],
  },
];

const SET_B: PrepQuestion[] = [
  {
    id: "g4-maths-measurement-b-q01",
    prompt: "Which unit is best for the mass of an apple?",
    options: [
      { id: "a", text: "Kilometre" },
      { id: "b", text: "Litre" },
      { id: "c", text: "Gram" },
      { id: "d", text: "Metre" },
    ],
    answerId: "c",
    explanation: "An apple's mass is usually given in grams.",
    hints: ["Mass of small foods is often in grams.", "Not length or capacity."],
  },
  {
    id: "g4-maths-measurement-b-q02",
    prompt: "How many metres make 1 kilometre?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "100" },
      { id: "c", text: "1,000" },
      { id: "d", text: "10,000" },
    ],
    answerId: "c",
    explanation: "1 kilometre = 1,000 metres.",
    hints: ["Kilo means one thousand.", "km ↔ m."],
  },
  {
    id: "g4-maths-measurement-b-q03",
    prompt: "Convert 8 m 5 cm to centimetres.",
    options: [
      { id: "a", text: "85 cm" },
      { id: "b", text: "805 cm" },
      { id: "c", text: "850 cm" },
      { id: "d", text: "8,005 cm" },
    ],
    answerId: "b",
    explanation: "8 m = 800 cm, plus 5 cm = 805 cm.",
    hints: ["Multiply metres by 100, then add cm.", "800 + 5."],
  },
  {
    id: "g4-maths-measurement-b-q04",
    prompt: "A bottle label says 750 ml. What fraction of a litre is that?",
    options: [
      { id: "a", text: "1/2 litre" },
      { id: "b", text: "3/4 litre" },
      { id: "c", text: "1/4 litre" },
      { id: "d", text: "1 litre" },
    ],
    answerId: "b",
    explanation: "750 ml out of 1,000 ml is 3/4 of a litre.",
    hints: ["1 litre = 1,000 ml.", "750/1000 simplifies to 3/4."],
  },
  {
    id: "g4-maths-measurement-b-q05",
    prompt: "Which is heavier?",
    options: [
      { id: "a", text: "800 g" },
      { id: "b", text: "1 kg" },
      { id: "c", text: "900 g" },
      { id: "d", text: "950 g" },
    ],
    answerId: "b",
    explanation: "1 kg = 1,000 g, which is more than 800 g, 900 g or 950 g.",
    hints: ["Convert kg to grams to compare.", "1 kg = 1,000 g."],
  },
  {
    id: "g4-maths-measurement-b-q06",
    prompt: "Kabir walks 2 km to school and 2 km back. How many metres does he walk in all?",
    options: [
      { id: "a", text: "4 m" },
      { id: "b", text: "400 m" },
      { id: "c", text: "4,000 m" },
      { id: "d", text: "40 m" },
    ],
    answerId: "c",
    explanation: "2 + 2 = 4 km = 4,000 m.",
    hints: ["Add the distances, then convert km to m.", "4 × 1,000."],
  },
  {
    id: "g4-maths-measurement-b-q07",
    prompt: "A traditional Indian mass unit still used in jewellery shops is the…",
    options: [
      { id: "a", text: "Metre" },
      { id: "b", text: "Tola" },
      { id: "c", text: "Litre" },
      { id: "d", text: "Hectare" },
    ],
    answerId: "b",
    explanation: "A tola is a traditional Indian unit of mass used for gold and silver.",
    hints: ["Jewellery mass has traditional names.", "Tola is linked to precious metals."],
  },
  {
    id: "g4-maths-measurement-b-q08",
    prompt: "Fill the blank: 3,200 ml = ___ l ___ ml",
    options: [
      { id: "a", text: "3 l 200 ml" },
      { id: "b", text: "32 l 0 ml" },
      { id: "c", text: "2 l 300 ml" },
      { id: "d", text: "3 l 20 ml" },
    ],
    answerId: "a",
    explanation: "3,200 ÷ 1,000 = 3 l with 200 ml left.",
    hints: ["Group millilitres into thousands for litres.", "3 × 1,000 + 200."],
  },
  {
    id: "g4-maths-measurement-b-q09",
    prompt: "Which length is equal to 1 m 25 cm?",
    options: [
      { id: "a", text: "125 mm" },
      { id: "b", text: "125 cm" },
      { id: "c", text: "1,025 cm" },
      { id: "d", text: "25 m" },
    ],
    answerId: "b",
    explanation: "1 m 25 cm = 100 cm + 25 cm = 125 cm.",
    hints: ["Convert the metre part to cm.", "100 + 25."],
  },
  {
    id: "g4-maths-measurement-b-q10",
    prompt: "A recipe needs 1/2 kg of atta. How many grams is that?",
    options: [
      { id: "a", text: "50 g" },
      { id: "b", text: "500 g" },
      { id: "c", text: "5,000 g" },
      { id: "d", text: "250 g" },
    ],
    answerId: "b",
    explanation: "1/2 of 1,000 g = 500 g.",
    hints: ["Half a kilogram is half of 1,000 g.", "1,000 ÷ 2."],
  },
  {
    id: "g4-maths-measurement-b-q11",
    prompt: "Which container holds more: a 2 litre can or eight 200 ml cups?",
    options: [
      { id: "a", text: "2 litre can" },
      { id: "b", text: "Eight 200 ml cups" },
      { id: "c", text: "They hold the same" },
      { id: "d", text: "Cannot tell" },
    ],
    answerId: "a",
    explanation: "2 l = 2,000 ml, but eight × 200 ml = 1,600 ml, so the can holds more.",
    hints: ["Convert both to ml and compare.", "2 l = 2,000 ml; 8 × 200 = 1,600 ml."],
  },
  {
    id: "g4-maths-measurement-b-q12",
    prompt: "Sana measures a table as 120 cm. What is that in metres and centimetres?",
    options: [
      { id: "a", text: "1 m 20 cm" },
      { id: "b", text: "12 m 0 cm" },
      { id: "c", text: "1 m 2 cm" },
      { id: "d", text: "2 m 10 cm" },
    ],
    answerId: "a",
    explanation: "120 cm = 1 m + 20 cm.",
    hints: ["Every 100 cm make 1 metre.", "120 = 100 + 20."],
  },
  {
    id: "g4-maths-measurement-b-q13",
    prompt: "A milkman delivers 5 litres of milk. How many 250 ml pouches is that?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "15" },
      { id: "c", text: "20" },
      { id: "d", text: "25" },
    ],
    answerId: "c",
    explanation: "5,000 ml ÷ 250 ml = 20 pouches.",
    hints: ["Convert litres to ml, then divide.", "5,000 ÷ 250."],
  },
  {
    id: "g4-maths-measurement-b-q14",
    prompt: "Which is a unit of mass?",
    options: [
      { id: "a", text: "Centimetre" },
      { id: "b", text: "Kilogram" },
      { id: "c", text: "Litre" },
      { id: "d", text: "Kilometre" },
    ],
    answerId: "b",
    explanation: "Kilogram measures mass.",
    hints: ["Mass is how heavy something is.", "kg and g are mass units."],
  },
  {
    id: "g4-maths-measurement-b-q15",
    prompt: "The height of a classroom door is about…",
    options: [
      { id: "a", text: "2 mm" },
      { id: "b", text: "2 cm" },
      { id: "c", text: "2 m" },
      { id: "d", text: "2 km" },
    ],
    answerId: "c",
    explanation: "A door is roughly about 2 metres high.",
    hints: ["Picture walking through a door.", "Metres fit human-sized heights."],
  },
  {
    id: "g4-maths-measurement-b-q16",
    prompt: "Subtract: 5 kg − 1 kg 250 g = ?",
    options: [
      { id: "a", text: "3 kg 750 g" },
      { id: "b", text: "4 kg 750 g" },
      { id: "c", text: "3 kg 250 g" },
      { id: "d", text: "4 kg 250 g" },
    ],
    answerId: "a",
    explanation: "5 kg = 4 kg 1,000 g; 4 kg 1,000 g − 1 kg 250 g = 3 kg 750 g.",
    hints: ["Borrow 1 kg as 1,000 g if needed.", "4,000 g − 250 g = 750 g leftover with 3 kg."],
  },
  {
    id: "g4-maths-measurement-b-q17",
    prompt: "How many centimetres make 3 metres?",
    options: [
      { id: "a", text: "30" },
      { id: "b", text: "300" },
      { id: "c", text: "3,000" },
      { id: "d", text: "3000 m" },
    ],
    answerId: "b",
    explanation: "3 × 100 = 300 cm.",
    hints: ["Multiply metres by 100.", "3 × 100."],
  },
  {
    id: "g4-maths-measurement-b-q18",
    prompt: "A water can has 4 l. After filling six glasses of 200 ml each, how much is left?",
    options: [
      { id: "a", text: "2,800 ml" },
      { id: "b", text: "1,200 ml" },
      { id: "c", text: "3,200 ml" },
      { id: "d", text: "800 ml" },
    ],
    answerId: "a",
    explanation: "6 × 200 = 1,200 ml used; 4,000 − 1,200 = 2,800 ml left.",
    hints: ["Find how much was poured out, then subtract from 4 l.", "4,000 − 1,200."],
  },
  {
    id: "g4-maths-measurement-b-q19",
    prompt: "Which pair shows equal lengths?",
    options: [
      { id: "a", text: "1 m and 10 cm" },
      { id: "b", text: "1 m and 100 cm" },
      { id: "c", text: "1 m and 1,000 cm" },
      { id: "d", text: "1 m and 100 mm" },
    ],
    answerId: "b",
    explanation: "1 metre equals 100 centimetres.",
    hints: ["Use the standard conversion.", "1 m = 100 cm."],
  },
  {
    id: "g4-maths-measurement-b-q20",
    prompt: "A flour bag shows 10 kg. How many 500 g packs can be made from it?",
    options: [
      { id: "a", text: "10" },
      { id: "b", text: "15" },
      { id: "c", text: "20" },
      { id: "d", text: "25" },
    ],
    answerId: "c",
    explanation: "10 kg = 10,000 g; 10,000 ÷ 500 = 20 packs.",
    hints: ["Convert kg to g, then divide by 500.", "10,000 ÷ 500."],
  },
  {
    id: "g4-maths-measurement-b-q21",
    prompt: "On a map, 1 cm stands for 1 km. A road drawn as 7 cm is how long in real life?",
    options: [
      { id: "a", text: "7 m" },
      { id: "b", text: "70 m" },
      { id: "c", text: "7 km" },
      { id: "d", text: "700 km" },
    ],
    answerId: "c",
    explanation: "Each centimetre on the map means 1 km, so 7 cm means 7 km.",
    hints: ["Multiply map cm by the scale value.", "7 × 1 km."],
  },
  {
    id: "g4-maths-measurement-b-q22",
    prompt: "Which is the best estimate for the capacity of a school water bottle?",
    options: [
      { id: "a", text: "5 ml" },
      { id: "b", text: "50 ml" },
      { id: "c", text: "500 ml" },
      { id: "d", text: "50 l" },
    ],
    answerId: "c",
    explanation: "A child's water bottle is often around half a litre (about 500 ml).",
    hints: ["Picture a lunch-box water bottle.", "Hundreds of ml, not litres of tank size."],
  },
  {
    id: "g4-maths-measurement-b-q23",
    prompt: "Add: 2 m 60 cm + 1 m 55 cm = ?",
    options: [
      { id: "a", text: "3 m 115 cm" },
      { id: "b", text: "4 m 15 cm" },
      { id: "c", text: "3 m 15 cm" },
      { id: "d", text: "4 m 5 cm" },
    ],
    answerId: "b",
    explanation: "60 + 55 = 115 cm = 1 m 15 cm; total metres 2 + 1 + 1 = 4 m 15 cm.",
    hints: ["Add cm, regroup every 100 cm as 1 m.", "115 cm → 1 m 15 cm."],
  },
  {
    id: "g4-maths-measurement-b-q24",
    prompt: "Papa buys vegetables of 2 kg 400 g and fruits of 1 kg 600 g. Total mass?",
    options: [
      { id: "a", text: "3 kg" },
      { id: "b", text: "4 kg" },
      { id: "c", text: "3 kg 1,000 g" },
      { id: "d", text: "4 kg 100 g" },
    ],
    answerId: "b",
    explanation: "2 kg 400 g + 1 kg 600 g = 3 kg 1,000 g = 4 kg.",
    hints: ["Add, then convert 1,000 g into an extra kilogram.", "400 + 600 = 1,000 g."],
  },
];

const lesson: ChapterDef["lesson"] = [
  {
    id: "h",
    type: "hook",
    emoji: "📏",
    title: "How long, how heavy, how much?",
    body: [
      "We measure length, mass and capacity with the right units.",
      "Metric units join Indian kitchen and road stories — and a few traditional names.",
      "Lesson is optional; jump to a set anytime.",
    ],
    cta: "Let's measure!",
    visual: "balance",
    speak: "We measure length, mass and capacity with the right units. Metric units join Indian kitchen and road stories.",
  },
  {
    id: "r1",
    type: "reveal",
    title: "Three kinds of measure",
    lead: "Tap each card.",
    visual: "balance",
    speak: "Length uses millimetre, centimetre, metre and kilometre. Mass uses gram and kilogram. Capacity uses millilitre and litre.",
    cards: [
      { label: "Length", reveal: "mm · cm · m · km — how long or how far", emoji: "📐" },
      { label: "Mass", reveal: "g · kg — how heavy (balance or scale)", emoji: "⚖️" },
      { label: "Capacity", reveal: "ml · l — how much a container holds", emoji: "🧴" },
      { label: "Indian units", reveal: "Hath for length; tola for jewellery mass", emoji: "🪔" },
    ],
  },
  {
    id: "d1",
    type: "demo",
    title: "Conversions you need",
    visual: "number-line",
    speak: "One metre is one hundred centimetres. One kilometre is one thousand metres. One kilogram is one thousand grams. One litre is one thousand millilitres.",
    steps: [
      "1 m = 100 cm · 1 cm = 10 mm",
      "1 km = 1,000 m",
      "1 kg = 1,000 g",
      "1 l = 1,000 ml",
    ],
    punchline: "Same amount, different unit labels.",
  },
  {
    id: "t1",
    type: "try",
    title: "Your turn",
    prompt: "A bottle holds 2 l. How many millilitres is that?",
    options: [
      { id: "a", text: "20 ml" },
      { id: "b", text: "200 ml" },
      { id: "c", text: "2,000 ml" },
      { id: "d", text: "20,000 ml" },
    ],
    answerId: "c",
    why: "2 × 1,000 = 2,000 ml.",
    visual: "balance",
    speak: "A bottle holds two litres. How many millilitres is that?",
  },
  {
    id: "d2",
    type: "demo",
    title: "Choose the sensible unit",
    visual: "balance",
    speak: "Pencils use centimetres. Roads use kilometres. Apples use grams. Milk packets use millilitres or litres. Matching the unit to the object keeps answers sensible.",
    steps: [
      "Pencil → cm (not km)",
      "City distance → km",
      "Apple → g; sack of rice → kg",
      "Water bottle → ml or l",
    ],
    punchline: "Right unit, clear answer.",
  },
  {
    id: "c1",
    type: "check",
    title: "Quick check",
    visual: "balance",
    speak: "A ribbon is three metres forty centimetres. How many centimetres is that?",
    question: {
      id: "g4-meas-check",
      prompt: "A ribbon is 3 m 40 cm. How many centimetres is that?",
      options: [
        { id: "a", text: "340 cm" },
        { id: "b", text: "304 cm" },
        { id: "c", text: "3,400 cm" },
        { id: "d", text: "43 cm" },
      ],
      answerId: "a",
      explanation: "3 m = 300 cm, plus 40 cm = 340 cm.",
      hints: ["Change metres to centimetres first.", "3 × 100 + 40."],
    },
  },
  {
    id: "w",
    type: "wrap",
    emoji: "⭐",
    title: "Measure master!",
    bullets: [
      "Length, mass and capacity need different units",
      "Know the ×1000 and ×100 conversions",
      "Pick sensible units for length, mass and capacity",
      "Set A and Set B ready — 24 MCQs each",
    ],
    cta: "Back to chapter",
    speak: "You can choose units and convert. Set A and Set B are ready.",
  },
];


export const g4MathsMeasurement: ChapterDef = {
  id: "g4-measurement",
  title: "Measurement",
  emoji: "📏",
  blurb: "Length, mass, capacity & conversions",
  lesson,
  sets: [
    {
      id: "set-a",
      title: "Set A",
      questionCount: SET_A.length,
      topic: "measurement",
      questions: SET_A,
    },
    {
      id: "set-b",
      title: "Set B",
      questionCount: SET_B.length,
      topic: "measurement",
      questions: SET_B,
    },
  ],
  paperTopics: ["measurement", "place-value"],
};

export const g4MathsMeasurementQuestions: PrepQuestion[] = [...SET_A, ...SET_B];

