#!/usr/bin/env python3
"""Grade 10 Science: Chemical Reactions, Life Processes, Light."""
from __future__ import annotations
from .emit import q, emit_chapter, lesson_ts


def chemical_reactions():
    A, B = [], []
    A += [
        q("A chemical reaction in which heat is absorbed is called —",
          ["endothermic", "exothermic", "displacement", "neutralisation"],
          "a", "Endothermic reactions take in heat from the surroundings.", "Endo = heat in; exo = heat out."),
        q("Rusting of iron is an example of —",
          ["oxidation / corrosion", "reduction only", "sublimation", "distillation"],
          "a", "Iron reacts with oxygen and moisture to form hydrated iron oxide (rust).", "Rusting is slow oxidation in moist air."),
        q("In the reaction Zn + CuSO₄ → ZnSO₄ + Cu, zinc —",
          ["displaces copper", "is reduced", "acts as an acid", "sublimes"],
          "a", "More reactive Zn displaces Cu from CuSO₄.", "Compare reactivity: Zn above Cu in the series."),
        q("Balanced equation for hydrogen burning in oxygen is —",
          ["2H₂ + O₂ → 2H₂O", "H₂ + O₂ → H₂O", "H₂ + O → H₂O", "2H₂ + O₂ → H₂O₂"],
          "a", "Two H₂ molecules need one O₂ to make two H₂O.", "Count atoms on both sides."),
        q("Quicklime reacts with water to give —",
          ["slaked lime (Ca(OH)₂) with heat release", "limestone", "CO₂ only", "CaO₂"],
          "a", "CaO + H₂O → Ca(OH)₂ is highly exothermic.", "Quicklime is CaO; adding water slakes it."),
        q("Which is a decomposition reaction?",
          ["2Pb(NO₃)₂ → 2PbO + 4NO₂ + O₂", "Zn + CuSO₄ → ZnSO₄ + Cu", "NaOH + HCl → NaCl + H₂O", "Fe + S → FeS"],
          "a", "One compound breaks into simpler products.", "Decomposition: one reactant → multiple products."),
        q("Oxidation is —",
          ["gain of oxygen or loss of hydrogen/electrons", "only gain of hydrogen", "only loss of oxygen", "melting"],
          "a", "Classical and electronic definitions of oxidation.", "OIL RIG: Oxidation Is Loss (of electrons)."),
        q("Rancidity in oils and fats is due to —",
          ["oxidation", "reduction by sugars", "neutralisation", "sublimation"],
          "a", "Fats oxidise when exposed to air, causing off smells.", "Air and light speed up rancidity."),
        q("A redox reaction involves —",
          ["both oxidation and reduction", "only oxidation", "only precipitation", "only neutralisation"],
          "a", "Oxidation and reduction occur together.", "Electrons lost by one species are gained by another."),
        q("Which observation suggests a chemical change?",
          ["gas evolution with new substance formed", "ice melting", "salt dissolving", "water boiling"],
          "a", "New substances (and often gas/heat/colour change) mark chemical change.", "Physical changes don't make new substances."),
        q("Fe₂O₃ + 2Al → 2Fe + Al₂O₃ is used in —",
          ["thermit welding", "photosynthesis", "electroplating only", "soap making"],
          "a", "Highly exothermic displacement (thermite) welds rails.", "Aluminium reduces iron oxide, releasing intense heat."),
        q("Acid + base → salt + water is —",
          ["neutralisation", "displacement", "decomposition", "double? also a double displacement"],
          "a", "Classic neutralisation definition.", "H⁺ from acid and OH⁻ from base form water."),
        q("Which metal is most reactive among Na, Cu, Au?",
          ["Na", "Cu", "Au", "all equal"],
          "a", "Sodium sits high in the reactivity series; gold is least reactive of these.", "Reactivity: Na ≫ Cu > Au."),
        q("Precipitation reactions typically are —",
          ["double displacement forming an insoluble salt", "only combustion", "only electrolysis", "sublimation"],
          "a", "Ions swap and an insoluble product settles out.", "Look for a cloudy solid forming in solution."),
        q("Burning of magnesium ribbon in air produces —",
          ["MgO (white ash) with bright light", "MgCl₂", "only soot", "MgSO₄"],
          "a", "2Mg + O₂ → 2MgO, highly exothermic with white light.", "Magnesium oxidises to magnesium oxide."),
        q("In electrolysis of water, the gas at the cathode is —",
          ["hydrogen", "oxygen", "chlorine", "nitrogen"],
          "a", "H⁺ ions gain electrons at the cathode → H₂.", "Cathode = reduction = hydrogen in water electrolysis."),
        q("Which prevents rancidity?",
          ["adding antioxidants / airtight packing", "leaving oil open in sun", "heating repeatedly with air", "adding more oxygen"],
          "a", "Limit oxygen exposure or add antioxidants.", "Keep fats cool, dark, and sealed."),
        q("CuO + H₂ → Cu + H₂O: hydrogen acts as —",
          ["a reducing agent", "an oxidising agent", "a catalyst only", "an acid"],
          "a", "H₂ removes oxygen from CuO, so H₂ is oxidised and CuO reduced.", "Reducing agent donates electrons / removes oxygen."),
        q("The brown gas in thermal decomposition of lead nitrate is —",
          ["NO₂", "N₂", "O₂ only", "CO₂"],
          "a", "2Pb(NO₃)₂ → 2PbO + 4NO₂ + O₂; NO₂ is brown.", "Nitrate decomposition often releases brown NO₂."),
        q("Combination reaction example:",
          ["C + O₂ → CO₂", "CaCO₃ → CaO + CO₂", "Zn + H₂SO₄ → ZnSO₄ + H₂", "AgNO₃ + NaCl → AgCl + NaNO₃"],
          "a", "Two or more substances combine into one.", "Combination: many reactants → one product."),
        q("Whitewashing uses which reaction after slaked lime on walls?",
          ["Ca(OH)₂ + CO₂ → CaCO₃ + H₂O", "CaCO₃ → CaO + CO₂", "Ca + H₂O → Ca(OH)₂", "CaO + SiO₂ → slag"],
          "a", "Carbon dioxide turns slaked lime into hard CaCO₃.", "Walls harden as carbonate forms."),
        q("Galvanisation protects iron by coating with —",
          ["zinc", "copper only", "silver", "lead"],
          "a", "Zinc coating (galvanising) sacrificially protects iron.", "Zn is more reactive and oxidises first."),
        q("In 2Na + 2H₂O → 2NaOH + H₂, sodium is —",
          ["oxidised", "reduced", "a catalyst", "precipitated"],
          "a", "Na loses electrons to form Na⁺ in NaOH.", "Metal → ion is oxidation."),
        q("Balancing: __ Fe + __ H₂O → __ Fe₃O₄ + __ H₂. Coefficients are —",
          ["3, 4, 1, 4", "1, 1, 1, 1", "2, 3, 1, 3", "3, 2, 1, 2"],
          "a", "3Fe + 4H₂O → Fe₃O₄ + 4H₂.", "Balance Fe, then O, then H."),
    ]
    B += [
        q("Exothermic reactions —",
          ["release heat to surroundings", "always absorb heat", "never change temperature", "only occur in darkness"],
          "a", "Energy is given out as heat/light.", "Exo = heat exits the system."),
        q("Which is NOT a chemical change?",
          ["melting of wax", "burning of wax", "rusting of iron", "digestion of food"],
          "a", "Melting is physical; composition stays CₙHₘ.", "Ask: was a new substance formed?"),
        q("Double displacement: BaCl₂ + Na₂SO₄ → —",
          ["BaSO₄↓ + 2NaCl", "BaSO₄ + NaCl only unbalanced", "Ba + Cl₂", "Na₂Ba"],
          "a", "BaSO₄ precipitates; sodium chloride stays dissolved.", "Swap ions; barium sulphate is insoluble."),
        q("Corrosion of copper in moist air forms a green coating of —",
          ["basic copper carbonate", "copper sulphate only", "pure copper oxide black only always", "copper metal"],
          "a", "Patina is basic copper carbonate (and related compounds).", "Think Statue of Liberty green layer."),
        q("In the reactivity series, which displaces H₂ from dilute acids most readily among Zn, Cu, Ag?",
          ["Zn", "Cu", "Ag", "none"],
          "a", "Zn is above hydrogen; Cu and Ag are below.", "Metals above H₂ liberate hydrogen from dilute acids."),
        q("Photosynthesis is overall —",
          ["endothermic (needs sunlight)", "exothermic like burning", "a displacement of metals", "electrolysis"],
          "a", "Light energy is absorbed to make glucose.", "Plants store light energy in chemical bonds."),
        q("Identifying gases: a gas that turns limewater milky is —",
          ["CO₂", "H₂", "O₂", "N₂"],
          "a", "CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O.", "Limewater test for carbon dioxide."),
        q("H₂ gas burns with a —",
          ["pop sound", "green flame only", "no reaction", "purple smoke always"],
          "a", "Classic pop test for hydrogen.", "Collect and ignite carefully — pop confirms H₂."),
        q("Oxygen relights a glowing splint because it —",
          ["supports combustion", "is inert", "is acidic", "is a noble gas"],
          "a", "O₂ is needed for combustion to resume.", "Glowing splint test for oxygen."),
        q("Neutralisation of HCl with NaOH produces —",
          ["NaCl and H₂O", "NaOH only", "Cl₂ gas", "H₂ only"],
          "a", "HCl + NaOH → NaCl + H₂O.", "Acid + base → salt + water."),
        q("Which equation is balanced?",
          ["CH₄ + 2O₂ → CO₂ + 2H₂O", "CH₄ + O₂ → CO₂ + H₂O", "CH₄ + 2O₂ → CO₂ + H₂O", "C + O₂ → CO"],
          "a", "C:1, H:4, O:4 on both sides.", "Count each element after balancing."),
        q("Electrolytic refining of copper uses —",
          ["impure Cu anode, pure Cu cathode, CuSO₄ electrolyte", "iron electrodes", "only water", "zinc anode always"],
          "a", "Cu dissolves from anode and deposits pure on cathode.", "Anode oxidises; cathode reduces Cu²⁺."),
        q("A shiny brown coin turns green: the change is mainly —",
          ["chemical (corrosion)", "only physical polishing loss", "melting", "magnetic"],
          "a", "Surface compounds form — a chemical change.", "Colour change from new compounds = chemical."),
        q("In MnO₂ + 4HCl → MnCl₂ + 2H₂O + Cl₂, MnO₂ acts as —",
          ["an oxidising agent", "a reducing agent", "an acid", "a base"],
          "a", "MnO₂ oxidises Cl⁻ to Cl₂ and is itself reduced.", "Oxidising agent gets reduced."),
        q("Food cans are coated with tin because tin is —",
          ["less reactive and non-toxic lining", "more reactive than iron always for food", "magnetic", "a gas"],
          "a", "Tin plating protects and is food-safe.", "Tin is less reactive in this use context."),
        q("Respiration is overall —",
          ["exothermic", "endothermic", "neutralisation", "sublimation"],
          "a", "Glucose oxidation releases energy for cells.", "Living cells release heat/energy from food."),
        q("Which pair is a redox pair in ZnO + C → Zn + CO?",
          ["C oxidised, ZnO reduced", "both oxidised", "both reduced", "neither"],
          "a", "Carbon gains oxygen (oxidised); ZnO loses oxygen (reduced).", "Track oxygen transfer."),
        q("Dilute H₂SO₄ on zinc liberates a gas that —",
          ["burns with a pop", "turns limewater milky", "relights a glowing splint", "bleaches litmus permanently as Cl₂"],
          "a", "Zn + H₂SO₄ → ZnSO₄ + H₂.", "Hydrogen gives the pop test."),
        q("Marble chips with dilute HCl produce —",
          ["CO₂", "O₂", "H₂", "N₂"],
          "a", "CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂.", "Carbonates + acid → carbon dioxide."),
        q("Black CuO heated with hydrogen becomes brownish Cu. This shows —",
          ["reduction of CuO", "oxidation of CuO", "CuO sublimed", "neutralisation"],
          "a", "CuO loses oxygen → copper metal.", "Loss of oxygen = reduction of the oxide."),
        q("Antacids work mainly by —",
          ["neutralising excess stomach acid", "oxidising food", "reducing enzymes", "precipitating gold"],
          "a", "Bases like Mg(OH)₂ neutralise HCl.", "Think acid–base neutralisation."),
        q("Which is an example of a photochemical reaction?",
          ["2AgBr → 2Ag + Br₂ (light)", "rusting in a closed box", "dissolving sugar", "melting ice"],
          "a", "Silver bromide decomposes in light (photography).", "Photo = driven by light."),
        q("To balance Al + Fe₂O₃ → Al₂O₃ + Fe, correct coefficients include —",
          ["2Al + Fe₂O₃ → Al₂O₃ + 2Fe", "Al + Fe₂O₃ → Al₂O₃ + Fe", "3Al + Fe₂O₃ → …", "4Al + …"],
          "a", "2 Al atoms make one Al₂O₃; Fe₂O₃ gives 2 Fe.", "Balance Al and Fe together."),
        q("Chips bags are flushed with nitrogen to —",
          ["prevent oxidation / rancidity", "add nutrients", "make them heavier", "cause rusting"],
          "a", "Inert N₂ displaces oxygen that would oxidise fats.", "Less oxygen → slower spoilage."),
    ]
    lesson = lesson_ts(
        "Chemical Reactions", "⚗️", "atom-lite",
        "Atoms rearrange. Balance equations and spot redox, heat, and precipitates.",
        [("Types", "Combine, decompose, displace, double displace", "🔀"),
         ("Redox", "Oxidation and reduction together", "🔋"),
         ("Energy", "Exo releases heat; endo absorbs", "🌡️"),
         ("Everyday", "Rust, rancidity, neutralisation", "🏠")],
        {"prompt": "Rusting of iron needs —",
         "options": [("a", "air and moisture"), ("b", "only darkness"), ("c", "only pure N₂"), ("d", "vacuum")],
         "answerId": "a", "why": "Oxygen and water together drive rust formation."},
        ["Reactions toolkit", "Balance atoms", "Spot redox", "Protect from rust & rancidity"],
    )
    outline = """
### step_1: Evidence of a reaction
- **tts**: Colour change, gas, precipitate, or heat can signal a chemical change.
- **check**: Is melting ice chemical? — Answer: No

### step_2: Types of reactions
- **tts**: Combination, decomposition, displacement, double displacement.
- **check**: CaCO₃ heat → CaO + CO₂ is which type? — Answer: Decomposition

### step_3: Redox and corrosion
- **tts**: Oxidation and reduction travel together. Rust is slow oxidation.
- **check**: Does painting iron slow rust? — Answer: Yes
"""
    return emit_chapter(
        file="g10-science-chem-reactions.ts",
        export="g10ScienceChemReactions",
        doc="science-ch01-chemical-reactions.md",
        meta={"id": "chem-reactions", "title": "Chemical Reactions", "emoji": "⚗️",
              "blurb": "Balance, redox, rust & rancidity", "topic": "matter-lite",
              "paperTopics": ["matter-lite"], "subjectLabel": "Science"},
        lesson=lesson, set_a_raw=A, set_b_raw=B, prefix="g10-sci-chem",
        lesson_outline=outline,
    )


def life_processes():
    A, B = [], []
    A += [
        q("The process of obtaining and using food in living organisms is called —",
          ["nutrition", "excretion only", "transpiration only", "phototropism"],
          "a", "Nutrition covers intake and utilisation of food.", "Nutrition = how organisms get energy materials."),
        q("Autotrophs —",
          ["make their own food (e.g. photosynthesis)", "only eat animals", "cannot use sunlight", "lack chlorophyll always"],
          "a", "Green plants and some bacteria fix energy into food.", "Auto = self-feeding."),
        q("The site of photosynthesis in a plant cell is the —",
          ["chloroplast", "mitochondrion", "nucleus", "ribosome"],
          "a", "Chlorophyll in chloroplasts captures light.", "Green plastids do photosynthesis."),
        q("Stomata mainly help in —",
          ["gas exchange and transpiration", "absorbing minerals from soil", "storing starch only", "transporting food in phloem exclusively"],
          "a", "Pores on leaves exchange CO₂/O₂ and release water vapour.", "Guard cells open and close stomata."),
        q("In humans, proteins are mainly digested by —",
          ["pepsin and trypsin", "amylase only", "lipase only", "bile salts only"],
          "a", "Pepsin (stomach) and trypsin (intestine) cleave proteins.", "Proteases digest proteins."),
        q("Bile is produced by the —",
          ["liver", "pancreas", "stomach", "kidney"],
          "a", "Liver makes bile; gall bladder stores it.", "Bile emulsifies fats."),
        q("The respiratory pigment in human blood is —",
          ["haemoglobin", "chlorophyll", "insulin", "pepsin"],
          "a", "Haemoglobin in RBCs carries oxygen.", "Iron-containing pigment binds O₂."),
        q("Aerobic respiration yields more energy because —",
          ["glucose is fully oxidised using oxygen", "no oxygen is used", "only fermentation occurs", "ATP is not involved"],
          "a", "Complete oxidation to CO₂ and H₂O releases more ATP.", "Aerobic = with oxygen."),
        q("In anaerobic respiration in muscle, glucose forms —",
          ["lactic acid", "alcohol and CO₂ always in muscle", "only water", "urea"],
          "a", "Oxygen debt leads to lactic acid in muscles.", "Yeast makes alcohol; muscles make lactate."),
        q("Xylem transports —",
          ["water and minerals upward", "food downward only", "oxygen only", "urea"],
          "a", "Xylem sap moves from roots toward leaves.", "Xylem = water highway."),
        q("Phloem transports —",
          ["food (sugars) to plant parts", "only water upward", "only minerals", "carbon dioxide soilward"],
          "a", "Translocation moves sucrose via phloem.", "Phloem = food highway."),
        q("The functional unit of the kidney is the —",
          ["nephron", "neuron", "alveolus", "villus"],
          "a", "Nephrons filter blood and form urine.", "Each kidney has about a million nephrons."),
        q("Blood is pumped from left ventricle to the body through the —",
          ["aorta", "pulmonary artery", "vena cava", "pulmonary vein"],
          "a", "Aorta is the main systemic artery.", "Left ventricle → aorta → body."),
        q("Pulmonary artery carries —",
          ["deoxygenated blood to lungs", "oxygenated blood to body", "oxygenated blood to lungs", "lymph"],
          "a", "Right ventricle → pulmonary artery → lungs.", "Pulmonary artery is the exception: artery with deoxygenated blood."),
        q("Villi in the small intestine —",
          ["increase surface area for absorption", "produce bile", "filter urea", "pump blood"],
          "a", "Finger-like folds maximise nutrient uptake.", "More area → faster absorption."),
        q("Transpiration helps in —",
          ["ascent of sap and cooling", "photosynthesis dark reaction only", "protein synthesis", "nerve impulse"],
          "a", "Water loss pulls the xylem stream and cools leaves.", "Evaporation from leaves drives pull."),
        q("Human excretory wastes include —",
          ["urea", "glucose as main waste", "oxygen", "starch"],
          "a", "Nitrogenous waste urea is removed in urine.", "Liver makes urea; kidneys excrete it."),
        q("Platelets help in —",
          ["blood clotting", "carrying oxygen", "fighting all viruses alone", "digesting fat"],
          "a", "Platelets trigger clot formation at wounds.", "Clotting prevents blood loss."),
        q("The breakdown of pyruvate in mitochondria (with O₂) yields —",
          ["CO₂, H₂O and energy (ATP)", "only lactic acid", "only alcohol", "starch"],
          "a", "Krebs cycle / aerobic path in mitochondria.", "Mitochondria = aerobic ATP factories."),
        q("Heterotrophs —",
          ["depend on other organisms for food", "always photosynthesise", "make food from CO₂ only", "need no energy"],
          "a", "Animals and fungi are heterotrophs.", "Hetero = other-feeding."),
        q("Salivary amylase begins digestion of —",
          ["starch", "protein", "fat", "vitamins"],
          "a", "Amylase converts starch toward maltose in the mouth.", "Amylium = starch."),
        q("Double circulation in humans means —",
          ["blood passes thrice? No — twice through heart per circuit: pulmonary + systemic", "blood never enters lungs", "only veins carry blood", "no valves"],
          "a", "Separate pulmonary and systemic loops; heart handled twice per full circuit.",
          "Lungs path and body path are separate."),
        q("Guard cells control —",
          ["stomatal opening", "heart rate", "urine volume only", "bone growth"],
          "a", "Turgid guard cells open the stoma.", "Kidney-bean shaped cells around the pore."),
        q("Dialysis is used when —",
          ["kidneys fail to filter blood", "liver makes too much bile", "lungs lack alveoli temporarily for fun", "stomach lacks acid"],
          "a", "Artificial filtering replaces kidney function.", "Dialysis cleans blood externally."),
    ]
    # Fix the awkwardly worded double circulation question
    A[21] = q(
        "Double circulation in humans means blood goes through the heart —",
        ["twice for each complete body circuit (pulmonary + systemic)", "only once ever", "only in veins", "never to the lungs"],
        "a", "Pulmonary and systemic circulations are separate; blood returns to the heart between them.",
        "Think two loops: heart→lungs→heart→body→heart.",
    )
    B += [
        q("Raw materials for photosynthesis are —",
          ["CO₂ and H₂O (with light & chlorophyll)", "only O₂", "only nitrogen gas", "urea"],
          "a", "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (light).", "Carbon dioxide and water in; sugar and oxygen out."),
        q("Oxygen released in photosynthesis comes mainly from —",
          ["water", "carbon dioxide", "glucose", "soil minerals"],
          "a", "Photolysis of water releases O₂.", "Water, not CO₂, is the usual O₂ source."),
        q("Peristalsis is —",
          ["wave-like muscle movement pushing food", "blood clotting", "leaf folding", "urine storage only"],
          "a", "Gut walls contract rhythmically to move food.", "Squeezing waves along the digestive tract."),
        q("Emulsification of fats is done by —",
          ["bile salts", "pepsin", "amylase", "HCl alone"],
          "a", "Bile breaks fat into tiny droplets for lipase.", "Emulsify = break into droplets."),
        q("Alveoli are adapted for gas exchange by having —",
          ["large surface area and thin walls", "thick cartilage only", "chloroplasts", "nephrons"],
          "a", "Millions of thin, moist pouches contact capillaries.", "Thin + moist + huge area = fast diffusion."),
        q("Lymph —",
          ["returns tissue fluid to blood and helps immunity", "carries oxygen mainly via haemoglobin", "is identical to pure water", "is made in alveoli"],
          "a", "Lymphatic system drains excess fluid and fights pathogens.", "Lymph nodes filter lymph."),
        q("Sphygmomanometer measures —",
          ["blood pressure", "body temperature only", "lung volume only", "blood sugar only"],
          "a", "It reads systolic/diastolic arterial pressure.", "Cuff + gauge for BP."),
        q("In plants, transport of water is mainly driven by —",
          ["transpiration pull", "blood pressure", "peristalsis", "bile flow"],
          "a", "Evaporation from leaves pulls the xylem column.", "Cohesion–tension with transpiration."),
        q("Ammonia is highly toxic; humans convert it to —",
          ["urea in the liver", "glucose in muscle", "oxygen in lungs", "starch in leaves"],
          "a", "Ornithine cycle forms urea for safer excretion.", "Liver detoxifies ammonia to urea."),
        q("Capillaries are —",
          ["thin-walled vessels for exchange with tissues", "the largest arteries", "valves in veins only", "air sacs"],
          "a", "One-cell-thick walls allow diffusion.", "Exchange happens at capillary beds."),
        q("HCl in the stomach —",
          ["kills microbes and activates pepsin", "digests cellulose fully", "makes bile", "absorbs vitamins"],
          "a", "Acidic pH (~2) and pepsinogen → pepsin.", "Stomach acid is a chemical defence too."),
        q("Aerobic respiration equation overall:",
          ["C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy", "C₆H₁₂O₆ → lactic acid only", "6CO₂ → glucose in animals", "N₂ + O₂ → protein"],
          "a", "Complete oxidation of glucose with oxygen.", "Same atoms as photosynthesis reversed."),
        q("Valves in veins —",
          ["prevent backflow of blood", "produce RBCs", "filter urea", "secrete enzymes"],
          "a", "One-way valves aid return against gravity.", "Especially important in leg veins."),
        q("Bowman's capsule is part of —",
          ["nephron filtration", "alveolus", "villus", "stomata"],
          "a", "It cups the glomerulus for ultrafiltration.", "First step of urine formation."),
        q("Paramecium takes food by —",
          ["cilia sweeping into oral groove", "photosynthesis", "roots", "stomata"],
          "a", "Ciliary currents bring particles to the cytostome.", "Unicellular holozoic nutrition."),
        q("ATP is —",
          ["an energy currency of cells", "a waste like urea", "a respiratory pigment", "a plant hormone only"],
          "a", "Adenosine triphosphate stores usable energy.", "Respiration charges ATP batteries."),
        q("Desert plants often have —",
          ["sunken stomata / thick cuticle to reduce water loss", "no roots", "only phloem, no xylem", "gills"],
          "a", "Xerophyte adaptations conserve water.", "Less transpiration in dry habitats."),
        q("Blood group antibodies are found in —",
          ["plasma", "only inside RBCs haemoglobin", "platelets only", "bone matrix"],
          "a", "Plasma carries antibodies (and many proteins).", "ABO antibodies live in plasma."),
        q("The pancreas secretes —",
          ["digestive enzymes and hormones (insulin/glucagon)", "only bile", "only HCl", "only urea"],
          "a", "Exocrine enzymes + endocrine insulin/glucagon.", "Dual gland: gut enzymes and blood sugar control."),
        q("During heavy exercise, breathing rate rises to —",
          ["supply more O₂ and remove more CO₂", "stop respiration", "cool blood by stopping heart", "close all alveoli"],
          "a", "Muscles need more ATP and produce more CO₂.", "Match ventilation to demand."),
        q("Saprophytic nutrition is seen in —",
          ["fungi like mushrooms on dead matter", "green leaves only", "human stomach only", "fish gills"],
          "a", "Saprophytes digest dead organic matter externally.", "Decomposers recycle nutrients."),
        q("The correct path of urine is —",
          ["kidney → ureter → bladder → urethra", "kidney → urethra → bladder", "bladder → kidney → ureter", "liver → ureter → skin"],
          "a", "Standard urinary tract order.", "Ureter from kidney; urethra exits body."),
        q("Chlorophyll appears green because it —",
          ["reflects green wavelengths mainly", "emits only X-rays", "absorbs only green", "is made of iron oxide"],
          "a", "It absorbs red/blue and reflects green.", "What you see is what isn't strongly absorbed."),
        q("Why is the wall of the left ventricle thicker than the right?",
          ["It pumps blood all around the body at higher pressure", "It only pumps to lungs", "It stores urine", "It makes bile"],
          "a", "Systemic circuit needs stronger push than pulmonary.", "Thicker muscle → higher pressure."),
    ]
    lesson = lesson_ts(
        "Life Processes", "🧬", "plant",
        "Living things nutrition, breathe, transport, and excrete.",
        [("Nutrition", "Auto vs hetero; digestion", "🥗"),
         ("Respiration", "Aerobic vs anaerobic ATP", "💨"),
         ("Transport", "Xylem/phloem; blood", "🩸"),
         ("Excretion", "Nephrons remove urea", "🧪")],
        {"prompt": "Which tissue carries water up a plant?",
         "options": [("a", "Xylem"), ("b", "Phloem only"), ("c", "Blood"), ("d", "Nerves")],
         "answerId": "a", "why": "Xylem vessels move water and minerals upward."},
        ["Life processes ready", "Food → energy", "Gas exchange", "Clean the blood"],
    )
    outline = """
### step_1: Nutrition
- **tts**: Autotrophs make food; heterotrophs consume it. Digestion breaks food for absorption.
- **check**: Where does starch digestion begin? — Answer: Mouth

### step_2: Respiration & transport
- **tts**: Oxygen helps release energy from food. Blood and xylem/phloem move materials.
- **check**: Where is oxygen mainly absorbed in lungs? — Answer: Alveoli

### step_3: Excretion
- **tts**: Kidneys filter blood; nephrons make urine.
- **check**: Main nitrogenous waste in humans? — Answer: Urea
"""
    return emit_chapter(
        file="g10-science-life-processes.ts",
        export="g10ScienceLifeProcesses",
        doc="science-ch02-life-processes.md",
        meta={"id": "life-processes", "title": "Life Processes", "emoji": "🧬",
              "blurb": "Nutrition, breath, transport, excretion", "topic": "plant",
              "paperTopics": ["plant"], "subjectLabel": "Science"},
        lesson=lesson, set_a_raw=A, set_b_raw=B, prefix="g10-sci-life",
        lesson_outline=outline,
    )


def light():
    A, B = [], []
    A += [
        q("The angle of incidence equals the angle of reflection. This is —",
          ["a law of reflection", "Snell's law only", "Ohm's law", "Hooke's law"],
          "a", "i = r, and incident ray, reflected ray, normal are coplanar.", "Measure both angles from the normal."),
        q("A ray along the normal to a plane mirror reflects —",
          ["back on itself", "at 90° to the normal", "parallel to the mirror", "not at all"],
          "a", "i = 0 ⇒ r = 0.", "Head-on to the normal means bounce straight back."),
        q("Image in a plane mirror is —",
          ["virtual, erect, same size, laterally inverted", "real and inverted", "smaller always", "magnified always"],
          "a", "Plane mirrors make virtual, same-size, left-right flipped images.", "Stand in front of a bathroom mirror."),
        q("Focal length f of a spherical mirror relates to radius R by —",
          ["f = R/2", "f = 2R", "f = R", "f = R²"],
          "a", "For spherical mirrors (paraxial), f = R/2.", "Centre of curvature is twice the focal length away."),
        q("A concave mirror can form a real image when the object is —",
          ["beyond the focus", "between pole and focus only", "at the pole", "inside the mirror material"],
          "a", "Object outside F can give real inverted images on a screen.", "Concave = converging for real objects beyond F."),
        q("Magnification m = h′/h equals —",
          ["−v/u for mirrors (sign convention)", "u/v always positive only", "f/R", "R/f"],
          "a", "m = h′/h = −v/u in the New Cartesian convention for mirrors.", "Negative m often means inverted image."),
        q("A ray through the centre of curvature of a concave mirror —",
          ["reflects back on itself", "passes through focus only after", "grazes the pole without reflecting", "stops"],
          "a", "It hits along the normal (radius), so i=0.", "C-bound rays reverse on themselves."),
        q("Refraction is —",
          ["bending of light when speed changes across a boundary", "bouncing from a mirror", "charging of electrons", "sound echo"],
          "a", "Light changes direction with optical density change.", "Air → glass bends toward the normal (usually)."),
        q("Absolute refractive index n = —",
          ["c/v", "v/c", "c×v", "1/c"],
          "a", "n = speed in vacuum / speed in medium.", "Larger n → slower light in that medium."),
        q("Snell's law: n₁ sin i = —",
          ["n₂ sin r", "n₂ / sin r", "sin i / n₂", "n₁ / n₂"],
          "a", "n₁ sin i = n₂ sin r at a boundary.", "Product n sinθ is conserved across the interface."),
        q("A convex lens is a —",
          ["converging lens", "diverging lens", "plane mirror", "prism only"],
          "a", "Thicker in the middle; brings parallel rays to a focus.", "Convex lenses converge."),
        q("A concave lens is a —",
          ["diverging lens", "converging lens", "spherical mirror", "optical fibre core only"],
          "a", "Thinner in the middle; spreads parallel rays.", "Concave lenses diverge."),
        q("Power of a lens P = —",
          ["1/f (f in metres), unit dioptre", "f in cm", "R/2", "v−u"],
          "a", "P = 1/f with f in m; unit D (dioptre).", "Converging lenses have positive power."),
        q("Total internal reflection needs —",
          ["light in denser medium, i > critical angle", "always i = 0", "a rough surface", "no boundary"],
          "a", "From denser to rarer, beyond critical angle, light reflects fully.", "Optical fibres use TIR."),
        q("Critical angle is the incidence angle in the denser medium for which —",
          ["refraction angle in rarer medium is 90°", "reflection is zero", "light stops", "n becomes 1"],
          "a", "At critical angle, refracted ray grazes the surface.", "Beyond it → TIR."),
        q("Rainbows form mainly due to —",
          ["dispersion and reflection in water drops", "only mirrors", "only diffraction in air without water", "magnetism"],
          "a", "Droplets refract, reflect, and disperse sunlight.", "Spectrum from raindrops."),
        q("Which mirror is used as a shaving/makeup mirror?",
          ["concave (enlarged erect when close)", "convex always diminished", "plane only sometimes smaller", "none"],
          "a", "Object between pole and F of concave → virtual enlarged erect.", "Sit close to a concave mirror."),
        q("Rear-view mirrors on vehicles are often —",
          ["convex (wider field, diminished erect)", "concave only", "plane always with no field gain", "opaque"],
          "a", "Convex mirrors give a wider field of view.", "Objects look smaller but more area is visible."),
        q("Lens formula:",
          ["1/v − 1/u = 1/f", "1/v + 1/u = 1/f always for lenses? mirrors differ", "v−u=f", "m=f/u"],
          "a", "For thin lenses (Cartesian signs): 1/v − 1/u = 1/f.", "Mind the sign convention."),
        q("SI unit of power of a lens is —",
          ["dioptre (D)", "metre", "watt", "candela"],
          "a", "1 D = 1 m⁻¹.", "P in dioptres."),
        q("A real image —",
          ["can be caught on a screen", "cannot exist for lenses", "is always erect for single concave mirror all positions", "needs no light"],
          "a", "Rays actually converge; screen shows the image.", "Virtual images cannot be screened."),
        q("Lateral inversion means —",
          ["left-right reversal in a plane mirror image", "upside-down always", "colour change", "magnification >1 always"],
          "a", "Your left hand appears as the image's right.", "Wave at a mirror with one hand."),
        q("If u = −30 cm, f = −20 cm for a concave mirror, v equals —",
          ["−60 cm", "+60 cm", "−12 cm", "+30 cm"],
          "a", "1/v = 1/f − 1/u = −1/20 + 1/30 = −1/60 → v=−60 cm (real).", "Use mirror formula 1/v+1/u=1/f."),
        q("White light splits into colours through a prism because of —",
          ["dispersion (n depends on colour)", "only reflection", "magnetic lensing", "diffraction only in vacuum"],
          "a", "Different wavelengths refract by different amounts.", "Violet bends more than red in glass."),
    ]
    B += [
        q("The normal at the point of incidence is —",
          ["perpendicular to the reflecting surface", "parallel to the mirror", "along the incident ray always", "45° always"],
          "a", "Angles i and r are measured from this normal.", "Draw a perpendicular at the hit point."),
        q("Image distance equals object distance for a plane mirror. Magnification is —",
          ["+1", "−1", "0", "2"],
          "a", "Same size, erect → m = +1.", "Plane mirror: |v|=|u|, erect."),
        q("Rays parallel to the principal axis of a concave mirror reflect through —",
          ["the focus", "the centre of curvature always only", "the pole only", "infinity always after"],
          "a", "Definition of principal focus for a concave mirror.", "Parallel in → through F out."),
        q("An object at the centre of curvature of a concave mirror forms image —",
          ["at C, real, inverted, same size", "at F, magnified", "behind mirror, virtual", "at infinity"],
          "a", "Object at C → image at C, m=−1.", "Symmetric conjugate positions at C."),
        q("Relative refractive index of medium 2 w.r.t. 1 is —",
          ["n₂/n₁", "n₁/n₂ only always smaller", "n₁×n₂", "c"],
          "a", "₁n₂ = n₂/n₁ = v₁/v₂.", "Ratio of absolute indices."),
        q("A glass slab shifts a ray —",
          ["laterally without changing direction (emergent parallel)", "by focusing to a point always", "by dispersing into a rainbow always", "not at all if thick"],
          "a", "Emergent ray is parallel but displaced sideways.", "Lateral shift increases with thickness."),
        q("Twinkling of stars is mainly due to —",
          ["atmospheric refraction", "mirrors on Earth", "stars switching off", "dispersion in space vacuum only"],
          "a", "Changing air layers bend starlight irregularly.", "Planets twinkle less (extended disks)."),
        q("Optical fibres work on —",
          ["total internal reflection", "diffuse reflection only", "only absorption", "magnetic confinement"],
          "a", "Core–cladding TIR guides light with low loss.", "i greater than critical angle inside the core."),
        q("For a thin lens, if object is at 2F, image is —",
          ["at 2F, real, inverted, same size", "at F", "at infinity", "virtual erect always"],
          "a", "Classic convex-lens case: u=−2f → v=+2f.", "Same-size real image at 2F."),
        q("A myopic eye is corrected by a —",
          ["concave lens", "convex lens", "cylindrical only always", "plane mirror"],
          "a", "Short-sight: focus in front of retina; diverge with concave.", "Myopia → diverging lens."),
        q("A hypermetropic eye is corrected by a —",
          ["convex lens", "concave lens", "prism only", "opaque contact"],
          "a", "Long-sight: focus behind retina; converge with convex.", "Hypermetropia → converging lens."),
        q("SI unit of focal length is —",
          ["metre", "dioptre", "candela", "newton"],
          "a", "f is a length.", "Power uses dioptre; focal length uses metre."),
        q("When light enters glass from air, its speed —",
          ["decreases", "increases", "becomes infinite", "becomes zero"],
          "a", "n>1 ⇒ v = c/n < c.", "Denser optically → slower."),
        q("The colour of light related most to —",
          ["wavelength / frequency", "only amplitude of sound", "mirror thickness only", "lens power only"],
          "a", "Different wavelengths appear as different colours.", "Frequency stays; wavelength changes with medium."),
        q("A real image formed by a convex lens on a screen is usually —",
          ["inverted", "erect always", "same as object colour-inverted only", "invisible"],
          "a", "Single convex lens real images are inverted.", "Upside-down on the screen."),
        q("Pole (P) of a spherical mirror is —",
          ["the centre of the reflecting surface", "the focus", "centre of curvature", "any point on the screen"],
          "a", "P is where the axis meets the mirror surface.", "Vertex of the mirror."),
        q("If refractive index of water is 4/3, speed of light in water is about —",
          ["2.25 × 10⁸ m/s", "3 × 10⁸ m/s", "1.5 × 10⁸ m/s", "4 × 10⁸ m/s"],
          "a", "v=c/n ≈ 3e8/(4/3)=2.25e8 m/s.", "Divide c by n."),
        q("Astigmatism is commonly corrected using —",
          ["cylindrical lenses", "only concave spherical", "only convex spherical", "mirrors only"],
          "a", "Different meridians need different powers.", "Cylinder lenses fix uneven cornea focus."),
        q("The aperture of a spherical mirror is —",
          ["the effective diameter of the reflecting surface", "always equal to f", "the wavelength", "the magnification"],
          "a", "Wider aperture gathers more light but may add aberration.", "Think of the mirror's opening size."),
        q("In mirror formula 1/v + 1/u = 1/f, sign convention usually takes —",
          ["object distance u negative for real object in front", "u always positive", "f always positive for all mirrors", "v never negative"],
          "a", "New Cartesian: light direction positive; real object u < 0.", "Be consistent with one convention."),
        q("A pencil in a glass of water looks bent because of —",
          ["refraction at the water surface", "reflection only in the pencil", "dispersion into a spectrum always", "diffraction by air only"],
          "a", "Rays from the submerged part bend at the interface.", "Apparent depth / bent stick effect."),
        q("Combination of two thin lenses in contact: power —",
          ["P = P₁ + P₂", "P = P₁P₂", "P = P₁ − P₂ only", "P = 1/(P₁+P₂)"],
          "a", "Powers add for thin lenses in contact.", "Net dioptres sum."),
        q("Which phenomenon does NOT need a change of medium?",
          ["reflection at a mirror in one medium", "refraction", "TIR requiring denser start", "Snell's law bending"],
          "a", "Reflection can occur at a mirror within the same medium.", "Refraction needs two media."),
        q("If f_convex = +20 cm, power is —",
          ["+5 D", "+0.2 D", "−5 D", "+20 D"],
          "a", "f=0.20 m; P=1/0.2=+5 D.", "Convert cm to m before taking reciprocal."),
    ]
    lesson = lesson_ts(
        "Light — Reflection & Refraction", "🔆", "none",
        "Mirrors reflect; lenses bend. Signs and formulas keep images organised.",
        [("Reflection", "i = r; plane & spherical mirrors", "🪞"),
         ("Refraction", "Snell's law; n = c/v", "↗️"),
         ("Lenses", "Convex converges; concave diverges", "🔎"),
         ("Applications", "Eyes, fibres, vehicle mirrors", "👁️")],
        {"prompt": "A convex rear-view mirror is used because it gives —",
         "options": [("a", "a wider field of view"), ("b", "always magnification > 1"), ("c", "real images on the road"), ("d", "no image")],
         "answerId": "a", "why": "Convex mirrors show more area, though objects look smaller."},
        ["Light toolkit", "i = r", "Snell & n", "Lens/mirror formula with signs"],
    )
    outline = """
### step_1: Reflection
- **tts**: Angle in equals angle out. Plane mirrors flip left and right.
- **check**: i = 30°, r = ? — Answer: 30°

### step_2: Spherical mirrors & lenses
- **tts**: Concave mirrors and convex lenses can converge light to real images.
- **check**: f related to R for a spherical mirror? — Answer: f = R/2

### step_3: Refraction & eyes
- **tts**: Light bends when speed changes. Lenses correct myopia and hypermetropia.
- **check**: Myopia corrected by? — Answer: Concave lens
"""
    return emit_chapter(
        file="g10-science-light.ts",
        export="g10ScienceLight",
        doc="science-ch03-light.md",
        meta={"id": "light", "title": "Light — Reflection & Refraction", "emoji": "🔆",
              "blurb": "Mirrors, lenses & refraction", "topic": "matter-lite",
              "paperTopics": ["matter-lite"], "subjectLabel": "Science"},
        lesson=lesson, set_a_raw=A, set_b_raw=B, prefix="g10-sci-light",
        lesson_outline=outline,
    )


def build_all():
    h = {}
    h.update(chemical_reactions())
    h.update(life_processes())
    h.update(light())
    return h
