import type { ContentPack } from "../../types";
import { spellingPhase } from "../spelling";

/** Multi-step patterns, place value stretch, harder hard-try. */
export const tuesdayPack1011: ContentPack = {
  id: "tue-10-11-v1",
  ageBand: "10-11",
  weekday: "tue",
  title: "Tuesday · Layers & Hundreds",
  ready: true,
  phases: {
    warm_up: {
      muscle: "confidence",
      title: "Warm-up",
      kidTitle: "Warm-up",
      emoji: "🌅",
      estimatedMin: 2,
      items: [
        {
          id: "wu-intro",
          type: "intro",
          emoji: "💪",
          title: "Brave brain warm-up",
          body: ["Quick warm-up before the stretch.", "Spot the rule — then lock in."],
          cta: "Let’s go!",
        },
        {
          id: "wu-tiny",
          type: "choice",
          prompt: "What number fits?",
          sequence: [
            { kind: "number", value: 4 },
            { kind: "number", value: 8 },
            { kind: "number", value: 16 },
            { kind: "blank" },
            { kind: "number", value: 64 },
          ],
          options: [
            { id: "24", text: "24" },
            { id: "32", text: "32" },
            { id: "28", text: "28" },
            { id: "48", text: "48" },
          ],
          answerId: "32",
          hints: [
            "Look at 4 → 8 → 16. Doubling?",
            "Each number is twice the one before.",
          ],
          correct: "32 — doubling each time. Warm-up locked!",
          tryAgain: "Close! Try multiplying by 2 each jump.",
          rule: "Double each time.",
        },
        {
          id: "wu-ritual",
          type: "ritual",
          title: "Today’s rule",
          body: ["One brave try first.", "Hints wait until you ask."],
          chant: "Try before hint!",
        },
      ],
    },

    focus_a: {
      muscle: "reasoning",
      title: "Reasoning",
      kidTitle: "Patterns",
      emoji: "🧩",
      estimatedMin: 7,
      items: [
        {
          id: "ra-intro",
          type: "intro",
          emoji: "🔎",
          title: "Multi-step patterns",
          body: [
            "Some patterns have more than one rule.",
            "Find every part that changes — then predict.",
          ],
          cta: "Show me!",
        },
        {
          id: "ra-1",
          type: "choice",
          prompt: "What comes next?",
          sequence: [
            { kind: "dot", color: "blue", size: "sm" },
            { kind: "dot", color: "blue", size: "lg" },
            { kind: "dot", color: "green", size: "sm" },
            { kind: "dot", color: "green", size: "lg" },
            { kind: "dot", color: "purple", size: "sm" },
            { kind: "blank" },
          ],
          options: [
            {
              id: "pl",
              label: "Big purple",
              token: { kind: "dot", color: "purple", size: "lg" },
            },
            {
              id: "ps",
              label: "Small purple",
              token: { kind: "dot", color: "purple", size: "sm" },
            },
            {
              id: "ys",
              label: "Small yellow",
              token: { kind: "dot", color: "yellow", size: "sm" },
            },
            {
              id: "gl",
              label: "Big green",
              token: { kind: "dot", color: "green", size: "lg" },
            },
          ],
          answerId: "pl",
          hints: [
            "Colors go blue, blue, green, green, purple, purple…",
            "Within each color: small then big.",
          ],
          correct: "Big purple! Color pairs, each small→big.",
          tryAgain: "Check both color pairs and size order.",
          rule: "Two of each color: small then big.",
        },
        {
          id: "ra-2",
          type: "choice",
          prompt: "What number comes next?",
          sequence: [
            { kind: "number", value: 3 },
            { kind: "number", value: 7 },
            { kind: "number", value: 15 },
            { kind: "number", value: 31 },
            { kind: "blank" },
          ],
          options: [
            { id: "47", text: "47" },
            { id: "63", text: "63" },
            { id: "62", text: "62" },
            { id: "35", text: "35" },
          ],
          answerId: "63",
          hints: [
            "Look at the jumps: +4, +8, +16…",
            "Each jump is double the jump before.",
          ],
          correct: "63! Jumps double: +4, +8, +16, +32.",
          tryAgain: "Focus on how much you add each time.",
          rule: "Add twice as much each step.",
        },
        {
          id: "ra-3",
          type: "choice",
          prompt: "Which letter comes next?",
          sequence: [
            { kind: "letter", char: "Z" },
            { kind: "letter", char: "Y" },
            { kind: "letter", char: "Y" },
            { kind: "letter", char: "X" },
            { kind: "letter", char: "X" },
            { kind: "letter", char: "X" },
            { kind: "letter", char: "W" },
            { kind: "letter", char: "W" },
            { kind: "letter", char: "W" },
            { kind: "blank" },
          ],
          options: [
            { id: "W", label: "W", token: { kind: "letter", char: "W" } },
            { id: "V", label: "V", token: { kind: "letter", char: "V" } },
            { id: "X", label: "X", token: { kind: "letter", char: "X" } },
          ],
          answerId: "W",
          hints: [
            "Z once, Y twice, X three times, W…",
            "How many W’s should there be?",
          ],
          correct: "W — four W’s in a row (you’re on the 4th).",
          tryAgain: "Count how many times each letter appears.",
          rule: "Letter n appears n times (going backwards).",
        },
        {
          id: "ra-4",
          type: "choice",
          prompt: "What comes next in the shape pattern?",
          sequence: [
            { kind: "shape", shape: "square", color: "red" },
            { kind: "shape", shape: "circle", color: "red" },
            { kind: "shape", shape: "triangle", color: "red" },
            { kind: "shape", shape: "square", color: "yellow" },
            { kind: "shape", shape: "circle", color: "yellow" },
            { kind: "shape", shape: "triangle", color: "yellow" },
            { kind: "shape", shape: "square", color: "blue" },
            { kind: "blank" },
          ],
          options: [
            {
              id: "ci-b",
              label: "Blue circle",
              token: { kind: "shape", shape: "circle", color: "blue" },
            },
            {
              id: "tr-b",
              label: "Blue triangle",
              token: { kind: "shape", shape: "triangle", color: "blue" },
            },
            {
              id: "sq-g",
              label: "Green square",
              token: { kind: "shape", shape: "square", color: "green" },
            },
          ],
          answerId: "ci-b",
          hints: [
            "Shapes cycle: square → circle → triangle.",
            "Colors change every three shapes.",
          ],
          correct: "Blue circle — shapes cycle; color stays for the trio.",
          tryAgain: "Finish the blue trio: square, __, triangle.",
          rule: "Shape cycle × color blocks of 3.",
        },
        {
          id: "ra-5",
          type: "choice",
          prompt: "Which rule fits best?",
          options: [
            { id: "add3", text: "Add 3 each time" },
            { id: "alt", text: "Alternate +4 and −2" },
            { id: "double", text: "Double each time" },
            { id: "add6", text: "Add 6 each time" },
          ],
          sequence: [
            { kind: "number", value: 5 },
            { kind: "number", value: 9 },
            { kind: "number", value: 7 },
            { kind: "number", value: 11 },
            { kind: "number", value: 9 },
            { kind: "blank" },
          ],
          answerId: "alt",
          hints: [
            "Check the jumps: 5→9, 9→7, 7→11, 11→9…",
            "Up by 4, down by 2, up by 4, down by 2…",
          ],
          correct: "Alternate +4 and −2. Next would be 13.",
          tryAgain: "Write the difference between each pair.",
          rule: "+4, −2, +4, −2…",
        },
        {
          id: "ra-close",
          type: "intro",
          emoji: "✨",
          title: "Multi-step mastery",
          body: [
            "You tracked more than one change at once.",
            "That’s real pattern power.",
          ],
          cta: "Next: Maths!",
        },
      ],
    },

    focus_b: {
      muscle: "maths",
      title: "Maths",
      kidTitle: "Big numbers",
      emoji: "🧮",
      estimatedMin: 7,
      items: [
        {
          id: "mb-intro",
          type: "intro",
          emoji: "💯",
          title: "Hundreds, tens & ones",
          body: [
            "Bigger numbers still break into place value.",
            "Hundreds · tens · ones — then operate.",
          ],
          cta: "Show me!",
        },
        {
          id: "mb-model-ten",
          type: "model",
          variant: "bundle_ten",
          title: "Still true: 1 ten = 10 ones",
          body: [
            "Same bundling idea — just more digits.",
            "10 tens make one hundred.",
          ],
        },
        {
          id: "mb-model-58",
          type: "model",
          variant: "show_number",
          number: 58,
          title: "Warm model: 58",
          body: [
            "5 tens and 8 ones.",
            "We’ll stretch this idea to hundreds next.",
          ],
        },
        {
          id: "mb-1",
          type: "choice",
          prompt: "4 hundreds + 1 ten + 6 ones = ?",
          options: [
            { id: "416", text: "416" },
            { id: "461", text: "461" },
            { id: "146", text: "146" },
            { id: "4016", text: "4016" },
          ],
          answerId: "416",
          hints: [
            "Hundreds · tens · ones — left to right.",
            "4 hundreds = 400, plus 10, plus 6.",
          ],
          correct: "416 — place value in order!",
          tryAgain: "Don’t shuffle the places.",
          rule: "HTO: hundreds, tens, ones.",
        },
        {
          id: "mb-2",
          type: "choice",
          prompt: "58 + 27 = ?",
          options: [
            { id: "75", text: "75" },
            { id: "85", text: "85" },
            { id: "715", text: "715" },
            { id: "84", text: "84" },
          ],
          answerId: "85",
          hints: [
            "Add ones first: 8 + 7 = 15 → write 5, carry 1 ten.",
            "Tens: 5 + 2 + 1 carry = 8.",
          ],
          correct: "85 — ones then tens with the carry!",
          tryAgain: "Watch the carry from the ones place.",
          rule: "Add ones, regroup, then tens.",
        },
        {
          id: "mb-3",
          type: "choice",
          prompt: "Which is greatest?",
          options: [
            { id: "a", text: "4 hundreds + 5 ones" },
            { id: "b", text: "3 hundreds + 12 tens" },
            { id: "c", text: "38 tens + 15 ones" },
            { id: "d", text: "5 hundreds − 80" },
          ],
          answerId: "b",
          hints: [
            "Rewrite each as a normal number.",
            "3 hundreds + 12 tens = 300 + 120 = 420.",
          ],
          correct: "420 wins — regrouping tens into hundreds helps!",
          tryAgain: "Convert everything to the same form first.",
          rule: "Compare after regrouping.",
        },
        {
          id: "mb-4",
          type: "choice",
          prompt: "A jar has 63 marbles. You take out 28. How many left?",
          options: [
            { id: "35", text: "35" },
            { id: "45", text: "45" },
            { id: "34", text: "34" },
            { id: "41", text: "41" },
          ],
          answerId: "35",
          hints: [
            "Subtract ones carefully — you may need to borrow.",
            "63 − 30 = 33, then add 2 back (you only took 28).",
          ],
          correct: "35 marbles left. Nice regrouping!",
          tryAgain: "Try 63 − 30 + 2.",
          rule: "Multi-digit subtract with regrouping.",
        },
        {
          id: "mb-5",
          type: "choice",
          prompt: "How many tens are in 520?",
          options: [
            { id: "2", text: "2 tens" },
            { id: "52", text: "52 tens" },
            { id: "520", text: "520 tens" },
            { id: "5", text: "5 tens" },
          ],
          answerId: "52",
          hints: [
            "520 ÷ 10 = ?",
            "5 hundreds = 50 tens, plus 2 tens already showing.",
          ],
          correct: "52 tens — hundreds count as tens too!",
          tryAgain: "Think: how many groups of 10 fit in 520?",
          rule: "Total tens = number ÷ 10.",
        },
        {
          id: "mb-close",
          type: "intro",
          emoji: "🎯",
          title: "Place value flex",
          body: [
            "Big numbers are just bundled smaller ones.",
            "Regroup when you add or subtract.",
          ],
          cta: "Spelling!",
        },
      ],
    },

    focus_c: spellingPhase("10-11"),

    hard_try: {
      muscle: "confidence",
      title: "Hard try",
      kidTitle: "Hard try",
      emoji: "🦁",
      estimatedMin: 3,
      items: [
        {
          id: "ht-1",
          type: "hard_try",
          frame: [
            "This stretch uses two ideas at once.",
            "One brave try first. No hint until you tap I tried.",
          ],
          sequence: [7, 14, 28, 56],
          answer: 112,
          hints: [
            "Are we adding a fixed amount — or multiplying?",
            "Each term is double the one before.",
            "7 → 14 → 28 → 56 → ?",
          ],
          messages: {
            correctNoHint:
              "You tried first — and you got it. High five for the try AND the answer!",
            correctAfterHint: "Tried, then hint, then finished — smart bravery.",
            wrong: "You did the brave part — you tried. Hint now, or one more try?",
            stuck: "You stayed with it. Trying counted today.",
          },
        },
      ],
    },

    reflect: {
      muscle: "confidence",
      title: "Reflect",
      kidTitle: "Think back",
      emoji: "💭",
      estimatedMin: 1,
      items: [
        {
          id: "rf-1",
          type: "reflect",
          questions: [
            {
              id: "feltHard",
              prompt: "What felt hard?",
              options: [
                { id: "multistep", label: "Tracking two rules at once", emoji: "🌀" },
                { id: "regroup", label: "Regrouping / carrying", emoji: "🔄" },
                { id: "waiting", label: "Waiting for a hint", emoji: "⏳" },
                { id: "nothing", label: "Nothing felt hard today", emoji: "😎" },
              ],
            },
            {
              id: "whatTried",
              prompt: "What did you try?",
              options: [
                { id: "jumps", label: "I checked the jumps", emoji: "📏" },
                { id: "rewrite", label: "I rewrote with place value", emoji: "🧱" },
                { id: "estimate", label: "I estimated first", emoji: "🎯" },
                { id: "hintAfter", label: "I asked for a hint after trying", emoji: "💡" },
              ],
            },
          ],
          closing:
            "You used Try before hint. That’s how brave brains grow. See you next time!",
        },
      ],
    },
  },
};
