import type { ContentPack } from "../../types";
import { spellingPhase } from "../spelling";

/** Multi-step rhythms, place-value stretch, fresh hard-try. */
export const wednesdayPack1011: ContentPack = {
  id: "wed-10-11-v1",
  ageBand: "10-11",
  weekday: "wed",
  title: "Wednesday · Rhythms & Regroup",
  ready: true,
  phases: {
    warm_up: {
      muscle: "confidence",
      title: "Warm-up",
      kidTitle: "Warm-up",
      emoji: "🌅",
      estimatedMin: 2,
      items: [
        {
          id: "wu-intro",
          type: "intro",
          emoji: "💪",
          title: "Brave brain warm-up",
          body: ["Quick warm-up before the stretch.", "Spot the rule — then lock in."],
          cta: "Let’s go!",
        },
        {
          id: "wu-tiny",
          type: "choice",
          prompt: "What number fits?",
          sequence: [
            { kind: "number", value: 3 },
            { kind: "number", value: 6 },
            { kind: "number", value: 12 },
            { kind: "blank" },
            { kind: "number", value: 48 },
          ],
          options: [
            { id: "18", text: "18" },
            { id: "24", text: "24" },
            { id: "20", text: "20" },
            { id: "36", text: "36" },
          ],
          answerId: "24",
          hints: [
            "Look at 3 → 6 → 12. Doubling?",
            "Each number is twice the one before.",
          ],
          correct: "24 — doubling each time. Warm-up locked!",
          tryAgain: "Close! Try multiplying by 2 each jump.",
          rule: "Double each time.",
        },
        {
          id: "wu-ritual",
          type: "ritual",
          title: "Today’s rule",
          body: ["One brave try first.", "Hints wait until you ask."],
          chant: "Try before hint!",
        },
      ],
    },

    focus_a: {
      muscle: "reasoning",
      title: "Reasoning",
      kidTitle: "Patterns",
      emoji: "🧩",
      estimatedMin: 7,
      items: [
        {
          id: "ra-intro",
          type: "intro",
          emoji: "🔎",
          title: "Multi-step patterns",
          body: [
            "Some patterns have more than one rule.",
            "Find every part that changes — then predict.",
          ],
          cta: "Show me!",
        },
        {
          id: "ra-1",
          type: "choice",
          prompt: "What comes next?",
          sequence: [
            { kind: "dot", color: "red", size: "lg" },
            { kind: "dot", color: "red", size: "sm" },
            { kind: "dot", color: "yellow", size: "lg" },
            { kind: "dot", color: "yellow", size: "sm" },
            { kind: "dot", color: "green", size: "lg" },
            { kind: "blank" },
          ],
          options: [
            {
              id: "gs",
              label: "Small green",
              token: { kind: "dot", color: "green", size: "sm" },
            },
            {
              id: "gl",
              label: "Big green",
              token: { kind: "dot", color: "green", size: "lg" },
            },
            {
              id: "bs",
              label: "Small blue",
              token: { kind: "dot", color: "blue", size: "sm" },
            },
            {
              id: "ys",
              label: "Small yellow",
              token: { kind: "dot", color: "yellow", size: "sm" },
            },
          ],
          answerId: "gs",
          hints: [
            "Colors go red, red, yellow, yellow, green, green…",
            "Within each color: big then small.",
          ],
          correct: "Small green! Color pairs, each big→small.",
          tryAgain: "Check both color pairs and size order.",
          rule: "Two of each color: big then small.",
        },
        {
          id: "ra-2",
          type: "choice",
          prompt: "What number comes next?",
          sequence: [
            { kind: "number", value: 2 },
            { kind: "number", value: 5 },
            { kind: "number", value: 11 },
            { kind: "number", value: 23 },
            { kind: "blank" },
          ],
          options: [
            { id: "35", text: "35" },
            { id: "47", text: "47" },
            { id: "46", text: "46" },
            { id: "27", text: "27" },
          ],
          answerId: "47",
          hints: [
            "Look at the jumps: +3, +6, +12…",
            "Each jump is double the jump before.",
          ],
          correct: "47! Jumps double: +3, +6, +12, +24.",
          tryAgain: "Focus on how much you add each time.",
          rule: "Add twice as much each step.",
        },
        {
          id: "ra-3",
          type: "choice",
          prompt: "Which letter comes next?",
          sequence: [
            { kind: "letter", char: "A" },
            { kind: "letter", char: "B" },
            { kind: "letter", char: "B" },
            { kind: "letter", char: "C" },
            { kind: "letter", char: "C" },
            { kind: "letter", char: "C" },
            { kind: "letter", char: "D" },
            { kind: "letter", char: "D" },
            { kind: "letter", char: "D" },
            { kind: "blank" },
          ],
          options: [
            { id: "D", label: "D", token: { kind: "letter", char: "D" } },
            { id: "E", label: "E", token: { kind: "letter", char: "E" } },
            { id: "C", label: "C", token: { kind: "letter", char: "C" } },
          ],
          answerId: "D",
          hints: [
            "A once, B twice, C three times, D…",
            "How many D’s should there be?",
          ],
          correct: "D — four D’s in a row (you’re on the 4th).",
          tryAgain: "Count how many times each letter appears.",
          rule: "Letter n appears n times (going forwards).",
        },
        {
          id: "ra-4",
          type: "choice",
          prompt: "What comes next in the shape pattern?",
          sequence: [
            { kind: "shape", shape: "circle", color: "blue" },
            { kind: "shape", shape: "square", color: "blue" },
            { kind: "shape", shape: "triangle", color: "blue" },
            { kind: "shape", shape: "circle", color: "green" },
            { kind: "shape", shape: "square", color: "green" },
            { kind: "shape", shape: "triangle", color: "green" },
            { kind: "shape", shape: "circle", color: "purple" },
            { kind: "blank" },
          ],
          options: [
            {
              id: "sq-p",
              label: "Purple square",
              token: { kind: "shape", shape: "square", color: "purple" },
            },
            {
              id: "tr-p",
              label: "Purple triangle",
              token: { kind: "shape", shape: "triangle", color: "purple" },
            },
            {
              id: "ci-y",
              label: "Yellow circle",
              token: { kind: "shape", shape: "circle", color: "yellow" },
            },
          ],
          answerId: "sq-p",
          hints: [
            "Shapes cycle: circle → square → triangle.",
            "Colors change every three shapes.",
          ],
          correct: "Purple square — shapes cycle; color stays for the trio.",
          tryAgain: "Finish the purple trio: circle, __, triangle.",
          rule: "Shape cycle × color blocks of 3.",
        },
        {
          id: "ra-5",
          type: "choice",
          prompt: "Which rule fits best?",
          options: [
            { id: "add5", text: "Add 5 each time" },
            { id: "alt", text: "Alternate +3 and −1" },
            { id: "double", text: "Double each time" },
            { id: "add2", text: "Add 2 each time" },
          ],
          sequence: [
            { kind: "number", value: 4 },
            { kind: "number", value: 7 },
            { kind: "number", value: 6 },
            { kind: "number", value: 9 },
            { kind: "number", value: 8 },
            { kind: "blank" },
          ],
          answerId: "alt",
          hints: [
            "Check the jumps: 4→7, 7→6, 6→9, 9→8…",
            "Up by 3, down by 1, up by 3, down by 1…",
          ],
          correct: "Alternate +3 and −1. Next would be 11.",
          tryAgain: "Write the difference between each pair.",
          rule: "+3, −1, +3, −1…",
        },
        {
          id: "ra-close",
          type: "intro",
          emoji: "✨",
          title: "Multi-step mastery",
          body: [
            "You tracked more than one change at once.",
            "That’s real pattern power.",
          ],
          cta: "Next: Maths!",
        },
      ],
    },

    focus_b: {
      muscle: "maths",
      title: "Maths",
      kidTitle: "Big numbers",
      emoji: "🧮",
      estimatedMin: 7,
      items: [
        {
          id: "mb-intro",
          type: "intro",
          emoji: "💯",
          title: "Hundreds, tens & ones",
          body: [
            "Bigger numbers still break into place value.",
            "Hundreds · tens · ones — then operate.",
          ],
          cta: "Show me!",
        },
        {
          id: "mb-model-ten",
          type: "model",
          variant: "bundle_ten",
          title: "Still true: 1 ten = 10 ones",
          body: [
            "Same bundling idea — just more digits.",
            "10 tens make one hundred.",
          ],
        },
        {
          id: "mb-model-73",
          type: "model",
          variant: "show_number",
          number: 73,
          title: "Warm model: 73",
          body: [
            "7 tens and 3 ones.",
            "We’ll stretch this idea to hundreds next.",
          ],
        },
        {
          id: "mb-1",
          type: "choice",
          prompt: "5 hundreds + 3 tens + 2 ones = ?",
          options: [
            { id: "532", text: "532" },
            { id: "523", text: "523" },
            { id: "352", text: "352" },
            { id: "5032", text: "5032" },
          ],
          answerId: "532",
          hints: [
            "Hundreds · tens · ones — left to right.",
            "5 hundreds = 500, plus 30, plus 2.",
          ],
          correct: "532 — place value in order!",
          tryAgain: "Don’t shuffle the places.",
          rule: "HTO: hundreds, tens, ones.",
        },
        {
          id: "mb-2",
          type: "choice",
          prompt: "73 + 48 = ?",
          options: [
            { id: "111", text: "111" },
            { id: "121", text: "121" },
            { id: "1111", text: "1111" },
            { id: "120", text: "120" },
          ],
          answerId: "121",
          hints: [
            "Add ones first: 3 + 8 = 11 → write 1, carry 1 ten.",
            "Tens: 7 + 4 + 1 carry = 12.",
          ],
          correct: "121 — ones then tens with the carry!",
          tryAgain: "Watch the carry from the ones place.",
          rule: "Add ones, regroup, then tens.",
        },
        {
          id: "mb-3",
          type: "choice",
          prompt: "Which is greatest?",
          options: [
            { id: "a", text: "3 hundreds + 8 ones" },
            { id: "b", text: "2 hundreds + 15 tens" },
            { id: "c", text: "29 tens + 12 ones" },
            { id: "d", text: "4 hundreds − 90" },
          ],
          answerId: "b",
          hints: [
            "Rewrite each as a normal number.",
            "2 hundreds + 15 tens = 200 + 150 = 350.",
          ],
          correct: "350 wins — regrouping tens into hundreds helps!",
          tryAgain: "Convert everything to the same form first.",
          rule: "Compare after regrouping.",
        },
        {
          id: "mb-4",
          type: "choice",
          prompt: "A shelf has 81 books. You lend 37. How many left?",
          options: [
            { id: "44", text: "44" },
            { id: "54", text: "54" },
            { id: "43", text: "43" },
            { id: "48", text: "48" },
          ],
          answerId: "44",
          hints: [
            "Subtract ones carefully — you may need to borrow.",
            "81 − 40 = 41, then add 3 back (you only took 37).",
          ],
          correct: "44 books left. Nice regrouping!",
          tryAgain: "Try 81 − 40 + 3.",
          rule: "Multi-digit subtract with regrouping.",
        },
        {
          id: "mb-5",
          type: "choice",
          prompt: "How many tens are in 610?",
          options: [
            { id: "1", text: "1 ten" },
            { id: "61", text: "61 tens" },
            { id: "610", text: "610 tens" },
            { id: "6", text: "6 tens" },
          ],
          answerId: "61",
          hints: [
            "610 ÷ 10 = ?",
            "6 hundreds = 60 tens, plus 1 ten already showing.",
          ],
          correct: "61 tens — hundreds count as tens too!",
          tryAgain: "Think: how many groups of 10 fit in 610?",
          rule: "Total tens = number ÷ 10.",
        },
        {
          id: "mb-close",
          type: "intro",
          emoji: "🎯",
          title: "Place value flex",
          body: [
            "Big numbers are just bundled smaller ones.",
            "Regroup when you add or subtract.",
          ],
          cta: "Spelling!",
        },
      ],
    },

    focus_c: spellingPhase("10-11"),

    hard_try: {
      muscle: "confidence",
      title: "Hard try",
      kidTitle: "Hard try",
      emoji: "🦁",
      estimatedMin: 3,
      items: [
        {
          id: "ht-1",
          type: "hard_try",
          frame: [
            "This stretch uses two ideas at once.",
            "One brave try first. No hint until you tap I tried.",
          ],
          sequence: [5, 10, 20, 40],
          answer: 80,
          hints: [
            "Are we adding a fixed amount — or multiplying?",
            "Each term is double the one before.",
            "5 → 10 → 20 → 40 → ?",
          ],
          messages: {
            correctNoHint:
              "You tried first — and you got it. High five for the try AND the answer!",
            correctAfterHint: "Tried, then hint, then finished — smart bravery.",
            wrong: "You did the brave part — you tried. Hint now, or one more try?",
            stuck: "You stayed with it. Trying counted today.",
          },
        },
      ],
    },

    reflect: {
      muscle: "confidence",
      title: "Reflect",
      kidTitle: "Think back",
      emoji: "💭",
      estimatedMin: 1,
      items: [
        {
          id: "rf-1",
          type: "reflect",
          questions: [
            {
              id: "feltHard",
              prompt: "What felt hard?",
              options: [
                { id: "multistep", label: "Tracking two rules at once", emoji: "🌀" },
                { id: "regroup", label: "Regrouping / carrying", emoji: "🔄" },
                { id: "waiting", label: "Waiting for a hint", emoji: "⏳" },
                { id: "nothing", label: "Nothing felt hard today", emoji: "😎" },
              ],
            },
            {
              id: "whatTried",
              prompt: "What did you try?",
              options: [
                { id: "jumps", label: "I checked the jumps", emoji: "📏" },
                { id: "rewrite", label: "I rewrote with place value", emoji: "🧱" },
                { id: "estimate", label: "I estimated first", emoji: "🎯" },
                { id: "hintAfter", label: "I asked for a hint after trying", emoji: "💡" },
              ],
            },
          ],
          closing:
            "You used Try before hint. That’s how brave brains grow. See you next time!",
        },
      ],
    },
  },
};
