#!/usr/bin/env python3
"""Grade 6 English + Science question banks for generate_g6_pack.py."""

BP_HINTS = ["Read carefully.", "Eliminate impossible options first."]
BP_HINTS_TXT = ["Look for clues in the text.", "Eliminate unsupported answers."]
BP_HINTS_SCI = ["Think about the lesson key ideas.", "Eliminate options that do not fit."]


def q(prompt, options, answer, explanation, hint, *, bp=None):
    assert answer in "abcd" and len(options) == 4
    return {
        "prompt": prompt,
        "options": options,
        "answer": answer,
        "explanation": explanation,
        "hint": hint,
        "bp": bp or BP_HINTS,
    }


P1 = (
    "Passage P1: Every Sunday, Kabir and his sister Meera visit the neighbourhood library. "
    "Kabir chooses science magazines, while Meera looks for folk tales. Last week, the librarian, "
    "Mrs Rao, showed them a new shelf of books written by Indian authors. Meera borrowed a story "
    "about a girl who plants trees along a dry river. Kabir found an article on how mangroves "
    "protect the coast during storms. Before leaving, they promised to return the books in ten days."
)

P2 = (
    "Passage P2: On market day, Amma buys vegetables from the same stall each week. The vendor, "
    "Uncle Raju, always weighs the tomatoes carefully and never rushes. Yesterday Amma asked for "
    "two kilos of tomatoes and a bunch of coriander. Uncle Raju smiled and said the coriander was "
    "fresh from his brother’s farm. Amma paid ₹90 and thanked him. On the walk home, she told her "
    "son that honest traders make shopping a pleasure."
)

P3 = (
    "Passage P3: The school science club met after lunch. Ananya explained that recycling paper "
    "saves trees, and Rohan added that sorting plastic from kitchen waste keeps drains cleaner. "
    "Their teacher, Mr Das, asked each member to bring one idea for the annual fair. Ananya "
    "suggested a stall that shows how to make seed balls. Rohan wanted a demo on composting. "
    "Everyone clapped when Mr Das said both ideas could share one corner of the hall."
)

P4 = (
    "Passage P4: During the monsoon, the cricket ground near Priya’s house turns muddy. Priya’s "
    "coach moves practice to the indoor hall on rainy evenings. Last Tuesday, lightning flashed "
    "and practice was cut short. Priya used the extra time to mend her bat grip. She told her "
    "friend that patience is part of becoming a better player. On Wednesday the sun returned, "
    "and the team practised fielding until dusk."
)


def _comp(passage, question, options, answer, explanation, hint):
    return q(f"{passage}\n\n{question}", options, answer, explanation, hint, bp=BP_HINTS_TXT)


ENG_COMP_A = [
    _comp(P1, "Where do Kabir and Meera go every Sunday?",
          ["The market", "The neighbourhood library", "The mangrove forest", "Mrs Rao’s house"],
          "b", "The first sentence says they visit the neighbourhood library every Sunday.",
          "Find the place named in the opening sentence."),
    _comp(P1, "What kind of reading does Kabir prefer?",
          ["Folk tales", "Science magazines", "Comic books", "Poetry only"],
          "b", "The passage says Kabir chooses science magazines.",
          "Match Kabir to the type of reading mentioned."),
    _comp(P1, "Who showed them the new shelf?",
          ["Meera", "Kabir", "Mrs Rao", "An Indian author"],
          "c", "Mrs Rao, the librarian, showed them the new shelf.",
          "Look for the librarian’s name."),
    _comp(P1, "What was Meera’s borrowed story about?",
          ["Mangroves in storms", "A girl who plants trees by a dry river",
           "How to run a library", "A coastal lighthouse"],
          "b", "Meera borrowed a story about a girl who plants trees along a dry river.",
          "Find the sentence about Meera’s book."),
    _comp(P1, "According to Kabir’s article, mangroves —",
          ["harm the coast", "protect the coast during storms", "grow only in deserts", "are folk tales"],
          "b", "The article said mangroves protect the coast during storms.",
          "Locate the mangrove sentence."),
    _comp(P1, "How soon must they return the books?",
          ["In two days", "In ten days", "In a month", "Never"],
          "b", "They promised to return the books in ten days.",
          "Find the promise at the end."),
    _comp(P2, "From whom does Amma buy vegetables?",
          ["Mrs Rao", "Uncle Raju", "Kabir", "Mr Das"],
          "b", "She buys from Uncle Raju’s stall.",
          "Name the vendor in the passage."),
    _comp(P2, "What quality of Uncle Raju is highlighted?",
          ["He rushes customers", "He weighs carefully and never rushes",
           "He sells only fruit", "He ignores Amma"],
          "b", "He weighs tomatoes carefully and never rushes.",
          "Find the description of how he works."),
    _comp(P2, "How much coriander did Amma ask for?",
          ["Two kilos", "A bunch", "A bag of seeds", "None"],
          "b", "She asked for a bunch of coriander.",
          "Read Amma’s order carefully."),
    _comp(P2, "Where was the coriander from?",
          ["A factory", "Uncle Raju’s brother’s farm", "The library", "The school club"],
          "b", "Uncle Raju said it was fresh from his brother’s farm.",
          "Find the farm mention."),
    _comp(P2, "How much did Amma pay?",
          ["₹19", "₹90", "₹900", "₹9"],
          "b", "Amma paid ₹90.",
          "Look for the rupee amount."),
    _comp(P2, "What did Amma tell her son on the walk home?",
          ["Markets are boring", "Honest traders make shopping a pleasure",
           "Never buy tomatoes", "Coriander is expensive"],
          "b", "She said honest traders make shopping a pleasure.",
          "Check the closing sentence."),
    _comp(P3, "When did the science club meet?",
          ["Before breakfast", "After lunch", "At midnight", "On Sunday only"],
          "b", "The club met after lunch.",
          "Find the meeting time."),
    _comp(P3, "What did Ananya say recycling paper does?",
          ["Wastes water", "Saves trees", "Blocks drains", "Makes plastic"],
          "b", "Ananya said recycling paper saves trees.",
          "Match Ananya to her claim."),
    _comp(P3, "According to Rohan, sorting plastic from kitchen waste —",
          ["keeps drains cleaner", "grows mangroves", "mends bat grips", "buys tomatoes"],
          "a", "Rohan said sorting plastic keeps drains cleaner.",
          "Find Rohan’s point about plastic."),
    _comp(P3, "What did Mr Das ask members to bring?",
          ["Lunch boxes", "One idea for the annual fair", "Mangrove plants", "₹90 each"],
          "b", "He asked each member to bring one idea for the annual fair.",
          "Locate the teacher’s request."),
    _comp(P3, "Ananya’s fair idea was a stall about —",
          ["Composting only", "Making seed balls", "Selling tomatoes", "Indoor cricket"],
          "b", "Ananya suggested a stall that shows how to make seed balls.",
          "Find Ananya’s suggestion."),
    _comp(P3, "How did Mr Das respond to both ideas?",
          ["He rejected both", "He said both could share one corner",
           "He chose only Rohan’s idea", "He cancelled the fair"],
          "b", "He said both ideas could share one corner of the hall.",
          "Read the ending carefully."),
    _comp(P4, "Why does the cricket ground become hard to use in the monsoon?",
          ["It turns muddy", "It becomes too dry", "It is locked forever", "It has no coach"],
          "a", "The ground turns muddy during the monsoon.",
          "Find the monsoon detail."),
    _comp(P4, "Where does the coach move practice on rainy evenings?",
          ["To the beach", "To the indoor hall", "To the library", "To Uncle Raju’s stall"],
          "b", "Practice moves to the indoor hall.",
          "Locate the indoor practice sentence."),
    _comp(P4, "What happened last Tuesday?",
          ["They played until dusk outdoors", "Lightning flashed and practice was cut short",
           "Priya bought tomatoes", "Mr Das cancelled science club"],
          "b", "Lightning flashed and practice was cut short.",
          "Find Tuesday’s event."),
    _comp(P4, "How did Priya use the extra time?",
          ["She slept", "She mended her bat grip", "She wrote a folk tale", "She sorted plastic"],
          "b", "She used the time to mend her bat grip.",
          "Look for Priya’s action after practice stopped."),
    _comp(P4, "What lesson did Priya share with her friend?",
          ["Speed matters most", "Patience is part of becoming a better player",
           "Never practise indoors", "Mud is good for batting"],
          "b", "She said patience is part of becoming a better player.",
          "Find Priya’s message about patience."),
    _comp(P4, "What did the team do on Wednesday?",
          ["Stayed home", "Practised fielding until dusk", "Visited the library", "Made seed balls"],
          "b", "With the sun back, they practised fielding until dusk.",
          "Read the final sentence."),
]

ENG_COMP_B = [
    _comp(P1, "Meera is Kabir’s —",
          ["librarian", "sister", "coach", "vendor"],
          "b", "The opening calls Meera his sister.",
          "Check how Meera is introduced."),
    _comp(P1, "The new shelf held books by —",
          ["only foreign authors", "Indian authors", "Mrs Rao alone", "scientists only"],
          "b", "Mrs Rao showed a shelf of books by Indian authors.",
          "Find who wrote the new books."),
    _comp(P1, "Which word best describes Mrs Rao in this passage?",
          ["Unhelpful", "Helpful", "Angry", "Absent"],
          "b", "She showed them a new shelf — a helpful action.",
          "Infer from what Mrs Rao does."),
    _comp(P1, "Kabir’s article topic is closest to —",
          ["coastal protection", "indoor cricket", "market prices", "folk dances"],
          "a", "Mangroves protecting the coast is about coastal protection.",
          "Link mangroves to the main idea."),
    _comp(P1, "The main purpose of the visit was —",
          ["to buy tomatoes", "to borrow or explore books", "to plant mangroves", "to mend a bat"],
          "b", "They visit the library and borrow/find reading material.",
          "What do people usually do at a library here?"),
    _comp(P1, "Which detail is NOT in the passage?",
          ["They visit every Sunday", "Meera likes folk tales", "Kabir bought a cricket bat", "They will return books in ten days"],
          "c", "No cricket bat is mentioned for Kabir.",
          "Eliminate details that appear; find the outsider."),
    _comp(P2, "Amma buys from the same stall —",
          ["each week", "once a year", "never", "only in the monsoon"],
          "a", "She buys from the same stall each week.",
          "Find the frequency."),
    _comp(P2, "What did Amma buy besides coriander?",
          ["Two kilos of tomatoes", "Science magazines", "Seed balls", "A cricket bat"],
          "a", "She asked for two kilos of tomatoes and a bunch of coriander.",
          "List the items in her order."),
    _comp(P2, "Uncle Raju’s smile suggests he is —",
          ["rude", "friendly", "afraid", "silent always"],
          "b", "Smiling while talking about fresh coriander suggests friendliness.",
          "Infer from his manner."),
    _comp(P2, "The money amount uses which currency symbol in the passage?",
          ["$", "₹", "€", "£"],
          "b", "Amma paid ₹90.",
          "Find the currency mark."),
    _comp(P2, "Who walked home with Amma?",
          ["Uncle Raju", "Her son", "Mrs Rao", "Mr Das"],
          "b", "She told her son on the walk home.",
          "Who receives Amma’s comment?"),
    _comp(P2, "The passage’s closing message praises —",
          ["rushing", "honesty in trade", "ignoring vendors", "high prices"],
          "b", "Honest traders make shopping a pleasure.",
          "Focus on the final moral."),
    _comp(P3, "Who explained that recycling paper saves trees?",
          ["Rohan", "Ananya", "Mr Das", "Uncle Raju"],
          "b", "Ananya explained that point.",
          "Match speaker to idea."),
    _comp(P3, "Rohan’s fair idea was about —",
          ["seed balls", "composting", "folk tales", "mangroves"],
          "b", "Rohan wanted a demo on composting.",
          "Find Rohan’s suggestion."),
    _comp(P3, "Mr Das is the students’ —",
          ["vendor", "coach", "teacher", "librarian"],
          "c", "The passage calls him their teacher.",
          "Read his introduction."),
    _comp(P3, "How did the group react when Mr Das approved sharing a corner?",
          ["They cried", "Everyone clapped", "They left silently", "They cancelled recycling"],
          "b", "Everyone clapped.",
          "Find the reaction word."),
    _comp(P3, "The annual fair ideas are mainly about —",
          ["sports scores", "caring for the environment", "buying tomatoes", "library fines"],
          "b", "Seed balls and composting are environment-care ideas.",
          "What theme links both stalls?"),
    _comp(P3, "Which statement is true?",
          ["Only Ananya may present", "Both ideas can share one corner",
           "Mr Das forbade recycling talk", "The club met before breakfast"],
          "b", "Mr Das said both ideas could share one corner.",
          "Check the teacher’s decision."),
    _comp(P4, "Priya’s coach changes the venue when —",
          ["it is sunny", "evenings are rainy", "the library opens", "tomatoes are cheap"],
          "b", "On rainy evenings practice moves indoors.",
          "Link weather to venue."),
    _comp(P4, "Why was Tuesday’s practice cut short?",
          ["Priya was late", "Lightning flashed", "The bat was perfect", "The hall was closed forever"],
          "b", "Lightning led to cutting practice short.",
          "Find the Tuesday cause."),
    _comp(P4, "“Patience is part of becoming a better player” is —",
          ["Priya’s belief", "Uncle Raju’s price list", "Mrs Rao’s library rule", "A mangrove fact"],
          "a", "Priya told her friend that idea.",
          "Who says it?"),
    _comp(P4, "On Wednesday the team practised —",
          ["batting only for one minute", "fielding until dusk", "sewing", "recycling paper"],
          "b", "They practised fielding until dusk.",
          "Read Wednesday’s action."),
    _comp(P4, "The passage suggests Priya is —",
          ["giving up cricket", "using setbacks to improve", "afraid of the sun", "a librarian"],
          "b", "She mends her grip and values patience — improving through setbacks.",
          "Infer from her actions and words."),
    _comp(P4, "Which title best fits Passage P4?",
          ["Market Day Bargains", "Rain, Practice and Patience", "Mangroves at War", "Library Sundays"],
          "b", "The focus is rainy practice, patience and returning to the ground.",
          "Choose the title that covers the whole story."),
]

ENG_GRAM_A = [
    q("Choose the correct verb: She ____ to school by bus.",
      ["go", "goes", "going", "gone"], "b",
      "She is singular third person, so the present form is goes.",
      "Match singular subject to singular verb."),
    q("Choose the correct verb: The boys ____ playing cricket.",
      ["is", "are", "am", "be"], "b",
      "Boys is plural → are.",
      "Plural subject needs a plural verb."),
    q("Identify the noun: The librarian opened a new shelf.",
      ["opened", "new", "librarian", "a"], "c",
      "Librarian names a person — a noun.",
      "Which word names a person, place or thing?"),
    q("Identify the adjective: Meera read an exciting story.",
      ["Meera", "read", "exciting", "story"], "c",
      "Exciting describes the story — an adjective.",
      "Find the describing word."),
    q("Choose the correct article: ____ apple a day keeps the doctor away.",
      ["A", "An", "The only ever", "No article possible"], "b",
      "Apple begins with a vowel sound → an.",
      "Use an before vowel sounds."),
    q("Choose the correct article: ____ Himalayas are beautiful.",
      ["A", "An", "The", "No article"], "c",
      "Mountain ranges take the: the Himalayas.",
      "Unique ranges usually need the."),
    q("Past tense of write is —", ["writed", "wrote", "writtened", "writing"], "b",
      "Write → wrote (past) → written (past participle).",
      "Irregular past of write."),
    q("Choose the correct pronoun: Ravi and ____ are partners.",
      ["me", "I", "mine", "myself"], "b",
      "Subject position needs I: Ravi and I.",
      "Would you say I are partners or me are partners?"),
    q("Which sentence is in the future tense?",
      ["She walks home.", "She walked home.", "She will walk home.", "She is walking home."], "c",
      "Will walk marks future time.",
      "Look for will + verb."),
    q("Choose the correct form: Neither of the answers ____ correct.",
      ["are", "is", "were", "be"], "b",
      "Neither is singular → is.",
      "Neither/either take singular verbs in school grammar."),
    q("Identify the adverb: He spoke politely to the vendor.",
      ["He", "spoke", "politely", "vendor"], "c",
      "Politely tells how he spoke — an adverb.",
      "How did he speak?"),
    q("Choose the correct preposition: The book is ____ the table.",
      ["in", "on", "at", "by only for people"], "b",
      "On the table is the usual preposition for surface contact.",
      "Surface → on."),
    q("Which is a complete sentence?",
      ["When the rain stopped.", "The rain stopped.", "Because the rain.", "Stopping the rain."], "b",
      "The rain stopped has a subject and a finite verb.",
      "Need a full subject + verb thought."),
    q("Choose the correct comparative: This rope is ____ than that one.",
      ["strong", "stronger", "strongest", "more stronger"], "b",
      "Comparing two things → stronger (not more stronger).",
      "Two items → comparative form."),
    q("Choose the correct superlative: Mount Everest is the ____ peak.",
      ["high", "higher", "highest", "most highest"], "c",
      "Among many peaks → highest.",
      "Superlative for the extreme."),
    q("Direct to indirect: She said, “I am ready.” → She said that she ____ ready.",
      ["am", "was", "is", "were"], "b",
      "Present am becomes was in backshift after a past reporting verb.",
      "Backshift the tense after said."),
    q("Choose the correct conjunction: I stayed home ____ it was raining.",
      ["and", "but", "because", "or"], "c",
      "Because shows reason.",
      "Which linker shows cause?"),
    q("Identify the subject: Across the field ran the foal.",
      ["Across", "the field", "ran", "the foal"], "d",
      "The foal is who ran — the subject, even after the verb.",
      "Who did the action?"),
    q("Choose the correct verb: Bread and butter ____ his breakfast.",
      ["are", "is", "were", "be"], "b",
      "Treated as one dish → singular is.",
      "Paired food as one unit."),
    q("Which word is a collective noun?",
      ["team", "player", "run", "quickly"], "a",
      "Team names a group — a collective noun.",
      "Word for a group acting as one."),
    q("Choose the correct form: The news ____ good today.",
      ["are", "is", "were", "have"], "b",
      "News is singular in agreement → is.",
      "News takes a singular verb."),
    q("Identify the interjection: Wow! That catch was brilliant.",
      ["That", "catch", "Wow", "brilliant"], "c",
      "Wow! expresses sudden feeling — an interjection.",
      "Which word bursts with feeling?"),
    q("Choose the correct tense: She ____ her homework before dinner yesterday.",
      ["finishes", "finish", "finished", "will finish"], "c",
      "Yesterday marks past → finished.",
      "Time word yesterday → past tense."),
    q("Which sentence uses a possessive pronoun?",
      ["This book is her.", "This book is hers.", "This book is she.", "This book is him."], "b",
      "Hers is the possessive pronoun form.",
      "Possessive pronouns: mine, yours, his, hers, ours, theirs."),
]

ENG_GRAM_B = [
    q("Choose the correct verb: My friends ____ here.",
      ["lives", "live", "living", "lived always only"], "b",
      "Friends is plural → live.",
      "Plural subject → plural verb."),
    q("Choose the correct verb: Either Rina or her brothers ____ coming.",
      ["is", "are", "am", "be"], "b",
      "With either…or, the verb agrees with the nearer subject: brothers → are.",
      "Agree with the noun closest to the verb."),
    q("Identify the verb: The mangroves protect the coast.",
      ["mangroves", "protect", "the", "coast"], "b",
      "Protect is the action word — the verb.",
      "Which word shows the action?"),
    q("Choose the correct article: He is ____ honest man.",
      ["a", "an", "the only", "no article"], "b",
      "Honest begins with a vowel sound → an.",
      "Listen for the vowel sound, not just the letter."),
    q("Past participle of eat is —", ["ate", "eated", "eaten", "eating"], "c",
      "Eat → ate → eaten.",
      "Third form after has/have."),
    q("Choose the correct pronoun: Let ____ help you.",
      ["I", "me", "mine", "myself"], "b",
      "After let, use object form me.",
      "Object pronoun after let."),
    q("Which sentence is in the present continuous?",
      ["She writes a letter.", "She wrote a letter.", "She is writing a letter.", "She will write a letter."], "c",
      "Is writing shows an action in progress.",
      "Look for be + -ing."),
    q("Choose the correct preposition: Divide the sweets ____ the two sisters.",
      ["among", "between", "in", "into only for liquids"], "b",
      "Between is used for two; among for more than two.",
      "Two people → between."),
    q("Identify the conjunction: Hurry up, or we will miss the bus.",
      ["Hurry", "up", "or", "bus"], "c",
      "Or joins alternatives — a conjunction.",
      "Which word links choices?"),
    q("Choose the correct comparative: Iron is ____ than wood.",
      ["heavy", "heavier", "heaviest", "more heavier"], "b",
      "Comparing two materials → heavier.",
      "Two-item comparison."),
    q("Change to plural: The child is sleeping.",
      ["The childs is sleeping.", "The children are sleeping.", "The childrens is sleeping.", "The child are sleeping."], "b",
      "Child → children; verb becomes are.",
      "Irregular plural + verb agreement."),
    q("Which is an interrogative sentence?",
      ["Close the door.", "What a catch!", "Where is my bat?", "The bat is new."], "c",
      "Where is my bat? asks a question.",
      "Questions ask; they often end with ?"),
    q("Choose the correct form: She has ____ the letter.",
      ["wrote", "written", "write", "writing"], "b",
      "Has takes the past participle written.",
      "Has/have + past participle."),
    q("Identify the object: Kabir borrowed a magazine.",
      ["Kabir", "borrowed", "a magazine", "None"], "c",
      "A magazine receives the action — the object.",
      "What was borrowed?"),
    q("Choose the correct determiner: There isn’t ____ milk left.",
      ["many", "much", "few", "several"], "b",
      "Milk is uncountable → much.",
      "Uncountable nouns take much, not many."),
    q("Which sentence is imperative?",
      ["Please return the books in ten days.", "The books are new.", "Are the books new?", "What useful books!"], "a",
      "Please return… gives a polite command/request.",
      "Imperatives tell someone to do something."),
    q("Choose the correct relative pronoun: The girl ____ planted trees is Meera’s heroine.",
      ["which", "who", "whose", "what"], "b",
      "Who refers to people.",
      "People → who."),
    q("Active to passive: The coach moved practice indoors. → Practice ____ indoors by the coach.",
      ["moved", "was moved", "is moving", "were move"], "b",
      "Past active moved → was moved in passive.",
      "Be + past participle for passive."),
    q("Choose the correct verb: The committee ____ decided the date.",
      ["have", "has", "are", "were"], "b",
      "Committee as one body → has.",
      "Collective noun as a unit → singular."),
    q("Identify the abstract noun: Honesty makes shopping a pleasure.",
      ["Honesty", "makes", "shopping", "a"], "a",
      "Honesty names a quality — an abstract noun.",
      "Which word names an idea you cannot touch?"),
    q("Choose the correct form: If it rains, we ____ indoors.",
      ["practise", "practised", "will practise", "practising"], "c",
      "First conditional: if + present, will + verb.",
      "If + present → will + base verb."),
    q("Which word is a synonym connector meaning ‘but’?",
      ["and", "however", "because", "therefore"], "b",
      "However introduces a contrast, like but.",
      "Contrast linker."),
    q("Choose the correct order: (a) a red (b) she bought (c) ribbon",
      ["a-b-c", "b-a-c", "c-b-a", "a-c-b"], "b",
      "She bought a red ribbon.",
      "Subject–verb–object with adjective before noun."),
    q("Which sentence has correct punctuation?",
      ["Wow that catch was brilliant", "Wow! That catch was brilliant.", "Wow. that catch was brilliant", "Wow that catch was brilliant?"], "b",
      "Interjection takes ! and the next sentence starts with a capital.",
      "Exclamation mark + capital."),
]

ENG_VOCAB_A = [
    q("Synonym of ancient is —", ["modern", "old", "tiny", "quick"], "b",
      "Ancient means very old.",
      "Which word is closest in meaning to ancient?"),
    q("Antonym of brave is —", ["courageous", "timid", "bold", "heroic"], "b",
      "Timid is the opposite of brave.",
      "Opposite of brave."),
    q("Synonym of assist is —", ["hinder", "help", "ignore", "delay"], "b",
      "Assist means help.",
      "Near meaning of assist."),
    q("Antonym of scarce is —", ["rare", "plentiful", "little", "thin"], "b",
      "Scarce means not enough; plentiful is the opposite.",
      "Opposite of not-enough."),
    q("In “the storm was fierce,” fierce means —", ["gentle", "violent", "silent", "colourful"], "b",
      "Fierce here means violent or intense.",
      "Use the storm context."),
    q("Choose the word that means ‘a person who sells goods’:",
      ["vendor", "author", "coach", "passenger"], "a",
      "A vendor sells goods.",
      "Seller word."),
    q("Prefix un- in unkind means —", ["very", "not", "again", "before"], "b",
      "Un- often means not: unkind = not kind.",
      "What does un- usually do?"),
    q("Suffix -ful in useful means —", ["without", "full of", "against", "before"], "b",
      "Useful means full of use / having use.",
      "-ful ≈ full of."),
    q("Synonym of glance is —", ["stare for hours", "quick look", "shout", "run"], "b",
      "A glance is a quick look.",
      "Brief look word."),
    q("Antonym of generous is —", ["kind", "selfish", "open", "giving"], "b",
      "Selfish is opposite of generous.",
      "Opposite of giving freely."),
    q("Choose the correct meaning of transparent:",
      ["Cannot be seen through", "Can be seen through", "Very heavy", "Always wet"], "b",
      "Transparent materials let light through so you can see through them.",
      "See-through meaning."),
    q("Homophone of pair is —", ["pear", "peer only", "pour", "poor only"], "a",
      "Pair and pear sound alike but differ in meaning.",
      "Same sound, different spelling."),
    q("Synonym of commence is —", ["end", "begin", "pause", "cancel"], "b",
      "Commence means begin.",
      "Start word."),
    q("Antonym of expand is —", ["grow", "contract", "rise", "spread"], "b",
      "Contract means shrink — opposite of expand.",
      "Opposite of get bigger."),
    q("In “honest traders,” honest means —", ["truthful and fair", "rich", "loud", "new"], "a",
      "Honest means truthful and fair.",
      "Context of traders."),
    q("Choose the odd one out (not a synonym of happy):",
      ["joyful", "glad", "miserable", "cheerful"], "c",
      "Miserable means unhappy — the odd one.",
      "Which word does not mean happy?"),
    q("Meaning of durable:",
      ["Easily broken", "Lasting a long time", "Always soft", "Invisible"], "b",
      "Durable means lasting / not easily worn out.",
      "Long-lasting materials."),
    q("Antonym of arrival is —", ["entry", "departure", "welcome", "visit"], "b",
      "Departure is the opposite of arrival.",
      "Coming vs going."),
    q("Synonym of cautious is —", ["careless", "careful", "noisy", "swift always"], "b",
      "Cautious means careful.",
      "Near meaning of cautious."),
    q("The idiom “break the ice” means —",
      ["smash frozen water only", "start a friendly conversation", "end a game", "buy vegetables"], "b",
      "Break the ice means to start conversation and ease tension.",
      "Figurative meaning, not literal ice."),
    q("Choose the correct word: The ____ of the story is to be patient.",
      ["morale", "moral", "mural", "mortal"], "b",
      "Moral means the lesson of a story.",
      "Story lesson word."),
    q("Antonym of artificial is —", ["fake", "natural", "plastic", "copied"], "b",
      "Natural is opposite of artificial.",
      "Opposite of man-made."),
    q("Synonym of fragrant is —", ["smelly in a bad way", "sweet-smelling", "silent", "rough"], "b",
      "Fragrant means sweet-smelling.",
      "Pleasant smell word."),
    q("In “sorting plastic from kitchen waste,” waste means —",
      ["valuable treasure", "unwanted discarded material", "a footrace", "a library shelf"], "b",
      "Waste here means discarded unwanted material.",
      "Context of kitchen rubbish."),
]

ENG_VOCAB_B = [
    q("Synonym of rapid is —", ["slow", "quick", "heavy", "quiet"], "b",
      "Rapid means quick.",
      "Near meaning of rapid."),
    q("Antonym of noisy is —", ["loud", "quiet", "busy", "bright"], "b",
      "Quiet is the opposite of noisy.",
      "Opposite of noisy."),
    q("Synonym of tiny is —", ["huge", "small", "tall", "wide"], "b",
      "Tiny means very small.",
      "Near meaning of tiny."),
    q("Antonym of victory is —", ["win", "defeat", "prize", "cheer"], "b",
      "Defeat is the opposite of victory.",
      "Opposite of winning."),
    q("In “fresh coriander,” fresh means —", ["stale", "recently harvested / not stale", "frozen solid", "expensive"], "b",
      "Fresh means newly produced / not stale.",
      "Food context."),
    q("Choose the word meaning ‘protect from harm’:",
      ["endanger", "shield", "ignore", "scatter"], "b",
      "Shield means protect.",
      "Protect synonym."),
    q("Prefix re- in rewrite means —", ["not", "again", "wrongly", "against"], "b",
      "Re- often means again: rewrite = write again.",
      "Again prefix."),
    q("Suffix -less in careless means —", ["full of", "without", "more", "before"], "b",
      "Careless means without care.",
      "-less ≈ without."),
    q("Synonym of purchase is —", ["sell", "buy", "borrow", "lose"], "b",
      "Purchase means buy.",
      "Buy word."),
    q("Antonym of include is —", ["contain", "exclude", "add", "list"], "b",
      "Exclude is the opposite of include.",
      "Opposite of include."),
    q("Meaning of fertile (soil):",
      ["barren", "able to grow plants well", "always sandy", "made of plastic"], "b",
      "Fertile soil is good for growing plants.",
      "Farming context."),
    q("Homophone of sea is —", ["see", "say", "sigh", "sow"], "a",
      "Sea and see sound the same.",
      "Same sound pair."),
    q("Synonym of vanish is —", ["appear", "disappear", "shine", "grow"], "b",
      "Vanish means disappear.",
      "Near meaning of vanish."),
    q("Antonym of polite is —", ["courteous", "rude", "kind", "gentle"], "b",
      "Rude is opposite of polite.",
      "Opposite of polite."),
    q("In “annual fair,” annual means —", ["weekly", "happening once a year", "daily", "never"], "b",
      "Annual means once a year.",
      "Yearly word."),
    q("Odd one out (not a synonym of big):",
      ["large", "huge", "tiny", "enormous"], "c",
      "Tiny means small — the odd one.",
      "Which is not big?"),
    q("Meaning of flexible:",
      ["unable to bend", "able to bend easily", "always wet", "made of stone only"], "b",
      "Flexible means able to bend without breaking.",
      "Bendable meaning."),
    q("Antonym of temporary is —", ["brief", "permanent", "short", "passing"], "b",
      "Permanent is opposite of temporary.",
      "Opposite of lasting only a short time."),
    q("Synonym of difficult is —", ["easy", "hard", "simple", "clear"], "b",
      "Difficult means hard.",
      "Near meaning of difficult."),
    q("The idiom “a piece of cake” means —",
      ["a dessert only", "something very easy", "something expensive", "a cricket shot"], "b",
      "Informally, a piece of cake means very easy.",
      "Figurative ease."),
    q("Choose the correct word: Please ____ the lights when you leave.",
      ["close", "switch off", "open", "grow"], "b",
      "We switch off / turn off lights (not close lights).",
      "Natural collocation for lights."),
    q("Antonym of public is —", ["open", "private", "common", "shared"], "b",
      "Private is opposite of public.",
      "Opposite of public."),
    q("Synonym of weary is —", ["fresh", "tired", "excited", "loud"], "b",
      "Weary means tired.",
      "Near meaning of weary."),
    q("In “fielding until dusk,” dusk means —",
      ["midday", "evening twilight", "midnight only", "dawn"], "b",
      "Dusk is the dim light at the end of the day.",
      "End-of-day light."),
]

SCI_FOOD_A = [
    q("Which nutrient is the body’s main source of energy?",
      ["Vitamin C", "Carbohydrate", "Water", "Iron"], "b",
      "Carbohydrates from foods like rice and roti are the main energy source.",
      "Energy nutrient group.", bp=BP_HINTS_SCI),
    q("Proteins are mainly needed for —",
      ["body building and repair", "only night vision", "making food sweet", "colouring clothes"], "a",
      "Proteins help build and repair body tissues.",
      "Body-building nutrient.", bp=BP_HINTS_SCI),
    q("Which food is rich in dietary fibre (roughage)?",
      ["Clear oil", "Whole grains and vegetables", "Sugar only", "Salt"], "b",
      "Whole grains, fruits and vegetables provide roughage.",
      "Fibre foods.", bp=BP_HINTS_SCI),
    q("Vitamin C deficiency can cause —",
      ["scurvy", "goitre", "night blindness", "anaemia from iron only"], "a",
      "Lack of vitamin C leads to scurvy.",
      "Link vitamin C to its deficiency disease.", bp=BP_HINTS_SCI),
    q("Iodine deficiency is linked to —",
      ["scurvy", "goitre", "rickets", "beri-beri"], "b",
      "Lack of iodine can cause goitre (swollen thyroid).",
      "Iodine → thyroid.", bp=BP_HINTS_SCI),
    q("Which vitamin is needed for good night vision?",
      ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin B1 only for bones"], "a",
      "Vitamin A helps prevent night blindness.",
      "Eyes and vitamin A.", bp=BP_HINTS_SCI),
    q("Sunlight helps our skin make —",
      ["Vitamin C", "Vitamin D", "Iron", "Iodine"], "b",
      "Sunlight helps the body produce vitamin D.",
      "Sunshine vitamin.", bp=BP_HINTS_SCI),
    q("A balanced diet means —",
      ["only sweets", "enough of all nutrient groups in right amounts", "only protein", "skipping breakfast always"], "b",
      "A balanced diet includes carbohydrates, proteins, fats, vitamins, minerals, fibre and water in suitable amounts.",
      "All groups, right amounts.", bp=BP_HINTS_SCI),
    q("Which of these is a body-building food?",
      ["Sugar candy", "Dal and milk", "Clear aerated drink", "Salt alone"], "b",
      "Dal and milk are rich in proteins.",
      "Protein-rich foods.", bp=BP_HINTS_SCI),
    q("Fats give more energy per gram than carbohydrates, but too much fat can —",
      ["always cure scurvy", "lead to obesity and heart strain", "replace water needs", "remove all fibre"], "b",
      "Excess fat is linked to obesity and other health problems.",
      "Risk of excess fat.", bp=BP_HINTS_SCI),
    q("Iron is important because it —",
      ["makes bones yellow", "helps make haemoglobin in blood", "sweetens fruit", "spins cotton"], "b",
      "Iron is needed for haemoglobin, which carries oxygen.",
      "Iron → blood.", bp=BP_HINTS_SCI),
    q("Which meal is closest to balanced?",
      ["Only chips", "Roti, dal, sabzi and curd", "Only sweets", "Only aerated drinks"], "b",
      "Roti (energy), dal (protein), sabzi (vitamins/fibre) and curd (protein/minerals) cover key groups.",
      "Look for mixed nutrient groups.", bp=BP_HINTS_SCI),
    q("Water in the diet is essential because it —",
      ["has no role", "helps transport nutrients and remove wastes", "replaces all proteins", "is a carbohydrate"], "b",
      "Water transports substances and helps remove wastes.",
      "Jobs of water.", bp=BP_HINTS_SCI),
    q("Night blindness is linked to lack of —",
      ["Vitamin A", "Iodine", "Vitamin C", "Calcium only"], "a",
      "Vitamin A deficiency can cause night blindness.",
      "Night vision vitamin.", bp=BP_HINTS_SCI),
    q("Rickets in children is linked to lack of —",
      ["Vitamin D / calcium issues", "Vitamin C only", "Iodine only", "Fibre only"], "a",
      "Rickets relates to vitamin D and calcium problems affecting bones.",
      "Bone-softening deficiency.", bp=BP_HINTS_SCI),
    q("Which is a protective food?",
      ["Oil alone", "Fruits and green vegetables", "Sugar alone", "Butter alone"], "b",
      "Fruits and greens supply vitamins and minerals that protect health.",
      "Protective = vitamins/minerals rich.", bp=BP_HINTS_SCI),
    q("Obesity can result from —",
      ["eating far more energy than you use", "drinking only water", "eating only greens forever", "iodine deficiency alone"], "a",
      "Taking in much more energy than the body uses leads to fat storage and obesity.",
      "Energy in vs energy out.", bp=BP_HINTS_SCI),
    q("Oranges and amla are good sources of —",
      ["Vitamin C", "Iodine", "Iron only", "Vitamin D only"], "a",
      "Citrus fruits and amla are rich in vitamin C.",
      "Vitamin C foods.", bp=BP_HINTS_SCI),
    q("Milk is a good source of —",
      ["only fibre", "protein and calcium", "iodine only", "roughage only"], "b",
      "Milk provides proteins and calcium for bones and teeth.",
      "Nutrients in milk.", bp=BP_HINTS_SCI),
    q("Roughage helps mainly in —",
      ["night vision", "smooth bowel movement", "making haemoglobin", "iodine uptake only"], "b",
      "Dietary fibre aids digestion and bowel movement.",
      "Job of fibre.", bp=BP_HINTS_SCI),
    q("Which habit supports good nutrition?",
      ["Skipping breakfast daily", "Washing vegetables before cooking", "Eating only fried snacks", "Never drinking water"], "b",
      "Washing produce reduces dirt and germs — a healthy food habit.",
      "Safe food habit.", bp=BP_HINTS_SCI),
    q("Beriberi is associated with deficiency of —",
      ["Vitamin B1 (thiamine)", "Vitamin C", "Iodine", "Vitamin A"], "a",
      "Beriberi is linked to lack of vitamin B1.",
      "B1 deficiency disease.", bp=BP_HINTS_SCI),
    q("A person with anaemia may need more —",
      ["iron-rich foods", "only sugar", "only oil", "iodised salt only for taste"], "a",
      "Anaemia often relates to iron deficiency; iron-rich foods help.",
      "Anaemia and iron.", bp=BP_HINTS_SCI),
    q("Why is iodised salt recommended?",
      ["It colours food blue", "It helps prevent iodine deficiency disorders", "It replaces all vitamins", "It is pure carbohydrate"], "b",
      "Iodised salt supplies iodine to prevent goitre and related problems.",
      "Why add iodine to salt?", bp=BP_HINTS_SCI),
]

SCI_FOOD_B = [
    q("Carbohydrates are stored in plants mainly as —",
      ["starch", "iron filings", "plastic", "iodine crystals"], "a",
      "Plants store carbohydrates largely as starch.",
      "Plant storage form.", bp=BP_HINTS_SCI),
    q("Which food is a rich protein source for many vegetarians?",
      ["Pulses (dal)", "Sugar", "Clear oil", "Salt"], "a",
      "Pulses are important protein foods in vegetarian diets.",
      "Veg protein.", bp=BP_HINTS_SCI),
    q("Vitamin D helps the body use —",
      ["calcium for bones", "iodine only", "fibre only", "plastic"], "a",
      "Vitamin D aids calcium use for strong bones.",
      "D and bones.", bp=BP_HINTS_SCI),
    q("Which is NOT a nutrient?",
      ["Protein", "Vitamin", "Roughage (fibre)", "Plate"], "d",
      "A plate is not a nutrient; fibre is considered an important dietary component.",
      "Which item is not food chemistry?", bp=BP_HINTS_SCI),
    q("Ghee and butter are rich in —",
      ["fibre", "fat", "vitamin C only", "iodine only"], "b",
      "Ghee and butter are fat-rich foods.",
      "Fat foods.", bp=BP_HINTS_SCI),
    q("Scurvy symptoms can include —",
      ["bleeding gums", "goitre only", "blue skin from iodine", "stronger night vision"], "a",
      "Scurvy (vitamin C lack) can cause bleeding gums.",
      "Scurvy signs.", bp=BP_HINTS_SCI),
    q("A diet with only rice for weeks may lack —",
      ["enough variety of nutrients", "all carbohydrates forever", "water in rice", "any energy"], "a",
      "Single-food diets miss proteins, vitamins and minerals.",
      "Why variety matters.", bp=BP_HINTS_SCI),
    q("Leafy greens like spinach provide —",
      ["iron and vitamins", "only pure fat", "only sugar", "plastic fibre"], "a",
      "Spinach offers iron and vitamins among other nutrients.",
      "Greens’ gifts.", bp=BP_HINTS_SCI),
    q("Which drink is healthiest as an everyday habit?",
      ["Sweet aerated drinks only", "Clean water", "Only deep-fried tea", "Undiluted syrup"], "b",
      "Clean water is essential every day.",
      "Daily drink choice.", bp=BP_HINTS_SCI),
    q("Calcium is especially important for —",
      ["bones and teeth", "making cloth", "magnetism", "evaporation"], "a",
      "Calcium strengthens bones and teeth.",
      "Calcium’s job.", bp=BP_HINTS_SCI),
    q("Energy-giving foods include —",
      ["rice and potato", "only vitamin tablets", "only water", "only salt"], "a",
      "Rice and potato are carbohydrate-rich energy foods.",
      "Energy examples.", bp=BP_HINTS_SCI),
    q("Junk food is often —",
      ["low in nutrients and high in sugar/fat/salt", "a complete balanced diet", "the only source of iodine", "rich in all vitamins always"], "a",
      "Many junk foods are energy-dense but nutrient-poor.",
      "What’s wrong with excess junk food?", bp=BP_HINTS_SCI),
    q("Which vitamin is easily destroyed by heavy cooking in some vegetables?",
      ["Vitamin C", "Iron metal", "Iodine crystals", "Plastic"], "a",
      "Vitamin C is heat-sensitive; gentle cooking helps retain it.",
      "Heat-sensitive vitamin.", bp=BP_HINTS_SCI),
    q("Eggs are a good source of —",
      ["protein", "only fibre", "only iodine salt", "cotton"], "a",
      "Eggs provide high-quality protein.",
      "Egg nutrient.", bp=BP_HINTS_SCI),
    q("A child who rarely plays outdoors may risk low —",
      ["vitamin D", "cotton fibre", "plastic", "magnetism"], "a",
      "Less sunlight can mean less vitamin D production.",
      "Outdoor light and vitamins.", bp=BP_HINTS_SCI),
    q("Which statement is true?",
      ["Fats are never needed", "Some fat is needed but not in excess", "Only sugar is a balanced diet", "Water is optional forever"], "b",
      "The body needs some fat for energy and vitamins, but excess is harmful.",
      "Balance about fats.", bp=BP_HINTS_SCI),
    q("Goitre affects the —",
      ["thyroid gland in the neck", "only the toenails", "cotton boll", "cricket bat"], "a",
      "Goitre is swelling of the thyroid in the neck.",
      "Where is the thyroid?", bp=BP_HINTS_SCI),
    q("Which food pair gives both energy and body-building nutrients?",
      ["Rice and dal", "Only sugar and salt", "Only oil and sugar", "Only aerated drink and chips"], "a",
      "Rice (carb) + dal (protein) cover energy and building.",
      "Pair energy + protein.", bp=BP_HINTS_SCI),
    q("Oral rehydration after diarrhoea mainly replaces —",
      ["lost water and salts", "cotton", "vitamin A only", "plastic"], "a",
      "ORS replaces fluids and electrolytes.",
      "What ORS restores.", bp=BP_HINTS_SCI),
    q("Which is a deficiency disease?",
      ["Scurvy", "Filtration", "Weaving", "Sieving"], "a",
      "Scurvy is caused by nutrient deficiency.",
      "Disease from missing nutrient.", bp=BP_HINTS_SCI),
    q("Millets in a diet can help because they often provide —",
      ["fibre and minerals with energy", "only pure fat", "no nutrients", "iodine metal pieces"], "a",
      "Millets contribute energy plus fibre and minerals.",
      "Why millets help.", bp=BP_HINTS_SCI),
    q("Too little protein in the diet may lead to —",
      ["poor growth and repair", "stronger muscles always", "extra vitamin C only", "automatic goitre cure"], "a",
      "Proteins are needed for growth and tissue repair.",
      "Low protein effect.", bp=BP_HINTS_SCI),
    q("Which practice keeps food safer?",
      ["Leaving cooked food uncovered for days", "Covering and refrigerating leftovers promptly", "Using dirty utensils", "Never washing hands"], "b",
      "Covering and chilling leftovers reduces spoilage and germ growth.",
      "Food safety habit.", bp=BP_HINTS_SCI),
    q("A balanced thali for a schoolchild should usually include —",
      ["only dessert", "cereal, protein food, vegetables/fruit and some fat in moderation", "only fried snacks", "only vitamins pills"], "b",
      "A mixed thali covers major nutrient groups.",
      "Picture a complete plate.", bp=BP_HINTS_SCI),
]

SCI_FIBRE_A = [
    q("Cotton fibre comes from the —",
      ["stem of jute only", "cotton plant’s boll", "sheep’s fleece", "silkworm cocoon"], "b",
      "Cotton fibres grow in the boll of the cotton plant.",
      "Plant source of cotton.", bp=BP_HINTS_SCI),
    q("Wool is obtained from —",
      ["cotton plants", "sheep (and some other animals)", "jute stems", "nylon factories only"], "b",
      "Wool is an animal fibre from sheep and similar animals.",
      "Animal fibre for woollens.", bp=BP_HINTS_SCI),
    q("Silk fibre is produced by —",
      ["cotton plants", "silkworms", "jute plants", "sheep"], "b",
      "Silkworms spin cocoons of silk fibre.",
      "Who makes silk?", bp=BP_HINTS_SCI),
    q("Jute fibre is mainly obtained from the plant’s —",
      ["flower petals", "stem", "roots only", "seeds only"], "b",
      "Jute fibres come from the stem.",
      "Jute plant part.", bp=BP_HINTS_SCI),
    q("Which is a natural fibre?",
      ["Nylon", "Polyester", "Cotton", "Acrylic"], "c",
      "Cotton is natural; nylon, polyester and acrylic are synthetic.",
      "Natural vs synthetic.", bp=BP_HINTS_SCI),
    q("Which is a synthetic fibre?",
      ["Wool", "Silk", "Polyester", "Jute"], "c",
      "Polyester is made from chemicals — synthetic.",
      "Factory-made fibre.", bp=BP_HINTS_SCI),
    q("Spinning converts —",
      ["fabric into fibre", "fibre into yarn", "yarn into sheep", "plastic into cotton"], "b",
      "Spinning twists fibres into yarn.",
      "Fibre → yarn step.", bp=BP_HINTS_SCI),
    q("Weaving is done on a —",
      ["charkha only forever", "loom", "filter paper", "protractor"], "b",
      "Weaving interlaces yarns on a loom.",
      "Weaving tool.", bp=BP_HINTS_SCI),
    q("Knitting differs from weaving because knitting —",
      ["uses a single yarn looped together", "always needs a loom with two yarn sets", "makes only metals", "grows cotton"], "a",
      "Knitting loops a yarn; weaving crosses two sets of yarns.",
      "Loops vs interlacing.", bp=BP_HINTS_SCI),
    q("Cotton plants grow well in —",
      ["black soil and warm climate (typical regions)", "only polar ice", "only deep ocean", "only deserts with no water ever"], "a",
      "Cotton needs a warm climate and suitable soils such as black soil in many Indian regions.",
      "Cotton growing conditions.", bp=BP_HINTS_SCI),
    q("The process of separating cotton fibres from seeds is —",
      ["ginning", "reeling", "shearing", "sericulture"], "a",
      "Ginning removes seeds from cotton fibres.",
      "Cotton seed removal name.", bp=BP_HINTS_SCI),
    q("Shearing refers to —",
      ["cutting silk cocoons with acid only", "removing wool fleece from sheep", "weaving jute", "filtering water"], "b",
      "Shearing is cutting/removing the sheep’s wool.",
      "Wool harvest step.", bp=BP_HINTS_SCI),
    q("Sericulture is the rearing of —",
      ["sheep", "silkworms", "cotton plants", "jute"], "b",
      "Sericulture means silkworm rearing for silk.",
      "Silk farming word.", bp=BP_HINTS_SCI),
    q("Yarn is —",
      ["a thin continuous strand made from fibres", "a finished stitched shirt only", "a type of soil", "a vitamin"], "a",
      "Yarn is spun fibre ready for fabric making.",
      "Define yarn.", bp=BP_HINTS_SCI),
    q("Which fabric is usually most suitable for hot, humid weather?",
      ["Heavy wool coat", "Cotton", "Thick acrylic winter wear only", "Leather jacket only"], "b",
      "Cotton is breathable and comfortable in heat.",
      "Summer fabric choice.", bp=BP_HINTS_SCI),
    q("Jute is widely used to make —",
      ["winter sweaters only", "gunny bags and mats", "silk sarees only", "nylon ropes only"], "b",
      "Jute is common for sacks, mats and similar goods.",
      "Jute products.", bp=BP_HINTS_SCI),
    q("Which statement is true?",
      ["All fibres are synthetic", "Some fibres are natural and some are synthetic", "Wool comes from cotton seeds", "Silk comes from sheep"], "b",
      "Fibres may be natural (plant/animal) or synthetic.",
      "Two big fibre families.", bp=BP_HINTS_SCI),
    q("Reeling in silk processing means —",
      ["unwinding silk filament from the cocoon", "shearing sheep", "ginning cotton", "knitting wool"], "a",
      "Reeling draws silk filament off the cocoon.",
      "Silk filament step.", bp=BP_HINTS_SCI),
    q("A charkha is used for —",
      ["spinning yarn", "filtering tea", "measuring angles", "evaporating salt"], "a",
      "A charkha is a spinning device.",
      "Gandhian spinning wheel use.", bp=BP_HINTS_SCI),
    q("Which fibre is animal in origin?",
      ["Jute", "Cotton", "Wool", "Coir from coconut husk is plant — so not this wait"], "c",
      "Wool is an animal fibre; jute and cotton are plant fibres.",
      "Animal vs plant fibre.", bp=BP_HINTS_SCI),
    q("Fabric is made from yarn by —",
      ["weaving or knitting", "only evaporation", "only handpicking stones", "only magnet use"], "a",
      "Weaving and knitting turn yarn into fabric.",
      "Yarn → fabric methods.", bp=BP_HINTS_SCI),
    q("Coir fibre comes from —",
      ["coconut husk", "sheep", "silkworm", "nylon pellets"], "a",
      "Coir is from coconut husk — a plant fibre.",
      "Coconut fibre.", bp=BP_HINTS_SCI),
    q("Which property makes cotton clothes comfortable in summer?",
      ["They are waterproof plastic", "They absorb sweat and allow air flow better than many synthetics", "They are always thicker than wool", "They are metals"], "b",
      "Cotton absorbs moisture and breathes.",
      "Why cotton feels cooler.", bp=BP_HINTS_SCI),
    q("Synthetic fibres are often —",
      ["made from petrochemicals", "harvested from sheep", "grown as cotton bolls", "spun by silkworms"], "a",
      "Many synthetics come from chemical/petroleum sources.",
      "Origin of synthetics.", bp=BP_HINTS_SCI),
]

SCI_FIBRE_B = [
    q("Which sequence is correct?",
      ["Fabric → yarn → fibre", "Fibre → yarn → fabric", "Yarn → fibre → fabric", "Fabric → fibre → yarn"], "b",
      "Fibres are spun to yarn, then woven/knitted to fabric.",
      "Order the three stages.", bp=BP_HINTS_SCI),
    q("Lint is a term linked with —",
      ["cotton fibres after ginning", "sheep shearing only", "nylon melt", "salt crystals"], "a",
      "Cotton lint refers to the fibres separated from seeds.",
      "Cotton after ginning.", bp=BP_HINTS_SCI),
    q("Which fibre is strongest among typical silk, wool, cotton comparisons in school science? (often taught)",
      ["Silk is known for strength among natural fibres discussed", "Chalk", "Water", "Steam"], "a",
      "Silk is often noted as a strong natural fibre in class discussions.",
      "Strong natural fibre.", bp=BP_HINTS_SCI),
    q("Polyester clothes —",
      ["dry quickly compared with many cottons", "are always made by silkworms", "come from sheep", "are a vitamin"], "a",
      "Synthetics like polyester often dry quickly.",
      "Synthetic drying property.", bp=BP_HINTS_SCI),
    q("Which animal fibre can come from goats (e.g. pashmina type discussions)?",
      ["Cotton", "Wool/specialty animal underfur fibres", "Jute", "Nylon"], "b",
      "Some fine animal fibres come from goats; wool broadly is animal.",
      "Animal fibre sources beyond sheep.", bp=BP_HINTS_SCI),
    q("Retting is a step used for —",
      ["loosening jute fibres from the stem", "shearing wool", "reeling silk only", "knitting sweaters"], "a",
      "Retting soaks jute stems so fibres can be separated.",
      "Jute processing soak.", bp=BP_HINTS_SCI),
    q("Which fabric choice suits a cold hill station better?",
      ["Light cotton tee only", "Woollen sweater", "Wet jute sack as clothing", "Paper"], "b",
      "Wool traps air and keeps the body warm.",
      "Warm fabric.", bp=BP_HINTS_SCI),
    q("Handloom fabrics are made —",
      ["on looms operated largely by hand/foot power", "only in chemical reactors", "by silkworms directly as shirts", "by magnets"], "a",
      "Handlooms are manually operated weaving devices.",
      "What handloom means.", bp=BP_HINTS_SCI),
    q("Which is plant fibre?",
      ["Silk", "Wool", "Jute", "Nylon"], "c",
      "Jute is a plant stem fibre.",
      "Plant source.", bp=BP_HINTS_SCI),
    q("Burning a cotton thread typically smells like —",
      ["burning paper (plant material)", "burning hair always for cotton", "burning plastic sweet smell always", "no smell ever"], "a",
      "Cotton is cellulose plant fibre and smells like burning paper.",
      "Burn test clue for cotton.", bp=BP_HINTS_SCI),
    q("Burning wool often smells like —",
      ["burning hair/feathers (protein)", "burning paper only", "pure mint", "ozone only"], "a",
      "Wool is protein fibre and smells like burning hair.",
      "Burn test clue for wool.", bp=BP_HINTS_SCI),
    q("Why are jute bags called eco-friendly compared with some plastics?",
      ["Jute is biodegradable plant fibre", "Jute is a metal", "Jute never decomposes", "Jute is pure plastic"], "a",
      "Natural jute can break down more readily than many plastics.",
      "Biodegradable angle.", bp=BP_HINTS_SCI),
    q("Yarn twist makes fibres —",
      ["hold together as a stronger strand", "evaporate", "become vitamins", "turn into iron"], "a",
      "Twisting binds fibres into usable yarn.",
      "Why twist yarn?", bp=BP_HINTS_SCI),
    q("Which occupation is linked to silk?",
      ["Sericulturist", "Astronaut only", "Deep-sea diver only", "Protractor maker only"], "a",
      "Sericulturists rear silkworms.",
      "Silk career word.", bp=BP_HINTS_SCI),
    q("Cotton is preferred for bandages partly because it is —",
      ["soft and absorbent", "completely waterproof plastic", "a metal mesh", "edible protein"], "a",
      "Soft absorbent cotton suits wound care.",
      "Medical cotton property.", bp=BP_HINTS_SCI),
    q("Which step comes first in wool processing among these?",
      ["Shearing", "Weaving a finished coat", "Wearing the sweater", "Dyeing a stitched blazer only"], "a",
      "First the fleece is sheared from the animal.",
      "First wool step.", bp=BP_HINTS_SCI),
    q("Blended fabrics combine —",
      ["two or more types of fibre", "only water and salt", "only metals", "only vitamins"], "a",
      "Blends mix fibres (e.g. cotton-polyester) for useful properties.",
      "What blend means.", bp=BP_HINTS_SCI),
    q("Which tool helps spin yarn by hand traditionally?",
      ["Takli or charkha", "Beaker", "Bar magnet", "Thermometer"], "a",
      "Takli and charkha are traditional spinning devices.",
      "Hand spinning tools.", bp=BP_HINTS_SCI),
    q("Fabric edges may fray because —",
      ["yarns can slip out when not finished", "fabric turns into water", "magnets pull cotton", "vitamins escape"], "a",
      "Unfinished edges let yarns loosen — hence hems/selvedge.",
      "Why edges fray.", bp=BP_HINTS_SCI),
    q("Which is true of knitting?",
      ["It can make stretchy fabrics like socks", "It always needs two perpendicular yarn sheets like weaving", "It grows cotton", "It is evaporation"], "a",
      "Knitted fabrics often stretch — good for socks.",
      "Knitting property.", bp=BP_HINTS_SCI),
    q("India’s history of cotton is notable because —",
      ["cotton weaving has deep traditional roots here", "cotton is a metal ore", "cotton is only synthetic", "cotton comes from sheep"], "a",
      "India has a long tradition of cotton textiles.",
      "Cultural/history note at class level.", bp=BP_HINTS_SCI),
    q("Which fibre is least likely to be called natural?",
      ["Acrylic", "Cotton", "Wool", "Silk"], "a",
      "Acrylic is synthetic.",
      "Spot the synthetic.", bp=BP_HINTS_SCI),
    q("Why sort laundry by fabric type sometimes?",
      ["Different fabrics need different wash/heat care", "All fabrics are identical metals", "Sorting removes vitamins", "It creates iodine"], "a",
      "Wool, cotton and synthetics tolerate heat/agitation differently.",
      "Care difference reason.", bp=BP_HINTS_SCI),
    q("The smallest usable textile building block among these is —",
      ["fibre", "stitched garment", "full loom shed", "market stall"], "a",
      "Fibre is the basic strand; yarn and fabric are built from it.",
      "Smallest unit.", bp=BP_HINTS_SCI),
]

SCI_SEP_A = [
    q("Handpicking is useful when —",
      ["unwanted pieces are large and easy to see", "all particles are identical and invisible", "you need to boil water", "you need a magnet only"], "a",
      "Handpicking removes large, visible impurities by hand.",
      "When handpicking works.", bp=BP_HINTS_SCI),
    q("Threshing separates —",
      ["grain from stalks", "salt from seawater by freezing only", "iron from sand with hands only", "cream by filtering paper"], "a",
      "Threshing beats stalks so grain separates.",
      "Grain harvest separation.", bp=BP_HINTS_SCI),
    q("Winnowing uses —",
      ["wind or blowing air to separate lighter husk", "only magnets", "only filters", "only evaporation pans"], "a",
      "Lighter husk blows away; heavier grain falls.",
      "Wind separation.", bp=BP_HINTS_SCI),
    q("Sieving separates particles based on —",
      ["size", "colour only", "magnetism only", "taste only"], "a",
      "A sieve lets smaller particles pass and holds larger ones.",
      "Sieve property.", bp=BP_HINTS_SCI),
    q("Sedimentation means —",
      ["heavier insoluble solids settle at the bottom of a liquid", "solids fly upward always", "salt disappears forever", "fibres become yarn"], "a",
      "Heavy particles settle when a mixture stands.",
      "Settling down.", bp=BP_HINTS_SCI),
    q("Decantation is —",
      ["pouring off liquid carefully after settling", "boiling metal", "spinning cotton", "measuring angles"], "a",
      "After sedimentation, liquid is poured off the sediment.",
      "Pour after settling.", bp=BP_HINTS_SCI),
    q("Filtration uses a filter to —",
      ["trap insoluble solids and let liquid pass", "separate two gases by colour only", "shear sheep", "weave cloth"], "a",
      "Filter paper/cloth holds residue; filtrate passes.",
      "Filter job.", bp=BP_HINTS_SCI),
    q("Evaporation separates —",
      ["dissolved solid from a solution by turning liquid to vapour", "iron from sand with wind", "husks by handpicking only", "yarn from fibre"], "a",
      "Water evaporates; dissolved salt remains.",
      "Sun/heat on solutions.", bp=BP_HINTS_SCI),
    q("Salt from seawater is obtained mainly by —",
      ["evaporation", "winnowing", "shearing", "knitting"], "a",
      "Seawater is evaporated in pans; salt is left.",
      "Salt pans method.", bp=BP_HINTS_SCI),
    q("A magnet can separate —",
      ["iron filings from sand", "salt from sugar", "oil from water by magnetism alone", "husks from grain by magnetism alone"], "a",
      "Iron is magnetic; sand is not.",
      "Magnetic property use.", bp=BP_HINTS_SCI),
    q("Which mixture can be separated by filtration?",
      ["Chalk powder in water", "Salt fully dissolved in water", "Sugar fully dissolved in water", "Alcohol mixed completely as one phase without solid"], "a",
      "Insoluble chalk is trapped by a filter; dissolved salt/sugar pass with water.",
      "Need undissolved solid for filtration.", bp=BP_HINTS_SCI),
    q("Cream from milk can be separated by —",
      ["centrifugation (or churning principles)", "winnowing husk", "magnetic separation", "sieving with large mesh only"], "a",
      "Centrifugation spins denser and lighter parts apart; cream rises/separates.",
      "Spin separation for milk.", bp=BP_HINTS_SCI),
    q("Which property allows winnowing?",
      ["Difference in weight/heaviness of particles", "Identical weight of all particles", "Only colour of books", "Magnetism of husk"], "a",
      "Heavier grain and lighter husk respond differently to air flow.",
      "Weight difference.", bp=BP_HINTS_SCI),
    q("Insoluble impurities in water can be removed by —",
      ["sedimentation and filtration", "only adding more salt", "weaving", "sericulture"], "a",
      "Settle, then filter to clarify water.",
      "Muddy water cleanup.", bp=BP_HINTS_SCI),
    q("Which method suits separating tea leaves from prepared tea?",
      ["Filtration/straining", "Magnetic separation", "Winnowing on a farm roof only", "Shearing"], "a",
      "A strainer filters tea leaves.",
      "Kitchen filtration.", bp=BP_HINTS_SCI),
    q("Miscible liquids like alcohol and water are harder to separate by —",
      ["simple decantation alone", "a special still/distillation approach in advanced classes", "both a and the need for more than pouring", "handpicking"], "a",
      "They mix uniformly, so pouring off does not separate them; distillation is used at higher levels.",
      "When liquids mix completely.", bp=BP_HINTS_SCI),
    q("Oil and water can be separated because they are —",
      ["immiscible and form layers", "the same liquid", "both magnetic", "both solids"], "a",
      "Oil floats on water as a separate layer and can be skimmed/separated.",
      "Immiscible layers.", bp=BP_HINTS_SCI),
    q("Which is a pure substance among these everyday ideas?",
      ["Distilled water (approx. pure H2O)", "Muddy river water", "Air as a fixed compound", "Trail mix"], "a",
      "Distilled water is essentially pure water; the others are mixtures.",
      "Pure vs mixture.", bp=BP_HINTS_SCI),
    q("Air is best described as —",
      ["a mixture of gases", "a single pure element only", "a fabric", "a vitamin"], "a",
      "Air contains nitrogen, oxygen and other gases mixed.",
      "Air composition type.", bp=BP_HINTS_SCI),
    q("Sieving flour removes —",
      ["larger impurities/lumps", "all dissolved sugar", "magnetic only dust", "water by evaporation"], "a",
      "Lumps and bran bits stay on the sieve.",
      "Kitchen sieving.", bp=BP_HINTS_SCI),
    q("Which method would you choose for iron nails mixed with sawdust?",
      ["Magnet", "Winnowing only", "Evaporation", "Handloom"], "a",
      "A magnet pulls iron nails from sawdust.",
      "Magnetic junk separation.", bp=BP_HINTS_SCI),
    q("Condensation is the change from —",
      ["gas/vapour to liquid", "liquid to solid always named condensation", "solid to fibre", "yarn to fabric"], "a",
      "Vapour cools to liquid in condensation.",
      "Opposite of evaporation.", bp=BP_HINTS_SCI),
    q("Why do we separate substances?",
      ["To get useful components or remove harmful ones", "Only to weave cloth", "Only to name angles", "Never for any reason"], "a",
      "Separation yields useful materials and removes impurities.",
      "Purpose of separation.", bp=BP_HINTS_SCI),
    q("Which pair is a mixture?",
      ["Sand and salt", "Distilled water only", "Pure gold element sample", "Oxygen gas alone as element sample"], "a",
      "Sand + salt is a mixture of two solids.",
      "Spot the mixture.", bp=BP_HINTS_SCI),
]

SCI_SEP_B = [
    q("After sedimentation, the clear liquid above is often called —",
      ["supernatant liquid", "residue solid only", "yarn", "hull"], "a",
      "The clearer liquid above the settled solid is the supernatant.",
      "Name the clear top liquid.", bp=BP_HINTS_SCI),
    q("Residue on filter paper is —",
      ["the solid left behind", "the liquid that passed", "a gas only", "a magnetic field"], "a",
      "Residue is the trapped solid; filtrate is the liquid that passed.",
      "Residue vs filtrate.", bp=BP_HINTS_SCI),
    q("Which separation uses heat and vapour?",
      ["Evaporation", "Handpicking", "Magnetic separation", "Sieving dry sand only"], "a",
      "Evaporation needs heat (or sun) to vapourise liquid.",
      "Heat-driven method.", bp=BP_HINTS_SCI),
    q("Husk is separated from grain mainly by —",
      ["winnowing", "reeling silk", "sericulture", "knitting"], "a",
      "Winnowing blows husk away from grain.",
      "Farm method for husk.", bp=BP_HINTS_SCI),
    q("Which mixture needs more than a magnet?",
      ["Salt dissolved in water", "Iron filings in sand", "Iron pins in rice", "Steel screws in plastic beads"], "a",
      "Salt solution is non-magnetic; evaporation/other methods are needed.",
      "When magnets fail.", bp=BP_HINTS_SCI),
    q("Loading (in water purification talks) helps —",
      ["fine clay settle faster by adding alum etc.", "spin silk", "weave jute", "grow cotton"], "a",
      "Alum helps fine suspended particles clump and settle.",
      "Alum/loading idea.", bp=BP_HINTS_SCI),
    q("Which is insoluble in water?",
      ["Sand", "Salt", "Sugar", "Lemon juice acids that dissolve"], "a",
      "Sand does not dissolve; salt and sugar do.",
      "Spot the insoluble.", bp=BP_HINTS_SCI),
    q("Saturated solution means —",
      ["no more solute dissolves at that temperature", "the beaker is empty", "only gases present", "a type of fabric"], "a",
      "At saturation, added solute remains undissolved.",
      "Define saturated.", bp=BP_HINTS_SCI),
    q("Which method separates butter from curd traditionally?",
      ["Churning", "Magnetic separation", "Sieving with brick mesh", "Ginning"], "a",
      "Churning agitates to separate butter.",
      "Dairy separation.", bp=BP_HINTS_SCI),
    q("Sawdust mixed with iron filings: best first step?",
      ["Use a magnet", "Evaporate with sun", "Winnow as if husk identically always", "Weave them"], "a",
      "Magnet removes iron quickly.",
      "Best tool first.", bp=BP_HINTS_SCI),
    q("Which change is reversible among these separations?",
      ["Dissolving salt then evaporating water to get salt back", "Burning paper to ash", "Cooking an egg hard", "Rusting iron completely as oxide only"], "a",
      "Salt can be recovered by evaporating water — a reversible physical separation path.",
      "Recovering dissolved salt.", bp=BP_HINTS_SCI),
    q("Filtrate is —",
      ["the liquid that passes through the filter", "the solid on the paper only", "a sheep", "a loom"], "a",
      "Filtrate = liquid collected after filtration.",
      "Define filtrate.", bp=BP_HINTS_SCI),
    q("Why does oil float on water?",
      ["Oil is less dense than water", "Oil is denser always", "Oil is magnetic", "Oil is a metal"], "a",
      "Lower density makes oil float as a layer.",
      "Density idea.", bp=BP_HINTS_SCI),
    q("Which apparatus is typical for filtration in the lab?",
      ["Filter paper + funnel", "Charkha", "Protractor", "Handloom"], "a",
      "Funnel and filter paper are standard.",
      "Lab filtration gear.", bp=BP_HINTS_SCI),
    q("Separating colours of ink is an introduction to —",
      ["chromatography (later classes)", "shearing", "ginning", "knitting"], "a",
      "Ink dyes can be separated by chromatography.",
      "Ink travel method name.", bp=BP_HINTS_SCI),
    q("Which is a heterogeneous mixture?",
      ["Sand in water", "Salt completely dissolved in water", "Sugar completely dissolved in water", "Air well mixed as one phase discussion"], "a",
      "Sand in water shows distinct phases/particles — heterogeneous.",
      "See distinct parts.", bp=BP_HINTS_SCI),
    q("Which is a homogeneous mixture?",
      ["Sugar solution", "Sand and iron filings visibly mixed", "Oil floating on water", "Trail mix"], "a",
      "A clear sugar solution is uniform throughout.",
      "Uniform mixture.", bp=BP_HINTS_SCI),
    q("Pebbles from dal can be removed by —",
      ["handpicking", "distillation only", "magnetic separation always", "reeling"], "a",
      "Large pebbles are handpicked from dal.",
      "Kitchen handpicking.", bp=BP_HINTS_SCI),
    q("Which property is used in magnetic separation?",
      ["Magnetism", "Colour only", "Taste only", "Smell only"], "a",
      "Magnetic materials respond to a magnet.",
      "Key property.", bp=BP_HINTS_SCI),
    q("Drying clothes in the sun mainly involves —",
      ["evaporation of water", "sedimentation of cloth", "magnetic drying", "winnowing shirts"], "a",
      "Water in clothes evaporates into air.",
      "Sun drying science.", bp=BP_HINTS_SCI),
    q("Which statement is correct?",
      ["Mixtures can usually be separated by physical methods", "Compounds are separated by winnowing always", "All mixtures are magnetic", "Filtration creates new elements"], "a",
      "Physical methods separate many mixtures without new substances.",
      "Mixtures vs compounds methods.", bp=BP_HINTS_SCI),
    q("To get drinking water from muddy water at a basic level, you might —",
      ["allow settling, then filter (and further purify as needed)", "add more mud", "winnow it", "shear it"], "a",
      "Sedimentation + filtration remove many solids (further purification may still be needed).",
      "Clarify muddy water steps.", bp=BP_HINTS_SCI),
    q("Which mixture is best separated by sieving?",
      ["Pebbles mixed with sand", "Salt dissolved in water", "Alcohol in water", "Cream in milk by sieve mesh only"], "a",
      "Different solid sizes → sieving works.",
      "Size-based solids.", bp=BP_HINTS_SCI),
    q("The solid left after seawater evaporates is mainly —",
      ["salt", "pure oxygen cakes", "cotton fibre", "wool"], "a",
      "Dissolved salts remain after water evaporates.",
      "What stays in the pan?", bp=BP_HINTS_SCI),
]

# Fix awkward option in SCI_FIBRE_A
SCI_FIBRE_A[19] = q(
    "Which fibre is animal in origin?",
    ["Jute", "Cotton", "Wool", "Nylon"],
    "c",
    "Wool is an animal fibre; jute and cotton are plant fibres; nylon is synthetic.",
    "Animal vs plant fibre.",
    bp=BP_HINTS_SCI,
)

# Fix awkward SCI_FIBRE_B strength question
SCI_FIBRE_B[2] = q(
    "Among common natural fibres discussed in class, silk is often noted for its —",
    ["strength and shine", "being a metal", "coming from sheep", "being synthetic polyester"],
    "a",
    "Silk is valued for strength and lustre among natural fibres.",
    "Known qualities of silk.",
    bp=BP_HINTS_SCI,
)

# Fix miscible liquids question to be cleaner
SCI_SEP_A[15] = q(
    "Alcohol mixed completely with water is best separated in later classes by —",
    ["distillation", "handpicking", "winnowing", "magnetic separation"],
    "a",
    "Miscible liquids need distillation (different boiling points), not simple pouring.",
    "Method for mixed liquids.",
    bp=BP_HINTS_SCI,
)

for name, banks in [
    ("ENG_COMP", (ENG_COMP_A, ENG_COMP_B)),
    ("ENG_GRAM", (ENG_GRAM_A, ENG_GRAM_B)),
    ("ENG_VOCAB", (ENG_VOCAB_A, ENG_VOCAB_B)),
    ("SCI_FOOD", (SCI_FOOD_A, SCI_FOOD_B)),
    ("SCI_FIBRE", (SCI_FIBRE_A, SCI_FIBRE_B)),
    ("SCI_SEP", (SCI_SEP_A, SCI_SEP_B)),
]:
    for label, bank in zip("AB", banks):
        assert len(bank) == 24, (name, label, len(bank))
