#!/usr/bin/env python3
"""Ingest Grade 4 English writer files (grade-4-english/chapter-0N.md). Usage: python3 scripts/ingest_g4_english.py"""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).parent))
from ingest_lib import ROOT
from ingest_g8_english import lesson, run

CHAPTERS = [
  dict(src="chapter-01.md", prefix="g4-eng-ch01", file="g4-english-reading.ts", export="g4EnglishReading",
       doc="english-ch01-reading.md",
       meta={"id": "story-spotters", "title": "Story Spotters", "emoji": "🔎",
             "blurb": "Main idea, details & clue words", "topic": "comprehension",
             "paperTopics": ["comprehension", "vocabulary"]},
       lesson=lesson(
         dict(emoji="🔎", title="Hello, story spotter!",
              body=["When we read, we find out what the story is really about.",
                    "The answer is always in the story — go back and check."],
              speak="Hello, story spotter! When we read, we don't just look at the words. We find out what the story is really about.",
              reveal_title="Story spotter tools",
              reveal_speak="Tap each card: main idea, details, order words and new words."),
         [("Main idea", "What is the story mostly about?", "💡"),
          ("Details", "Who, what, where and when", "🧩"),
          ("Order words", "first, next, then, at last", "🔢"),
          ("New words", "Read the words around it to guess", "🔤")],
         dict(title="Find the clues",
              speak="Mohan opened the door. His umbrella was dripping, and his shoes went squish, squish. The story did not say rain, but the clues told us. Squish is a soft, wet sound.",
              steps=["\u201cMohan opened the door. His umbrella was dripping, and his shoes went squish, squish.\u201d",
                     "Dripping umbrella + squishy shoes → it was raining!",
                     "The story never said \u201crain\u201d — the clues told us",
                     "\u201cSquish\u201d = a soft, wet sound"],
              punchline="Clues in the story tell us more than the words say."),
         dict(prompt="\u201cRiya yawned and rubbed her eyes. The moon was high in the sky.\u201d What time is it most likely?",
              options=[("a", "Morning"), ("b", "Noon"), ("c", "Night"), ("d", "Lunch time")],
              answerId="c", why="Yawning, rubbing eyes and a high moon are clues that it is night."),
         ["Super story spotter!", "Main idea first, then details", "Use clues to guess new words",
          "Not sure? Read that part again"])),
  dict(src="chapter-02.md", prefix="g4-eng-ch02", file="g4-english-grammar.ts", export="g4EnglishGrammar",
       doc="english-ch02-grammar.md",
       meta={"id": "word-workshop", "title": "Word Workshop", "emoji": "🛠️",
             "blurb": "Nouns, pronouns, adjectives & verbs", "topic": "grammar",
             "paperTopics": ["grammar", "vocabulary"]},
       lesson=lesson(
         dict(emoji="🛠️", title="Welcome, word worker!",
              body=["Every word has a job.", "Let's meet the team and build sentences together."],
              speak="Hello, word worker! Welcome to the Word Workshop, where we build sentences together. Every word has a job.",
              reveal_title="Meet the word team",
              reveal_speak="Tap each card: nouns, pronouns, adjectives, verbs and articles."),
         [("Nouns", "Naming words: Ravi, school, mango, Delhi", "📛"),
          ("Pronouns", "Take a noun's place: he, she, it, we, they", "🔁"),
          ("Adjectives", "Describing words: a big tiger, a sweet mango", "🎨"),
          ("Verbs", "Doing words that tell when: eat, ate, am eating", "🏃"),
          ("A, an, the", "Use \u201can\u201d before a vowel sound: an apple, an owl", "🔤")],
         dict(title="Spot the jobs",
              speak="Priya is eating an orange under the tree. Priya is a noun. Is eating is a verb happening right now. An orange, because orange begins with a vowel sound. Under tells us where.",
              steps=["\u201cPriya is eating an orange under the tree.\u201d",
                     "Priya → noun (a name)",
                     "is eating → verb, happening right now",
                     "an orange → vowel sound · under → tells where"],
              punchline="Ask: what job is this word doing?"),
         dict(prompt="Choose the right word: \u201cI saw ___ owl in the tree.\u201d",
              options=[("a", "a"), ("b", "an"), ("c", "the two"), ("d", "some")],
              answerId="b", why="Owl begins with a vowel sound, so we use \u201can.\u201d"),
         ["Word worker pro!", "Nouns name, verbs do", "Adjectives describe; pronouns replace",
          "Say it aloud — the right answer sounds right"])),
  dict(src="chapter-03.md", prefix="g4-eng-ch03", file="g4-english-words.ts", export="g4EnglishWords",
       doc="english-ch03-words.md",
       meta={"id": "word-garden", "title": "Word Garden", "emoji": "🌻",
             "blurb": "Opposites, rhymes, homophones & word parts", "topic": "vocabulary",
             "paperTopics": ["vocabulary", "synonyms", "antonyms"]},
       lesson=lesson(
         dict(emoji="🌻", title="Hello, word gardener!",
              body=["Today we grow wonderful words.", "Opposites, look-alikes, rhymes and word parts!"],
              speak="Hello, word gardener! Today we're going to grow some wonderful words.",
              reveal_title="Grow your words",
              reveal_speak="Tap each card: opposites, same meaning, rhymes, homophones and compound words."),
         [("Opposites", "hot ↔ cold", "🔄"),
          ("Same meaning", "big ≈ large", "👯"),
          ("Rhymes", "cat, hat, mat — same end sound", "🎵"),
          ("Homophones", "sun (sky) · son (boy in a family)", "👂"),
          ("Compound words", "rain + bow = rainbow", "🌈")],
         dict(title="Break the word",
              speak="The puppy was fearless. It ran straight into the big puddle! Fearless is fear plus less. Less means without. So fearless means without fear.",
              steps=["\u201cThe puppy was fearless. It ran straight into the big puddle!\u201d",
                     "fearless = fear + less (less = without)",
                     "So fearless means without fear",
                     "Clue: the puppy ran right in — not scared at all!"],
              punchline="un = not · ful = full of · less = without"),
         dict(prompt="What does \u201cunhappy\u201d mean?",
              options=[("a", "Very happy"), ("b", "Not happy"), ("c", "Happy again"), ("d", "Full of happiness")],
              answerId="b", why="\u201cUn\u201d means not, so unhappy means not happy."),
         ["Word garden blooming!", "Opposites, look-alikes & rhymes", "Word parts change meaning",
          "Not sure? Say both answers out loud"])),
]

if __name__ == "__main__":
    src = ROOT / "grade-4-english"
    run([c for c in CHAPTERS if (src / c["src"]).exists()], src, 4)
